import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "A11y Scanner - Free Online Accessibility Checker Tool | IconVault",
    metaDescription: "Paste HTML and scan for missing alt text, empty links and buttons, unlabeled inputs, heading order and contrast issues. Free, 100% in your browser.",
    about: [
      "**IconVault**'s **A11y Scanner** runs a **static accessibility scan** on HTML you paste in. It flags the most common real-world issues: **missing alt text** on images, **empty links and buttons**, **unlabeled form inputs**, a missing **lang attribute**, **heading order** problems, **duplicate ids** and risky inline **color contrast**, each grouped by severity with counts and element descriptions.",
      "The scan is instant and runs **100% in your browser**, so your markup is never uploaded or stored. It is **free** to use with no signup. Be honest about its limits: it checks static markup only and does not replace tools like axe or Lighthouse, keyboard walkthroughs or testing with an actual **screen reader**."
    ],
    faqs: [
      { q: "How do I use the A11y Scanner?", a: "Paste an HTML snippet or a full page of markup into the editor and run the scan. You get a list of errors and warnings with counts and short descriptions of the offending elements, which you can then fix in your own code." },
      { q: "What exactly does it check?", a: "It checks images for missing or empty alt text, links and buttons for accessible names, form inputs for associated labels, the html element for a lang attribute, heading levels for skipped or out-of-order headings, duplicate id attributes, and basic inline color contrast." },
      { q: "Does it replace axe DevTools or Lighthouse?", a: "No. Those tools analyze a live rendered page including ARIA states, focus management and dynamic content. This scanner is a fast static pre-check for markup you are writing or reviewing, best used alongside a full audit." },
      { q: "Is my HTML sent to a server?", a: "No. Parsing and every check happen locally in your browser. Nothing is uploaded, logged or stored, so you can safely scan proprietary or unreleased markup." },
      { q: "Can it scan a live URL?", a: "Not directly. Copy the page source or the component markup you want to check and paste it in. For live-page audits use a browser extension based tool." },
      { q: "Why did it flag my decorative image?", a: "Decorative images should carry an empty alt attribute (alt=\"\") so screen readers skip them. If the image adds no information, leave alt empty rather than describing it." }
    ],
    tags: [
      "accessibility checker",
      "a11y scanner",
      "html accessibility checker",
      "check html for accessibility issues",
      "missing alt text checker",
      "find images without alt text",
      "empty link checker",
      "empty button checker",
      "unlabeled input checker",
      "form label accessibility check",
      "heading order checker",
      "h1 h2 heading hierarchy test",
      "duplicate id checker html",
      "missing lang attribute checker",
      "inline style contrast checker",
      "wcag html validator",
      "static accessibility scan",
      "accessibility audit tool free",
      "free a11y checker online",
      "paste html accessibility test",
      "website accessibility scanner",
      "webpage a11y audit",
      "screen reader issue finder",
      "keyboard accessibility basics checker",
      "aria issue checker",
      "html code accessibility review",
      "frontend accessibility testing tool",
      "developer accessibility checker",
      "pre deploy accessibility check",
      "qa accessibility checklist tool",
      "html semantic checker",
      "check alt attributes in bulk",
      "image alt text audit",
      "link text accessibility check",
      "button accessible name checker",
      "input label association test",
      "html lang attribute test",
      "page title accessibility check",
      "skip link checker",
      "landmark roles checker",
      "table header accessibility check",
      "iframe title checker",
      "video captions reminder",
      "decorative image alt check",
      "redundant alt text check",
      "focus order basics",
      "color contrast in html scan",
      "accessibility linter online",
      "html a11y linter",
      "free alternative to axe devtools",
      "browser based accessibility tester",
      "no install accessibility checker",
      "private accessibility scan",
      "client side a11y test",
      "instant html accessibility report"
    ],
  };

export default seo;
