import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Contrast Grid - Free Online WCAG Contrast Checker Tool | IconVault",
    metaDescription: "Test every foreground and background pair in one matrix with WCAG ratios, AA and AAA badges and CSV export. Free, in your browser.",
    about: [
      "**IconVault**'s **Contrast Grid** checks the **color contrast** of your entire palette in one view. Add your **foreground** and **background** colors to see a live **contrast ratio matrix** where each cell shows the exact **WCAG 2.1 ratio** with a clear **AA**, **AAA**, **AA-large** or **Fail** badge, so failing pairs stand out instantly instead of requiring one-by-one checks.",
      "Ratios are computed from **relative luminance** exactly as **WCAG 2.1** defines it (**4.5:1** for normal text, **3:1** for large text, **7:1** for AAA), and everything runs **fully in your browser** with nothing uploaded. It is **free** to try (repeated use may ask for Pro), and you can export the matrix as **CSV** for design reviews and audit reports."
    ],
    faqs: [
      { q: "What is a contrast grid?", a: "A contrast grid is a matrix that compares every foreground color against every background color in a palette and shows the WCAG contrast ratio for each pair, so you can see at a glance which combinations are readable and which fail." },
      { q: "What contrast ratio do I need to pass WCAG AA?", a: "Normal text needs at least 4.5:1 and large text (bold text around 18.66px and up, or 24px and up) needs at least 3:1. AAA requires 7:1 for normal text and 4.5:1 for large text. The grid labels each pair with the highest level it meets." },
      { q: "Does this replace an automated accessibility audit?", a: "No. The Contrast Grid checks color contrast only. A full audit also covers keyboard navigation, screen reader behavior, focus order, form labels and motion, so treat this as one useful check inside a broader accessibility review." },
      { q: "Is my palette uploaded anywhere?", a: "No. Every ratio is computed locally in your browser with JavaScript. Your colors never leave your device, so it is safe to use with client or unreleased brand palettes." },
      { q: "How do I export the results?", a: "Use the export button to download the full matrix as CSV, including each pair's ratio and its AA/AAA verdict, which you can attach to design reviews, handoffs or compliance documentation." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "wcag contrast checker",
      "contrast ratio calculator",
      "color contrast checker",
      "check color contrast online",
      "foreground background contrast",
      "text color contrast tester",
      "wcag 2.1 contrast ratio",
      "aa aaa contrast checker",
      "4.5:1 contrast ratio checker",
      "7:1 contrast ratio aaa",
      "large text contrast 3:1",
      "accessible color combinations",
      "find accessible color pairs",
      "color palette accessibility test",
      "test all color combinations at once",
      "contrast matrix tool",
      "contrast grid generator",
      "online contrast checker free",
      "free wcag contrast checker",
      "web accessibility color checker",
      "ui color contrast check",
      "design system contrast testing",
      "dark mode contrast checker",
      "button text contrast checker",
      "link color contrast test",
      "badge color contrast wcag",
      "chart color contrast accessibility",
      "contrast checker csv export",
      "export contrast report csv",
      "relative luminance calculator",
      "how to check color contrast",
      "what is a good contrast ratio for text",
      "wcag aa color requirements",
      "wcag aaa color requirements",
      "does my website pass wcag contrast",
      "color contrast compliance checker",
      "accessible text on colored background",
      "white text on color background contrast",
      "black text contrast ratio",
      "brand palette accessibility audit",
      "check logo color contrast",
      "website color accessibility test",
      "app color contrast checker",
      "figma contrast checker alternative",
      "tailwind color contrast check",
      "material design contrast checker",
      "bootstrap color contrast",
      "css color contrast tester",
      "hex color contrast calculator",
      "two colors contrast ratio",
      "multiple colors contrast matrix",
      "batch contrast checker",
      "color accessibility checker online",
      "readable text color finder",
      "pick accessible text color"
    ],
  };

export default seo;
