import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "AbortSignal Playground - Free Online Tool | IconVault",
    metaDescription: "Learn AbortController hands-on: cancel a slow fetch, try AbortSignal.timeout and race signals with AbortSignal.any. Free, runs in your browser.",
    about: [
      "**IconVault**'s **AbortSignal Playground** teaches the AbortController API by letting you run it. Cancel a real slow fetch mid-flight, watch AbortSignal.timeout() kill a request automatically, and race two controllers with AbortSignal.any(), all with a timestamped event log showing exactly what happens. It is free and runs fully in your browser.",
      "**Abort signals** are how modern JavaScript cancels async work: fetch requests, event listeners, streams and more. Instead of reading docs, you press buttons and see promises reject with **AbortError** or **TimeoutError** in real time, including how **custom abort reasons** propagate. Every demo ships with a copyable code snippet you can drop into your own projects."
    ],
    faqs: [
      { q: "What is AbortController used for?", a: "It gives you a signal object you can pass to fetch(), addEventListener() and other APIs. Calling controller.abort() cancels the associated work, which is essential for cleaning up on component unmount, user cancellation, or timeouts." },
      { q: "What is the difference between AbortError and TimeoutError?", a: "A manual controller.abort() rejects fetch with an AbortError. AbortSignal.timeout(ms) is a newer static method that auto-aborts and rejects with a TimeoutError instead, so you can tell timeouts apart from user cancellations." },
      { q: "What does AbortSignal.any() do?", a: "It combines multiple signals into one that aborts when ANY of the sources abort. The classic pattern is racing a user-cancel signal against AbortSignal.timeout(10000) so a request dies on whichever happens first." },
      { q: "Can I pass a reason to abort()?", a: "Yes. controller.abort(myReason) sets signal.reason, and the fetch rejection wraps it. The playground demonstrates aborting with both a string and an Error so you can see the difference in the log." },
      { q: "Does aborting fetch stop the server work?", a: "It closes the client connection, which most servers treat as a client disconnect. The server may or may not stop processing, so treat abort as best-effort cancellation, not a guarantee." },
      { q: "Do these demos hit a real server?", a: "Yes, the fetch demos call httpbin.org delay endpoints so you experience genuine network timing. The abort logic itself is pure browser API and works offline." }
    ],
    tags: [
      "abortsignal playground",
      "abortcontroller tutorial",
      "abortcontroller fetch cancel",
      "abortsignal timeout",
      "abortsignal.any example",
      "javascript abort fetch",
      "cancel fetch request js",
      "aborterror vs timeouterror",
      "abortcontroller example",
      "how to cancel fetch",
      "fetch abort signal",
      "abortcontroller react cleanup",
      "cancel fetch on unmount",
      "javascript cancellation token",
      "abort signal reason",
      "controller.abort reason",
      "fetch with timeout javascript",
      "abortsignal.timeout browser support",
      "race abort signals",
      "combine abort signals",
      "abortcontroller addeventlistener signal",
      "remove event listener abort signal",
      "abortcontroller streams",
      "cancel readable stream",
      "javascript abort async task",
      "abortsignal playground free",
      "learn abortcontroller interactive",
      "abortcontroller mdn example",
      "fetch cancellation demo",
      "timeout fetch request js",
      "promise cancellation javascript",
      "abortcontroller typescript",
      "signal aborted check",
      "throwIfAborted example",
      "abortsignal aborted property",
      "what is abortcontroller",
      "abortcontroller vs axios canceltoken",
      "cancel axios vs fetch abort",
      "abortsignal any browser support",
      "abortcontroller multiple fetches",
      "abort all fetches",
      "javascript timeout pattern",
      "fetch timeout without library",
      "abortcontroller best practices",
      "when to use abortcontroller",
      "abortsignal in event listener options",
      "passive once signal addeventlistener",
      "abortcontroller memory leak",
      "cancel pending requests js",
      "abortcontroller fetch cancel example online"
    ],
  };

export default seo;
