import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Add Watermark to Photo - Free Online Tool | IconVault",
    metaDescription: "Stamp text or a logo watermark onto any photo online. Free, private, in-browser watermarker with live preview.",
    about: [
      "**IconVault**'s **Add Watermark** tool protects your photos with a text or **logo stamp**. Pick from 8 fonts, set **size, color and opacity**, choose any of 9 **position presets**, and even rotate the mark, all with a live preview. Everything runs **free** and **browser-private**, your photos never leave your device.",
      "A transparent PNG logo blends perfectly, and JPG or PNG export keeps the result ready to share. **Pro** members get unlimited use with no trial limits.",
    ],
    faqs: [
      { q: "How do I add a text watermark to a photo?", a: "Drop your photo into the tool, type your name, choose a font, size, color and opacity, pick a position, then download. The preview updates live." },
      { q: "Can I use my own logo as a watermark?", a: "Yes. Switch to Logo type, upload your logo (a PNG with transparency works best), then adjust size, opacity and position." },
      { q: "Where should I place a watermark?", a: "Bottom center or bottom right are the classic spots. Use one of the 9 position presets and the margin slider to fine-tune the placement." },
      { q: "Can I rotate the watermark?", a: "Yes. The rotation slider tilts the watermark up to 45 degrees in either direction for a diagonal stamp look." },
      { q: "Is my photo uploaded anywhere?", a: "No. Watermarking happens entirely in your browser, so your photos and your logo stay private." },
      { q: "Is the watermark tool free?", a: "Yes, free users get a generous number of uses. Pro members get unlimited use of every tool." },
    ],
    tags: [ "add watermark to photo", "watermark image online", "photo watermarker free", "add logo to picture", "text watermark maker", "stamp photo online", "protect photos with watermark", "watermark png image", "add copyright text to photo", "logo overlay on image", "photo branding tool", "watermark maker no signup", "add signature to photo", "image watermark generator", "free watermark tool", "watermark jpg online", "transparent logo watermark", "batch watermark alternative", "photo credit stamp", "watermark position presets" ,
      "photo watermark software",
      "add watermark to photos online free",
      "bulk watermark app",
      "image watermarking tool",
      "put watermark on photos",
      "copyright watermark generator",
      "photo watermark for instagram",
      "add watermark to pictures",
      "image branding watermark",
      "photo watermark creator",
      "add text logo to photos",
      "watermark batch photos",
      "online photo watermarker",
      "watermark photo online free no signup",
      "add watermark to png images",
      "how to watermark photos",
      "photography watermark maker",
      "add copyright watermark to images",
      "photo watermark online tool",
      "watermark images in bulk",
      "add logo watermark to pictures",
      "image watermark free online",
      "watermark maker app",
      "add watermark to photo online free",
      "photo watermark generator free",
      "stamp logo on photo",
      "watermarking photos for photographers",
      "add watermark to jpg photo",
      "watermark image online free no signup",
      "how to add watermark to photo",
      "photo watermark template",
      "protect images with watermark",
      "watermark photo batch online",
      "add branding to product photos",
      "image watermark editor",
      "watermark picture maker",
      "add digital watermark to image",
      "photo watermark placement",
      "watermarking tool free",
      "watermark photos for portfolio"],
  };

export default seo;
