import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Add Border to Photo - Free Online Tool | IconVault",
    metaDescription: "Add a colored frame to any photo online. Adjustable width, rounded corners and drop shadow. Free and private.",
    about: [
      "**IconVault**'s **Add Border** tool puts a clean frame around any photo in seconds. Set the **width in pixels or percent**, pick any color or go **transparent**, round the corners, or add a soft **drop shadow**. Everything runs **free** and **browser-private**, your photo never leaves your device.",
      "The tool is smart about formats: it exports as **PNG automatically** whenever transparency is needed (transparent border, rounded corners or shadow), otherwise as high-quality JPG. **Pro** members get unlimited use with no trial limits.",
    ],
    faqs: [
      { q: "How do I add a border to a photo online?", a: "Drop your photo into the Add Border tool, set the width, pick a color, then download. You can also round the corners or add a drop shadow." },
      { q: "Can I make the border transparent?", a: "Yes. Click the Transparent button and the border area becomes fully transparent, exported as a PNG." },
      { q: "What is the difference between px and percent width?", a: "Pixel width is fixed, while percent width scales relative to the shortest side of your photo, so the frame stays proportional on any image size." },
      { q: "Why did my image download as PNG instead of JPG?", a: "Rounded corners, transparent borders and drop shadows need transparency, which JPG cannot store, so the tool switches to PNG automatically." },
      { q: "Is my photo uploaded to a server?", a: "Never. All processing happens in your browser on your own device." },
      { q: "Is adding a border free?", a: "Yes, free users get a generous number of uses per tool. Pro members get unlimited use." },
    ],
    tags: [ "add border to photo", "add frame to image online", "photo border maker", "add white border to picture", "image frame generator", "rounded border photo", "add colored border to image", "picture border online free", "add drop shadow to image", "photo frame maker online", "border around image", "add transparent border", "instagram white border photo", "frame my photo online", "add border to png", "add border to jpg", "photo border editor", "image padding border", "fancy photo frame online", "border maker for pictures" ,
      "add border to image",
      "photo frame online",
      "picture frame generator",
      "add border online free",
      "image border maker",
      "photo border online",
      "frame photo online free",
      "add black border to photo",
      "polaroid frame maker",
      "add polaroid border",
      "vintage photo frame",
      "square photo border",
      "thick border photo",
      "thin border image",
      "add outline to image",
      "image outline generator",
      "photo edge border",
      "picture edge frame",
      "canvas border photo",
      "add margin to image",
      "image margin maker",
      "white frame photo online",
      "black frame photo",
      "add gold border photo",
      "decorative photo border",
      "ornate frame generator",
      "simple photo frame online",
      "minimal photo border",
      "add border to profile picture",
      "profile pic border maker",
      "facebook profile frame",
      "add border to screenshot",
      "screenshot frame border",
      "certificate border maker",
      "document border frame",
      "add border to webp",
      "add border to gif",
      "animated border photo",
      "neon border photo",
      "gradient border image"],
  };

export default seo;
