import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "AES Encryptor - Free Online Text Encryption Tool | IconVault",
    metaDescription: "Encrypt and decrypt text with AES-256-GCM and PBKDF2 key derivation, with a fresh random salt and IV every time. Free, fully in your browser.",
    about: [
      "**IconVault**'s **AES Encryptor** protects text with **AES-256-GCM**, a modern **authenticated encryption** standard. Your passphrase is turned into a key with **PBKDF2-SHA-256** at **310,000 iterations**, and every operation generates a fresh random **16-byte salt** and **12-byte IV**, packed together with the ciphertext in one Base64 payload you can store or share.",
      "All cryptography runs through the browser's **Web Crypto API**, so your plaintext and passphrase **never leave your device** and nothing is uploaded. It is **free** to use with no signup. The honest caveat: security depends on your **passphrase strength**, so use a long unique passphrase, and keep a backup of anything important because a forgotten passphrase cannot be recovered."
    ],
    faqs: [
      { q: "What algorithm does this tool use?", a: "AES-256 in GCM mode for encryption, with the key derived from your passphrase using PBKDF2 with SHA-256 and 310,000 iterations. GCM is authenticated, so tampered ciphertext is detected on decryption instead of silently producing garbage." },
      { q: "Is my text sent to a server?", a: "No. Encryption and decryption run entirely in your browser using the Web Crypto API. Your plaintext, passphrase and keys never leave your device." },
      { q: "Why does the same text encrypt differently each time?", a: "Each encryption uses a fresh random salt and IV, which is correct cryptographic practice. It means identical inputs produce different outputs, so attackers cannot tell when two messages are the same." },
      { q: "What happens if I forget my passphrase?", a: "The data cannot be recovered. There is no backdoor, no reset and no key escrow, so store your passphrase somewhere safe before encrypting anything important." },
      { q: "Is AES-256-GCM considered secure?", a: "Yes. It is a widely deployed modern standard used by TLS, messaging apps and disk encryption. Practical security then depends on your passphrase: a short or common passphrase can be brute-forced regardless of the algorithm." },
      { q: "Can I use this to store passwords?", a: "It can encrypt text containing secrets, but for password storage in applications, one-way hashing (bcrypt, Argon2) is the correct approach, not reversible encryption. Use this tool for messages, notes and config secrets you need to read back." }
    ],
    tags: [
      "aes encryptor",
      "aes encryption online",
      "encrypt text online",
      "aes 256 encrypt",
      "aes 256 gcm encryptor",
      "decrypt aes online",
      "text encryption tool",
      "encrypt message with password",
      "password based encryption",
      "pbkdf2 aes online",
      "webcrypto aes gcm",
      "client side encryption tool",
      "browser text encryptor",
      "free encryption tool online",
      "encrypt notes online",
      "secure text encryptor",
      "encrypt sensitive text",
      "decrypt text with passphrase",
      "aes passphrase encryption",
      "online cipher tool",
      "symmetric encryption online",
      "encrypt decrypt tool free",
      "no signup encryption",
      "private text encryption",
      "encrypt without server",
      "base64 aes payload",
      "how to encrypt text with aes 256",
      "how to decrypt aes 256 gcm",
      "is aes 256 gcm secure",
      "aes gcm vs cbc which is better",
      "what is pbkdf2 key derivation",
      "how many pbkdf2 iterations",
      "can aes encrypted text be cracked",
      "encrypt text before sending email",
      "share encrypted message safely",
      "encrypt api keys for storage",
      "encrypt config secrets browser",
      "javascript aes encryption online",
      "web crypto api encrypt example",
      "aes 256 online free no login",
      "best free text encryption tool",
      "encrypt diary entries online",
      "password protect text online",
      "lock text with password",
      "unlock encrypted text online",
      "aes encryption for developers",
      "test aes gcm implementation",
      "generate aes encrypted payload",
      "random iv salt encryption",
      "authenticated encryption online",
      "256 bit encryption online",
      "military grade encryption text",
      "encrypt clipboard text",
      "secure note encryption browser",
      "zero knowledge text encryption",
      "encrypt string online free",
      "decrypt string online free",
      "aes online tool with salt"
    ],
  };

export default seo;
