import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "AI Cost Calculator - Free Online Pricing Calculator Tool | IconVault",
    metaDescription: "Estimate AI API spend from per-1M-token prices for GPT-4o, Claude, Gemini, Grok, DeepSeek and more. Free calculator, runs in your browser.",
    about: [
      "**IconVault**'s **AI Cost Calculator** turns token usage into dollars. Pick from **16 popular models**, including OpenAI's **GPT-4o**, **GPT-4.1**, **o3** and **o4-mini**, Anthropic's **Claude Sonnet 4**, **Opus 4** and **Haiku 3.5**, Google's **Gemini 2.5 Pro and Flash**, xAI's **Grok 3**, **DeepSeek V3**, **Mistral Large** and hosted **Llama 3.3**, then enter your **input and output tokens** to see the estimated cost broken down per side.",
      "It is **free** and runs **fully in your browser** with nothing sent anywhere. Two honest caveats: listed **prices change often**, so verify against the provider before budgeting, and token counts are estimates because **tokenizers differ** between models (roughly 4 characters per token for English). Cached tokens, batch discounts and fine-tuning are not modeled."
    ],
    faqs: [
      { q: "How is AI API cost calculated?", a: "Cost equals input tokens times the input price per million plus output tokens times the output price per million. This calculator applies each model's listed per-1M-token rates to the volumes you enter and shows the split." },
      { q: "Which models are included?", a: "Sixteen models across OpenAI, Anthropic, Google, xAI, DeepSeek, Mistral and Meta (hosted Llama), from flagship models like GPT-4o and Claude Opus 4 down to budget options like GPT-4o mini, Gemini 2.0 Flash and DeepSeek V3." },
      { q: "Are the prices current?", a: "Prices were correct when the tool was built but providers change them often, sometimes with little notice. Treat the result as a planning estimate and confirm the live price on the provider's pricing page before committing to a budget." },
      { q: "How do I estimate my token usage?", a: "A rough rule is about 4 characters of English per token, so 1,000 tokens is roughly 750 words. For accuracy, count tokens with the provider's tokenizer on a sample of your real prompts and scale up to your expected request volume." },
      { q: "Does it account for cached tokens or batch discounts?", a: "No. Prompt caching, batch API discounts and volume tiers can cut bills significantly but vary by provider and workload, so the calculator gives you the straightforward list-price estimate to plan from." },
      { q: "Is my usage data stored?", a: "No. The calculation happens locally in your browser and your numbers are never uploaded or logged." }
    ],
    tags: [
      "ai cost calculator",
      "ai api cost calculator",
      "llm cost calculator",
      "openai api cost calculator",
      "gpt-4o api pricing calculator",
      "claude api cost calculator",
      "gemini api pricing calculator",
      "calculate llm api cost",
      "token cost calculator",
      "cost per 1m tokens",
      "ai api pricing comparison",
      "compare ai model prices",
      "how much does gpt-4o api cost",
      "how much does claude api cost",
      "gpt-4o mini vs gpt-4o cost",
      "cheapest llm api",
      "ai token pricing chart",
      "input output token pricing",
      "estimate openai monthly cost",
      "ai budget planner",
      "llm spend estimator",
      "ai api bill calculator",
      "tokens to dollars calculator",
      "how many tokens per dollar",
      "ai cost per 1000 requests",
      "chatbot operating cost calculator",
      "rag pipeline cost estimate",
      "ai agent cost calculator",
      "deepseek api cost calculator",
      "grok api pricing",
      "mistral api cost",
      "llama api pricing hosted",
      "o3 api cost",
      "gemini flash vs pro cost",
      "claude opus 4 pricing",
      "ai pricing calculator free",
      "free ai cost estimator online",
      "startup ai cost planning",
      "how to budget for ai api",
      "reduce llm api costs",
      "ai cost per user calculator",
      "saas ai feature cost",
      "openai pricing explained",
      "anthropic pricing explained",
      "google ai pricing explained",
      "per token pricing calculator",
      "million tokens cost",
      "ai api cost formula",
      "is ai api expensive",
      "ai cost comparison table",
      "llm price tracker",
      "gpt-4.1 pricing",
      "claude sonnet 4 cost",
      "gemini 2.5 pro pricing"
    ],
  };

export default seo;
