import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Alt Text Helper - Free Online Writing Tool | IconVault",
    metaDescription: "Draft better image alt text with live feedback on length, redundant phrases and keyword stuffing, plus decorative-image guidance. Free.",
    about: [
      "**IconVault**'s **Alt Text Helper** helps you write **image alt text** that actually works for **screen reader** users. Type your draft and get instant, specific feedback: whether the length sits in the **125-character sweet spot**, whether it opens with redundant phrases like **\"image of\"** or **\"photo of\"**, and whether it drifts into **keyword stuffing**. A **decorative-image** toggle guides you to the correct empty **alt=\"\"** when the image adds no information.",
      "It is **free** and runs **fully in your browser**, so your drafts never leave your device. The honest limit: these are **heuristic checks**, not AI image recognition, so the tool cannot see your image. Always read your alt text back against the actual picture and ask whether a listener would understand what matters in it."
    ],
    faqs: [
      { q: "How long should alt text be?", a: "Aim for about 125 characters or fewer. Most screen readers start cutting off or chunking announcements around 125 to 150 characters, so concise descriptions get heard in full." },
      { q: "What phrases should I avoid in alt text?", a: "Skip redundant openers like image of, picture of, photo of or graphic of, since screen readers already announce the element as an image. Start directly with what the image shows." },
      { q: "When should alt text be empty?", a: "When the image is purely decorative and adds no information or function, use alt=\"\" so screen readers skip it. If the image conveys meaning, links somewhere, or is a chart or diagram, it needs a real description." },
      { q: "Does the tool write the alt text for me?", a: "No. You write the draft and the helper critiques it: length, redundant phrasing, stuffing and decorative handling. That keeps you in control of describing what actually matters in the image." },
      { q: "Does good alt text help SEO?", a: "It can. Search engines use alt text to understand images, which helps image search visibility. But write for humans first: keyword-stuffed alt text hurts screen reader users and can look spammy to search engines too." },
      { q: "Is my draft uploaded anywhere?", a: "No. The analysis runs entirely in your browser. Nothing you type is sent to a server or stored." }
    ],
    tags: [
      "alt text helper",
      "alt text checker",
      "image alt text checker",
      "alt text length checker",
      "how to write alt text",
      "alt text best practices",
      "alt text examples",
      "good alt text examples",
      "what is alt text",
      "why is alt text important",
      "alt text for accessibility",
      "wcag alt text requirements",
      "decorative image alt text",
      "empty alt attribute",
      "when to use empty alt",
      "alt text 125 characters",
      "how long should alt text be",
      "avoid image of in alt text",
      "redundant alt text phrases",
      "keyword stuffing alt text",
      "alt text seo",
      "does alt text help seo",
      "write alt text for images",
      "alt text writing tool",
      "improve image alt text",
      "alt text feedback tool",
      "alt text linter",
      "alt text quality checker",
      "audit alt text website",
      "find missing alt text",
      "screen reader alt text tips",
      "how screen readers read alt text",
      "alt text for charts",
      "alt text for logos",
      "alt text for icons",
      "alt text for infographics",
      "alt text for social media",
      "instagram alt text tips",
      "twitter alt text guide",
      "wordpress alt text",
      "shopify product image alt text",
      "ecommerce alt text best practices",
      "blog image alt text",
      "hero image alt text",
      "background image alt text",
      "alt text vs title attribute",
      "alt text vs caption",
      "complex image description",
      "free alt text tool",
      "online alt text checker free",
      "accessibility writing assistant",
      "inclusive design writing tool",
      "alt text for beginners"
    ],
  };

export default seo;
