import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "API Mock Generator - Free Online Mock Data Generator Tool | IconVault",
    metaDescription: "Design a field schema and generate realistic mock data as JSON, CSV or SQL with a seeded random generator. Free, runs in your browser.",
    about: [
      "**IconVault**'s **API Mock Generator** creates **realistic fake data** for development and testing. Design a **schema** from typed fields, including **full names**, **emails**, **phones**, **UUIDs**, **integers**, **floats**, **booleans**, **dates**, **lorem text**, **hex colors**, **IP addresses** and **URLs**, choose how many rows you need, and generate a full dataset in one click, exportable as **JSON**, **CSV** or **SQL insert statements**.",
      "Generation uses a **seeded random generator**, so the same seed always reproduces the same dataset, which is ideal for repeatable tests and shared fixtures. Everything runs **100% client-side** with nothing uploaded, and it is **free** to use. The honest boundary: this is synthetic data for **dev, QA and demos**, not real personal data and not for production use."
    ],
    faqs: [
      { q: "What formats can I export?", a: "JSON arrays, CSV files and SQL INSERT statements, so the same generated dataset can feed a frontend prototype, a spreadsheet or a database seed script." },
      { q: "Is the generated data reproducible?", a: "Yes. The generator is seeded, so entering the same seed value regenerates the exact same rows. That makes test fixtures deterministic and shareable with your team." },
      { q: "What field types are supported?", a: "Full and first names, emails, phone numbers, UUIDs, integers, floats, booleans, dates, ISO dates, lorem words, sentences, hex colors, IP addresses and URLs, each with sensible realistic output." },
      { q: "Can I generate large datasets for load testing?", a: "Yes, you can generate thousands of rows for seeding databases or stress-testing imports. Very large generations happen in your browser tab, so extremely big datasets may take a moment." },
      { q: "Is my schema uploaded anywhere?", a: "No. Schema design and data generation both happen locally in your browser. Nothing is sent to a server, stored or logged." },
      { q: "Does the mock data contain real personal information?", a: "No. Names, emails, phones and addresses are randomly assembled from built-in lists and are entirely fictional. Never paste real user data into a mock generator, here or anywhere else." }
    ],
    tags: [
      "api mock generator",
      "mock data generator",
      "generate mock json",
      "fake data generator",
      "json mock data generator",
      "csv mock data",
      "sql mock data generator",
      "seeded random data generator",
      "reproducible test data",
      "fake api response generator",
      "rest api mock data",
      "generate test users json",
      "random user generator json",
      "fake email generator list",
      "uuid generator bulk",
      "random name generator json",
      "lorem ipsum json generator",
      "test data generator online",
      "developer test data tool",
      "frontend mock data",
      "prototype with fake data",
      "seed database with fake data",
      "sql insert generator",
      "generate insert statements",
      "csv test file generator",
      "json placeholder alternative",
      "mockaroo alternative free",
      "free mock data tool",
      "no signup mock generator",
      "client side data generator",
      "javascript mock data",
      "react mock api data",
      "unit test data generator",
      "integration test fixtures",
      "generate 1000 rows csv",
      "bulk fake data",
      "random date generator",
      "random phone number generator",
      "random ip address generator",
      "fake address generator json",
      "boolean random generator",
      "random float generator",
      "data schema designer",
      "define fields generate data",
      "api development tools free",
      "backend testing tools",
      "qa test data",
      "demo data generator",
      "sample dataset creator",
      "json array generator",
      "realistic fake data",
      "deterministic random generator",
      "shareable mock dataset"
    ],
  };

export default seo;
