import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "App Icon Generator - Free Online Tool | IconVault",
    metaDescription: "Generate a complete iOS + Android app icon package from one image, with site.webmanifest, in seconds. Free, no signup.",
    about: [
      "**IconVault**'s **App Icon Generator** turns one square artwork file into the full icon package your app needs: every required iOS size from 180px down to 29px plus the 1024px App Store icon, Android launcher sizes from 192px down to 48px, and a maskable 512px icon for adaptive launchers. It even writes a **site.webmanifest** with your app name and the icon list, so a PWA is ready to drop in.",
      "Everything runs **100% in your browser**: your artwork never leaves your device. Tune padding, pick a background color or keep transparency, name your app, and download a single ZIP with organized ios/, android/ folders. **Free** to use with a daily trial, and Pro users get unlimited generations.",
    ],
    faqs: [
      { q: "What sizes does the App Icon Generator create?", a: "The ZIP contains the full iOS set (1024, 180, 167, 152, 120, 87, 80, 60, 58, 40, 29px), Android launcher sizes (192, 144, 96, 72, 48px), and a 512px maskable icon with a safe-zone aware full-bleed render." },
      { q: "What is the site.webmanifest file for?", a: "It is the web app manifest for PWAs. The generator fills it with your app name and every Android icon entry (including the maskable one), so you can reference it from your site's head tag and get installable app behavior." },
      { q: "What image should I upload?", a: "A square PNG at 1024x1024 gives the sharpest results, but any square-ish image works. The tool center-fits your artwork into each size, so logos with some breathing room scale down cleanest." },
      { q: "Can I use a transparent background?", a: "Yes. Enable the Transparent option to keep alpha. Note that iOS icons traditionally ship with a filled background, so a solid color is the safer default for App Store submission." },
      { q: "Do my files get uploaded to a server?", a: "No. All rendering happens locally in your browser with canvas and JSZip. Your artwork never leaves your device." },
      { q: "How many icon packages can I generate for free?", a: "The free trial includes a set number of generations per day. IconVault Pro removes the limit for unlimited packages plus all other tools." },
    ],
    tags: [ "app icon generator", "ios icon sizes", "android launcher icon generator", "generate app icons online", "site.webmanifest generator", "maskable icon generator", "pwa icon generator", "app store icon maker", "1024x1024 icon generator", "favicon and app icon set", "adaptive icon generator", "iphone icon sizes list", "android icon sizes dp", "create icons for app", "icon package zip", "pwa manifest icons", "app icon maker free", "generate icons from image", "mobile app icon sizes", "web app manifest generator" ,
      "app icon sizes generator",
      "make app icon online",
      "app icon generator free online",
      "ios app icon generator",
      "android app icon maker",
      "app icon designer online",
      "generate app icons from image",
      "mobile app icon generator",
      "app icon maker tool",
      "create app icons online free",
      "app icon template generator",
      "ios icon pack generator",
      "android adaptive icon",
      "app icon sizes ios android",
      "app icon 512x512",
      "app icon 192x192",
      "favicon app icons",
      "app icon exporter",
      "convert logo to app icon",
      "app icon asset generator",
      "flutter app icon generator",
      "react native app icon",
      "expo app icon",
      "app icon sizes chart",
      "ios app icon sizes 2026",
      "android launcher icon sizes",
      "generate apple touch icons",
      "app icon studio",
      "round app icon maker",
      "app icon generator from png",
      "create ios icons",
      "app icon resizer",
      "app icon set generator",
      "mobile icon generator",
      "generate notification icons android",
      "app icon creator online",
      "download app icons zip",
      "app icon generator no signup",
      "xcode app icon sizes",
      "app icon from logo maker"],
  };

export default seo;
