import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "ARIA Role Explorer - Free Online Tool | IconVault",
    metaDescription: "Explore ARIA roles: what each role means, required context, keyboard expectations and copyable HTML patterns. Free accessibility reference.",
    about: [
      "**IconVault**'s **ARIA Role Explorer** is a searchable reference for ARIA roles. Browse landmarks, widgets and structural roles to learn what each role communicates to assistive technology, which keyboard interactions users expect, what context a role requires, and grab a copyable HTML pattern that uses it correctly. It is free and runs fully in your browser.",
      "**ARIA roles** are promises: role=\"dialog\" tells a screen reader to expect focus trapping and an Escape key, role=\"slider\" promises arrow-key control with announced values. Getting the role right but the keyboard behavior wrong is one of the most common accessibility bugs. This explorer pairs every role with its **keyboard contract** and **required attributes** so your custom components behave the way assistive technology expects."
    ],
    faqs: [
      { q: "When should I use an ARIA role instead of a native element?", a: "Almost never as a first choice. Native button, input, nav and dialog elements come with roles, keyboard behavior and semantics built in. Use ARIA roles only when building custom widgets that no native element can express, then implement the full keyboard contract." },
      { q: "What is the difference between a landmark role and a widget role?", a: "Landmark roles (banner, main, navigation, complementary) identify large page regions for navigation. Widget roles (button, dialog, slider, tab) describe interactive controls and come with keyboard expectations. Structure roles (heading, list, table) describe document organization." },
      { q: "Do I need keyboard support if I add a widget role?", a: "Yes. The role announces what the control is, but you must implement the keys yourself: Space/Enter for buttons, arrows for sliders and tablists, Escape for dialogs. A role without keyboard support is worse than no role at all." },
      { q: "What does aria-modal do on a dialog?", a: "It tells assistive technology that content behind the dialog is inert. You still need to trap Tab focus inside the dialog and return focus to the trigger when it closes; aria-modal alone does not do that for you." },
      { q: "What is the difference between role=alert and role=status?", a: "Both are live regions. status is polite: announcements wait for the screen reader to finish. alert is assertive: it interrupts. Use status for confirmations like Saved, and alert for urgent errors." },
      { q: "Can ARIA roles hurt accessibility?", a: "Yes. A wrong role actively misleads screen reader users, which is why the first rule of ARIA is to prefer native elements. This explorer exists so that when you do need a role, you use the right one with the right pattern." }
    ],
    tags: [
      "aria role explorer",
      "aria roles list",
      "aria roles cheat sheet",
      "what is aria role",
      "aria landmark roles",
      "aria widget roles",
      "role button aria",
      "role dialog keyboard",
      "aria dialog focus trap",
      "role switch vs checkbox",
      "aria slider keyboard",
      "role tablist keyboard arrows",
      "aria combobox pattern",
      "role listbox option",
      "aria menu vs navigation",
      "role alert vs status",
      "aria live regions explained",
      "role tooltip example",
      "aria progressbar example",
      "role banner main contentinfo",
      "aria complementary landmark",
      "role search landmark",
      "aria form role label",
      "role region vs section",
      "aria heading role level",
      "role img aria-label",
      "aria roles reference free",
      "learn aria roles",
      "aria roles tutorial",
      "aria authoring practices",
      "wai-aria roles explained",
      "aria keyboard interaction",
      "custom checkbox aria",
      "aria-checked true false mixed",
      "aria-expanded controls",
      "aria-selected tab",
      "aria-modal dialog",
      "accessible modal dialog",
      "aria-describedby tooltip",
      "screen reader roles",
      "aria role taxonomy",
      "when to use aria roles",
      "first rule of aria",
      "aria roles html patterns",
      "copyable aria examples",
      "aria widget keyboard support",
      "aria roles for beginners",
      "accessibility roles reference",
      "aria in html guide",
      "aria roles list interactive demo"
    ],
  };

export default seo;
