import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "ARIA Reference - Free Online Learning Tool | IconVault",
    metaDescription: "Searchable ARIA roles and attributes reference: required and supported attributes, plain-English descriptions and copyable examples. Free.",
    about: [
      "**IconVault**'s **ARIA Reference** is a searchable quick guide to **WAI-ARIA roles and attributes**. Look up any role to see a plain-English description, its **required attributes**, the **supported attributes** you can use with it, and a ready-to-use **HTML example** you can copy straight into your code.",
      "It is **free** and runs **fully in your browser**. Two honest notes: this is a curated quick reference, not the full specification, so check the **W3C WAI-ARIA spec** for edge cases; and remember the first rule of ARIA, which is to prefer **native HTML elements** (button, input, nav) over divs with roles whenever the native element exists."
    ],
    faqs: [
      { q: "What is ARIA?", a: "ARIA (Accessible Rich Internet Applications) is a set of roles, states and properties you add to HTML so assistive technologies like screen readers understand custom widgets. It fills the gap when native HTML elements cannot express what a component does." },
      { q: "Which roles are covered?", a: "Common widget and structural roles such as button, link, checkbox, radio, switch, textbox, dialog, tab, menu, alert and landmarks, each with its required and supported attributes plus a copyable example." },
      { q: "Should I use ARIA or native HTML?", a: "Native HTML first. A real button element already has keyboard support, focus behavior and screen reader semantics that a div with role=\"button\" only gets if you hand-code all of it. Use ARIA when no native element fits, like custom sliders, tree views or live regions." },
      { q: "Can I copy the examples?", a: "Yes. Every role includes a copyable HTML snippet showing correct attribute usage, which you can paste into your project and adapt." },
      { q: "Is this the complete WAI-ARIA specification?", a: "No, it is a practical quick reference covering the roles and attributes developers reach for most. For normative details, global states, and rare roles, consult the official W3C specification." },
      { q: "Do I need an account to use it?", a: "No. The reference is free, works entirely in your browser, and needs no signup." }
    ],
    tags: [
      "aria reference",
      "aria roles list",
      "aria attributes list",
      "wai aria cheat sheet",
      "aria roles and attributes",
      "aria role button",
      "aria label example",
      "aria expanded",
      "aria pressed",
      "aria checked",
      "aria describedby",
      "aria labelledby",
      "role checkbox aria",
      "role switch vs checkbox",
      "aria required attributes",
      "aria supported attributes",
      "accessible rich internet applications guide",
      "learn aria",
      "aria tutorial",
      "aria for beginners",
      "when to use aria",
      "aria first rule",
      "native html vs aria",
      "aria examples copy paste",
      "aria code snippets",
      "screen reader aria guide",
      "assistive technology semantics",
      "web accessibility aria",
      "frontend accessibility reference",
      "developer aria guide",
      "aria landmark roles",
      "aria widget roles",
      "aria live regions",
      "aria hidden",
      "aria disabled",
      "tabindex and aria",
      "keyboard accessibility aria",
      "aria design patterns",
      "w3c aria practices",
      "aria in html",
      "react aria attributes",
      "vue aria",
      "aria cheat sheet printable",
      "common aria mistakes",
      "aria overuse",
      "do divs need roles",
      "accessible button example",
      "accessible modal aria",
      "accessible dropdown aria",
      "accessible tabs aria pattern",
      "aria for forms",
      "form aria labels",
      "free aria reference online",
      "aria lookup tool",
      "search aria roles",
      "aria documentation quick"
    ],
  };

export default seo;
