import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Array Visualizer - Free Online Learning Tool | IconVault",
    metaDescription: "Step through map, filter, reduce, find and sort like a debugger: watch the index pointer move and the result grow. Free, in your browser.",
    about: [
      "**IconVault**'s **Array Visualizer** teaches **JavaScript array methods** the way a debugger would. Step through **map**, **filter**, **reduce**, **find** and **sort** one operation at a time while the **index pointer** moves across your array, each step explained in plain English, the **result so far** growing beside it and the **accumulator** shown for reduce.",
      "Bring your own data (comma-separated values, up to 24 items) and even your own **callback expression**, which is compiled **locally in your browser** and never leaves your device. It is **free** with no signup. The honest framing: it builds real intuition for iteration, filtering and folding, which you then cement by writing the code yourself."
    ],
    faqs: [
      { q: "Which array methods are covered?", a: "map (transform every element), filter (keep elements that pass), reduce (fold into one value), find (first element that passes) and sort (animated bubble sort). Each method runs as a step-by-step trace you control." },
      { q: "How do I step through the execution?", a: "Use play to run the animation, pause it, or step forward and backward through individual operations. Every step shows which index is being read, what the callback returned, and how the result array changed." },
      { q: "Can I use my own array?", a: "Yes. Enter comma-separated values (numbers or strings, up to 24 items) and the visualizer will trace the method over your data instead of the default example." },
      { q: "Can I write my own callback?", a: "Yes. Type an expression using x (the element), i (the index) and arr (the array), such as x * 2 or x > 10. It is compiled locally in your browser with the Function constructor, so keep expressions simple and never paste untrusted code." },
      { q: "Is my code sent to a server?", a: "No. Your array and callback expression are evaluated entirely in your browser tab. Nothing is uploaded or stored." },
      { q: "Which sort algorithm is used for sort?", a: "The sort trace animates bubble sort, so you can watch comparisons and swaps happen explicitly. It is chosen for clarity, not speed." }
    ],
    tags: [
      "array methods visualizer",
      "javascript array methods visualizer",
      "map filter reduce visualizer",
      "array map visualizer",
      "array filter step by step",
      "array reduce explained visually",
      "array find visualizer",
      "javascript sort visualizer",
      "learn array methods",
      "js array methods tutorial",
      "map vs foreach",
      "how does array reduce work",
      "how does array filter work",
      "array method step debugger",
      "watch map iterate",
      "accumulator visualizer",
      "callback execution visualizer",
      "javascript for beginners",
      "learn javascript arrays",
      "js methods explained visually",
      "functional programming js visual",
      "array methods cheat sheet",
      "javascript practice tool",
      "interactive js learning",
      "coding bootcamp study tool",
      "dsa arrays visualizer",
      "array iteration animation",
      "index pointer visualization",
      "step through code online",
      "javascript playground visual",
      "custom callback tester",
      "test map function online",
      "reduce initial value explained",
      "find vs filter javascript",
      "sort comparator visual",
      "bubble sort array method",
      "js array methods interview",
      "array methods interview questions",
      "frontend interview prep",
      "javascript visualizer free",
      "free js learning tool online",
      "no signup js playground",
      "browser javascript lab",
      "learn by watching code run",
      "code execution visualizer",
      "programming logic visualizer",
      "array transformation visual",
      "chained array methods",
      "map filter chaining explained",
      "immutable array methods",
      "does map mutate array",
      "pure functions array methods"
    ],
  };

export default seo;
