import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "ASCII Art - Free Online Text Art Generator Tool | IconVault",
    metaDescription: "Turn text into ASCII art with 4 built-in FIGlet-style fonts. Copy to clipboard or download as a text file. Free, runs in your browser.",
    about: [
      "**IconVault**'s **ASCII Art** generator turns plain text into big **block-letter art**. Type anything, pick from **4 built-in FIGlet-style fonts**, and watch the preview render instantly. **Copy** the result to your clipboard or **download** it as a text file for READMEs, code comments, terminal banners and profile headers.",
      "Everything renders **purely client-side**, so it is instant, **free** and private with no signup. The honest scope: these are stylized **text fonts**, not image-to-ASCII conversion, and the art only lines up correctly in a **monospace font**, so view or paste it somewhere like a terminal or code editor."
    ],
    faqs: [
      { q: "What fonts are included?", a: "Four built-in FIGlet-style block letter fonts covering A to Z, 0 to 9 and common punctuation, all rendered locally in your browser with no font files to download." },
      { q: "Can I convert an image to ASCII art?", a: "No. This tool converts text to ASCII art only. Image-to-ASCII conversion is a different technique and is not included." },
      { q: "Why does my ASCII art look misaligned?", a: "ASCII art depends on every character being the same width. View or paste it in a monospace font (a terminal, code editor or code block) and the alignment will snap into place." },
      { q: "Can I download the result?", a: "Yes. Download it as a .txt file or copy it straight to your clipboard with one click." },
      { q: "What is ASCII art good for?", a: "README headers, code comment banners, terminal welcome messages, Discord and forum signatures, social bios and anywhere else you want plain-text decoration that works without images." },
      { q: "Is it free?", a: "Yes. The generator is free, runs entirely in your browser and needs no account." }
    ],
    tags: [
      "ascii art generator",
      "text to ascii art",
      "ascii text generator",
      "figlet online",
      "figlet generator",
      "ascii banner generator",
      "big text ascii",
      "ascii font generator",
      "text art generator",
      "ascii logo maker",
      "terminal text art",
      "readme ascii art",
      "ascii header generator",
      "code comment banner",
      "ascii art text free",
      "online ascii art maker",
      "copy paste ascii text",
      "fancy text ascii",
      "block letter generator",
      "bubble text ascii",
      "typewriter text art",
      "retro text generator",
      "hacker text generator",
      "matrix text art",
      "discord ascii art",
      "ascii art for discord",
      "youtube banner ascii",
      "instagram bio ascii",
      "twitter ascii art",
      "birthday ascii art",
      "name in ascii art",
      "write my name in ascii",
      "ascii art alphabet",
      "figlet fonts list",
      "standard figlet font",
      "banner figlet font",
      "slant ascii font",
      "big ascii font online",
      "ascii art download txt",
      "save ascii art",
      "monospace ascii art",
      "why ascii art misaligned",
      "ascii art generator no signup",
      "free text art tool",
      "browser ascii generator",
      "ascii art for github readme",
      "github profile ascii",
      "cli banner generator",
      "startup banner text",
      "motd ascii generator",
      "terminal greeting art",
      "nerd text art",
      "forum signature ascii"
    ],
  };

export default seo;
