import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "AVIF to JPG Converter - Free Online Tool | IconVault",
    metaDescription: "Convert AVIF images to JPG free in your browser. Bulk support, quality slider, background fill, no uploads.",
    about: [
      "**IconVault**'s **AVIF to JPG Converter** turns modern **AVIF images** into universally compatible **JPG files** right in your browser. Your browser decodes AVIF natively, so no plugins are needed. The tool is completely **free**, handles **bulk uploads**, and your images **never leave your device**.",
      "A **quality slider** (90% default) controls sharpness versus size, and the **background color** picker fills transparent areas, since JPG has no alpha channel. Batches download as a **ZIP**. **IconVault Pro** removes trial limits for unlimited use.",
    ],
    faqs: [
      { q: "Is AVIF to JPG conversion free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited conversions." },
      { q: "Do my images get uploaded?", a: "No. Your browser decodes AVIF locally, so nothing ever leaves your device." },
      { q: "Why convert AVIF to JPG?", a: "JPG opens everywhere: older editors, email clients and apps that still do not support AVIF." },
      { q: "What happens to transparency?", a: "JPG cannot store transparency, so transparent areas become the fill color you choose, white by default." },
      { q: "What quality should I use?", a: "90% is a good default for sharp photos. Lower it toward 75% for smaller web files." },
      { q: "Can I convert many AVIFs at once?", a: "Yes. Add a batch and download everything together as a ZIP file." },
    ],
    tags: ["avif to jpg", "convert avif to jpg", "avif converter", "avif to jpeg", "avif to jpg online", "bulk avif to jpg", "avif to jpg free", "avif file converter", "avif to jpg quality", "avif transparent to jpg", "avif to jpg batch", "save avif as jpg", "avif to jpg no signup", "avif to jpg private", "avif image converter", "avif to jpg download", "free avif converter", "avif to jpeg converter", "avif to jpg zip", "open avif as jpg",
      "avif converter online",
      "convert avif files",
      "avif to jpg converter free",
      "change avif to jpg",
      "avif file to jpg",
      "convert avif image",
      "avif to jpeg online",
      "avif picture converter",
      "download avif as jpg",
      "avif format converter",
      "how to convert avif to jpg",
      "avif to jpg windows",
      "avif to jpg mac",
      "avif to jpg android",
      "open avif file",
      "avif to jpg app",
      "convert avif to jpg free",
      "avif to jpg converter online free",
      "avif jpeg conversion",
      "save avif image as jpg",
      "avif to jpg high quality",
      "avif image to jpeg",
      "convert avif without software",
      "avif to jpg browser tool",
      "avif format to jpg",
      "transform avif to jpg",
      "avif converter free online",
      "convert downloaded avif to jpg",
      "avif to jpg without losing quality",
      "bulk avif converter",
      "avif to jpg image converter",
      "avif photo converter",
      "change avif file to jpg",
      "avif to jpg online converter",
      "avif to jpg website",
      "convert avif images online",
      "avif to jpg tool",
      "avif to jpeg free",
      "avif converter to jpg",
      "avif image to jpg"],
  };

export default seo;
