import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Badging API - Interactive Lab | IconVault",
    metaDescription: "Try navigator.setAppBadge live with a real favicon fallback that draws the badge on the tab icon. Free, runs in your browser.",
    about: [ "**IconVault**'s **Badging API** playground calls the real `navigator.setAppBadge()` and `clearAppBadge()` so you can experiment with unread counts, plus and minus stepping, and clearing. Where the API is missing, the tool does not fake it: it draws the badge live onto this tab's **favicon**, giving you a real visual result in any browser. It is free and runs fully in your browser.", "Badges are the quiet workhorse of **installed web apps**: chat apps show unread messages, mail clients show inbox counts, task apps show due items. The lab explains where the native badge actually appears (**the installed PWA or app icon**, never the tab), the **99+ display convention**, and the exact **three-line favicon fallback** you can ship today for browsers without support." ],
    faqs: [ { q: "What does the Badging API do?", a: "navigator.setAppBadge(n) asks the operating system to show a small badge, usually a number, on the web app's icon. clearAppBadge() removes it. It is designed for installed PWAs to surface unread counts and status." }, { q: "Why can't I see the badge after setting it?", a: "The native badge renders on the installed app icon, not in the browser tab, and only where the OS supports it (Chrome/Edge 81+, Safari 16.4+). If your site is not installed as an app, the call resolves successfully but nothing visible changes, which is why this tool adds a favicon preview." }, { q: "How does the favicon fallback work?", a: "It draws your site's favicon onto a 64px canvas, paints a red notification dot with the count in the corner, and swaps the tab's icon to the resulting data URL. The original favicon is restored when you clear the badge or leave the page." }, { q: "Which browsers support the Badging API?", a: "Chrome and Edge 81+, Opera, and Safari 16.4+. Firefox does not support it. Always feature-detect with 'setAppBadge' in navigator before calling it." }, { q: "Is there a maximum badge number?", a: "The spec takes any non-negative integer, but platforms typically display values above 99 as '99+'. This playground follows the same convention." }, { q: "Does setting a badge need permission?", a: "No permission prompt is involved; it is a simple method call. That is also why the API only affects installed app icons, limiting abuse potential." } ],
    tags: [ "badging api", "navigator.setappbadge", "setappbadge", "clearappbadge", "app badge api", "badge api javascript", "pwa badge", "pwa app badge", "unread badge web app", "notification badge pwa", "badging api demo", "badging api example", "setappbadge example", "app icon badge web", "favicon badge", "dynamic favicon badge", "favicon notification count", "draw badge on favicon", "tab icon badge", "browser tab notification badge", "badging api browser support", "badging api safari", "badging api chrome", "badging api firefox", "mdn badging api", "how to show badge on pwa icon", "pwa unread count", "web app badge number", "setappbadge typescript", "badging api tutorial", "badge counter javascript", "notification dot favicon", "live favicon update", "canvas favicon", "change favicon dynamically", "installed pwa badge", "web app icon badge", "badging api polyfill", "favicon fallback badge", "show count on app icon", "pwa push badge", "does setappbadge work without install", "badging api https", "app badging", "w3c badging api", "experimental badging", "test badging api online", "badging playground", "setappbadge not working", "pwa icon badge number", "web badging demo" ],
  };

export default seo;
