import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Battery Status - Interactive Lab | IconVault",
    metaDescription: "Connect to the real Battery Status API: live level chart, charging state, time estimates and event log. Free, runs in your browser.",
    about: [ "**IconVault**'s **Battery Status** playground connects to the real `navigator.getBattery()` API: live charge level with a recording chart, charging versus discharging state, estimated time to full or empty, and an event log that fires the instant you plug or unplug the charger. Where the API has been removed, the tool says so plainly instead of simulating numbers. It is free and runs fully in your browser.", "The lab covers the honest history too: Firefox and Safari dropped this API over **fingerprinting concerns**, so it is **Chromium-only** today. You will learn the **four events** (`chargingchange`, `levelchange`, `chargingtimechange`, `dischargingtimechange`), why times report `Infinity` when unknown, and the practical pattern of lowering work (fewer animations, deferred sync) when the device is unplugged and low." ],
    faqs: [ { q: "What does navigator.getBattery() return?", a: "A promise for a BatteryManager with level (0 to 1), charging (boolean), chargingTime and dischargingTime in seconds, plus events that fire whenever any of them change. This tool renders all four live." }, { q: "Why is the API missing in Firefox and Safari?", a: "Both removed it because battery readings can be used for fingerprinting: the precise level and discharge curve can help identify a device across sites. Chromium still ships it." }, { q: "What does Infinity mean for chargingTime?", a: "Infinity (shown here as n/a) means the browser cannot estimate: for example chargingTime is Infinity while discharging, and dischargingTime is Infinity while charging." }, { q: "Do I need permission to read battery status?", a: "No permission prompt; it is a plain promise. That simplicity is exactly why some browsers removed it, so treat the data as approximate and never as an identifier." }, { q: "How should apps use battery information?", a: "Adapt, do not punish: reduce animation, defer background sync, or offer a data-saver mode when unplugged and low. Never block features solely because the battery is low." }, { q: "Is my battery data sent anywhere?", a: "No. Readings stay in your browser; the chart is drawn on a local canvas and the trial counter is a localStorage number." } ],
    tags: [ "battery status api", "navigator.getbattery", "getbattery", "battery api javascript", "battery level javascript", "html battery api", "battery status demo", "battery api example", "chargingchange", "levelchange", "batterymanager", "get battery level web", "javascript battery percentage", "web battery indicator", "battery api chrome", "battery api firefox removed", "battery api safari", "why battery api removed", "battery fingerprinting", "chargingtime", "dischargingtime", "battery time to full", "battery level chart", "monitor battery web app", "pwa battery", "low battery web app", "data saver battery", "mdn battery status api", "battery status api tutorial", "battery api typescript", "battery api polyfill", "is battery api supported", "caniuse battery status", "navigator.getbattery not a function", "battery api https", "web api battery level", "javascript detect charging", "laptop charging javascript", "phone battery web", "battery events javascript", "battery status example code", "how to get battery percentage in javascript", "battery api 2024", "battery api privacy", "test battery api online", "battery playground", "battery monitor browser", "getbattery typescript", "battery api example code", "detect charger javascript", "battery level web app" ],
  };

export default seo;
