import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "BFC Layout Debugger - Free Online Tool | IconVault",
    metaDescription: "Visualize Block Formatting Contexts: float containment, margin collapse and float exclusion with live toggles. Free CSS learning tool.",
    about: [
      "**IconVault**'s **BFC Layout Debugger** makes Block Formatting Contexts visible. Toggle a BFC on and off in three classic scenarios: a parent collapsing around floated children, two margins collapsing into one gap (with a live pixel measurement), and text wrapping under a float versus forming its own column. It is free and runs fully in your browser.",
      "The BFC is one of **CSS layout**'s most misunderstood ideas, yet it explains so many real bugs: **the collapsed parent**, the margin that refuses to add up, the text that slides under a floated image. Seeing the before and after side by side, with the exact CSS that creates a BFC (**display: flow-root**, **overflow: hidden**, and friends), turns a vague concept into a debugging tool you will actually use."
    ],
    faqs: [
      { q: "What is a Block Formatting Context?", a: "A BFC is an isolated layout region. Inside it, floats are contained, margins only collapse with each other (never with the outside), and outside floats cannot intrude. It is the reason display: flow-root fixes collapsed float parents." },
      { q: "How do I create a BFC?", a: "The clean modern way is display: flow-root. Historically people used overflow: hidden or overflow: auto, which also work but can clip content. Other triggers include floats, absolutely positioned elements, inline-blocks, and contain: layout." },
      { q: "Why do my vertical margins collapse?", a: "Adjoining vertical margins of block boxes collapse to the larger of the two instead of adding up. It is by design: it keeps paragraph spacing consistent. Wrap one element in a BFC to opt out, or use padding/gap instead." },
      { q: "What is the difference between display: flow-root and overflow: hidden?", a: "Both create a BFC, but overflow: hidden clips anything sticking out (shadows, tooltips, sticky children), while flow-root creates the BFC with no side effects. Prefer flow-root for new code." },
      { q: "Why does text wrap under my floated image?", a: "Text in normal flow wraps around floats by design. If you want a clean column beside the float, put the text in its own BFC with display: flow-root and the float can no longer intrude." },
      { q: "Do flex and grid items create BFCs?", a: "Flex items and grid items establish a BFC-like containment for their contents, which is one reason margins do not collapse through flex and grid containers." }
    ],
    tags: [
      "bfc css",
      "block formatting context",
      "block formatting context explained",
      "css bfc visualizer",
      "display flow-root",
      "display flow-root vs overflow hidden",
      "css float parent collapse",
      "parent div not wrapping floats",
      "clearfix vs flow-root",
      "css margin collapse",
      "margins not adding up css",
      "prevent margin collapse css",
      "margin collapse bfc",
      "css float text wrap",
      "text wrapping under float",
      "overflow hidden creates bfc",
      "what creates a bfc",
      "bfc triggers list",
      "css layout debugging",
      "learn css layout",
      "css bfc examples",
      "block formatting context tutorial",
      "css float containment",
      "clear floats css",
      "css bfc interactive",
      "visualize margin collapse",
      "css margin 40px 40px 40px gap",
      "why do margins collapse",
      "css bfc mdn",
      "flow-root browser support",
      "css contain layout",
      "bfc vs stacking context",
      "css formatting context",
      "inline formatting context",
      "css float exclusion",
      "float intrusion css",
      "css layout concepts",
      "css box model deep dive",
      "frontend interview bfc",
      "css bfc interview question",
      "margin collapsing rules",
      "negative margin collapse",
      "css bfc tool free",
      "css debugger online",
      "learn css floats",
      "css float layout explained",
      "block formatting context demo",
      "bfc css margin collapse fix",
      "what creates a bfc in css",
      "bfc overflow hidden explained"
    ],
  };

export default seo;
