import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Blur Face in Photo - Free Online Tool | IconVault",
    metaDescription: "Blur or pixelate faces in photos online. Draw boxes, adjust strength, export free. Private, in-browser.",
    about: [
      "**IconVault**'s **Blur Face** tool lets you hide **faces**, license plates and anything sensitive by drawing boxes right on the photo and applying **blur** or **pixelation** with an adjustable strength that scales **relative to each box's size**. Every box can be moved, resized and deleted before you export, and you can cover as many regions as you need.",
      "It is **free** and runs **100% in your browser**, so the photo never leaves your device, ideal for journalists, sellers and parents sharing photos of kids. Export as **JPG, PNG, WebP** or keep the original format. One honest note: for text like names or numbers, use **Redact Image** instead, because blur can sometimes be reversed. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "How do I blur a face in a photo?", a: "Upload the photo, drag a box over the face, pick Blur or Pixelate, set the strength and hit Export image. You can add as many boxes as you need." },
      { q: "Is blur or pixelate better for privacy?", a: "Both hide the region at a glance. For text like names or numbers, solid redaction is safest because blur can sometimes be partially reversed." },
      { q: "Is my photo uploaded?", a: "No. Blurring happens entirely in your browser with canvas. Your photo never leaves your device." },
      { q: "Can I blur multiple faces at once?", a: "Yes. Draw one box per face or region, adjust each one by dragging or with the corner handle, then export everything in one go." },
      { q: "What formats can I export?", a: "Same as the source, JPG, PNG or WebP. JPG exports get a white background behind transparent areas." },
      { q: "Is it free?", a: "Yes, with 5 free exports. Pro members get unlimited exports plus HD quality and every template across all IconVault tools." },
    ],
    tags: [ "blur face online", "blur face in photo", "pixelate image online", "blur part of image", "face blur tool", "censor photo online", "blur image region", "pixelate face", "hide face in photo", "blur license plate photo", "photo anonymizer", "blur photo online free", "mosaic blur image", "redact photo blur", "blur multiple faces", "image blur editor", "privacy blur photo", "blur sensitive info photo", "pixelate region image", "face pixelizer" ,
      "blur faces online",
      "face blurring tool",
      "auto face blur",
      "blur faces in photos free",
      "anonymous face blur",
      "blurry face tool",
      "photo face censor",
      "blur faces online free",
      "censor faces in photo",
      "privacy face blur",
      "blur face app online",
      "face blur photo editor",
      "hide faces in pictures",
      "blur out faces",
      "face mosaic tool",
      "pixelate faces online",
      "blur faces in picture",
      "protect identity photo",
      "blur faces for youtube thumbnail",
      "face blur for instagram",
      "how to blur faces in photos",
      "blur faces without app",
      "online face blur tool",
      "face blur editor free",
      "blur background faces",
      "crowd face blur",
      "blur faces in screenshots",
      "face blur generator",
      "pixelate faces in photo",
      "blur face online free tool",
      "automatic face blur photo",
      "mask faces in image",
      "face concealment tool",
      "blur children's faces in photos",
      "blur face in image free",
      "photo censor faces",
      "blur faces privacy",
      "face blur software online",
      "how to pixelate a face",
      "blur face tool free"],
  };

export default seo;
