import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Blurhash Generator - Free Online Tool | IconVault",
    metaDescription: "Encode any image to a compact Blurhash placeholder string with a live decoded preview. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Blurhash Generator** turns any image into a **Blurhash string**, the compact text placeholder used by apps like Mastodon and Unsplash to show a blurry preview while the real image loads. Adjust the X/Y components (4x3 suits most photos), copy the hash, and decode it client-side anywhere.",
      "The tool shows a live **decoded preview** next to your original so you can see exactly what users will glimpse while loading. Note the trade-off: more components keep more detail but make a longer string. Everything is encoded **in your browser**: your image is never uploaded. **Free** with a daily trial, unlimited with Pro.",
    ],
    faqs: [
      { q: "What is a Blurhash?", a: "Blurhash is a compact string encoding of an image's low-frequency color data. Clients decode it into a blurred placeholder in a few milliseconds, which is much nicer than a gray box while the full image downloads." },
      { q: "What do the X and Y components control?", a: "They set how many basis components encode the image horizontally and vertically. 4x3 is the recommended default for photos; more components preserve more detail but produce a longer hash string." },
      { q: "How do I use the hash in my app?", a: "Store the hash alongside your image URL and decode it with any Blurhash library (JavaScript, Swift, Kotlin, and more) into a small canvas or image view shown while the real file loads." },
      { q: "How long is the hash string?", a: "With the default 4x3 components it is around 28 characters. Raising the component counts lengthens the string roughly in proportion." },
      { q: "Is my image uploaded to a server?", a: "No. Encoding and decoding both happen locally in your browser. Nothing leaves your device." },
      { q: "How many hashes can I generate free?", a: "A daily trial covers free encodes. IconVault Pro unlocks unlimited use across all tools." },
    ],
    tags: [ "blurhash generator", "blurhash encoder online", "image placeholder hash", "blurry image placeholder", "blurhash string generator", "lazy load placeholder", "image blur placeholder", "decode blurhash", "blurhash react", "blurhash javascript", "placeholder image technique", "low quality image placeholder", "lqip generator", "blurhash components", "encode image to blurhash", "blurhash preview", "mastodon blurhash", "progressive image loading", "blurhash online tool", "free blurhash generator" ,
      "blurhash encode",
      "generate blurhash",
      "blurhash generator free",
      "blurhash online",
      "blurhash tool",
      "blurhash placeholder",
      "create blurhash",
      "blurhash maker",
      "blurhash image",
      "blurhash decoder online",
      "convert image to blurhash",
      "blurhash api",
      "blurhash npm",
      "blurhash placeholder generator",
      "blurhash encode online",
      "image to blurhash string",
      "blurhash example",
      "blurhash web",
      "blurhash python",
      "blurhash for images",
      "blurhash react native",
      "skeleton placeholder images",
      "image loading placeholder generator",
      "blur up placeholder",
      "blurhash css",
      "blurhash width height",
      "blurhash canvas",
      "generate image placeholders",
      "blurry placeholder generator",
      "image preview placeholder",
      "blurhash for lazy loading",
      "create image placeholder blur",
      "blurhash demo",
      "blurhash code generator",
      "encode placeholder image",
      "blurhash string example",
      "blurhash vs lqip",
      "placeholder blur image generator",
      "blurhash next js",
      "blurhash tutorial"],
  };

export default seo;
