import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "BMP and TIFF Converter - Free Online Tool | IconVault",
    metaDescription: "Convert BMP and TIFF to JPG, PNG or WebP free in your browser. Multi-page TIFF support, ZIP download, no uploads.",
    about: [
      "**IconVault**'s **BMP and TIFF Converter** turns **BMP** photos and **TIFF** scans into web-friendly **JPG, PNG or WebP files**, right in your browser. **Multi-page TIFFs** are split automatically, one image per page, so scanned documents convert in a single step. The tool is completely **free**, and your files **never leave your device**.",
      "A **quality slider** (90% default) controls size for JPG and WebP, and the **background color** picker fills transparency for JPG output. Convert a batch and download everything as a **ZIP**. **IconVault Pro** removes trial limits for heavy conversion work.",
    ],
    faqs: [
      { q: "Is the BMP and TIFF converter free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited conversions." },
      { q: "Are my files uploaded?", a: "No. BMP decodes natively and TIFF decodes locally in your browser, so nothing leaves your device." },
      { q: "How are multi-page TIFFs handled?", a: "Each page becomes a separate image, named with its page number, and everything downloads as a ZIP." },
      { q: "Which output format should I choose?", a: "JPG for small photos, PNG for lossless graphics, WebP for the best size-to-quality ratio." },
      { q: "What happens to transparency?", a: "JPG cannot store transparency, so transparent areas become the fill color you pick, white by default." },
      { q: "Can I convert many files at once?", a: "Yes. Add BMP and TIFF files in bulk and download them together as a ZIP." },
    ],
    tags: ["bmp converter", "tiff converter", "bmp to jpg", "tiff to jpg", "bmp to png", "tiff to png", "convert bmp", "convert tiff", "tiff to pdf", "bmp to webp", "tiff to webp", "multipage tiff converter", "tif to jpg", "bmp to jpg online", "tiff converter free", "bmp converter free", "tiff to png online", "bmp tiff free", "tif file converter", "tiff pages to images",
      "bmp to jpeg",
      "tiff to jpeg",
      "bmp to png online",
      "tiff to png easy",
      "convert tiff to jpg",
      "convert bmp to jpg",
      "tif to png",
      "bmp image converter",
      "tiff image converter",
      "bmp to jpg converter",
      "tiff to jpg converter",
      "convert tif to jpg",
      "bmp to png converter",
      "tiff to png converter",
      "open tiff file online",
      "view tiff online",
      "tiff file opener",
      "convert scanned tiff",
      "bmp to pdf",
      "tiff to pdf converter",
      "convert bmp online free",
      "convert tiff online free",
      "bmp format converter",
      "tiff format converter",
      "tif converter online",
      "bmp to gif",
      "tiff to gif",
      "bmp to webp online",
      "tiff to webp online",
      "change bmp to jpg",
      "change tiff to png",
      "bmp to ico",
      "tiff to jpg free online",
      "bmp to jpg free online",
      "tiff pages extractor",
      "split multipage tiff",
      "tiff to single images",
      "convert tiff to jpeg",
      "bmp converter online free",
      "tiff converter online free"],
  };

export default seo;
