import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "BroadcastChannel - Interactive Lab | IconVault",
    metaDescription: "Real cross-tab messaging with BroadcastChannel: chat between tabs, ping round-trips and a live leader election. Free, in-browser.",
    about: [ "**IconVault**'s **BroadcastChannel** playground opens a real named channel: connect, open the page in a second tab, and send messages that arrive instantly in every tab. Ping measures cross-tab round trips, and the leader-election demo runs a genuine bully algorithm over the channel so one tab becomes leader while the rest follow. It is free and runs fully in your browser.", "**BroadcastChannel** is the simplest way for **same-origin tabs**, windows and iframes to coordinate: **no server**, no storage events hack. The lab shows the message protocol in the open, explains why the **sender never receives its own broadcast**, and covers the classic use cases: electing one tab to hold a WebSocket, avoiding duplicate polling, and syncing logout or theme changes across tabs." ],
    faqs: [ { q: "What is BroadcastChannel?", a: "A web API that lets browsing contexts (tabs, windows, iframes, workers) on the same origin send messages to each other by name. Any context listening on the same channel name receives every message posted to it." }, { q: "Do messages reach the tab that sent them?", a: "No. BroadcastChannel never delivers a message to the context that posted it, which is why this playground still logs your sent messages locally for clarity." }, { q: "How does the leader election work?", a: "Each tab broadcasts a bid with its random id, collects bids for 800ms, and the highest id wins and announces victory. It is a simplified bully algorithm, good enough to elect one tab for polling, sockets, or timers." }, { q: "Can different origins communicate this way?", a: "No. BroadcastChannel is strictly same-origin. For cross-origin communication you need postMessage with explicit origin checks, or a server relay." }, { q: "What data can I send?", a: "Anything the structured clone algorithm supports: objects, arrays, Dates, Maps, Blobs, even transferable ports. Functions and DOM nodes cannot be cloned." }, { q: "Is any message sent to a server?", a: "No. BroadcastChannel is purely local to the browser. The trial counter is a localStorage number." } ],
    tags: [ "broadcastchannel", "broadcast channel api", "broadcastchannel javascript", "broadcastchannel example", "cross tab messaging", "communicate between tabs javascript", "tab to tab communication", "broadcastchannel demo", "broadcastchannel tutorial", "leader election javascript", "bully algorithm javascript", "elect leader tab", "one tab websocket", "avoid duplicate polling tabs", "sync tabs javascript", "logout all tabs", "storage event vs broadcastchannel", "broadcastchannel browser support", "broadcastchannel safari", "broadcastchannel typescript", "postmessage broadcastchannel", "same origin messaging", "broadcastchannel ping", "broadcastchannel round trip", "broadcastchannel chat", "multiple tabs coordination", "shared worker vs broadcastchannel", "broadcastchannel closed", "broadcastchannel onmessage", "how to use broadcastchannel", "mdn broadcastchannel", "broadcastchannel polyfill", "broadcastchannel react", "cross window messaging", "iframe parent communication broadcastchannel", "web worker broadcastchannel", "service worker broadcastchannel", "broadcastchannel messageevent", "broadcastchannel name", "test broadcastchannel online", "broadcastchannel playground", "broadcast channel lab", "tab sync demo", "real time tab sync", "broadcastchannel security", "can broadcastchannel cross origin", "broadcastchannel example code", "tab communication javascript", "broadcast channel leader", "cross tab chat" ],
  };

export default seo;
