import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Bulk Crop - Free Online Tool | IconVault",
    metaDescription: "Crop many photos to one aspect ratio at once, free in your browser. Adjust each, crop all, download a ZIP.",
    about: [
      "**IconVault**'s **Bulk Crop** crops a whole batch of photos to the same **aspect ratio** (Square, 16:9, 4:3 or 3:2) in one click, while keeping each photo's own resolution. Every image gets an **Adjust** button with a small preview where you drag the crop box to reposition it, so faces and subjects stay framed. Then **Crop N images** processes the batch and **Download all** grabs a ZIP.",
      "It is **free** to use and **private by design**: everything runs locally in your browser, so your photos never leave your device. **Pro** members get unlimited bulk crops for entire shoots and catalogs.",
    ],
    faqs: [
      { q: "Does bulk crop resize my photos?", a: "No. It crops each photo to the chosen ratio at its own resolution. A 4000x3000 photo cropped to 16:9 becomes 4000x2250, not a fixed small size." },
      { q: "Can I reposition the crop on individual photos?", a: "Yes. Click Adjust on any photo to open a preview where you drag the crop box to the best position before cropping the batch." },
      { q: "What does the None option do?", a: "None leaves photos untouched, useful when you only want to convert formats or just download the batch as a ZIP." },
      { q: "What output formats are supported?", a: "Each photo keeps its original format (JPG, PNG or WebP). Anything else is exported as JPG." },
      { q: "How many photos can I crop at once?", a: "Up to 50 per batch, with individual download buttons after cropping plus a one-click ZIP of everything." },
      { q: "Are my photos uploaded to a server?", a: "No. All cropping happens in your browser on your device. Your files never leave your device." },
    ],
    tags: ["bulk crop images", "crop multiple photos", "batch crop photos", "bulk image cropper", "crop photos to square", "batch crop to 16:9", "multiple image cropper", "crop many images at once", "bulk photo cropper", "free bulk crop", "crop images in bulk online", "batch photo crop tool", "crop all images same size ratio", "online bulk crop", "mass crop images", "crop product photos batch", "bulk crop jpg", "batch crop png", "photo batch cropper", "crop folder of images",
      "crop many photos",
      "batch photo cropper online",
      "multiple photo cropper",
      "bulk image cropper online",
      "crop images batch online",
      "mass photo cropper",
      "bulk crop tool",
      "batch crop images online",
      "crop multiple images online",
      "bulk photo editor crop",
      "crop all photos at once",
      "batch crop to square",
      "bulk crop png",
      "bulk crop to 1:1",
      "batch image cropper free",
      "crop photos in batch",
      "multiple image cropper online",
      "bulk crop photos online free",
      "batch crop jpg",
      "bulk image resizer cropper",
      "crop 100 images at once",
      "batch crop profile pictures",
      "bulk crop product images",
      "crop multiple pictures",
      "online batch cropper",
      "batch photo cutter",
      "bulk image cutter",
      "crop photos together",
      "same crop for multiple images",
      "apply same crop to all images",
      "batch cropper free",
      "bulk crop app",
      "crop multiple photos to same size",
      "bulk photo cropper free",
      "batch image crop tool",
      "multiple photos crop online",
      "crop images in bulk free",
      "bulk crop images online free",
      "photo batch crop",
      "batch crop photos online free"],
  };

export default seo;
