import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Can I NPM - Free Online npm Package Name Checker | IconVault",
    metaDescription: "Check npm package name availability in bulk with validation and alternative name suggestions. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Can I NPM** tells you instantly whether a package name is **available on npm**. Check names **in bulk**, get **validation** against npm's real naming rules (length, lowercase, allowed characters, scoped format), and receive **alternative name suggestions** when your first choice is taken. A **404 on the registry** means the name is free to claim.",
      "Checks run **fully in your browser** against the public npm registry, with nothing to install and nothing uploaded. It is **free** with no signup. The honest caveat: checking does not **reserve** the name. Anyone can publish it after you check, so publish promptly once you find a name you like."
    ],
    faqs: [
      { q: "How does the availability check work?", a: "The tool queries registry.npmjs.org for each name. If the registry returns 404, no package with that name exists and it is available. If it returns package data, the name is taken." },
      { q: "What makes an npm package name invalid?", a: "Names must be 214 characters or fewer, lowercase, with no spaces and no leading dot or underscore. Only letters, numbers and . _ ~ @ / - are allowed. Scoped names must look like @scope/name." },
      { q: "Can I check scoped names like @myorg/utils?", a: "Yes. Enter the full scoped name and the tool validates the @scope/name format, then checks the registry for that exact name." },
      { q: "Does checking a name reserve it for me?", a: "No. Availability checks never reserve anything. To claim a name you must publish a package under it (or contact npm support about an unpublished placeholder, subject to their policy)." },
      { q: "What do the name suggestions do?", a: "When a name is taken, the tool generates alternatives like name-js, name-cli and name-lib so you can find a free variant without starting your brainstorm over." },
      { q: "Is it really free?", a: "Yes. Unlimited name checks, no account, no signup. The npm registry is public and free to query." }
    ],
    tags: [
      "can i npm",
      "npm name checker",
      "npm package name availability",
      "check npm package name availability",
      "is npm package name available",
      "npm name availability checker",
      "npm package name validator",
      "npm naming rules",
      "npm package name generator",
      "npm name suggestions",
      "npm package name taken",
      "npm scoped package name",
      "npm package name search",
      "npm name check online",
      "npm name checker free",
      "npm package name availability checker online",
      "check if npm name is taken",
      "npm package name lookup",
      "npm registry name check",
      "npm valid package name",
      "npm package naming conventions",
      "npm package name rules",
      "npm name requirements",
      "npm package name length limit",
      "npm package name lowercase",
      "npm scope name checker",
      "check npm scope availability",
      "npm org name availability",
      "find available npm package name",
      "npm package name ideas",
      "npm package name brainstorm",
      "npm naming tool",
      "npm package title checker",
      "reserve npm package name",
      "claim npm package name",
      "npm publish name check",
      "before publishing to npm check name",
      "npm package name conflict",
      "npm duplicate package name",
      "npm package rename checker",
      "npm new package name",
      "npm library name checker",
      "npm module name availability",
      "npm module name checker",
      "check npm module name",
      "npm name availability bulk",
      "bulk npm name check",
      "npm name checker bulk",
      "npmjs name availability",
      "npmjs package name search",
      "npm package name availability test"
    ],
  };

export default seo;
