import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Case Converter - Free Text Case Tool | IconVault",
    metaDescription:
      "Convert text case free: UPPERCASE, lowercase, Title Case, camelCase, PascalCase, snake_case and kebab-case. Instant, in your browser.",
    about: [
      "**IconVault**'s **Case Converter** flips your **text** between every useful **case** in one click: **UPPERCASE**, lowercase, **Title Case**, **Sentence case**, **camelCase**, **PascalCase**, **snake_case**, **kebab-case**, aLtErNaTiNg and iNVERSE - for code, headlines and everything between.",
      "Paste once, copy any variant. Smart Title Case respects small words (a, the, of). All client-side, free, no account needed.",
    ],
    faqs: [
      {
        q: "Which cases are supported?",
        a: "UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, alternating and inverse.",
      },
      {
        q: "How does Title Case handle small words?",
        a: "Articles and short prepositions (a, an, the, of, in, on...) stay lowercase unless they're the first or last word - standard headline style.",
      },
      {
        q: "Can I convert code identifiers?",
        a: "Yes - camelCase, PascalCase, snake_case and kebab-case handle word boundaries from spaces, hyphens and underscores, ideal for renaming variables.",
      },
      {
        q: "Is there a text limit?",
        a: "No practical limit - conversion is instant and local in your browser.",
      },
    ],
    tags: [
      "case converter", "text case converter", "uppercase to lowercase",
      "convert to uppercase online", "title case converter", "camelcase converter",
      "snake case converter", "kebab case converter", "change text case",
      "uppercase converter", "lowercase converter", "free case converter",
    
      "convert case online",
      "change case online",
      "text case changer",
      "uppercase text online",
      "lowercase text online",
      "convert text to uppercase",
      "convert text to lowercase",
      "title case online",
      "sentence case converter",
      "capitalize text online",
      "alternating case generator",
      "inverse case converter",
      "toggle case online",
      "random case generator",
      "spongebob case converter",
      "camel case generator",
      "snake_case converter",
      "kebab-case generator",
      "pascal case converter",
      "constant case converter",
      "dot case converter",
      "path case converter",
      "header case converter",
      "train case generator",
      "convert to camelcase",
      "convert to snake_case",
      "convert to kebab-case",
      "variable name converter",
      "programmer case converter",
      "code case converter",
      "identifier case converter",
      "convert case free",
      "case converter no signup",
      "online text transformer",
      "text style converter",
      "uppercase lower case tool",
      "all caps converter",
      "all lowercase converter",
      "capitalize each word",
      "sentence capitalization",
      "proper case converter",
      "start case converter",
      "flip text case",
      "swap case online",
      "mocking text generator",
      "aesthetic text case",
      "small caps generator",
      "wide text generator"],
  };

export default seo;
