import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Channel Messaging - Interactive Lab | IconVault",
    metaDescription: "Real MessageChannel demos: entangled ports, structured-clone proof, and a port transferred to a Web Worker. Free, in-browser.",
    about: [ "**IconVault**'s **Channel Messaging** playground builds real `MessageChannel` ports: two entangled ports trade structured-cloned payloads in the page, and a second demo transfers a port into a genuine **Web Worker** (created from a Blob URL) that echoes messages back. A deliberate DataCloneError demo shows why functions cannot cross a port. It is free and runs fully in your browser.", "**MessageChannel** is the plumbing behind iframe-to-parent widgets, worker offloading, and cross-context libraries: one side of a port can be transferred to another context while staying a **private two-way pipe**. The lab makes the entanglement rule tangible (each port only hears the other), proves **structured cloning** with nested objects and dates, and shows the **transfer-list pattern** you need for worker communication." ],
    faqs: [ { q: "What is MessageChannel?", a: "It creates two entangled MessagePorts. Messages posted on port1 are delivered to port2's onmessage and vice versa. Ports can be transferred to workers and iframes, keeping a private two-way channel across contexts." }, { q: "What is structured cloning?", a: "The serialization used when posting messages: objects, arrays, Dates, Maps, Sets, Blobs and ArrayBuffers are deep-copied. Functions, DOM nodes and some host objects throw DataCloneError instead, which this playground demonstrates on purpose." }, { q: "How do I give a port to a Web Worker?", a: "Pass it in the transfer list: worker.postMessage({type:'init'}, [port2]). The worker receives it on event.ports[0]. After transfer the port is neutered on the sending side." }, { q: "When do I need MessageChannel instead of BroadcastChannel?", a: "Use MessageChannel for private one-to-one pipes (page to worker, parent to one iframe). Use BroadcastChannel when every same-origin context should hear the message." }, { q: "Do ports need to be started?", a: "MessagePorts created by MessageChannel start automatically. Ports received via transfer in some older setups needed port.start(); calling it unconditionally is harmless." }, { q: "Is any message sent to a server?", a: "No. Ports, workers and structured clones are all local to your browser. The trial counter is a localStorage number." } ],
    tags: [ "messagechannel", "message channel api", "messagechannel javascript", "messageport", "message channel example", "messagechannel demo", "messageport example", "entangled ports", "transfer port to worker", "worker postmessage port", "postmessage transfer list", "structured clone", "structuredclone", "datacloneerror", "cannot clone function postmessage", "what can be structured cloned", "messagechannel vs broadcastchannel", "broadcastchannel vs messagechannel", "web worker communication", "page to worker messaging", "iframe parent postmessage port", "messagechannel tutorial", "mdn messagechannel", "messagechannel typescript", "messagechannel browser support", "messageport onmessage", "port.postmessage", "event.ports", "messagechannel react", "offload to web worker", "worker echo example", "blob url worker", "new worker blob", "transferable objects", "neutered port", "messagechannel close", "how to use messagechannel", "messagechannel step by step", "channel messaging api", "cross context messaging", "two way communication worker", "test messagechannel online", "messagechannel playground", "messageport demo", "web worker ports", "messagechannel example code", "messageport transfer", "worker communication javascript", "structured clone example", "postmessage port" ],
  };

export default seo;
