import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Character Counter - Free | IconVault",
    metaDescription:
      "Count characters free: with and without spaces, lines, words and bytes. Live counts for tweets, meta tags and forms.",
    about: [
      "**IconVault**'s **Character Counter** gives you every **character** metric that matters: with and without **spaces**, **lines**, words, **bytes** (UTF-8) and remaining-count against common limits like tweets, SMS and **meta descriptions**.",
      "Counts update live with Unicode-aware accuracy (emoji count as one character, not two). Your text never leaves your browser. Free, no account.",
    ],
    faqs: [
      {
        q: "Do emoji count as one character?",
        a: "Yes - the counter is Unicode-aware, so emoji and accented characters count as single characters, matching how platforms count them.",
      },
      {
        q: "What's the difference from Word Counter?",
        a: "This tool focuses on character-level limits: tweets (280), SMS segments (160), meta titles/descriptions - with with/without-spaces and byte counts.",
      },
      {
        q: "Can I check remaining characters for a limit?",
        a: "Yes - set any custom limit and the tool shows characters remaining, turning red when you go over.",
      },
      {
        q: "Is my text uploaded?",
        a: "No. Everything is computed locally in your browser.",
      },
    ],
    tags: [
      "character counter", "char counter", "count characters online",
      "character count tool", "characters with and without spaces",
      "tweet character counter", "sms character counter", "letter counter",
      "byte counter", "text length checker", "free character counter",
    
      "count characters",
      "characters counter online",
      "count letters in text",
      "character count online free",
      "text character counter",
      "count characters and words",
      "character counter tool",
      "letters counter",
      "character length checker",
      "count chars online",
      "character count checker",
      "count characters free",
      "online character counter tool",
      "tweet length checker",
      "twitter character limit",
      "x character limit checker",
      "sms length checker",
      "meta title character limit",
      "meta description character limit",
      "seo title length",
      "character counter with spaces",
      "character counter without spaces",
      "count characters no spaces",
      "letter count tool",
      "digit counter",
      "count numbers in text",
      "word and character counter",
      "sentence length checker",
      "paragraph length checker",
      "text length calculator",
      "character limit checker",
      "count characters in word",
      "count characters in sentence",
      "count characters in paragraph",
      "bio character counter",
      "instagram bio character limit",
      "youtube title character limit",
      "headline character counter",
      "free char counter",
      "character counter no signup",
      "instant character count",
      "real time character counter",
      "live character counter",
      "text counter online",
      "glyph counter",
      "unicode character counter",
      "emoji counter",
      "count emojis in text",
      "special character counter"],
  };

export default seo;
