import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Trad/Simp Converter - Free Online Chinese Character Converter | IconVault",
    metaDescription: "Convert between Simplified and Traditional Chinese instantly with a built-in character table. Free, runs fully in your browser, no uploads.",
    about: [
      "**IconVault**'s **Trad/Simp Converter** switches text between **Simplified Chinese** and **Traditional Chinese** in one click using a built-in common-character table. Paste a paragraph, pick the direction, and get the converted result with a copy button. It is free and runs fully in your browser, so nothing you paste ever leaves your device.",
      "The converter covers frequent **simplified/traditional character pairs** such as 爱/愛, 国/國 and 学/學, which handles everyday text like product copy, subtitles and emails. Rare or variant characters that are not in the table pass through unchanged, so always **proofread names and specialized terms** before publishing. There is no sign-up and **no server round trip**."
    ],
    faqs: [
      { q: "How does the Simplified to Traditional conversion work?", a: "The tool matches each character against a built-in table of common simplified/traditional pairs and swaps them. Conversion happens instantly in your browser, character by character." },
      { q: "Is the conversion 100 percent accurate?", a: "For common characters, yes. The table covers frequent pairs only, so rare characters, regional variants and characters with multiple readings pass through unchanged. Proofread anything important, especially proper nouns." },
      { q: "Can it convert Traditional Chinese to Simplified?", a: "Yes, it works in both directions. The same character table is applied in reverse, so you can convert Traditional text into Simplified with one click." },
      { q: "Does my text get uploaded anywhere?", a: "No. Conversion runs entirely in your browser with a local lookup table. Your text is never sent to a server, which makes it safe for drafts and sensitive documents." },
      { q: "Does it handle Cantonese-specific characters?", a: "Only where they overlap with the common pairs table. Cantonese-specific characters and some Hong Kong/Taiwan variants are not covered and will pass through unchanged." },
      { q: "Why would I convert between Simplified and Traditional?", a: "Mainland China uses Simplified; Hong Kong, Taiwan and Macau use Traditional. Converting lets you localize marketing copy, subtitles, product pages and emails for each audience quickly."
      }
    ],
    tags: [
      "simplified to traditional chinese converter",
      "traditional to simplified chinese converter",
      "chinese character converter",
      "convert simplified chinese to traditional",
      "convert traditional chinese to simplified",
      "simplified vs traditional chinese",
      "chinese converter online free",
      "simp to trad chinese",
      "trad to simp chinese",
      "chinese text converter",
      "simplified chinese translator to traditional",
      "traditional chinese translator to simplified",
      "convert chinese characters online",
      "chinese simplified traditional tool",
      "free chinese converter",
      "chinese character conversion tool",
      "simplified chinese to traditional chinese online",
      "traditional chinese to simplified chinese online",
      "convert chinese text simplified",
      "chinese localization tool",
      "convert mandarin simplified to traditional",
      "hk traditional chinese converter",
      "taiwan traditional chinese converter",
      "mainland simplified chinese converter",
      "chinese script converter",
      "convert chinese pinyin characters",
      "simplified chinese characters list converter",
      "traditional chinese characters list converter",
      "bulk convert chinese simplified traditional",
      "chinese subtitle converter simplified traditional",
      "convert document chinese simplified",
      "online chinese character table converter",
      "chinese variant character converter",
      "fan ti zi converter",
      "jian ti zi converter",
      "fantizi to jiantizi",
      "jiantizi to fantizi",
      "convert chinese essay simplified",
      "chinese email converter traditional",
      "convert product description chinese",
      "website chinese localization simplified traditional",
      "convert wechat message chinese traditional",
      "chinese name converter simplified traditional",
      "learn simplified vs traditional chinese",
      "difference simplified traditional chinese characters",
      "chinese writing system converter",
      "convert cantonese text simplified traditional",
      "traditional chinese input converter",
      "simplified chinese input converter",
      "instant chinese converter no signup",
      "browser chinese converter private"
    ],
  };

export default seo;
