import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Circle Crop - Free Online Tool | IconVault",
    metaDescription: "Crop any photo into a perfect circle with an optional colored border. Free, private, in-browser circle cropper.",
    about: [
      "**IconVault**'s **Circle Crop** turns any photo into a perfect circle, ideal for **profile pictures** and **avatars**. Drag to position the photo, zoom in for the perfect framing, and add a colored border ring if you like. Everything runs **free** and **browser-private**, your photo never leaves your device.",
      "The result is always a **PNG with transparent corners**, so it blends into any background. Choose 256, 512 or 1024px, or keep the original resolution. **Pro** members get unlimited use with no trial limits.",
    ],
    faqs: [
      { q: "How do I crop a photo into a circle?", a: "Drop your image into the Circle Crop tool, drag to position it inside the circle, adjust the zoom if needed, then download a PNG with transparent corners." },
      { q: "Can I add a colored ring around the circle?", a: "Yes. Use the border width slider and color picker to add a ring in any color around your circle crop." },
      { q: "What size should I use for a profile picture?", a: "512px works well for most social profiles. The tool also offers 256px, 1024px, or the original resolution of your photo." },
      { q: "Does the circle crop keep the background transparent?", a: "Yes. The corners outside the circle are fully transparent, so the circle blends into any background." },
      { q: "Is my photo uploaded anywhere?", a: "No. The crop happens entirely in your browser, so your photos stay private on your own device." },
      { q: "Is the circle crop tool free?", a: "Yes, free users get a generous number of uses. Pro members get unlimited use of every tool." },
    ],
    tags: [ "circle crop image", "crop photo into circle online", "circular profile picture maker", "round image cropper", "circle crop photo free", "make image circular", "profile picture cropper", "avatar circle crop", "crop image to circle png", "round photo maker online", "circular image with border", "circle crop with transparent background", "profile photo maker", "crop picture round", "circle image generator", "round avatar maker", "circle crop online free", "circular crop tool", "crop photo round shape", "instagram profile circle crop" ,
      "circle crop",
      "crop image circle",
      "round crop image",
      "circular crop",
      "circle image cropper",
      "make photo circular",
      "circle profile photo",
      "crop to circle online",
      "circle crop png",
      "round photo crop",
      "circular avatar maker",
      "crop image in circle",
      "circle crop maker",
      "round image maker",
      "circle crop tool online",
      "profile pic circle maker",
      "crop picture in circle",
      "circle crop photo online",
      "round crop photo",
      "circular photo cropper",
      "make round profile picture",
      "crop image round shape",
      "circle thumbnail maker",
      "round logo cropper",
      "crop photo to circle online free",
      "circular image cropper online",
      "circle crop jpg",
      "round crop online",
      "make image round",
      "circle photo frame",
      "round profile picture maker",
      "crop in circle shape",
      "circle avatar generator",
      "circular profile pic",
      "crop photo circle free",
      "round image cropper online",
      "circle cutout image",
      "circular crop online free",
      "make circular avatar",
      "round photo editor"],
  };

export default seo;
