import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Clipboard API - Interactive Lab | IconVault",
    metaDescription: "Real Clipboard API lab: multi-MIME writes, image copy, custom formats and full clipboard.read() inspection. Free, in-browser.",
    about: [ "**IconVault**'s **Clipboard API** playground performs real clipboard operations: `writeText`, multi-MIME `ClipboardItem` writes (rich HTML, a canvas-generated PNG, and a custom `web` format), and a full `clipboard.read()` inspector that lists every MIME type on the clipboard and renders images inline. A live support matrix shows exactly which operations your browser allows. It is free and runs fully in your browser.", "The lab teaches the rules that bite in production: secure context plus focus plus user gesture, why **`read()`** can throw **`NotAllowedError`**, Firefox's text-only limitation, and the `web ` prefix required for custom formats. Copy the sample image, then read it back to watch **`image/png`** round-trip through your **real system clipboard**." ],
    faqs: [ { q: "What is the Async Clipboard API?", a: "navigator.clipboard exposes promise-based read and write: writeText/readText for plain text, and write()/read() with ClipboardItem for multiple MIME types such as text/html and image/png, all without hidden textareas or execCommand." }, { q: "Why did clipboard.read() throw NotAllowedError?", a: "Reading the clipboard is gated: the document must be focused, the call must come from a user gesture, the page must be a secure context, and the browser may require the clipboard-read permission. This tool surfaces the permission states so you can see why." }, { q: "Which browsers support image copy?", a: "Chrome, Edge and Safari support writing image/png via ClipboardItem. Firefox currently supports only readText/writeText. The support matrix in the tool detects this live." }, { q: "What are custom clipboard formats?", a: "On write, Chrome accepts vendor types prefixed with web (for example web text/x-myapp-note), letting apps round-trip private data alongside standard fallbacks like text/plain." }, { q: "Is the old document.execCommand('copy') still needed?", a: "Only as a fallback for very old browsers. The Async Clipboard API is supported in all modern browsers for text, and this playground shows exactly where each browser stands." }, { q: "Can websites read my clipboard silently?", a: "No. Reads require focus and a user gesture, and browsers may prompt. That is why the Read button here only works when you click it deliberately." } ],
    tags: [ "clipboard api", "navigator.clipboard", "async clipboard api", "clipboard.write", "clipboard.read", "clipboarditem", "copy to clipboard javascript", "javascript copy text", "copy image to clipboard", "copy html to clipboard", "clipboard api example", "clipboard api demo", "writetext", "readtext", "clipboard read image", "paste image javascript", "clipboarditem image png", "custom clipboard format", "web text clipboard", "clipboard api browser support", "clipboard api firefox", "clipboard api safari", "clipboard notallowederror", "clipboard-read permission", "clipboard-write permission", "permissions.query clipboard", "secure context clipboard", "mdn clipboard api", "clipboard api tutorial", "clipboard api typescript", "how to copy rich text javascript", "copy formatted text web", "execcommand copy alternative", "clipboard polyfill", "react copy to clipboard", "clipboard api mobile", "clipboard api https", "read clipboard contents", "inspect clipboard mime types", "gettype clipboarditem", "clipboardItem.types", "copy canvas to clipboard", "canvas toblob clipboard", "paste event vs clipboard api", "clipboard api limits", "is clipboard api supported", "caniuse clipboard", "test clipboard api online", "clipboard playground", "clipboard lab" ],
  };

export default seo;
