import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Code Formatter - Free Online Code Beautifier | IconVault",
    metaDescription: "Format JS, TS, CSS, HTML, JSON, YAML and Markdown with clean indentation and spacing. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Code Formatter** cleans up messy code with proper **indentation**, brace placement and spacing for **JavaScript/TypeScript, CSS, HTML, JSON, YAML and Markdown**. Paste your code, hit format, and copy the tidy result. It is free and runs fully in your browser, so your code never leaves your machine.",
      "This is a **lightweight formatter**, not a full **Prettier** port: it normalizes indentation, brace newlines and spacing so unreadable minified or hand-mangled code becomes readable again. It is ideal for quick cleanups, debugging pasted snippets and preparing code for docs. For project-wide enforced style, a dedicated formatter in your build pipeline is still the right tool."
    ],
    faqs: [
      { q: "Which languages does the code formatter support?", a: "JavaScript/TypeScript, CSS, HTML, JSON, YAML and Markdown. Each language gets indentation, brace newline and spacing rules suited to its syntax." },
      { q: "Is this as powerful as Prettier?", a: "No, and it is honest about that. This is a lightweight in-browser formatter for quick cleanups. Prettier or your editor's formatter is better for project-wide enforced style." },
      { q: "Can it format minified code?", a: "Yes. Paste minified JS, CSS or HTML and the formatter expands it into readable indented code, which makes debugging copied production snippets much easier." },
      { q: "Does it validate JSON?", a: "It will format valid JSON with clean indentation. If the JSON is malformed, formatting fails on the broken structure, which itself is a quick signal that something is wrong." },
      { q: "Is my code uploaded to a server?", a: "No. Formatting runs entirely in your browser. You can safely format proprietary or sensitive code without it ever leaving your device." },
      { q: "Can I customize indentation (tabs vs spaces)?", a: "The tool applies consistent indentation rules per language. For full style control like tab width and quote style, pair it with a configurable formatter in your editor."
      }
    ],
    tags: [
      "code formatter",
      "online code formatter",
      "code beautifier",
      "free code formatter",
      "javascript formatter online",
      "js formatter",
      "typescript formatter online",
      "css formatter online",
      "html formatter online",
      "json formatter",
      "yaml formatter online",
      "markdown formatter",
      "format code online free",
      "code beautifier online",
      "js beautify online",
      "css beautifier",
      "html beautifier",
      "json beautifier",
      "prettify code online",
      "code indenter",
      "auto indent code online",
      "format minified javascript",
      "unminify js online",
      "unminify css online",
      "format javascript code",
      "format typescript code",
      "format css code",
      "format html code",
      "format json online free",
      "json pretty print online",
      "yaml pretty print",
      "tidy html online",
      "code cleanup tool",
      "online prettier alternative",
      "lightweight code formatter",
      "format code in browser",
      "no signup code formatter",
      "paste and format code",
      "javascript code tidier",
      "css code tidier",
      "fix indentation code online",
      "brace placement formatter",
      "code spacing normalizer",
      "format snippet for documentation",
      "readable code from minified",
      "online code formatter no upload",
      "private code formatter",
      "quick code cleanup",
      "format yaml file online",
      "format markdown code blocks",
      "json formatter with indentation",
      "css formatter with line breaks"
    ],
  };

export default seo;
