import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Color Palette Extractor - Free Online Tool | IconVault",
    metaDescription: "Extract the dominant colors from any image as click-to-copy HEX swatches. Free, private, works in your browser.",
    about: [
      "**IconVault**'s **Color Palette Extractor** finds the dominant colors in any photo or artwork using **median-cut quantization**, the same technique professional tools use. Drop an image, choose how many colors you want (2 to 12), and get a clean swatch strip of the palette, each one **click-to-copy** as HEX.",
      "The tool ignores transparent pixels, so PNGs with alpha give clean results, and it runs **entirely in your browser**: nothing is uploaded anywhere. Perfect for building a brand palette from a logo, matching UI colors to a photo, or stealing a color scheme you love. **Free** to use daily, unlimited with Pro.",
    ],
    faqs: [
      { q: "How does the palette extraction work?", a: "The image is downscaled and its opaque pixels are quantized with median-cut: pixels are grouped by color and each box is split along its widest channel until the target number of colors is reached, then each group's average becomes a swatch." },
      { q: "Why are transparent pixels ignored?", a: "Alpha-channel pixels carry no real color information, so the extractor skips any pixel under 50% opacity. That keeps palettes from PNGs with transparency honest." },
      { q: "Can I copy all colors at once?", a: "Yes. Use the Copy all HEX values button to get the whole palette as a comma-separated list for pasting into CSS or design tools." },
      { q: "How many colors can I extract?", a: "The slider runs from 2 to 12 colors. Six is a good default for most photos; logos often look best with 3 to 5." },
      { q: "Is my image uploaded anywhere?", a: "No. Everything is computed locally in your browser. Your files never leave your device." },
      { q: "Is there a limit on free uses?", a: "The free trial covers a set number of extractions per day. IconVault Pro unlocks unlimited uses across every tool." },
    ],
    tags: [ "color palette extractor", "extract colors from image", "image color palette", "dominant colors from photo", "palette generator from image", "hex palette from photo", "photo color scheme", "color picker from image", "median cut palette", "brand colors from logo", "color swatches from picture", "get colors of image", "image to hex palette", "color palette finder", "ui colors from photo", "photo palette generator", "extract hex codes from image", "picture color analyzer", "design palette from photo", "free color palette tool" ,
      "color palette generator",
      "image to palette",
      "photo to palette",
      "color scheme generator from image",
      "extract palette from image",
      "dominant color extractor",
      "image color analyzer",
      "palette from photo",
      "color palette from picture",
      "image color scheme",
      "photo color palette generator",
      "get palette from image",
      "color palette creator",
      "image color extraction",
      "photo palette maker",
      "color palette tool",
      "extract color scheme from photo",
      "image to color palette online",
      "dominant colors extractor",
      "photo to color palette",
      "color palette from image online",
      "picture to palette",
      "image color palette generator free",
      "top colors in image",
      "most used colors in photo",
      "color histogram tool",
      "image color distribution",
      "photo color breakdown",
      "palette generator online",
      "create palette from image",
      "logo color extractor",
      "website color palette from image",
      "brand palette generator",
      "image color theme",
      "photo color theme generator",
      "extract dominant colors",
      "color palette inspiration",
      "rgb palette from image",
      "image color codes",
      "palette extractor online"],
  };

export default seo;
