import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Compress to Exact KB - Free Online Tool | IconVault",
    metaDescription: "Shrink any image to an exact KB size free in your browser. Perfect for form uploads with strict file size limits.",
    about: [
      "**IconVault**'s **Compress to Exact KB** hits a precise file size target, like 50 KB or 200 KB, for forms and portals that reject oversized uploads. Pick a preset (**20, 50, 100, 200 or 500 KB**) or enter a custom value, choose **JPG or WebP**, and the tool lowers quality first; if that isn't enough, it scales the image down until it fits. You see the final size, quality and dimensions before downloading.",
      "It is **free** to use and **private by design**: everything runs in your browser, so sensitive documents like ID photos never leave your device. **Pro** members get unlimited exact-size compressions.",
    ],
    faqs: [
      { q: "How does it reach an exact KB size?", a: "It binary-searches the quality setting first, keeping full resolution as long as possible. Only if quality alone cannot hit the target does it scale the image down, step by step." },
      { q: "Why isn't PNG offered as an output?", a: "PNG is lossless, so it can't be squeezed to an exact size. JPG and WebP allow quality tuning, which is what makes precise targets possible." },
      { q: "What if the target is impossibly small?", a: "The tool will tell you honestly: if even the smallest attempt exceeds the target, you get the smallest version it could produce, clearly labeled." },
      { q: "Is this good for job applications and exam forms?", a: "Yes, that is exactly what it is built for: photo and signature uploads with strict limits like 20 KB, 50 KB or 100 KB." },
      { q: "Are my documents uploaded anywhere?", a: "No. All processing happens locally in your browser. Your files never leave your device." },
      { q: "Can I set a custom KB value?", a: "Yes, choose Custom and type any size in KB, such as 37 KB or 1024 KB." },
    ],
    tags: ["compress image to exact kb", "reduce image to 100kb", "compress photo to 50kb", "image size reducer kb", "compress jpg to 200kb", "reduce photo to 20kb", "exact file size compressor", "shrink image to specific size", "compress image to 500kb", "photo kb reducer", "resize image to kb online", "compress signature to 20kb", "id photo kb compressor", "exam form photo compressor", "free kb compressor", "image kb size reducer", "compress to target file size", "online image sizer kb", "reduce image below 100kb", "kb image compressor",
      "compress image to 100kb",
      "reduce image to 50kb",
      "compress photo to 100kb",
      "image to 100kb",
      "photo to 50kb",
      "compress image to 200kb",
      "reduce image to 200kb",
      "compress image to 20kb",
      "photo to 20kb",
      "compress image to 400kb",
      "reduce image to 500kb",
      "compress jpg to 100kb",
      "compress png to 100kb",
      "image kb compressor online",
      "target kb image compressor",
      "compress photo to exact size",
      "reduce photo to exact kb",
      "image file size compressor",
      "set image file size",
      "compress image below 50kb",
      "compress image under 100kb",
      "reduce image under 200kb",
      "compress photo to 30kb",
      "image to 30kb",
      "compress signature to 50kb",
      "compress photo to 10kb",
      "image to 10kb converter",
      "compress image to 1mb",
      "reduce image to 1mb",
      "compress photo to 300kb",
      "image to 300kb",
      "exact kb photo compressor",
      "compress image to specific kb",
      "online kb photo compressor",
      "reduce jpg to exact kb",
      "compress image file size online",
      "photo size in kb reducer",
      "compress image to 150kb",
      "reduce image to 150kb",
      "compress image to 250kb"],
  };

export default seo;
