import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Compress GIF - Free Online Tool | IconVault",
    metaDescription: "Shrink animated GIFs online: fewer colors, frame dropping, lossy differencing. Free, private, in-browser.",
    about: [
      "**IconVault**'s **Compress GIF** tool shrinks heavy animated GIFs with four independent levers: a smaller **color palette** (256 down to 32), **frame dropping** that keeps every 2nd, 3rd or 4th frame while the **total duration stays the same**, a **lossy** slider that treats near-identical pixels as unchanged via transparent diff frames, and a **size** slider, plus optional **Bayer dithering** for smoother gradients.",
      "It is **free** and runs **100% in your browser**, with an **animated preview** of the result and honest **before and after sizes** so you can see exactly what each setting costs. Your GIF never leaves your device. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "How does GIF compression work here?", a: "Four ways: fewer palette colors, dropping frames (duration preserved), lossy frame differencing that stores only changed pixels, and scaling the GIF down. You control each one." },
      { q: "What does the lossy slider do?", a: "It treats near-identical pixels between frames as unchanged and stores them as transparent diff data, which compresses far better. Higher values mean smaller files with more visible change." },
      { q: "Does dropping frames change the timing?", a: "No. The delays of dropped frames are added to the kept frame, so the total duration stays exactly the same." },
      { q: "What is dithering?", a: "An ordered Bayer pattern that smooths gradients when you use few colors. It can slightly increase file size but looks better on photos." },
      { q: "Is my GIF uploaded?", a: "No. Compression happens entirely in your browser. Your GIF never leaves your device." },
      { q: "Is it free?", a: "Yes, with 5 free compressions. Pro members get unlimited runs plus HD exports and every template across all IconVault tools." },
    ],
    tags: [ "compress gif", "gif compressor", "reduce gif size", "shrink gif online", "gif optimizer", "make gif smaller", "compress animated gif", "gif size reducer", "optimize gif online", "lossy gif compression", "gif to smaller gif", "reduce gif file size", "gif compressor free", "online gif optimizer", "gif quality reducer", "smaller gif maker", "gif compression tool", "animated gif shrinker", "gif file shrinker", "free gif compressor" ,
      "gif size compressor",
      "compress gif online free",
      "reduce animated gif size",
      "gif file compressor",
      "shrink animated gif",
      "optimize animated gif",
      "compress gif without losing quality",
      "gif optimizer online",
      "reduce gif mb",
      "compress gif to kb",
      "gif compressor online",
      "make animated gif smaller",
      "gif shrinker online",
      "compress gif for discord",
      "gif compressor for discord",
      "compress gif for whatsapp",
      "reduce gif size for discord",
      "gif size reducer online",
      "compress large gif",
      "gif compression online",
      "optimize gif file size",
      "shrink gif file",
      "gif optimizer free",
      "compress gif for email",
      "reduce gif file size online",
      "gif compressor no signup",
      "compress gif image",
      "gif size optimizer",
      "make gif file smaller",
      "compress gif to 1mb",
      "gif compressor tool online",
      "reduce gif quality",
      "gif file size reducer",
      "compress animated gif online",
      "online gif compressor free",
      "gif shrinker free",
      "compress gif for website",
      "faster loading gif",
      "gif optimizer tool",
      "compress gif download"],
  };

export default seo;
