import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Compress JPG - Free Online Tool | IconVault",
    metaDescription: "Compress JPG images free in your browser. Shrink file sizes with no visible quality loss, no uploads, no watermarks.",
    about: [
      "**IconVault**'s **Compress JPG** shrinks your photos right in the browser, with a simple **quality slider** (default 75%) that balances file size against visible detail. Settings of 60 to 80% are usually indistinguishable from the original for everyday photos, and the tool processes **up to 50 images at once**, each with its own download button plus a combined ZIP.",
      "It is **free** to use, **private by design** (your files never leave your device), and honest about results: if a compressed file would end up larger than the original, you simply get the **original back**. **Pro** members get unlimited compressions.",
    ],
    faqs: [
      { q: "Will compressing reduce the visible quality of my photos?", a: "Barely. At 60 to 80% quality, the difference is usually invisible to the eye while file sizes drop dramatically. Drop the slider lower only when you need the absolute smallest file." },
      { q: "Can I compress many JPGs at once?", a: "Yes, you can add up to 50 images in one batch. Each file gets its own download button, and you can also grab everything as a single ZIP." },
      { q: "What happens if compression makes a file bigger?", a: "You get the original file back. The tool never outputs a file larger than the one you uploaded." },
      { q: "Are my photos uploaded to a server?", a: "No. All compression happens locally in your browser using your device's processor. Your files never leave your device." },
      { q: "Can I compress PNG or WebP files here?", a: "This tool accepts JPG, PNG and WebP inputs, but the output is always JPG. For PNG and WebP output, use the dedicated Compress PNG and Compress WebP tools." },
      { q: "Is there a limit on how many times I can use it?", a: "Visitors get 5 free compressions, and Pro members get unlimited use with no watermarks on anything." },
    ],
    tags: ["compress jpg", "reduce jpg size", "jpg compressor", "shrink jpg file size", "compress jpeg online", "reduce jpeg size", "jpg size reducer", "compress photo online", "make jpg smaller", "jpg optimizer", "bulk jpg compressor", "compress multiple jpg", "reduce image file size", "photo compressor online", "free jpg compressor", "jpg compression tool", "decrease jpg size", "compress jpg without losing quality", "online image compressor", "jpg to smaller jpg",
      "jpg compressor online",
      "compress jpg online free",
      "reduce jpg file size",
      "jpeg compressor",
      "compress jpeg",
      "jpeg size reducer",
      "shrink jpeg",
      "optimize jpeg",
      "jpeg optimizer online",
      "compress photo jpg",
      "jpg file compressor",
      "reduce photo size jpg",
      "compress jpg to kb",
      "jpg compressor free online",
      "compress jpg image",
      "online jpg compressor",
      "jpg shrinker",
      "jpeg file compressor",
      "compress jpeg without losing quality",
      "jpg compression online",
      "make jpeg smaller",
      "reduce jpeg file size",
      "compress jpg for email",
      "jpg optimizer free",
      "compress jpg to 100kb",
      "jpg file size reducer",
      "compress jpg no signup",
      "jpeg compressor online free",
      "shrink jpg online",
      "optimize jpg online",
      "compress jpg download",
      "reduce jpg mb to kb",
      "jpg size optimizer",
      "compress image jpg",
      "jpeg image compressor",
      "photo size reducer jpg",
      "compress jpg quality",
      "jpg compress tool",
      "free online jpg compressor",
      "compress jpg for website"],
  };

export default seo;
