import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Compress WebP - Free Online Tool | IconVault",
    metaDescription: "Compress WebP images free in your browser. Smaller files with a quality slider, and the original back if it can't shrink.",
    about: [
      "**IconVault**'s **Compress WebP** squeezes modern WebP images even smaller with an adjustable **quality slider** (default 70%). WebP already compresses well, so the tool is honest about results: **if a file can't get smaller, you get the original back**, never a larger file. Batch **up to 50 images** with per-file downloads and a combined ZIP.",
      "It is **free** to use and **private by design**: every byte is processed locally in your browser, so your files never leave your device. **Pro** members get unlimited compressions for whole-site image pipelines.",
    ],
    faqs: [
      { q: "Why compress WebP if it is already efficient?", a: "WebP files from cameras and design tools are often saved at very high quality. Dropping to 60-80% quality can cut the file size in half with no visible difference." },
      { q: "What if my WebP is already fully optimized?", a: "Then you get the original file back. The tool compares sizes and never returns a file larger than your upload." },
      { q: "Does it keep transparency?", a: "Yes, WebP alpha transparency is preserved through compression." },
      { q: "Can I convert other formats to WebP here?", a: "This tool accepts JPG, PNG and WebP inputs and always outputs WebP, so it doubles as a quick converter to WebP." },
      { q: "Are my files uploaded to a server?", a: "No. Compression runs entirely in your browser. Your images never leave your device." },
      { q: "How many files can I compress at once?", a: "Up to 50 per batch, each with its own download button, plus a single ZIP for everything." },
    ],
    tags: ["compress webp", "reduce webp size", "webp compressor", "shrink webp file size", "webp optimizer", "compress webp online", "reduce webp file size", "make webp smaller", "bulk webp compressor", "free webp compressor", "webp compression tool", "decrease webp size", "optimize webp images", "webp size reducer", "compress webp without losing quality", "online webp compressor", "convert jpg to webp compressed", "convert png to webp", "webp file shrinker", "compress webp images",
      "webp compressor online",
      "compress webp online free",
      "reduce webp file size online",
      "webp file compressor",
      "shrink webp online",
      "optimize webp",
      "webp optimizer free",
      "compress webp image",
      "online webp compressor free",
      "webp shrinker",
      "compress webp to kb",
      "webp compression online",
      "reduce webp mb",
      "compress webp no signup",
      "webp file size reducer",
      "compress webp download",
      "make webp file smaller",
      "webp size optimizer",
      "compress webp for website",
      "lossless webp compression",
      "webp compressor lossless",
      "compress transparent webp",
      "reduce webp image size",
      "webp optimizer tool",
      "compress webp quality",
      "shrink webp file",
      "webp image optimizer",
      "compress webp to 200kb",
      "free webp optimizer",
      "webp compress tool online",
      "optimize webp images online",
      "compress webp without quality loss",
      "webp file shrinker online",
      "reduce webp resolution size",
      "compress webp batch",
      "webp compressor website",
      "compress webp for email",
      "webp image size reducer",
      "compress animated webp",
      "webp size reducer tool"],
  };

export default seo;
