import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Compress PNG - Free Online Tool | IconVault",
    metaDescription: "Compress PNG images free in your browser with smart color reduction. Fewer colors, smaller files, no uploads.",
    about: [
      "**IconVault**'s **Compress PNG** shrinks PNG files with **median-cut color quantization**: you choose how many colors to keep (256, 128, 64, 32 or 16), and the tool rebuilds the image with an optimized palette. Fewer colors means a smaller file, and it works best on **logos, icons and graphics** with flat colors. Process **up to 50 images at once**, each with its own download button plus a combined ZIP.",
      "It is **free** to use and **private by design**: everything runs locally in your browser, so your files never leave your device. **Pro** members get unlimited compressions and can batch entire asset folders without hitting the trial cap.",
    ],
    faqs: [
      { q: "How does PNG compression work here?", a: "The tool reduces the number of colors in the image using median-cut quantization. A logo with flat colors often looks identical at 64 or 32 colors while the file becomes a fraction of its original size." },
      { q: "How many colors should I keep?", a: "Start with 256 for photos and complex graphics, then try 128 or 64 for logos and icons. If banding appears, step back up one level." },
      { q: "Will transparency be preserved?", a: "Yes. Fully transparent pixels stay transparent in the compressed PNG." },
      { q: "Is this good for compressing photos saved as PNG?", a: "It works, but photos have millions of colors, so consider the Compress JPG or Compress WebP tools instead for much smaller photographic files." },
      { q: "Are my images uploaded anywhere?", a: "No. All processing happens in your browser on your own device. Nothing is sent to a server." },
      { q: "Can I compress multiple PNGs at once?", a: "Yes, up to 50 files per batch, with individual download buttons and a one-click ZIP of everything." },
    ],
    tags: ["compress png", "reduce png size", "png compressor", "shrink png file size", "png optimizer", "reduce png file size online", "compress png without losing quality", "png size reducer", "make png smaller", "bulk png compressor", "pngquant alternative online", "reduce png colors", "compress logo png", "free png compressor", "png compression tool", "decrease png size", "optimize png online", "png file shrinker", "compress png images", "online png compressor",
      "png compressor online",
      "compress png online free",
      "reduce png file size",
      "png file compressor",
      "shrink png online",
      "optimize png",
      "png optimizer free",
      "compress png image",
      "online png compressor free",
      "png shrinker",
      "compress png to kb",
      "png compression online",
      "reduce png mb",
      "compress png no signup",
      "png file size reducer",
      "compress png download",
      "make png file smaller",
      "png size optimizer",
      "compress png for website",
      "lossless png compression",
      "png compressor lossless",
      "compress transparent png",
      "reduce png image size",
      "png optimizer tool",
      "compress png quality",
      "shrink png file",
      "png image optimizer",
      "compress png to 200kb",
      "free png optimizer",
      "png compress tool online",
      "optimize png images",
      "compress png without quality loss",
      "png file shrinker online",
      "reduce png resolution size",
      "compress png batch",
      "png compressor website",
      "compress screenshot png",
      "png size reducer online",
      "compress png for email",
      "tiny png alternative"],
  };

export default seo;
