import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "ContentEditable Playground - Free Online Tool | IconVault",
    metaDescription: "Experiment with contenteditable: execCommand toolbar, plaintext-only mode, live selection inspector and HTML output. Free, in-browser.",
    about: [
      "**IconVault**'s **ContentEditable Playground** is a hands-on lab for browser rich-text editing. Format text with an execCommand toolbar, switch between rich-text and plaintext-only modes, inspect the live Selection and Range objects behind your cursor, and watch the generated innerHTML update as you type. It is free and runs fully in your browser.",
      "**contenteditable** powers comment boxes, notes apps and **WYSIWYG** editors across the web, but its behavior is full of surprises: how **plaintext-only** strips pasted formatting, what HTML **execCommand** actually generates, and how selections map to DOM nodes and offsets. This playground exposes all of it live, which makes it invaluable when you are building or debugging any in-browser editor."
    ],
    faqs: [
      { q: "What is the difference between contenteditable=true and plaintext-only?", a: "With true you get full rich text: pasted content keeps formatting and execCommand styles apply. With plaintext-only the browser strips all formatting on paste and input while keeping line breaks, which is ideal for comment boxes and chat inputs." },
      { q: "Is document.execCommand deprecated?", a: "Yes, it is officially deprecated, but it remains the only built-in rich-text editing API and every browser still supports it. For production editors, many teams layer their own model on top of it or use a library." },
      { q: "How do I read the user's selection in JavaScript?", a: "Use window.getSelection() to get the Selection, then getRangeAt(0) for the Range with startContainer, startOffset, endContainer and endOffset. The playground's Inspect button prints all of this live." },
      { q: "Why does pasted content bring ugly formatting?", a: "Browsers paste the source HTML as-is. The fixes are plaintext-only mode, intercepting the paste event to insert plain text manually, or sanitizing the HTML on input." },
      { q: "How do I get clean HTML out of a contenteditable?", a: "Read element.innerHTML, then sanitize it: strip disallowed tags and attributes (especially event handlers and javascript: URLs) before storing or rendering it anywhere." },
      { q: "Is anything I type sent to a server?", a: "No. The editor, the selection inspector and the HTML output all run locally in your browser." }
    ],
    tags: [
      "contenteditable playground",
      "contenteditable tutorial",
      "document.execcommand",
      "execcommand bold example",
      "contenteditable plaintext-only",
      "plaintext-only vs true",
      "contenteditable paste as plain text",
      "rich text editor javascript",
      "build wysiwyg editor js",
      "selection api tutorial",
      "window.getselection example",
      "range startcontainer endoffset",
      "inspect selection javascript",
      "contenteditable innerhtml",
      "sanitize contenteditable html",
      "contenteditable xss",
      "contenteditable placeholder",
      "contenteditable events",
      "input event contenteditable",
      "contenteditable react",
      "contenteditable cursor position",
      "set cursor contenteditable",
      "contenteditable line breaks",
      "contenteditable strip formatting",
      "document.execcommand deprecated alternative",
      "execcommand formatblock",
      "execcommand insertunorderedlist",
      "execcommand removeformat",
      "execcommand forecolor",
      "contenteditable toolbar",
      "custom rich text toolbar",
      "contenteditable demo",
      "learn contenteditable",
      "contenteditable examples",
      "contenteditable browser support",
      "contenteditable mobile",
      "contenteditable accessibility",
      "contenteditable aria",
      "contenteditable spellcheck",
      "contenteditable free tool",
      "html editor playground",
      "wysiwyg playground online",
      "selection range visualizer",
      "dom range explained",
      "collapsed selection",
      "anchor node focus node",
      "contenteditable gotchas",
      "contenteditable best practices",
      "medium style editor js",
      "contenteditable rich text editor demo"
    ],
  };

export default seo;
