import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Content Index - Interactive Lab | IconVault",
    metaDescription: "Real Content Index API lab: add, list and delete offline PWA content entries with honest support detection. Free, in-browser.",
    about: [ "**IconVault**'s **Content Index** playground talks to the real API: once a service worker with `registration.index` is detected, you can add entries with titles, descriptions, icons and categories, list them with `getAll()`, and delete them, all logged with genuine results. Where the API is missing, the form disables itself honestly and shows the exact code to run where it exists. It is free and runs fully in your browser.", "The **Content Index** lets installed **PWAs** register their offline content, articles, videos, audio, with the browser so it can surface it in download managers and OS-level surfaces. The lab explains the requirements (Chrome/Edge 84+, HTTPS, an active service worker), the **entry schema** including icons and categories, and why this is the missing piece between cached assets and discoverable offline content." ],
    faqs: [ { q: "What is the Content Index API?", a: "It lets a service worker register metadata about offline-available content (id, URL, title, description, icons, category) via registration.index.add(). The browser can then show that content in its own UIs even when the PWA is closed." }, { q: "Why is the tool unavailable in my browser?", a: "It needs Chrome or Edge 84+ over HTTPS plus an active service worker on the page, because the API lives on the service worker registration. Firefox and Safari do not implement it. The tool detects each requirement and tells you which one failed." }, { q: "What makes a good index entry?", a: "Content the user explicitly saved for offline: downloaded articles, podcast episodes, videos. Include a real title, a short description, at least one icon, and the right category so the browser UI renders it well." }, { q: "Do indexed URLs have to work offline?", a: "They should. The index is metadata only; your service worker must actually cache the URL (for example in a backgroundfetchsuccess handler) or the entry leads to an error page." }, { q: "Can I update an entry?", a: "Yes: calling add() with an existing id replaces that entry. Use delete(id) to remove one, and getAll() to list everything your origin has indexed." }, { q: "Is indexed content sent anywhere?", a: "No. Entries live in the browser's local index for your origin. The trial counter is a localStorage number." } ],
    tags: [ "content index api", "registration.index", "content index pwa", "contentindex", "index.add", "content index example", "content index demo", "content index browser support", "content index chrome", "content index firefox", "offline content pwa", "pwa offline articles", "service worker content index", "background fetch content index", "index.getall", "index.delete content", "content index category", "content index icons", "pwa installable content", "offline video pwa", "offline podcast pwa", "content index tutorial", "mdn content index", "content index typescript", "content index polyfill", "is content index supported", "caniuse content index", "content index https", "service worker ready index", "pwa content discovery", "browser download ui pwa", "content indexing web", "how to use content index api", "content index step by step", "content index entry schema", "contentindexentry", "test content index online", "content index playground", "content index lab", "pwa offline management", "workbox content index", "content index 2024", "web app offline library", "registration.index.add example", "content index pwa example", "offline content api", "pwa content index tutorial", "index.add icons", "contentindexentry example", "pwa offline articles api" ],
  };

export default seo;
