import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Container Style Queries - Free Online Tool | IconVault",
    metaDescription: "Learn @container style() queries hands-on: theme and feature flags via custom properties with a live demo. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Container Style Queries** playground teaches @container style() queries by doing. Flip theme, density and feature-flag custom properties on a container and watch a card restyle itself in pure CSS, with zero JavaScript involved in the styling. The full CSS is shown and copyable. It is free and runs fully in your browser.",
      "**Style queries** are the **missing half of container queries**: while **size queries** respond to width, **style queries** respond to custom property values, which makes them perfect for theming, density modes and feature flags scoped to a component subtree. Instead of toggling classes with JavaScript, you set --theme: dark on a container and every descendant styled with @container style(--theme: dark) updates automatically."
    ],
    faqs: [
      { q: "What is the difference between size and style container queries?", a: "Size queries like @container (min-width: 400px) respond to the container's dimensions. Style queries like @container style(--theme: dark) respond to custom property values on the container. They can be combined on the same container." },
      { q: "Which browsers support style queries?", a: "Chrome and Edge 111+, Safari 18+, and Firefox 137+. Any container-type (inline-size, size, or style) makes an element queryable for style features." },
      { q: "How are style queries different from :has() or classes?", a: "Classes need JavaScript to toggle and apply globally unless scoped carefully. Style queries read custom properties through the cascade, so a theme set on one subtree only affects that subtree, and inheritance does the distribution for free." },
      { q: "Can style queries read any CSS property?", a: "Currently they query custom properties (and a few defined style features). Querying arbitrary computed properties like color is not supported; the pattern is to drive everything through custom properties." },
      { q: "Do I need container-type for style queries to work?", a: "Yes, the element being queried must be a query container, which means setting container-type to inline-size, size, or style. The playground's demo uses container-type: inline-size." },
      { q: "What is a good use case for style queries?", a: "Component theming (--theme), density modes (--density: compact), and feature flags (--beta: on) scoped to part of a page. They shine in design systems where the same card component must adapt to whatever context it is dropped into." }
    ],
    tags: [
      "container style queries",
      "css @container style",
      "@container style(--theme)",
      "css style queries tutorial",
      "container queries style vs size",
      "css custom properties theming",
      "css feature flags",
      "component theming css",
      "css density mode",
      "style query browser support",
      "@container style firefox",
      "style queries safari",
      "css container-type style",
      "container query custom property",
      "css theming without javascript",
      "scoped css variables",
      "css @container examples",
      "learn container queries",
      "container queries interactive",
      "css style() query syntax",
      "query custom property value css",
      "css container query demo",
      "design system theming css",
      "css dark mode container",
      "per component dark mode",
      "css @container style not working",
      "style query fallback",
      "css style queries explained",
      "container style queries free tool",
      "css container queries cheat sheet",
      "style container queries mdn",
      "css @container style boolean",
      "custom property as feature flag",
      "css variable theming tutorial",
      "container queries 2024",
      "modern css container queries",
      "css style query multiple conditions",
      "@container style and size combined",
      "css component scoped theme",
      "card component theming",
      "css @container style(--density)",
      "style queries vs :has",
      "css container query playground",
      "interactive css container queries",
      "css style query code examples",
      "copy paste container queries",
      "css container queries generator",
      "css container style queries demo",
      "style query vs media query",
      "container style queries browser support"
    ],
  };

export default seo;
