import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Contact Picker - Interactive Lab | IconVault",
    metaDescription: "Try the real Contact Picker API: capability check, property selection and live picked contacts. Free, runs in your browser.",
    about: [ "**IconVault**'s **Contact Picker** playground calls the genuine API: `getProperties()` reports what the device can share, then `contacts.select()` opens the system picker for exactly the fields you ticked. Results render as contact cards with names, phone numbers and emails. Where the API does not exist, the tool says so plainly instead of showing a fake contact list. It is free and runs fully in your browser.", "**Contact Picker** is the **privacy-safe** way to get a phone number or email into a web form: your app never sees the address book, only the contacts the user explicitly chose. The lab covers the **hard limits**, Chrome for Android only, HTTPS required, user gesture required, and the `AbortError` versus `NotAllowedError` outcomes you must handle in production." ],
    faqs: [ { q: "What does the Contact Picker API do?", a: "navigator.contacts.select() opens the operating system's contact picker. The user chooses one or more contacts, and your page receives only the requested properties (name, email, tel) of those contacts. Nothing else is exposed." }, { q: "Why is the API missing on my desktop?", a: "It is only implemented in Chrome for Android 80 and later. Desktop Chrome, Firefox, Safari and iOS do not support it, so this tool reports the gap honestly and shows the exact code to test on an Android device." }, { q: "Does my site get access to the whole address book?", a: "No. That is the point of the API: unlike native apps, the web page cannot enumerate contacts. It only learns about contacts the user deliberately picks, field by field." }, { q: "What is getProperties() for?", a: "It returns the list of contact properties the device supports, such as name, email, tel, address and icon. You should only request properties from that list, which is why the tool builds its checkboxes from the live result." }, { q: "How do I handle the user dismissing the picker?", a: "select() rejects with an AbortError when dismissed and a NotAllowedError when permission is denied. Treat both as normal outcomes, not crashes, and leave the form usable." }, { q: "Are picked contacts uploaded anywhere?", a: "No. They render locally on this page, and the Clear button wipes them. The trial counter is a localStorage number." } ],
    tags: [ "contact picker api", "navigator.contacts", "contacts.select", "contact picker javascript", "contact picker web", "getproperties contacts", "pick contact web app", "contact picker demo", "contact picker example", "contact picker android", "contact picker chrome", "contact picker desktop", "why contact picker not working", "contacts api browser support", "contact picker safari", "contact picker ios", "contact picker firefox", "contact picker https", "contact picker user gesture", "aborterror contact picker", "notallowederror contacts", "mdn contact picker", "contact picker tutorial", "contact picker typescript", "contacts manager", "contact picker pwa", "web contacts api", "pick phone number web", "autofill contact web", "contact picker privacy", "contact picker permission", "select multiple contacts", "contact picker polyfill", "is contact picker supported", "caniuse contact picker", "contact picker 2024", "how to use contact picker api", "contact picker react", "contact picker form", "invite friends contact picker", "share contact web api", "test contact picker online", "contact picker playground", "contacts api demo", "webotp vs contact picker", "contacts api javascript", "navigator.contacts.select example", "contact picker web demo", "pick contact phone number", "contacts getproperties" ],
  };

export default seo;
