import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CORS Preflight Flow - Free Online Tool | IconVault",
    metaDescription: "Step through the browser CORS algorithm across 8 scenarios: simple vs preflighted requests, allowed vs blocked, with fixes. Free learning tool.",
    about: [
      "**IconVault**'s **CORS Preflight Flow** walks you through exactly what the browser checks before letting JavaScript read a cross-origin response. Pick from 8 realistic scenarios, simple GETs, JSON POSTs, custom headers, credentialed requests and classic failures, and step through the decision algorithm one check at a time until you reach the allow or block verdict. It is free and runs fully in your browser.",
      "CORS errors are confusing because the network tab shows a successful 200 while fetch() still throws. The confusion disappears once you see the **algorithm**: **same-origin check**, **simple-request check**, optional **preflight OPTIONS** round-trip, then response header validation. Each failing scenario in this tool ends with the concrete server-side fix, so you leave knowing not just what went wrong but how to fix it."
    ],
    faqs: [
      { q: "What triggers a CORS preflight?", a: "Anything beyond a simple request: methods other than GET, HEAD or POST; content types other than urlencoded, multipart or text/plain; or any custom header. The browser then sends an OPTIONS request first to ask the server for permission." },
      { q: "Why does fetch fail when the network tab shows 200?", a: "CORS is enforced by the browser, not the server. The server happily responded 200, but without an Access-Control-Allow-Origin header the browser refuses to expose the response to your JavaScript." },
      { q: "What is the difference between simple and preflighted requests?", a: "Simple requests (safelisted method, safelisted headers, safelisted content type) go out immediately and are only checked on the way back. Everything else needs a preflight OPTIONS request approved before the real request is even sent." },
      { q: "Can I use Access-Control-Allow-Origin: * with credentials?", a: "No. Credentialed requests (cookies, authorization headers) require the server to echo the exact requesting origin and send Access-Control-Allow-Credentials: true. A wildcard is rejected." },
      { q: "How do I fix a CORS error in development?", a: "Configure the server (or dev proxy) to send the right headers: ACAO with your origin, ACAM with the methods you use, ACAH with your custom headers, and ACAC: true if you send credentials. The tool's blocked scenarios each name the exact missing header." },
      { q: "Does CORS protect my server?", a: "No. CORS only stops browsers from exposing responses to other origins' JavaScript. curl, Postman and any non-browser client ignore it completely, so never rely on CORS for security." }
    ],
    tags: [
      "cors preflight",
      "cors explained",
      "cors tutorial",
      "what is cors",
      "cors preflight request",
      "options request cors",
      "access-control-allow-origin",
      "cors error fix",
      "cors blocked by policy",
      "no access-control-allow-origin header",
      "cors simple request",
      "cors safelisted headers",
      "when is preflight required",
      "access-control-request-method",
      "access-control-allow-methods",
      "access-control-allow-headers",
      "access-control-allow-credentials",
      "cors credentials wildcard",
      "cors with cookies",
      "fetch cors mode",
      "cors preflight flow chart",
      "learn cors interactive",
      "cors visualizer",
      "cors playground",
      "cors scenarios",
      "cors step by step",
      "debug cors error",
      "cors localhost",
      "cors dev proxy",
      "express cors setup",
      "cors headers explained",
      "preflight 204",
      "cors max age",
      "access-control-max-age",
      "cors and json post",
      "why does post trigger preflight",
      "content-type application/json cors",
      "custom header cors preflight",
      "x-api-key cors",
      "cors delete method",
      "cors put request",
      "cors patch preflight",
      "cors error chrome",
      "cors firefox",
      "cors same-origin policy",
      "same origin policy explained",
      "cors vs jsonp",
      "cors security",
      "cors wildcard subdomains",
      "cors allow all origins",
      "cors free learning tool"
    ],
  };

export default seo;
