import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Credential Management - Interactive Lab | IconVault",
    metaDescription: "Try the real Credential Management API: password credential flows, passkey creation and mediation modes. Free, runs fully in your browser.",
    about: [ "**IconVault**'s **Credential Management** playground talks to the real `navigator.credentials` API in your browser: request stored password credentials with optional, required or silent mediation, create a demo passkey through your platform authenticator, and block silent access with `preventSilentAccess()`. Every call and its result is logged with the exact API shape, so you see what production sign-in code actually receives. It is free and runs fully in your browser.", "You will learn why `get()` returns null on a fresh profile, how the three **mediation modes** differ in UI behavior, what a real **WebAuthn creation ceremony** returns (credential id, clientDataJSON, attestation object), and how **conditional mediation** powers **passkey autofill**. Nothing leaves your device: the passkey demo uses a random challenge on the current origin and never sends data anywhere." ],
    faqs: [ { q: "What is the Credential Management API?", a: "It is the browser API behind navigator.credentials: storing and retrieving password credentials, and the get/create entry points that WebAuthn passkeys use. This lab exercises both paths live." }, { q: "Why does get() return null?", a: "Returning null is the normal honest result when no password credential is stored for this origin. Browsers only return credentials the user previously saved through the password manager." }, { q: "What do the mediation modes do?", a: "optional returns a credential silently when exactly one matches, required always shows the account chooser UI, and silent never shows UI and resolves null instead of prompting." }, { q: "Is the passkey button real?", a: "Yes. It calls navigator.credentials.create with a real challenge and invokes your platform authenticator (Touch ID, Windows Hello, or a security key). Canceling the native prompt is a normal result and is logged." }, { q: "What does preventSilentAccess() do?", a: "It tells the browser to stop handing out credentials without user interaction until the next explicit sign-in, which is what a good Sign out button should call." }, { q: "Is any credential data sent to a server?", a: "No. Everything stays on this device; the demo relying-party id is the current hostname and the challenge is random per attempt." } ],
    tags: [ "credential management api", "navigator.credentials", "credentials api javascript", "passwordcredential", "credential management api example", "webauthn tutorial", "passkey demo", "create passkey javascript", "navigator.credentials.create", "navigator.credentials.get", "publickeycredential", "passkey authentication", "webauthn example", "mediation optional required silent", "conditional mediation", "passkey autofill", "preventsilentaccess", "password credential api", "browser credential manager", "webauthn rp id", "attestation none", "clientdatajson", "authenticatorattestationresponse", "user verification discouraged", "platform authenticator", "isuserverifyingplatformauthenticatoravailable", "passkey vs password", "fido2 web", "how passkeys work", "credential api browser support", "caniuse credential management", "passwordless login web", "webauthn javascript tutorial", "passkey demo site", "test webauthn online", "credentialrequestoptions", "password credential mediation", "store password credential", "federatedcredential", "otpcredential", "webauthn origin check", "passkey challenge", "webauthn timeout", "excludecredentials", "authenticatorselection", "pubkeycredparams", "webauthn error notallowederror", "passkey localhost test", "credential management mdn", "sign in with passkey code", "webauthn frontend", "passkey ux best practices" ],
  };

export default seo;
