import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Crop Image - Free Online Tool | IconVault",
    metaDescription: "Crop images free in your browser with a draggable box, rule-of-thirds grid and aspect presets. No uploads, no watermarks.",
    about: [
      "**IconVault**'s **Crop Image** gives you precise, visual cropping: drag a box directly on the photo with a **rule-of-thirds grid** overlay, pull **corner and edge handles** to resize, or type exact **X, Y, Width and Height** values that stay in sync with the box. **Aspect presets** (Free, 1:1, 4:5, 16:9, 9:16, 3:2) lock the ratio while you drag, and you can export to **JPG or WebP** with a quality slider.",
      "It is **free** to use and **private by design**: cropping happens entirely in your browser, so your photos never leave your device. **Pro** members get unlimited crops with full-resolution output.",
    ],
    faqs: [
      { q: "How do I crop precisely?", a: "Drag on the image to draw a box, drag inside it to move, pull the handles to resize, or type exact pixel values in the X, Y, Width and Height fields. All three stay in sync." },
      { q: "What is the rule-of-thirds grid for?", a: "It divides the crop box into thirds to help you place subjects along the grid lines, a classic composition technique for stronger photos." },
      { q: "Can I lock the crop to a specific ratio?", a: "Yes. Choose 1:1, 4:5, 16:9, 9:16 or 3:2 and the box keeps that ratio while you drag or resize. Free lets you crop any shape." },
      { q: "What formats can I export?", a: "JPG or WebP, with a quality slider up to 100%. JPG fills transparency with white; WebP keeps it." },
      { q: "Are my photos uploaded anywhere?", a: "No. The editor and the crop both run locally in your browser. Your files never leave your device." },
      { q: "Does cropping reduce image quality?", a: "Cropping itself is lossless: the selected pixels are copied at full resolution. Only the final JPG/WebP encoding applies compression, which you control with the quality slider." },
    ],
    tags: ["crop image online", "free image cropper", "crop photo online", "image crop tool", "crop jpg online", "crop png online", "photo cropper free", "crop image to size", "online photo crop", "crop picture online", "image cropping tool", "crop photo to 1:1", "crop image 16:9", "free crop tool", "crop image no watermark", "precise image crop", "crop photo editor", "crop image browser", "online image cropper", "crop photo free",
      "image cropper",
      "crop image",
      "photo cropper",
      "crop photo",
      "online crop image",
      "crop picture",
      "image crop online",
      "photo crop online",
      "cropper tool",
      "image cropper online free",
      "crop jpg",
      "crop png",
      "crop webp",
      "crop image to 4:3",
      "crop image to 3:2",
      "crop image to 9:16",
      "crop photo to 4:5",
      "crop image custom size",
      "crop image no signup",
      "free online cropper",
      "crop image download",
      "crop photo to square",
      "crop image to rectangle",
      "crop image aspect ratio",
      "aspect ratio cropper",
      "crop photo editor online",
      "crop image pixels",
      "crop image by pixels",
      "crop image free no watermark",
      "how to crop an image",
      "crop image in browser",
      "photo cropping tool",
      "picture cropper online",
      "crop image online free tool",
      "crop photo online free",
      "image cropping online",
      "crop images free",
      "simple image cropper",
      "quick photo crop",
      "crop and download image"],
  };

export default seo;
