import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Transition Generator - Free Online CSS Tool | IconVault",
    metaDescription: "Create smooth CSS transitions visually: pick a property, duration, delay and easing, design custom cubic-bezier curves, preview on hover. Free, in-browser.",
    about: [ "**IconVault**'s **CSS Transition Generator** builds buttery **CSS transitions** with a visual editor. Choose the **property** to animate, set **duration** and **delay**, pick a **timing function** from presets like ease and ease-in-out, or draw your own **cubic-bezier** curve with sliders for Spring, Overshoot, Smooth and Snap feels. A **live demo** shows exactly how your transition behaves on hover or click before you ship it.",
    "Everything runs **100% in your browser** with no sign-up and nothing uploaded. Copy the finished **transition** line in one click, reuse it for buttons, menus, cards and modals, and tweak the curve until the motion feels right. It is free to use and the output is plain, standards-based CSS that works in every modern browser." ],
    faqs: [
      { q: "What does the CSS Transition Generator do?", a: "It builds the CSS transition property for you. You pick an animating property, duration, delay and easing curve, preview it live on hover or click, and copy the finished transition line." },
      { q: "What is cubic-bezier in CSS?", a: "cubic-bezier defines a custom easing curve with four numbers, like cubic-bezier(0.34, 1.56, 0.64, 1) for a springy overshoot. The tool gives you sliders and presets so you can design the curve visually instead of typing numbers." },
      { q: "Which timing function should I use?", a: "Use ease-out for elements entering the screen, ease-in for elements leaving, and ease-in-out or a custom cubic-bezier for motion that should feel springy or snappy. Preview each one live in the tool." },
      { q: "Can I animate multiple properties at once?", a: "Yes. Set the property to all, or list several comma-separated transitions in your stylesheet. The tool focuses on one transition at a time so you can perfect its feel." },
      { q: "Is it free and private?", a: "Yes, it is free with no account required. All editing happens locally in your browser, so nothing is uploaded or tracked." },
      { q: "Does the output work in all browsers?", a: "Yes. Transitions and cubic-bezier easing are standard CSS supported by every modern browser without prefixes." }
    ],
    tags: [
      "css transition generator",
      "css transition online",
      "css transition tool",
      "css animation transition generator",
      "css easing generator",
      "cubic bezier generator",
      "cubic-bezier tool",
      "cubic bezier online",
      "css timing function generator",
      "css ease in out generator",
      "css transition duration generator",
      "css transition delay generator",
      "css hover transition generator",
      "css transition preview",
      "css transition playground",
      "css transition visualizer",
      "css transition examples",
      "css transition property list",
      "css transition all generator",
      "how to make css transitions smooth",
      "css spring animation",
      "css overshoot easing",
      "spring cubic bezier css",
      "css bounce easing",
      "css snap easing",
      "css smooth hover effect",
      "css transition button hover",
      "css card hover transition",
      "css transition opacity",
      "css transition transform",
      "css transition box shadow",
      "css transition background color",
      "css transition border radius",
      "css transition width",
      "css transition filter",
      "css transition syntax",
      "css transition shorthand",
      "css transition multiple properties",
      "css transition for beginners",
      "generate css transition code",
      "css transition copy paste",
      "css animation vs transition",
      "css transition curve editor",
      "visual css transition builder",
      "css ease presets",
      "css step start step end",
      "css transition generator tool free",
      "online transition maker css",
      "css motion design tool",
      "css micro interaction generator"
    ],
  };

export default seo;
