import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Custom Highlights - Interactive CSS Lab | IconVault",
    metaDescription: "Style text ranges with ::highlight(): live search, spellcheck and syntax demos using the CSS Custom Highlight API. Free, runs fully in your browser.",
    about: [ "**IconVault**'s **CSS Custom Highlights** lab is an interactive playground for the **CSS Custom Highlight API**. Type in the search box to highlight every match in a paragraph, toggle the **spellcheck** demo to mark misspelled words with wavy red underlines, and switch the **syntax coloring** demo to see code tokens styled through **::highlight()**. Ranges are registered with **CSS.highlights** from JavaScript and styled purely in CSS, so you can inspect exactly how the API works. It is free and runs fully in your browser.",
    "Custom highlights solve a long-standing problem: styling arbitrary text ranges without wrapping them in spans. Because highlights live outside the DOM, they never disturb **selection**, copy and paste, or screen readers. The lab shows the full workflow: walk text nodes, build **Range** objects, wrap them in a **Highlight**, register it under a name with CSS.highlights.set(), and style it with **::highlight(name)**. Support is feature-detected, and the copyable snippet includes both the CSS and the JavaScript you need." ],
    faqs: [
      { q: "What is the CSS Custom Highlight API?", a: "It is a browser API that lets JavaScript register text ranges under a name, which CSS then styles with the ::highlight() pseudo-element. It is designed for search highlighting, spellcheck marks, syntax coloring and grammar suggestions." },
      { q: "How do I style a highlight?", a: "Use ::highlight(name) in CSS, for example ::highlight(search-hit) { background: yellow; }. Supported properties include color, background, text-decoration, text-shadow and a few others. Layout-affecting properties like font-size are not allowed." },
      { q: "Which browsers support ::highlight()?", a: "Chrome 105+, Edge 105+ and recent versions of Firefox and Safari support the Custom Highlight API. This lab detects support at runtime and tells you honestly whether the live demos are running." },
      { q: "Do highlights affect copy and paste?", a: "No. Highlights are painted over the text but are not part of the DOM, so copying text, selecting it, and screen reader output are all unaffected. That is the main advantage over wrapping matches in mark or span elements." },
      { q: "Can one Highlight hold multiple ranges?", a: "Yes. A Highlight is constructed with any number of Range objects, and ranges can span multiple text nodes and elements. You can also register several named highlights at once with CSS.highlights.set()." },
      { q: "How do I clear a highlight?", a: "Call CSS.highlights.delete(name) to remove one, or CSS.highlights.clear() to remove them all. Re-setting a name replaces its ranges." },
    ],
    tags: [ "css custom highlights", "::highlight()", "css highlight api", "custom highlight api", "CSS.highlights", "highlight search results css", "css search highlight", "javascript highlight text", "css ::highlight example", "::highlight(search)", "css highlight pseudo element", "text highlight javascript range", "spellcheck highlight css", "wavy underline css", "syntax highlighting css", "highlight api browser support", "css highlights chrome", "::highlight firefox", "css.highlights.set", "new Highlight()", "range highlight css", "highlight text without span", "css highlight tutorial", "learn css highlights", "css highlight playground", "interactive highlight demo", "css highlight generator", "text range styling css", "document.createRange highlight", "treeWalker text nodes highlight", "css highlight mdn", "how to use ::highlight()", "::highlight syntax", "css highlight properties", "custom highlight api example", "css highlight copy paste", "accessible text highlighting", "find in page highlight css", "code syntax highlight css", "highlight keywords css", "css highlight multiple ranges", "css.highlights.delete", "css.highlights.clear", "highlight api 2026", "::highlight not working", "css highlight fallback", "custom highlights safari", "css text marker effect", "css highlight color",
      "css highlight search box", "text fragment highlight css" ],
  };

export default seo;
