import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS @function Playground - Interactive CSS Lab | IconVault",
    metaDescription: "Define native CSS @function helpers with typed parameters. Live spacing, fluid-type and tint demos with copyable code. Free, in your browser.",
    about: [ "**IconVault**'s **CSS @function Playground** teaches native CSS **@function** with three working helpers you can tune live. Adjust the **--spacing()** multiplier and watch padding grow in 8px steps, drag the **--fluid-type()** range and resize your window to see type scale with the viewport, or mix a **--tint()** color toward white with **color-mix**. Each tab shows the exact **@function** definition and call site, ready to copy. It is free and runs fully in your browser.",
    "Custom functions finally let stylesheets compute their own values: declare **typed parameters** like **--n: <number>**, compute **result** from them, and call the function anywhere a value is expected. Because parameters are type-checked, mistakes fail loudly at parse time instead of silently breaking your layout. The playground feature-detects **@function** support, runs natively on Chrome 137+ and Edge 137+, and mirrors every result in JavaScript on older browsers so you can learn the syntax today and ship it when your audience is ready." ],
    faqs: [
      { q: "What is CSS @function?", a: "@function defines a custom CSS function with typed parameters and a computed result, like @function --spacing(--n: <number>) returns <length> { result: calc(var(--n) * 8px); }. You call it as padding: --spacing(3)." },
      { q: "How is @function different from @mixin?", a: "@mixin returns a block of declarations applied with @apply, while @function returns a single value you can use anywhere a value fits, including inside calc(), color-mix() and other functions." },
      { q: "Which browsers support CSS @function?", a: "Chrome 137+ and Edge 137+ support @function. Firefox and Safari do not support it yet. This playground detects support and computes the same results in JavaScript on unsupported browsers." },
      { q: "What types can function parameters use?", a: "Any CSS type: <number>, <length>, <percentage>, <color>, <angle>, <time> and more. The browser type-checks arguments at parse time, so passing a color where a length is expected is a loud error, not a silent bug." },
      { q: "Can @function replace Sass functions?", a: "For value computation it largely can, with the bonus of runtime values like viewport units and custom properties. Sass still wins for loops, maps and build-time logic that CSS cannot express." },
      { q: "What is a good first use of @function?", a: "A spacing scale (--spacing), fluid type (--fluid-type) and color manipulation (--tint, --shade) cover most needs. They turn magic numbers into a documented, reusable API for your design system." },
    ],
    tags: [ "css @function", "css functions", "css custom functions", "@function css", "native css functions", "css @function example", "css @function tutorial", "learn css @function", "css @function playground", "interactive @function demo", "css @function generator", "css function parameters", "typed css parameters", "css function returns", "css spacing function", "css fluid type function", "css tint function", "color-mix css", "css @function browser support", "css @function chrome", "@function firefox", "css @function 2026", "how to use css @function", "@function syntax css", "css @function mdn", "css @function vs @mixin", "css @function vs sass", "sass function vs css", "css custom function copy paste", "css @function not working", "css @function fallback", "css functions design system", "css spacing scale", "fluid typography css", "clamp() css", "css clamp fluid type", "css color functions", "css result keyword", "css <length> type", "css <number> type", "css <color> type", "modern css features", "css 2026 features", "css function cheat sheet", "css @function reference", "frontend css tools", "css lab", "learn modern css", "css value computation", "css dynamic values" ],
  };

export default seo;
