import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS font-size-adjust - Interactive CSS Lab | IconVault",
    metaDescription: "Normalize x-height across font fallbacks with font-size-adjust. Live visual matcher with x-height bars and copyable CSS. Free, in your browser.",
    about: [ "**IconVault**'s **CSS font-size-adjust** lab shows why text seems to shrink when a webfont fails and a fallback takes over. Pick a primary font and a fallback, slide the **font-size-adjust** value, and watch the teal **x-height bars** line up: when they match, the fallback renders at the same readable size as the original. The one-click **Match** button computes the right value from real font metrics. It is free and runs fully in your browser.",
    "Different fonts have different **x-heights** at the same font size, so a fallback like Arial can look noticeably smaller than the Georgia it replaced, shifting your layout and hurting **CLS**. Setting **font-size-adjust** tells the browser to scale the fallback so its x-height equals a fixed fraction of the font size, keeping text legible and layouts stable. The lab explains numeric values and the newer **from-font** keyword, shows the generated CSS for your exact pairing, and notes that the built-in ratios are approximate and vary by platform." ],
    faqs: [
      { q: "What does font-size-adjust do?", a: "It scales a font so that its x-height equals a specified fraction of the font size. This keeps text the same perceived size when the browser swaps in a fallback font with different metrics." },
      { q: "Why does text shrink when fonts swap?", a: "Every font has its own x-height ratio. Georgia's x-height is about 0.48 of its font size while Verdana's is about 0.55, so the same 16px renders visibly different sizes. font-size-adjust normalizes this." },
      { q: "How do I pick the right value?", a: "Use the x-height ratio of your primary font. Common values: Verdana 0.545, Arial 0.519, Georgia 0.481, Times New Roman 0.448. This lab's Match button sets it from the selected font automatically." },
      { q: "What is font-size-adjust: from-font?", a: "It is a newer keyword that automatically uses the x-height ratio of the first available font in the stack, so you do not have to look up the number yourself. It needs Chrome 127+ or a recent Firefox." },
      { q: "Which browsers support font-size-adjust?", a: "Numeric values work in all modern browsers including Safari. Keyword values like from-font and ex-height need newer Chrome or Firefox." },
      { q: "Does font-size-adjust help CLS?", a: "Yes. Font swaps that change x-height also change line breaks and element heights, causing layout shift. Normalizing x-height with font-size-adjust reduces that shift noticeably." },
    ],
    tags: [ "css font-size-adjust", "font-size-adjust css", "x-height css", "font fallback css", "css font fallback size", "font-size-adjust example", "font-size-adjust from-font", "css x-height normalization", "webfont fallback shift", "font swap layout shift", "css font metrics", "x-height ratio fonts", "georgia x-height", "arial x-height", "verdana x-height", "times new roman x-height", "font-size-adjust tutorial", "learn font-size-adjust", "font-size-adjust playground", "interactive font-size-adjust", "css font-size-adjust generator", "font-size-adjust value", "how to use font-size-adjust", "font-size-adjust mdn", "css font-size-adjust 2026", "font-size-adjust browser support", "font-size-adjust safari", "fallback font looks smaller", "webfont failed fallback too small", "css keep text size font swap", "font-display fallback size", "cls font swap fix", "reduce cls webfonts", "css font-size-adjust copy paste", "x-height bar", "measure x-height css", "font-size-adjust calculator", "font pairing x-height", "matching fallback fonts", "css font stack best practice", "system font stack css", "font-size-adjust ex-height", "font-size-adjust cap-height", "css font size adjust not working", "font-size-adjust number", "typography css tools", "readable text css", "font legibility css",
      "font-size-adjust 0.5", "css font adjust", "x-height matching fonts" ],
  };

export default seo;
