import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Selector Tester - Free Online Tool | IconVault",
    metaDescription: "Test CSS selectors live on a sample DOM with match highlighting and a specificity calculator. Free, no signup, runs in your browser.",
    about: [
      "**IconVault**'s **CSS Selector Tester** lets you type any CSS selector and instantly see what it matches. Matches light up with a teal outline on a realistic sample document, you get an exact match count plus a list of the matched elements, and a built-in specificity calculator scores your selector as you type. It is free and runs fully in your browser.",
      "Debugging selectors by refreshing a page and squinting at DevTools is slow. This tester gives you a safe sandbox to experiment with **combinators**, **pseudo-classes** like :nth-child(), and **attribute selectors**, while the **specificity readout** (IDs vs classes vs elements) teaches you why one rule beats another. Invalid selectors are caught and explained instead of failing silently."
    ],
    faqs: [
      { q: "How is specificity calculated?", a: "Each selector is scored as three numbers: A counts ID selectors, B counts classes, attributes and pseudo-classes, and C counts element names and pseudo-elements. A selector like #nav .link (1,1,0) beats ul li a (0,0,3). The tool shows the score live as you type." },
      { q: "What happens if my selector is invalid?", a: "The tool catches the browser's SyntaxError and shows you the message, so you can see exactly what went wrong instead of getting zero matches with no explanation." },
      { q: "Can I test selectors against my own HTML?", a: "This version tests against a built-in sample document covering headers, lists, forms and attributes. For your own pages, paste selectors into your browser DevTools console with document.querySelectorAll()." },
      { q: "Does :not() affect specificity?", a: "Yes. Per the spec, :not(), :is() and :has() take the specificity of their most specific argument, while :where() always contributes zero. The tool's score is an approximation and notes this edge case." },
      { q: "Is anything I type sent to a server?", a: "No. Selector matching uses your browser's own querySelectorAll, and everything runs locally on your device." },
      { q: "Why do two rules with the same specificity behave differently?", a: "When specificity ties, the rule that appears later in the stylesheet wins. Also check for !important, inline styles, and cascade layers, which all outrank normal specificity." }
    ],
    tags: [
      "css selector tester",
      "css specificity calculator",
      "test css selector online",
      "css selector match checker",
      "specificity calculator css",
      "css selector playground",
      "css specificity explained",
      "how to calculate css specificity",
      "css selector cheat sheet",
      "css nth-child tester",
      "css attribute selector tester",
      "queryselectorall tester online",
      "css combinator examples",
      "css specificity points",
      "id vs class specificity",
      "css selector not working",
      "debug css selector",
      "css pseudo class list",
      "css :not specificity",
      "css :is :where specificity",
      "specificity hierarchy css",
      "css selector visualizer",
      "learn css selectors interactive",
      "css child selector vs descendant",
      "css sibling selector examples",
      "css selector tester free",
      "css specificity calculator online",
      "css selector practice",
      "css selector examples with output",
      "how does css specificity work",
      "css important vs specificity",
      "css cascade layers specificity",
      "inline style specificity score",
      "css selector invalid error",
      "css :nth-child(2n) example",
      "css attribute selector contains",
      "css selector starts with",
      "css selector ends with",
      "css multiple selectors comma",
      "css universal selector specificity",
      "css pseudo element specificity",
      "which css rule wins",
      "css specificity wars",
      "css selector matching explained",
      "test selectors without devtools",
      "css selector sandbox",
      "css specificity tool free",
      "css :has selector examples",
      "css :is selector specificity",
      "css selector weight calculator",
      "css specificity (1,0,0) meaning"
    ],
  };

export default seo;
