import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS scroll-state() - Interactive CSS Lab | IconVault",
    metaDescription: "Learn scroll-state() container queries: sticky stuck detection and snap highlighting without JavaScript. Live badges, copyable CSS.",
    about: [
      "**IconVault**'s **CSS scroll-state()** lab is a hands-on introduction to scroll-state container queries: the new CSS that answers questions like 'is my sticky header stuck?' and 'which snap target is snapped?' with pure CSS. Scroll the live demo and watch the **stuck: top**, **stuck: bottom** and **snapped: block** badges flip exactly the way the spec defines them, then copy the **@container scroll-state()** rules for your own projects.",
      "Everything is free and runs fully in your browser. scroll-state() is new (Chrome 133+), so support varies: the tool injects the real **@container** rules for browsers that understand them and computes the badges in JavaScript the same way everywhere else, labelled honestly. You will finally be able to style stuck headers without a scroll listener."
    ],
    faqs: [
      { q: "What are scroll-state() container queries?", a: "scroll-state() queries let a container's descendants react to the container's scroll state in pure CSS. Features include stuck (a sticky child is pinned to an edge), snapped (a snap target rests on its snap point), and scrollable (the container can still scroll in a direction). The scroller opts in with container-type: scroll-state." },
      { q: "How do I style a sticky header only when it is stuck?", a: "Give the scroller container-type: scroll-state, then write @container scroll-state(stuck: top) { .header { ... } }. The rule matches only while the sticky header is pinned to the top, with no JavaScript scroll listener needed." },
      { q: "Which browsers support scroll-state() queries?", a: "Chrome 133 and later plus other Chromium browsers support scroll-state() container queries. Firefox and Safari had not shipped them at the time of writing. This tool detects nothing by magic: it injects the real rules (which light up in Chromium) and mirrors the state in JS badges everywhere." },
      { q: "What is the difference between :stuck and scroll-state(stuck)?", a: ":stuck is an older proposed pseudo-class for sticky elements that never shipped widely. scroll-state(stuck: top) is the container-query based mechanism that did ship: it queries the scroll container's state and can style any descendant, not just the sticky element itself." },
      { q: "What scroll-state features exist?", a: "The spec defines stuck with top/right/bottom/left values, snapped with block/inline/x/y values, and scrollable with top/right/bottom/left values. Stuck tracks sticky pinning, snapped tracks scroll-snap targets at rest, and scrollable tells you whether more scrolling is possible in a direction." },
      { q: "Do scroll-state queries replace IntersectionObserver for sticky detection?", a: "For styling, yes: that was the classic IntersectionObserver hack (a 1px sentinel element). scroll-state(stuck) expresses it declaratively. Keep the observer approach only if you need the state in JavaScript logic or must support browsers without scroll-state()." }
    ],
    tags: [
      "css scroll-state",
      "scroll-state container queries",
      "css scroll state queries",
      "@container scroll-state",
      "container-type scroll-state",
      "scroll-state stuck",
      "stuck top css",
      "style sticky header when stuck css",
      "sticky header stuck state css",
      "css detect sticky stuck",
      "scroll-state snapped",
      "snapped block css",
      "scroll snap highlight css",
      "scroll-state scrollable",
      "css scroll state browser support",
      "scroll-state chrome 133",
      "scroll-state firefox",
      "scroll-state safari",
      "css container queries scroll",
      "container queries new features",
      "scroll driven css",
      "css without javascript scroll",
      "sticky position stuck selector",
      ":stuck css",
      "stuck pseudo class css",
      "intersectionobserver sticky header",
      "sticky header shadow on scroll css",
      "change header on scroll css only",
      "css scroll listener alternative",
      "scroll-state tutorial",
      "scroll-state example",
      "learn css scroll-state",
      "interactive scroll-state demo",
      "css scroll-state playground",
      "scroll-state mdn",
      "scroll-state caniuse",
      "css scroll-state 2026",
      "container query units scroll",
      "scroll state query syntax",
      "@container scroll-state(stuck: top)",
      "scroll-state(stuck: bottom)",
      "scroll-state(snapped: block)",
      "scroll snap css highlight active",
      "css scroll snap active item style",
      "sticky footer stuck css",
      "position sticky state css",
      "css scroll container queries",
      "new css features 2026",
      "baseline css scroll-state",
      "css scroll-state polyfill"
    ],
  };

export default seo;
