import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS interpolate-size - Interactive CSS Lab | IconVault",
    metaDescription: "Animate height auto smoothly with interpolate-size: allow-keywords. Live accordion demo vs the grid fallback, with copyable CSS. Free, in your browser.",
    about: [ "**IconVault**'s **CSS interpolate-size** lab finally answers the classic question: why can't **height: auto** be animated? Two side-by-side accordions show the difference live. The left panel uses **interpolate-size: allow-keywords** to animate straight from 0 to auto; the right panel uses the classic **grid 0fr to 1fr** trick that works everywhere. Toggle the keyword opt-in off to feel the old snapping behavior, then adjust duration and easing. It is free and runs fully in your browser.",
    "Transitions need numbers to interpolate between, and **auto** was never a number, so expanding panels always snapped open. Setting **interpolate-size: allow-keywords** on the changing element opts it into animating between lengths and intrinsic sizes like auto, min-content and max-content. The lab feature-detects support, explains the honest fallback story for older browsers, and generates copyable CSS for both the modern approach and the universal grid fallback, including a width variant." ],
    faqs: [
      { q: "Why can't CSS animate height: auto?", a: "Transitions interpolate between two numeric values, and auto is a keyword, not a number. The browser had nothing to animate from or to, so the change applied instantly with no transition." },
      { q: "What is interpolate-size: allow-keywords?", a: "It is a CSS property that opts an element into animating between lengths and intrinsic sizing keywords like auto, min-content, max-content and fit-content. Set it on the element whose size changes, then transition height or width normally." },
      { q: "Which browsers support interpolate-size?", a: "Chrome 129+ and Edge 129+ support it. Firefox and Safari do not support it yet, so keep the grid fallback for broad audiences." },
      { q: "What is the fallback for older browsers?", a: "Animate grid-template-rows from 0fr to 1fr with the content wrapped in an overflow hidden element with min-height: 0. It animates smoothly in every modern browser and needs no new features." },
      { q: "Does interpolate-size work with @starting-style?", a: "Yes. Combined with transition-behavior: allow-discrete and @starting-style, you can animate elements appearing from display: none, which previously also snapped." },
      { q: "Can I animate width: auto too?", a: "Yes. interpolate-size covers any property that resolves to a size, including width, min-height, flex-basis and grid track sizes. This lab has a width mode so you can try it." },
    ],
    tags: [ "css interpolate-size", "interpolate-size allow-keywords", "animate height auto css", "css height auto transition", "css auto height animation", "interpolate-size css", "css accordion animation", "smooth accordion css", "css expand collapse animation", "height 0 to auto css", "css transition height auto", "interpolate-size browser support", "interpolate-size chrome", "css interpolate-size tutorial", "learn interpolate-size", "interpolate-size playground", "interactive interpolate-size demo", "css interpolate-size generator", "grid 0fr 1fr animation", "css grid accordion", "grid-template-rows animation", "css auto animation fallback", "animate to auto css 2026", "css transition auto", "css max-height transition trick", "css accordion without javascript", "pure css accordion", "css details animation", "css expandable panel", "css interpolate-size mdn", "how to use interpolate-size", "interpolate-size syntax", "allow-keywords css", "interpolate-size numeric-only", "css intrinsic size animation", "animate min-content css", "css transition-behavior allow-discrete", "@starting-style animation", "css display none animation", "css height transition not working", "css animation height auto fix", "smooth height animation css", "css accordion copy paste", "css transition duration easing", "cubic-bezier css", "css animation tips",
      "css interpolate-size example", "interpolate size keywords", "css auto size transition", "height auto animation 2026", "css transition to auto" ],
  };

export default seo;
