import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Typed OM - Interactive CSS Lab | IconVault",
    metaDescription: "Learn the CSS Typed OM: build CSSUnitValues, run real unit arithmetic, chain CSSTransformValue transforms, drive attributeStyleMap live.",
    about: [
      "**IconVault**'s **CSS Typed OM** lab replaces stringly-typed CSS in JavaScript with real typed values. Build **CSSUnitValue** objects like **CSS.px(24)** and inspect their value and unit, then run genuine unit arithmetic: **px + px** works, **px + deg** throws a TypeError exactly as the spec demands, and **.to()** converts between compatible units. No mocks: every operation runs against the real Typed OM.",
      "A transform chain builder composes **CSSTranslate**, **CSSRotate** and **CSSScale** into a **CSSTransformValue** that drives a live preview, and the styleMap lab sets width, rotate and opacity through **attributeStyleMap** with a typed readout. Free, runs fully in your browser, with per-feature support badges because Typed OM is Chromium-first and support varies elsewhere."
    ],
    faqs: [
      { q: "What is the CSS Typed OM?", a: "The CSS Typed Object Model is a set of JavaScript APIs that represent CSS values as typed objects instead of strings. Instead of el.style.width = '24px', you work with CSS.px(24), a CSSUnitValue with numeric value and unit, and set it via el.attributeStyleMap.set('width', CSS.px(24))." },
      { q: "Why use Typed OM instead of style strings?", a: "Typed values carry units, so arithmetic is unit-aware: adding px to px works, adding px to deg throws instead of silently producing garbage. Parsing is done once by the browser, transforms compose without string concatenation, and computed values come back typed, which kills a whole class of unit bugs." },
      { q: "How does CSSUnitValue arithmetic work?", a: "CSSUnitValue and CSSMathValue expose add(), sub(), mul() and div(). Compatible units combine (px with px); incompatible ones throw a TypeError. Multiplication and division by plain numbers scale values, and .to('px') converts between compatible units like cm and px." },
      { q: "What is CSSTransformValue?", a: "CSSTransformValue is a list of transform components (CSSTranslate, CSSRotate, CSSScale, CSSSkew, CSSPerspective, CSSMatrix) that you set as a single typed transform value. It replaces building transform strings by hand and lets you read back and modify individual components." },
      { q: "What is attributeStyleMap?", a: "attributeStyleMap is the typed equivalent of element.style: a StylePropertyMap you read with .get() (returns typed values) and write with .set(), .append() and .delete(). Reading el.attributeStyleMap.get('width') gives you a CSSUnitValue, not a string." },
      { q: "Which browsers support the CSS Typed OM?", a: "Chromium browsers support the full Typed OM. Safari and Firefox support varies by feature: some pieces like CSSUnitValue exist while attributeStyleMap or transform values lag. This tool probes each feature and badges it, and every demo reports honest errors where unsupported." }
    ],
    tags: [
      "css typed om",
      "css typed object model",
      "cssunitvalue",
      "css.px",
      "css typed om tutorial",
      "css typed om example",
      "attributestylemap",
      "element.attributestylemap",
      "css typed om browser support",
      "css typed om firefox",
      "css typed om safari",
      "csstransformvalue",
      "csstranslate",
      "cssrotate",
      "cssscale",
      "css typed transforms",
      "css mathvalue",
      "cssunitvalue add",
      "css unit arithmetic javascript",
      "typed css values js",
      "css houdini typed om",
      "houdini typed om",
      "css typed om vs cssom",
      "style property map",
      "stylepropertymap",
      "cssnumberish",
      "css.px() example",
      "css.deg()",
      "css.ms()",
      "css.percent()",
      "cssnumber",
      "csskeywordvalue",
      "computedstylemap",
      "getcomputedstyle typed",
      "css typed om performance",
      "avoid css string parsing js",
      "typed css custom properties js",
      "css variable typed om",
      "web animations typed om",
      "element.animate typed",
      "css typed om 2026",
      "learn css typed om",
      "interactive typed om demo",
      "css typed om playground",
      "typed om mdn",
      "css typed om caniuse",
      "css paint api typed om",
      "css layout api stylemap",
      "cssmathsum",
      "cssmathproduct",
      "cssunitvalue to()",
      "css unit conversion js"
    ],
  };

export default seo;
