import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS @property Playground - Interactive CSS Lab | IconVault",
    metaDescription: "Learn CSS @property with live demos: animate gradient angles, progress values and hues. Build and register your own typed custom property.",
    about: [
      "**IconVault**'s **CSS @property Playground** shows you why typed custom properties matter. Three live demos, an animated gradient angle, a progress value, and a hue shift, each run twice: once with **@property** registered and once without. The difference is the whole lesson: registered properties **interpolate smoothly**, unregistered ones jump, because the browser only knows how to transition a value it has a **syntax** for.",
      "Then build your own: pick a name, a syntax like **<angle>** or **<color>**, set inherits and an initial value, and the tool generates the **@property** at-rule plus the **CSS.registerProperty()** JavaScript equivalent. Registering on the page works for real where supported. Free, runs fully in your browser, and @property itself is Baseline widely available."
    ],
    faqs: [
      { q: "What does @property do in CSS?", a: "The @property at-rule registers a custom property with a type (syntax), an inherits flag, and an initial value. Once registered, the browser knows the value's type, so it can interpolate it in transitions and animations, validate it, and fall back to the initial value when invalid." },
      { q: "Why won't my custom property transition without @property?", a: "Unregistered custom properties are treated as opaque token streams (syntax '*'). The browser cannot interpolate between two arbitrary token streams, so a transition between --x: 0 and --x: 100 does nothing visible. Registering with syntax '<number>' or '<length>' tells the browser how to interpolate, and the transition starts working." },
      { q: "What syntax values can @property use?", a: "Common ones include <length>, <number>, <percentage>, <length-percentage>, <color>, <image>, <url>, <integer>, <angle>, <time>, <resolution>, <transform-function>, and <custom-ident>, plus the universal '*'. You can also combine types with the | operator, for example '<color> | <image>'." },
      { q: "Is @property the same as CSS.registerProperty()?", a: "They do the same thing. @property is the CSS at-rule form; CSS.registerProperty({ name, syntax, inherits, initialValue }) is the JavaScript equivalent. The at-rule is usually preferred because it lives with your other CSS, but the JS form is handy for libraries and polyfills." },
      { q: "Which browsers support @property?", a: "@property is Baseline widely available: Chrome 85+, Edge 85+, Safari 16.4+, and Firefox 128+. The demos in this tool detect support in your browser and the unregistered fallback shows what older browsers do." },
      { q: "What is @property commonly used for?", a: "The classic uses are animating conic-gradient angles for spinners and progress rings, smoothly transitioning registered numbers that feed calc(), animating gradient color stops, and building theme tokens that can transition between themes instead of snapping." }
    ],
    tags: [
      "css @property",
      "css property at-rule",
      "css registerproperty",
      "typed custom properties css",
      "css custom properties animation",
      "animate css variable",
      "transition css variable",
      "css @property tutorial",
      "css @property example",
      "registerproperty example",
      "css @property browser support",
      "css houdini properties and values api",
      "css properties and values api",
      "animate gradient angle css",
      "conic gradient animation",
      "css @property angle animation",
      "css variable transition not working",
      "why wont my css variable animate",
      "css custom property syntax",
      "at-property syntax list",
      "css @property inherits",
      "css @property initial value",
      "css typed om custom properties",
      "houdini custom properties",
      "css @property color transition",
      "animate css variable color",
      "progress ring css @property",
      "css @property number animation",
      "css @property length",
      "css @property percentage",
      "css @property integer",
      "css @property url",
      "css @property image",
      "@property vs var css",
      "css registerproperty javascript",
      "css.registerproperty example",
      "typed css variables",
      "css variable type checking",
      "css @property fallback",
      "css @property 2026",
      "learn css @property",
      "interactive css property playground",
      "css @property demo",
      "css @property generator",
      "css custom property registration",
      "animate custom property css",
      "css variable interpolation",
      "css @property mdn",
      "baseline css @property",
      "css @property caniuse",
      "css @property polyfill"
    ],
  };

export default seo;
