import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS zoom Playground - Interactive Lab | IconVault",
    metaDescription: "Compare CSS zoom vs transform: scale side by side with live layout measurements. Free interactive lab that runs fully in your browser.",
    about: [ "**IconVault**'s **CSS zoom Playground** is a free, interactive lab that shows exactly what the **CSS zoom property** does to your layout, next to **transform: scale()** for comparison. Drag the zoom slider and watch live measurements: zoom grows the element inside the document flow and pushes its siblings, while scale only paints bigger and leaves layout untouched. It is free and runs fully in your browser, nothing is uploaded.", "Use it to decide which technique fits your task. **Zoom** is the right call for accessible text resizing and print-friendly scaling where the element must reserve real space. **Transform scale** is better for hover effects and animations where layout must not jump. Every snippet on the page is copyable, so you can paste the exact CSS into your project." ],
    faqs: [
      { q: "What is the CSS zoom property?", a: "zoom is a CSS property that scales an element and its layout box. Unlike transform: scale(), zoom affects document flow: the element takes up more (or less) space and surrounding content reflows. It is now baseline across all modern browsers." },
      { q: "What is the difference between zoom and transform: scale?", a: "zoom changes layout measurements like offsetWidth and moves siblings; transform: scale() only changes painting, so offsetWidth stays the same and siblings do not move. Use zoom when space must be reserved, scale for visual-only effects." },
      { q: "Is CSS zoom supported in all browsers?", a: "Yes, zoom is now supported in Chrome, Edge, Safari and Firefox, so it is safe to use without prefixes. Older code sometimes avoided it because Firefox lacked support, but that gap is closed." },
      { q: "Does zoom affect child elements?", a: "Yes. zoom scales the element and everything inside it, including text, padding and borders, and the effect compounds with nested zoom values. It applies before transforms in the rendering pipeline." },
      { q: "Can I animate the zoom property?", a: "zoom is animatable in browsers that support it, but animating it triggers layout on every frame, which is expensive. For smooth 60fps animation prefer transform: scale(), and reserve zoom for discrete state changes." },
      { q: "Is this tool free?", a: "Yes. The CSS zoom Playground is completely free, runs fully in your browser, and every snippet can be copied with one click." },
    ],
    tags: [ "css zoom", "css zoom property", "zoom vs scale css", "css zoom vs transform scale", "transform scale vs zoom", "css zoom example", "how to use css zoom", "css zoom browser support", "is css zoom supported", "css zoom firefox", "css zoom chrome", "css scale property", "transform scale css", "css transform scale example", "difference between zoom and scale in css", "does css zoom affect layout", "css zoom layout shift", "css zoom reflow", "css zoom offsetwidth", "css zoom tutorial", "learn css zoom", "css zoom playground", "css zoom demo", "css zoom interactive", "css zoom visualizer", "css zoom calculator", "css transform scale layout", "transform scale does not affect layout", "css scale without layout shift", "css zoom text resize", "css zoom accessibility", "css zoom print", "css zoom property mdn", "css zoom syntax", "css zoom values", "zoom 1.5 css", "css zoom 2", "css zoom 0.5", "css zoom reset", "css zoom inherit", "css zoom percentage", "zoom property css tricks", "css zoom alternative", "scale vs zoom performance", "animating css zoom", "css zoom animation", "css zoom transition", "css zoom hover effect", "css zoom responsive", "css zoom mobile", "css zoom not working", "css zoom ignored", "css zoom vs font size", "css zoom container", "css zoom flexbox", "css zoom grid layout", "css layout affecting properties", "css visual vs layout properties" ],
  };

export default seo;
