import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Grid Track Sizing - Interactive Lab | IconVault",
    metaDescription: "Watch the browser resolve fr, minmax() and auto tracks into real pixels. Free interactive CSS grid lab, runs fully in your browser.",
    about: [ "**IconVault**'s **Grid Track Sizing** lab lets you configure **CSS grid column tracks** and watch the browser resolve them into real pixels. Pick track definitions like **1fr**, **minmax(150px, 1fr)**, **auto**, **min-content** or **max-content**, drag the container width, and read the exact resolved width of every track straight from the live layout engine. It is free and runs fully in your browser.", "This is the fastest way to build intuition for the **CSS grid track sizing algorithm**: how fr units divide leftover space, how minmax() clamps tracks between bounds, and how content-sized keywords react to long words. When the layout looks right, copy the generated **grid-template-columns** CSS and paste it into your project." ],
    faqs: [
      { q: "How does the fr unit work in CSS grid?", a: "1fr represents one share of the free space left after fixed-size tracks and gaps are subtracted. 2fr gets twice as much as 1fr. fr tracks never shrink below their minimum, which is why minmax() is often paired with them." },
      { q: "What does minmax() do in grid-template-columns?", a: "minmax(min, max) clamps a track between a minimum and maximum size. For example minmax(150px, 1fr) never goes below 150px but grows with available space. It is the standard way to build responsive grids without media queries." },
      { q: "What is the difference between auto, min-content and max-content tracks?", a: "auto sizes from content with some flexibility, min-content shrinks to the longest unbreakable word, and max-content grows to fit the whole content on one line. All three react to what is inside the track, unlike fr or px." },
      { q: "Why is there unused space in my grid?", a: "Unused space appears when no fr track claims the leftover room, for example with only px and max-content tracks in a wide container. Add an fr track or use justify-content to distribute the extra space." },
      { q: "How can I see resolved track sizes in devtools?", a: "Chrome and Firefox devtools overlay track sizes on the grid, and getComputedStyle(el).gridTemplateColumns returns the resolved pixel values, which is exactly what this lab reads and displays." },
      { q: "Is this tool free?", a: "Yes. Grid Track Sizing is completely free and runs fully in your browser, with copyable CSS output." },
    ],
    tags: [ "css grid track sizing", "grid-template-columns", "css grid fr unit", "css grid minmax", "minmax css grid example", "css grid auto vs fr", "css grid min-content max-content", "css grid fit-content", "how fr unit works css", "css grid leftover space", "css grid track size calculator", "css grid visualizer", "css grid playground", "css grid interactive tutorial", "learn css grid tracks", "grid-template-columns fr", "grid-template-columns minmax", "grid-template-columns auto", "css grid column width", "css grid responsive columns", "css grid repeat minmax", "repeat auto-fit minmax", "css grid track sizing algorithm", "css grid intrinsic sizing", "css grid fixed vs flexible tracks", "css grid gap", "css grid container width", "css grid resolved sizes", "getcomputedstyle gridtemplatecolumns", "css grid devtools", "css grid holy grail", "css grid sidebar layout", "css grid 3 columns", "css grid equal columns", "css grid column sizes", "understanding css grid", "css grid tutorial", "css grid explained", "css grid cheat sheet", "css grid generator", "css grid template columns generator", "minmax 150px 1fr", "minmax 100px 300px", "css grid max-content example", "css grid min-content example", "css grid auto fit vs auto fill", "css grid fr minimum", "fr unit minimum content", "css grid overflow track", "css grid long word overflow", "css grid track list", "css grid explicit tracks", "css grid sizing playground", "interactive css grid lab" ],
  };

export default seo;
