import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Stacking Context - Interactive CSS Lab | IconVault",
    metaDescription: "Visualize CSS stacking contexts and z-index paint order live. Tweak position, opacity, transform and isolation, see what paints on top.",
    about: [
      "**IconVault**'s **CSS Stacking Context** visualizer turns the most confusing part of CSS painting into something you can poke. Three overlapping boxes each get live controls for **position**, **z-index**, **opacity**, **transform**, **isolation** and **filter**. The stage renders your exact values while a back-to-front paint-order readout, computed per the spec, explains which box wins and why.",
      "Gotcha alerts fire as you experiment: **z-index ignored on static elements**, **opacity below 1** creating a stacking context, transforms and filters trapping children. It is free, runs fully in your browser, and the current setup exports as copyable CSS with the paint order baked into a comment."
    ],
    faqs: [
      { q: "What is a stacking context in CSS?", a: "A stacking context is a group of elements painted together as a unit. Inside it, z-index orders children relative to each other, but the whole group is then placed atomically in its parent context. That is why a child with z-index 9999 can still render below an element with z-index 1: its parent context sits lower in the parent's paint order." },
      { q: "What creates a stacking context?", a: "Positioned elements with a z-index other than auto, and also: opacity below 1, any transform except none, filter except none, isolation: isolate, mix-blend-mode other than normal, will-change on those properties, perspective, clip-path, mask, contain: layout/paint, and a few others. This tool flags each one live as you toggle it." },
      { q: "Why does z-index not work on my element?", a: "The most common cause is position: static: z-index only applies to positioned elements (relative, absolute, fixed, sticky). The next most common cause is a parent stacking context trapping the element: no z-index inside can escape above a sibling stacking context." },
      { q: "What is the CSS paint order?", a: "Within a stacking context, back to front: the context root's background and borders, negative z-index children, non-positioned block backgrounds, floats, inline content, positioned z-index auto/0 children (in DOM order), then positive z-index children. This tool's readout follows that order." },
      { q: "Does opacity really create a stacking context?", a: "Yes. Any opacity value below 1 creates a stacking context, which surprises people when a semi-transparent overlay suddenly traps its children's z-index. Toggle the opacity slider in this tool and watch the stacking-context alert appear." },
      { q: "How do I debug z-index issues in DevTools?", a: "In Chrome DevTools, the Layers panel and the 3D view show stacking contexts, and the Rendering panel can highlight them. A quicker mental model: find the nearest ancestor that creates a stacking context for each competing element, then compare those ancestors instead of the elements themselves." }
    ],
    tags: [
      "css stacking context",
      "z-index stacking context",
      "css paint order",
      "z-index not working",
      "z index ignored",
      "stacking context explained",
      "css stacking order",
      "what creates a stacking context",
      "opacity stacking context",
      "transform stacking context",
      "filter stacking context",
      "isolation isolate css",
      "z-index position static",
      "z-index absolute not working",
      "css z-index tutorial",
      "learn css stacking context",
      "interactive z-index demo",
      "css paint order visualizer",
      "z-index visualizer",
      "stacking context visualizer",
      "css stacking context list",
      "does transform create stacking context",
      "does opacity create stacking context",
      "does filter create stacking context",
      "will-change stacking context",
      "mix-blend-mode stacking context",
      "css z-index 9999 not working",
      "child z-index parent stacking context",
      "z-index trapped",
      "css paint order spec",
      "stacking context mdn",
      "css z-index best practices",
      "debug z-index chrome devtools",
      "css stacking context 2026",
      "css positioned elements painting order",
      "negative z-index css",
      "z-index auto vs 0",
      "isolation css property",
      "css contain stacking context",
      "clip-path stacking context",
      "perspective stacking context",
      "css stacking context examples",
      "z-index modal overlay",
      "dropdown z-index problem",
      "css dropdown behind content",
      "tooltip z-index issue",
      "css stacking context playground",
      "interactive css stacking demo",
      "css rendering order",
      "browser paint order css"
    ],
  };

export default seo;
