import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Anchor Positioning - Interactive CSS Lab | IconVault",
    metaDescription: "Learn CSS anchor positioning with a live draggable demo. Try position-area, anchor() and @position-try, then copy production CSS. Free, in your browser.",
    about: [ "**IconVault**'s **CSS Anchor Positioning** lab is a hands-on playground for the new CSS anchor positioning spec. Drag the anchor box around the demo canvas, pick a **position-area** value, adjust the gap, and toggle **position-try-fallbacks** to watch the tooltip flip automatically near edges. Every control updates the live demo and the copyable CSS snippet in real time, so you learn the syntax by doing instead of reading. It is free and runs fully in your browser, with nothing to install.",
    "Anchor positioning finally lets you tether an element, like a tooltip, popover or menu, to another element with pure CSS, replacing fragile JavaScript measurement code. If your browser supports the spec you get the **real CSS engine** driving the demo; older browsers get an honest JS simulation plus the exact code to paste once you open Chrome 125+, Edge 125+ or a recent Safari. The lab also covers the **anchor()** function for reading an anchor's edges and **@position-try** for declaring explicit fallback positions." ],
    faqs: [
      { q: "What is CSS anchor positioning?", a: "It is a CSS feature that positions an element relative to another element (the anchor) without JavaScript. You mark an element with anchor-name, then position another element with position-anchor and position-area. The browser keeps the two aligned even when the anchor moves." },
      { q: "What does position-area do?", a: "position-area places the positioned element on one side of its anchor using one or two keywords, like top, bottom left, or center. It replaces manual translate math and pairs with margins to set the gap from the anchor." },
      { q: "What are position-try-fallbacks?", a: "They are fallback positions the browser tries when the first choice would overflow the viewport. flip-block and flip-inline flip the position automatically, or you can declare exact fallbacks with @position-try rules." },
      { q: "Which browsers support anchor positioning?", a: "Chrome 125+, Edge 125+ and Safari 26+ support it. Firefox does not support it yet except behind a flag. This lab detects support and shows a JS simulation on unsupported browsers so you can still learn the syntax." },
      { q: "What is the anchor() function?", a: "anchor() reads a specific edge of the anchor, for example bottom: anchor(top) places the element's bottom edge at the anchor's top edge. It is useful for arrows, connecting lines and fine-tuned alignment." },
      { q: "Does anchor positioning work with popovers?", a: "Yes, it pairs perfectly with the Popover API. A popover in the top layer can use position-anchor and position-area to stay attached to its invoker, and position-try-fallbacks keep it on screen." },
    ],
    tags: [ "css anchor positioning", "anchor positioning css", "css anchor", "position-anchor", "position-area css", "anchor-name css", "css position-try", "anchor() css function", "@position-try", "css anchor positioning tutorial", "css anchor positioning example", "tooltip css anchor positioning", "css popover positioning", "position-area top left", "position-try-fallbacks", "flip-block flip-inline", "css anchored tooltip", "anchor positioning browser support", "css anchor positioning chrome", "css anchor positioning firefox", "anchor() top css", "anchor() left css", "css anchor positioning demo", "learn css anchor positioning", "css anchor positioning generator", "position-area generator", "css tooltip without javascript", "pure css tooltip positioning", "css menu positioning", "dropdown positioning css", "css anchor positioning vs absolute", "anchor positioning fallback", "css anchor positioning polyfill", "position-anchor example", "anchor-name example", "css anchor positioning mdn", "how to use css anchor positioning", "css anchor positioning syntax", "position area css values", "css anchor positioning 2026", "anchored popover css", "css top layer positioning", "popover anchor positioning", "css anchor positioning not working", "anchor positioning safari", "css anchor positioning can i use", "position-area center", "position-area bottom", "css anchor positioning playground", "interactive css anchor demo", "css anchor positioning tool" ],
  };

export default seo;
