import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Variables Builder - Free Online CSS Tool | IconVault",
    metaDescription: "Build a CSS custom property theme visually: add variables, edit colors, start from Light, Dark or Pastel presets, preview and export :root CSS. Free.",
    about: [ "**IconVault**'s **CSS Variables Builder** creates **CSS custom properties** (variables) through a visual theme editor. Add variables with names and values, get a **color picker** automatically when a value is a color, or start from **starter themes** like Light, Dark and Pastel and customize from there. A **live preview** shows your theme applied to sample components, and the tool exports a clean **:root block** you can drop into any project.",
    "Everything runs **100% in your browser**: no sign-up, no uploads, free to use. It is the fastest way to set up a **design token** palette for colors, spacing, radii and typography, then switch themes by swapping one block of variables. The generated CSS is plain standard custom-property syntax that works in every modern browser." ],
    faqs: [
      { q: "What does the CSS Variables Builder do?", a: "It helps you create CSS custom properties (variables) visually. You add named variables like --primary with values, preview them on sample UI, and export a :root block of CSS." },
      { q: "What are CSS custom properties used for?", a: "They store reusable values like colors, spacing and border radii. Changing one variable updates every place that references it, which makes theming and design systems much easier." },
      { q: "Can I build dark mode with this?", a: "Yes. Start from the Dark preset, adjust the colors to your taste, and export the :root block. Swap it with your light theme's variables to toggle themes." },
      { q: "Does it handle color values specially?", a: "Yes. When a variable's value looks like a hex color, the tool shows a color picker so you can choose colors visually instead of typing hex codes." },
      { q: "How do I use the exported CSS?", a: "Copy the :root block into your stylesheet and reference variables with var(--name), for example color: var(--primary)." },
      { q: "Is it free?", a: "Yes, it is free with no account required, and everything runs locally in your browser." }
    ],
    tags: [
      "css variables builder",
      "css custom properties generator",
      "css variables generator",
      "css custom properties tool",
      "css variable theme builder",
      "css design tokens generator",
      "css theme generator",
      "css dark mode generator",
      "css color palette variables",
      "css root variables generator",
      "generate :root css",
      "css :root block builder",
      "css variable naming",
      "how to use css variables",
      "css var() function",
      "css custom properties explained",
      "css variables tutorial",
      "css variables for beginners",
      "css theming with variables",
      "css variable color picker",
      "online css theme maker",
      "css palette builder",
      "website color theme generator",
      "css light dark theme",
      "css pastel theme",
      "css variable presets",
      "design token builder",
      "design tokens css",
      "css tokens generator",
      "export css variables",
      "css variables copy paste",
      "css custom property syntax",
      "define css variables in root",
      "css variable fallback",
      "css variables vs sass variables",
      "css variables browser support",
      "css variable inheritance",
      "css variable scope",
      "override css variables",
      "css variables javascript",
      "update css variables with js",
      "css variables best practices",
      "css variable naming conventions",
      "semantic css variables",
      "css spacing variables",
      "css border radius variables",
      "css typography variables",
      "css variable playground",
      "interactive css variables",
      "free css theme tool"
    ],
  };

export default seo;
