import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS @starting-style - Interactive CSS Lab | IconVault",
    metaDescription: "Learn CSS @starting-style: animate elements in from display:none with pure CSS. Compare techniques live, copy the working recipe.",
    about: [
      "**IconVault**'s **CSS @starting-style** lab teaches the pure-CSS way to animate elements in from **display: none**. Three techniques run side by side on the same card: **@starting-style** alone, **transition-behavior: allow-discrete** alone, and both combined. You will feel the classic gotcha firsthand: @starting-style alone does nothing, allow-discrete alone animates only the exit, and only the pair gives you a smooth entry and exit.",
      "Pick a **fade, slide or scale effect**, dial the duration, and copy the **generated CSS**. It is free and runs fully in your browser, and **@starting-style** is **Baseline new** (Chrome 117+, Safari 17.5+, Firefox 129+). The same recipe animates popovers and dialogs open and closed without a line of JavaScript."
    ],
    faqs: [
      { q: "What is @starting-style in CSS?", a: "@starting-style is an at-rule that defines the starting values for a transition when an element's style changes for the first time, for example when it goes from display: none to display: block. Without it, there is no 'from' state for the entry transition, so the element just appears." },
      { q: "Why is my @starting-style animation not working?", a: "Almost always because display is not transitionable by default. You also need transition-behavior: allow-discrete on the element so the display change participates in the transition. @starting-style alone cannot animate display: none to display: block. This tool's technique switcher demonstrates the failure live." },
      { q: "How do I animate an element from display: none?", a: "The recipe: transition the visual properties plus display (transition: opacity .4s, display .4s), add transition-behavior: allow-discrete, and define @starting-style { .el { opacity: 0; } }. The browser then animates opacity while display flips at the 50% mark." },
      { q: "Can @starting-style animate popovers and dialogs?", a: "Yes, that is one of its best uses. Native popovers and <dialog> elements toggle between display: none and display: block, so the same allow-discrete plus @starting-style recipe gives you animated open and close transitions with zero JavaScript." },
      { q: "Which browsers support @starting-style?", a: "@starting-style shipped in Chrome 117, Edge 117, Safari 17.5, and Firefox 129, making it Baseline newly available. Older browsers ignore the at-rule and the element simply appears, which is a safe degradation." },
      { q: "What is the difference between @starting-style and from keyframes?", a: "@starting-style defines the before-change style for the very first style update, which is what display: none to block needs. A @keyframes from rule only applies inside an animation, not to transitions triggered by a display flip, so it cannot solve the entry-from-none case on its own." }
    ],
    tags: [
      "css @starting-style",
      "starting style css",
      "css starting-style example",
      "animate display none css",
      "css transition display none",
      "display none to block animation css",
      "css entry animation",
      "pure css enter animation",
      "transition-behavior allow-discrete",
      "allow discrete css",
      "css allow-discrete example",
      "animate popover css",
      "css popover animation",
      "dialog open animation css",
      "animate dialog css",
      "@starting-style browser support",
      "@starting-style not working",
      "starting-style allow-discrete",
      "css display transition 2026",
      "interpolate-size allow-keywords",
      "animate to auto height css",
      "css discrete animation",
      "transition display css tricks",
      "css @starting-style tutorial",
      "learn css starting style",
      "interactive @starting-style demo",
      "css starting style playground",
      "@starting-style mdn",
      "@starting-style caniuse",
      "baseline @starting-style",
      "css entry transition",
      "element appear animation css",
      "fade in from display none",
      "slide in from display none css",
      "css transition behavior",
      "transition-behavior css property",
      "css transition discrete properties",
      "animate visibility css",
      "visibility transition css",
      "css overlay property",
      "popover transition css",
      "dialog transition css",
      "@starting-style popover example",
      "css @starting-style dialog",
      "entry animation no javascript",
      "css only modal animation",
      "display none animation hack",
      "css starting style generator",
      "copy paste display animation css",
      "css starting-style fade slide scale"
    ],
  };

export default seo;
