import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Shape Builder - Free Online Tool | IconVault",
    metaDescription: "Build clip-path shapes visually: drag polygon points, tune circle, ellipse and inset, or write path(). Free, live preview, runs in browser.",
    about: [
      "**IconVault**'s **CSS Shape Builder** is a visual editor for the CSS clip-path property. Drag polygon points around on a grid, tune circle(), ellipse() and inset() with sliders, or hand-write path() data, and watch the clipped result update live. Copy the generated CSS or download it as a file. It is free and runs fully in your browser.",
      "**Clip-path** is the easiest way to make **non-rectangular UI**: angled section dividers, star badges, hexagon avatars, arrow buttons and blob shapes, all without images or SVG files. The builder writes the exact **polygon coordinates** for you, which beats hand-calculating percentages, and the live preview shows precisely how the shape will look at any size."
    ],
    faqs: [
      { q: "What is clip-path?", a: "clip-path is a CSS property that clips an element to a shape: polygon(), circle(), ellipse(), inset() or path(). Everything outside the shape is hidden, but the element keeps its layout box, so surrounding content is unaffected." },
      { q: "How do I make a triangle with clip-path?", a: "Use polygon(50% 0, 100% 100%, 0 100%). In the builder, pick the Triangle preset and drag the points if you want a custom angle." },
      { q: "Does clip-path work in all browsers?", a: "Basic shapes (polygon, circle, ellipse, inset) work in all modern browsers. path() has good support in Chrome, Edge and Safari, with Firefox support added more recently. Always test your target browsers." },
      { q: "Can I animate clip-path?", a: "Yes, as long as the start and end shapes have the same structure, for example two polygons with the same number of points. The builder's presets keep point counts consistent to help with this." },
      { q: "What is the difference between clip-path and border-radius?", a: "border-radius only rounds corners of a rectangle. clip-path can cut any polygonal or curved shape, including stars, arrows and custom paths." },
      { q: "Is my shape data sent anywhere?", a: "No. Everything is computed locally in your browser; the download is generated on your device." }
    ],
    tags: [
      "css shape builder",
      "clip-path generator",
      "css clip path builder",
      "polygon clip path generator",
      "css triangle generator",
      "clip path maker online",
      "css shape generator",
      "clip-path polygon tool",
      "css star shape clip path",
      "hexagon clip path css",
      "css arrow shape",
      "clip path circle generator",
      "css ellipse clip path",
      "clip path inset rounded",
      "css path clip path generator",
      "clip-path visual editor",
      "css clip path examples",
      "non rectangular css shapes",
      "angled dividers css",
      "css blob shape generator",
      "clip path chevron",
      "css diamond shape",
      "clip-path animation",
      "animate clip path polygon",
      "clip path vs border radius",
      "css clip path browser support",
      "clip path path() examples",
      "css shape() function",
      "clip path responsive",
      "css clip path code generator free",
      "make triangle with css",
      "css hexagon avatar",
      "star rating css clip path",
      "clip path badge",
      "css ribbon shape",
      "clip path parallelogram",
      "css trapezoid",
      "clip path pentagon",
      "css clip path tool online free",
      "polygon points drag editor",
      "css shapes without svg",
      "clip path image mask",
      "css clip path generator free",
      "learn clip path css",
      "clip path tutorial",
      "css clip path percentage",
      "clip path coordinates explained",
      "css shape builder online",
      "clip path arrow button",
      "css custom shapes generator"
    ],
  };

export default seo;
