import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Individual Transforms - Interactive CSS Lab | IconVault",
    metaDescription: "Control translate, rotate and scale as independent CSS properties. Live sliders, fixed application order diagram and copyable CSS. Free, in your browser.",
    about: [ "**IconVault**'s **CSS Individual Transforms** lab lets you drive **translate**, **rotate** and **scale** as separate CSS properties with live sliders. Move the box around the canvas, change **transform-origin**, and toggle an extra **transform** skew to see how the individual properties and the classic transform list combine. A fixed **application order** diagram shows exactly what the browser does first, and every change updates the copyable CSS instantly. It is free and runs fully in your browser.",
    "Individual transform properties fix the oldest annoyance of CSS transforms: with the shorthand you had to repeat the whole chain to change one part, and a **rotate** transition would wipe out your **translate**. Now each property animates independently, which makes hover effects, entrance animations and interactive motion far simpler to write. The lab also demonstrates that the three properties always apply in the order translate, rotate, scale, followed by the **transform** property, and it works in all modern browsers with no fallback needed." ],
    faqs: [
      { q: "What are CSS individual transform properties?", a: "They are the translate, rotate and scale properties, which apply transforms independently of the transform property. Each can be set, transitioned and animated on its own without affecting the others." },
      { q: "In what order do individual transforms apply?", a: "The browser always applies them in the fixed order translate, then rotate, then scale, and finally the transform property's list. This order cannot be changed, unlike a hand-written transform chain." },
      { q: "Can I combine them with the transform property?", a: "Yes. Individual properties apply first, then the transform list runs on top of the result. That makes transform a good place for one-off tweaks while the individual properties hold the base pose." },
      { q: "Which browsers support individual transforms?", a: "All modern browsers: Chrome 104+, Edge 104+, Firefox 72+ and Safari 14.1+. No fallback is needed for current audiences." },
      { q: "How do I animate just rotation?", a: "Transition the rotate property: .box { transition: rotate 0.3s; } .box:hover { rotate: 45deg; }. Your translate and scale stay untouched, which was impossible with the shorthand without re-declaring everything." },
      { q: "Do individual properties accept the same units?", a: "Yes. translate takes lengths and percentages, rotate takes angles, and scale takes unitless numbers. They also accept multiple values, like translate: 10px 20px and scale: 1.2 0.8." },
    ],
    tags: [ "css individual transforms", "css translate rotate scale", "translate property css", "rotate property css", "scale property css", "css individual transform properties", "css transform vs translate", "animate rotate without translate", "css transform order", "translate rotate scale order", "css transform-origin", "css transform property", "individual transforms tutorial", "learn css transforms", "css transforms playground", "interactive css transform", "css transform generator", "css transform demo", "css rotate transition", "css translate transition", "css scale transition", "transform-box css", "css transform independent", "css transform shorthand vs individual", "css motion tutorial", "css animation transforms", "css transform cheat sheet", "css transform examples", "translate css mdn", "rotate css mdn", "scale css mdn", "css transform browser support", "css transforms 2026", "css hover rotate effect", "css entrance animation", "css transform copy paste", "css transform visualizer", "css transform sliders", "how to use css translate", "css rotate deg", "css scale x y", "transform-origin center", "css transform-origin examples", "css translate x y", "css transform list", "skew transform css", "css transform playground", "css transform lab", "css animation tips", "smooth css animations" ],
  };

export default seo;
