import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS transition-behavior - Interactive CSS Lab | IconVault",
    metaDescription: "Learn transition-behavior: allow-discrete with live side-by-side demos. Animate display and visibility transitions, copy the CSS.",
    about: [
      "**IconVault**'s **CSS transition-behavior** lab shows what one line of CSS changes. Two panes toggle **display** or **visibility** together: the default pane flips instantly, while the **allow-discrete** pane fades and slides around the flip, because discrete properties now participate in the transition and change at the 50% mark. A duration slider lets you slow the whole thing down and watch it happen.",
      "The tool generates the complete recipe including the **@starting-style** block that entry-from-none needs, and it is free and runs fully in your browser. transition-behavior is Baseline new (Chrome 117+, Safari 18+, Firefox 129+), and the page spells out exactly which half of the animation each piece is responsible for."
    ],
    faqs: [
      { q: "What does transition-behavior: allow-discrete do?", a: "It opts discrete properties like display and visibility, and discrete values of other properties, into transitions. Instead of flipping instantly at the start or end, the discrete change happens at the 50% mark of the transition, so surrounding animatable properties like opacity can animate around it." },
      { q: "How do I transition display: none to block?", a: "Set transition: opacity .5s, display .5s; transition-behavior: allow-discrete; on the element. The display flip then happens mid-transition. For the entry half (none to block) you additionally need @starting-style to define the from-values, since there is no previous rendered state to transition from." },
      { q: "What is the difference between @starting-style and transition-behavior?", a: "transition-behavior: allow-discrete makes the discrete property change transitionable at all. @starting-style provides the starting values for the first style update (the entry). Exit animations need only allow-discrete; entry animations need both." },
      { q: "Can I animate visibility with transition-behavior?", a: "Yes. visibility is discrete (visible, hidden, collapse), so without allow-discrete it flips at the end of the transition delay. With allow-discrete it flips at 50%, which pairs naturally with a fade: the element fades out, then becomes hidden halfway through." },
      { q: "Which browsers support transition-behavior?", a: "Chrome 117+, Edge 117+, Safari 18+, and Firefox 129+ support transition-behavior: allow-discrete. Older browsers ignore the declaration and fall back to the instant flip, which is an acceptable degradation for most show/hide UI." },
      { q: "What is the overlay property?", a: "overlay is a newer CSS property designed for top-layer transitions: it keeps an element in the top layer during its exit transition when combined with allow-discrete, so popovers and dialogs can animate closed instead of vanishing. It pairs with the same recipe this tool teaches." }
    ],
    tags: [
      "css transition-behavior",
      "transition behavior css",
      "allow-discrete css",
      "transition-behavior allow-discrete",
      "css allow discrete example",
      "animate display none to block",
      "css display transition",
      "transition display property css",
      "discrete animation css",
      "css transition discrete values",
      "animate visibility css",
      "visibility transition allow-discrete",
      "transition-behavior browser support",
      "transition-behavior caniuse",
      "transition-behavior not working",
      "css transition behavior tutorial",
      "learn css transition-behavior",
      "interactive transition-behavior demo",
      "css transition behavior playground",
      "allow-discrete vs starting-style",
      "css exit animation",
      "animate element hide css",
      "fade out display none css",
      "css transition 50% discrete",
      "discrete properties css list",
      "which css properties are discrete",
      "css overlay property",
      "overlay css popover",
      "top layer transition css",
      "animate popover close css",
      "dialog close animation css",
      "css transition-behavior mdn",
      "baseline transition-behavior",
      "css transition-behavior 2026",
      "css transitions level 2",
      "transition behavior normal vs allow-discrete",
      "css flip at 50 percent",
      "display none fade out pure css",
      "show hide animation css only",
      "css transition visibility hidden",
      "collapse transition css",
      "content-visibility transition",
      "css transition-behavior generator",
      "copy paste allow-discrete css",
      "css discrete keyframes",
      "@starting-style allow-discrete combined",
      "css enter exit animations",
      "allow-discrete transition example code",
      "css transition-behavior demo",
      "transition display block animation"
    ],
  };

export default seo;
