import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Paint API - Interactive CSS Lab | IconVault",
    metaDescription: "Build Houdini registerPaint() worklets live in your browser. Edit paint code, tweak custom properties, preview instantly, copy the CSS.",
    about: [
      "**IconVault**'s **CSS Paint API** playground is a hands-on lab for the Houdini **Paint API**: the browser feature that lets you call **registerPaint()** in a worklet and draw element backgrounds with JavaScript canvas code. Pick a preset like checkerboard, stripes, polka dots or confetti, edit the worklet source directly, then adjust **--paint-color** and **--paint-size** custom properties and watch the preview repaint instantly.",
      "Everything runs fully in your browser and is free to use. Pressing Paint it registers your worklet through **CSS.paintWorklet.addModule()** for real, and you can copy the worklet JavaScript plus the **background-image: paint(name)** CSS to drop into any project. Honest note: the Paint API is **Chromium-only** (Chrome, Edge, Opera), so the tool detects support and every snippet includes a background-color fallback for Firefox and Safari."
    ],
    faqs: [
      { q: "What is the CSS Paint API?", a: "The CSS Paint API is part of the Houdini task force APIs. It lets you register a custom paint worklet with registerPaint() and then use it in CSS as background-image: paint(my-painter). The worklet draws with the 2D canvas API, and the browser repaints automatically when the element resizes or its input custom properties change." },
      { q: "Which browsers support CSS.paintWorklet?", a: "Only Chromium browsers (Chrome, Edge, Opera) support the Paint API. Firefox and Safari do not. This tool detects support in your browser and always generates a background-color fallback so your design degrades gracefully where paint() is ignored." },
      { q: "How do custom properties reach the paint worklet?", a: "A worklet declares static get inputProperties() returning the custom property names it reads, for example ['--paint-color', '--paint-size']. Inside paint(), you read them with props.get('--paint-color'). When any listed property changes, the browser repaints the element automatically." },
      { q: "Does paint() work hurt performance?", a: "Paint worklets run off the main thread, so heavy drawing does not block interaction the way main-thread canvas can. Still, keep per-frame work modest: cache gradients, avoid huge loops, and prefer input properties over reparsing on every paint." },
      { q: "Can I use the worklet code from this tool in production?", a: "Yes. Copy the worklet into a .js file, serve it from your own origin, and register it with CSS.paintWorklet.addModule('paint-worklet.js'). Worklets require a secure context (HTTPS or localhost) and only take effect in Chromium browsers, so keep the fallback background in place." },
      { q: "Why does my preview say the Paint API is not supported?", a: "You are likely in Firefox or Safari, which never shipped the API. Switch to Chrome, Edge or Opera and the register button will work. The code editor and generated CSS remain useful for learning regardless of browser." }
    ],
    tags: [
      "css paint api",
      "houdini paint api",
      "registerpaint",
      "css paint worklet",
      "paint worklet example",
      "css houdini tutorial",
      "background image paint",
      "css paint api browser support",
      "registerpaint example",
      "houdini css examples",
      "css paint api firefox",
      "css paint api safari",
      "paint worklet custom properties",
      "inputproperties paint worklet",
      "css paintworklet addmodule",
      "houdini worklet tutorial",
      "css paint api generator",
      "dynamic css backgrounds javascript",
      "canvas css background",
      "programmatic css background",
      "css paint api demo",
      "houdini paint api demo",
      "registerpaint worklet code",
      "css paint checkerboard",
      "css paint stripes pattern",
      "polka dot css background code",
      "confetti css background",
      "css paint api patterns",
      "custom css paint function",
      "css houdini paint api explained",
      "what is css houdini",
      "houdini apis list",
      "css paint api vs canvas",
      "paint worklet performance",
      "css paint api fallback",
      "background paint css function",
      "css paint worklet typescript",
      "registerpaint typescript",
      "houdini paint api react",
      "css paint worklet not working",
      "css.paintworklet undefined",
      "paint worklet blob url",
      "css paint api 2026",
      "learn css houdini",
      "interactive css paint playground",
      "css paint worklet builder",
      "generate paint worklet online",
      "css paint api playground",
      "houdini registerpaint tutorial",
      "css custom paint demo",
      "paint worklet input properties example",
      "css paint api background pattern generator"
    ],
  };

export default seo;
