import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS reading-flow - Interactive CSS Lab | IconVault",
    metaDescription: "Learn CSS reading-flow: reorder flex items visually, then walk the Tab order with and without it. Live simulation, copyable CSS.",
    about: [
      "**IconVault**'s **CSS reading-flow** lab teaches the property that fixes one of the sneakiest accessibility bugs in modern CSS. Reorder cards with **flex-direction: row-reverse**, **column-reverse** or the **order** property, then step through the simulated keyboard walk: with **reading-flow: normal** focus follows DOM order while your eyes see something else; with **flex-visual** or **flex-flow** the Tab path matches the visual layout.",
      "The tool is free and runs fully in your browser. Because reading-flow is still **experimental** and not in stable browsers, the focus walk simulates the spec algorithm and says so plainly, while the copied snippet applies the real property so your CSS is ready when browsers ship it. You will leave knowing exactly when to reorder the DOM instead."
    ],
    faqs: [
      { q: "What is the CSS reading-flow property?", a: "reading-flow controls the order of sequential focus navigation (Tab key) and, in some proposals, screen-reader order, for flex and grid containers. Values like flex-visual make focus follow the visual order of items instead of the DOM order, fixing the mismatch created by order, row-reverse, or grid placement." },
      { q: "Why does visual order differ from Tab order?", a: "Properties like order, flex-direction: row-reverse, and explicit grid placement only change the visual rendering. The DOM order is unchanged, and browsers move keyboard focus through the DOM. So a card that looks first can be focused last, which confuses keyboard and screen-reader users." },
      { q: "Which browsers support reading-flow?", a: "As of now, reading-flow is experimental and available only in Chrome Canary behind a flag. It is not in any stable browser. This tool simulates the specified behavior so you can learn the concept today and generates the real CSS for when support lands." },
      { q: "What are the reading-flow values?", a: "The specified values include normal (DOM order), flex-visual (visual order in flex containers), flex-flow (flow direction then wrap order), grid-rows, grid-columns, grid-order, and source-order (explicit DOM order). This lab covers the flex values, which are the most common case." },
      { q: "Should I use order or reading-flow to reorder content?", a: "If the reordering is meaningful for all users, reorder the DOM itself: it works everywhere today. Use order plus reading-flow only for purely presentational reordering, and only once browser support exists. Until then, DOM order is the accessible order." },
      { q: "Does reading-flow affect screen readers?", a: "The intent is that sequential navigation, including Tab focus, follows the reading flow. Screen-reader virtual-cursor behavior is still being worked out in the spec, so treat DOM order as the screen-reader order for now and keep meaningful content in logical DOM order." }
    ],
    tags: [
      "css reading-flow",
      "reading flow css",
      "css reading flow browser support",
      "reading-flow flex-visual",
      "reading-flow flex-flow",
      "reading-flow grid-rows",
      "tab order css",
      "css tab order visual order",
      "flexbox tab order problem",
      "order property accessibility",
      "css order keyboard navigation",
      "flex-direction row-reverse tab order",
      "screen reader order vs visual order css",
      "css visual order dom order mismatch",
      "reading flow spec",
      "css display ruby reading flow",
      "sequential focus navigation css",
      "css focus order flexbox",
      "how to change tab order css",
      "css reading-flow example",
      "reading-flow tutorial",
      "css reading-flow 2026",
      "learn css reading-flow",
      "interactive css reading flow demo",
      "css reading flow playground",
      "flex visual order keyboard",
      "grid tab order css",
      "css order property a11y",
      "accessibility flexbox order",
      "dom order vs display order",
      "css reading-flow caniuse",
      "reading-flow chrome flag",
      "css reading flow mdn",
      "focus order css grid",
      "keyboard navigation flexbox",
      "tabindex css order",
      "css logical order focus",
      "reading-flow source-order",
      "css reading-flow values",
      "what is reading-flow css",
      "csswg reading flow",
      "flex-flow reading order",
      "css reading order property",
      "fix tab order flexbox",
      "visual vs dom order css",
      "css reading-flow polyfill",
      "reading flow css tricks",
      "accessible reordering css",
      "css order screen reader",
      "keyboard trap flexbox order"
    ],
  };

export default seo;
