import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Subgrid - Interactive CSS Lab | IconVault",
    metaDescription: "Learn CSS subgrid with a live with/without comparison. Align nested grid items to parent tracks, toggle guides, copy the CSS.",
    about: [
      "**IconVault**'s **CSS Subgrid** lab makes the concept click in seconds. A row of pricing cards with deliberately uneven content renders twice in spirit: flip the switch and each card either sizes its own rows (buttons land at ragged heights) or inherits the parent tracks with **grid-template-rows: subgrid** (every title, body and button lines up). Row-track guides overlay the demo so you can see the shared tracks.",
      "Adjust the column count and gap, then copy the **generated CSS and HTML**. It is free, runs fully in your browser, and subgrid is **Baseline widely available** (Chrome 117+, Firefox 71+, Safari 16+), so the code you copy works in **production today**."
    ],
    faqs: [
      { q: "What is CSS subgrid?", a: "Subgrid lets a grid item that is itself a grid adopt its parent's track sizing: grid-template-rows: subgrid (or columns) makes the nested grid use the parent's row tracks instead of defining its own. Child items of the nested grid then align with items in sibling subgrids, which is impossible with regular nested grids." },
      { q: "When should I use subgrid?", a: "Whenever sibling components need internal alignment across a shared grid: card rows with uneven text, form label/input pairs, table-like layouts built from divs, and multi-column article layouts where headlines, images and captions must line up across columns." },
      { q: "How is subgrid different from a nested grid?", a: "A nested grid defines its own tracks, so its rows size to its own content and never align with neighboring cards. A subgrid borrows the parent's tracks: the nested items participate in the parent's sizing, so corresponding rows across cards share heights." },
      { q: "What is the syntax for subgrid?", a: "On the grid item that becomes a nested grid: display: grid; grid-template-rows: subgrid; (or grid-template-columns: subgrid). Pair it with grid-row: span N so the item covers the parent tracks it wants to inherit. You can name lines too: grid-template-rows: subgrid [header] [body] [footer]." },
      { q: "Which browsers support subgrid?", a: "Subgrid is Baseline widely available: Firefox 71+, Safari 16+, and Chrome 117+. All modern browsers support both row and column subgrid, so it is safe to use in production without fallbacks for most audiences." },
      { q: "Can I use subgrid for columns too?", a: "Yes: grid-template-columns: subgrid inherits the parent's column tracks. A common pattern is a card grid where the parent defines columns and each card spans rows with subgrid on rows; full two-dimensional subgrid (both axes) works wherever you need nested items to align in both directions." }
    ],
    tags: [
      "css subgrid",
      "subgrid css",
      "css subgrid tutorial",
      "css subgrid example",
      "grid-template-rows subgrid",
      "grid-template-columns subgrid",
      "css subgrid browser support",
      "subgrid caniuse",
      "css subgrid vs nested grid",
      "when to use subgrid",
      "subgrid card layout",
      "align cards css grid",
      "css grid equal height cards",
      "card buttons align css",
      "css subgrid 2026",
      "learn css subgrid",
      "interactive subgrid demo",
      "css subgrid playground",
      "subgrid mdn",
      "css grid subgrid lines",
      "named grid lines subgrid",
      "grid-row span subgrid",
      "subgrid gap",
      "subgrid firefox",
      "subgrid chrome 117",
      "subgrid safari 16",
      "baseline css subgrid",
      "css subgrid production",
      "subgrid fallback",
      "nested grid alignment problem",
      "css grid nested items align",
      "form layout subgrid",
      "subgrid form labels",
      "table layout with css grid subgrid",
      "pricing cards css grid",
      "equal height columns css grid",
      "css grid track sizing subgrid",
      "subgrid auto rows",
      "subgrid fr units",
      "subgrid minmax",
      "css subgrid generator",
      "subgrid code example",
      "css grid advanced techniques",
      "css grid level 2 subgrid",
      "subgrid polyfill",
      "css subgrid tricks",
      "masonry vs subgrid",
      "css grid alignment across cards",
      "subgrid explained simply",
      "css grid subgrid row alignment"
    ],
  };

export default seo;
