import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Custom State - Interactive CSS Lab | IconVault",
    metaDescription: "Learn the :state() pseudo-class with CustomStateSet. Toggle --on, --invalid and --loading on a live custom element. Free, in your browser.",
    about: [ "**IconVault**'s **CSS Custom State** lab teaches the **:state()** pseudo-class with a live custom element you can control. Toggle the **--on**, **--invalid** and **--loading** states to watch a switch restyle itself through **CustomStateSet**, exactly like native **:checked** or **:disabled** work on built-in inputs. The page shows the custom element definition, the **attachInternals()** wiring, and the CSS selectors side by side, so the whole pattern clicks. It is free and runs fully in your browser.",
    "Before custom states, component authors faked element states with classes like **.is-open**, leaking implementation details into HTML and fighting the cascade. With **ElementInternals.states**, a custom element exposes real states that CSS reads with **:state(--name)**, keeping markup clean and selectors semantic. The lab feature-detects **:state()** support, runs the real thing on Chrome 133+ and recent Firefox, and shows an honest class-based simulation on older browsers, plus copyable code for both the element and the stylesheet." ],
    faqs: [
      { q: "What is the CSS :state() pseudo-class?", a: "It matches custom elements that have a given custom state, like my-el:state(--checked). Custom states are set from inside the element with ElementInternals.states, so component authors can expose states the way native elements expose :checked or :open." },
      { q: "What is CustomStateSet?", a: "It is a set-like object on ElementInternals that holds an element's custom states. You add states with internals.states.add('--loading'), remove them with .delete(), and check them with .has(). CSS reads them through :state()." },
      { q: "Do custom elements need attachInternals() for states?", a: "Yes. Call this.attachInternals() in the constructor (the element must be form-associated for the full API, but states work on form-associated custom elements). The returned ElementInternals gives you the states set." },
      { q: "Which browsers support :state()?", a: "CustomStateSet has worked in Chrome since version 90, but the :state() pseudo-class needs Chrome 133+ or a very recent Firefox. Safari support is still missing. This lab detects support and simulates with classes where needed." },
      { q: "Why use :state() instead of classes?", a: "States are encapsulated: they cannot be faked or broken from outside the component, they do not pollute class attributes, and selectors like el:state(--invalid) read like native pseudo-classes. It is the intended styling API for custom elements." },
      { q: "Can :state() be combined with other selectors?", a: "Yes. It behaves like any pseudo-class, so you can write my-el:state(--on):hover .knob or my-el:not(:state(--loading)) and use it in :has() and other functional selectors." },
    ],
    tags: [ "css :state()", "css custom state", ":state() pseudo class", "CustomStateSet", "elementInternals states", "custom element states css", ":state(--on)", "attachInternals states", "css state() example", "css custom state tutorial", "learn css :state()", "css :state() playground", "custom states web components", "styling custom elements states", ":state() browser support", ":state() chrome", "customstateset example", "internals.states.add", "web components custom states", "css :state() mdn", "how to use css :state()", ":state() syntax", "custom element pseudo class", "formAssociated custom element", "elementinternals example", "css :state() vs class", "custom state css 2026", ":state() not working", ":state() firefox", ":state() safari", "css custom state generator", "interactive :state() demo", "custom element toggle state", "css state management components", "shadow dom custom states", ":host :state()", "css :state() fallback", "customstateset has delete", "css custom state code", "web component state styling", "css :state() copy paste", ":state(--invalid)", ":state(--loading)", "custom element validation state", "css :state() reference", "custom states cheat sheet",
      "css :state() custom element", "customstateset tutorial", "css state pseudo-class", ":state() selector example", "web component states css" ],
  };

export default seo;
