import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Matrix Calculator - Interactive CSS Lab | IconVault",
    metaDescription: "Build CSS transform stacks and see the 2D matrix math step by step, with a live preview and copyable matrix(). Free, runs fully in your browser.",
    about: [ "**IconVault**'s **CSS Matrix Calculator** demystifies the math behind every CSS transform. Add **translate**, **rotate**, **scale** and **skew** steps to a stack, edit their values, and watch each step's **3x3 matrix**, the multiplication chain, and the combined result update live. A geometric preview shows your square morphing around its origin, and one click copies the equivalent single **matrix()** function or the original transform stack. It is free and runs fully in your browser.",
    "Every 2D transform is just a 3x3 matrix, and stacking transforms multiplies those matrices left to right, which is why order matters so much in CSS. Seeing the numbers makes concepts like **why rotate then translate differs from translate then rotate** click instantly. The calculator is also genuinely useful: paste a stack from DevTools, simplify it to one **matrix(a, b, c, d, e, f)**, or verify hand-written matrices before shipping them. The math is pure client-side JavaScript, so it works in every browser." ],
    faqs: [
      { q: "What is the CSS matrix() function?", a: "matrix(a, b, c, d, e, f) applies a 2D transformation defined by six numbers: a and d scale x and y, b and c skew, e and f translate. It is the low-level form that every other transform function compiles to." },
      { q: "How do transform stacks combine?", a: "Each transform function becomes a 3x3 matrix, and the stack multiplies them left to right: the combined matrix is M3 x M2 x M1 for transform: t1 t2 t3. This calculator shows every step of that multiplication." },
      { q: "Why does transform order matter?", a: "Because matrix multiplication is not commutative. Rotating then translating moves the element along the rotated axes, while translating then rotating spins the already-moved element around the origin. Try both orders in the preview." },
      { q: "How do I read a 3x3 transform matrix?", a: "In the CSS matrix(a,b,c,d,e,f) form: a is x-scale, d is y-scale, b and c are skew factors, e is x-translation and f is y-translation. The calculator labels the combined values so you can map them back." },
      { q: "When would I use matrix() directly?", a: "When exporting transforms from design tools, when JavaScript computes transforms per frame, or when you want the most compact representation of a complex stack. It is also what getComputedStyle returns." },
      { q: "Does this handle 3D transforms?", a: "This calculator covers 2D transforms, which use 3x3 matrices. 3D transforms use 4x4 matrices and the matrix3d() function with sixteen values." },
    ],
    tags: [ "css matrix calculator", "css transform matrix", "matrix() css", "css matrix function", "transform matrix calculator", "2d matrix calculator", "css transform stack", "matrix multiplication css", "css matrix(a b c d e f)", "css matrix parameters", "understand css matrix", "css transform math", "learn css matrix", "css matrix tutorial", "interactive matrix demo", "css matrix playground", "css matrix visualizer", "transform order css", "css rotate then translate", "matrix multiplication order", "3x3 matrix transform", "css transform origin", "getComputedStyle matrix", "css matrix decomposition", "simplify css transforms", "css transform to matrix", "matrix to transform css", "css skew matrix", "css rotate matrix", "css scale matrix", "css translate matrix", "matrix3d vs matrix", "css 2d transforms", "css transform functions", "css transform cheat sheet", "css transform examples", "css animation matrix", "javascript css matrix", "canvas transform matrix", "svg transform matrix", "linear algebra css", "css matrix copy paste", "css transform generator", "css matrix generator", "webgl matrix css", "css transform reference", "css matrix explained", "css transform lab", "matrix math for developers",
      "css matrix() explained", "transform matrix math" ],
  };

export default seo;
