import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSS Layout API - Interactive CSS Lab | IconVault",
    metaDescription: "Write Houdini registerLayout() worklets in your browser. Masonry and circular layout presets, live reflow, copyable worklet and CSS.",
    about: [
      "**IconVault**'s **CSS Layout API** playground is a hands-on lab for the Houdini **Layout API**: the experimental browser feature that lets you write your own layout algorithms with **registerLayout()** and use them via **display: layout(name)**. Start from a working masonry worklet or a circular layout worklet, edit the code, tweak inputs like **--columns** and **--radius**, add children, and watch the container reflow with your algorithm in charge.",
      "Everything runs fully in your browser and is free to use. The tool registers your worklet through **CSS.layoutWorklet.addModule()** for real, and you can copy the worklet JavaScript plus the CSS that applies it. Honest note: the Layout API is still **experimental** and needs the Experimental Web Platform Features flag in Chrome; the tool says so plainly and the code remains a solid way to learn the API before it ships."
    ],
    faqs: [
      { q: "What is the CSS Layout API?", a: "The CSS Layout API is part of Houdini. It lets you register a custom layout with registerLayout() that receives child boxes, measures them with layoutNextFragment(), positions each fragment, and returns the container size. You then apply it with display: layout(my-layout), and the browser runs your algorithm instead of block, flex or grid." },
      { q: "Which browsers support CSS.layoutWorklet?", a: "Effectively none in stable form. The Layout API is experimental and only available in Chromium behind the Experimental Web Platform Features flag (chrome://flags). Firefox and Safari have not shipped it. This tool detects the worklet object and tells you exactly what to enable." },
      { q: "How does a layout worklet position children?", a: "Inside async layout(children, edges, constraints, styleMap), you call await child.layoutNextFragment() for each child to get a fragment, then set fragment.inlineOffset and fragment.blockOffset to place it. Return { autoBlockSize, childFragments } and the browser paints the fragments where you put them." },
      { q: "What is the difference between the Paint API and the Layout API?", a: "The Paint API draws pixels inside a box (backgrounds, borders, masks). The Layout API decides where boxes go: it measures and positions children like flexbox or grid would. Paint is shipped in Chromium; Layout is still experimental." },
      { q: "Can I build masonry with the Layout API?", a: "Yes, masonry is the canonical example and it is one of this tool's presets. The worklet divides the container into columns, measures each child at the column width, and places each fragment in the currently shortest column." },
      { q: "Will custom layouts ever be production-ready?", a: "The API design is stable but implementation is stalled behind the flag, so do not depend on it in production today. Learning the fragment model now still pays off: the same concepts (inline/block axes, intrinsic sizing, fragmentation) underpin how browsers lay out everything." }
    ],
    tags: [
      "css layout api",
      "houdini layout api",
      "registerlayout",
      "css layout worklet",
      "display layout css",
      "css houdini layout tutorial",
      "custom css layout algorithm",
      "masonry layout worklet",
      "css masonry without javascript library",
      "layoutworklet addmodule",
      "css layout api browser support",
      "css layout api chrome flag",
      "experimental web platform features layout api",
      "registerlayout example",
      "houdini layout worklet example",
      "css custom layout engine",
      "write your own css layout",
      "layoutnextfragment example",
      "css layout api demo",
      "houdini layout api demo",
      "circular layout css",
      "css layout api vs grid",
      "css layout api vs flexbox",
      "what is css houdini layout api",
      "houdini apis explained",
      "css layout worklet not working",
      "css.layoutworklet undefined",
      "layout worklet typescript",
      "registerlayout typescript",
      "intrinsicSizes layout worklet",
      "child layoutnextfragment",
      "css layout api 2026",
      "learn css layout api",
      "interactive css layout playground",
      "css layout worklet builder",
      "masonry css native 2026",
      "native css masonry",
      "css grid masonry",
      "pinterest layout css worklet",
      "custom layout css houdini",
      "display layout my layout",
      "css layout api playground",
      "houdini registerlayout tutorial",
      "layout worklet input properties",
      "stylemap layout worklet",
      "css fragmentation layout api",
      "autoBlockSize layout worklet",
      "css layout worklet generator",
      "experimental css layout features",
      "future of css layout"
    ],
  };

export default seo;
