import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "CSV Viewer - Free Online Data Tool | IconVault",
    metaDescription: "View CSV data as an interactive table: paste or upload, sort columns, search filter, auto delimiter detection, export to JSON. Free, runs in your browser.",
    about: [ "**IconVault**'s **CSV Viewer** turns raw **CSV data** into an interactive **table** you can actually explore. Paste CSV text or upload a file, and the tool parses it with proper handling of quoted fields, then lets you **sort any column**, apply a **search filter**, and switch between auto-detected or manual **delimiters** (comma, semicolon, tab, pipe). A built-in sample dataset shows how it works in one click.",
    "Everything runs **100% in your browser**: your data is never uploaded to any server, so it is safe for sensitive spreadsheets. Export the parsed rows to **JSON** with one click, copy values, and clear the workspace instantly. It is free to use, with no account and no file size drama for typical CSV work." ],
    faqs: [
      { q: "What does the CSV Viewer do?", a: "It parses CSV text or files into an interactive table with sortable columns, a search filter, delimiter options and JSON export. It correctly handles quoted fields that contain commas." },
      { q: "Is my data uploaded anywhere?", a: "No. Parsing happens entirely in your browser, so your CSV never leaves your device. It is safe for private or sensitive data." },
      { q: "Which delimiters are supported?", a: "Auto-detect plus comma, semicolon, tab and pipe. Auto-detect inspects your data and picks the most likely delimiter, and you can override it manually." },
      { q: "Can I convert CSV to JSON?", a: "Yes. Once parsed, you can export the table as JSON, which is handy for APIs, config files and JavaScript apps." },
      { q: "Does it handle quoted fields and line breaks?", a: "Yes. The parser understands RFC-style quoting, so fields like \"Cambridge, UK\" with embedded commas or escaped quotes parse correctly." },
      { q: "Is it free?", a: "Yes, it is completely free with no account needed." }
    ],
    tags: [
      "csv viewer",
      "csv viewer online",
      "view csv online",
      "csv table viewer",
      "csv to table",
      "csv file viewer",
      "open csv online",
      "csv parser online",
      "csv reader",
      "online csv reader",
      "csv to json",
      "csv to json converter",
      "convert csv to json online",
      "csv json converter free",
      "csv editor online",
      "csv sort online",
      "sort csv by column",
      "csv search filter",
      "csv delimiter detector",
      "csv semicolon to comma",
      "tab separated viewer",
      "pipe delimited viewer",
      "tsv viewer",
      "view tsv online",
      "csv data explorer",
      "csv pretty print",
      "csv formatter online",
      "format csv online",
      "csv preview tool",
      "paste csv view table",
      "csv without excel",
      "open csv without excel",
      "csv in browser",
      "csv analyzer",
      "csv column sorter",
      "csv filter rows",
      "csv search online",
      "csv to html table",
      "csv table generator",
      "csv data cleaning tool",
      "inspect csv file",
      "csv validator online",
      "check csv format",
      "csv quoted fields",
      "csv with commas in fields",
      "large csv viewer",
      "csv download as json",
      "csv export json",
      "free csv tools",
      "spreadsheet viewer online",
      "data table viewer"
    ],
  };

export default seo;
