import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "cURL Builder - Free Online Developer Tool | IconVault",
    metaDescription: "Build shell-safe cURL commands from a form: method, headers, query params, JSON body, auth. Or paste a cURL command to edit it. Free, in-browser.",
    about: [ "**IconVault**'s **cURL Builder** creates correct, **shell-safe cURL commands** from simple form fields. Pick the **HTTP method** (GET, POST, PUT, PATCH, DELETE and more), add **headers**, **query parameters** and a request **body** (JSON, form-encoded or plain text), set **Basic or Bearer auth**, and the tool assembles a properly quoted command with safe escaping of single quotes. You can also **paste an existing cURL command** back in to edit and rebuild it.",
    "Everything runs **100% in your browser**: no request is ever sent and nothing is uploaded, so API keys and tokens stay on your machine. Copy the finished command, download it as a shell snippet, and use it for testing **REST APIs**, debugging webhooks or documenting endpoints. It is free to use with no account." ],
    faqs: [
      { q: "What does the cURL Builder do?", a: "It builds a cURL command from form fields: URL, HTTP method, headers, query params, body and auth. It handles shell quoting safely so the command runs as intended. You can also paste a cURL command in to edit it." },
      { q: "Does it send the HTTP request?", a: "No. It only generates the command text. Nothing is sent to any server, which keeps your tokens and test data private." },
      { q: "How does it handle special characters in values?", a: "Values are wrapped in single quotes with embedded quotes escaped the shell-safe way, so spaces, ampersands and quotes in your data do not break the command." },
      { q: "Can it parse an existing cURL command?", a: "Yes. Paste a cURL command into the tool to load it back into the form fields, edit the values, and rebuild a clean command." },
      { q: "Which auth methods are supported?", a: "Basic auth (username and password) and Bearer token auth. You can also add custom Authorization headers manually." },
      { q: "Is it free?", a: "Yes, it is free with no account required, and everything runs locally in your browser." }
    ],
    tags: [
      "curl builder",
      "curl command builder",
      "curl generator",
      "online curl builder",
      "curl command generator",
      "build curl command online",
      "curl request builder",
      "curl online tool",
      "generate curl command",
      "curl post request generator",
      "curl get request",
      "curl with headers",
      "curl with json body",
      "curl bearer token",
      "curl basic auth",
      "curl query params",
      "curl form data",
      "curl command syntax",
      "curl examples",
      "curl cheat sheet",
      "how to use curl",
      "curl for beginners",
      "curl rest api testing",
      "test api with curl",
      "curl post json",
      "curl put request example",
      "curl patch request example",
      "curl delete request",
      "curl authorization header",
      "curl content type json",
      "curl escape quotes",
      "curl shell escaping",
      "curl command parser",
      "parse curl command",
      "curl to form",
      "edit curl command online",
      "curl command formatter",
      "pretty print curl",
      "curl windows command",
      "curl mac terminal",
      "curl linux command",
      "api testing tool online",
      "http request builder",
      "rest client online",
      "curl vs postman",
      "curl alternative online",
      "curl debug api",
      "webhook test curl",
      "curl download file command",
      "free curl tool"
    ],
  };

export default seo;
