import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "DateTime Calculator - Free Online Calculator | IconVault",
    metaDescription: "Date math made easy: add or subtract days, find the difference between dates, get ISO week numbers and day of year. Free, runs in your browser.",
    about: [ "**IconVault**'s **DateTime Calculator** handles everyday **date math** without a spreadsheet. **Add or subtract** days, weeks, months or years from any date to find deadlines and anniversaries, compute the exact **difference between two dates** in days, get the **ISO week number** and **day of year** for any date, and see the resulting weekday spelled out clearly.",
    "Everything runs **100% in your browser**: no sign-up, nothing uploaded, free to use. Project managers can count working days to a launch, travelers can measure trip lengths, and developers can verify **ISO 8601 week numbers** for reports and scheduling. Results are shown instantly as you change the inputs." ],
    faqs: [
      { q: "What does the DateTime Calculator do?", a: "It does date arithmetic: add or subtract time from a date, find the difference between two dates, and look up ISO week numbers and day-of-year values." },
      { q: "How do I add 90 days to a date?", a: "Use the add/subtract tab, pick your start date, enter 90 days, and the tool returns the resulting date with its weekday." },
      { q: "How do I find days between two dates?", a: "Use the difference tab, enter both dates, and the tool shows the exact number of days between them." },
      { q: "What is an ISO week number?", a: "ISO 8601 defines weeks starting Monday, with week 1 containing the first Thursday of the year. The tool computes the correct ISO week number (1-53) for any date." },
      { q: "What is day of year?", a: "It is the ordinal day number, where January 1 is day 1 and December 31 is day 365 (or 366 in a leap year). Useful for scheduling and data analysis." },
      { q: "Is it free?", a: "Yes, it is free with no account required, and everything runs locally in your browser." }
    ],
    tags: [
      "date calculator",
      "datetime calculator",
      "date calculator online",
      "add days to date",
      "subtract days from date",
      "add days to date calculator",
      "date difference calculator",
      "days between two dates",
      "calculate days between dates",
      "how many days between dates",
      "date duration calculator",
      "count days between dates",
      "iso week number",
      "iso week calculator",
      "what week is it",
      "current week number",
      "week number calculator",
      "iso 8601 week",
      "day of year calculator",
      "what day of the year is it",
      "ordinal date calculator",
      "julian date calculator",
      "date math calculator",
      "date arithmetic",
      "deadline calculator",
      "project deadline date calculator",
      "add business days calculator",
      "add months to date",
      "add years to date",
      "90 days from today",
      "30 days from today",
      "60 days from today",
      "100 days from today",
      "days until calculator",
      "days since calculator",
      "how many days until",
      "trip length calculator",
      "pregnancy due date calculator",
      "anniversary calculator",
      "age in days calculator",
      "what day of the week was",
      "weekday calculator",
      "date to weekday",
      "leap year checker",
      "is it a leap year",
      "calendar calculator online",
      "free date calculator",
      "time calculator date",
      "schedule date calculator",
      "date calculator add subtract"
    ],
  };

export default seo;
