import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JS Decorators - Interactive Lab | IconVault",
    metaDescription: "Learn JavaScript decorators with runnable patterns: log, memoize, debounce, validate, deprecated and class decorators. Free, runs in your browser.",
    about: [ "**IconVault**'s **JS Decorators** lab teaches the **decorator pattern** with real, runnable code. Each pattern, from **@log** and **@measure** to **@memoize**, **@debounce**, **@validate**, **@deprecated** and class-level **@register**, comes with copyable source and a Run button that executes it live and prints the output to an on-page console. It is free and runs fully in your browser.", "Decorators are functions that wrap classes, methods or fields to add behavior without changing their bodies, which makes them perfect for **cross-cutting concerns** like logging, caching, timing and validation. The demos apply decorators by hand (the exact functions the **@ syntax** calls), so everything runs with zero build config; in TypeScript you only need **experimentalDecorators** to use the @ form directly." ],
    faqs: [
      { q: "What is a decorator in JavaScript?", a: "A decorator is a function that receives a class, method or field definition and can wrap or replace it. Method decorators get the prototype, the method name and the property descriptor, so they can intercept calls to add logging, caching or validation." },
      { q: "What is the difference between legacy and standard decorators?", a: "Legacy (TypeScript experimental) decorators use the (target, key, descriptor) signature shown in this lab. The new TC39 standard proposal changes the API. The patterns here teach the widely-used legacy form that works in TypeScript and Babel today." },
      { q: "How do I enable decorators in TypeScript?", a: "Set experimentalDecorators: true in tsconfig.json. That unlocks the @ syntax; the decorator functions themselves are plain JavaScript you write yourself, exactly as demonstrated in each pattern." },
      { q: "What are decorators used for in real projects?", a: "Logging method calls, measuring performance, memoizing expensive computations, debouncing UI handlers, validating arguments, marking deprecated APIs, dependency injection (Angular, NestJS), and ORM model definitions (TypeORM, MobX)." },
      { q: "Can decorators be applied to class fields?", a: "In the legacy model, field decorators are applied via defineProperty-style helpers; in the new standard proposal, field decorators receive an initializer. This lab focuses on method and class decorators, which cover the most common real-world patterns." },
      { q: "Is this tool free?", a: "Yes. JS Decorators is completely free, runs fully in your browser, and every pattern is copyable." },
    ],
    tags: [ "javascript decorators", "js decorators", "typescript decorators", "decorator pattern javascript", "what are decorators in js", "js decorator tutorial", "typescript decorator example", "method decorator javascript", "class decorator javascript", "experimentaldecorators", "enable decorators typescript", "tsconfig experimentaldecorators", "decorator factory typescript", "parameterized decorator js", "@log decorator", "method logging decorator", "@memoize decorator", "memoize decorator javascript", "@debounce decorator", "debounce decorator js", "@validate decorator", "validation decorator typescript", "@deprecated decorator", "deprecated decorator js", "measure performance decorator", "timing decorator javascript", "propertydescriptor decorator", "how decorators work javascript", "are decorators functions", "apply decorator manually js", "decorator without typescript", "babel decorators", "legacy decorators vs standard decorators", "tc39 decorators proposal", "angular decorators explained", "nestjs decorators", "mobx decorator", "typeorm decorators", "decorator metadata", "reflect metadata decorator", "decorator composition", "multiple decorators order", "decorator evaluation order", "method decorator descriptor.value", "wrap method with decorator", "decorator design pattern", "decorator pattern example", "decorators vs higher order functions", "decorators vs middleware", "cross cutting concerns javascript", "aop javascript decorators", "javascript decorator playground", "interactive decorators lab", "learn js decorators", "decorator patterns cheat sheet", "typescript decorator patterns", "custom decorator typescript example" ],
  };

export default seo;
