import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Dependabot Config Generator - Free Online Dev Tool | IconVault",
    metaDescription: "Generate a dependabot.yml visually: pick from 14 ecosystems, set directories, schedule, target branch, reviewers and labels. Copy or download. Free.",
    about: [ "**IconVault**'s **Dependabot Config Generator** builds a correct **dependabot.yml** for **GitHub Dependabot** without memorizing YAML syntax. Choose from **14 package ecosystems** (npm, pip, bundler, cargo, composer, docker, github-actions, gomod, gradle, maven, nuget, terraform, hex, elm), set the **directory**, **schedule** (daily, weekly, monthly), **target branch**, **reviewers**, **assignees** and **labels**, and watch the **live YAML** update as you configure it.",
    "Everything runs **100% in your browser**: no sign-up, nothing uploaded, free to use. **Copy** the finished config or **download** it as dependabot.yml and drop it into .github/ to start getting automated **dependency update pull requests**. It is the fastest way to enable Dependabot correctly across single-repo and multi-directory projects." ],
    faqs: [
      { q: "What does the Dependabot Config Generator do?", a: "It builds a dependabot.yml file through a visual form: you pick ecosystems and directories, set the update schedule, target branch, reviewers and labels, and get valid YAML to copy or download." },
      { q: "Which ecosystems are supported?", a: "npm, pip, bundler, cargo, composer, docker, github-actions, gomod, gradle, maven, nuget, terraform, hex and elm, all 14 ecosystems Dependabot supports." },
      { q: "Where do I put the dependabot.yml file?", a: "In the .github directory of your repository. Dependabot reads it from there and starts opening dependency update pull requests on your schedule." },
      { q: "How often can Dependabot check for updates?", a: "Daily, weekly or monthly. Weekly on a chosen weekday is the most common choice, and the tool lets you pick the day." },
      { q: "Can I configure multiple directories?", a: "Yes. Add one update entry per ecosystem and directory combination, for example npm in /frontend and pip in /backend." },
      { q: "Is it free?", a: "Yes, it is free with no account required, and everything runs locally in your browser." }
    ],
    tags: [
      "dependabot generator",
      "dependabot config generator",
      "dependabot.yml generator",
      "dependabot yml builder",
      "generate dependabot.yml",
      "dependabot config online",
      "dependabot configuration tool",
      "github dependabot setup",
      "how to set up dependabot",
      "dependabot tutorial",
      "dependabot example config",
      "dependabot.yml example",
      "dependabot schedule weekly",
      "dependabot daily vs weekly",
      "dependabot target branch",
      "dependabot reviewers",
      "dependabot labels",
      "dependabot assignees",
      "dependabot npm config",
      "dependabot pip config",
      "dependabot docker config",
      "dependabot github actions",
      "dependabot multiple directories",
      "dependabot monorepo",
      "dependabot ecosystems list",
      "what is dependabot",
      "dependabot vs renovate",
      "automated dependency updates",
      "dependency update bot github",
      "github security updates",
      "dependabot alerts",
      "dependabot pull requests",
      "dependabot version updates",
      "dependabot ignore dependencies",
      "dependabot open pull requests limit",
      "dependabot rebase strategy",
      "dependabot commit message",
      "dependabot timezone schedule",
      "dependabot cron schedule",
      "github actions dependency bot",
      "keep dependencies updated github",
      "npm auto update dependencies",
      "pip auto update dependencies",
      "docker base image updates",
      "terraform provider updates dependabot",
      "composer dependabot",
      "cargo dependabot",
      "free dependabot tool",
      "devops config generator",
      "dependabot yml validator"
    ],
  };

export default seo;
