import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Device Sensors - Interactive Lab | IconVault",
    metaDescription: "Connect to real device orientation and motion sensors: live 3D cube, alpha beta gamma readouts, iOS permission flow. Free, in your browser.",
    about: [ "**IconVault**'s **Device Sensors** playground listens to the real `DeviceOrientationEvent` and `DeviceMotionEvent` streams: a 3D cube rotates as you tilt your phone, with live alpha, beta and gamma readouts, accelerometer and gyroscope values, and the iOS permission flow handled the way production apps must handle it. It is free and runs fully in your browser.", "You will learn the **Euler angle conventions** (which axis is which, and where gimbal lock bites), why iOS 13 and later needs an **explicit permission tap** from a user gesture, how a **low-pass filter** smooths jittery sensor data, and why desktops honestly show no data: without motion hardware there is nothing to read, and this tool says so instead of faking numbers." ],
    faqs: [ { q: "What do alpha, beta and gamma mean?", a: "They are the device orientation Euler angles in degrees: alpha is rotation around the z axis (compass direction), beta is front-to-back tilt around x, and gamma is left-to-right tilt around y." }, { q: "Why is there no data on my desktop?", a: "Most desktops and laptops have no motion sensors, so the browser fires no events. That is the honest result; open the page on a phone to see live data." }, { q: "Why does iOS ask for permission?", a: "Since iOS 13, DeviceOrientationEvent.requestPermission() must be called from a user gesture before any motion events fire. This tool performs that exact flow." }, { q: "What is the smoothing slider doing?", a: "It applies a low-pass filter to each angle: new values blend toward old ones. Lower values are smoother but laggier; higher values are snappier but jittery." }, { q: "What is gimbal lock in this demo?", a: "Near beta of plus or minus 90 degrees, alpha and gamma become ambiguous and the cube can spin oddly. Production 3D apps avoid this with quaternions instead of Euler angles." }, { q: "What is the difference between acceleration and accelerationIncludingGravity?", a: "acceleration excludes gravity and reads near zero when the device is still; accelerationIncludingGravity includes the roughly 9.8 m/s^2 pull of gravity, so it reads about 9.8 on the downward axis at rest." } ],
    tags: [ "deviceorientationevent", "devicemotionevent", "device orientation javascript", "device motion api", "alpha beta gamma javascript", "mobile sensor web api", "deviceorientation example", "devicemotion example", "requestpermission deviceorientation", "ios motion permission", "gyroscope javascript", "accelerometer javascript", "web motion sensors", "deviceorientation ios 13", "how to access gyroscope in browser", "javascript tilt phone", "device orientation 3d cube", "euler angles device", "gimbal lock explained", "low pass filter sensor", "smooth sensor data javascript", "accelerationincludinggravity", "rotationrate javascript", "absolute deviceorientation", "caniuse deviceorientation", "deviceorientation deprecated", "device motion https", "phone tilt web page", "compass javascript browser", "web api motion sensor", "devicemotion interval", "sensor fusion web", "mdn deviceorientationevent", "test device orientation online", "device sensors playground", "orientation sensor demo", "motion sensor demo browser", "javascript read accelerometer", "mobile web sensors", "pwa sensors", "deviceorientation not firing", "deviceorientationevent typescript", "webkitcompassheading", "absolute orientation", "screen orientation vs device orientation", "handle device motion", "sensor permissions web", "calibrate gyroscope web", "zero orientation offset", "web sensor api", "device motion listener", "phone gyroscope test" ],
  };

export default seo;
