import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Device Info - Free Online Browser Tool | IconVault",
    metaDescription: "See your device and browser details instantly: screen size, viewport, browser version, OS, CPU cores, timezone and more, shown as cards and JSON. Free.",
    about: [ "**IconVault**'s **Device Info** tool takes a complete snapshot of **your device and browser** in one click. It reports **screen resolution**, **viewport size**, **device pixel ratio**, **browser name and version**, **operating system**, **CPU cores**, approximate **device memory**, **touch support**, **network type**, **timezone** and **language**, shown as readable cards plus a copy-ready **JSON** dump.",
    "Everything runs **100% in your browser**: the information is read from standard web APIs on your own device and nothing is uploaded anywhere. It is free to use and handy for **debugging responsive layouts**, filing bug reports, checking what browser a visitor uses, or verifying **device capabilities** before building a feature." ],
    faqs: [
      { q: "What does the Device Info tool do?", a: "It reads your browser's standard APIs and displays your screen resolution, viewport, browser version, OS, CPU cores, memory, touch support, timezone and more, both as cards and as JSON." },
      { q: "Is my data sent to a server?", a: "No. Everything is collected locally in your browser using built-in web APIs. Nothing is uploaded, stored or shared." },
      { q: "What is device pixel ratio?", a: "It is the ratio between physical screen pixels and CSS pixels. A ratio of 2 means the screen packs twice as many physical pixels per CSS pixel, which is why images need higher resolution on retina displays." },
      { q: "Why does memory say approximate or not available?", a: "Browsers only expose an approximate device memory figure, and some browsers do not expose it at all for privacy. The tool shows what the browser makes available." },
      { q: "Can I copy the results?", a: "Yes. The full snapshot is available as JSON that you can copy and paste into bug reports, support tickets or documentation." },
      { q: "Is it free?", a: "Yes, it is free with no account required." }
    ],
    tags: [
      "device info",
      "device info online",
      "what is my device",
      "browser info",
      "check my browser",
      "what browser am i using",
      "browser version checker",
      "my screen resolution",
      "what is my screen resolution",
      "screen size checker",
      "viewport size",
      "what is my viewport",
      "device pixel ratio",
      "check device pixel ratio",
      "my operating system",
      "what os am i using",
      "my ip and device info",
      "system info online",
      "computer specs checker",
      "phone specs checker",
      "how many cpu cores do i have",
      "check cpu cores browser",
      "device memory checker",
      "how much ram does my phone have",
      "touch screen test",
      "is my screen touch",
      "network information api",
      "check connection type",
      "what is my timezone",
      "browser timezone checker",
      "browser language checker",
      "user agent checker",
      "what is my user agent",
      "user agent parser",
      "device fingerprint",
      "browser fingerprint check",
      "responsive design tester",
      "debug responsive layout",
      "web developer device info",
      "bug report system info",
      "support ticket device details",
      "json device info",
      "export device info json",
      "free device info tool",
      "online system information",
      "my device specs",
      "check mobile device info",
      "tablet info checker",
      "laptop specs online",
      "what device am i on"
    ],
  };

export default seo;
