import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Dev.to Stats - Free Online dev.to Author Dashboard | IconVault",
    metaDescription: "Article performance dashboard for dev.to authors: views, reactions, comments, top tags and posting patterns. Free, in your browser.",
    about: [
      "**IconVault**'s **Dev.to Stats** builds an **article performance dashboard** for any **dev.to author**. Enter a username and the tool pulls up to **1,000 public articles** through the **dev.to API**, then totals **page views, reactions and comments**, ranks your **top tags** by views, and charts your **posting pattern** month by month so you can see what topics and cadences actually land.",
      "Everything is fetched and computed **fully in your browser** from dev.to's public API: no login, no API key, no signup. It is **free** to use. The honest caveat: view counts are what dev.to reports publicly and can lag behind the dashboard in your own author panel. Drafts and unlisted posts are never included."
    ],
    faqs: [
      { q: "What data does the dashboard show?", a: "Total page views, reactions and comments across all public articles, a per-article table with views and engagement, top tags ranked by total views and a monthly posting pattern chart." },
      { q: "How many articles are analyzed?", a: "Up to 1,000 public articles, fetched 100 per page from the dev.to API. Authors with fewer articles simply get all of them." },
      { q: "Why do the numbers differ from my dev.to dashboard?", a: "The public API reports the same underlying counts, but your private author dashboard may update faster or include extra metrics like follows. Small timing differences are normal." },
      { q: "What if the user is not found?", a: "You will see a not-found error. Usernames are lowercased before lookup, so check the exact spelling on dev.to." },
      { q: "Are drafts included?", a: "No. Only published public articles are visible through the dev.to API, so drafts and unlisted posts never appear." },
      { q: "Is it really free?", a: "Yes. Unlimited author lookups, no account, no signup. The dev.to API is public and free." }
    ],
    tags: [
      "dev.to stats",
      "devto stats",
      "dev.to analytics",
      "dev.to author dashboard",
      "dev.to article stats",
      "dev.to views checker",
      "dev.to profile stats",
      "dev.to author analytics",
      "dev.to dashboard",
      "dev.to insights",
      "dev.to performance",
      "dev.to article performance",
      "dev.to views counter",
      "dev.to reactions",
      "dev.to comments stats",
      "dev.to top tags",
      "dev.to tag analytics",
      "dev.to posting frequency",
      "dev.to author profile",
      "dev.to username lookup",
      "dev.to profile checker",
      "dev.to article views",
      "dev.to total views",
      "dev.to most viewed articles",
      "dev.to popular posts",
      "dev.to content analytics",
      "dev.to blogging stats",
      "dev.to writer dashboard",
      "dev.to author tools",
      "dev.to api stats",
      "dev.to stats viewer",
      "dev.to profile analyzer",
      "dev.to author report",
      "dev.to growth tracker",
      "dev.to audience stats",
      "dev.to engagement stats",
      "dev.to reading time",
      "dev.to monthly posts",
      "dev.to posting patterns",
      "dev.to content strategy",
      "dev.to analytics free",
      "dev.to stats free",
      "dev.to stats online",
      "check dev.to stats",
      "dev.to author search",
      "dev.to profile lookup",
      "dev.to article list",
      "dev.to all articles",
      "dev.to archive stats",
      "dev.to engagement tracker"
    ],
  };

export default seo;
