import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Document PiP - Interactive Lab | IconVault",
    metaDescription: "Open a real Document Picture-in-Picture window with live HTML: stopwatch, mirrored note, themes. Free, runs fully in your browser.",
    about: [ "**IconVault**'s **Document PiP** playground calls the real `documentPictureInPicture.requestWindow()` API: a floating always-on-top window opens with live HTML inside it, a running stopwatch, and a note that mirrors every keystroke you type on the main page. You control the window size and theme, and everything is built with the actual PiP document object. It is free and runs fully in your browser.", "You will learn how **document PiP** differs from **video PiP** (full interactive HTML instead of one video element), how to inject styles into the PiP document, how to keep it updated from timers and events, and how **`pagehide`** tells you when the user closes it. Where the API is missing (Firefox, Safari), the tool says so plainly instead of faking a window." ],
    faqs: [ { q: "What is Document Picture-in-Picture?", a: "It is a Chrome and Edge API that opens an always-on-top window containing a full HTML document you control, unlike classic video PiP which only shows a video element." }, { q: "How do I put content in the PiP window?", a: "requestWindow() resolves with a Window object; you append elements and styles to pipWindow.document exactly like a normal document. This lab builds a stopwatch and note that way." }, { q: "Can the PiP window be interactive?", a: "Yes. It supports forms, buttons, timers and script-driven updates, and it keeps running while the main tab is in the background." }, { q: "How do I know when the user closes it?", a: "Listen for pagehide on the PiP window object, as this lab does, and clean up your timers and references there." }, { q: "Which browsers support Document PiP?", a: "Chrome and Edge 116 and later on desktop. Firefox and Safari do not implement it yet." }, { q: "What does navigationUI do here?", a: "That option belongs to the Fullscreen API, not PiP. PiP windows are controlled through the width and height options passed to requestWindow()." } ],
    tags: [ "document picture in picture", "documentpictureinpicture", "document pip api", "requestwindow", "picture in picture html", "pip window javascript", "document pip example", "document pip chrome", "pip custom html", "floating window web api", "always on top window browser", "video pip vs document pip", "documentpictureinpicture tutorial", "how to use document pip", "pip stopwatch", "mini player web", "pip note app", "document pip browser support", "caniuse document picture in picture", "document pip firefox", "document pip safari", "pagehide pip window", "pip window styles", "pip window close event", "multiple pip windows", "document pip react", "document pip typescript", "mdn document picture in picture", "test document pip online", "document pip demo", "pip api javascript", "custom pip player", "floating video player web", "pip controls custom", "document pip width height", "requestwindow options", "pip window document", "is documentpictureinpicture supported", "document pip 2024", "picture in picture web app", "pip productivity", "floating widget browser", "document pip use cases", "pip api example code", "open pip window javascript", "close pip window", "pip window events", "document pip security", "pip window focus", "floating pip window", "document pip example code" ],
  };

export default seo;
