import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Drag & Drop - Interactive Lab | IconVault",
    metaDescription: "Master HTML5 drag and drop: sortable list, file drop with previews, effectAllowed and a live DataTransfer inspector. Free, in your browser.",
    about: [ "**IconVault**'s **Drag & Drop** playground is a hands-on lab for the real HTML5 drag and drop API: reorder a sortable list, drop files to inspect their payload with live previews, switch `effectAllowed` to see the forbidden cursor in action, and watch every drag event land in a DataTransfer inspector with its live types, dropEffect and file list. It is free and runs fully in your browser.", "You will learn the **event sequence** (dragstart, dragover, drop, dragend), why dragover must call preventDefault to allow a drop, how **setData** moves custom payloads between dragstart and drop, and what the **types array** actually contains during file drags versus element drags. Dropped files never leave your device: only names, sizes and local previews are shown." ],
    faqs: [ { q: "Why must dragover call preventDefault?", a: "By default the browser forbids dropping. Calling preventDefault on dragover (and usually dragenter) signals that the element is a valid drop target, which is the single most common drag and drop bug." }, { q: "What is effectAllowed versus dropEffect?", a: "effectAllowed is set by the drag source and declares which operations are legal (copy, move, link, none); dropEffect is the operation the current target will perform and follows the cursor and modifier keys." }, { q: "How do I pass data from dragstart to drop?", a: "With dataTransfer.setData(format, value) on dragstart and getData(format) on drop. This lab sets both text/plain and a custom application/x-dnd-index type." }, { q: "Why does types only show Files during file drags?", a: "For security, the browser hides file contents and custom data until drop; only the Files type token is visible during the drag. The inspector here shows this live." }, { q: "How do dropped files stay private?", a: "File objects from dataTransfer.files are local references; this tool only reads name, size, type and creates an object URL preview. Nothing is uploaded." }, { q: "Can I drag files and list items at the same time?", a: "The lab has two zones so you can compare: the list uses element dragging with custom data, the zone uses file dragging. The inspector logs both side by side." } ],
    tags: [ "html5 drag and drop", "drag and drop javascript", "datatransfer", "dragstart dragover drop", "html drag drop tutorial", "javascript drag drop list", "sortable list javascript", "drag and drop file upload", "datatransfer.files", "effectallowed", "dropeffect", "setdata getdata", "drag drop event order", "preventdefault dragover", "html5 dnd example", "draggable attribute", "drag and drop inspector", "datatransfer types", "drag drop custom data", "file drop zone javascript", "drag drop preview image", "html drag drop not working", "drop event not firing", "dragover preventdefault why", "dragend event", "dragenter vs dragover", "drag drop touch devices", "mobile drag and drop alternative", "pointer events drag", "native drag and drop vs library", "react drag and drop", "vue drag drop", "datatransfer setdragimage", "custom drag image", "drag drop accessibility", "keyboard reorder list", "mdn drag and drop", "test drag drop online", "drag drop playground", "learn drag and drop api", "file api drag drop", "object url preview", "drop multiple files", "drag drop effect none", "copy vs move drag", "drag data formats", "application/x custom type", "drag drop security", "cross window drag drop", "drag files into browser", "dnd api browser support" ],
  };

export default seo;
