import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "EditContext - Interactive Lab | IconVault",
    metaDescription: "Build a real custom text editor on the EditContext API: IME composition events, bounds updates, caret model. Free, in your browser.",
    about: [ "**IconVault**'s **EditContext** playground wires a working custom text editor to the real `EditContext` API: type with your physical keyboard, open an IME or the emoji picker to fire genuine composition events, and watch every textupdate, characterboundsupdate and composition event land in the log with its exact payload. It is free and runs fully in your browser.", "You will learn the core idea (the browser routes text input to your model instead of mutating your DOM), the **event protocol** for applying remote edits, why **character bounds** matter for IME candidate windows, and the keyboard handling a real canvas editor still owns itself. Where **EditContext** is missing, the tool says so instead of pretending." ],
    faqs: [ { q: "What is the EditContext API?", a: "It is the browser API that lets custom text editors (canvas, WebGL, design tools) receive text input, IME composition and autocorrect without a hidden textarea: you own the text model and the browser sends textupdate events." }, { q: "How do I attach an EditContext?", a: "Create one with new EditContext({ text, selectionStart, selectionEnd }) and assign it to element.editContext. This lab does exactly that on its editor div." }, { q: "What is a textupdate event?", a: "It carries updateRangeStart, updateRangeEnd and the replacement text from the IME or virtual keyboard; your job is to apply that edit to your model, as the lab does." }, { q: "What are character bounds for?", a: "The IME asks where characters are on screen so it can position its candidate window; you answer with updateCharacterBounds(). The lab answers with the live caret rect." }, { q: "Does EditContext handle my physical keyboard?", a: "No. Physical key presses still arrive as keydown events that you handle yourself; EditContext covers IME, virtual keyboards, autocorrect and dictation." }, { q: "Which browsers support EditContext?", a: "Chrome and Edge 121 and later. Firefox and Safari do not implement it yet." } ],
    tags: [ "editcontext", "editcontext api", "edit context javascript", "custom text editor web", "ime web api", "composition events", "textupdate event", "characterboundsupdate", "virtual keyboard web", "canvas text editor", "hidden textarea alternative", "editcontext example", "editcontext tutorial", "editcontext browser support", "caniuse editcontext", "editcontext chrome 121", "ime composition javascript", "compositionstart compositionend", "input method editor web", "emoji picker web app", "updatecharacterbounds", "updatetext editcontext", "updateselection", "control bounds ime", "selection bounds", "custom editor ime support", "code editor web", "canvas editor text input", "mobile keyboard custom editor", "autocorrect web", "dictation web api", "textformatupdate", "editcontext react", "editcontext typescript", "mdn editcontext", "test editcontext online", "editcontext demo", "chromium editcontext", "editcontext spec", "rich text custom editor", "slate editor ime", "prosemirror ime", "monaco editcontext", "vscode editcontext", "editcontext vs contenteditable", "contenteditable problems", "editcontext performance", "ime candidate window position", "editcontext android", "editcontext ios" ],
  };

export default seo;
