import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Encoding API - Interactive Lab | IconVault",
    metaDescription: "Explore TextEncoder and TextDecoder with UTF-8 byte visualization, multi-encoding decode and streaming demos. Free, runs in your browser.",
    about: [ "**IconVault**'s **Encoding API** playground makes **TextEncoder** and **TextDecoder** visible. Type any text and see its exact **UTF-8 bytes** as a color-coded hex grid, inspect the per-character breakdown of **code points** and byte sequences, then decode hex back to text with any encoding label from **utf-8** and **utf-16** to **windows-1252** and **shift_jis**. It is free and runs fully in your browser.", "The streaming demo shows why **{ stream: true }** matters: split bytes into tiny chunks and watch a naive decode produce replacement characters while the streaming decoder buffers partial **multibyte sequences** correctly. Every concept ships with copyable code, so you can paste the pattern straight into your fetch handlers, WebSocket code or file parsers." ],
    faqs: [
      { q: "What does TextEncoder do in JavaScript?", a: "TextEncoder converts a string into UTF-8 bytes as a Uint8Array. It always encodes UTF-8; there is no option for other encodings on the encode side. Use it before sending text over WebSockets, fetch bodies or binary protocols." },
      { q: "How do I decode bytes to a string in JavaScript?", a: "Use new TextDecoder(label).decode(bytes), where label can be utf-8, utf-16le, windows-1252 and over a hundred other WHATWG encoding labels. Pass { fatal: true } to throw on invalid bytes instead of inserting replacement characters." },
      { q: "What is streaming decode and why does it matter?", a: "When bytes arrive in chunks (network streams, file reads), a multibyte UTF-8 character can be split across chunks. Decoding each chunk alone corrupts it; new TextDecoder('utf-8', { stream: true }) buffers incomplete sequences until the rest arrives." },
      { q: "How many bytes is a character in UTF-8?", a: "ASCII characters take 1 byte, most Latin and common symbols take 2, CJK characters take 3, and emoji take 4. The byte grid in this lab colors lead and continuation bytes so you can see the structure." },
      { q: "What is the difference between encode() and encodeInto()?", a: "encode() allocates and returns a new Uint8Array. encodeInto(string, uint8Array) writes into an existing buffer and reports how many code units and bytes were written, which avoids allocation in hot loops." },
      { q: "Is this tool free?", a: "Yes. The Encoding API playground is completely free and runs fully in your browser." },
    ],
    tags: [ "textencoder", "textdecoder", "javascript textencoder", "javascript textdecoder", "encoding api javascript", "utf-8 bytes javascript", "string to bytes js", "bytes to string js", "uint8array to string", "string to uint8array", "textencoder encode example", "textdecoder decode example", "textdecoder stream true", "streaming text decode", "decode chunks utf-8", "multibyte character split chunk", "replacement character utf-8", "textdecoder fatal", "whatwg encoding labels", "textdecoder windows-1252", "textdecoder shift_jis", "textdecoder utf-16le", "decode hex to string js", "hex to utf-8 javascript", "utf-8 byte visualization", "utf-8 hex grid", "code point vs bytes", "how many bytes per character utf-8", "utf-8 lead byte continuation byte", "emoji utf-8 bytes", "chinese characters utf-8 bytes", "encodeinto vs encode", "textencoder encodeinto example", "decode streaming fetch", "readable stream text decode", "response body decode stream", "websocket binary text decode", "file reader encoding js", "character encoding javascript", "learn textencoder", "encoding api tutorial", "encoding api playground", "interactive encoding lab", "utf-8 explained", "utf-8 encoding table", "unicode code point javascript", "string codepointat", "get utf-8 bytes of string", "convert string to hex js", "hex dump javascript", "byte length vs string length", "string length emoji problem", "spread string char count vs bytes" ],
  };

export default seo;
