import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Env Vars Reference - Interactive Lab | IconVault",
    metaDescription: "Searchable reference of 80+ environment variables across Node.js, AWS, GCP and Docker with copy and .env template builder. Free.",
    about: [ "**IconVault**'s **Env Vars Reference** is a searchable catalog of **80+ environment variables** across **Node.js**, **AWS**, **GCP** and **Docker**. Every entry explains what the variable does with a realistic example value, from NODE_ENV and PORT to AWS_REGION, GOOGLE_APPLICATION_CREDENTIALS and DOCKER_HOST. It is free and runs fully in your browser.", "Filter by platform, search by name or purpose, copy any variable with one click, or tick several and generate a commented **.env template** to paste into your project. It is the fastest way to stop guessing what that variable you saw in a Dockerfile actually controls." ],
    faqs: [
      { q: "What is the most important Node.js environment variable?", a: "NODE_ENV, which switches frameworks between development, production and test behavior. PORT is next: platforms inject it and your server should listen on it instead of a hardcoded port." },
      { q: "Which AWS environment variables do the SDKs read?", a: "AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN for credentials, AWS_REGION or AWS_DEFAULT_REGION for the target region, plus AWS_PROFILE, AWS_MAX_ATTEMPTS, AWS_RETRY_MODE and AWS_ENDPOINT_URL for local development." },
      { q: "How does GCP authentication via environment variables work?", a: "Set GOOGLE_APPLICATION_CREDENTIALS to the path of a service account JSON key and client libraries pick it up as Application Default Credentials. On Cloud Run and Cloud Functions, GOOGLE_CLOUD_PROJECT and friends are injected automatically." },
      { q: "What does DOCKER_HOST do?", a: "DOCKER_HOST tells the Docker CLI which daemon to talk to, instead of the local socket. Combined with DOCKER_TLS_VERIFY and DOCKER_CERT_PATH it lets you manage remote daemons securely." },
      { q: "Should I commit my .env file?", a: "No. Commit a .env.example with variable names and empty or example values, and keep real secrets in a secret manager or your deployment platform's env config. This tool generates exactly that template format." },
      { q: "Is this tool free?", a: "Yes. Env Vars Reference is completely free and runs fully in your browser." },
    ],
    tags: [ "environment variables", "env vars", "env variables list", "node env variables", "nodejs environment variables", "NODE_ENV", "node port env", "NODE_OPTIONS", "aws environment variables", "AWS_REGION", "AWS_ACCESS_KEY_ID", "aws sdk env vars", "aws lambda environment variables", "AWS_LAMBDA_FUNCTION_NAME", "gcp environment variables", "GOOGLE_APPLICATION_CREDENTIALS", "google cloud env vars", "cloud run environment variables", "K_SERVICE", "docker environment variables", "DOCKER_HOST", "docker compose env", "COMPOSE_PROJECT_NAME", "env var reference", "env vars cheat sheet", "common environment variables", "what is NODE_ENV", "node_env production vs development", "UV_THREADPOOL_SIZE", "NODE_EXTRA_CA_CERTS", "AWS_DEFAULT_REGION vs AWS_REGION", "AWS_PROFILE env", "AWS_SESSION_TOKEN", "AWS_MAX_ATTEMPTS", "AWS_RETRY_MODE adaptive", "AWS_ENDPOINT_URL localstack", "GOOGLE_CLOUD_PROJECT", "GCLOUD_PROJECT", "K_REVISION", "FUNCTION_TARGET", "DOCKER_BUILDKIT", "BUILDKIT_PROGRESS plain", "COMPOSE_FILE", "COMPOSE_PROFILES", "DOCKER_CONTENT_TRUST", "DOCKER_DEFAULT_PLATFORM", "env file template generator", ".env.example generator", ".env template", "how to use env variables", "env variables tutorial", "dotenv explained", "process.env node", "reading env vars javascript", "12 factor app config", "env var naming convention", "secret vs env var", "where to store api keys", "vercel environment variables", "netlify env vars", "dockerfile ENV vs env_file" ],
  };

export default seo;
