import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JS Error Types - Interactive Lab | IconVault",
    metaDescription: "Trigger real TypeError, RangeError, SyntaxError and more, inspect Error.cause chains, AggregateError and stack traces. Free lab.",
    about: [ "**IconVault**'s **JS Error Types** explorer lets you throw every **built-in JavaScript error** for real: TypeError, RangeError, ReferenceError, SyntaxError, URIError, EvalError, plus modern patterns like **Error.cause** chains and **AggregateError**. Each caught error is dissected live, showing its name, message and a frame-by-frame **stack trace analysis**. It is free and runs fully in your browser.", "You can also paste any **stack trace** from your own app and get it parsed into a clean table of functions, files and line numbers, with the throw site highlighted. Understanding what each **error type** means is the fastest way to debug faster: the name alone usually tells you where to look." ],
    faqs: [
      { q: "What are the built-in JavaScript error types?", a: "Error plus six subclasses: TypeError (wrong type operation), RangeError (number out of range), ReferenceError (undeclared variable), SyntaxError (parse failure), URIError (bad encode/decodeURI), and EvalError (legacy eval misuse). AggregateError wraps multiple errors as one." },
      { q: "What is Error.cause in JavaScript?", a: "The cause property, set via new Error('message', { cause: originalError }), chains errors so a high-level error keeps the original failure attached. It preserves the full story across abstraction layers without losing the root stack." },
      { q: "When is AggregateError thrown?", a: "Most commonly by Promise.any(), which rejects with an AggregateError containing every individual rejection in its errors array. You can also construct one manually when collecting multiple validation failures." },
      { q: "How do I read a JavaScript stack trace?", a: "Read top to bottom: frame 0 is where the error was thrown, and each frame below is its caller. Each line shows the function name, file, line and column. Async boundaries may show as separate stacks." },
      { q: "TypeError vs ReferenceError: which is which?", a: "ReferenceError means the variable itself does not exist (a typo or missing declaration). TypeError means the variable exists but you used it wrong, like calling null as a function or reading a property of undefined." },
      { q: "Is this tool free?", a: "Yes. JS Error Types is completely free and runs fully in your browser." },
    ],
    tags: [ "javascript error types", "js error types", "built in errors javascript", "TypeError", "RangeError", "ReferenceError", "SyntaxError", "URIError", "EvalError", "AggregateError", "Error.cause", "javascript error cause", "error cause chaining js", "promise.any aggregateerror", "what is aggregateerror", "js stack trace", "read javascript stack trace", "stack trace analyzer", "parse stack trace online", "javascript stack frames", "error.stack format", "typeerror vs referenceerror", "cannot read properties of null", "cannot read properties of undefined", "invalid array length", "json parse syntaxerror", "uri malformed error", "uncaught typeerror", "uncaught referenceerror", "javascript error names", "error name vs message", "custom error class javascript", "throw new error js", "try catch javascript", "error handling javascript", "javascript debugging", "learn javascript errors", "js error tutorial", "error types explained", "when to use rangeerror", "when to use typeerror", "evalerror example", "urierror example decodeuricomponent", "syntaxerror json.parse", "referenceerror variable not defined", "error cause vs nested errors", "chained exceptions javascript", "aggregate errors array", "promise.any errors array", "multiple errors one catch", "javascript error playground", "interactive error lab", "trigger javascript errors", "js error explorer" ],
  };

export default seo;
