import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Event Propagation - Interactive Lab | IconVault",
    metaDescription: "Watch a real click travel through capturing, target and bubbling phases with animated highlights. Free interactive lab, runs in your browser.",
    about: [ "**IconVault**'s **Event Propagation** visualizer animates a real click as it travels through the DOM. Toggle **capture** and **bubble** listeners on each level, press dispatch, and watch the event move **down** through capturing, hit the **target**, then travel **up** through bubbling, with every step logged using real **eventPhase** values. It is free and runs fully in your browser.", "You can also inject **stopPropagation()** at any level and see exactly which listeners never fire, which makes the behavior concrete instead of theoretical. The page generates the matching **addEventListener** code for your current configuration, ready to copy." ],
    faqs: [
      { q: "What are the three phases of event propagation?", a: "Capturing (the event travels down from window to the target), target (it arrives at the element), and bubbling (it travels back up to window). Listeners default to the bubble phase; pass { capture: true } to listen during capture." },
      { q: "What is the difference between capturing and bubbling?", a: "Capture listeners on ancestors fire before the event reaches the target; bubble listeners fire after. Most code uses bubbling, while capture is useful when a parent must observe or intercept events first." },
      { q: "What does stopPropagation() do?", a: "It prevents the event from continuing to further listeners in the propagation path, in both capture and bubble phases. It does not stop other listeners on the same element; that is stopImmediatePropagation()." },
      { q: "What is eventPhase in JavaScript?", a: "The numeric phase of the event when a listener runs: 1 for capturing, 2 for at-target, 3 for bubbling. This lab displays the real value from each fired listener." },
      { q: "Do capture and bubble listeners both fire at the target?", a: "At the target node itself, listeners fire in registration order regardless of the capture flag in modern browsers. The capture/bubble distinction only matters for ancestors of the target." },
      { q: "Is this tool free?", a: "Yes. Event Propagation is completely free and runs fully in your browser." },
    ],
    tags: [ "event propagation", "javascript event propagation", "event capturing", "event bubbling", "capturing vs bubbling", "event phases javascript", "eventphase", "event.phase 1 2 3", "stoppropagation", "stopimmediatepropagation", "stoppropagation vs stopimmediatepropagation", "addeventlistener capture true", "capture phase example", "bubble phase example", "target phase", "event flow dom", "dom event flow", "how events travel in dom", "event propagation visualizer", "event bubbling animation", "event capturing animation", "interactive event propagation", "learn event bubbling", "event delegation bubbling", "why use event capturing", "when to use capture true", "event propagation order", "nested click handlers order", "parent child click both fire", "prevent parent click when child clicked", "event bubbling problem", "stop event bubbling", "event propagation interview question", "javascript event model", "dom level 2 events", "w3c event flow", "event listener phases", "at_target phase", "capturing_phase bubbling_phase", "e.eventphase", "event path", "composedpath", "event propagation react", "react synthetic events bubbling", "event propagation vue", "event propagation angular", "event propagation tutorial", "dom events explained", "javascript events deep dive", "event propagation playground", "event propagation demo", "visualize event bubbling", "event order visualizer" ],
  };

export default seo;
