import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "EventTarget Patterns - Interactive Lab | IconVault",
    metaDescription: "Master CustomEvent, event delegation, and once, passive and signal listener options with live demos. Free, runs in your browser.",
    about: [ "**IconVault**'s **EventTarget Patterns** lab teaches the essential **addEventListener** patterns with live, working demos. Dispatch **CustomEvent** with structured detail, see **event delegation** handle a whole list with one listener, and try the **once**, **passive** and **signal** options to feel exactly what each one changes. Every interaction is logged to a live event console. It is free and runs fully in your browser.", "These patterns are the difference between fragile and robust event code: delegation keeps dynamic lists fast, passive listeners keep scrolling smooth, once removes one-shot handlers automatically, and **AbortController signals** clean up whole groups of listeners at once. Every snippet is copyable for your projects." ],
    faqs: [
      { q: "What is event delegation in JavaScript?", a: "Attaching one listener to a parent and using event.target (or closest()) to find which child was clicked. It handles dynamically added children automatically and uses far less memory than a listener per item." },
      { q: "What does the once option do in addEventListener?", a: "With { once: true }, the browser automatically removes the listener after it fires a single time. It is perfect for one-shot actions like onboarding tooltips or first-interaction setup." },
      { q: "What is a passive event listener?", a: "A listener registered with { passive: true } promises never to call preventDefault(), so the browser can scroll immediately without waiting for your JavaScript. Use it for wheel, touchstart and touchmove handlers to avoid scroll jank." },
      { q: "How do I remove many event listeners at once?", a: "Pass the same AbortController signal to each addEventListener call, then call controller.abort(). Every listener sharing that signal is removed in one line, which is ideal for component teardown." },
      { q: "How do I pass data with a CustomEvent?", a: "Put it in the detail property: new CustomEvent('my-event', { detail: { user: 'ana' }, bubbles: true }). Listeners read it as event.detail. Custom events do not bubble unless you opt in." },
      { q: "Is this tool free?", a: "Yes. EventTarget Patterns is completely free and runs fully in your browser." },
    ],
    tags: [ "addeventlistener", "javascript addeventlistener", "eventtarget", "customevent", "javascript customevent example", "customevent detail", "dispatchEvent", "event delegation", "event delegation javascript", "event delegation example", "event.target vs event.currenttarget", "event.target closest", "once true addeventlistener", "addeventlistener once option", "passive true", "passive event listener", "passive wheel listener", "preventdefault passive ignored", "scroll jank passive listeners", "abortcontroller signal addeventlistener", "removeeventlistener", "remove all event listeners", "abortcontroller remove listeners", "addeventlistener options", "addeventlistener third argument", "capture vs bubble addeventlistener", "javascript event patterns", "event listener patterns", "event handling best practices", "memory leaks event listeners", "event listener cleanup", "component unmount remove listeners", "custom events vs callbacks", "event.detail typescript", "dispatchevent bubbles", "composed custom event", "shadow dom custom events", "event delegation dynamic list", "event delegation table rows", "delegation vs direct listeners", "performance event delegation", "touchstart passive", "wheel passive listener chrome", "lighthouse passive listeners", "javascript event tutorial", "learn dom events", "dom events playground", "interactive events lab", "eventtarget mdn", "event listener cheat sheet", "js event options explained" ],
  };

export default seo;
