import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Exam Photo Resizer - Free Online Tool | IconVault",
    metaDescription: "Resize your photo to exact IBPS, SBI, SSC, UPSC, NEET or JEE portal specs with the right file size. Free and browser-private.",
    about: [
      "**IconVault**'s **Exam Photo Resizer** sizes your photo exactly the way Indian exam portals demand. Pick a preset (**IBPS and SBI 200 x 230 px 20-50 KB, SSC 276 x 354 px 20-50 KB, UPSC 420 x 540 px 20-300 KB, NEET UG and JEE Main 276 x 354 px 10-200 KB**) or go **Custom** with your own width, height, and Min/Max KB. Your photo is center-cropped to the target dimensions and compressed to fit the file size limit. **Free** to use, **100% in your browser**, and your files never leave your device.",
      "Form rejections for a wrong-size photo are common, so the tool shows the final dimensions and file size right after resizing. **Pro** members get unlimited resizes; free users get a trial quota.",
    ],
    faqs: [
      { q: "What photo size does IBPS need?", a: "IBPS forms typically ask for a 200 x 230 px photo between 20 and 50 KB. The IBPS preset in this tool matches those numbers." },
      { q: "What photo size does SSC need?", a: "SSC usually asks for a 276 x 354 px photo between 20 and 50 KB. Select the SSC preset and resize in one click." },
      { q: "What photo size does UPSC need?", a: "UPSC generally asks for a larger 420 x 540 px photo, 20 to 300 KB. The UPSC preset is built in." },
      { q: "What photo size do NEET and JEE need?", a: "NTA forms for NEET UG and JEE Main typically ask for 276 x 354 px, 10 to 200 KB. Both presets are included." },
      { q: "Can I use my own dimensions and KB limits?", a: "Yes. Choose the Custom preset and set width, height, Min KB and Max KB yourself." },
      { q: "Is my photo uploaded anywhere?", a: "No. The resize and compression happen entirely in your browser, so your photo never leaves your device." },
    ],
    tags: ["exam photo resizer", "ibps photo size 200x230", "sbi photo size 200 x 230", "ssc photo size 276x354", "upsc photo size 420x540", "neet photo size 276 x 354", "jee photo size", "photo 20 to 50 kb", "exam form photo resizer", "government job photo resizer", "passport photo kb reducer", "photo size for ibps form", "ssc cgl photo size kb", "upsc cse photo size", "neet ug photo size nta", "jee main photo size nta", "free exam photo resizer", "online photo resizer kb", "ibps po photo size", "ssc chsl photo size",
      "photo resizer for exam",
      "ibps photo resizer",
      "ssc photo resizer",
      "upsc photo resizer",
      "neet photo resizer",
      "jee photo resizer",
      "sbi photo resizer",
      "exam form photo size",
      "photo resizer 20kb to 50kb",
      "ibps clerk photo size",
      "sbi clerk photo size",
      "ssc mts photo size",
      "upsc photo size in kb",
      "neet photo size in kb",
      "jee main photo size in kb",
      "ibps rrb photo resizer",
      "rrb photo size",
      "gate photo size",
      "cat exam photo size",
      "bank exam photo resizer",
      "railway exam photo size",
      "ssc gd photo resizer",
      "upsc photo dimensions",
      "ibps photo dimensions",
      "ssc photo dimensions",
      "resize photo for ssc form",
      "resize photo for ibps form",
      "resize photo for upsc form",
      "photo compressor for exam form",
      "exam application photo maker",
      "sarkari naukri photo resizer",
      "government exam photo tool",
      "photo size reducer for forms",
      "online exam photo maker",
      "form photo resizer",
      "photo kb resizer online",
      "ibps po photo resizer",
      "sbi po photo size",
      "ssc cgl photo resizer",
      "neet ug photo resizer"],
  };

export default seo;
