import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Exam Portal Presets - Free Online Tool | IconVault",
    metaDescription: "Make both your exam photo and signature files in one click for IBPS, SBI, SSC, UPSC, NEET or JEE portals. Free and browser-private.",
    about: [
      "**IconVault**'s **Exam Portal Presets** make both uploads for your exam form in a single click. Add your **photo** and your **signature**, pick your exam (**IBPS, SBI, SSC, UPSC, NEET UG, or JEE Main**), and the tool produces both JPGs at the commonly published dimensions and file size ranges for that portal. It is **free**, runs **100% in your browser**, and your files never leave your device.",
      "The photo is center-cropped to the portal size, and the signature gets its paper background whitened, trimmed, and centered on a white canvas. A **Custom** mode lets you set your own width, height, and KB limits when your notification differs. **Pro** members get unlimited uses; free users get a trial quota.",
    ],
    faqs: [
      { q: "Which exams are supported?", a: "IBPS, SBI, SSC, UPSC, NEET UG, and JEE Main, plus a Custom mode for any other portal or notification." },
      { q: "What files do I get?", a: "Two JPGs: one for the photo and one for the signature, each resized to your exam's published dimensions and compressed to its file size range." },
      { q: "Are the sizes guaranteed to match my portal?", a: "They match the commonly published rules, but portals do change them. Always check your exam notification before submitting; the disclaimer on the tool reminds you of this." },
      { q: "Does it clean the signature background?", a: "Yes. Clean signature background is on by default and whitens the paper so your ink looks crisp." },
      { q: "Can I set custom sizes?", a: "Yes. Switch the exam selector to Custom and enter your own width, height, Min KB and Max KB for both the photo and the signature." },
      { q: "Are my files uploaded anywhere?", a: "No. Both files are generated in your browser on your device, so nothing is uploaded or stored." },
    ],
    tags: ["exam portal presets", "ibps photo signature size", "sbi photo signature size", "ssc photo signature size", "upsc photo signature size", "neet photo signature size", "jee photo signature size", "exam form photo maker", "exam form signature maker", "ibps photo 200x230 signature 140x60", "ssc photo 276x354 signature 315x157", "upsc photo 420x540", "neet ug photo signature nta", "free exam portal tool", "government exam form photos", "online exam document maker", "portal photo signature generator", "exam upload photo signature", "ibps rrb photo size", "ssc gd photo signature",
      "exam photo signature maker",
      "ibps photo and signature",
      "ssc photo and signature",
      "upsc photo and signature",
      "neet photo and signature",
      "jee photo and signature",
      "sbi photo and signature",
      "exam portal photo maker",
      "exam form documents maker",
      "ibps signature 140x60",
      "ssc signature size",
      "upsc signature size",
      "neet signature size",
      "ibps clerk photo signature",
      "sbi clerk photo signature",
      "ssc mts photo signature",
      "rrb photo signature size",
      "gate photo signature",
      "bank form photo signature",
      "exam upload documents",
      "photo signature for ibps",
      "photo signature for ssc",
      "photo signature for upsc",
      "photo signature for neet",
      "online exam form helper",
      "exam application documents",
      "sarkari form photo signature",
      "government form photo tool",
      "ibps po photo signature",
      "sbi po photo signature",
      "ssc cgl photo signature",
      "ssc chsl photo signature",
      "upsc cse photo signature",
      "jee main photo signature",
      "neet pg photo signature",
      "cat photo signature size",
      "railway photo signature",
      "exam form preset sizes",
      "portal upload photo signature",
      "exam document size checker"],
  };

export default seo;
