import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "EXIF Viewer - Free Online Tool | IconVault",
    metaDescription: "Read a photo's EXIF metadata online: camera, date taken, exposure and GPS. Free, private, runs in your browser.",
    about: [
      "**IconVault**'s **EXIF Viewer** reads the hidden metadata inside your photos: **camera model**, **lens**, **capture date**, **exposure settings**, **dimensions** and **GPS location**, presented in a clean, readable table instead of raw tag soup. Everything is decoded **in your browser**, so the photo is never uploaded and your data never leaves your device.",
      "It is **free** to use and perfect for photographers checking their settings, buyers verifying a listing photo, or anyone curious what their phone records. Every result can be copied as **JSON** for your own records. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "What is EXIF data?", a: "EXIF is metadata your camera or phone embeds in every photo: the camera model, date taken, exposure, ISO, focal length and often the GPS location where the shot was taken." },
      { q: "Is my photo uploaded to a server?", a: "No. The EXIF Viewer reads your photo entirely in your browser with JavaScript. Your image never leaves your device." },
      { q: "Why does my image show no EXIF data?", a: "Screenshots, images downloaded from social apps and photos that were already stripped usually carry no EXIF. The tool will tell you honestly when a file has none." },
      { q: "Can I see the GPS location of a photo?", a: "Yes. If the camera recorded GPS coordinates, they appear in the table with a one-click link to open the spot in a map." },
      { q: "Can I copy the metadata?", a: "Yes. The Copy all as JSON button copies every field, including the raw tags, so you can paste it anywhere or save it for your records." },
      { q: "Is the EXIF Viewer free?", a: "Yes, with 5 free uses. Pro members get unlimited uses plus HD exports and every template across all IconVault tools." },
    ],
    tags: [ "exif viewer", "exif viewer online", "photo metadata viewer", "read exif data", "image metadata reader", "check photo metadata", "exif data online", "view exif online free", "photo exif checker", "camera metadata viewer", "jpg metadata viewer", "png metadata reader", "photo info viewer", "image properties online", "exif reader free", "photo date taken viewer", "gps photo metadata", "exif gps viewer", "photo location finder", "metadata extractor image" ,
      "exif data viewer",
      "view exif data",
      "exif viewer free",
      "online exif reader",
      "exif tool",
      "exif checker",
      "exif online",
      "read photo exif",
      "photo exif data",
      "image exif viewer",
      "exif reader online",
      "check exif online",
      "exif metadata viewer",
      "view photo metadata",
      "photo metadata checker",
      "image metadata checker",
      "exif info",
      "photo exif reader",
      "camera settings viewer",
      "aperture shutter speed viewer",
      "photo iso viewer",
      "image taken date",
      "photo timestamp viewer",
      "exif date viewer",
      "find location of photo",
      "photo gps coordinates viewer",
      "where was photo taken",
      "exif location viewer",
      "image gps data",
      "photo geolocation viewer",
      "exif data checker",
      "view image properties",
      "photo details viewer",
      "image info viewer",
      "exif viewer app online",
      "read jpg metadata",
      "read png metadata",
      "exif data extractor",
      "photo metadata extractor",
      "image metadata online"],
  };

export default seo;
