import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "EyeDropper - Interactive Lab | IconVault",
    metaDescription: "Pick colors from anywhere on screen with the real EyeDropper API and build a palette. Free, runs fully in your browser.",
    about: [ "**IconVault**'s **EyeDropper** playground uses the real `EyeDropper` API: one click opens the browser's native magnifier loupe, and the exact sRGB hex of any pixel on any window lands in your palette. Build the palette up, click a swatch to copy its hex, and download the whole set as JSON. It is free and runs fully in your browser.", "You will learn the **one-method API** (`new EyeDropper().open()`), how to cancel a pick with an **AbortSignal** or the Esc key, and why the API only exists on desktop Chromium. Picks are **per-pixel exact**, which makes this the fastest way to steal a color from a screenshot, a video frame or another app." ],
    faqs: [ { q: "How does the EyeDropper API work?", a: "new EyeDropper().open() returns a promise that resolves with { sRGBHex } after the user clicks a pixel in the native magnifier loupe. This lab calls it directly." }, { q: "Can I cancel a color pick?", a: "Yes: press Esc, or abort the AbortSignal passed to open(). The lab wires both and shows the cancel in a toast." }, { q: "Which browsers support EyeDropper?", a: "Chrome and Edge 95 and later on desktop. Firefox and Safari do not implement it." }, { q: "Can it pick colors outside the browser?", a: "Yes, that is the point: the loupe works over any window on screen, not just the page, which is why it needs a user gesture to activate." }, { q: "What color format does it return?", a: "An sRGB hex string like #0F766E. The lab also converts it to rgb() for each swatch." }, { q: "What is in the downloaded palette?", a: "A JSON file with the palette name, export time, and every color as both hex and rgb values." } ],
    tags: [ "eyedropper api", "eyedropper javascript", "color picker from screen", "pick color from screen", "screen color picker", "eyedropper web api", "new eyedropper().open()", "srgbhex", "color picker api browser", "sample pixel color web", "desktop color picker web", "eyedropper example", "eyedropper tutorial", "eyedropper browser support", "caniuse eyedropper", "eyedropper firefox", "eyedropper safari", "abort eyedropper", "eyedropper abortsignal", "palette builder online", "color palette from screen", "extract colors from image web", "copy hex color", "hex to rgb", "online color picker tool", "screen sampler tool", "design color picker", "ui color picker", "web design eyedropper", "chrome eyedropper", "edge eyedropper", "magnifier loupe web", "pixel color picker", "pick color from video", "pick color from screenshot", "color palette json export", "swatch builder", "color palette generator", "mdn eyedropper", "test eyedropper online", "eyedropper demo", "eyedropper react", "eyedropper typescript", "color thief alternative", "browser color tools", "designer tools online", "hex color copier", "rgb values", "color contrast check", "screen color sampler", "pick any pixel color" ],
  };

export default seo;
