import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "File Handling - Interactive Lab | IconVault",
    metaDescription: "Explore the File Handling API: launchQueue consumer, simulated file launches, file_handlers manifest builder. Free, in your browser.",
    about: [ "**IconVault**'s **File Handling** playground demystifies the PWA File Handling API: attach a real `launchQueue` consumer, simulate an OS file launch through the same code path a real launch uses, preview launched text files, and generate the `file_handlers` manifest snippet your PWA needs to register file types. It is free and runs fully in your browser.", "You will learn why a real launch needs an installed PWA with a **manifest declaration**, how launched files arrive as **FileSystemHandle** objects, and how to read their contents with **getFile()**. The manifest builder produces a copy-ready snippet with your app name, action URL and accepted extensions." ],
    faqs: [ { q: "What is the File Handling API?", a: "It lets an installed PWA register as a handler for file types, so double-clicking a file in the OS can open your web app with that file, much like a native app." }, { q: "How does my app receive the launched files?", a: "Through launchQueue.setConsumer(): the browser calls your callback with LaunchParams containing a files array of FileSystemHandle objects." }, { q: "Why does the lab simulate the launch?", a: "A genuine OS launch requires an installed PWA declaring file_handlers in its manifest. This page is not installed, so the picker stands in and the chosen files flow through the identical consumer code." }, { q: "What goes in the manifest snippet?", a: "A file_handlers array with an action URL and an accept map of MIME types to extensions. The builder generates it from your app name, action and extension list." }, { q: "Which browsers support File Handling?", a: "Chrome and Edge on desktop operating systems that support file associations. It is a PWA feature, not a plain web page feature." }, { q: "Can the launched file be written back?", a: "The handle you receive can request read and write permission, so yes: with user consent your app can edit the original file in place." } ],
    tags: [ "file handling api", "file_handlers", "launchqueue", "pwa file handling", "launchparams", "web app manifest file_handlers", "open file with pwa", "file association web app", "launchqueue.setconsumer", "file handling example", "file handling tutorial", "pwa open files", "register file type pwa", "manifest file_handlers action", "accept map file_handlers", "filesystemhandle", "getfile from handle", "pwa as default app", "double click opens pwa", "file handling browser support", "caniuse file handling", "file handling chrome", "installed pwa features", "pwa capabilities", "project fugu file handling", "fugu apis", "web app file association", "handle file launch web", "os integration pwa", "pwa manifest generator", "web app manifest builder", "file type registration web", "mdn file handling api", "test file handling online", "file handling demo", "launch queue web", "consume launch params", "read launched file", "write launched file", "pwa file editor", "native file handling web", "file handler action url", "multiple files launch", "launch files array", "pwa installable", "beforeinstallprompt", "pwa manifest display standalone", "file handling security", "permission file handle", "pwa file_handlers example", "launchqueue api" ],
  };

export default seo;
