import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "File System Access - Interactive Lab | IconVault",
    metaDescription: "Use the real File System Access API: open, edit and save files in place, browse directories. Free, runs fully in your browser.",
    about: [ "**IconVault**'s **File System Access** playground uses the real picker APIs: open a text file from your disk, edit it in the live editor, and save straight back to the same file with no download step. You can also Save As, start a new file, and browse a whole directory with names, kinds and sizes. It is free and runs fully in your browser.", "You will learn how file handles persist user permission across the session, the difference between reading with **getFile()** and writing with **createWritable()**, and why every access starts with an **explicit picker gesture**. Nothing is uploaded: the browser mediates a local file reference, and the permission badge shows exactly what access was granted." ],
    faqs: [ { q: "What is the File System Access API?", a: "It gives web apps read and write access to user-selected files and directories through showOpenFilePicker, showSaveFilePicker and showDirectoryPicker, with permission the user grants per handle." }, { q: "How does Save write to the original file?", a: "openFile keeps the FileSystemFileHandle; Save calls handle.createWritable(), writes the editor text and closes the stream, which commits to the same file on disk." }, { q: "Which browsers support it?", a: "Chrome and Edge 86 and later on desktop for the full API. Firefox and Safari do not implement the picker methods." }, { q: "Is my file uploaded anywhere?", a: "No. Handles are local capabilities; reads and writes happen between the browser and your disk. The demo editor never sends content to a server." }, { q: "What is the permission badge showing?", a: "The result of handle.queryPermission({ mode: 'readwrite' }): whether this page currently may read and write that specific file without prompting again." }, { q: "Can a site keep the handle after reload?", a: "Yes, handles can be stored in IndexedDB and re-permissioned later, which is how web IDEs remember your project folder. This lab keeps it simple and in-memory." } ],
    tags: [ "file system access api", "showopenfilepicker", "showsavefilepicker", "showdirectorypicker", "filesystemfilehandle", "file system access example", "file system access tutorial", "read local file javascript", "write local file javascript", "createwritable", "getfile handle", "browser file editor", "web file system", "native file system api", "file handle permission", "querypermission", "requestpermission file", "opfs", "origin private file system", "file system access browser support", "caniuse file system access", "file system access firefox", "file system access safari", "webkit file system", "save file javascript no download", "edit file in browser", "web ide file system", "local file web app", "directory picker web", "list directory javascript", "read directory browser", "file picker web", "save as dialog web", "text file editor online", "mdn file system access", "test file system access online", "file system access demo", "file system access react", "file system access typescript", "file system access security", "user gesture file picker", "aborterror picker cancelled", "file system access https", "indexeddb file handles", "persist file handle", "web app local files", "project fugu", "fugu file system", "sandboxed file system", "file system writable stream" ],
  };

export default seo;
