import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Fullscreen API - Interactive Lab | IconVault",
    metaDescription: "Try the real Fullscreen API: requestFullscreen, navigationUI options, :fullscreen CSS, live state and events. Free, in your browser.",
    about: [ "**IconVault**'s **Fullscreen API** playground calls the real `requestFullscreen()`: send the demo box or the whole page fullscreen, experiment with the navigationUI option, watch document.fullscreenElement update live, and see fullscreenchange and fullscreenerror events stream into the log. A pure CSS `:fullscreen` rule restyles the demo box with zero JavaScript. It is free and runs fully in your browser.", "You will learn why the request needs a **user gesture**, what each **navigationUI** value does to the browser chrome, why only one element can be fullscreen at a time, and that Esc always exits (the browser reserves it). If an iframe blocks fullscreen, the tool reports **fullscreenEnabled** honestly instead of failing silently." ],
    faqs: [ { q: "How do I make an element fullscreen?", a: "Call element.requestFullscreen() from a user gesture; it returns a promise that resolves when the transition completes. This lab does it on the demo box or the page root." }, { q: "What does the navigationUI option do?", a: "It hints whether browser UI should stay visible: auto lets the browser decide, hide requests a fully immersive view, show keeps the chrome. It applies to page-level fullscreen." }, { q: "How do I style the fullscreen element?", a: "With the :fullscreen CSS pseudo-class, as the demo box does: it swaps to a teal gradient with no JavaScript involved." }, { q: "How do I exit fullscreen?", a: "Call document.exitFullscreen(), or let the user press Esc, which the browser always honors. Both fire fullscreenchange on the document." }, { q: "Why did my request get rejected?", a: "Common causes: no user gesture, an iframe without allow=fullscreen, Permissions Policy blocking it, or another element already fullscreen. Rejections appear in the event log here." }, { q: "Can two elements be fullscreen at once?", a: "No. Requesting fullscreen on a second element moves fullscreen to it; document.fullscreenElement always points at the single current one." } ],
    tags: [ "fullscreen api", "requestfullscreen", "fullscreen javascript", "exitfullscreen", "fullscreenchange", "fullscreenerror", "fullscreen css", ":fullscreen", "document.fullscreenelement", "fullscreenenabled", "navigationui", "fullscreen api example", "fullscreen api tutorial", "make div fullscreen", "fullscreen button javascript", "fullscreen video custom", "fullscreen image gallery", "presentation mode web", "kiosk mode browser", "immersive web", "fullscreen iframe allow", "allow fullscreen iframe", "permissions policy fullscreen", "fullscreen promise rejected", "fullscreen not working", "esc exits fullscreen", "fullscreenchange event", "fullscreen api browser support", "caniuse fullscreen", "fullscreen safari webkit", "webkitrequestfullscreen", "mozrequestfullscreen", "fullscreen api react", "fullscreen api typescript", "mdn fullscreen api", "test fullscreen online", "fullscreen playground", "fullscreen demo", "toggle fullscreen javascript", "fullscreen element styling", "fullscreen background", "fullscreen mobile", "screen orientation fullscreen", "wake lock fullscreen", "game fullscreen web", "canvas fullscreen", "fullscreen api 2024", "picture in picture vs fullscreen", "enter fullscreen onclick", "fullscreen event listener", "fullscreen toggle button" ],
  };

export default seo;
