import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Gamepad - Interactive Lab | IconVault",
    metaDescription: "Connect a real gamepad: live button and axis viewer, connection events and rumble test. Free, runs fully in your browser.",
    about: [ "**IconVault**'s **Gamepad** playground reads the real Gamepad API: connect a controller over USB or Bluetooth, press any button, and watch every button light up with its analog value while the sticks sweep live axis bars. A rumble panel drives the vibration actuator with your choice of duration and motor strength. It is free and runs fully in your browser.", "You will learn the **polling model** (`navigator.getGamepads()` every animation frame), the **standard button mapping**, why browsers only expose a gamepad after you press a button, and how **`playEffect('dual-rumble')`** addresses the strong and weak motors separately. With no gamepad connected the page shows an honest empty state and never fakes input." ],
    faqs: [ { q: "Why does nothing show until I press a button?", a: "For privacy, browsers keep gamepads hidden from navigator.getGamepads() until the user interacts with one. Press any button once and it appears instantly." }, { q: "How do I read gamepad input in code?", a: "Poll navigator.getGamepads() in a requestAnimationFrame loop and read gamepad.buttons (pressed plus analog value) and gamepad.axes (minus 1 to 1). This lab does exactly that." }, { q: "What is the standard mapping?", a: "mapping: 'standard' means the familiar layout: A/B/X/Y, bumpers, triggers, Back/Start, stick clicks and the D-pad, in that index order, which the lab labels." }, { q: "How does the rumble test work?", a: "It calls gamepad.vibrationActuator.playEffect('dual-rumble', { duration, strongMagnitude, weakMagnitude }). Not every controller exposes an actuator, and the lab reports that honestly." }, { q: "Do I need HTTPS for the Gamepad API?", a: "It works on secure contexts including localhost. Some browsers gate it behind a user gesture or a permissions policy in iframes." }, { q: "Which gamepads work?", a: "Most USB and Bluetooth controllers: Xbox, PlayStation, Switch Pro and generic HID pads. Mapping quality varies by browser and OS." } ],
    tags: [ "gamepad api", "navigator.getgamepads", "gamepad javascript", "game controller web", "gamepad api example", "gamepad api tutorial", "html5 gamepad", "controller input browser", "gamepad buttons", "gamepad axes", "standard mapping gamepad", "gamepadconnected", "gamepaddisconnected", "vibrationactuator", "playeffect dual-rumble", "gamepad rumble", "controller vibration web", "rumble test online", "gamepad tester", "test gamepad online", "gamepad viewer", "xbox controller browser", "ps5 controller web", "switch pro controller pc browser", "bluetooth gamepad web", "gamepad not detected", "gamepad api not working", "press button gamepad", "gamepad polling", "requestanimationframe gamepad", "gamepad timestamp", "gamepad id", "analog trigger value", "gamepad deadzone", "gamepad input lag", "web game controller", "browser game controller support", "caniuse gamepad", "gamepad api firefox", "gamepad api chrome", "gamepad safari", "gamepad typescript", "mdn gamepad", "gamepad demo", "gamepad playground", "controller test site", "gamepad api 2024", "haptic feedback web", "dual rumble", "strongmagnitude weakmagnitude" ],
  };

export default seo;
