import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Geolocation Playground - Interactive Web API Lab | IconVault",
    metaDescription: "Test the live Geolocation API: real-time position, accuracy circle, speed, heading and geofence enter/exit alerts. Free, runs in your browser.",
    about: [ "**IconVault**'s **Geolocation Playground** connects to the real **Geolocation API** (`navigator.geolocation`): your live latitude and longitude, the **accuracy** radius drawn as a circle on the map, **speed** and **heading** as you move, and a movement trail that records where you have been. Draw a geofence and the lab fires enter and exit alerts when you cross its boundary. It is free and runs fully in your browser.", "Geolocation only works with your **permission**, and only in a **secure context** (HTTPS or localhost). You will learn the difference between `getCurrentPosition()` and `watchPosition()`, why accuracy swings from a few meters outdoors to hundreds indoors, and the sensible options: `enableHighAccuracy`, `timeout` and `maximumAge`. The lab also covers the privacy angle: always explain why you need a location before asking, and never store precise coordinates you do not need." ],
    faqs: [ { q: "Does the Geolocation API need my permission?", a: "Yes. The browser shows a permission prompt, and you can revoke it at any time in site settings. This lab cannot read your position until you allow it." }, { q: "Why does my position accuracy change so much?", a: "GPS outdoors can reach a few meters; indoors the device falls back to Wi-Fi and cell towers, which can be hundreds of meters off. The accuracy circle on the map shows the current uncertainty." }, { q: "What is the difference between getCurrentPosition and watchPosition?", a: "getCurrentPosition returns one fix; watchPosition keeps streaming updates and returns an ID you clear with clearWatch(). This lab uses watchPosition for the live trail." }, { q: "Why does geolocation fail on plain HTTP?", a: "It is restricted to secure contexts: HTTPS pages and localhost. Non-secure origins get a permission-denied error by design." }, { q: "What is a geofence?", a: "A virtual boundary around a map point. This lab lets you draw one and logs an event when your position enters or exits it, the same pattern apps use for arrival reminders." }, { q: "Is my location sent to a server?", a: "No. Everything is computed locally in your browser; the lab never uploads your coordinates." } ],
    tags: [ "geolocation api", "navigator.geolocation", "geolocation api javascript", "html5 geolocation", "getcurrentposition", "watchposition", "geolocation example", "geolocation api tutorial", "geolocation playground", "javascript get location", "browser location api", "html geolocation example", "geolocation permission", "geolocation not working", "geolocation accuracy", "geolocation speed heading", "geolocation altitude", "geofence javascript", "geofencing web", "geofence enter exit", "geolocation watchposition example", "clearwatch", "enablehighaccuracy", "geolocation timeout", "maximumage geolocation", "mdn geolocation api", "geolocation secure context", "geolocation https required", "why is geolocation inaccurate", "improve geolocation accuracy", "get latitude longitude javascript", "how to get user location in javascript", "device location web api", "location api web", "maps geolocation demo", "test geolocation online", "geolocation coordinates", "position.coords", "geolocation timestamp", "geolocation error codes", "permission denied geolocation", "position unavailable", "geolocation ios safari", "geolocation android chrome", "pwa geolocation", "geolocation privacy", "geolocation best practices", "reverse geocoding", "geolocation distance calculator", "haversine javascript", "draw accuracy circle map", "leaflet geolocation", "mapbox geolocation", "openstreetmap location", "geolocation api 2024", "caniuse geolocation", "is geolocation supported", "geolocation typescript" ],
  };

export default seo;
