import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "GitHub Releases - Free Online Release Notes Browser | IconVault",
    metaDescription: "Browse release notes for any GitHub repo with version filtering, assets and download counts. Free, runs in your browser.",
    about: [
      "**IconVault**'s **GitHub Releases** browser lets you read the **release notes** of any public GitHub repository without opening a dozen tabs. Paste an **owner/repo** name or a full **github.com URL**, then filter releases by **version**, expand notes inline and see **prerelease** and **draft** flags, **publish dates** and downloadable **assets** with their **download counts**.",
      "Everything is fetched from the **public GitHub API** directly in your browser: no login, no token, no signup. It is **free** to use. The honest caveat: anonymous GitHub API calls are limited to **60 requests per hour** per IP, so heavy browsing sessions can hit a rate limit. Wait a bit and retry if that happens."
    ],
    faqs: [
      { q: "How do I look up a repository?", a: "Type owner/repo, for example facebook/react, or paste a full github.com URL. The tool parses both formats and loads the release list from the GitHub API." },
      { q: "What information is shown per release?", a: "Tag name, release title, published date, prerelease and draft flags, the full release notes body and every attached asset with its download count and a download link." },
      { q: "How does the version filter work?", a: "Type part of a version or tag name and the list narrows to matching releases, so you can jump straight to v2.x notes in a long history." },
      { q: "Why did I get a rate limit error?", a: "The public GitHub API allows 60 anonymous requests per hour per IP address. Each lookup uses a couple of requests, so slow down or wait an hour if you hit the cap." },
      { q: "Can I browse private repositories?", a: "No. Only public repositories are visible through the anonymous GitHub API. Private repos need an authenticated token, which this tool does not use." },
      { q: "Is it really free?", a: "Yes. Unlimited browsing within GitHub's anonymous rate limit, no account, no signup." }
    ],
    tags: [
      "github releases",
      "github release notes",
      "browse github releases",
      "github releases viewer",
      "github changelog viewer",
      "github release notes online",
      "github repo releases",
      "github releases page",
      "github latest release checker",
      "github version history",
      "github release history",
      "github tag releases",
      "github release assets",
      "github release download count",
      "github release notes search",
      "github release filter",
      "check github releases online",
      "github releases browser",
      "github releases tool",
      "view github releases without login",
      "github releases no login",
      "github public releases viewer",
      "github repo changelog",
      "github project changelog",
      "github software releases",
      "github release tracker",
      "track github releases",
      "github prerelease viewer",
      "github draft releases",
      "github release body",
      "github release notes format",
      "github releases api viewer",
      "github release notes browser",
      "see all github releases",
      "github all versions list",
      "github version list",
      "github software version history",
      "github app update history",
      "github release archive",
      "github old releases",
      "download old github release",
      "github release assets download",
      "github release notes search online",
      "github repo version checker",
      "what is the latest version on github",
      "github latest tag checker",
      "github release date checker",
      "github release timeline",
      "github releases dashboard",
      "github release notes reader"
    ],
  };

export default seo;
