import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "GIF to MP4 Converter - Free Online Tool | IconVault",
    metaDescription: "Convert animated GIFs to MP4 or WebM video online. Free, private, records in your browser.",
    about: [
      "**IconVault**'s **GIF to MP4** converter turns an **animated GIF** into a real video file: far smaller, with smooth playback on every platform. The animation is replayed onto a canvas and recorded with **MediaRecorder**, so you get **genuine MP4 in Safari** and **WebM in Chrome**, stated honestly up front with the matching file extension, never a mislabeled file.",
      "Pick a **background color** for transparent areas (videos have no transparency), preview the result, then download. It is **free** and runs **100% in your browser**, so your GIF never leaves your device. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "How do I convert a GIF to MP4?", a: "Upload the GIF, pick a background color and hit Convert to video. The animation is recorded in your browser and you download the video file." },
      { q: "Will I really get an MP4?", a: "In Safari, yes. Chrome and Firefox cannot record MP4, so they produce WebM instead. The tool detects your browser and labels the output honestly with the matching extension." },
      { q: "What happens to transparency?", a: "Videos have no transparency, so clear areas are filled with the background color you choose (white by default)." },
      { q: "Why convert GIF to video?", a: "Video files are dramatically smaller than GIFs for the same animation and play smoothly on social apps and messaging platforms." },
      { q: "Is my GIF uploaded?", a: "No. Recording happens entirely in your browser. Your GIF never leaves your device." },
      { q: "Is it free?", a: "Yes, with 5 free conversions. Pro members get unlimited runs plus HD exports and every template across all IconVault tools." },
    ],
    tags: [ "gif to mp4", "convert gif to mp4", "gif to video", "gif to webm", "animated gif to video", "gif mp4 converter online", "turn gif into video", "gif to video converter free", "mp4 from gif", "gif video download", "convert gif to video online", "gif to mp4 no watermark", "gif to movie", "save gif as video", "gif to mp4 free", "video from animated gif", "gif converter to mp4", "browser gif to video", "gif to mp4 safari", "gif to webm converter" ,
      "gif to mp4 online free",
      "convert animated gif to mp4",
      "gif to video online free",
      "gif to mp4 high quality",
      "best gif to mp4 converter",
      "gif to mp4 converter free no watermark",
      "turn gif into mp4 video",
      "gif to video file",
      "gif to mov",
      "convert gif to mov",
      "gif to video for whatsapp",
      "gif to mp4 for instagram",
      "gif to mp4 for discord",
      "gif to mp4 bulk converter",
      "batch gif to mp4",
      "multiple gifs to mp4",
      "gif to mp4 in browser",
      "gif to mp4 without watermark online",
      "animated gif to mp4 converter",
      "how to convert gif to mp4",
      "how to turn a gif into a video",
      "gif to mp4 iphone",
      "gif to mp4 android",
      "gif to mp4 download",
      "gif to mp4 60fps",
      "convert gif to hd video",
      "gif to mp4 hd quality",
      "gif to video converter app",
      "gif to mp4 converter app",
      "gif to video for social media",
      "gif to mp4 for twitter",
      "gif to mp4 loop video",
      "make gif a video file",
      "convert gif to video file",
      "gif to video online no sign up",
      "gif to mp4 free converter online",
      "gif to mp4 fast converter",
      "convert gif to mp4 for free",
      "gif to mp4 tool",
      "gif to mp4 converter no signup"],
  };

export default seo;
