import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "GIF Maker - Free Online Tool | IconVault",
    metaDescription: "Make animated GIFs from images online. Frame delay, loop, size and palette controls. Free, private, in-browser.",
    about: [
      "**IconVault**'s **GIF Maker** turns your images into a smooth **animated GIF** with full creative control: reorder frames with up and down buttons, set the **frame delay**, choose **loop forever** or a fixed play count, pick the **width** (height follows the first image), and choose **fit inside** or **fill and crop** with a custom background color and a 256, 128 or 64 **color palette**.",
      "It is **free** and runs **100% in your browser** with a **live animated preview** that rebuilds as you tweak settings, so what you see is exactly what you download. Your images never leave your device. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "How do I make a GIF from images?", a: "Upload 2 or more images, order the frames, set the frame delay and loop, then hit Make GIF. A live preview shows the animation before you download." },
      { q: "How many images do I need?", a: "At least 2. There is no upper limit, but very long frame lists make heavier GIFs." },
      { q: "Can I control the GIF size?", a: "Yes. Set the width in pixels and the height is calculated from the first image to keep proportions. Fit inside letterboxes, fill and crop crops to fill." },
      { q: "Can the GIF loop a set number of times?", a: "Yes. Choose Forever for an infinite loop or Set times and enter how many plays you want." },
      { q: "Are my images uploaded?", a: "No. Encoding happens entirely in your browser. Your images never leave your device." },
      { q: "Is it free?", a: "Yes, with 5 free GIFs. Pro members get unlimited runs plus HD exports and every template across all IconVault tools." },
    ],
    tags: [ "gif maker", "make gif from images", "gif maker online free", "create animated gif", "images to gif", "gif creator", "online gif maker", "photo to gif", "make gif free", "gif animator online", "slideshow to gif", "gif frame maker", "animated gif creator", "jpg to gif", "png to gif", "gif loop maker", "custom gif maker", "gif maker no watermark", "browser gif maker", "free gif generator" ,
      "gif maker from photos",
      "turn photos into gif",
      "create gif from pictures",
      "how to make a gif online",
      "best gif maker online",
      "free gif maker no sign up",
      "animated gif maker online",
      "convert pictures to gif",
      "make a gif from multiple images",
      "gif generator from images",
      "turn images into gif online",
      "gif maker with text overlay",
      "live photo to gif",
      "burst photos to gif",
      "gif maker with captions",
      "gif maker for whatsapp",
      "gif maker online no watermark free",
      "animated gif maker without watermark",
      "gif creator free download",
      "bulk gif maker",
      "gif animation maker",
      "photo animation maker",
      "make gif from screenshots",
      "slideshow gif maker",
      "gif maker with frame delay",
      "gif maker adjust speed",
      "gif frame rate editor",
      "create gif online without app",
      "gif maker in browser free",
      "how to make an animated gif from photos",
      "turn a video clip into a gif",
      "gif maker from jpeg",
      "gif maker from png images",
      "best free gif maker",
      "gif maker for memes",
      "gif maker for discord",
      "reaction gif maker",
      "animated meme gif maker",
      "gif maker with transparent background",
      "transparent gif maker online"],
  };

export default seo;
