import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "GIF to Frames - Free Online Tool | IconVault",
    metaDescription: "Split an animated GIF into PNG or JPG frames online. Free, private, individual or ZIP download.",
    about: [
      "**IconVault**'s **GIF to Frames** splitter extracts every frame of an **animated GIF** as a full-size still image. Each frame is the **full picture as it appears in the animation**, composited over the frames before it, not a cropped patch, so frame 20 looks exactly like frame 20 of the playback.",
      "Choose **PNG or JPG** output, download frames **individually** or grab them all as one **ZIP**, and even **paste a GIF** straight from your clipboard. It is **free** and runs **100% in your browser**, so your GIF never leaves your device. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "How do I split a GIF into frames?", a: "Drop the GIF (or paste it from your clipboard), pick PNG or JPG, and every frame appears as a downloadable still, individually or as a ZIP." },
      { q: "Are the frames full images or cropped patches?", a: "Full images. Each frame is composited exactly as it appears during playback, so you get the complete picture for every frame." },
      { q: "PNG or JPG: which should I pick?", a: "PNG keeps full quality and transparency. JPG makes smaller files; transparent areas get a white background." },
      { q: "Can I paste a GIF instead of uploading?", a: "Yes. Click the drop zone and paste, or just drag and drop the file." },
      { q: "Is my GIF uploaded?", a: "No. Splitting happens entirely in your browser. Your GIF never leaves your device." },
      { q: "Is it free?", a: "Yes, with 5 free splits. Pro members get unlimited runs plus HD exports and every template across all IconVault tools." },
    ],
    tags: [ "gif to frames", "split gif into frames", "extract frames from gif", "gif frame extractor", "gif to png", "gif to jpg", "decompose gif", "gif frames download", "save gif frames", "gif to image sequence", "animated gif to stills", "gif splitter online", "extract gif images", "gif frame grabber", "gif to pictures", "download gif as images", "gif frames zip", "gif to png sequence", "online gif extractor", "free gif splitter" ,
      "gif to frames online free",
      "export gif as png sequence",
      "export gif as jpg sequence",
      "split animated gif",
      "convert gif to frames free",
      "gif to still images",
      "gif to jpeg frames",
      "extract all frames from gif",
      "gif frame splitter free",
      "break gif into images",
      "gif frames to zip",
      "save each gif frame",
      "gif to png frames online",
      "gif to image converter",
      "extract gif frames no watermark",
      "how to extract frames from a gif",
      "gif frame by frame viewer",
      "view gif frames individually",
      "gif to individual images",
      "split gif online free",
      "gif frame downloader",
      "animated gif frames extractor",
      "gif to frames for animation editing",
      "convert gif to sprite sheet frames",
      "gif to webp frames",
      "export gif frames as webp",
      "gif frame extract tool free",
      "decompile gif",
      "gif decompiler online",
      "gif to bmp sequence",
      "extract gif frames in bulk",
      "gif frames bulk download",
      "gif to frames high quality",
      "download gif frame by frame",
      "gif thumbnail extractor",
      "get still from gif",
      "gif to photos online",
      "turn gif into photos",
      "gif still frame capture",
      "extract images from animated gif"],
  };

export default seo;
