import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "GitHub Token Validator - Free Online Token Checker Tool | IconVault",
    metaDescription: "Check if a GitHub personal access token is valid, see its account, scopes and rate limit. Sent directly from your browser to GitHub, never stored. Free.",
    about: [
      "**IconVault**'s **GitHub Token Validator** checks a **personal access token** (classic ghp_ or fine-grained) by calling GitHub's own **/user** endpoint. In seconds you learn whether the token is **valid**, which **account** it belongs to, which **OAuth scopes** it grants and how much **API rate limit** remains, so you can confirm a token works before pasting it into CI or a deploy pipeline.",
      "The validation request goes **directly from your browser to GitHub**. The token lives in **memory only** and is never saved, logged or sent to our servers, and the Clear button wipes it instantly. It is **free** to use with no signup. The honest caveat: this tool cannot tell you why a token was revoked or when it expires, and it checks only the token you paste, it never touches your GitHub password or 2FA."
    ],
    faqs: [
      { q: "How do I check if a GitHub token is valid?", a: "Paste it into the tool and click Validate token. It calls GitHub's /user API with the token and reports whether GitHub accepted it, along with the account, scopes and remaining rate limit." },
      { q: "Is my token stored anywhere?", a: "No. The request goes directly from your browser to api.github.com. The token stays in page memory, is never written to disk or sent to IconVault's servers, and the Clear button wipes it instantly." },
      { q: "What does it show for a valid token?", a: "The GitHub username the token belongs to, the OAuth scopes attached to it (repo, workflow and similar), and the remaining API quota. That helps you keep permissions minimal and spot quota problems early." },
      { q: "Why is my token invalid?", a: "Usually it has expired, been revoked, was typed incorrectly, or was replaced by a newer token. Fine-grained tokens can also fail if they lack access to the user endpoint. If in doubt, generate a new token at github.com/settings/tokens." },
      { q: "Does it work with fine-grained personal access tokens?", a: "Yes, both classic (ghp_) and fine-grained tokens work. For fine-grained tokens the scopes display may be empty, because GitHub reports permissions differently for them." },
      { q: "Can I use this in CI or a script?", a: "This page is a manual browser check. For automation, run curl with an Authorization header against api.github.com/user in your own pipeline instead." }
    ],
    tags: [
      "github token validator",
      "check github token",
      "validate github personal access token",
      "github token checker online",
      "is my github token valid",
      "test github api token",
      "github token expired check",
      "github token scopes check",
      "ghp token validator",
      "github pat validator",
      "check if github token is valid",
      "validate ghp token online",
      "github personal access token checker",
      "github oauth token test",
      "how to check if github token is valid",
      "how to validate github token",
      "github api token test",
      "github token status check",
      "verify github access token",
      "github token not working",
      "github token invalid 401",
      "github token revoked how to check",
      "check github token permissions",
      "github token scopes list",
      "x-oauth-scopes github",
      "github rate limit remaining check",
      "github api quota check",
      "github token expiry date",
      "do github tokens expire",
      "github fine grained token test",
      "validate github classic token",
      "github token for ci cd",
      "github actions token validation",
      "github deployment token check",
      "github cli token validation",
      "curl validate github token",
      "github api user endpoint test",
      "free github token checker",
      "online github pat checker",
      "no signup github token test",
      "secure github token validation",
      "github token privacy check",
      "github token memory only",
      "github developer token tester",
      "github token troubleshooting",
      "why is my github token invalid",
      "github 401 bad credentials fix",
      "regenerate github personal access token",
      "github token best practices",
      "github token least privilege"
    ],
  };

export default seo;
