import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "GitHub Profile Stats - Free Online GitHub Profile Analyzer | IconVault",
    metaDescription: "Analyze any GitHub profile: repos, stars, followers, top languages and a repo creation timeline. Free, in your browser.",
    about: [
      "**IconVault**'s **GitHub Profile Stats** turns any GitHub username into a visual **profile dashboard**. You get the **avatar, bio and join date**, totals for **public repos, followers and following**, the **total star count** across all repos, the **top 8 languages** by repository count with a color breakdown, and a **repo-creation timeline** showing activity year by year.",
      "All data comes from the **public GitHub API** and is rendered **fully in your browser**: no login, no token, no signup. It is **free** to use. The honest caveat: anonymous API calls are capped at **60 per hour** per IP, so very active profiles or back-to-back lookups can trigger a rate limit. Private repositories are never visible through this API."
    ],
    faqs: [
      { q: "What stats does the dashboard show?", a: "Profile basics (avatar, name, bio, join date), public repo count, follower and following counts, total stars across all public repos, top 8 languages by repo count and a year-by-year repo creation timeline." },
      { q: "How are the top languages calculated?", a: "By counting each public repository's primary language, then ranking the top 8. It reflects breadth of repos per language, not lines of code." },
      { q: "Why did I hit a rate limit?", a: "GitHub allows 60 anonymous API requests per hour per IP. A profile lookup uses two requests, so the cap only bites during heavy use. Wait a while and retry." },
      { q: "Are private repositories included?", a: "No. Only public repositories and public profile data are visible through the anonymous API, so private work never appears." },
      { q: "What if the username does not exist?", a: "You will see a clear not-found error. Usernames are case-insensitive, so double-check the spelling." },
      { q: "Is it really free?", a: "Yes. Unlimited profile lookups within GitHub's anonymous rate limit, no account, no signup." }
    ],
    tags: [
      "github profile stats",
      "github profile analyzer",
      "github stats viewer",
      "github profile checker",
      "github user stats",
      "github profile dashboard",
      "github profile summary",
      "github developer profile",
      "github portfolio stats",
      "github repos stats",
      "github stars counter",
      "github total stars",
      "github followers checker",
      "github profile insights",
      "github profile analytics",
      "github user analytics",
      "github profile report",
      "github profile overview",
      "github language stats",
      "github top languages",
      "github profile languages chart",
      "github repo timeline",
      "github activity timeline",
      "github profile history",
      "analyze github profile",
      "github profile analysis tool",
      "github profile lookup",
      "github user lookup",
      "github username checker",
      "github profile search",
      "view github profile stats online",
      "github stats no login",
      "github profile without login",
      "github developer stats",
      "github coder stats",
      "github profile card",
      "github stats card",
      "github readme stats alternative",
      "github profile grade",
      "github profile score",
      "github developer portfolio",
      "github hiring stats",
      "github recruiter profile check",
      "github profile for resume",
      "github account stats",
      "github account analyzer",
      "github account overview",
      "github public repos list",
      "github most starred repos",
      "github profile breakdown",
      "github yearly activity"
    ],
  };

export default seo;
