import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Gitignore Generator - Free Online .gitignore Builder Tool | IconVault",
    metaDescription: "Pick from 150+ templates for Node.js, Python, React, Docker and more, merged into one clean .gitignore with duplicates removed. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Gitignore Generator** turns ignore rules into a two-minute job. Choose from **150+ curated templates** covering **languages** (Node.js, Python, Go, Rust, Java), **frameworks** (React, Next.js, Django, Laravel, Flutter), **tools** (Docker, Terraform, Firebase), **operating systems** and **IDEs**, and the tool merges your selection into one clean **.gitignore** file.",
      "The merge is smart: **duplicate lines are removed automatically**, every section is labeled, and you get a **live preview** as you toggle templates, then **copy or download** the finished file. It is **free** with no signup and runs **fully in your browser**, so your project setup stays private. The honest caveat: templates are starting points, so review the preview before committing, and remember .gitignore cannot untrack files you already committed (use git rm --cached for those)."
    ],
    faqs: [
      { q: "What is a .gitignore file?", a: "A text file in a Git repo that tells Git which files and folders to ignore, like node_modules, build output, logs and OS junk. It keeps repositories small and stops secrets from being committed." },
      { q: "How does the merge work?", a: "Select any combination of templates and the tool stacks them with a header per template, skipping lines that already appeared. You get one deduplicated file instead of 150 separate ones." },
      { q: "How many templates are included?", a: "Over 150, across languages, frameworks, build tools, operating systems and IDEs, each hand-checked. Use the search box to find yours fast." },
      { q: "Is my selection uploaded anywhere?", a: "No. Everything runs in your browser. Your template choices never leave your device." },
      { q: "What if my stack is not listed?", a: "Pick the closest matches (for example JavaScript plus React for a custom setup) and add any extra lines yourself after downloading, since the file is plain text." },
      { q: "Will this remove files I already committed?", a: "No. .gitignore only affects untracked files. To stop tracking a file that is already committed, run git rm --cached <file> after adding it to .gitignore." }
    ],
    tags: [
      "gitignore generator",
      ".gitignore generator online",
      "gitignore file generator",
      "create gitignore online",
      "gitignore template",
      "gitignore node",
      "gitignore python",
      "gitignore react",
      "gitignore nextjs",
      "gitignore django",
      "gitignore java",
      "gitignore golang",
      "gitignore rust",
      "gitignore flutter",
      "gitignore unity",
      "gitignore visual studio",
      "gitignore vscode",
      "gitignore macos",
      "gitignore windows",
      "gitignore docker",
      "gitignore terraform",
      "gitignore laravel",
      "gitignore angular",
      "gitignore vue",
      "gitignore svelte",
      "gitignore electron",
      "gitignore wordpress",
      "gitignore jupyter",
      "gitignore latex",
      "gitignore android",
      "gitignore xcode",
      "gitignore intellij",
      "how to create a gitignore file",
      "gitignore best practices",
      "gitignore example",
      "gitignore cheat sheet",
      "gitignore merge templates",
      "combine gitignore files",
      "gitignore for monorepo",
      "gitignore full stack project",
      "gitignore node_modules",
      "gitignore env file",
      "should env be in gitignore",
      "gitignore already committed files",
      "git rm cached gitignore",
      "free gitignore tool",
      "online gitignore builder",
      "no signup gitignore generator",
      "gitignore download",
      "gitignore copy",
      "gitignore live preview",
      "gitignore for beginners",
      "what to put in gitignore",
      "gitignore vs git keep",
      "global gitignore",
      "gitignore patterns explained"
    ],
  };

export default seo;
