import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Glassmorphism Generator - Free Online Frosted Glass CSS Tool | IconVault",
    metaDescription: "Design frosted glass cards with blur, opacity, border and shadow sliders, preview over live gradients and copy the CSS. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Glassmorphism Generator** builds the **frosted glass** look visually. Drag sliders for **backdrop blur**, **background opacity**, **border width, color and opacity**, **border radius** and **shadow**, and watch the card update live over colorful **gradient backgrounds** (Sunset, Ocean, Candy, Forest).",
      "When it looks right, one click copies production-ready **CSS** with the **backdrop-filter** rule, the **-webkit-backdrop-filter** fallback for Safari, and your exact values. It is **free** with no signup and runs **fully in your browser**. The honest caveat: heavy blur values can cost performance on low-end phones, and always provide a readable fallback because backdrop-filter is unsupported in very old browsers."
    ],
    faqs: [
      { q: "What is glassmorphism?", a: "A UI style where elements look like frosted glass: a translucent background with a backdrop blur so content behind shows through softly, plus a subtle border and shadow." },
      { q: "What CSS does this generate?", a: "A background with RGBA, backdrop-filter: blur() plus the -webkit- prefixed fallback, border-radius, border and box-shadow. Paste it onto any div." },
      { q: "Does it work in all browsers?", a: "backdrop-filter works in all modern browsers including Safari (via the -webkit prefix, included automatically). Very old browsers ignore the blur and show a flat translucent box, so pick an opacity that stays readable without blur." },
      { q: "Can I change the background behind the card?", a: "Yes. Four built-in gradient backgrounds let you preview how the glass reads on light and dark scenes. The exported CSS is just the card; your own page is the backdrop." },
      { q: "Does blur hurt performance?", a: "Large blur radii over big areas can be expensive on low-end devices. Keep blur modest on mobile and avoid animating blurred elements." },
      { q: "Is this free to use in commercial projects?", a: "Yes. The CSS is yours to use anywhere, no attribution needed." }
    ],
    tags: [
      "glassmorphism generator",
      "glass morphism css generator",
      "frosted glass css",
      "glassmorphism css online",
      "glass card css generator",
      "backdrop filter generator",
      "glass effect css",
      "css glassmorphism tool",
      "glass ui generator",
      "frosted glass effect online",
      "glassmorphism design tool",
      "create glassmorphism css",
      "glassmorphism blur slider",
      "glass card design",
      "glassmorphism background",
      "glass panel css",
      "frosted glass card css",
      "glassmorphism codepen alternative",
      "css backdrop blur",
      "webkit backdrop filter",
      "glassmorphism landing page",
      "glass navbar css",
      "glass button css",
      "glassmorphism dashboard",
      "glassmorphism website design",
      "glass effect ui design",
      "frosted glass modal css",
      "glassmorphism tailwind",
      "glassmorphism react",
      "glassmorphism examples",
      "how to make glassmorphism css",
      "what is glassmorphism",
      "glassmorphism vs neumorphism",
      "glassmorphism color picker",
      "translucent card css",
      "blur background css card",
      "css glass card tutorial",
      "glassmorphism figma to css",
      "glassmorphism generator free",
      "online glass effect maker",
      "no signup css generator",
      "copy glassmorphism css",
      "glassmorphism css code snippet",
      "frosted glass overlay css",
      "glassmorphism opacity",
      "backdrop blur performance",
      "glassmorphism dark mode",
      "glassmorphism light mode",
      "glass card border glow",
      "glassmorphism box shadow"
    ],
  };

export default seo;
