import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Gradient Text - Free Online Gradient Text CSS Tool | IconVault",
    metaDescription: "Create gradient text with multi-stop color sliders, angle control, animated gradients and presets. Copy the CSS in one click. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Gradient Text** tool designs **gradient-filled headlines** visually. Add as many **color stops** as you like, drag each stop's position, set the **gradient angle**, adjust the **preview size**, and toggle an **animated gradient** that shifts colors with a smooth keyframe loop.",
      "It renders a live preview and generates the exact **CSS** using **background-clip: text** with the **-webkit-** fallback, including the animation code when you enable it. **One-click copy** drops it into your project. It is **free** with no signup and runs **fully in your browser**. The honest caveat: background-clip text needs transparent text color, which can hurt readability over busy backgrounds and is invisible in very old browsers, so keep a solid-color fallback."
    ],
    faqs: [
      { q: "How do I make gradient text with CSS?", a: "Apply a linear-gradient as the background, set background-clip: text with the -webkit- prefix, and make the text color transparent. This tool generates that CSS for you." },
      { q: "Can I use more than two colors?", a: "Yes. Add unlimited color stops, each with its own position slider, and presets like Sunset, Ocean, Candy and Neon give you starting points." },
      { q: "How does the animated gradient work?", a: "It sets background-size to 200% and animates background-position with keyframes, so the colors sweep across the text on a 4-second loop." },
      { q: "Does gradient text work in all browsers?", a: "The -webkit-background-clip: text technique works in all modern browsers. Very old browsers will show transparent text, which is why a fallback color is recommended." },
      { q: "Can I change the angle of the gradient?", a: "Yes, from 0 to 360 degrees, with a live preview of the direction." },
      { q: "Is the CSS free for commercial use?", a: "Yes. Use the generated code in any project, no attribution needed." }
    ],
    tags: [
      "gradient text generator",
      "gradient text css",
      "css gradient text",
      "gradient text online",
      "text gradient generator",
      "gradient font generator",
      "gradient headline generator",
      "colorful text css",
      "rainbow text generator",
      "gradient text effect",
      "animated gradient text",
      "gradient text animation css",
      "background clip text",
      "webkit background clip text",
      "gradient text maker",
      "gradient text tool",
      "gradient typography",
      "gradient text presets",
      "sunset gradient text",
      "neon gradient text",
      "multi color text css",
      "gradient text with angle",
      "linear gradient text",
      "css text effects",
      "fancy text css",
      "gradient text codepen",
      "gradient text tailwind",
      "gradient text react",
      "gradient text html",
      "how to make gradient text css",
      "gradient text tutorial",
      "gradient text for website",
      "gradient text for logo",
      "gradient text instagram",
      "gradient text canva alternative",
      "gradient lettering online",
      "gradient word art",
      "chrome text effect css",
      "metallic text gradient css",
      "gold gradient text css",
      "silver gradient text css",
      "purple gradient text",
      "blue gradient text",
      "pink gradient text",
      "gradient text generator free",
      "online gradient text maker",
      "no signup text generator",
      "copy gradient css",
      "gradient text code snippet",
      "gradient text readability",
      "gradient text accessibility",
      "gradient text fallback color"
    ],
  };

export default seo;
