import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Grade Calculator - Free Online Weighted Grade Tool | IconVault",
    metaDescription: "Calculate your weighted class grade from assignments and forecast what you need on the final exam to hit your target. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Grade Calculator** computes your **weighted course grade** from your assignments. Add rows with each **assignment's score, total points and weight**, and it instantly shows your current grade, how many items are counted and whether your weights add up.",
      "It also includes a **final exam forecaster**: enter the **final's weight** and your **target grade**, and it tells you exactly what score you need on the final, flagging when the target is already locked in or mathematically **out of reach**. It is **free** with no signup and runs **fully in your browser**, so your grades stay private. The honest caveat: it uses the simple weighted-average formula, so confirm with your syllabus if your class drops lowest scores or uses a curve."
    ],
    faqs: [
      { q: "How is a weighted grade calculated?", a: "Each assignment contributes (earned / possible) x weight. The sum of those contributions divided by the total weight, times 100, gives your percentage grade." },
      { q: "How does the final exam forecaster work?", a: "It takes your current weighted grade, the final's weight and your target grade, then solves for the final-exam score that gets you there." },
      { q: "What if I need more than 100% on the final?", a: "The tool says so plainly: your target is out of reach with the remaining weight, so lower the target or earn more points before the final." },
      { q: "Do my grades leave my device?", a: "No. Every calculation runs in your browser. Nothing is uploaded or stored." },
      { q: "Can I copy my grade breakdown?", a: "Yes. One click copies a text summary of every assignment, the current weighted grade and the final-exam forecast." },
      { q: "Does it handle dropped scores or curves?", a: "No. It is a straight weighted average. If your class drops the lowest quiz or applies a curve, adjust your inputs to match." }
    ],
    tags: [
      "grade calculator",
      "weighted grade calculator",
      "final grade calculator",
      "calculate my grade",
      "college grade calculator",
      "school grade calculator",
      "what do i need on the final",
      "final exam calculator",
      "grade calculator online",
      "semester grade calculator",
      "gpa vs grade calculator",
      "assignment grade calculator",
      "weighted average grade",
      "how to calculate weighted grade",
      "percentage grade calculator",
      "grade percentage calculator",
      "class grade calculator",
      "course grade calculator",
      "high school grade calculator",
      "university grade calculator",
      "points based grade calculator",
      "grade needed on final exam",
      "final exam grade needed calculator",
      "what grade do i need on my final to get an a",
      "target grade calculator",
      "grade forecaster",
      "grade projection calculator",
      "my current grade",
      "calculate current grade",
      "grade calculator with weights",
      "grade calculator free",
      "online grade calculator no signup",
      "grade calculator app alternative",
      "grade tracker",
      "gradebook calculator",
      "grade estimator",
      "what if grade calculator",
      "grade scenario calculator",
      "letter grade calculator",
      "a b c d f grade calculator",
      "grade scale calculator",
      "plus minus grading calculator",
      "gpa calculator",
      "cumulative grade calculator",
      "quarter grade calculator",
      "trimester grade calculator",
      "exam weight calculator",
      "test grade calculator",
      "quiz grade calculator",
      "homework grade calculator",
      "grade calculator for teachers",
      "student grade calculator",
      "grade calculator high school final"
    ],
  };

export default seo;
