import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Grafana Dashboard Generator - Free Online Dashboard JSON Tool | IconVault",
    metaDescription: "Build import-ready Grafana dashboard JSON visually: add timeseries, stat and gauge panels with PromQL queries, then copy or download. Free, in-browser.",
    about: [
      "**IconVault**'s **Grafana Dashboard Generator** builds **import-ready dashboard JSON** without hand-writing it. Set the **dashboard title and UID**, add **timeseries, stat and gauge panels**, and for each panel pick a **unit** (percent, bytes, reqps, ms) and write the **PromQL expression**. The tool assembles correct **gridPos layout**, **Prometheus datasource** blocks and field config automatically.",
      "You get a **live preview** of the dashboard JSON as you build, plus **copy and download** buttons. Import the file under Dashboards, New, Import in Grafana. It is **free** with no signup and runs **fully in your browser**. The honest caveat: the generator assumes a Prometheus datasource with the UID \"prometheus\", so update the datasource block if yours is named differently."
    ],
    faqs: [
      { q: "How do I import the generated JSON into Grafana?", a: "In Grafana go to Dashboards, New, Import, then paste the JSON or upload the downloaded file. The dashboard appears immediately." },
      { q: "Which panel types are supported?", a: "Timeseries, stat and gauge, the three most common monitoring panels. Each gets sensible default sizing and grid placement." },
      { q: "What units can I set?", a: "none, percent, percentunit, bytes, bytes per second, ms, seconds, ops, reqps and currency. Units control how Grafana formats the numbers." },
      { q: "Does it write the PromQL for me?", a: "No. You write the query per panel (for example rate(http_requests_total[5m])), and the tool handles the JSON structure, datasource wiring, layout and field config around it." },
      { q: "Which datasource does it assume?", a: "Prometheus with UID \"prometheus\". If your datasource has a different UID, edit the datasource blocks in the JSON after generating." },
      { q: "Is my dashboard data sent anywhere?", a: "No. Generation runs entirely in your browser; the tool never connects to your Grafana or Prometheus instance." }
    ],
    tags: [
      "grafana dashboard generator",
      "grafana json generator",
      "create grafana dashboard online",
      "grafana dashboard builder",
      "grafana dashboard json example",
      "import dashboard grafana",
      "grafana dashboard template",
      "prometheus grafana dashboard",
      "grafana panel json",
      "grafana timeseries panel json",
      "grafana stat panel json",
      "grafana gauge panel json",
      "grafana dashboard uid",
      "grafana schema version",
      "grafana gridpos",
      "grafana dashboard layout",
      "build grafana dashboard without ui",
      "grafana dashboard as code",
      "grafana json model",
      "grafana dashboard api import",
      "grafana provisioning dashboard",
      "grafana dashboard generator free",
      "online grafana dashboard builder",
      "grafana dashboard from promql",
      "promql dashboard generator",
      "rate http_requests_total dashboard",
      "grafana error rate panel",
      "grafana request rate dashboard",
      "grafana monitoring dashboard template",
      "grafana devops dashboard",
      "grafana sre dashboard",
      "kubernetes grafana dashboard json",
      "node exporter dashboard json",
      "grafana dashboard variables",
      "grafana dashboard tutorial",
      "how to create grafana dashboard",
      "grafana dashboard best practices",
      "grafana dashboard design",
      "grafana panel types",
      "timeseries vs stat grafana",
      "grafana units percent",
      "grafana field config unit",
      "grafana datasource uid prometheus",
      "grafana dashboard download json",
      "grafana import json file",
      "copy grafana dashboard json",
      "grafana dashboard generator no signup",
      "grafana dashboard quick start",
      "grafana dashboard json validator",
      "grafana dashboard json schema"
    ],
  };

export default seo;
