import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "GraphQL Studio - Free Online Schema Explorer & Mock Tool | IconVault",
    metaDescription: "Paste a GraphQL SDL schema, explore its types, build queries with a visual field picker and generate matching mock responses. Free, fully in-browser.",
    about: [
      "**IconVault**'s **GraphQL Studio** turns a raw **GraphQL SDL schema** into an interactive playground. Paste your schema and the studio parses every **type, enum, input, scalar, interface and union**, letting you browse fields, arguments and relationships in a clean **type explorer**.",
      "Then build queries with a **visual field picker** instead of writing them by hand, and generate a **realistic mock JSON response** that matches the query's shape, with sensible sample values per scalar. It is **free** with no signup and runs **fully in your browser**, nothing is uploaded. The honest caveat: the SDL parser handles standard schema syntax but not every exotic directive or extension, and mocks are fake data for testing, not a live server."
    ],
    faqs: [
      { q: "What can I paste into GraphQL Studio?", a: "Any GraphQL schema written in SDL (type Query { ... }, enums, inputs, unions). The tool parses it and lists every type and field." },
      { q: "How does the visual query builder work?", a: "Pick a root field from Query or Mutation, then tick the fields you want on each nested type. The studio assembles a valid query string as you go." },
      { q: "What are the mock responses for?", a: "Frontend development and testing. The tool generates JSON with realistic values (names, emails, IDs, booleans) shaped exactly like your query's response, so you can build UI without a running server." },
      { q: "Does it connect to my GraphQL server?", a: "No. It works from the schema text only. There is no network execution, no introspection query and no server required." },
      { q: "Is my schema uploaded?", a: "No. Parsing, query building and mock generation all run in your browser. Your schema never leaves your device." },
      { q: "Does it support subscriptions and directives?", a: "The parser focuses on types, fields, args, enums, inputs and unions. Custom directives are largely ignored, and subscriptions are not executable here since there is no server connection." }
    ],
    tags: [
      "graphql studio",
      "graphql schema explorer",
      "graphql playground online",
      "graphql query builder",
      "graphql mock generator",
      "graphql sdl parser",
      "graphql visual query builder",
      "graphql schema visualizer",
      "explore graphql schema",
      "graphql type explorer",
      "graphql mock data",
      "graphql fake data generator",
      "graphql response mock",
      "graphql query generator",
      "graphql ide online",
      "graphql editor online",
      "graphql tester",
      "graphql schema viewer",
      "graphql documentation generator",
      "graphql introspection alternative",
      "paste graphql schema",
      "graphql sdl online",
      "graphql union explorer",
      "graphql enum viewer",
      "graphql input type builder",
      "build graphql query visually",
      "graphql query builder free",
      "graphql frontend testing",
      "mock graphql api",
      "fake graphql server alternative",
      "graphql without server",
      "graphql ui development",
      "graphql sample responses",
      "graphql scalar mock values",
      "graphql code generator alternative",
      "graphql learning tool",
      "learn graphql online",
      "graphql tutorial tool",
      "graphql schema design",
      "graphql api design",
      "graphql developer tools",
      "graphql chrome extension alternative",
      "graphql client testing",
      "apollo client mock",
      "urql mock data",
      "relay mock graphql",
      "graphql query syntax checker",
      "graphql field picker",
      "graphql nested query builder",
      "graphql query string generator",
      "free graphql tools",
      "online graphql tools no signup",
      "graphql schema to json",
      "graphql json mock"
    ],
  };

export default seo;
