import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Grass Seed Calculator - Free Online Lawn Seed Tool | IconVault",
    metaDescription: "Work out how much grass seed your lawn needs by length x width or acres, for new lawns or overseeding, with bag counts. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Grass Seed Calculator** tells you exactly how much **grass seed** to buy. Enter your lawn by **length x width** or by **acres**, choose **new lawn** or **overseeding**, set your **seeding rate** in pounds per 1,000 sq ft, and pick a **bag size**.",
      "It instantly computes the **lawn area**, the **total pounds of seed** and how many **bags** that means, with a one-click **copy of the estimate**. New lawns default to 8 lbs per 1,000 sq ft and overseeding to 4, matching common guidance. It is **free** with no signup and runs **fully in your browser**. The honest caveat: rates vary by seed blend and region, so treat this as a planning estimate and check your seed bag's label before buying."
    ],
    faqs: [
      { q: "How much grass seed do I need per 1,000 sq ft?", a: "For new lawns, common rates are 6 to 10 lbs per 1,000 sq ft; for overseeding, 3 to 5 lbs. The tool defaults to 8 and 4 but lets you set any rate." },
      { q: "How do I measure my lawn area?", a: "Measure length times width in feet for rectangles, or enter acres directly (1 acre = 43,560 sq ft). For odd shapes, split the lawn into rectangles and add them up." },
      { q: "What is the difference between new lawn and overseeding?", a: "A new lawn starts from bare soil and needs a full rate. Overseeding thickens existing grass and uses about half the rate." },
      { q: "How many bags should I buy?", a: "The tool divides total pounds by your chosen bag size and rounds up, so you never come up short mid-lawn." },
      { q: "Does seed type change the rate?", a: "Yes. Kentucky bluegrass, fescue and ryegrass blends each have different recommended rates, which is why the tool lets you override the default." },
      { q: "Is this estimate exact?", a: "It is a planning estimate. Soil prep, spreader calibration and seed blend all affect real usage, so buy a small buffer and follow the label." }
    ],
    tags: [
      "grass seed calculator",
      "how much grass seed do i need",
      "lawn seed calculator",
      "grass seed per square foot",
      "grass seed coverage calculator",
      "grass seed for new lawn",
      "overseeding calculator",
      "how much seed to overseed lawn",
      "grass seed rate per 1000 sq ft",
      "pounds of grass seed per acre",
      "lawn area calculator",
      "square footage of lawn",
      "acres to square feet lawn",
      "new lawn seed amount",
      "grass seed bag calculator",
      "how many bags of grass seed",
      "50 lb bag grass seed coverage",
      "25 lb bag grass seed coverage",
      "grass seed calculator free",
      "online lawn calculator",
      "kentucky bluegrass seeding rate",
      "fescue seeding rate",
      "ryegrass seeding rate",
      "bermuda grass seed rate",
      "zoysia seed rate",
      "tall fescue overseeding rate",
      "grass seed for bare spots",
      "lawn renovation calculator",
      "seeding a new lawn guide",
      "how to seed a lawn",
      "best time to plant grass seed",
      "grass seed germination",
      "lawn care calculator",
      "yard size calculator",
      "lawn square footage calculator",
      "measure lawn for seed",
      "irregular lawn area calculator",
      "grass seed cost estimator",
      "how much does grass seed cost",
      "scotts grass seed coverage",
      "pennington grass seed rate",
      "grass seed spreader settings",
      "broadcast spreader seed rate",
      "lawn seeding tips",
      "overseeding lawn guide",
      "thicken lawn with seed",
      "fall overseeding calculator",
      "spring lawn seeding",
      "grass seed calculator app alternative",
      "lawn care tools online",
      "free lawn calculator"
    ],
  };

export default seo;
