import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Gzip Tool - Free Online Gzip Compressor Tool | IconVault",
    metaDescription: "Compress text or files to .gz and decompress gzip data back to text, with before/after sizes and ratio. Free, uses native browser compression.",
    about: [
      "**IconVault**'s **Gzip Tool** compresses and decompresses right in the tab. **Paste text** or **drop a file** to compress it with real **gzip** via the browser-native **CompressionStream API**, and see the **before and after sizes** plus the exact **compression ratio** before you download the **.gz** file or copy it as **base64**.",
      "Flip to the **decompress** tab to expand a **.gz file** or **base64 gzip data** back to text. It is **free** with no signup and runs **fully in your browser**, your files never leave your device. The honest caveat: compression uses your browser's built-in gzip, so very old browsers without CompressionStream cannot run it, and already-compressed files like JPEGs or ZIPs will barely shrink."
    ],
    faqs: [
      { q: "How do I compress text with gzip online?", a: "Paste the text, click Compress, and download the .gz file. The tool shows the original size, compressed size and ratio." },
      { q: "Can I compress a file?", a: "Yes. Drop any file into the upload zone and it compresses with gzip in your browser, with no upload to a server." },
      { q: "How do I decompress a .gz file?", a: "Switch to the decompress tab, drop the .gz file or paste base64-encoded gzip data, and the tool expands it back to text." },
      { q: "Why is my file barely smaller?", a: "Gzip shines on text: HTML, CSS, JS, JSON and logs. Media files like JPEG, MP4 or ZIP are already compressed and will not shrink much further." },
      { q: "Is my data sent to a server?", a: "No. Compression and decompression use the browser's native CompressionStream API. Everything stays on your device." },
      { q: "Which browsers support this?", a: "Any modern browser with CompressionStream support (Chrome, Edge, Firefox, Safari 16.4 and up). Older browsers show a clear error instead of failing silently." }
    ],
    tags: [
      "gzip tool",
      "gzip online",
      "gzip compressor online",
      "compress text gzip",
      "gzip file online",
      "create gz file online",
      "gzip decompress online",
      "ungzip online",
      "decompress gz file",
      "gzip base64",
      "gzip to text",
      "text to gzip",
      "gzip compression ratio",
      "gzip file size",
      "gzip compressor free",
      "online gzip utility",
      "no signup gzip tool",
      "gzip json online",
      "compress json gzip",
      "gzip html file",
      "gzip css file",
      "gzip javascript file",
      "gzip log file",
      "how to gzip a file",
      "how to create a gz file",
      "how to open gz file online",
      "extract gz online",
      "gz extractor",
      "gzip vs zip",
      "gzip vs brotli",
      "what is gzip compression",
      "gzip compression explained",
      "gzip for websites",
      "gzip text compression",
      "deflate vs gzip",
      "compressionstream api",
      "browser gzip compression",
      "client side gzip",
      "gzip without server",
      "gzip command line alternative",
      "tar gz online",
      "gzip tar file",
      "gzip download",
      "download gz file",
      "copy gzip base64",
      "base64 gzip decode",
      "gzip decode online",
      "gzip encoder",
      "gzip decoder",
      "gzip test file",
      "gzip benchmark",
      "gzip level",
      "gzip performance",
      "gzip online tool free",
      "gzip decompressor"
    ],
  };

export default seo;
