import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Heading Visualizer - Free Online H1-H6 Outline Tool | IconVault",
    metaDescription: "Paste HTML and see your H1-H6 headings as an indented tree. Flags skipped levels, multiple H1s and empty headings. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Heading Visualizer** shows your page the way **search engines and screen readers** see it. Paste **HTML** and it extracts every **H1-H6** tag into an **indented outline tree**, so a broken document structure is obvious at a glance.",
      "It automatically flags **SEO and accessibility issues**: **skipped heading levels** (jumping from H2 to H4), **multiple H1s**, an **H1 after other headings** and **empty headings** that screen readers announce with no name. You can **copy the outline** as plain text. It is **free** with no signup and runs **fully in your browser**. The honest caveat: it analyzes the HTML you paste, not your live site, so paste the rendered HTML (view source after JS runs) for single-page apps."
    ],
    faqs: [
      { q: "Why do heading levels matter for SEO?", a: "Headings form the page's outline. A clean H1-H6 hierarchy helps search engines understand sections and helps screen reader users navigate, which is why both flag broken structure." },
      { q: "How many H1 tags should a page have?", a: "Exactly one. It should be the page's main title and appear before any other heading." },
      { q: "What is a skipped heading level?", a: "Jumping from H2 straight to H4, for example. Levels should nest in order: H1, then H2, then H3 under each H2." },
      { q: "Why are empty headings a problem?", a: "A screen reader announces an empty heading as a heading with no name, which confuses users navigating by headings. Either add text or remove the tag." },
      { q: "Can I scan a live URL?", a: "No. The tool parses HTML you paste, locally, with nothing uploaded. For JavaScript-rendered pages, paste the HTML from the browser's rendered DOM, not the raw source." },
      { q: "Can I export the outline?", a: "Yes. One click copies the outline as indented text (using # marks per level) for docs or audits." }
    ],
    tags: [
      "heading visualizer",
      "html heading checker",
      "h1 h2 h3 checker",
      "heading outline tool",
      "heading structure analyzer",
      "seo heading checker",
      "heading hierarchy tool",
      "h1 checker online",
      "multiple h1 checker",
      "skipped heading level",
      "heading levels seo",
      "h1 h2 h3 seo best practices",
      "how many h1 per page",
      "heading outline generator",
      "html outline tool",
      "document outline viewer",
      "heading tree generator",
      "accessibility heading checker",
      "empty heading checker",
      "screen reader headings",
      "wcag headings",
      "semantic html checker",
      "html structure analyzer",
      "seo audit headings",
      "on page seo headings",
      "heading tag checker",
      "h1 tag checker",
      "h2 tag checker",
      "heading hierarchy checker",
      "heading order validator",
      "html5 outline",
      "heading map",
      "headingsmap alternative",
      "seo meta heading tool",
      "content structure analyzer",
      "blog heading structure",
      "article outline generator",
      "heading audit tool",
      "website heading analysis",
      "check headings on page",
      "view page headings",
      "extract headings from html",
      "list all headings html",
      "html h1-h6 extractor",
      "heading report",
      "free seo tools",
      "online seo checker no signup",
      "heading checker free",
      "technical seo headings",
      "heading best practices 2026"
    ],
  };

export default seo;
