import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "HEIC to JPG Converter - Free Online Tool | IconVault",
    metaDescription: "Convert HEIC photos to JPG in your browser, free and private. No uploads, bulk support, quality control included.",
    about: [
      "**IconVault**'s **HEIC to JPG Converter** turns Apple photos into universally compatible **JPG files** right in your browser. **HEIC** is the default on iPhones, but many websites and older apps still refuse it, so converting to **JPG** makes your photos usable everywhere. The tool is completely **free**, works with **bulk uploads**, and your photos **never leave your device**.",
      "You control the output with a **quality slider** (90% is the sweet spot for sharp photos) and a **background color** picker, since JPG has no transparency. Converted files download individually or as a handy **ZIP** when you convert several at once. **IconVault Pro** removes trial limits so you can convert entire photo libraries without waiting.",
    ],
    faqs: [
      { q: "Is the HEIC to JPG converter really free?", a: "Yes. You get a free trial quota every day, and IconVault Pro unlocks unlimited conversions with no waiting." },
      { q: "Do my photos get uploaded to a server?", a: "No. Every conversion happens locally in your browser, so your photos never leave your device." },
      { q: "Why convert HEIC to JPG?", a: "HEIC is Apple's efficient format, but many websites, editors and older devices only accept JPG. Converting makes your photos compatible everywhere." },
      { q: "What quality should I choose?", a: "90% is a good default: sharp photos with much smaller files. Lower it toward 70% for web use, raise it toward 100% for archiving." },
      { q: "What happens to transparency?", a: "JPG has no transparency, so any see-through areas are filled with the background color you pick, white by default." },
      { q: "Can I convert many HEIC files at once?", a: "Yes. Add as many files as you like and download them all at once as a ZIP file." },
    ],
    tags: ["heic to jpg", "heic converter", "convert heic to jpg", "heic to jpg online", "iphone photo converter", "heif to jpg", "heic to jpeg", "bulk heic converter", "heic to jpg free", "convert apple photos to jpg", "heic file converter", "heif converter", "jpg from heic", "heic to jpg batch", "iphone heic to jpg", "heic to jpg no signup", "heic to jpg private", "convert heic iphone", "heic to jpg quality", "heic download as jpg",
      "convert heic to jpg free",
      "heic to jpg online free",
      "heic to jpg without losing quality",
      "best heic to jpg converter",
      "heic to jpg converter online",
      "heic to jpg windows",
      "heic to jpg on mac",
      "heic to jpg android",
      "convert heic files to jpg",
      "change heic to jpg",
      "heic to jpg app",
      "heic to jpg ios",
      "convert heic photo to jpeg",
      "apple heic to jpg",
      "convert iphone photos to jpg",
      "how to convert heic to jpg",
      "heic to jpg converter free online",
      "heic to jpg no watermark",
      "heic to jpg large files",
      "heic to jpg high resolution",
      "convert heic to jpg in bulk",
      "multiple heic to jpg",
      "heic to jpg fast converter",
      "heic to jpg converter app",
      "heic to jpg for windows 10",
      "heic to jpg for windows 11",
      "open heic on windows as jpg",
      "convert heic to jpg without software",
      "heic to jpg browser tool",
      "heic to jpg free download",
      "heic to jpg image converter",
      "heic photo converter free",
      "convert .heic to .jpg",
      "heic extension to jpg",
      "why are my photos heic",
      "turn off heic iphone",
      "convert heic to jpg without losing metadata",
      "heic to jpg keep exif",
      "heic to jpg for printing",
      "heic to jpg email friendly"],
  };

export default seo;
