import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "HEIC to PNG Converter - Free Online Tool | IconVault",
    metaDescription: "Convert HEIC photos to lossless PNG in your browser. Free, private, no uploads, bulk conversion with ZIP download.",
    about: [
      "**IconVault**'s **HEIC to PNG Converter** turns iPhone **HEIC photos** into **lossless PNG files** with zero quality loss, entirely in your browser. PNG keeps every pixel exactly, which makes it ideal for editing, graphics and archival copies. The tool is completely **free**, supports **bulk uploads**, and your files **never leave your device**.",
      "There are no options to fiddle with: just drop your files and download. Multiple conversions are bundled into a **ZIP** automatically. **IconVault Pro** removes trial limits, so whole photo libraries convert in one sitting.",
    ],
    faqs: [
      { q: "Is the HEIC to PNG converter free?", a: "Yes, with a daily free quota. IconVault Pro removes the limit for unlimited conversions." },
      { q: "Are my photos uploaded anywhere?", a: "No. The conversion runs entirely in your browser, so your photos stay on your device." },
      { q: "Why choose PNG over JPG?", a: "PNG is lossless, so every pixel is kept exactly. Use it for editing, screenshots and graphics where quality matters most." },
      { q: "Will PNG files be larger than JPG?", a: "Usually yes. Lossless compression cannot shrink photos as much as JPG, so expect bigger files." },
      { q: "Does it keep transparency?", a: "PNG fully supports transparency, so any alpha in the source is preserved." },
      { q: "Can I convert many files at once?", a: "Yes. Add as many HEIC files as you like and download them all as a ZIP." },
    ],
    tags: ["heic to png", "convert heic to png", "heic converter png", "heif to png", "heic to png online", "iphone photo to png", "bulk heic to png", "heic to png free", "heif converter", "heic file to png", "convert apple photos png", "heic png no signup", "heic to lossless png", "heic to png batch", "iphone heic png", "heic to png private", "heif to png online", "png from heic", "heic converter free", "convert heic files",
      "convert heic to png free",
      "heic to png online free",
      "heic to png converter online",
      "best heic to png converter",
      "heic to png without losing quality",
      "heic to png windows",
      "heic to png on mac",
      "heic to png android",
      "convert heic files to png",
      "change heic to png",
      "heic to png app",
      "heic to png ios",
      "apple heic to png",
      "convert iphone photos to png",
      "how to convert heic to png",
      "heic to png converter free online",
      "heic to png no watermark",
      "heic to png high resolution",
      "convert heic to png in bulk",
      "multiple heic to png",
      "heic to png fast converter",
      "heic to png for windows 10",
      "heic to png for windows 11",
      "open heic on windows as png",
      "convert heic to png without software",
      "heic to png browser tool",
      "heic to png free download",
      "convert .heic to .png",
      "heic to png with transparency",
      "heic transparency to png",
      "convert heic to png for editing",
      "heic to png for photoshop",
      "heic to png keep exif",
      "heic to png image converter",
      "heic photo to png free",
      "heic to png email friendly",
      "convert heic to png for web",
      "heic to png for printing",
      "batch heic png converter",
      "heic to png no signup free"],
  };

export default seo;
