import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Hex Converter - Free Online Hex Encoding Tool | IconVault",
    metaDescription: "Convert text to hex and hex back to text in your browser, with uppercase/lowercase, 7 delimiter styles and a hex to ASCII table view. Free.",
    about: [
      "**IconVault**'s **Hex Converter** turns plain **text into hex bytes** and decodes **hex back to readable text**, using your browser's built-in encoders. Pick **uppercase or lowercase** digits and one of seven **delimiter styles**: none, spaces, colons, dashes, backslash-x escapes, 0x prefixes or commas, so the output matches exactly what your code, protocol or payload format expects.",
      "A third mode renders any hex dump as a classic **hex to ASCII table** with byte offsets, just like a hex editor, with 16 bytes per row and printable characters shown beside each row. The decoder is forgiving: paste hex with **0x prefixes, \\x escapes, spaces, colons or dashes** and it still parses, and it flags odd digit counts and invalid characters with a clear error instead of guessing. It is **free** to use with no signup, and everything runs **fully in your browser** so your data never leaves your device."
    ],
    faqs: [
      { q: "What is hex encoding used for?", a: "Hex represents binary data as printable text, two characters per byte. Developers use it to debug network protocols, inspect file contents, craft test payloads, check character encodings and move binary data through text-only channels." },
      { q: "Why does my hex fail to decode?", a: "The two usual causes are an odd number of digits (every byte needs two hex characters) and invalid characters outside 0-9 and A-F. This tool reports both problems explicitly instead of producing garbage output." },
      { q: "Does it handle Unicode and emoji?", a: "Yes. Text is encoded to its UTF-8 bytes first, so accented characters and emoji become their multi-byte hex sequences, and decoding reconstructs the original text exactly." },
      { q: "Is my data sent to a server?", a: "No. All conversion runs locally in your browser with the built-in TextEncoder and TextDecoder APIs. Nothing is uploaded, logged or stored." },
      { q: "What is the hex to ASCII table view?", a: "It renders a hex dump the way hex editors do: byte offsets on the left, 16 bytes per row in the middle, and the printable ASCII characters on the right, with dots for non-printable bytes." },
      { q: "Can it convert color codes like #FF5733?", a: "That is a different job: color hex is three color channels, not text bytes. Pasting a color code here would decode it as text bytes, which is not meaningful. Use a color picker or palette tool for colors." }
    ],
    tags: [
      "hex converter",
      "text to hex",
      "hex to text",
      "hex decoder",
      "hex encoder online",
      "convert text to hexadecimal",
      "string to hex converter",
      "hex to string converter",
      "hex to ascii",
      "ascii to hex",
      "hex to ascii table",
      "hex dump viewer",
      "hex code converter",
      "utf8 to hex",
      "hex to utf8",
      "text to hex with spaces",
      "hex with 0x prefix",
      "backslash x hex converter",
      "colon separated hex",
      "dash separated hex",
      "comma separated hex",
      "uppercase hex converter",
      "lowercase hex converter",
      "hex formatter",
      "format hex string",
      "hex string parser",
      "decode hex online",
      "encode text as hex",
      "hexadecimal converter",
      "hex to bytes",
      "bytes to hex",
      "hex byte viewer",
      "hex offset table",
      "hexdump online",
      "hexdump to text",
      "convert hexdump to ascii",
      "hex to readable text",
      "binary to hex",
      "hex to binary",
      "hex escape converter",
      "hex encode utf-8",
      "hex decode utf-8",
      "free hex converter",
      "hex converter no signup",
      "browser hex converter",
      "hex tool online",
      "hex conversion tool",
      "debug hex payload",
      "hex payload decoder",
      "hex string validator",
      "is my hex valid",
      "odd length hex error",
      "remove 0x from hex",
      "add 0x to hex",
      "hex delimiter converter",
      "hex to text no upload",
      "private hex converter"
    ],
  };

export default seo;
