import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "HMAC Generator - Free Online Signature Tool | IconVault",
    metaDescription: "Generate HMAC-SHA-256, SHA-384, SHA-512 and SHA-1 signatures with any secret key, in hex or Base64, and verify received tags. Free, in-browser.",
    about: [
      "**IconVault**'s **HMAC Generator** computes **Hash-based Message Authentication Codes** for any message and secret key, using your browser's **Web Crypto API**. Choose **HMAC-SHA-256, SHA-384, SHA-512 or SHA-1**, output the tag in **hex or Base64**, and use the built-in **compare mode** to check a received tag against the computed one, which is exactly how webhook signature verification works.",
      "HMAC proves a message came from someone holding the **secret key** and was not altered in transit, which is why APIs use it to sign requests and webhooks. It is **free** with no signup and runs **fully in your browser**, so your key and message never leave your device. The honest caveats: SHA-1 is included only for **legacy compatibility**, pick SHA-256 or better for new work, and never paste a real production secret into any web tool, including this one; it is built for testing and development."
    ],
    faqs: [
      { q: "What is HMAC?", a: "HMAC is a keyed hash: it combines a secret key with a hash function to produce a tag that proves both who sent a message and that it was not modified. Without the key, nobody can forge a valid tag." },
      { q: "How is HMAC different from a plain SHA-256 hash?", a: "A plain hash has no secret, so anyone can recompute it for a forged message. HMAC mixes in a secret key, so only key holders can produce or verify the tag, which is what makes it an authentication mechanism." },
      { q: "Which algorithm should I choose?", a: "HMAC-SHA-256 is the standard choice for new work, including most webhook signatures. SHA-512 is also fine. SHA-1 is listed only for verifying legacy systems; do not build anything new on it." },
      { q: "Is my secret key sent to a server?", a: "No. The HMAC is computed locally with the Web Crypto API. Your message and key never leave your browser." },
      { q: "How do I verify a webhook signature?", a: "Paste the raw webhook body as the message, enter the signing secret from your provider, pick the algorithm they use, then paste the signature they sent into the compare field. A match means the webhook is authentic." },
      { q: "Why does my tag not match the one from my backend?", a: "The usual causes are a different algorithm, a different output encoding (hex vs Base64), extra whitespace or newlines in the message, or the key being used in a different form. Make all four identical on both sides." }
    ],
    tags: [
      "hmac generator",
      "hmac sha256 online",
      "hmac sha512",
      "hmac sha384",
      "hmac sha1",
      "compute hmac",
      "verify hmac",
      "hmac calculator",
      "message authentication code",
      "hmac online tool",
      "webhook signature verifier",
      "api signature generator",
      "hmac secret key",
      "hmac hex",
      "hmac base64",
      "sha256 hmac generator",
      "sha512 hmac online",
      "sign message with secret",
      "verify webhook signature",
      "github webhook hmac",
      "stripe signature verify",
      "hmac vs hash",
      "what is hmac",
      "hmac explained",
      "hmac authentication",
      "hmac test vector",
      "generate mac",
      "keyed hash",
      "webcrypto hmac",
      "browser hmac",
      "free hmac tool",
      "hmac generator no signup",
      "hmac signature online",
      "hmac digest calculator",
      "hmac for api auth",
      "aws signature hmac",
      "hmac sha256 javascript",
      "compare hmac tags",
      "hmac validation tool",
      "check hmac signature",
      "hmac token generator",
      "hmac online free",
      "hmac code generator",
      "keyed hash function",
      "hmac message signing",
      "hmac webhook secret",
      "verify signed request",
      "hmac tag compare",
      "rfc 2104 hmac",
      "hmac hex vs base64",
      "generate webhook signature",
      "test hmac implementation",
      "hmac for developers",
      "secure message signing"
    ],
  };

export default seo;
