import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Hreflang Generator - Free Online SEO Tags Tool | IconVault",
    metaDescription: "Build valid hreflang link tags for multilingual sites: language and region codes, x-default fallback, per-page URLs. Copy-ready HTML, free.",
    about: [
      "**IconVault**'s **Hreflang Generator** builds the **hreflang link tags** that tell Google which **language and region version** of a page to show each searcher. Add your **language-region pairs** like en-US or fr-CA with their page URLs, set an **x-default fallback** for unmatched visitors, and get copy-ready <link rel=\"alternate\" hreflang=\"...\"> tags to paste into your page head.",
      "Getting hreflang wrong is one of the most common **international SEO** mistakes: wrong codes, missing self-references and one-way tags all silently break it. This tool formats every tag to the correct **ISO language and region code** syntax so you can avoid those errors. It is **free** with no signup and runs **fully in your browser**. The honest note: hreflang is a signal, not a ranking boost, and every language version should link back to all the others, including itself."
    ],
    faqs: [
      { q: "What is hreflang?", a: "Hreflang is an HTML link tag that tells search engines which language and regional version of a page to show a searcher. Without it, Google may show the wrong language version or treat translated pages as duplicates." },
      { q: "Do I need an x-default tag?", a: "It is strongly recommended. x-default points to the fallback page for visitors whose language or region matches none of your versions, such as a language selector or your main English page." },
      { q: "What is the difference between language and region codes?", a: "The language code (ISO 639-1, e.g. en, fr) is required; the region code (ISO 3166-1 alpha-2, e.g. US, CA) is optional and narrows it further. Use en for all English speakers or en-US for the US-specific version." },
      { q: "Where do I put hreflang tags?", a: "In the <head> of every language version of the page, including a self-referencing tag. Alternatively they can live in an XML sitemap or HTTP headers, but head tags are the most common approach." },
      { q: "What is the most common hreflang mistake?", a: "One-way tagging: page A links to page B, but page B does not link back. Hreflang must be reciprocal across all versions, and each page must also reference itself, or search engines ignore the whole cluster." },
      { q: "Does hreflang improve my rankings?", a: "Not directly. It does not boost rankings; it makes sure the right language version appears for the right searcher, which fixes wrong-language results and duplicate content issues between translations." }
    ],
    tags: [
      "hreflang generator",
      "hreflang tags generator",
      "generate hreflang tags",
      "hreflang tag builder",
      "multilingual seo hreflang",
      "hreflang link tags",
      "x-default generator",
      "hreflang x-default",
      "language region codes",
      "iso 639-1 list",
      "hreflang en-us",
      "hreflang example",
      "hreflang html tags",
      "alternate hreflang",
      "hreflang implementation",
      "hreflang validator",
      "hreflang checker",
      "hreflang mistakes",
      "hreflang reciprocal",
      "hreflang sitemap vs html",
      "add hreflang to website",
      "hreflang wordpress",
      "hreflang for multilingual site",
      "international seo tool",
      "hreflang tag format",
      "hreflang syntax",
      "hreflang language codes list",
      "hreflang region codes",
      "hreflang best practices",
      "what is hreflang",
      "how to add hreflang tags",
      "hreflang canonical relationship",
      "self referencing hreflang",
      "hreflang seo guide",
      "free hreflang generator",
      "hreflang generator online",
      "hreflang tool no signup",
      "browser hreflang builder",
      "hreflang tags copy paste",
      "multiple languages seo tags",
      "hreflang fr-ca example",
      "hreflang de-at",
      "hreflang es-mx",
      "hreflang pt-br",
      "hreflang ar",
      "hreflang for shopify",
      "hreflang for ecommerce",
      "hreflang language selector",
      "hreflang duplicate content",
      "hreflang country targeting",
      "hreflang link element",
      "generate alternate links",
      "seo hreflang tool"
    ],
  };

export default seo;
