import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "htaccess Generator - Free Online Apache Config Tool | IconVault",
    metaDescription: "Build a production .htaccess visually: HTTPS and www redirects, gzip, browser caching, security headers, error pages, rewrites. Free.",
    about: [
      "**IconVault**'s **htaccess Generator** builds a complete, production-ready **.htaccess file** through toggles instead of memorized Apache syntax. Turn on **HTTPS redirects**, **www to non-www** (or the reverse), **gzip compression**, **browser caching** with Expires headers for assets, **security headers** like HSTS and X-Frame-Options, **custom error pages**, **directory listing** control, **hotlink protection** for images and your own **rewrite rules**, with a live preview of the file as you configure it.",
      "Copy the result or download it straight to your server directory. It is **free** with no signup and runs **fully in your browser**, so nothing is uploaded. The honest caveats: .htaccess is **Apache only** and does nothing on Nginx or LiteSpeed-without-support; some shared hosts disable certain directives, so test the file on staging first; and the tool cannot see your existing .htaccess, so merge its output with rules you already have instead of overwriting them."
    ],
    faqs: [
      { q: "What is an .htaccess file?", a: "It is a per-directory configuration file for Apache web servers. It controls redirects, compression, caching, security headers, error pages and URL rewrites without needing access to the main server configuration." },
      { q: "Will this work on my hosting?", a: "It works on Apache and hosts that allow .htaccess overrides. It does not work on Nginx, which uses a different configuration system. Check with your host if you are unsure which server software you run." },
      { q: "How do I force HTTPS with .htaccess?", a: "Enable the HTTPS redirect toggle. The tool generates a rewrite rule that 301-redirects every HTTP request to its HTTPS equivalent, which also helps SEO by consolidating your URLs on the secure version." },
      { q: "What about my existing .htaccess rules?", a: "The generator builds a fresh file from the options you pick; it cannot read what is already on your server. Copy your current file first, then add the new rules to it or merge the two before uploading." },
      { q: "What security headers does it add?", a: "Options include Strict-Transport-Security (HSTS), X-Frame-Options to block clickjacking, X-Content-Type-Options, Referrer-Policy and a basic Content-Security-Policy, all of which harden the site against common browser-based attacks." },
      { q: "How does the browser caching section help?", a: "It sets far-future Expires headers by file type for CSS, JavaScript, images and fonts, so returning visitors reuse cached files instead of downloading them again, which speeds up repeat page loads." }
    ],
    tags: [
      "htaccess generator",
      "htaccess builder",
      "generate htaccess",
      "apache htaccess generator",
      "htaccess redirect generator",
      "https redirect htaccess",
      "www redirect htaccess",
      "force https htaccess",
      "htaccess www to non www",
      "gzip htaccess",
      "enable gzip htaccess",
      "browser caching htaccess",
      "expires headers htaccess",
      "security headers htaccess",
      "hsts htaccess",
      "x-frame-options htaccess",
      "content security policy htaccess",
      "custom error pages htaccess",
      "404 page htaccess",
      "disable directory listing htaccess",
      "hotlink protection htaccess",
      "prevent image hotlinking",
      "rewrite rules generator",
      "htaccess rewrite generator",
      "redirect 301 htaccess",
      "htaccess redirect examples",
      "htaccess cheat sheet",
      "apache config generator",
      "htaccess file creator",
      "create htaccess online",
      "htaccess for wordpress",
      "htaccess seo",
      "htaccess performance",
      "htaccess security",
      "free htaccess tool",
      "htaccess generator no signup",
      "htaccess snippets",
      "common htaccess rules",
      "htaccess redirect http to https",
      "htaccess force www",
      "htaccess remove www",
      "htaccess trailing slash",
      "htaccess file download",
      "htaccess expiresbytype",
      "htaccess deflate",
      "htaccess cache control",
      "htaccess visual builder",
      "htaccess online editor",
      "build htaccess file",
      "htaccess tester",
      "htaccess for apache",
      "htaccess redirect www",
      "htaccess compression"
    ],
  };

export default seo;
