import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "HTML Entities - Free Online Character Encoder Tool | IconVault",
    metaDescription: "Encode text to HTML entities and decode entities back, with a searchable 250-entry reference. Named and numeric entities. Free, in-browser.",
    about: [
      "**IconVault**'s **HTML Entities** tool encodes text into **HTML entities** and decodes entities back to characters, instantly. Paste anything with **special characters**, symbols or markup and get properly encoded output using **named entities** like &amp;amp;, decimal codes like &amp;#169; or hex codes like &amp;#xA9;, or reverse the process to turn entity soup back into readable text.",
      "It also includes a **searchable 250-entry reference** of the entities developers actually reach for: punctuation, quotes, currency, math, arrows and accented letters. Encoding special characters correctly keeps your **markup valid** and text displaying as intended instead of breaking tags. It is **free** with no signup and runs **fully in your browser**. The honest note: entity encoding is one layer of output safety, not a complete XSS defense on its own."
    ],
    faqs: [
      { q: "What are HTML entities?", a: "They are codes that represent special characters in HTML, like &amp; for an ampersand or &copy; for the copyright symbol. They let you display characters that would otherwise be interpreted as markup or that are hard to type." },
      { q: "When should I encode text as entities?", a: "Whenever text contains <, > or & that should display literally rather than act as markup, and for characters outside your page encoding. Encoding user content before inserting it into HTML also reduces injection risks." },
      { q: "What is the difference between named and numeric entities?", a: "Named entities like &euro; are readable; numeric ones like &#8364; or &#x20AC; address the character by its Unicode code point. Both render identically, so pick whichever your workflow prefers." },
      { q: "Does entity encoding prevent XSS?", a: "It helps: encoding output stops injected tags from being parsed as HTML. But real XSS defense also needs context-aware escaping (attributes, JavaScript, URLs), input validation and a Content-Security-Policy, so do not rely on encoding alone." },
      { q: "How many entities are in the reference?", a: "250 entries covering the symbols developers use most: punctuation, quotes, dashes, currency, math operators, arrows, fractions and accented Latin letters. Use the search box to find one by name or appearance." },
      { q: "Is my text sent to a server?", a: "No. Encoding, decoding and the reference search all run locally in your browser. Nothing is uploaded or stored." }
    ],
    tags: [
      "html entities",
      "html entity encoder",
      "html entity decoder",
      "html entities list",
      "html entity converter",
      "encode html entities",
      "decode html entities",
      "html special characters",
      "html character codes",
      "html entities reference",
      "html symbol codes",
      "named html entities",
      "numeric html entities",
      "html entity chart",
      "html entity lookup",
      "search html entities",
      "amp entity html",
      "lt gt entities",
      "nbsp entity",
      "copy entity html",
      "reg entity html",
      "euro entity html",
      "html escape",
      "escape html online",
      "unescape html",
      "html escape tool",
      "encode special characters html",
      "html encode online",
      "html decode online",
      "convert to html entities",
      "html entities cheat sheet",
      "html entity codes list",
      "250 html entities",
      "html character entity reference",
      "html entities for symbols",
      "html entities for accents",
      "html entities for arrows",
      "html entities for math symbols",
      "html entities for currency",
      "copyright symbol html",
      "trademark symbol html",
      "registered symbol html",
      "euro symbol html",
      "pound symbol html",
      "yen symbol html",
      "degree symbol html",
      "html space entity",
      "html quote entity",
      "apostrophe html entity",
      "less than greater than html",
      "ampersand html entity",
      "free html entity tool",
      "html entities no signup",
      "browser html encoder",
      "html entities tool online"
    ],
  };

export default seo;
