import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "HTML Minifier - Free Online Code Optimizer Tool | IconVault",
    metaDescription: "Minify HTML in your browser: strip comments, collapse whitespace, drop optional quotes, shrink inline CSS and JS. Preserves pre and code blocks.",
    about: [
      "**IconVault**'s **HTML Minifier** shrinks your markup by stripping **comments**, collapsing **whitespace**, removing **optional quotes** and applying basic minification to **inline CSS and JavaScript**. Paste your HTML, tune the options, and copy the compact output, with before-and-after sizes so you can see exactly how many bytes you saved.",
      "Smaller HTML means **faster page loads** and less bandwidth, especially on large templates. Content inside **<pre>, <textarea>, <script> and <style>** is always preserved, so code samples and scripts survive minification untouched. It is **free** with no signup and runs **fully in your browser**. The honest note: always test the minified page before deploying, because aggressive whitespace removal can change rendering where spacing is significant."
    ],
    faqs: [
      { q: "What is HTML minification?", a: "It removes everything browsers do not need to render the page: comments, extra whitespace, redundant attributes and optional quotes, plus it compresses inline styles and scripts. The page looks identical but the file is smaller." },
      { q: "How much smaller will my HTML get?", a: "It depends on the source. Heavily commented, indented templates often shrink 20 to 40 percent; already-tight markup shrinks less. The tool shows the exact byte savings for your input." },
      { q: "Will minification break my page?", a: "It should not, when whitespace handling is conservative. Risky spots are inline elements separated by meaningful spaces and <pre> content, which this tool preserves. Always test the minified version in a browser before shipping." },
      { q: "Does it minify CSS and JavaScript inside the HTML?", a: "Yes, at a basic level: inline <style> blocks and <script> blocks get whitespace and comment reduction. For heavy JavaScript, a dedicated JS minifier does a better job." },
      { q: "Is minifying better than gzip?", a: "They stack. Gzip compresses whatever you send, including minified HTML, so minify first and let gzip compress the result. Doing both gives the smallest possible transfer size." },
      { q: "Is my HTML uploaded anywhere?", a: "No. Minification runs entirely in your browser. Your code never leaves your device." }
    ],
    tags: [
      "html minifier",
      "minify html",
      "html minifier online",
      "compress html",
      "html compressor",
      "reduce html size",
      "minify html code",
      "html optimizer",
      "optimize html",
      "html minification tool",
      "strip html comments",
      "remove html whitespace",
      "collapse whitespace html",
      "remove optional quotes html",
      "inline css minifier",
      "inline js minifier",
      "html size reducer",
      "shrink html file",
      "html minify free",
      "html minifier no signup",
      "minify html browser",
      "html performance tool",
      "faster page load html",
      "html minifier with stats",
      "before after size html",
      "html minifier safe",
      "minify html without breaking",
      "preserve pre tag minify",
      "html minify pre textarea",
      "html minifier for production",
      "html minifier for email",
      "minify html email",
      "html minifier tool online",
      "best html minifier",
      "free html minifier",
      "html code shrinker",
      "html whitespace remover",
      "html comment remover",
      "html minify css js",
      "html minifier download",
      "copy minified html",
      "html minification explained",
      "why minify html",
      "does minifying html help seo",
      "minify vs gzip html",
      "html minifier online free",
      "html minify tool",
      "reduce page size html",
      "html minifier for developers",
      "minify html template",
      "html minify options",
      "safe html minifier"
    ],
  };

export default seo;
