import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "HTML to JSX - Free Online React Converter Tool | IconVault",
    metaDescription: "Convert HTML markup to React JSX: class becomes className, style strings to objects, comments and self-closing tags handled. Free, in-browser.",
    about: [
      "**IconVault**'s **HTML to JSX** converter turns ordinary **HTML markup into React-ready JSX**. Paste a snippet from a template, a design export or Stack Overflow, and get JSX where **class becomes className**, **for becomes htmlFor**, **style attributes become style objects**, HTML comments become **JSX comments**, and void elements like <br> and <img> are properly **self-closed**.",
      "It is the fastest way to drop existing HTML into a **React or Next.js component** without rewriting every attribute by hand. It is **free** with no signup and runs **fully in your browser**. The honest note: it converts markup faithfully, but review the result before pasting: inline event handlers, custom data flows and framework-specific attributes still need your judgment."
    ],
    faqs: [
      { q: "What is JSX?", a: "JSX is a syntax extension for JavaScript used by React that lets you write HTML-like markup inside your code. It looks like HTML but follows JavaScript rules, which is why attributes like class have different names." },
      { q: "Why does class become className?", a: "Because class is a reserved word in JavaScript. JSX renames it to className, and similarly for becomes htmlFor, to avoid clashing with the language's keywords." },
      { q: "How are style attributes converted?", a: "Inline style strings like style=\"color: red; margin-top: 8px\" become JSX style objects like style={{color: 'red', marginTop: '8px'}}, with hyphenated CSS properties converted to camelCase." },
      { q: "What happens to onclick handlers?", a: "HTML event attributes do not map directly to React's synthetic event system, so the converter flags them for manual review. You will need to rewrite them as React handlers like onClick with your own functions." },
      { q: "Does it handle SVG?", a: "SVG markup converts, but SVG attribute names in JSX are camelCase (strokeWidth, viewBox stays as-is in React 16+). Double-check SVG attributes in the output, since they are the most common source of warnings." },
      { q: "Can I convert a whole page?", a: "You can, but the output is best treated as a starting point. Large pages usually need splitting into components, plus manual work on scripts, forms and interactive behavior that HTML alone cannot express." }
    ],
    tags: [
      "html to jsx",
      "convert html to jsx",
      "html to jsx converter",
      "html to jsx online",
      "jsx converter",
      "html to react",
      "convert html to react component",
      "html to react jsx",
      "class to className",
      "htmlfor jsx",
      "style to jsx object",
      "jsx style object converter",
      "html comments to jsx",
      "self closing tags jsx",
      "paste html into react",
      "html snippet to jsx",
      "free html to jsx",
      "html to jsx no signup",
      "html to jsx browser",
      "react converter tool",
      "jsx transform",
      "html to jsx for nextjs",
      "nextjs html to jsx",
      "convert template to jsx",
      "bootstrap html to jsx",
      "tailwind html to jsx",
      "html to tsx",
      "convert html to tsx",
      "html attributes to jsx props",
      "jsx attribute converter",
      "react props from html",
      "html to jsx explained",
      "jsx vs html differences",
      "jsx syntax converter",
      "online jsx tool",
      "jsx code generator",
      "html to jsx copy paste",
      "quick html to jsx",
      "html to jsx with styles",
      "inline styles jsx converter",
      "html to jsx camelcase",
      "jsx className converter",
      "convert html for react",
      "html to react online free",
      "jsx markup converter",
      "react snippet converter",
      "html to jsx tool",
      "html to jsx free online",
      "design to react jsx",
      "html template to react",
      "jsx output generator",
      "html to jsx no login"
    ],
  };

export default seo;
