import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "HTTP Status Codes - Free Online HTTP Status Code Reference | IconVault",
    metaDescription: "Look up any HTTP status code: 200, 301, 404, 500 and more, with plain-English meanings and when each appears. Free reference in your browser.",
    about: [
      "**IconVault**'s **HTTP Status Codes** is a searchable reference of every **HTTP status code**, from 100 Continue to 511 Network Authentication Required. Search by code or keyword, filter by class (**1xx** informational, **2xx** success, **3xx** redirection, **4xx** client error, **5xx** server error), and get a **plain-English explanation** of what each code means and when servers send it.",
      "It runs **fully in your browser** with **no signup** and is **free** to use, handy whether you are debugging a failing API call, writing error handling, or studying for an exam. Honest note: it is a reference guide, not a live checker; the exact behavior of a code can vary slightly between servers and frameworks."
    ],
    faqs: [
      { q: "What are HTTP status codes?", a: "Three-digit numbers a server returns with every HTTP response to say what happened: 2xx means success, 3xx means redirection, 4xx means the client made an error, and 5xx means the server failed." },
      { q: "How do I look up a code?", a: "Type the number (for example 418) or a keyword (for example redirect) into the search box, or filter by the 1xx through 5xx classes." },
      { q: "What is the difference between 401 and 403?", a: "401 Unauthorized means authentication is missing or invalid, so try logging in. 403 Forbidden means the server understood your credentials but still refuses; you do not have permission." },
      { q: "What is the difference between 301 and 302?", a: "301 Moved Permanently tells clients and search engines the URL has moved for good and to update bookmarks and indexes. 302 Found is a temporary redirect." },
      { q: "What does 429 mean?", a: "429 Too Many Requests means you hit the server's rate limit. Slow down, respect the Retry-After header if present, and retry later." },
      { q: "What is status code 418?", a: "418 I'm a teapot is an April Fools' joke from RFC 2324 (Hyper Text Coffee Pot Control Protocol) that stuck around as a real, if rarely used, code." }
    ],
    tags: [
      "http status codes",
      "http status code list",
      "http status codes explained",
      "http status code reference",
      "http response codes",
      "http status 200",
      "http status 404",
      "http status 500",
      "what does 404 mean",
      "what does 500 mean",
      "301 vs 302",
      "401 vs 403",
      "400 bad request meaning",
      "403 forbidden meaning",
      "404 not found meaning",
      "429 too many requests",
      "503 service unavailable",
      "418 i'm a teapot",
      "http 1xx codes list",
      "http 2xx codes list",
      "http 3xx codes list",
      "http 4xx codes list",
      "http 5xx codes list",
      "informational responses http",
      "success status codes",
      "redirection status codes",
      "client error codes",
      "server error codes",
      "http status code cheat sheet",
      "http codes for developers",
      "rest api status codes",
      "which status code for not found",
      "which status code for validation error",
      "200 ok meaning",
      "201 created meaning",
      "204 no content meaning",
      "301 moved permanently",
      "302 found redirect",
      "304 not modified meaning",
      "400 vs 422",
      "422 unprocessable entity",
      "502 bad gateway meaning",
      "504 gateway timeout",
      "http status code lookup",
      "search http status codes",
      "http status code meaning table",
      "common http errors explained",
      "website error codes list",
      "api error codes explained",
      "debugging http errors",
      "http response status explained",
      "101 switching protocols",
      "100 continue meaning",
      "learn http status codes",
      "http status codes interview questions",
      "http status codes for beginners",
      "511 network authentication required"
    ],
  };

export default seo;
