import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Header Analyzer - Free Online HTTP Security Header Tool | IconVault",
    metaDescription: "Paste raw HTTP response headers or fetch a URL to check security headers like HSTS, CSP and X-Frame-Options. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Header Analyzer** turns raw **HTTP response headers** into a clean, readable table plus an automatic **security header audit**. Paste a captured header block, or fetch a URL and inspect the headers the browser actually exposes. Parsing and analysis are 100% client-side.",
      "It flags the headers that matter for **web security**: **Strict-Transport-Security (HSTS)**, **Content-Security-Policy**, **X-Frame-Options**, **X-Content-Type-Options**, **Referrer-Policy**, **Permissions-Policy** and cookie flags like **Secure**, **HttpOnly** and **SameSite**. It is **free** with **no signup** and nothing leaves your device. Honest note: the browser only exposes headers that CORS allows, so a cross-origin fetch may show fewer headers than a full raw paste from DevTools or curl."
    ],
    faqs: [
      { q: "How do I use the Header Analyzer?", a: "Paste a raw HTTP response header block into the input, or enter a URL and fetch it. The tool parses every header into a table and runs a security check against the headers that matter most: HSTS, CSP, X-Frame-Options, nosniff, Referrer-Policy, Permissions-Policy and cookie flags." },
      { q: "Is my data sent to a server?", a: "No. Parsing and analysis happen entirely in your browser. Headers you paste never leave your device." },
      { q: "Why do fewer headers show when I fetch a URL instead of pasting?", a: "Browsers only expose response headers that CORS permits. Cross-origin fetches return a reduced set, so for a full audit paste the raw headers captured from DevTools or curl." },
      { q: "What security headers does it check?", a: "Strict-Transport-Security, Content-Security-Policy, X-Frame-Options (or CSP frame-ancestors), X-Content-Type-Options, Referrer-Policy, Permissions-Policy, and the Secure, HttpOnly and SameSite flags on Set-Cookie headers." },
      { q: "What does a missing HSTS warning mean?", a: "It means the site does not force browsers to use HTTPS only, so visitors can still be downgraded to plain HTTP. Adding a Strict-Transport-Security header with a long max-age fixes it." },
      { q: "Can I analyze request headers too?", a: "The tool is built for response headers, but the parser accepts any Name: Value lines, so you can paste request headers to get them tabulated. The security audit findings are only meaningful for responses." }
    ],
    tags: [
      "http header analyzer",
      "analyze http headers",
      "check http headers",
      "http response headers check",
      "view http headers online",
      "inspect http response headers",
      "http headers analyzer online free",
      "security headers check",
      "check security headers of a website",
      "http security headers analyzer",
      "missing security headers checker",
      "hsts checker",
      "csp checker",
      "content security policy checker",
      "x-frame-options checker",
      "strict transport security test",
      "check website response headers",
      "view response headers of url",
      "fetch http headers online",
      "curl headers online",
      "http headers lookup",
      "list http response headers",
      "parse http headers",
      "raw http headers parser",
      "http header parser online",
      "check server headers online",
      "server response headers checker",
      "detect missing csp header",
      "check nosniff header",
      "referrer policy checker",
      "permissions policy checker",
      "set cookie flags checker",
      "secure httponly samesite checker",
      "website security headers test",
      "online security header audit",
      "http header security score",
      "owasp security headers check",
      "web server headers analyzer",
      "check caching headers",
      "cache control header checker",
      "etag header checker",
      "check cors headers online",
      "access control allow origin checker",
      "check content type header",
      "x content type options test",
      "clickjacking protection checker",
      "frame ancestors checker",
      "how to check http response headers",
      "how to view response headers in chrome",
      "what are http security headers",
      "why is hsts important",
      "http headers explained",
      "response header names list",
      "common http response headers",
      "test website headers free",
      "free http header tool no signup"
    ],
  };

export default seo;
