import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Header Builder - Free Online HTTP Request Header Tool | IconVault",
    metaDescription: "Build raw HTTP request headers from common presets and custom fields, with name validation and one-click copy. Free, fully in your browser.",
    about: [
      "**IconVault**'s **Header Builder** helps you compose raw **HTTP request headers** without typos. Pick from common presets like **Authorization**, **Content-Type**, **Accept**, **Cache-Control**, **Origin** and **If-None-Match**, add your own **custom fields**, and copy the finished block straight into curl, Postman, Insomnia or your API client.",
      "Every header **name is validated** as you type, so malformed names are caught before they ever reach your request. It is **free**, needs **no signup**, and everything runs **in your browser**, so tokens and API keys you type never leave your device. Honest note: it builds the header block; it does not send the request, which keeps your credentials local."
    ],
    faqs: [
      { q: "What is the Header Builder for?", a: "For composing the raw header block of an HTTP request, for example Authorization: Bearer <token> plus Content-Type: application/json, then pasting it into curl, Postman, Insomnia or a fetch call." },
      { q: "Which preset headers are included?", a: "Accept, Accept-Language, Accept-Encoding, Authorization, Cache-Control, Connection, Content-Type, Content-Length, Cookie, Host, User-Agent, Referer, Origin, If-None-Match, If-Modified-Since, Range, X-Requested-With, X-Api-Key, X-Request-Id, X-Forwarded-For and DNT." },
      { q: "Can I add my own custom headers?", a: "Yes. Add any custom header name and value; the tool validates the name format and includes it in the copied block." },
      { q: "Is my API key sent anywhere?", a: "No. The builder only assembles text in your browser. Nothing is transmitted until you paste the block into your own client." },
      { q: "Does it validate header names?", a: "Yes. Header names are checked against the allowed token characters, so spaces or invalid characters are flagged before you copy." },
      { q: "Can I use it for response headers?", a: "It is designed for request headers, but nothing stops you from typing response-style headers; the output is just a raw text block you can paste anywhere." }
    ],
    tags: [
      "http header builder",
      "build http headers",
      "http request header builder",
      "create http headers online",
      "http header generator",
      "request headers generator",
      "api header builder",
      "http headers for curl",
      "build headers for postman",
      "authorization header generator",
      "bearer token header format",
      "content type header examples",
      "custom http header creator",
      "http header presets",
      "common http request headers list",
      "http request headers explained",
      "how to add headers to curl request",
      "curl with custom headers example",
      "postman headers how to add",
      "fetch api headers example",
      "javascript fetch custom headers",
      "axios headers example",
      "http header name validation",
      "valid http header name characters",
      "http header format name colon value",
      "raw http request example",
      "raw http headers block",
      "copy http headers template",
      "http headers cheat sheet",
      "api request headers list",
      "rest api headers examples",
      "x-api-key header example",
      "x-request-id header purpose",
      "if-none-match header example",
      "if-modified-since format",
      "range header bytes example",
      "origin header cors",
      "referer vs referrer header",
      "user agent header examples",
      "accept header json example",
      "accept language header format",
      "cache control no cache header",
      "content length header explained",
      "cookie header format",
      "host header http",
      "connection keep alive header",
      "dnt header do not track",
      "x-forwarded-for header",
      "x-requested-with ajax",
      "how to set authorization header",
      "http headers for api testing",
      "free api header tool",
      "http header maker online"
    ],
  };

export default seo;
