import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "IBAN Validator - Free Online IBAN Checker Tool | IconVault",
    metaDescription: "Validate any IBAN with the official mod-97 check, see the parsed bank code and account number, and format it for print. Free, in your browser.",
    about: [
      "**IconVault**'s **IBAN Validator** checks any **International Bank Account Number** with the official **mod-97 checksum algorithm** from ISO 13616. Paste an IBAN and instantly see whether it is valid, which **country** it belongs to, and the parsed **bank code** and **account number** inside it.",
      "You can also **format** IBANs for print (groups of four) or compact electronic use, and browse per-country IBAN structure rows. It is **free**, needs **no signup**, and runs **fully in your browser**, so account numbers never leave your device. Honest note: a valid checksum only proves the IBAN is well-formed; it does not prove the account exists or belongs to anyone."
    ],
    faqs: [
      { q: "How does IBAN validation work?", a: "The IBAN is rearranged (country code and check digits moved to the end, letters converted to numbers) and divided by 97. If the remainder is 1, the IBAN passes the mod-97 check defined by ISO 13616." },
      { q: "Is my IBAN sent to a server?", a: "No. Validation, parsing and formatting all run in your browser. Your account details never leave your device." },
      { q: "Does a valid IBAN mean the account exists?", a: "No. The mod-97 check only catches typos and transcription errors. It cannot confirm the account is open, active or owned by a particular person." },
      { q: "What does the validator show for a valid IBAN?", a: "The country, the check digits, the bank identifier (BBAN parts vary by country), the account number, and the IBAN in both print format (spaced groups of four) and electronic format (no spaces)." },
      { q: "What is the difference between IBAN and SWIFT/BIC?", a: "An IBAN identifies a specific bank account; a SWIFT/BIC code identifies the bank itself. International transfers usually need both." },
      { q: "Can it validate IBANs from any country?", a: "It applies the standard mod-97 algorithm plus country-specific length and structure rules, covering the SEPA region and other IBAN-issuing countries." }
    ],
    tags: [
      "iban validator",
      "iban checker",
      "validate iban",
      "check iban number",
      "iban validation online",
      "iban checker free",
      "mod 97 iban check",
      "iban checksum calculator",
      "is this iban valid",
      "verify iban online",
      "iban format checker",
      "iban structure by country",
      "iban country code list",
      "iban length by country",
      "german iban validator",
      "french iban check",
      "uk iban validator",
      "spanish iban checker",
      "italian iban validation",
      "sepa iban checker",
      "iban print format",
      "format iban with spaces",
      "iban electronic format",
      "iban vs account number",
      "what is an iban",
      "iban number explained",
      "iban check digits meaning",
      "bban vs iban",
      "how to validate iban manually",
      "mod 97 algorithm explained",
      "iso 13616 iban",
      "iban generator vs validator",
      "check bank account number validity",
      "international bank account number check",
      "swift bic vs iban",
      "sepa transfer iban",
      "european iban validation",
      "iban for wire transfer",
      "correct iban format example",
      "iban spaces or no spaces",
      "how long is an iban",
      "iban starting with de",
      "iban starting with fr",
      "iban starting with gb",
      "iban starting with es",
      "iban starting with it",
      "iban regex pattern",
      "bank identifier code iban",
      "find bank from iban",
      "iban country lookup",
      "free iban tool no signup",
      "online iban verifier"
    ],
  };

export default seo;
