import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Idle Detection Playground - Interactive Web API Lab | IconVault",
    metaDescription: "Try the real Idle Detection API: permission flow, threshold control, live user and screen idle states plus an event timeline. Free, in your browser.",
    about: [ "**IconVault**'s **Idle Detection Playground** talks to the real **`IdleDetector`** API: request permission, choose an idle **threshold**, then watch **user state** (active or idle) and **screen state** (locked or unlocked) flip live as you stop moving the mouse or lock the screen. A scrolling event timeline records every change with timestamps. It is free and runs fully in your browser.", "Idle detection is **Chromium-only** today and requires explicit **permission**, which the tool requests through the real prompt flow. You will learn why the API needs a secure context, how the threshold minimum works (60 seconds in current implementations), sensible uses like pausing timers or marking yourself away in a chat app, and the privacy design: idle state is coarse on purpose, so sites cannot tell exactly what you are doing." ],
    faqs: [ { q: "Which browsers support the Idle Detection API?", a: "Chrome and Edge on desktop. Firefox and Safari do not ship it, so this lab shows a clear unsupported notice there instead of faking data." }, { q: "Why does the API ask for permission?", a: "Idle state can reveal whether someone is at their computer, so the spec requires an explicit permission grant in a secure context. This lab walks you through the real request flow." }, { q: "What is the minimum idle threshold?", a: "Current Chromium builds enforce a minimum of 60 seconds; anything lower is clamped. Set the slider below that and watch the lab report the enforced value." }, { q: "What is the difference between user state and screen state?", a: "User state is active or idle based on input; screen state is locked or unlocked. A locked screen implies the user is idle, but an unlocked screen can still be idle." }, { q: "What are good uses for idle detection?", a: "Pausing animations and timers, marking presence as away, dimming a dashboard, or delaying non-urgent sync until the user returns. Never use it to punish inactivity." }, { q: "Is my activity data sent anywhere?", a: "No. State changes are read locally and the timeline is only rendered on this page." } ],
    tags: [ "idle detection api", "idledetector", "idle detection javascript", "idle detector api", "detect user idle javascript", "javascript idle detection", "user idle api", "screen idle api", "idle threshold", "idle state web", "browser idle detection", "detect inactivity javascript", "inactive user javascript", "idle timer web app", "idle api chrome", "idle detection permission", "idledetector.requestpermission", "userState screenState", "idlechange event", "mdn idle detection api", "idle detection api tutorial", "idle detection example", "idle detection playground", "how to detect idle user in javascript", "javascript detect user inactive", "auto logout idle javascript", "pause on idle web", "presence api web", "away status javascript", "chat idle status", "detect screen lock javascript", "screen locked javascript", "idle api secure context", "why idle detection needs permission", "idle detection privacy", "idle detection caniuse", "is idle detection supported", "idle detector typescript", "idle detection polyfill", "requestidlecallback vs idle detection", "document.hidden vs idle", "visibilitychange idle", "heartbeat idle detection", "mouse move idle timer", "keyboard idle timer", "web idle timeout", "session timeout javascript", "idle logout best practices", "idle detection 2024", "chromium idle detector", "edge idle api" ],
  };

export default seo;
