import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image Dithering - Free Online Retro Dither Effect Tool | IconVault",
    metaDescription: "Apply retro dithering to photos: Floyd-Steinberg, ordered Bayer and Atkinson, with classic palettes. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Image Dithering** turns photos into **retro pixel-art style** images with real dithering algorithms: **Floyd-Steinberg** error diffusion, **ordered Bayer** (4x4 and 8x8 matrices) and **Atkinson** dithering. Pick a **classic palette** like 1-bit black and white, Game Boy greens or CGA colors, and watch smooth gradients dissolve into beautiful dot patterns.",
      "Processing happens **entirely in your browser** on an HTML canvas, with **no upload** and **no signup**, and it is **free**. Honest note: dithering is destructive by design; keep your original file, because the effect cannot be reversed from the exported image."
    ],
    faqs: [
      { q: "What is image dithering?", a: "A technique that simulates shades and gradients using a limited palette by arranging dots of available colors in patterns. Your eye blends the dots into tones that are not really there." },
      { q: "What is the difference between Floyd-Steinberg and Bayer?", a: "Floyd-Steinberg is error diffusion: it spreads each pixel's quantization error to neighbors, giving organic, detailed results. Ordered Bayer uses a fixed threshold matrix, giving a regular, geometric dot pattern with a classic retro look." },
      { q: "What is Atkinson dithering?", a: "An error-diffusion variant used by the original Macintosh that spreads only part of the error, producing higher-contrast results with blown-out highlights and deep shadows, the look of early Mac art." },
      { q: "Which palettes are available?", a: "Classic limited palettes including 1-bit black and white, Game Boy 4-shade green, CGA, and other retro console-inspired sets." },
      { q: "Are my photos uploaded?", a: "No. Your image is loaded into a canvas locally and every pixel is processed in your browser." },
      { q: "Can I undo dithering?", a: "Not from the exported file. Dithering permanently reduces the image to the palette, so keep the original and re-export if you want a different look." }
    ],
    tags: [
      "image dithering",
      "dithering effect online",
      "photo dithering tool",
      "floyd steinberg dithering",
      "ordered dithering bayer",
      "atkinson dithering online",
      "retro dither effect",
      "1 bit dither image",
      "black and white dither",
      "game boy palette image",
      "dithered photo effect",
      "pixel art dither",
      "retro pixel effect photo",
      "error diffusion dithering",
      "bayer matrix dithering",
      "cga palette image",
      "limited palette image converter",
      "dither image online free",
      "apply dithering to photo",
      "vintage computer graphics effect",
      "old macintosh image style",
      "8 bit dither effect",
      "halftone vs dithering",
      "dithering explained",
      "what is floyd steinberg",
      "how does ordered dithering work",
      "atkinson vs floyd steinberg",
      "best dithering algorithm",
      "dither png online",
      "dither jpg online",
      "convert photo to 1 bit",
      "black white stipple photo",
      "newspaper print photo effect",
      "dot pattern photo effect",
      "retro game art style",
      "demake photo filter",
      "lo fi image effect",
      "dithering for print",
      "reduce colors with dithering",
      "posterize vs dither",
      "image to gameboy style",
      "image to retro console style",
      "free dithering tool no signup",
      "dither image in browser",
      "no upload dither tool",
      "dithered avatar maker",
      "pixel dither generator",
      "bayer 4x4 vs 8x8",
      "custom palette dithering",
      "retro dither photo filter",
      "1bit art from photo"
    ],
  };

export default seo;
