import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image Splitter - Free Online Tool | IconVault",
    metaDescription: "Split an image into grid tiles or Instagram carousel slices online. Free, private, in-browser splitter with ZIP download.",
    about: [
      "**IconVault**'s **Image Splitter** slices one image into a grid of tiles or into **Instagram carousel** slices. Set any **rows and columns**, use presets like 2x2, 3x3 profile grid or 2 halves, then download each tile or grab them all as a **ZIP**. Everything runs **free** and **browser-private**, your image never leaves your device.",
      "Carousel mode cuts overlapping **4:5 portrait slices** panned across your photo, perfect for swipeable posts. Choose Same, JPG, PNG or WebP output. **Pro** members get unlimited use with no trial limits.",
    ],
    faqs: [
      { q: "How do I split an image into a grid?", a: "Drop your image into the splitter, choose grid mode, set the rows and columns, click Split into tiles, then download each tile or all of them as a ZIP." },
      { q: "How do I split a photo for an Instagram carousel?", a: "Switch to Instagram carousel mode and set the number of slices. The tool cuts overlapping 4:5 portrait slices panned across your photo, ready to post as a swipeable carousel." },
      { q: "How do I post a split grid on Instagram?", a: "Split into a 3x3 profile grid, then post the tiles in reverse order so they appear left to right, top to bottom on your profile." },
      { q: "What size are the carousel slices?", a: "Each slice is exported at 1080px wide, the standard Instagram width, with a 4:5 portrait crop." },
      { q: "Is my image uploaded to a server?", a: "Never. Splitting happens entirely in your browser on your own device." },
      { q: "Is the image splitter free?", a: "Yes, free users get a generous number of uses. Pro members get unlimited use of every tool." },
    ],
    tags: [ "split image into grid", "image splitter online", "split photo into tiles", "instagram grid splitter", "split image for instagram", "photo grid cutter", "split picture into pieces", "carousel image splitter", "3x3 grid splitter", "split image online free", "slice image into parts", "instagram puzzle feed maker", "split photo for profile grid", "image tile cutter", "divide image into squares", "photo splitter online", "split panorama for instagram", "grid post maker", "cut image into equal parts", "tile image generator" ,
      "image splitter online free",
      "split image into 9",
      "split image into 4",
      "split image into 6",
      "split image into 2",
      "split picture into grid free",
      "photo grid splitter online",
      "instagram carousel splitter",
      "split image for carousel post",
      "instagram post splitter",
      "3x2 grid image splitter",
      "2x3 image splitter",
      "split photo into equal parts",
      "image divider online",
      "cut photo into grid",
      "split image into squares free",
      "puzzle grid image splitter",
      "instagram puzzle grid maker",
      "split wide image for instagram",
      "split panorama photo",
      "split image rows and columns",
      "custom grid image splitter",
      "image slicer online",
      "photo slicer free",
      "slice photo into tiles",
      "split image download zip",
      "split image no watermark",
      "split image in browser",
      "how to split an image into grid",
      "split image for social media",
      "split image for facebook carousel",
      "linkedin carousel image splitter",
      "split image into thumbnails",
      "split long image into parts",
      "split tall image for stories",
      "image split tool free",
      "grid cutter for photos",
      "split image 3x3 online",
      "split image 4x4",
      "split image into equal tiles"],
  };

export default seo;
