import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image to PDF Converter - Free Online Tool | IconVault",
    metaDescription: "Combine JPG, PNG and more into a PDF free in your browser. Page sizes, margins, no uploads, private by design.",
    about: [
      "**IconVault**'s **Image to PDF Converter** combines your **JPG, PNG, WebP, GIF and BMP images** into a single **PDF document**, right in your browser. Each image becomes one page, centered and scaled to fit, never stretched or cropped. The tool is completely **free**, and your images **never leave your device**.",
      "Choose a **page size** (fit image, A4 or Letter) and **margins** (none, small or large) to control the layout. Pages follow the order you add them. **IconVault Pro** removes trial limits so you can build long documents in one go.",
    ],
    faqs: [
      { q: "Is the Image to PDF converter free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited PDF creation." },
      { q: "Are my images uploaded?", a: "No. The PDF is built entirely in your browser, so your images stay private." },
      { q: "Will my images be stretched or cropped?", a: "Never. Each image is centered and scaled to fit the page while keeping its aspect ratio." },
      { q: "What page sizes are available?", a: "Fit image (each page matches its image), A4 and Letter, with none, small or large margins." },
      { q: "Can I reorder the pages?", a: "Pages follow the order you add the images. Remove any image before building the PDF." },
      { q: "What image formats are supported?", a: "JPG, PNG, WebP, GIF and BMP. Add as many as you like; each becomes one page." },
    ],
    tags: ["image to pdf", "jpg to pdf", "png to pdf", "convert image to pdf", "images to pdf online", "jpg to pdf free", "combine images pdf", "photo to pdf", "image to pdf free", "multiple images to pdf", "jpg to pdf converter", "png to pdf converter", "make pdf from images", "image to pdf no signup", "image to pdf private", "pictures to pdf", "scan to pdf", "image to pdf batch", "photos to pdf", "image to pdf browser",
      "convert image to pdf free",
      "jpg to pdf online",
      "png to pdf online",
      "jpeg to pdf",
      "webp to pdf",
      "heic to pdf",
      "images to pdf converter free",
      "convert photos to pdf",
      "turn images into pdf",
      "make a pdf from photos",
      "photo to pdf converter free",
      "combine jpg to pdf",
      "merge images into pdf",
      "multiple jpg to one pdf",
      "image to pdf no watermark",
      "free image to pdf converter",
      "best image to pdf converter",
      "image to pdf in browser",
      "convert image to pdf online",
      "how to convert image to pdf",
      "screenshot to pdf",
      "screenshots to pdf",
      "scan images to pdf",
      "document scanner pdf",
      "image to pdf a4",
      "image to pdf letter size",
      "fit image to pdf page",
      "pdf page size from image",
      "portrait landscape pdf from image",
      "image to pdf with margins",
      "compress image pdf",
      "image to pdf small file",
      "png to pdf with transparency",
      "image to pdf for printing",
      "image to pdf for email",
      "batch image to pdf",
      "bulk images to pdf",
      "folder of images to pdf",
      "image to pdf zip download",
      "image to pdf mobile"],
  };

export default seo;
