import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image to AVIF Converter - Free Online Tool | IconVault",
    metaDescription: "Convert images to next-gen AVIF free in your browser. Smallest modern format, quality control, bulk ZIP download.",
    about: [
      "**IconVault**'s **Image to AVIF Converter** turns **PNG, JPG, GIF, BMP and WebP** images into **AVIF files**, the smallest modern image format, right in your browser. AVIF beats even WebP on size at the same visual quality and is supported by all major browsers. The tool is completely **free**, handles **bulk uploads**, and your images **never leave your device**.",
      "A **quality slider** (90% default) balances size and sharpness, and batches download as a **ZIP**. Encoding needs a modern browser: if yours cannot encode AVIF, the tool tells you plainly instead of failing silently. **IconVault Pro** removes trial limits for unlimited conversions.",
    ],
    faqs: [
      { q: "Is the Image to AVIF converter free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited conversions." },
      { q: "Are my images uploaded?", a: "No. The conversion runs entirely in your browser, keeping everything private." },
      { q: "Why convert to AVIF?", a: "AVIF produces the smallest files of any modern format at the same visual quality, so pages load faster." },
      { q: "My browser cannot encode AVIF. What now?", a: "The tool detects this and tells you honestly. Try Chrome or a recent Edge, Firefox or Safari, which all encode AVIF." },
      { q: "Does AVIF keep transparency?", a: "Yes. AVIF fully supports transparency, so transparent sources stay transparent." },
      { q: "Can I convert many images at once?", a: "Yes. Add files in bulk and download them all together as a ZIP." },
    ],
    tags: ["image to avif", "convert to avif", "png to avif", "jpg to avif", "avif converter", "avif online", "image to avif free", "bulk avif converter", "webp to avif", "avif quality", "avif file converter", "make avif", "avif batch converter", "avif no signup", "avif converter private", "avif download", "photo to avif", "avif zip download", "next gen image format", "avif vs webp",
      "convert image to avif",
      "jpg to avif online",
      "png to avif online",
      "jpeg to avif",
      "webp to avif online",
      "image to avif converter online",
      "best avif converter",
      "free avif converter online",
      "avif converter free online",
      "convert photos to avif",
      "turn jpg into avif",
      "turn png into avif",
      "avif encoder online",
      "encode avif online",
      "avif compression online",
      "convert to avif free",
      "avif maker online",
      "create avif images",
      "avif image maker",
      "bulk convert to avif",
      "convert multiple images to avif",
      "avif batch converter free",
      "avif quality settings",
      "avif vs jpg",
      "avif vs png",
      "why use avif",
      "avif image format converter",
      "next-gen image converter",
      "avif converter no signup free",
      "avif converter no watermark",
      "convert image to avif in browser",
      "avif file maker",
      "jpg to av1 image",
      "heic to avif",
      "gif to avif",
      "bmp to avif",
      "tiff to avif",
      "avif to avif compressor",
      "reduce avif file size",
      "avif optimizer online"],
  };

export default seo;
