import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image Stitcher - Free Online Tool | IconVault",
    metaDescription: "Join multiple photos side by side or stacked into one image. Free, private, in-browser stitcher with live preview.",
    about: [
      "**IconVault**'s **Image Stitcher** joins 2 or more images into a single picture. Line them up **side by side** or **stacked**, control **alignment** and **spacing**, optionally make them all the same height or width, and pick a **background color** or transparent background. Everything runs **free** and **browser-private**, your photos never leave your device.",
      "A live preview shows the result before you download in **PNG, JPG or WebP**. **Pro** members get unlimited use with no trial limits.",
    ],
    faqs: [
      { q: "How do I join two images side by side?", a: "Drop both images into the stitcher, keep the Side by side direction, optionally make them the same height, then click Stitch and download." },
      { q: "Can I stack images vertically?", a: "Yes. Switch the direction to Stacked and the images are joined top to bottom, with optional same-width scaling and left, center or right alignment." },
      { q: "Can the background be transparent?", a: "Yes. Choose the Transparent background option and download as PNG or WebP. JPG always uses a solid background." },
      { q: "How do I control the gap between images?", a: "Use the spacing control to set the gap in pixels between the stitched images, from 0 for a seamless join upward." },
      { q: "Are my photos uploaded anywhere?", a: "No. Stitching happens entirely in your browser, so your photos stay private on your own device." },
      { q: "Is the image stitcher free?", a: "Yes, free users get a generous number of uses. Pro members get unlimited use of every tool." },
    ],
    tags: [ "stitch images together", "combine images side by side", "join photos online", "merge images vertically", "image joiner online", "combine two pictures", "photo stitcher free", "stack images online", "merge photos side by side", "join multiple images", "picture combiner online", "append images together", "combine jpg images", "merge png images", "side by side photo maker", "before after image joiner", "combine screenshots", "image merger online free", "join photos vertically", "panorama stitcher online" ,
      "stitch photos together online",
      "combine images online free",
      "merge photos online free",
      "join images online free",
      "image stitcher online",
      "photo stitcher online free",
      "combine multiple photos into one",
      "merge two images into one",
      "stitch screenshots together",
      "combine screenshots vertically",
      "long screenshot stitcher",
      "tall image maker from screenshots",
      "stitch images horizontally",
      "stitch images vertically free",
      "image joiner free online",
      "photo merger free online",
      "collage two photos side by side",
      "before after photo maker",
      "comparison image maker",
      "combine png images online",
      "combine jpg online",
      "merge webp images",
      "stitch photos no watermark",
      "image stitcher no signup",
      "how to stitch images together",
      "how to combine two photos",
      "merge images in browser",
      "free image combiner",
      "online image merger",
      "join pictures together",
      "merge pictures online free",
      "stack photos vertically",
      "arrange photos side by side",
      "two photos one image",
      "merge multiple jpg",
      "batch image joiner",
      "stitch product photos",
      "stitch scanned pages",
      "combine scan images",
      "panorama maker from photos"],
  };

export default seo;
