import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image Size Checker - Free Online Tool | IconVault",
    metaDescription: "Check image dimensions, format, file size and aspect ratio free in your browser. Bulk inspection, no uploads.",
    about: [
      "**IconVault**'s **Image Size Checker** tells you the true facts about your images: **pixel dimensions** (W x H), **format**, **file size** and the **aspect ratio** (16:9, 1:1, 4:3, and so on). Drop up to 50 files and get a clean table instantly. There are no options and no processing: it only inspects, so your files are never modified.",
      "It is **free** to use and **private by design**: inspection happens locally in your browser, so your files never leave your device. **Pro** members get unlimited checks for auditing whole media libraries.",
    ],
    faqs: [
      { q: "What information does it show?", a: "For each image: file name, dimensions in pixels, format (JPEG, PNG, WebP, GIF, AVIF and more), file size, and aspect ratio." },
      { q: "How is the aspect ratio calculated?", a: "Dimensions are reduced to their simplest ratio, like 16:9 or 4:3. Unusual sizes show a decimal ratio such as 1.33:1." },
      { q: "Does it change or compress my images?", a: "No. This is an inspection-only tool. Your files are read, never modified, and nothing is downloaded unless you want it." },
      { q: "Can I check many images at once?", a: "Yes, drop up to 50 images and they all appear in one table, perfect for auditing a folder before upload." },
      { q: "Are my images uploaded to a server?", a: "No. Everything is read locally in your browser. Your files never leave your device." },
      { q: "Why do dimensions matter?", a: "Platforms reject or downscale wrong-sized images. Checking first saves you from blurry uploads and failed form submissions." },
    ],
    tags: ["image size checker", "check image dimensions", "image dimension checker", "photo size checker", "check photo resolution", "image info online", "get image dimensions", "bulk image inspector", "image metadata viewer", "check aspect ratio", "photo dimension checker", "image resolution checker", "free image size checker", "online image inspector", "view image details", "image file info", "check image width height", "picture size checker", "image specs checker", "photo info tool",
      "check image size online",
      "find image dimensions online",
      "image dimension finder",
      "photo dimension finder",
      "what size is my image",
      "check photo dimensions online",
      "get photo dimensions",
      "image resolution finder",
      "check image dpi online",
      "image ppi checker",
      "photo kb size checker",
      "check file size of image",
      "image file size checker",
      "how big is my photo",
      "image width height checker",
      "picture dimension checker",
      "check image aspect ratio online",
      "find aspect ratio of image",
      "bulk image size checker",
      "check multiple image sizes",
      "image size checker free online",
      "photo size checker free",
      "online photo inspector",
      "jpg dimension checker",
      "png dimension checker",
      "webp dimension checker",
      "image specs online free",
      "check if image is 300 dpi",
      "verify image resolution",
      "image quality checker",
      "check image megapixels",
      "photo megapixel checker",
      "how many megapixels is my photo",
      "image dimension validator",
      "check minimum image size",
      "image size requirements checker",
      "photo size in inches checker",
      "image info reader online",
      "upload image check size",
      "drag drop image size check"],
  };

export default seo;
