import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image to WebP Converter - Free Online Tool | IconVault",
    metaDescription: "Convert PNG, JPG and more to WebP free in your browser. Smaller files, quality control, bulk ZIP download, no uploads.",
    about: [
      "**IconVault**'s **Image to WebP Converter** turns **PNG, JPG, GIF, BMP and AVIF** images into modern **WebP files** right in your browser. WebP files are dramatically smaller than PNG and JPG at the same visual quality, which makes pages load faster. The tool is completely **free**, supports **bulk uploads**, and your images **never leave your device**.",
      "A **quality slider** controls the size-versus-sharpness tradeoff, with 80% recommended as a good balance for photos on the web. Convert a batch and download everything as a **ZIP**. **IconVault Pro** removes trial limits for unlimited conversions.",
    ],
    faqs: [
      { q: "Is the Image to WebP converter free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited conversions." },
      { q: "Are my images uploaded anywhere?", a: "No. Everything converts locally in your browser, so your images stay private." },
      { q: "Why convert to WebP?", a: "WebP is much smaller than PNG or JPG at the same quality, so websites load faster and use less bandwidth." },
      { q: "What quality should I use?", a: "80% is a good balance for photos on the web. Raise it for hero images, lower it for thumbnails." },
      { q: "Does WebP keep transparency?", a: "Yes. WebP fully supports transparency, so transparent PNGs stay transparent." },
      { q: "Can I convert many images at once?", a: "Yes. Add PNG, JPG, GIF, BMP or AVIF files in bulk and download them as a ZIP." },
    ],
    tags: ["image to webp", "convert to webp", "png to webp", "jpg to webp", "webp converter", "webp online", "image to webp free", "bulk webp converter", "convert image webp", "webp quality", "png jpg to webp", "webp file converter", "webp converter free", "make webp", "webp batch converter", "webp no signup", "webp converter private", "webp download", "photo to webp", "webp zip download",
      "convert image to webp",
      "jpg to webp online",
      "png to webp online",
      "jpeg to webp",
      "gif to webp",
      "bmp to webp",
      "tiff to webp",
      "heic to webp",
      "image to webp converter online",
      "best webp converter",
      "free webp converter online",
      "convert photos to webp",
      "turn jpg into webp",
      "turn png into webp",
      "webp encoder online",
      "encode webp online",
      "convert to webp free",
      "webp maker online",
      "create webp images",
      "webp image maker",
      "bulk convert to webp",
      "convert multiple images to webp",
      "webp batch converter free",
      "webp quality settings",
      "webp vs jpg",
      "webp vs png",
      "why use webp",
      "webp converter no signup free",
      "webp converter no watermark",
      "convert image to webp in browser",
      "webp file maker",
      "webp for website",
      "webp for wordpress",
      "speed up site with webp",
      "convert images for web",
      "webp animated converter",
      "animated webp maker",
      "webp to webp compressor",
      "reduce webp file size online",
      "webp optimizer free"],
  };

export default seo;
