import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image to Base64 Converter - Free Online Tool | IconVault",
    metaDescription: "Encode images as Base64 data URIs free in your browser. Original, WebP or JPEG output, one-click copy, no uploads.",
    about: [
      "**IconVault**'s **Image to Base64 Converter** encodes any image into a **Base64 data URI** you can paste straight into **HTML or CSS**, right in your browser. Data URIs embed the image directly in your code, so there is no separate file to host. The tool is completely **free**, and your images **never leave your device**.",
      "Keep the **original format** or re-encode as **WebP or JPEG**, which can be much smaller. The tool shows the **encoded size** so you can judge the tradeoff, and a one-click **Copy button** grabs the whole URI. **IconVault Pro** removes trial limits for bulk encoding.",
    ],
    faqs: [
      { q: "Is the Image to Base64 converter free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited encoding." },
      { q: "Is my image uploaded anywhere?", a: "No. Encoding happens entirely in your browser, so your image stays private." },
      { q: "Why use a Base64 data URI?", a: "It embeds the image directly in HTML or CSS, avoiding an extra HTTP request. Great for small icons and logos." },
      { q: "Should I keep the original or use WebP?", a: "WebP and JPEG can be much smaller than PNG. Use them unless you need the exact original format." },
      { q: "Are Base64 URIs bigger than the file?", a: "Yes, roughly 33 percent larger. They pay off only for small images where saving a request matters." },
      { q: "How do I use the result?", a: "Copy it with the Copy button and paste it as an img src or CSS background url." },
    ],
    tags: ["image to base64", "base64 encoder", "image to data uri", "base64 image online", "convert image to base64", "base64 encoder free", "data uri generator", "image base64 converter", "png to base64", "jpg to base64", "base64 encode image", "base64 data uri", "image to base64 no signup", "base64 tool", "encode image online", "base64 for css", "base64 for html", "image to base64 private", "webp base64", "base64 copy",
      "image to base64 online",
      "convert image to base64 online",
      "png to base64 online",
      "jpg to base64 online",
      "jpeg to base64",
      "gif to base64",
      "svg to base64",
      "ico to base64",
      "base64 image encoder online",
      "free base64 encoder",
      "online base64 converter",
      "picture to base64",
      "photo to base64",
      "encode png to base64",
      "encode jpg to base64",
      "image to base64 string",
      "base64 data uri converter",
      "data uri from image",
      "image data uri maker",
      "base64 for img tag",
      "base64 image for css background",
      "embed image as base64",
      "base64 image embed code",
      "convert image to data url",
      "image to base64 no signup free",
      "base64 encoder no watermark",
      "base64 tool online free",
      "image to base64 bulk",
      "batch image to base64",
      "multiple images to base64",
      "base64 favicon generator",
      "favicon to base64",
      "image to base64 for email",
      "email signature image base64",
      "how to convert image to base64",
      "base64 image decoder",
      "base64 to image converter",
      "image to base64 api",
      "base64 image size calculator",
      "base64 vs image file size"],
  };

export default seo;
