import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image Color Picker - Free Online Tool | IconVault",
    metaDescription: "Pick any color off an image with a magnifier loupe. HEX, RGB and HSL readouts, click to copy. Free and private.",
    about: [
      "**IconVault**'s **Image Color Picker** is an eyedropper for your pictures: hover over any pixel and a **magnifier loupe** follows your cursor, zoomed from 2x to 12x with a crosshair on the exact pixel. Click to lock the color, then read it as **HEX, RGB and HSL**, each one click-to-copy.",
      "The picker samples the true source pixel at full image resolution, not the scaled preview, so the value you get is exactly right. Everything runs **in your browser**, your image is never uploaded. **Free** for daily use, unlimited with Pro.",
    ],
    faqs: [
      { q: "How accurate is the color picker?", a: "It samples the pixel from the original full-resolution image, mapped from your cursor position, so the HEX value matches the true color under your cursor." },
      { q: "What do the HEX, RGB and HSL readouts mean?", a: "HEX is the web-friendly color code (#RRGGBB), RGB lists red/green/blue channels 0-255, and HSL describes hue, saturation and lightness. Click any readout to copy it." },
      { q: "Can I change the loupe zoom?", a: "Yes, the loupe zoom slider runs from 2x to 12x. Higher zoom makes it easier to land on a single pixel in detailed photos." },
      { q: "Does the tool keep the last color I clicked?", a: "Yes. Clicking locks the color into the readout panel so it stays put while you move the mouse, until you click a new pixel." },
      { q: "Is my image uploaded to a server?", a: "No. The image is decoded and sampled locally in your browser. Nothing leaves your device." },
      { q: "Is the Image Color Picker free?", a: "Yes, with a daily free trial limit. IconVault Pro removes all limits across every tool." },
    ],
    tags: [ "image color picker", "eyedropper tool online", "pick color from image", "pixel color picker", "hex color from photo", "rgb picker from image", "color sampler online", "magnifier color picker", "get hex code from image", "photo color picker", "screen color picker", "identify color in image", "color code finder", "hsl color picker", "web color from picture", "design color picker", "free eyedropper", "image to hex", "pixel color value", "color inspector online" ,
      "color picker from image online",
      "eyedropper online free",
      "pick hex color from image",
      "image eyedropper tool",
      "color picker tool online free",
      "upload image pick color",
      "find color code from picture",
      "rgb color picker online",
      "hex code picker online",
      "photo eyedropper",
      "color grabber online",
      "image color finder",
      "get rgb from image",
      "get hsl from image",
      "color from photo hex",
      "identify hex color online",
      "color picker no download",
      "browser color picker tool",
      "find pantone color from image",
      "color name from image",
      "what color is this image",
      "find color of pixel",
      "dominant color picker",
      "color picker with zoom",
      "image color analyzer tool",
      "palette color picker",
      "css color from image",
      "web design color picker",
      "online eyedropper picker",
      "color picker for developers",
      "copy hex from image",
      "extract color code from png",
      "extract color code from jpg",
      "image color sampler free",
      "hover color picker image",
      "zoom color picker",
      "precise color picker",
      "color dropper online",
      "pick pantone from photo",
      "image color code extractor"],
  };

export default seo;
