import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image Compare - Free Online Before After Image Comparison | IconVault",
    metaDescription: "Compare two images side by side with a draggable before/after slider and a pixel-difference score. Free, fully in your browser.",
    about: [
      "**IconVault**'s **Image Compare** puts two images on one canvas with a **draggable before/after slider**, so you can sweep between versions and spot exactly what changed. Switch between **split view** and **side-by-side**, and get a live **difference percentage** computed from the pixels, with an adjustable **threshold** for how sensitive the comparison is.",
      "Everything is processed **in your browser** with **no upload** and **no signup**, and it is **free** to use, which makes it safe for unreleased designs and client work. Honest note: the difference score is a raw pixel comparison, so compression artifacts or tiny shifts can inflate it; use your eyes for the final judgment."
    ],
    faqs: [
      { q: "How do I compare two images?", a: "Upload both images, then drag the slider to wipe between them, or switch to side-by-side mode. The difference percentage updates live as you move the slider." },
      { q: "What does the difference percentage mean?", a: "It is the share of pixels that differ between the two images beyond the threshold you set. 0% means the images are pixel-identical at that threshold." },
      { q: "What is the threshold slider for?", a: "It controls how big a per-pixel change must be to count as a difference. Raise it to ignore JPEG noise and compression artifacts; lower it to catch the tiniest edits." },
      { q: "Are my images uploaded anywhere?", a: "No. Both images are decoded and compared locally on a canvas in your browser. Nothing is sent to a server." },
      { q: "What is this good for?", a: "Checking design revisions, verifying image exports, spotting retouching changes, comparing compression settings, and QA of before/after edits." },
      { q: "Do the images need to be the same size?", a: "Comparison is most meaningful when both images share dimensions. The tool draws them on one canvas, so mismatched sizes are aligned to the canvas rather than scaled." }
    ],
    tags: [
      "image compare",
      "compare two images",
      "image comparison tool",
      "before after image slider",
      "before after slider online",
      "image diff tool",
      "compare images side by side",
      "visual diff images",
      "pixel difference checker",
      "image difference calculator",
      "spot the difference images",
      "compare image versions",
      "design revision compare",
      "check image changes",
      "image comparison slider",
      "draggable image comparison",
      "online image diff",
      "free image compare tool",
      "compare photos online",
      "before after photo comparison",
      "image a b test visual",
      "verify image export",
      "compare compression quality images",
      "diff percentage images",
      "image similarity checker",
      "are these images identical",
      "find differences between pictures",
      "image overlay compare",
      "swipe to compare images",
      "image compare widget",
      "side by side image viewer",
      "compare screenshots online",
      "screenshot diff tool",
      "visual regression check images",
      "qa image comparison",
      "retouching before after check",
      "photo edit comparison",
      "compare mockup revisions",
      "image diff online free",
      "compare png images",
      "compare jpg images",
      "pixel by pixel image compare",
      "image threshold diff",
      "how to compare two images",
      "best image comparison tool",
      "image compare no upload",
      "private image comparison",
      "browser image diff tool",
      "compare images without photoshop",
      "image change detector",
      "visual compare tool free"
    ],
  };

export default seo;
