import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Image Noise - Free Online Film Grain Effect Tool | IconVault",
    metaDescription: "Add realistic film grain to photos with adjustable intensity, mono or color noise, and repeatable seeds. Free, fully in your browser.",
    about: [
      "**IconVault**'s **Image Noise** adds **film grain** to any photo with fine control: an **intensity slider**, a choice between **monochrome and color noise**, and a **seeded random generator**, so the exact same grain pattern can be reproduced whenever you need it.",
      "Grain is a classic way to add texture, hide **banding** in gradients, or give digital photos an **analog film look**. Everything runs **in your browser** with **no upload** and **no signup**, and it is **free**. Honest note: noise is baked into the exported pixels; keep the original if you might want a clean version later."
    ],
    faqs: [
      { q: "What does the Image Noise tool do?", a: "It adds random grain to your photo, like the texture of analog film. You control how strong the grain is, whether it is monochrome or colored, and the random seed." },
      { q: "What is the seed for?", a: "The noise uses a seeded random generator, so entering the same seed reproduces the exact same grain pattern. Useful for matching grain across a series of images." },
      { q: "Should I use mono or color noise?", a: "Monochrome grain looks like classic black-and-white film and is the safer choice for most photos. Color noise adds chroma variation, which can look more like high-ISO digital noise." },
      { q: "Can grain fix banding?", a: "Yes. Adding a small amount of noise is a well-known trick to break up visible banding in smooth gradients, such as skies, because it dithers the harsh steps." },
      { q: "Are my photos uploaded?", a: "No. The image stays on your device and the noise is rendered onto a canvas locally in your browser." },
      { q: "Can I remove the noise afterwards?", a: "Not cleanly from the exported file. Noise is destructive, so keep your original image and re-export if you change your mind." }
    ],
    tags: [
      "image noise",
      "add noise to image",
      "film grain effect online",
      "add grain to photo",
      "photo grain filter",
      "film grain overlay",
      "analog film grain effect",
      "vintage grain photo",
      "add texture to photo",
      "image grain generator",
      "grainy photo effect",
      "film look filter",
      "35mm film grain",
      "high iso noise effect",
      "monochrome grain photo",
      "color noise image",
      "random noise image generator",
      "film grain intensity control",
      "how to add film grain to photo",
      "why add grain to photos",
      "film grain vs digital noise",
      "remove banding with noise",
      "fix gradient banding photo",
      "add noise to hide banding",
      "film grain aesthetic",
      "lofi photo grain",
      "vintage photo texture",
      "old film photo effect",
      "add grain to digital photo",
      "photo noise simulator",
      "seeded noise generator",
      "reproducible image noise",
      "match grain across images",
      "add noise to png",
      "add noise to jpg",
      "grain effect for portraits",
      "film grain for video thumbnails",
      "noise texture generator",
      "perlin noise vs film grain",
      "what is film grain",
      "film grain explained",
      "does film grain look good",
      "how much grain to add",
      "subtle grain photo edit",
      "heavy grain effect",
      "black and white grain",
      "grainy black and white photo",
      "film grain lightroom alternative",
      "free film grain tool",
      "add grain online no signup",
      "grain photo in browser",
      "no upload grain tool",
      "film grain maker free"
    ],
  };

export default seo;
