import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "IndexedDB Explorer - Free Online IndexedDB Browser Tool | IconVault",
    metaDescription: "Browse your site's IndexedDB databases, object stores and records, with add, edit, delete and JSON import/export. Free, in your browser.",
    about: [
      "**IconVault**'s **IndexedDB Explorer** lets you inspect the **IndexedDB databases** stored by websites in your browser: list **object stores**, page through **records** (25 per page, up to 500 reads), and view keys, values and indexes. You can **add, edit and delete records**, and **import or export JSON** for backup or migration.",
      "It runs **entirely in your browser** with **no signup** and is **free**. Honest notes: for privacy and security, browsers only expose **this origin's** databases, so you see IconVault's own storage here, not other sites'; and edits write straight to the live database, so export a backup before changing production data."
    ],
    faqs: [
      { q: "What is IndexedDB?", a: "A low-level browser API for storing large amounts of structured data, including files and blobs, on the client. Web apps use it for offline data, caches and local state." },
      { q: "Why can I only see this site's databases?", a: "Browsers enforce the same-origin policy on storage. A page can only open IndexedDB databases created by its own origin, so this tool shows IconVault's databases, not other websites'." },
      { q: "Can I edit records?", a: "Yes. You can add new records, edit existing values and delete records or clear stores. Changes apply immediately to the live database." },
      { q: "How do import and export work?", a: "Export downloads a store's records as JSON; import reads a JSON file back into a store. Handy for backups, moving data between browsers, or seeding test data." },
      { q: "What are the read limits?", a: "Records are paged at 25 per page with a 500-record read cap per store, which keeps the UI fast even on large stores." },
      { q: "What if a database is blocked?", a: "If another tab holds the database open in a way that blocks access, the tool reports it. Closing the other tab usually clears the block." }
    ],
    tags: [
      "indexeddb explorer",
      "indexeddb viewer",
      "browse indexeddb",
      "indexeddb browser tool",
      "view indexeddb data",
      "inspect indexeddb chrome",
      "indexeddb devtools alternative",
      "indexeddb online tool",
      "open indexeddb database",
      "list indexeddb object stores",
      "indexeddb records viewer",
      "edit indexeddb records",
      "delete indexeddb data",
      "clear indexeddb store",
      "indexeddb import json",
      "indexeddb export json",
      "backup indexeddb data",
      "indexeddb json export",
      "what is indexeddb",
      "indexeddb explained",
      "indexeddb tutorial",
      "indexeddb vs localstorage",
      "how to view indexeddb",
      "check indexeddb storage",
      "debug indexeddb app",
      "indexeddb database blocked",
      "indexeddb same origin policy",
      "can websites see my indexeddb",
      "indexeddb storage limits",
      "indexeddb keypath explained",
      "indexeddb indexes",
      "query indexeddb records",
      "indexeddb transaction modes",
      "idbobjectstore explained",
      "clear site data indexeddb",
      "manage browser storage",
      "browser database viewer",
      "client side database tool",
      "offline storage inspector",
      "web app storage viewer",
      "pwa storage debugger",
      "service worker cache vs indexeddb",
      "where is indexeddb stored",
      "indexeddb file location chrome",
      "free indexeddb tool",
      "indexeddb admin panel",
      "inspect local databases browser",
      "view website local data",
      "web storage explorer",
      "indexeddb crud tool",
      "indexeddb data backup online"
    ],
  };

export default seo;
