import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JPG to PNG Converter - Free Online Tool | IconVault",
    metaDescription: "Convert JPG images to lossless PNG free in your browser. No uploads, bulk support, zero quality loss.",
    about: [
      "**IconVault**'s **JPG to PNG Converter** re-packages your **JPG images** as **lossless PNG files** in your browser, with no quality lost in the re-encoding step. PNG is the right choice for graphics, screenshots and anything you plan to edit again. The tool is completely **free**, supports **bulk uploads**, and your images **never leave your device**.",
      "There are no settings to configure: drop files, convert, download individually or as a **ZIP**. **IconVault Pro** removes trial limits for heavy batch work.",
    ],
    faqs: [
      { q: "Is JPG to PNG conversion free?", a: "Yes, with a daily free quota. IconVault Pro removes the limit entirely." },
      { q: "Are my images uploaded?", a: "No. The conversion happens locally in your browser, keeping everything private." },
      { q: "Does converting to PNG improve quality?", a: "It cannot restore detail lost to JPG compression, but it stops any further loss, which helps for editing and archiving." },
      { q: "Why use PNG instead of JPG?", a: "PNG is lossless and supports transparency, making it better for graphics, logos and screenshots." },
      { q: "Will the PNG be bigger than the JPG?", a: "Usually yes, because PNG stores every pixel exactly without lossy compression." },
      { q: "Can I convert many JPGs at once?", a: "Yes. Add a batch and download them all together as a ZIP." },
    ],
    tags: ["jpg to png", "jpeg to png", "convert jpg to png", "jpg to png online", "jpeg converter png", "jpg to png free", "bulk jpg to png", "jpg to png no loss", "jpeg to png converter", "convert jpeg files", "jpg to png batch", "jpg to png no signup", "jpg to png private", "free image converter", "jpg to png zip", "jpeg to png online", "jpg file converter", "png from jpg", "convert photo to png", "jpg to png tool",
      "convert jpg to png free",
      "jpg to png online free",
      "jpeg to png online free",
      "convert jpeg to png free",
      "jpg to png converter online",
      "best jpg to png converter",
      "jpg to png without losing quality",
      "jpg to png windows",
      "jpg to png on mac",
      "convert jpg files to png",
      "change jpg to png",
      "jpg to png app",
      "jpeg to png app",
      "convert photo to png free",
      "how to convert jpg to png",
      "jpg to png converter free online",
      "jpg to png no watermark",
      "jpg to png high resolution",
      "convert jpg to png in bulk",
      "multiple jpg to png",
      "jpg to png fast converter",
      "convert jpg to png without software",
      "jpg to png browser tool",
      "convert .jpg to .png",
      "jpg to png for logo",
      "jpg to png for web",
      "jpg to png for printing",
      "jpg to png for favicon",
      "convert jpg to png for editing",
      "jpg to png for photoshop",
      "jpg to png keep quality",
      "jpg to png image converter",
      "jpg photo to png free",
      "jpg to png email friendly",
      "batch jpg png converter",
      "convert jpg to png for free",
      "jpg to png free download",
      "jpg to png ios",
      "jpg to png android",
      "jpg to png mobile converter"],
  };

export default seo;
