import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Coercion Visualizer - Free Online JavaScript Equality Tool | IconVault",
    metaDescription: "Watch JavaScript == vs === coercion play out step by step with ToPrimitive and ToNumber traces. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Coercion Visualizer** demystifies the weirdest corner of JavaScript: **type coercion**. Type two values and watch the engine evaluate **loose equality (==)** one rule at a time, showing each **ToPrimitive**, **ToNumber**, **ToString** and **ToBoolean** conversion in order, right next to the result of **strict equality (===)** for comparison.",
      "It is the fastest way to understand why `[] == \"0\"` is true while `[] === \"0\"` is false, or why `null == undefined` passes but `null == 0` does not. Every step follows the actual **ECMAScript abstract operations**, everything runs **fully in your browser** with nothing uploaded, and it is **free** to try (heavy repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "What is the difference between == and === in JavaScript?", a: "Strict equality (===) returns true only when both operands have the same type and the same value, with no conversion. Loose equality (==) first converts operands to a common type using rules like ToPrimitive and ToNumber, which is why == can be true when === is false." },
      { q: "What does the visualizer show exactly?", a: "You enter a left and a right operand, and the tool lists each conversion step the engine would perform for == (for example [] becoming the empty string, then 0) alongside the final == result and the === result for the same operands." },
      { q: "Why is [] == false true in JavaScript?", a: "Because == converts both sides to primitives: [] becomes '' and then 0, while false becomes 0, so 0 == 0 is true. Strict equality [] === false is false because the types differ. The visualizer walks through exactly these steps." },
      { q: "Is == ever safe to use?", a: "Most style guides recommend === by default because it is predictable. Loose equality is occasionally used for null == undefined checks, which match both null and undefined. The visualizer helps you build the intuition to decide case by case." },
      { q: "Does the tool use real ECMAScript coercion rules?", a: "Yes. The step walk follows the abstract operations defined by the ECMAScript spec (ToPrimitive, ToNumber, ToString, ToBoolean) and the Abstract Equality Comparison algorithm, not simplified approximations." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "javascript type coercion",
      "js type coercion visualizer",
      "javascript == vs === operator",
      "loose equality vs strict equality",
      "javascript equality visualizer",
      "js equality operator explained",
      "javascript double equals vs triple equals",
      "== vs === javascript example",
      "javascript coercion steps",
      "toprimitive javascript",
      "tonumber javascript coercion",
      "tostring javascript coercion",
      "toboolean javascript",
      "javascript abstract equality",
      "abstract equality comparison",
      "strict equality comparison javascript",
      "why is empty array == false true in javascript",
      "javascript empty array equals not empty array",
      "null == undefined javascript",
      "0 == false javascript",
      "'' == false javascript",
      "nan === nan false",
      "javascript weird equality examples",
      "js coercion table",
      "javascript type conversion table",
      "implicit type conversion javascript",
      "explicit type conversion javascript",
      "javascript equality quirks",
      "js equality interview questions",
      "javascript interview coercion questions",
      "understand javascript coercion",
      "learn js type coercion",
      "javascript coercion playground",
      "test javascript equality online",
      "javascript equality tester",
      "== vs === performance",
      "should i use == or === in javascript",
      "when to use loose equality javascript",
      "javascript object is vs ===",
      "object.is vs strict equality",
      "javascript NaN comparison",
      "compare values javascript tool",
      "js equality step by step",
      "visualize javascript equality",
      "javascript type coercion examples",
      "javascript truthy falsy values",
      "falsy values javascript list",
      "javascript coercion rules",
      "ecmascript toprimitive explained",
      "javascript valueof tostring coercion",
      "double equals javascript explained"
    ],
  };

export default seo;
