import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSON to Excel - Free Online JSON to XLSX Tool | IconVault",
    metaDescription: "Convert JSON arrays into real .xlsx Excel workbooks with named sheets and instant download. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **JSON to Excel** converter turns your **JSON data** into a genuine **Excel workbook (.xlsx)** you can download and open in **Microsoft Excel**, **LibreOffice** or **Google Sheets**. Paste an array of objects, name your **sheet**, and get a properly formatted spreadsheet with headers, typed cells and auto-sized columns.",
      "Unlike CSV exports, a real **xlsx file** preserves data types, so numbers stay numbers and dates stay dates, and you can import it anywhere without delimiter surprises. The workbook is built **fully in your browser** with nothing uploaded, keeping private datasets local, and it is **free** to try (heavy repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "How do I convert JSON to Excel?", a: "Paste a JSON array of objects, optionally set the sheet name, and click convert. The tool generates a real .xlsx workbook that you can download and open in Excel, Google Sheets or LibreOffice." },
      { q: "Is this a real xlsx file or just CSV?", a: "It is a genuine xlsx workbook with sheets, typed cells and headers, not a CSV with a renamed extension. Numbers, booleans and dates keep their types instead of arriving as plain text." },
      { q: "Can I name the worksheet?", a: "Yes. The tool lets you set the sheet name before converting, which is handy when you build workbooks for reports, clients or imports that expect a specific tab name." },
      { q: "How are nested objects exported?", a: "Nested objects are flattened into dotted column paths such as user.name, so every row has the same columns and the sheet opens correctly. Arrays are kept readable in their cells." },
      { q: "Is my data uploaded anywhere?", a: "No. The workbook is generated entirely in your browser with JavaScript. Your data never leaves your device, so it is safe for sensitive reports and client data." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "json to excel",
      "json to excel converter",
      "convert json to excel online",
      "json to xlsx",
      "json to xlsx converter",
      "json to excel online free",
      "json array to excel",
      "export json to excel",
      "download excel from json",
      "json to spreadsheet xlsx",
      "json to excel file download",
      "json data to xlsx",
      "json to excel sheet",
      "json to excel with headers",
      "json to workbook",
      "create excel from json",
      "generate xlsx from json",
      "json to excel free",
      "online json to xlsx converter",
      "json to excel no signup",
      "json to excel private",
      "json to excel without upload",
      "api json to excel",
      "convert api response to excel",
      "rest api to excel",
      "nested json to excel",
      "flatten json to excel",
      "json to excel multiple sheets",
      "json to xls",
      "json to xls converter",
      "json to openoffice",
      "json to libreoffice calc",
      "json to google sheets xlsx",
      "json to excel typed cells",
      "json numbers to excel",
      "json dates to excel",
      "json to excel column names",
      "json keys to excel columns",
      "json to excel batch",
      "large json to excel",
      "json lines to excel",
      "jsonl to excel",
      "json to excel formatter",
      "pretty json to excel",
      "json to excel copy paste",
      "best json to excel converter",
      "json to excel for reports",
      "json to excel download free",
      "json to excel online tool",
      "json object to excel row",
      "json to excel autofit columns"
    ],
  };

export default seo;
