import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSONPath Tester - Free Online JSONPath Evaluator Tool | IconVault",
    metaDescription: "Test JSONPath expressions against your JSON with live matched results and syntax help. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **JSONPath Tester** lets you write and test **JSONPath expressions** against real JSON with instant feedback. Paste your document, type a path like `$.store.book[*].title`, and see the **matched values** update live, so you can debug selectors for **APIs**, **ETL pipelines** and **configuration** without running code.",
      "The tester supports the full JSONPath syntax: **child operators**, **recursive descent**, **wildcards**, **array slices** and **filter expressions**. It shows how many matches each expression returns and highlights the result, and everything is evaluated **fully in your browser** with nothing uploaded. It is **free** to try (heavy repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "What is JSONPath?", a: "JSONPath is a query language for JSON, similar to XPath for XML. Expressions like $.store.book[0].title navigate into a document and return the matching values, and many APIs, logging tools and test frameworks use them to extract data." },
      { q: "How do I test a JSONPath expression?", a: "Paste your JSON document into the input area and type your JSONPath expression. The matched values appear instantly, so you can iterate on the selector until it returns exactly what you want." },
      { q: "Does it support filters and wildcards?", a: "Yes. Wildcards (*), recursive descent (..), array slices ([0:3]) and filter expressions ([?(@.price < 10)]) are supported, along with the standard child and bracket operators." },
      { q: "What if my expression matches nothing?", a: "The tool shows zero matches clearly, which usually means a typo in a key name, a wrong array index, or a filter that excludes everything. Try shortening the expression to find where the path stops matching." },
      { q: "Is my JSON uploaded anywhere?", a: "No. Expression evaluation happens entirely in your browser with JavaScript. Your documents never leave your device, so it is safe for production payloads." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "jsonpath tester",
      "jsonpath online",
      "jsonpath evaluator",
      "test jsonpath online",
      "jsonpath expression tester",
      "json path finder",
      "jsonpath query tool",
      "jsonpath playground",
      "jsonpath checker",
      "jsonpath validator",
      "jsonpath free",
      "jsonpath syntax",
      "jsonpath examples",
      "jsonpath cheat sheet",
      "jsonpath wildcard",
      "jsonpath recursive descent",
      "jsonpath filter expression",
      "jsonpath array slice",
      "jsonpath $ syntax",
      "jsonpath store book example",
      "jsonpath query builder",
      "build jsonpath expression",
      "jsonpath debug",
      "debug jsonpath expression",
      "jsonpath not working",
      "jsonpath returns nothing",
      "jsonpath match count",
      "jsonpath online free no signup",
      "jsonpath without upload",
      "jsonpath private",
      "evaluate jsonpath in browser",
      "jsonpath javascript",
      "jsonpath npm alternative online",
      "jsonpath for api testing",
      "extract data with jsonpath",
      "jsonpath selector",
      "jsonpath dot notation",
      "jsonpath bracket notation",
      "jsonpath child operator",
      "jsonpath union",
      "jsonpath script expression",
      "jsonpath current node",
      "jsonpath root",
      "jsonpath tutorial",
      "learn jsonpath",
      "jsonpath vs jq",
      "jq vs jsonpath",
      "jsonpath in postman",
      "postman jsonpath test",
      "jsonpath for rest api",
      "jsonpath expression examples",
      "jsonpath live preview"
    ],
  };

export default seo;
