import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSON to Types - Free Online Type Generator Tool | IconVault",
    metaDescription: "Generate TypeScript, Go, Python, Rust and C# types from JSON with one paste. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **JSON to Types** converts any **JSON document** into **type definitions** for five languages: **TypeScript interfaces**, **Go structs**, **Python dataclasses**, **Rust structs** and **C# classes**. Paste API JSON, pick your language, name the root type, and get clean, idiomatic code with inferred **types**, nested definitions and **nullable** handling.",
      "It is the fastest way to build **typed API clients**, **DTOs** and **data models** without hand-translating JSON key by key. Nested objects become separate types, arrays become typed collections, and naming follows each language's conventions. Everything runs **fully in your browser** with nothing uploaded, and it is **free** to try (heavy repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "Which languages can I generate types for?", a: "TypeScript (interfaces), Go (structs), Python (dataclasses), Rust (structs) and C# (classes). Paste your JSON once and switch between language tabs to get each flavor." },
      { q: "How do I generate TypeScript interfaces from JSON?", a: "Paste your JSON, select the TypeScript tab and set a root interface name. The tool emits interfaces with inferred property types and nested interfaces for nested objects." },
      { q: "How does it name nested types?", a: "Nested objects become their own named types derived from the property name, following each language's naming conventions (PascalCase in TypeScript, Go and C#, snake-friendly names in Python, and Rust conventions in Rust output)." },
      { q: "Can I rename the root type?", a: "Yes. Set the root name before generating and all nested type names are derived consistently, so the output drops straight into your codebase." },
      { q: "Is my JSON uploaded anywhere?", a: "No. Type generation runs entirely in your browser with JavaScript. Your JSON never leaves your device, so it is safe for proprietary API payloads." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "json to types",
      "json to typescript",
      "json to ts",
      "json to typescript interface",
      "convert json to typescript",
      "json to interface online",
      "json to go",
      "json to golang struct",
      "json to go struct online",
      "json to python",
      "json to python dataclass",
      "json to python class",
      "json to rust",
      "json to rust struct",
      "json to c# types",
      "json to type definitions",
      "generate types from json",
      "json schema to types",
      "json to dto",
      "json to data model",
      "api json to types",
      "rest api json to typescript",
      "json to typed client",
      "json to typescript free",
      "json to typescript online free",
      "json to go online free",
      "json to python online free",
      "json to rust online free",
      "nested json to types",
      "json to types no signup",
      "json to types private",
      "json to types without upload",
      "json type generator",
      "json to interface generator",
      "typescript interface generator",
      "go struct generator from json",
      "python dataclass generator",
      "rust struct from json",
      "json to model class",
      "json to types tool",
      "best json to typescript converter",
      "json to ts interface online",
      "json to typescript with optional",
      "json to typescript nullable",
      "json to go json tags",
      "json to python type hints",
      "json to rust serde",
      "json to c# from types",
      "json to types copy paste",
      "json to types for developers",
      "json to multiple languages"
    ],
  };

export default seo;
