import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSON to XML - Free Online JSON XML Converter Tool | IconVault",
    metaDescription: "Convert JSON to XML and XML back to JSON instantly in your browser. Custom root element, copy and download. Free, nothing uploaded.",
    about: [
      "**IconVault**'s **JSON to XML** converter translates data between the two formats in one click. **JSON to XML** uses a **custom serializer** with proper **XML escaping** and a **customizable root element**, and arrays become repeated elements using the **singular** of the key name, so tags becomes tag.",
      "**XML to JSON** parses your markup with the browser's **DOMParser** and rebuilds it as **pretty-printed JSON**. One honest note: **XML has no data types**, so numbers and booleans come back as strings. Everything runs **fully in your browser** with nothing uploaded, it is **free** to try (heavy repeated use may ask for **Pro**), and you can **copy** the result or **download** it as a file."
    ],
    faqs: [
      { q: "What does this converter do?", a: "It converts JSON to XML and XML to JSON. Switch modes with the tabs, paste your input, and the tool produces the other format with pretty printing." },
      { q: "What happens to arrays when converting JSON to XML?", a: "Each array item becomes a repeated element using the singular of the key name, so a tags array becomes repeated tag elements." },
      { q: "Do numbers and booleans survive XML to JSON conversion?", a: "No. XML has no data types, so everything comes back as strings. A 29 in XML becomes the string 29 in JSON." },
      { q: "Can I change the root element name?", a: "Yes. In JSON to XML mode you can set any root element name, and it is sanitized to a valid XML tag name automatically." },
      { q: "Is my data uploaded anywhere?", a: "No. Conversion happens locally in your browser, so it is safe for sensitive payloads and internal API data." },
      { q: "Is it really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "json to xml",
      "json to xml converter",
      "convert json to xml online",
      "json to xml online",
      "json to xml converter online",
      "json to xml free",
      "xml to json",
      "xml to json converter",
      "convert xml to json online",
      "xml to json online",
      "xml to json converter online",
      "xml to json free",
      "json xml converter",
      "json xml converter online",
      "json and xml converter",
      "convert between json and xml",
      "json to xml tool",
      "xml to json tool",
      "free json to xml",
      "free xml to json",
      "json to xml with root element",
      "custom root element xml",
      "json array to xml elements",
      "json to xml pretty",
      "pretty xml from json",
      "format xml output",
      "xml from json generator",
      "generate xml from json",
      "xml to json pretty print",
      "parse xml to json",
      "xml parser online",
      "xml parser to json",
      "domparser xml to json",
      "json to xml api",
      "json to xml for api",
      "soap json to xml",
      "rest json xml conversion",
      "json xml data conversion",
      "data format converter",
      "json xml translation",
      "convert data format online",
      "json to xml no signup",
      "xml to json no signup",
      "online json converter",
      "online xml converter",
      "json to xml escaped",
      "xml escaping json values",
      "json special characters to xml",
      "xml to json string types",
      "numbers become strings xml to json",
      "xml has no data types",
      "json to xml javascript",
      "client side json xml converter",
      "browser json xml converter"
    ],
  };

export default seo;
