import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSON to C# - Free Online JSON to C# Class Tool | IconVault",
    metaDescription: "Generate C# classes from JSON with properties, types and attributes, or convert C# back to JSON. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **JSON to C#** generator turns any **JSON document** into clean, ready-to-compile **C# classes**: **PascalCase properties**, correct **value and reference types**, **nullable** annotations where the data demands them, and nested objects become their own **class definitions** automatically. Paste API JSON and get your **data models** without hand-writing them.",
      "It also works in reverse: paste a **C# class with auto-properties** and get a sample **JSON object** back, which is handy for mocking responses and testing serializers. Everything runs **fully in your browser** with nothing uploaded, and it is **free** to try (heavy repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "How do I generate C# classes from JSON?", a: "Paste your JSON into the input box. The tool emits C# class definitions with PascalCase property names, inferred types, nullable annotations where values were null, and separate classes for nested objects." },
      { q: "How does it handle nested objects and arrays?", a: "Nested objects become their own named classes, and arrays become List<T> with the element type inferred from the data. Deeply nested documents produce a complete set of classes that compile together." },
      { q: "Can I convert a C# class back to JSON?", a: "Yes. Switch to the C#-to-JSON tab and paste a class with auto-properties. The tool returns a sample JSON object with sensible placeholder values for each property, useful for mocking API responses." },
      { q: "Does it support nullable reference types?", a: "Yes. Properties that were null in the JSON are emitted as nullable types, which keeps the generated code compatible with nullable reference type contexts." },
      { q: "Is my code uploaded anywhere?", a: "No. Generation runs entirely in your browser with JavaScript. Your JSON and classes never leave your device, so it is safe for proprietary APIs and models." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "json to c#",
      "json to csharp",
      "json to c# class",
      "convert json to c#",
      "json to c# online",
      "json to c# class generator",
      "json to c# online free",
      "json to csharp class online",
      "generate c# classes from json",
      "json to poco",
      "json to c# poco generator",
      "json to c# model",
      "json to c# data model",
      "api json to c#",
      "rest api json to c#",
      "json to c# properties",
      "json to c# pascalcase",
      "json to c# nullable",
      "json to c# list",
      "json array to c#",
      "nested json to c#",
      "json to c# free",
      "json to c# no signup",
      "json to c# private",
      "json to c# without upload",
      "c# to json",
      "c# class to json",
      "convert c# class to json",
      "c# to json online",
      "c# object to json sample",
      "c# model to json",
      "generate json from c# class",
      "c# auto properties to json",
      "json c# converter",
      "c# json converter online",
      "json to csharp code",
      "json to .net class",
      "json to dotnet model",
      "json to c# newtonsoft",
      "json to c# system.text.json",
      "json to c# attributes",
      "jsonproperty c# generator",
      "json to c# record",
      "json to c# struct",
      "json to c# copy paste",
      "json to c# tool",
      "best json to c# converter",
      "json to c# for unity",
      "json to c# for asp.net",
      "json to c# visual studio"
    ],
  };

export default seo;
