import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSON Tree Viewer - Free Online JSON Tree Explorer Tool | IconVault",
    metaDescription: "Paste or upload JSON and explore it as a collapsible tree with search, JSONPath copy and key stats. Free, runs 100% in your browser.",
    about: [
      "**IconVault**'s **JSON Tree Viewer** turns pasted or uploaded **JSON** into an interactive **collapsible tree**. Nodes **expand and collapse**, nested **arrays and objects** stay readable at a glance, and you can **search keys and values** with match highlighting, so huge API responses and config files stop being walls of text.",
      "Every **tree node** is clickable to copy its **JSONPath** for use in code, and the panel shows **key count**, **maximum depth** and **file size** so you know what you are working with. Parsing, search and rendering all happen **fully in your browser** with nothing uploaded. It is **free** to try (heavy repeated use may ask for **Pro**), and you can copy the **pretty-printed JSON** back out with one click."
    ],
    faqs: [
      { q: "What does the JSON Tree Viewer do?", a: "It parses the JSON you paste or upload and renders it as an expandable tree. You can expand and collapse nodes, search keys and values with highlighting, see key count, max depth and size, copy any node's JSONPath, and copy the formatted JSON back out." },
      { q: "Is my JSON uploaded to a server?", a: "No. Parsing and rendering happen entirely in your browser with JavaScript. Your data never leaves your device, so it is safe for sensitive payloads, logs and API responses." },
      { q: "How do I copy the JSONPath of a key?", a: "Just click any node in the tree. Its JSONPath, like $.store.books[0].title, is copied to your clipboard automatically." },
      { q: "Can it handle very large JSON files?", a: "It handles typical files fine, but very large files (10 MB and up) may render slowly because every node becomes a DOM element. For such files, the search box and collapse-all are the fastest way to find what you need." },
      { q: "What happens if my JSON is invalid?", a: "The tool shows an invalid JSON error with the parser's message instead of rendering, so you can fix the syntax and try again." },
      { q: "Is it really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "json viewer",
      "json viewer online",
      "view json online",
      "json tree viewer",
      "json tree view online",
      "online json explorer",
      "json file viewer",
      "json data viewer",
      "json visualizer",
      "json visualizer online",
      "json formatter online",
      "format json online",
      "beautify json online",
      "json prettifier",
      "json prettifier online",
      "json pretty print",
      "json pretty print online",
      "view json in browser",
      "json explorer",
      "json tree",
      "json tree visualizer",
      "json tree view",
      "json hierarchy viewer",
      "json structure viewer",
      "json path finder",
      "jsonpath copy",
      "jsonpath generator online",
      "jsonpath tester",
      "find jsonpath of key",
      "copy json path",
      "json search online",
      "search json file",
      "search inside json",
      "json key search",
      "json validator online",
      "validate json online",
      "check json validity",
      "is my json valid",
      "json parse online",
      "parse json",
      "json parser",
      "json parser online",
      "json reader online",
      "read json file online",
      "open json file online",
      "json file opener",
      "large json viewer",
      "view large json file",
      "json depth analyzer",
      "json key counter",
      "json node explorer",
      "collapse expand json",
      "json tree collapse",
      "json outline viewer",
      "free json viewer",
      "json viewer no signup",
      "json viewer free online",
      "json formatter no ads",
      "pretty json free tool",
      "json minify and format",
      "json formatter and viewer",
      "json code viewer",
      "inspect json online",
      "json api response viewer",
      "api json viewer",
      "view api json response"
    ],
  };

export default seo;
