import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSON String Converter - Free Online JSON Escape Tool | IconVault",
    metaDescription: "Stringify JSON into escaped string literals and parse string literals back to JSON. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **JSON String Converter** moves data both ways between **JSON objects** and **escaped string literals**. **Stringify** mode takes raw JSON or text and produces a properly **escaped quoted string** with newlines, tabs and quotes handled, ready to embed in **code**, **seed scripts** or **JSON-in-JSON payloads**. **Parse** mode takes a quoted string literal and decodes it back to readable JSON.",
      "It takes care of the escapes developers get wrong: **unicode sequences**, escaped slashes, and quotes inside quotes all round-trip correctly. Conversion runs **fully in your browser** with nothing uploaded, and it is **free** to try (heavy repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "What does stringify mode do?", a: "Stringify mode takes raw text or JSON and outputs a quoted, escaped string literal, exactly like JSON.stringify produces. Newlines become \\n, tabs become \\t, and quotes and backslashes are escaped so the result is valid wherever a JSON string is expected." },
      { q: "What does parse mode do?", a: "Parse mode takes a quoted string literal, for example one copied from code or a log, and decodes the escape sequences back into readable text or JSON." },
      { q: "When would I need this?", a: "Common cases include embedding a JSON object inside another JSON payload, building seed data for tests, pasting JSON into a JavaScript or Python string, and decoding escaped strings found in logs or API responses." },
      { q: "Does it handle unicode escapes?", a: "Yes. Unicode escape sequences are encoded and decoded correctly, and special characters survive the round trip without corruption." },
      { q: "Is my data uploaded anywhere?", a: "No. The conversion runs entirely in your browser with JavaScript. Your strings never leave your device." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "json string converter",
      "json stringify online",
      "json string escape",
      "escape json string",
      "unescape json string",
      "json string literal",
      "json to escaped string",
      "escaped string to json",
      "json encode string",
      "json decode string",
      "stringify json online",
      "parse json string online",
      "json string parser",
      "json string formatter",
      "json string free",
      "json escape quotes",
      "json escape newlines",
      "json escape backslash",
      "json escape unicode",
      "json \\n escape",
      "json string with quotes",
      "embed json in json",
      "json inside json string",
      "json in json payload",
      "stringify json for code",
      "json to javascript string",
      "json to python string",
      "json string seed data",
      "json string test data",
      "json string no signup",
      "json string private",
      "json string without upload",
      "json string online free",
      "json string tool",
      "json stringify pretty",
      "json stringify unquoted",
      "json string decode online",
      "decode escaped json",
      "unescape json online",
      "json escape tool online",
      "json string literal generator",
      "convert text to json string",
      "json string copy paste",
      "json string round trip",
      "json stringify vs parse",
      "json string escape characters",
      "json string special characters",
      "json string tab escape",
      "json string carriage return",
      "json string forward slash"
    ],
  };

export default seo;
