import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSON Diff - Free Online JSON Comparison Tool | IconVault",
    metaDescription: "Compare two JSON documents side by side and see added, removed and changed keys highlighted. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **JSON Diff** compares two **JSON documents** and shows exactly what changed. Paste the original and the modified version to get a clean **side-by-side diff** where **added keys**, **removed keys** and **changed values** are highlighted line by line, so you can review API responses, config changes and data migrations in seconds.",
      "The diff understands JSON structure, not just text: reordered keys can be ignored, **nested objects** and **arrays** are compared recursively, and formatting differences do not show up as false changes. Everything runs **fully in your browser** with nothing uploaded, and it is **free** to try (heavy repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "How do I compare two JSON files?", a: "Paste the original JSON on the left and the modified JSON on the right. The tool highlights added, removed and changed keys and values, so you can spot every difference without reading both documents." },
      { q: "Does it compare JSON semantically or as plain text?", a: "Semantically. It parses both documents and compares the actual structure recursively, so key order and whitespace differences do not create noise the way a plain text diff would." },
      { q: "Can it ignore key order?", a: "Yes. Because the comparison is structural, reordering keys does not register as a change. Only real additions, removals and value changes are reported." },
      { q: "What is JSON Diff useful for?", a: "Common uses include comparing API responses between environments, reviewing config file changes before deploys, verifying database migrations, and debugging why a frontend receives different data than expected." },
      { q: "Is my JSON uploaded anywhere?", a: "No. The comparison runs entirely in your browser with JavaScript. Your documents never leave your device, so it is safe for production configs and sensitive payloads." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "json diff",
      "json diff online",
      "json diff checker",
      "compare json online",
      "json compare tool",
      "json difference finder",
      "compare two json files",
      "json diff viewer",
      "json diff free",
      "online json comparator",
      "json text compare",
      "diff json files online",
      "json file comparison",
      "json vs json compare",
      "json changes between versions",
      "find differences in json",
      "json diff side by side",
      "json added removed changed",
      "json semantic diff",
      "deep compare json",
      "recursive json comparison",
      "json object comparison",
      "compare json responses",
      "api response diff",
      "compare api json outputs",
      "json config diff",
      "compare config files json",
      "json diff no signup",
      "json diff private",
      "json diff without upload",
      "json diff tool free",
      "json pretty diff",
      "visual json diff",
      "json diff highlight",
      "json key differences",
      "json value changed",
      "nested json diff",
      "json array diff",
      "compare json arrays",
      "json diff ignore order",
      "json diff ignore key order",
      "json merge diff",
      "json patch generator",
      "json diff to patch",
      "json diff online free no login",
      "json compare and merge",
      "best json diff tool",
      "json diff for developers",
      "json diff copy paste",
      "json diff download results",
      "json diff large files"
    ],
  };

export default seo;
