import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSON to CSV - Free Online JSON Converter Tool | IconVault",
    metaDescription: "Convert JSON to CSV and CSV back to JSON instantly with column mapping and download. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **JSON to CSV** converter turns structured **JSON data** into a clean **CSV spreadsheet** in one click, and converts **CSV back to JSON** just as easily. Paste an array of objects and get properly quoted, escaped **comma-separated values** with the headers as the first row, ready to open in **Excel** or **Google Sheets**, or download the result directly.",
      "The converter handles the tricky parts: **nested objects** are flattened with dotted paths, values containing commas or quotes are escaped per the CSV spec, and round-trips preserve your data types. Conversion happens **fully in your browser** with nothing uploaded, so private datasets stay private, and it is **free** to try (heavy repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "How do I convert JSON to CSV?", a: "Paste a JSON array of objects into the input box and the tool immediately generates CSV with the object keys as header columns. You can then copy the result or download it as a .csv file." },
      { q: "Can I convert CSV back to JSON?", a: "Yes. Switch to the CSV-to-JSON direction, paste your CSV, and it becomes a JSON array of objects with each row mapped to its column headers." },
      { q: "How are nested objects handled?", a: "Nested objects are flattened using dotted key paths, so {\"user\": {\"name\": \"Ava\"}} becomes a column named user.name. This keeps every row the same shape so the CSV opens correctly in spreadsheets." },
      { q: "What if my JSON values contain commas or quotes?", a: "Values with commas, quotes or newlines are wrapped in double quotes and inner quotes are doubled, following standard CSV escaping rules, so spreadsheets parse them back into single cells." },
      { q: "Is my data uploaded anywhere?", a: "No. The conversion runs entirely in your browser with JavaScript. Your data never leaves your device, which makes it safe for sensitive exports and client datasets." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "json to csv",
      "json to csv converter",
      "convert json to csv online",
      "json to csv online free",
      "json array to csv",
      "turn json into csv",
      "json to csv file",
      "download csv from json",
      "csv to json",
      "csv to json converter",
      "convert csv to json online",
      "csv to json online free",
      "csv to json array",
      "json csv converter free",
      "online json to csv converter",
      "json to spreadsheet",
      "json to excel csv",
      "json to google sheets",
      "import json to google sheets",
      "json to tsv",
      "json to tab separated values",
      "nested json to csv",
      "flatten json to csv",
      "json flatten online",
      "json to csv with headers",
      "json keys as csv headers",
      "json to csv download",
      "save json as csv",
      "export json to csv",
      "api json to csv",
      "convert api response to csv",
      "rest api to csv",
      "json data to csv",
      "large json to csv",
      "json lines to csv",
      "jsonl to csv converter",
      "json to csv without upload",
      "json to csv private",
      "json to csv no signup",
      "csv json converter tool",
      "free csv to json tool",
      "json to csv batch",
      "json object to csv row",
      "json to csv delimiter",
      "json to semicolon separated",
      "json to csv quote escaping",
      "csv escape quotes",
      "json to csv formatter",
      "pretty json to csv",
      "json to csv copy paste",
      "online data format converter"
    ],
  };

export default seo;
