import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JSON Schema Validator - Free Online JSON Validation Tool | IconVault",
    metaDescription: "Validate JSON against a JSON Schema with clear error messages, or generate a schema from JSON. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **JSON Schema Validator** checks your **JSON document** against a **JSON Schema** and reports exactly what fails: which property is wrong, which **type** was expected, and which **required field** is missing. It is the fastest way to debug **API payloads**, **config files** and **data contracts** before they break something downstream.",
      "No schema yet? Generate one from your JSON in a single click, then tighten it with **required fields**, **enums**, **formats** and **patterns**. Validation runs **fully in your browser** with nothing uploaded, so production data stays local, and it is **free** to try (heavy repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "How do I validate JSON against a schema?", a: "Paste the JSON document into the instance box and your JSON Schema into the schema box. The tool lists every validation error with the failing path, the expected type or constraint, and the actual value." },
      { q: "Can I generate a schema from my JSON?", a: "Yes. Paste a sample JSON document and click generate to get a draft schema describing its structure. You can then mark fields required, add enums and patterns, and re-validate against the tightened schema." },
      { q: "What is JSON Schema used for?", a: "JSON Schema describes the expected shape of JSON data: property types, required fields, allowed values, string formats and numeric ranges. APIs, config systems and data pipelines use it to catch malformed payloads early." },
      { q: "Which JSON Schema draft is supported?", a: "The validator follows the modern JSON Schema vocabulary for type checking, required properties, enums, patterns, formats, minimums and maximums, and nested object and array constraints." },
      { q: "Is my data uploaded anywhere?", a: "No. Validation runs entirely in your browser with JavaScript. Your JSON and schemas never leave your device, which makes it safe for proprietary payloads." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "json schema validator",
      "json schema validator online",
      "validate json against schema",
      "json schema validation online",
      "json schema checker",
      "json schema tester",
      "json validator",
      "json validate online",
      "json schema online free",
      "json schema generator",
      "generate json schema from json",
      "json to json schema",
      "create json schema online",
      "json schema builder",
      "json schema draft",
      "json schema example",
      "json schema required",
      "json schema type",
      "json schema enum",
      "json schema pattern",
      "json schema format",
      "json schema properties",
      "json schema array",
      "json schema nested object",
      "validate api response schema",
      "api payload validation",
      "json contract testing",
      "json schema for rest api",
      "openapi json schema",
      "json schema tutorial",
      "learn json schema",
      "json schema cheat sheet",
      "json schema error messages",
      "json validation errors",
      "json schema required field missing",
      "json schema type mismatch",
      "json schema no signup",
      "json schema validator free",
      "json schema private",
      "json schema without upload",
      "validate json in browser",
      "json schema playground",
      "test json schema online",
      "json schema lint",
      "json schema debug",
      "json schema best practices",
      "json schema for config files",
      "json config validation",
      "json schema ajv online",
      "json schema oneof anyof",
      "json schema allof",
      "json schema additionalproperties"
    ],
  };

export default seo;
