import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "JWT Builder - Free Online JWT Token Generator Tool | IconVault",
    metaDescription: "Build and sign HS256, HS384 and HS512 JWTs in your browser, then decode and verify them. Free. Testing only, never paste production secrets.",
    about: [
      "**IconVault**'s **JWT Builder** lets you create and inspect **JSON Web Tokens** without a server. Enter a **header** and **payload** as JSON, pick **HS256**, **HS384** or **HS512**, add a **secret**, and the tool signs the token with **WebCrypto HMAC** in your browser. The result is decoded back into readable **header** and **payload** panels, and the **signature** is verified by re-signing, so you can see exactly what each part of the token contains.",
      "Handy helpers include **iat = now** and **exp = +1h** timestamp buttons and a show/hide secret toggle, and you can **copy** the finished token with one click. Everything runs **fully in your browser** and it is **free** to try (heavy repeated use may ask for **Pro**). One hard rule: this tool is **for testing only**. Never paste **production secrets** or real user tokens here, and treat anything you paste as potentially visible."
    ],
    faqs: [
      { q: "What does the JWT Builder do?", a: "It builds a JSON Web Token from a header and payload you type as JSON, signs it with HS256, HS384 or HS512 using your secret, then decodes it back and verifies the signature." },
      { q: "Can I use it with production secrets?", a: "No. It is built for testing only. Everything runs locally, but you should never paste production secrets or real user tokens into any browser tool." },
      { q: "Which algorithms are supported?", a: "HS256 (HMAC with SHA-256), HS384 and HS512. Asymmetric algorithms like RS256 and ES256 are not supported." },
      { q: "How does signature verification work?", a: "After signing, the tool decodes the header and payload, re-signs them with your secret, and compares the result to the original signature. If they match, the signature is verified." },
      { q: "What are the iat and exp buttons for?", a: "They set the issued-at claim to the current time and the expiry claim to one hour from now, so you can build realistic test tokens quickly." },
      { q: "Is it really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "jwt builder",
      "jwt builder online",
      "jwt generator",
      "jwt generator online",
      "generate jwt token",
      "generate jwt online",
      "jwt token generator",
      "create jwt token",
      "jwt signer",
      "sign jwt online",
      "jwt encoder",
      "jwt encoder online",
      "jwt decoder",
      "jwt decoder online",
      "decode jwt token",
      "jwt token decoder",
      "verify jwt signature",
      "jwt signature verifier",
      "jwt verify online",
      "hs256 jwt",
      "hs256 jwt generator",
      "hs512 jwt",
      "hs384 jwt",
      "hmac jwt signer",
      "json web token generator",
      "json web token decoder",
      "jwt.io alternative",
      "jwt token maker",
      "make jwt token",
      "build jwt token",
      "jwt header payload signature",
      "jwt payload editor",
      "jwt claims editor",
      "jwt exp iat",
      "jwt expiry generator",
      "test jwt token",
      "jwt testing tool",
      "free jwt tool",
      "jwt tool no signup",
      "jwt in browser",
      "client side jwt signer",
      "webcrypto jwt",
      "jwt token tester",
      "debug jwt token",
      "inspect jwt token",
      "jwt token inspector",
      "jwt debugger online",
      "jwt playground",
      "jwt sandbox",
      "create test jwt",
      "dummy jwt token",
      "sample jwt token",
      "jwt secret signer",
      "jwt base64url",
      "jwt token format"
    ],
  };

export default seo;
