import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Keyboard API Playground - Interactive Web API Lab | IconVault",
    metaDescription: "Explore the real Keyboard API: dump your layout map, inspect live key events, match shortcuts and detect dead keys. Free, runs in your browser.",
    about: [ "**IconVault**'s **Keyboard API Playground** uses the real **`navigator.keyboard`** interfaces: dump your full **layout map** to see which physical key produces which character, inspect live **keydown, keyup** events with `code`, `key`, modifiers and repeat flags, and test a **shortcut matcher** that recognizes combos as you type. A dead-key detector shows how accent composition behaves on your layout. It is free and runs fully in your browser.", "You will learn why `code` (the **physical key**) and `key` (the **produced character**) differ across layouts like QWERTY, AZERTY and Dvorak, and why **`getLayoutMap()`** is the right way to build shortcut help that stays correct in every language. The lab also covers the limits: the Keyboard API is **Chromium-only**, the layout map needs no permission, and locking the keyboard (`keyboard.lock()`) only works in fullscreen for specific keys." ],
    faqs: [ { q: "What is the difference between key and code?", a: "key is the character produced (changes with layout and Shift); code is the physical key position (stays the same). This lab shows both live for every press." }, { q: "What does getLayoutMap() return?", a: "A promise for a map from key codes to the characters your layout produces. Press Dump layout map in the lab to see yours." }, { q: "Which browsers support the Keyboard API?", a: "Chromium browsers (Chrome, Edge, Opera). Firefox and Safari do not implement navigator.keyboard, so the lab reports unsupported there." }, { q: "What are dead keys?", a: "Keys like ^ or the acute accent that produce no character alone but combine with the next letter (e becomes e with circumflex or acute). The lab detects and labels them as you type." }, { q: "How should I build keyboard shortcuts for all layouts?", a: "Match on code for position-based shortcuts (like WASD) and on key for character-based ones, and show the actual characters from getLayoutMap() in your shortcut help." }, { q: "Do key events work if the page is not focused?", a: "No. Browsers only deliver key events to the focused page, and keyboard.lock() additionally requires fullscreen. Nothing here can act as a keylogger." } ],
    tags: [ "keyboard api", "navigator.keyboard", "keyboard api javascript", "getlayoutmap", "keyboard layout map", "keydown keyup keypress", "keyboard event inspector", "javascript key events", "key vs code", "keyboardEvent code", "keyboardEvent key", "dead keys javascript", "detect dead keys", "keyboard shortcuts javascript", "shortcut matcher", "keyboard shortcut tester", "test keyboard online", "keyboard event tester", "keycode tester", "what is my keycode", "keyboard layout detector", "qwerty azerty dvorak", "keyboard api chrome", "keyboard lock api", "keyboard.lock", "mdn keyboard api", "keyboard api tutorial", "keyboard api example", "javascript keyboard layout", "international keyboard shortcuts", "handle keyboard shortcuts web", "preventdefault keydown", "key repeat javascript", "modifier keys javascript", "ctrl shift alt meta", "composition events", "keyboard events mdn", "is keyboard api supported", "caniuse keyboard api", "keyboard api firefox", "keyboard api safari", "keyboard typescript", "keyboard playground", "online keyboard tester", "key press visualizer", "keyboard event log", "web keyboard shortcuts best practices", "wasd key codes", "arrow key codes", "function key codes", "escape key javascript" ],
  };

export default seo;
