import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Keycode Tester - Free Online Key Event & KeyCode Tool | IconVault",
    metaDescription: "Press any key and see its key, code, keyCode, modifiers and location instantly. Free keyboard event tester that runs in your browser.",
    about: [
      "**IconVault**'s **Keycode Tester** shows the full **KeyboardEvent** details of any key you press. Click the capture area, press a key, and you instantly see its **key**, **code**, **keyCode**, **which**, **location** (general, left, right or numpad) and any **modifiers** (Ctrl, Shift, Alt, Meta), which is exactly what you need when debugging **keyboard shortcuts** or remapping keys.",
      "Every press is logged to a **history table** (the last 50 events) so you can compare keys and spot inconsistencies across **browsers** and layouts. Everything runs **fully in your browser** with nothing uploaded, it is **free** to try (heavy repeated use may ask for **Pro**), and there is no signup."
    ],
    faqs: [
      { q: "What details does it show for each key press?", a: "The key, code, keyCode, which, location (general, left, right or numpad), the active modifiers (Ctrl, Shift, Alt, Meta) and the time of the press." },
      { q: "What is the difference between key and code?", a: "key is the character produced by the press, while code is the physical key on the keyboard. On an AZERTY layout, pressing the key labeled Q gives key q but code KeyA. Use code when you care about position and key when you care about the character." },
      { q: "Does it work for modifier and function keys?", a: "Yes. Ctrl, Shift, Alt, Meta, F1 to F12, arrows, numpad keys and media keys all register, as long as the browser reports them." },
      { q: "Is keyCode deprecated?", a: "Yes, keyCode is deprecated in the web specification but it is still widely used in legacy code and games, which is why this tool shows it alongside the modern code property." },
      { q: "Is anything I press recorded anywhere?", a: "No. The history lives only in the page's memory and is cleared when you reload or close the tab. Nothing is sent anywhere." },
      { q: "Is it really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "keycode tester",
      "keycode tester online",
      "keyboard event tester",
      "key code finder",
      "keycode finder",
      "what is my keycode",
      "check keycode",
      "keycode checker",
      "keyboard key tester",
      "test keyboard keys",
      "keyboard tester online",
      "press key to see keycode",
      "javascript keycode",
      "js keycode",
      "event.keycode",
      "event.key vs event.code",
      "key vs code javascript",
      "keyboard event properties",
      "keycode of enter",
      "keycode of space",
      "keycode of escape",
      "keycode of arrow keys",
      "keycode of f1",
      "keycode list",
      "javascript keycode table",
      "key codes list",
      "keyboard key codes",
      "keycode 13",
      "keycode 27",
      "keycode 32",
      "keycode 37 38 39 40",
      "which vs keycode",
      "event.which",
      "key location javascript",
      "keyboard location numpad",
      "detect modifier keys",
      "ctrl shift alt key test",
      "keyboard shortcut debugger",
      "debug keyboard shortcuts",
      "test function keys",
      "f keys tester",
      "media keys tester",
      "keyboard input tester",
      "browser key tester",
      "online keyboard tester",
      "free keycode tool",
      "keycode tool no signup",
      "keyboard event logger",
      "key press logger",
      "key history table",
      "remap keys find code",
      "game keycode tester"
    ],
  };

export default seo;
