import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Kubernetes YAML Generator - Free Online K8s Manifest Tool | IconVault",
    metaDescription: "Generate Kubernetes YAML for Deployment, Service, Ingress and CronJob with a live preview. Copy or download. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Kubernetes YAML Generator** builds **valid Kubernetes manifests** from a simple form. Configure a **Deployment** (image, **replicas**, **container port**, **environment variables**, **resource requests and limits**), a **Service** (**ClusterIP**, **NodePort** or **LoadBalancer**), an **Ingress** (**host**, **path**, **TLS**) and a **CronJob** (**cron schedule**, **command**), and the **live multi-doc preview** updates as you type.",
      "Names are **sanitized** to valid **lowercase DNS names** automatically, you can toggle each resource in or out of the output, then **copy** the YAML or **download** it as **k8s.yaml**, ready for kubectl apply -f. Everything runs **fully in your browser** and it is **free** to try (heavy repeated use may ask for **Pro**). Always review generated manifests against your cluster's policies before applying them to production."
    ],
    faqs: [
      { q: "Which Kubernetes resources can it generate?", a: "Deployment, Service, Ingress and CronJob. Each one has its own tab and can be toggled in or out of the generated multi-document YAML." },
      { q: "How do I apply the generated YAML?", a: "Download it as k8s.yaml and run kubectl apply -f k8s.yaml against your cluster." },
      { q: "Does it support resource requests and limits?", a: "Yes. The Deployment tab has a toggle for CPU and memory requests and limits, with sensible defaults you can override." },
      { q: "Are resource names sanitized?", a: "Yes. App names are automatically converted to valid lowercase DNS names, since Kubernetes rejects uppercase letters and most special characters." },
      { q: "Is the generated YAML production ready?", a: "It is syntactically valid, but you should review it against your cluster's ingress controller, networking, security policies and quota before applying it to production." },
      { q: "Is it really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "kubernetes yaml generator",
      "k8s yaml generator",
      "kubernetes manifest generator",
      "k8s manifest generator",
      "kubernetes yaml builder",
      "generate kubernetes yaml",
      "create k8s yaml online",
      "kubernetes deployment generator",
      "k8s deployment yaml generator",
      "kubernetes deployment yaml",
      "generate deployment yaml",
      "kubernetes service generator",
      "k8s service yaml",
      "kubernetes ingress generator",
      "k8s ingress yaml",
      "kubernetes cronjob generator",
      "k8s cronjob yaml",
      "kubectl yaml generator",
      "kubectl apply yaml",
      "kubernetes yaml online",
      "k8s yaml online",
      "free kubernetes yaml generator",
      "kubernetes config generator",
      "k8s config generator",
      "deployment yaml example",
      "service yaml example",
      "ingress yaml example",
      "cronjob yaml example",
      "kubernetes yaml template",
      "k8s yaml template",
      "multi doc yaml kubernetes",
      "kubernetes yaml copy",
      "download k8s yaml",
      "kubernetes replicas yaml",
      "kubernetes env variables yaml",
      "kubernetes resource limits yaml",
      "cpu memory requests limits yaml",
      "kubernetes tls ingress yaml",
      "clusterip nodeport loadbalancer yaml",
      "kubernetes namespace yaml",
      "cron schedule kubernetes",
      "kubernetes command yaml",
      "k8s beginner tool",
      "learn kubernetes yaml",
      "kubernetes yaml visual builder",
      "no code kubernetes yaml",
      "kubernetes yaml form",
      "k8s manifest builder",
      "generate k8s manifests",
      "kubernetes deployment service ingress",
      "devops yaml generator",
      "k8s yaml no signup",
      "kubernetes tool free online",
      "sanitize k8s names",
      "valid kubernetes names"
    ],
  };

export default seo;
