import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Launch Handler Playground - Interactive Web API Lab | IconVault",
    metaDescription: "Learn the Launch Handler API: real launchQueue consumer, launch parameter inspection and a PWA manifest generator with client modes. Free, in your browser.",
    about: [ "**IconVault**'s **Launch Handler Playground** demystifies the **Launch Handler API** for installed web apps: a working **`launchQueue.setConsumer()`** you can trigger, inspection of **launch parameters** (target URL, handled files, share data), and a **manifest generator** that writes the `launch_handler` block with the right **client mode** (`auto`, `navigate-new`, `navigate-existing`, `focus-existing`). It is free and runs fully in your browser.", "Launch handling only applies to **installed PWAs** in Chromium, so the lab simulates launches while teaching the real API surface: how `client_mode` decides whether a link opens a new window or reuses one, how **file handlers** receive launched files, and how to test the flow locally before shipping. You will also see the manifest validation rules that silently fall back to defaults when the JSON is wrong." ],
    faqs: [ { q: "What does the Launch Handler API do?", a: "It lets an installed PWA control what happens when it is launched: open a new window, navigate the existing one, or just focus it, based on the launch_handler client_mode in the manifest." }, { q: "What are the client_mode values?", a: "auto (browser decides), navigate-new, navigate-existing, navigate-self and focus-existing. The manifest generator in this lab explains each and writes valid JSON." }, { q: "What is launchQueue?", a: "A queue the browser fills with LaunchParams every time your app is launched. Your app calls launchQueue.setConsumer() once to receive them, including targetURL and files." }, { q: "Can a normal website use launch handling?", a: "No. The API only applies to installed web apps in Chromium browsers. This lab simulates launches so you can learn the API without installing anything." }, { q: "How do file handlers relate to launch params?", a: "If your manifest declares file_handlers, launched files arrive inside LaunchParams.files, and the lab shows how to read them." }, { q: "Do I need to ship this to test it?", a: "No. The playground simulates launch events and validates your manifest JSON locally, so you can iterate before deploying." } ],
    tags: [ "launch handler api", "launch handler pwa", "launchqueue", "launchqueue.setconsumer", "launchparams", "pwa launch handler", "client_mode", "launch_handler manifest", "web app launch", "installed pwa launch", "navigate-new", "navigate-existing", "focus-existing", "pwa manifest generator", "launch handler example", "launch handler tutorial", "launch handler javascript", "mdn launch handler", "pwa deep linking", "handle pwa launch", "pwa file handlers", "launchparams files", "targeturl launch", "share target pwa", "web app manifest launch", "pwa window management", "pwa single window", "pwa multiple windows", "chromium pwa apis", "pwa capabilities", "project fugu", "fugu apis", "launch handler caniuse", "is launch handler supported", "launch handler chrome", "launch handler typescript", "pwa manifest validator", "manifest json launch_handler", "test pwa launch", "pwa launch event", "app launch parameters", "how pwa handles links", "pwa link capturing", "pwa protocol handlers", "pwa url handling", "installed web app api", "pwa development tools", "learn pwa apis", "web capabilities playground", "launch handler demo", "pwa launch params" ],
  };

export default seo;
