import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "License Chooser - Free Online Open Source License Picker Tool | IconVault",
    metaDescription: "Compare MIT, Apache-2.0, GPL-3.0, BSD-3-Clause, ISC and MPL-2.0, then generate a LICENSE file. Free, in your browser. Not legal advice.",
    about: [
      "**IconVault**'s **License Chooser** makes picking an **open source license** less painful. A **comparison table** lines up **MIT**, **Apache-2.0**, **GPL-3.0**, **BSD-3-Clause**, **ISC** and **MPL-2.0** by **copyleft**, **commercial use**, **patent grant**, **source disclosure** and **same-license** requirements, with a one-line **tagline** for each license so the trade-offs are obvious.",
      "Pick a license, enter the **copyright holder** and **year**, and the tool generates a ready-to-ship **LICENSE** file you can **copy** or **download** (full texts for **MIT**, **ISC** and **BSD-3-Clause**; official header notices plus authoritative links for the longer documents). Everything runs **fully in your browser** and it is **free** to try (heavy repeated use may ask for **Pro**). This is **not legal advice**: for real projects with revenue or contributors, talk to a lawyer."
    ],
    faqs: [
      { q: "Which licenses does it cover?", a: "MIT, Apache-2.0, GPL-3.0, BSD-3-Clause, ISC and MPL-2.0, the six licenses most open source projects choose between." },
      { q: "What is copyleft?", a: "Copyleft is a license requirement that derivative works stay open under the same license. GPL-3.0 is strong copyleft, MPL-2.0 is weak copyleft at the file level, and MIT, Apache-2.0, BSD-3-Clause and ISC have no copyleft." },
      { q: "MIT or Apache-2.0, which should I pick?", a: "Apache-2.0 adds an explicit patent grant and requires stating changes, so it suits larger projects. MIT is shorter and simpler, and is the default for most small projects. The comparison table shows the exact differences." },
      { q: "Does it generate the full license text?", a: "For MIT, ISC and BSD-3-Clause you get the complete license text. For Apache-2.0, GPL-3.0 and MPL-2.0 you get the official header notice plus a link to the authoritative full text, since those are long documents maintained by their foundations." },
      { q: "Is this legal advice?", a: "No. The tool compares publicly documented license terms and generates standard texts, but it is not legal advice. For commercial projects, talk to a lawyer." },
      { q: "Is it really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "license chooser",
      "open source license chooser",
      "choose open source license",
      "software license chooser",
      "license picker",
      "open source license picker",
      "mit vs apache",
      "mit vs gpl",
      "apache vs mit",
      "gpl vs mit",
      "mit license generator",
      "generate mit license",
      "mit license text",
      "apache 2.0 license text",
      "gpl 3.0 license text",
      "bsd 3 clause license",
      "isc license",
      "mpl 2.0 license",
      "compare open source licenses",
      "open source license comparison",
      "license comparison table",
      "copyleft vs permissive",
      "what is copyleft",
      "permissive license meaning",
      "strong copyleft license",
      "weak copyleft license",
      "which license for my project",
      "best license for open source",
      "best license for github project",
      "github license chooser",
      "choosealicense alternative",
      "generate license file",
      "license file generator",
      "create license file online",
      "download mit license",
      "license generator online",
      "free license generator",
      "copyright holder license",
      "license year generator",
      "patent grant license",
      "license with patent protection",
      "commercial use license",
      "can i use mit commercially",
      "gpl commercial use",
      "disclose source license",
      "same license requirement",
      "license conditions",
      "open source license explained",
      "software licensing explained",
      "license for npm package",
      "license for python package",
      "not legal advice license",
      "license tool no signup",
      "free license tool online",
      "oss license picker",
      "open source licensing guide"
    ],
  };

export default seo;
