import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "List Converter - Free Online List Cleanup & Format Tool | IconVault",
    metaDescription: "Clean up lists in seconds: trim, dedupe, sort, change case, prefix, suffix, quote and join. Free, live output, fully in your browser.",
    about: [
      "**IconVault**'s **List Converter** cleans and reshapes **line-based lists** with one click each. Apply operations in a fixed pipeline: **cleanup** (**trim lines**, **drop empty lines**, **remove duplicates**), then **sort A to Z** or **Z to A**, change **case** (**UPPER**, **lower**, **Title**), add a **prefix** or **suffix**, wrap in **single or double quotes**, and **join** everything with a **custom delimiter**.",
      "The **live output** updates as you type or toggle options, with a **line count** and one-click **copy**. Everything runs **fully in your browser**, nothing is uploaded, and it is **free** to try (heavy repeated use may ask for **Pro**)."
    ],
    faqs: [
      { q: "What operations does the List Converter support?", a: "Trim lines, drop empty lines, remove duplicates, sort A to Z or Z to A, change case to UPPER, lower or Title, add a prefix and suffix, wrap items in single or double quotes, and join everything with a custom delimiter." },
      { q: "In what order are the operations applied?", a: "Cleanup first, then sort, then case, then prefix and suffix, then quotes, and finally joining. The order is fixed so results are predictable." },
      { q: "Can I join lines with commas or another separator?", a: "Yes. Type any delimiter such as a comma, semicolon or pipe into the join field. Leave it empty for one item per line." },
      { q: "How do I remove duplicate lines?", a: "Keep the remove duplicates checkbox on. It keeps the first occurrence of each line and drops the rest." },
      { q: "Can I add quotes around every item?", a: "Yes. Choose single or double quotes and each line is wrapped, which is handy for building SQL IN clauses or JSON-style arrays." },
      { q: "Is it really free?", a: "Yes, it is free to try with no signup. Heavy repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "list converter",
      "list converter online",
      "convert list online",
      "list cleanup tool",
      "clean up list",
      "clean list online",
      "remove duplicates from list",
      "dedupe list online",
      "remove duplicate lines",
      "sort list online",
      "sort list a to z",
      "alphabetize list",
      "alphabetize list online",
      "sort lines alphabetically",
      "change list case",
      "uppercase list",
      "lowercase list",
      "title case list",
      "add prefix to list",
      "add suffix to list",
      "prefix suffix list",
      "quote each line",
      "add quotes to list",
      "wrap lines in quotes",
      "join lines with comma",
      "comma separated list",
      "convert list to csv",
      "list to comma separated",
      "newline to comma",
      "join lines online",
      "trim list lines",
      "remove empty lines",
      "drop blank lines",
      "text list formatter",
      "format list online",
      "bulk list editor",
      "list transformer",
      "transform list online",
      "free list converter",
      "list converter no signup",
      "list formatting tool",
      "prepare list for excel",
      "list for spreadsheet",
      "sql in list generator",
      "make sql in clause from list",
      "email list cleanup",
      "keyword list cleanup",
      "domain list formatter",
      "url list cleanup",
      "browser list converter",
      "client side list tool",
      "one click list cleanup",
      "multi operation list tool",
      "list processing online"
    ],
  };

export default seo;
