import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "List Comparer - Free Online List Difference Checker Tool | IconVault",
    metaDescription: "Compare two lists line by line: only in A, only in B, in both, and combined unique. Free, live in your browser, nothing uploaded.",
    about: [
      "**IconVault**'s **List Comparer** finds the difference between two **line-based lists** instantly. Paste list A and list B to see four results: **only in List A**, **only in List B**, **in both lists**, and a **combined unique** merge, with **live counts** and per-section **copy** buttons, so deduping email lists, keyword sets or ID lists takes seconds.",
      "Options include **trim whitespace** and **ignore case** for forgiving comparisons. Comparison is **live** as you type, runs **fully in your browser** with nothing uploaded, and it is **free** to try (heavy repeated use may ask for **Pro**)."
    ],
    faqs: [
      { q: "What does the List Comparer do?", a: "It compares two line-based lists and shows four sections: items only in list A, items only in list B, items in both lists, and a combined unique merge of both." },
      { q: "Can the comparison ignore case?", a: "Yes. Turn on the ignore case toggle and Apple and apple are treated as the same item." },
      { q: "Are duplicates inside one list removed?", a: "For comparison purposes each list is treated as a set of unique items, so repeated lines in the same list do not inflate the results." },
      { q: "Can I copy the results?", a: "Yes. Each of the four sections has its own copy button, so you can paste just the differences or just the overlap wherever you need them." },
      { q: "What is the combined unique list?", a: "It is the union of both lists with duplicates removed, preserving the order items first appear in." },
      { q: "Is my data uploaded anywhere?", a: "No. The comparison runs locally in your browser, so it is safe for private lists." }
    ],
    tags: [
      "list comparer",
      "list comparer online",
      "compare two lists",
      "compare two lists online",
      "list comparison tool",
      "list difference checker",
      "find difference between two lists",
      "diff two lists",
      "list diff online",
      "compare lists online",
      "list a vs list b",
      "items in a not in b",
      "find missing items in list",
      "find common items in two lists",
      "intersection of two lists",
      "union of two lists",
      "combine two lists unique",
      "merge lists remove duplicates",
      "dedupe two lists",
      "compare email lists",
      "compare keyword lists",
      "compare id lists",
      "spreadsheet list compare",
      "excel list compare online",
      "compare column data",
      "text list comparer",
      "line by line compare",
      "compare lists line by line",
      "free list comparer",
      "list compare no signup",
      "case insensitive list compare",
      "ignore case compare lists",
      "trim whitespace compare",
      "copy difference list",
      "export difference",
      "list overlap finder",
      "find overlapping items",
      "list subtraction",
      "subtract one list from another",
      "list a minus list b",
      "symmetric difference lists",
      "unique to each list",
      "duplicates across lists",
      "compare large lists",
      "bulk list compare",
      "online diff tool text",
      "list diff tool free",
      "compare word lists",
      "compare url lists",
      "compare two columns",
      "data list comparison",
      "browser list comparer",
      "client side list compare"
    ],
  };

export default seo;
