import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "LocalStorage Explorer - Free Online Browser Storage Tool | IconVault",
    metaDescription: "Browse, search, edit and delete keys in your browser's localStorage with export, import and a usage meter. Free, runs locally.",
    about: [
      "**IconVault**'s **LocalStorage Explorer** opens a window into your browser's **localStorage** for the current origin. Browse every **key** with its **size** and **value preview**, **search** keys and values, and **view, add, edit or delete** entries through simple dialogs, which makes debugging **cached settings**, **tokens** and **app state** far easier than devtools digging.",
      "A **storage usage meter** estimates how much of the roughly **5 MB quota** you have used, and you can **export** everything to **JSON** or **import** a JSON export back. It only ever touches **this site's origin**, runs **fully in your browser** with nothing uploaded, and is **free** to try (heavy repeated use may ask for **Pro**). **Viewing is unlimited**; add, edit, delete and export use the trial."
    ],
    faqs: [
      { q: "What is localStorage?", a: "It is key-value storage built into browsers that persists across sessions, with a typical quota of around 5 MB per origin. Sites use it for settings, session tokens and cached state." },
      { q: "Can it see other websites' storage?", a: "No. Browsers isolate localStorage per origin for security, so this tool can only read and edit storage belonging to the site it runs on." },
      { q: "Can I export and import my storage?", a: "Yes. Export downloads every key and value as JSON, and you can import that JSON back later, overwriting keys with the same names." },
      { q: "What does the usage meter measure?", a: "It estimates the byte length of all keys plus values and compares it to the typical 5 MB quota. The real quota varies by browser." },
      { q: "Is anything sent to a server?", a: "No. All reads and writes happen locally in your browser." },
      { q: "Is it really free?", a: "Yes, it is free to try with no signup. Viewing keys is unlimited; add, edit, delete and export use the trial, and Pro unlocks unlimited use." }
    ],
    tags: [
      "localstorage explorer",
      "localstorage viewer",
      "view localstorage",
      "localstorage manager",
      "localstorage editor",
      "edit localstorage",
      "localstorage browser tool",
      "browser storage explorer",
      "local storage viewer online",
      "inspect localstorage",
      "debug localstorage",
      "localstorage debugger",
      "see localstorage keys",
      "localstorage key value viewer",
      "localstorage search",
      "search localstorage",
      "delete localstorage key",
      "clear localstorage key",
      "add localstorage key",
      "localstorage export json",
      "export localstorage",
      "import localstorage",
      "localstorage backup",
      "localstorage usage",
      "localstorage size",
      "localstorage quota",
      "how much localstorage used",
      "5mb localstorage limit",
      "localstorage full",
      "localstorage vs sessionstorage",
      "what is localstorage",
      "browser storage types",
      "web storage api",
      "localstorage javascript",
      "read localstorage js",
      "localstorage devtools alternative",
      "easier than devtools localstorage",
      "view site storage",
      "application tab alternative",
      "chrome localstorage viewer",
      "free localstorage tool",
      "localstorage tool no signup",
      "localstorage quota exceeded",
      "localstorage storage estimate",
      "localstorage json export",
      "localstorage import json",
      "localstorage key size",
      "localstorage value preview",
      "localstorage unlimited viewing",
      "client side storage manager",
      "web storage manager",
      "browser key value store"
    ],
  };

export default seo;
