import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Log Parser - Free Online Log Analyzer Tool | IconVault",
    metaDescription: "Paste or upload log files, filter by level and search. Auto-detects Apache, Nginx, JSON lines and plain text. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Log Parser** turns messy log output into something you can actually read. Paste or upload a **log file** and it **auto-detects the format** (**Apache/Nginx** combined, **JSON lines** or plain text), tags every line with its **level** (info, warn, error, debug), and shows per-level counts so you know exactly where the problems are.",
      "Filter lines by **severity**, **search** across the full log, and copy or inspect only what matters. Everything runs **fully in your browser** with nothing uploaded, so even sensitive production logs stay private. It is **free** to try (repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "What log formats does the Log Parser support?", a: "It auto-detects Apache and Nginx combined logs, JSON lines (it reads the level, severity or type field), and plain text logs. For plain text, it scans each line for keywords like error, warn, debug and info to assign a level." },
      { q: "Is my log file uploaded anywhere?", a: "No. Parsing, filtering and searching all happen locally in your browser with JavaScript. Your log data never leaves your device, so it is safe to use with production logs that contain sensitive information." },
      { q: "Can I upload a large log file?", a: "Yes, you can upload a log file directly or paste the content. For very large files the tool caps the input it processes so the page stays responsive; filter down to the levels you care about for the fastest results." },
      { q: "How does level detection work for plain text logs?", a: "The parser looks for words like error, err, fatal, critical, fail, exception or traceback for errors, warn or warning for warnings, debug, trace or verbose for debug output, and info, notice, started, success or ok for info. Lines that match nothing are grouped as other." },
      { q: "Can I export the filtered lines?", a: "Yes. After filtering by level or searching, you can copy the matching lines to use in tickets, share with teammates, or paste into your debugging notes." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "log parser",
      "log analyzer",
      "online log parser",
      "parse log files online",
      "free log analyzer",
      "log file viewer online",
      "online log reader",
      "apache log parser",
      "nginx log parser",
      "parse apache access log",
      "parse nginx error log",
      "json log viewer",
      "jsonl log parser",
      "filter logs by level",
      "search log file online",
      "log level filter",
      "error log analyzer",
      "server log analyzer",
      "application log parser",
      "plain text log reader",
      "upload log file to analyze",
      "browser log analyzer",
      "log analyzer no upload",
      "debug log analyzer",
      "exception finder in logs",
      "count errors in log file",
      "log statistics tool",
      "log line counter by severity",
      "find errors in log file",
      "grep log file online",
      "search inside log file",
      "log file filter online",
      "web server log analyzer",
      "view large log file in browser",
      "split log by severity",
      "log format detector",
      "combined log parser",
      "log analysis for developers",
      "devops log tool",
      "troubleshoot server errors from logs",
      "find fatal errors in logs",
      "find warnings in log file",
      "find stack traces in log",
      "log keyword search tool",
      "copy filtered log lines",
      "log file privacy tool",
      "free server log parser",
      "online log parser no signup",
      "log analyzer free tool",
      "parse log in browser",
      "log viewer with search",
      "filter error lines from log",
      "analyze access log online",
      "read json logs online",
      "log parser for developers"
    ],
  };

export default seo;
