import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "MAC Generator - Free Online Random MAC Address Tool | IconVault",
    metaDescription: "Generate random MAC addresses with vendor OUI presets, a locally administered toggle and OUI lookup. 100% client-side and free.",
    about: [
      "**IconVault**'s **MAC Generator** creates **cryptographically random MAC addresses** for lab work, testing and privacy. Generate **1 to 20 addresses** at once, pick a **vendor OUI** from the built-in table (Apple, Cisco, Intel, Samsung, Dell, Microsoft, Google, VMware and more), or toggle the **locally administered bit** to produce safe test addresses that cannot collide with real hardware.",
      "It also includes a reverse **OUI lookup** that identifies the vendor of any MAC address, with links out to the full OUI database. Generation uses **crypto.getRandomValues** and everything runs **fully in your browser**, nothing stored or uploaded. It is **free** to try (repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "What is a MAC address generator used for?", a: "Developers and network engineers use random MAC addresses for testing virtual machines, emulators, containers and network labs without reusing real hardware addresses. It is also handy for privacy research and documentation examples." },
      { q: "What is a locally administered MAC address?", a: "Setting the local bit (the second-least-significant bit of the first octet) marks the address as locally administered rather than globally unique. This guarantees your generated addresses will never collide with real manufacturer-assigned addresses, which is why the toggle is recommended for test data." },
      { q: "What is an OUI and how does the lookup work?", a: "An OUI (Organizationally Unique Identifier) is the first three octets of a MAC address, assigned to a manufacturer. Paste any MAC address into the lookup box and the tool checks its OUI against the built-in vendor table and names the company if it is a known one." },
      { q: "Is it legal to use random MAC addresses?", a: "Generating addresses is fine, but using them to impersonate another device on a network you do not own or manage may be against the law or your provider's terms. Use generated MACs only for your own devices, labs and test environments." },
      { q: "Are the generated addresses stored anywhere?", a: "No. Generation happens with crypto.getRandomValues directly in your browser, and nothing is sent to a server or saved. Each batch is freshly random." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "mac address generator",
      "random mac address",
      "generate mac address online",
      "mac generator free",
      "fake mac address generator",
      "random mac address generator",
      "mac address maker",
      "create mac addresses",
      "bulk mac address generator",
      "generate 10 mac addresses",
      "vendor mac address generator",
      "oui mac generator",
      "apple mac address generator",
      "cisco mac oui generator",
      "locally administered mac address",
      "set local bit mac address",
      "unicast locally administered mac",
      "mac address for testing",
      "test mac address",
      "randomize mac address",
      "virtual machine mac address",
      "vmware mac address generator",
      "virtualbox mac generator",
      "docker mac address random",
      "network testing mac addresses",
      "mac address for emulator",
      "oui lookup",
      "mac vendor lookup",
      "find vendor from mac address",
      "mac oui checker",
      "identify device by mac address",
      "what company owns this mac address",
      "oui database search",
      "first three octets lookup",
      "organizationally unique identifier lookup",
      "mac address format generator",
      "valid mac address generator",
      "unicast mac address generator",
      "mac address randomizer online",
      "generate mac addresses in bulk",
      "mac address generator no signup",
      "free mac address tool",
      "online mac generator",
      "browser mac address generator",
      "random mac no download",
      "mac address privacy tool",
      "generate mac for testing",
      "ethernet mac generator",
      "wifi mac address random",
      "device mac address creator",
      "network lab mac addresses",
      "ccna lab mac address",
      "networking tools mac generator",
      "spoof mac address for testing",
      "random mac address for android emulator"
    ],
  };

export default seo;
