import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "PWA Manifest Generator - Free Web App Manifest Builder | IconVault",
    metaDescription: "Build a valid web app manifest.json: name, colors, display, icons at 192 and 512px from your upload, shortcuts. Free, in your browser.",
    about: [
      "**IconVault**'s **PWA Manifest** tool builds a complete **web app manifest.json** for your **progressive web app**. Fill in the app **name** and **short name**, **theme** and **background colors**, **display mode**, **start URL**, **scope** and **orientation**, then upload one icon and let the tool generate real **192px** and **512px PNGs** from it right in the page.",
      "Add **app shortcuts**, preview the **live JSON** as you edit, then **copy** or **download** the manifest plus the icon files. Everything runs **fully in your browser** with nothing uploaded, so your branding never leaves your device. It is **free** to try (repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "What is a web app manifest and why do I need one?", a: "A web app manifest is a JSON file that tells the browser how your site should behave when installed as an app: its name, icons, colors and launch behavior. It is required for the browser to offer an install prompt, and Lighthouse checks for a valid manifest as part of PWA scoring." },
      { q: "What icon sizes does the tool generate?", a: "Upload any image and the tool renders real 192x192 and 512x512 PNG files from it using canvas, then references them in the manifest. Those two sizes are the ones browsers require for an installable PWA." },
      { q: "What display modes can I choose?", a: "Standalone, fullscreen, minimal-ui and browser are all supported, along with orientation options of any, portrait, landscape and natural." },
      { q: "What are app shortcuts?", a: "Shortcuts are quick actions that appear when a user long-presses your installed app icon (for example, New note or Open inbox). The tool lets you add them with names, URLs and icons, and writes them into the manifest." },
      { q: "Is my uploaded icon sent to a server?", a: "No. The icon is resized locally in your browser with canvas, and the PNGs are generated on your device. Nothing is uploaded." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "pwa manifest generator",
      "web app manifest generator",
      "manifest.json generator",
      "create manifest.json online",
      "free pwa manifest tool",
      "pwa manifest builder",
      "generate manifest json",
      "web app manifest creator",
      "pwa icon generator",
      "generate pwa icons 192 512",
      "pwa splash icon generator",
      "manifest icons 192x192 512x512",
      "resize icon for pwa",
      "create pwa from website",
      "make website installable",
      "add to homescreen manifest",
      "pwa installable requirements",
      "webmanifest generator",
      "site.webmanifest creator",
      "manifest.json example",
      "pwa manifest example",
      "manifest display standalone",
      "manifest theme color",
      "manifest background color",
      "manifest start url",
      "manifest scope",
      "manifest orientation portrait",
      "pwa shortcuts generator",
      "app shortcuts manifest",
      "manifest name short name",
      "pwa manifest validator",
      "check manifest.json valid",
      "lighthouse pwa manifest",
      "installable web app checklist",
      "progressive web app tools",
      "pwa builder online free",
      "manifest generator no signup",
      "browser pwa manifest tool",
      "android pwa manifest",
      "ios pwa apple touch icon",
      "maskable icon generator",
      "purpose any maskable manifest",
      "manifest categories",
      "manifest description",
      "manifest lang",
      "manifest dir",
      "web app capable manifest",
      "pwa manifest download",
      "copy manifest json",
      "online manifest.json maker",
      "free pwa tools",
      "pwa starter template",
      "twa manifest generator",
      "chrome pwa install prompt"
    ],
  };

export default seo;
