import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Markdown Table Builder - Free Online Table Generator | IconVault",
    metaDescription: "Build Markdown tables visually: editable grid, per-column alignment, copy or download. No alignment syntax to memorize. Free, in your browser.",
    about: [
      "**IconVault**'s **Markdown Table Builder** turns an **editable grid** into a perfectly formatted **Markdown table**. Add or remove **rows and columns**, click to edit any cell, and set **per-column alignment** (left, center or right) without touching pipe and colon syntax yourself.",
      "The Markdown output updates **live** and renders correctly on **GitHub**, **GitLab**, Notion and everywhere else tables are supported. **Copy** it or **download** it as a .md file. Everything runs **fully in your browser**. It is **free** to try (repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "How do I make a table in Markdown without memorizing the syntax?", a: "Use the grid: type your content into the cells, add rows and columns with the plus buttons, and choose alignment per column. The tool writes the pipe characters, header separator row and alignment colons for you." },
      { q: "How does column alignment work in Markdown?", a: "Alignment is set in the separator row: :--- for left, :---: for centered, and ---: for right. The builder sets these automatically when you pick an alignment for a column." },
      { q: "What is the maximum table size?", a: "The grid supports up to 30 rows and 12 columns, which covers nearly every documentation table. Very wide tables may scroll on some renderers, so keep columns modest for readability." },
      { q: "Will the output work on GitHub and GitLab?", a: "Yes. The tool emits standard GitHub Flavored Markdown tables, which render on GitHub, GitLab, Bitbucket, Notion, Reddit, Discord and most static site generators." },
      { q: "Can I paste data from a spreadsheet?", a: "You can paste text into any cell directly. For CSV content, many people paste it in cell by cell or one row at a time; the live preview shows the finished table as you go." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "markdown table generator",
      "create markdown table online",
      "markdown table builder",
      "free markdown table maker",
      "markdown table creator",
      "build markdown table visually",
      "online markdown table editor",
      "markdown table syntax generator",
      "github markdown table generator",
      "markdown table with alignment",
      "markdown table center align",
      "markdown table left right align",
      "markdown table column alignment",
      "ascii table to markdown",
      "csv to markdown table",
      "excel to markdown table",
      "convert csv to markdown",
      "spreadsheet to markdown table",
      "paste table as markdown",
      "markdown table formatter",
      "format markdown table online",
      "pretty markdown table",
      "align markdown table columns",
      "markdown table generator no signup",
      "free markdown tools",
      "markdown table example",
      "markdown table cheat sheet",
      "how to make a table in markdown",
      "markdown table syntax pipes",
      "markdown table header row",
      "markdown table multiple columns",
      "readme table generator",
      "github readme table maker",
      "documentation table generator",
      "notion markdown table",
      "markdown table download",
      "copy markdown table",
      "markdown grid editor",
      "visual markdown editor table",
      "markdown table for gitlab",
      "markdown table for discord",
      "markdown table for reddit",
      "markdown table generator free online",
      "easy markdown tables",
      "markdown table rows columns",
      "html table to markdown",
      "convert html table to markdown",
      "markdown table cell editor",
      "online table to markdown converter",
      "markdown table generator for blogs"
    ],
  };

export default seo;
