import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Markdown Formatter - Free | IconVault",
    metaDescription:
      "Format Markdown free: normalize headings, lists, spacing and code fences. Tidy messy Markdown in one click.",
    about: [
      "**IconVault**'s **Markdown Formatter** tidies messy **Markdown**: consistent **heading** spacing, normalized **list** indentation and bullets, single blank lines between blocks, trimmed trailing spaces and fenced **code blocks** - so your README renders the same everywhere.",
      "Paste, format, copy. A diff-style summary tells you what changed. Runs in your browser - free, no account needed.",
    ],
    faqs: [
      {
        q: "What does the formatter normalize?",
        a: "Heading levels and spacing (# Title), list markers and indentation, blank lines between blocks, trailing whitespace, and code fence consistency.",
      },
      {
        q: "Will it change my content?",
        a: "No - only whitespace and marker style are normalized. Your words, links and code stay byte-identical.",
      },
      {
        q: "Does it support tables?",
        a: "Yes - pipe tables get aligned delimiters and consistent cell padding.",
      },
      {
        q: "How is this different from Markdown Preview?",
        a: "Preview renders Markdown to HTML for reading; Formatter rewrites the Markdown source itself so it's clean and consistent.",
      },
    ],
    tags: [
      "markdown formatter", "format markdown online", "markdown prettifier",
      "tidy markdown", "markdown linter", "prettify md", "markdown cleaner",
      "format readme", "markdown style fixer", "md formatter free",
    
      "markdown beautifier",
      "pretty markdown",
      "format md online",
      "markdown pretty print",
      "markdown tidier",
      "clean markdown online",
      "markdown code formatter",
      "md prettifier",
      "readme formatter",
      "format readme.md",
      "github markdown formatter",
      "markdown table formatter",
      "format markdown table",
      "markdown table generator",
      "markdown linter online",
      "markdown validator",
      "check markdown syntax",
      "markdown syntax checker",
      "markdown fixer",
      "fix markdown formatting",
      "consistent markdown",
      "markdown style guide checker",
      "prettier markdown online",
      "markdown formatter free",
      "format markdown no signup",
      "online markdown tool",
      "markdown text formatter",
      "md file formatter",
      "format markdown file",
      "markdown to pretty",
      "markdown whitespace fixer",
      "markdown heading formatter",
      "markdown list formatter",
      "format bullet list markdown",
      "markdown quote formatter",
      "markdown link formatter",
      "markdown image formatter",
      "markdown code block formatter",
      "format code in markdown",
      "markdown bold italic fixer",
      "markdown formatter tool",
      "beautify md file",
      "tidy md online",
      "markdown cleanup tool",
      "normalize markdown",
      "markdown formatter app",
      "md linter free",
      "markdown beautifier online",
      "format markdown text",
      "clean md file"],
  };

export default seo;
