import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Math Evaluator - Free Online Expression Calculator | IconVault",
    metaDescription: "Evaluate math expressions safely with a hand-written parser: sin, cos, sqrt, log, powers, constants pi and e. No eval(). Free, in your browser.",
    about: [
      "**IconVault**'s **Math Evaluator** computes **math expressions** with a **hand-written parser**, never **eval()** or Function(), so it is safe by design. Type full expressions with **parentheses**, **powers**, **modulo**, and functions like **sin**, **cos**, **tan**, **sqrt**, **log** and **ln**, plus the constants **pi** and **e**, and get an instant result.",
      "An on-screen **keypad** with clear and delete keys makes quick entry easy, and with no server round trip everything runs **fully in your browser**. It is **free** to try (repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "Why does this calculator avoid eval()?", a: "eval() and Function() execute arbitrary JavaScript, which is a security risk if the input ever comes from anywhere untrusted. This tool uses a hand-written tokenizer and parser that understands only math, so it can evaluate expressions safely." },
      { q: "Which functions are supported?", a: "Trigonometric functions sin, cos and tan, square root, logarithms log and ln, absolute value, powers and modulo, plus the constants pi and e. You can nest them with parentheses to any depth." },
      { q: "Does it respect order of operations?", a: "Yes. The parser implements standard precedence: parentheses first, then powers, then multiplication, division and modulo, then addition and subtraction, just like PEMDAS/BODMAS." },
      { q: "Are results exact or rounded?", a: "Results are computed with JavaScript double-precision numbers and displayed as-is, so you may see long decimals for values like 1/3 or irrational results. That is normal floating point behavior." },
      { q: "Can I use the keyboard or the on-screen keypad?", a: "Both. Type directly into the input field or click the on-screen keypad buttons for digits, operators, parentheses and functions. Clear and delete keys help fix mistakes fast." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "math evaluator",
      "online math calculator",
      "evaluate math expression online",
      "expression evaluator",
      "math expression solver",
      "free calculator online",
      "scientific calculator online",
      "calculate expression in browser",
      "safe eval alternative",
      "math parser online",
      "evaluate formula online",
      "solve math equation online",
      "trigonometry calculator online",
      "sin cos tan calculator",
      "sqrt calculator online",
      "logarithm calculator",
      "natural log calculator",
      "power calculator online",
      "modulo calculator",
      "pi calculator",
      "expression calculator no eval",
      "math input calculator",
      "on screen calculator keypad",
      "quick math calculator",
      "free math tool",
      "browser calculator",
      "no signup calculator",
      "order of operations calculator",
      "pemdas calculator online",
      "parentheses calculator",
      "nested parentheses solver",
      "math homework helper calculator",
      "evaluate algebraic expression",
      "math function calculator",
      "engineering calculator online",
      "simple scientific calculator",
      "web calculator free",
      "instant math answer",
      "type expression get answer",
      "math calculator with pi",
      "e constant calculator",
      "calculate exponents online",
      "root calculator online",
      "math expression checker",
      "validate math expression",
      "free online math tools",
      "calculate trigonometry online",
      "math solver with functions",
      "expression calculator free",
      "online formula calculator"
    ],
  };

export default seo;
