import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Meal Generator - Free Random Meal Ideas with Macros | IconVault",
    metaDescription: "Random meal ideas matched to your diet and calorie target, with protein, carbs and fat per meal. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Meal Generator** ends the what-should-I-eat loop. Pick a **diet** (any, **veg**, **vegan**, **high-protein** or **low-carb**) and a **calorie target**, and it suggests a random **meal** with its description and full **macros**: calories, **protein**, **carbs** and **fat**.",
      "**Reroll** as many times as you like for fresh ideas, and **copy** any suggestion to your notes or shopping list. Everything runs **fully in your browser** with nothing uploaded. It is **free** to try (repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "How does the Meal Generator work?", a: "Choose a diet type and set your calorie target, then the tool picks a random meal from its built-in list that matches your diet and shows the meal's calories, protein, carbs and fat. Hit the reroll button for another idea." },
      { q: "Which diets are supported?", a: "Anything, veg, vegan, high-protein and low-carb. The meal list is filtered by your choice before the random pick, so vegan picks never include animal products and high-protein picks skew toward protein-rich meals." },
      { q: "Are these full recipes or just ideas?", a: "They are meal ideas with a short description and macro breakdown, meant to spark a decision, not detailed recipes. Copy an idea and look up a full recipe for it if you want step-by-step instructions." },
      { q: "Can I use this for meal planning?", a: "Yes. Reroll through a few ideas, copy the ones you like, and you have a day or week of meals with macro estimates. It is a starting point for planning, not a substitute for a dietitian's advice." },
      { q: "Is my data saved anywhere?", a: "No. Your diet choice and calorie target stay in your browser session, and nothing is uploaded or stored on a server." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "meal generator",
      "random meal generator",
      "meal idea generator",
      "what should i eat generator",
      "dinner idea generator",
      "lunch idea generator",
      "breakfast idea generator",
      "free meal planner",
      "meal suggestions online",
      "random dinner ideas",
      "what to cook tonight",
      "dinner decision maker",
      "meal picker wheel",
      "random food generator",
      "healthy meal ideas generator",
      "high protein meal ideas",
      "low carb meal ideas",
      "vegan meal ideas",
      "vegetarian meal ideas",
      "meal ideas with macros",
      "meals with protein carbs fat",
      "calorie counted meal ideas",
      "macro friendly meal ideas",
      "meal generator with calories",
      "weight loss meal ideas",
      "muscle gain meal ideas",
      "meal inspiration tool",
      "weekly meal ideas",
      "meal prep ideas generator",
      "quick meal ideas",
      "easy dinner ideas",
      "simple meal generator",
      "free meal idea tool",
      "online meal planner free",
      "meal generator no signup",
      "browser meal generator",
      "diet meal ideas",
      "vegetarian dinner ideas",
      "vegan dinner ideas",
      "high protein dinner ideas",
      "low carb dinner ideas",
      "family dinner ideas",
      "picky eater meal ideas",
      "random recipe inspiration",
      "food idea randomizer",
      "what to eat for lunch",
      "what to eat for dinner",
      "healthy lunch ideas",
      "protein packed meals",
      "balanced meal ideas",
      "macro meal planner",
      "meal ideas with calories and protein",
      "random healthy meal picker"
    ],
  };

export default seo;
