import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Media Session Playground - Interactive Web API Lab | IconVault",
    metaDescription: "Master the Media Session API: build metadata, set playback state and wire action handlers that respond to real media keys. Free, in your browser.",
    about: [ "**IconVault**'s **Media Session Playground** drives the real **`navigator.mediaSession`** API: build **metadata** (title, artist, album, artwork), flip the **playback state** between playing and paused, and register **action handlers** for play, pause, next track and previous track that respond to your keyboard's actual **media keys**, headset buttons and OS media controls. It is free and runs fully in your browser.", "You will learn why every audio and video app should set **media metadata**: it powers the **lock-screen player**, **notification controls** and picture-in-picture overlays on phones and desktops. The lab shows which artwork sizes each platform prefers, how **`setPositionState()`** keeps scrubbers in sync, and the graceful pattern for handlers the browser does not support: check first, register only what exists." ],
    faqs: [ { q: "What is the Media Session API for?", a: "It tells the OS what is playing so lock screens, notifications and hardware media keys can show metadata and control playback. This lab wires it to real media key presses." }, { q: "How do I make my headset buttons control my web app?", a: "Register action handlers with navigator.mediaSession.setActionHandler('play', ...) and friends; the lab demonstrates play, pause, previoustrack and nexttrack live." }, { q: "What metadata should I provide?", a: "Title, artist and album plus artwork at several sizes (96, 128, 192, 256, 384 and 512px is the common set). The builder generates the full MediaMetadata object." }, { q: "What does setPositionState do?", a: "It reports duration, playbackRate and current position so the OS scrubber stays in sync. Update it on seeks; the lab has a live position slider for this." }, { q: "Which browsers support Media Session?", a: "All modern browsers on desktop and mobile support the core API, though the exact actions each OS surfaces vary. The lab feature-detects before registering." }, { q: "Can I test media keys without hardware keys?", a: "Yes. The lab includes on-screen buttons that fire the same handlers, and logs every action event with its source." } ],
    tags: [ "media session api", "navigator.mediasession", "media session javascript", "media metadata api", "media keys web", "headset buttons web", "lock screen media controls", "web audio metadata", "now playing web", "MediaMetadata", "setactionhandler", "media session actions", "play pause handler", "previoustrack nexttrack", "seekbackward seekforward", "setpositionstate", "playbackstate media session", "media session artwork", "media session example", "media session tutorial", "media session demo", "media session playground", "mdn media session", "media session chrome", "media session safari", "media session android", "media controls web app", "podcast web player controls", "music player web api", "picture in picture metadata", "notification media controls", "os media overlay", "hardware media keys javascript", "how to add media keys to website", "web player lock screen", "audio player metadata", "video player metadata", "media session typescript", "caniuse media session", "is media session supported", "media session events", "media session seekto", "media session stop action", "web media player api", "bluetooth headset web", "media notification web", "media artwork sizes", "album art web player", "media session position slider", "media session demo online", "web audio session api" ],
  };

export default seo;
