import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "MediaRecorder Studio - Interactive Web API Lab | IconVault",
    metaDescription: "Record real audio and video in your browser: camera, screen and mic capture with codec selection, live preview, playback and download. Free.",
    about: [ "**IconVault**'s **MediaRecorder Studio** is a real **recording tool** built on the **`MediaRecorder`** API: capture from your **camera**, **screen** (with optional system audio) or **microphone**, pick a **codec** from the ones your browser actually supports, watch a live preview with a recording timer, then play back and **download** the file. It is free and runs fully in your browser.", "You will learn the honest browser limits: Chrome records **WebM** (MP4 in newer builds), Safari records **MP4**, and Firefox supports WebM, so the studio labels the true container instead of guessing. Screen capture needs a user gesture, and `getDisplayMedia()` cannot be triggered silently. The lab also covers bitrate trade-offs and why `ondataavailable` chunking matters for long recordings." ],
    faqs: [ { q: "What can I record with MediaRecorder?", a: "Camera video, microphone audio, or your screen via getDisplayMedia, with optional system audio where the browser allows it. This studio offers all three sources." }, { q: "Which file format will I get?", a: "It depends on your browser: Chrome and Firefox produce WebM (Chrome also MP4 in recent versions), Safari produces MP4. The studio shows the real mimeType before you download." }, { q: "Why is screen recording asking for permission every time?", a: "Browsers require a fresh user gesture for getDisplayMedia and never allow silent screen capture. That is a deliberate privacy rule, not a bug." }, { q: "Can I choose the codec?", a: "Yes, from the codecs your browser reports via MediaRecorder.isTypeSupported(). Unsupported options are disabled rather than failing at record time." }, { q: "How do I record long sessions without huge memory use?", a: "Use timeslice chunking so ondataavailable fires periodically; the studio streams chunks and assembles the final file only when you stop." }, { q: "Is my recording uploaded anywhere?", a: "No. Capture, preview and download all happen locally in your browser; nothing leaves your device." } ],
    tags: [ "mediarecorder", "media recorder api", "mediarecorder javascript", "record video javascript", "record audio browser", "screen recording javascript", "getdisplaymedia", "getusermedia", "media recorder example", "media recorder tutorial", "media recorder demo", "online voice recorder", "online screen recorder", "browser screen recorder", "record webcam javascript", "webcam recorder web", "microphone recorder browser", "media recorder codecs", "istypesupported", "webm recorder", "mp4 recording chrome", "safari mediarecorder", "mediarecorder mimeType", "video/webm codecs", "audio/webm", "ondataavailable", "timeslice mediarecorder", "media recorder bitrate", "videoBitsPerSecond", "audioBitsPerSecond", "record screen with audio", "system audio capture", "media recorder chunks", "download recording javascript", "blob video download", "playback recorded video", "media recorder states", "pause resume recording", "mdn mediarecorder", "media stream recording api", "caniuse mediarecorder", "is mediarecorder supported", "mediarecorder typescript", "mediarecorder firefox", "chrome media recorder", "how to record video in html", "javascript video capture", "web audio recorder", "podcast recording browser", "voice memo web app" ],
  };

export default seo;
