import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Media Query Builder - Free CSS Breakpoint Generator | IconVault",
    metaDescription: "Compose responsive breakpoints with device presets and get a commented CSS media query skeleton to copy. Free, in your browser.",
    about: [
      "**IconVault**'s **Media Query Builder** writes your **responsive CSS skeleton** for you. Name each **breakpoint**, set optional **min** and **max widths**, or load **device presets** for **mobile**, **tablet**, **laptop** and **desktop**, and it generates a clean, **commented set of @media rules** you can paste straight into your stylesheet.",
      "Add and remove breakpoints freely, and **copy** the finished CSS in one click. Everything runs **fully in your browser** with nothing uploaded. It is **free** to try (repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "What breakpoints should I use?", a: "There is no single standard, but common ranges are around 480px for mobile, 768px for tablets, 1024px for laptops and 1280px and up for desktops. The tool ships with these as presets, and you can rename or adjust every one." },
      { q: "Should I use min-width or max-width?", a: "Mobile-first designs use min-width (styles apply from that width upward); desktop-first designs use max-width (styles apply down to that width). You can set either or both per breakpoint in the tool." },
      { q: "What does the generated CSS look like?", a: "Each breakpoint becomes a commented @media block with its name and range, for example a Mobile block covering up to 480px. The comments make it easy to find the right block later when your stylesheet grows." },
      { q: "Can I add custom breakpoints?", a: "Yes. Add as many breakpoints as you need with your own names and min/max values, and remove any you do not want. The skeleton regenerates instantly." },
      { q: "Is my CSS sent anywhere?", a: "No. The breakpoint list and the generated CSS are built locally in your browser. Nothing is uploaded or stored." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "media query generator",
      "css media query builder",
      "responsive breakpoint generator",
      "free media query tool",
      "media query creator online",
      "css breakpoint generator",
      "build media queries online",
      "media query code generator",
      "responsive css generator",
      "mobile tablet desktop breakpoints",
      "standard css breakpoints",
      "common media query breakpoints",
      "480px 768px 1024px 1280px media queries",
      "mobile first media query",
      "desktop first media query",
      "min-width max-width generator",
      "media query syntax helper",
      "how to write media queries",
      "css responsive design tool",
      "responsive web design helper",
      "media query template",
      "media query boilerplate",
      "css skeleton generator",
      "commented css media queries",
      "copy paste media queries",
      "media query for mobile phones",
      "media query for tablets",
      "media query for laptops",
      "media query for large screens",
      "breakpoint manager css",
      "custom breakpoints css",
      "media query cheat sheet",
      "css media query examples",
      "responsive design breakpoints guide",
      "device width media queries",
      "screen size media queries",
      "viewport breakpoint tool",
      "css @media generator",
      "media screen generator",
      "free css tools online",
      "frontend developer tools",
      "web design helper tools",
      "media query generator no signup",
      "browser media query builder",
      "css tools free online",
      "responsive layout helper",
      "breakpoint css generator",
      "css media query skeleton",
      "responsive stylesheet starter",
      "mobile responsive css generator"
    ],
  };

export default seo;
