import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Meme Generator - Free Online Tool | IconVault",
    metaDescription: "Make classic memes with top/bottom text, draggable extra layers, and Impact styling. Export JPG or PNG. Free.",
    about: [
      "**IconVault**'s **Meme Generator** gives you the authentic classic meme look: **Impact font, white fill, black stroke**, with automatic line wrapping so long captions stay readable. Type your top and bottom text, dial the font size as a percentage of image height, and hit Export.",
      "Need more captions? **Add extra text** layers, up to five, and **drag each one** anywhere on the image in the live preview. Export as **JPG or PNG** at full resolution. Everything renders **in your browser**, so your images never leave your device. **Free** with a daily trial, unlimited with Pro.",
    ],
    faqs: [
      { q: "What is the classic meme style?", a: "Impact typeface in all caps with white fill and a thick black stroke, positioned top and bottom. This tool reproduces that exact look and wraps long lines automatically." },
      { q: "Can I add more text besides top and bottom?", a: "Yes. The Add extra text button creates up to five additional draggable text layers you can position anywhere on the image by dragging in the preview." },
      { q: "How do I move the extra text?", a: "Click a layer in the list to select it, then drag the text directly on the preview canvas. The layer follows your cursor and re-renders live." },
      { q: "What export formats are supported?", a: "JPG and PNG at the original image resolution. JPG keeps file sizes small for sharing; PNG preserves maximum quality." },
      { q: "Is my image uploaded anywhere?", a: "No. Meme composition happens on canvas in your browser. Nothing leaves your device." },
      { q: "Is the meme generator free?", a: "Yes, with a daily free trial limit. IconVault Pro unlocks unlimited exports across every tool." },
    ],
    tags: [ "meme generator", "meme maker online", "classic meme maker", "impact font meme", "top text bottom text meme", "make meme free", "meme creator online", "funny meme generator", "image meme maker", "custom meme generator", "meme text generator", "drag text on image", "meme maker no watermark", "online meme studio", "caption image meme", "meme export jpg", "white text black outline meme", "viral meme maker", "meme template maker", "free meme tool" ,
      "meme generator free",
      "best meme generator",
      "meme maker free online",
      "make your own meme",
      "create meme online free",
      "meme maker with templates",
      "popular meme templates",
      "trending meme templates",
      "meme templates free",
      "drake meme generator",
      "distracted boyfriend meme maker",
      "woman yelling at cat meme",
      "two buttons meme generator",
      "change my mind meme maker",
      "expanding brain meme maker",
      "meme caption maker",
      "add funny text to image",
      "meme font generator",
      "impact font generator",
      "meme text maker",
      "make meme with your photo",
      "upload photo make meme",
      "custom image meme maker",
      "meme maker for whatsapp",
      "meme maker for instagram",
      "meme maker for discord",
      "funny picture maker",
      "meme creator free no watermark",
      "meme generator no sign up",
      "online meme maker free",
      "how to make a meme",
      "meme maker app alternative",
      "gif meme maker",
      "video meme maker",
      "meme generator with your own image",
      "blank meme templates",
      "meme background templates",
      "reaction meme maker",
      "relatable meme maker",
      "office meme generator"],
  };

export default seo;
