import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Mermaid Editor - Free Online Diagram Editor | IconVault",
    metaDescription: "Write Mermaid diagram code with live SVG preview, theme picker and SVG/PNG downloads. Nothing uploaded. Free.",
    about: [
      "**IconVault**'s **Mermaid Editor** lets you write **Mermaid diagram code** and see it rendered as **SVG** instantly. Start from samples for **flowcharts**, **sequence diagrams**, **class diagrams**, **state diagrams**, **Gantt charts**, **pie charts**, **mindmaps** and **timelines**, pick a **theme**, and watch the **live preview** update as you type, with clear error messages when the syntax is off.",
      "**Export** your finished diagram as **SVG** or **PNG** for docs, READMEs and presentations. The Mermaid library loads on demand and everything runs **fully in your browser** with nothing uploaded. It is **free** to try (repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "What is Mermaid?", a: "Mermaid is a text-based diagramming syntax: you describe a flowchart, sequence diagram or chart in a few lines of plain text, and it renders as a vector diagram. It is popular for documentation because the source is version-control friendly." },
      { q: "Which diagram types can I make?", a: "The editor includes starter samples for flowcharts, sequence diagrams, class diagrams, state diagrams, Gantt charts, pie charts, mindmaps and timelines. You can edit any sample or write your own Mermaid code from scratch." },
      { q: "How do I export the diagram?", a: "Use the download buttons to export the rendered diagram as SVG (crisp vector, best for the web and print) or PNG (raster, best for slides and tools that do not accept SVG). You can also copy the SVG markup directly." },
      { q: "What happens if my syntax has an error?", a: "The editor shows an error indicator so you know the diagram failed to render. Check for common mistakes like unclosed brackets, missing arrows or unsupported keywords, and the preview returns as soon as the code is valid again." },
      { q: "Is my diagram code uploaded to a server?", a: "No. Rendering happens with the Mermaid library running locally in your browser, and your code never leaves your device." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "mermaid editor",
      "mermaid diagram editor",
      "online mermaid editor",
      "free mermaid editor",
      "mermaid live editor",
      "mermaid live preview",
      "mermaid flowchart generator",
      "create mermaid diagram online",
      "mermaid diagram maker",
      "mermaid code editor",
      "mermaid to svg",
      "mermaid to png",
      "export mermaid diagram",
      "download mermaid svg",
      "mermaid diagram download",
      "flowchart maker online",
      "sequence diagram generator",
      "class diagram generator",
      "state diagram maker",
      "gantt chart generator online",
      "pie chart mermaid",
      "mindmap generator online",
      "timeline diagram maker",
      "mermaid syntax checker",
      "mermaid syntax helper",
      "learn mermaid syntax",
      "mermaid examples",
      "mermaid flowchart example",
      "mermaid sequence diagram example",
      "text to diagram tool",
      "diagram as code",
      "docs diagram tool",
      "readme diagram generator",
      "github mermaid diagram",
      "mermaid for documentation",
      "architecture diagram text tool",
      "system design diagram maker",
      "free diagram maker online",
      "online diagram tool no signup",
      "browser diagram editor",
      "vector diagram export",
      "svg diagram download",
      "png diagram export",
      "mermaid theme picker",
      "mermaid dark theme",
      "mermaid diagram themes",
      "mermaid error checker",
      "fix mermaid syntax",
      "mermaid playground",
      "mermaid js editor",
      "mermaid diagram tool free",
      "draw flowchart with code"
    ],
  };

export default seo;
