import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Mesh Gradient - Free Online Gradient Background Tool | IconVault",
    metaDescription: "Create mesh gradients with draggable color pins and export layered radial-gradient CSS. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Mesh Gradient** generator lets you design smooth, organic **gradient backgrounds** by dragging **color pins** over a base color. Each pin adds a layered **radial gradient**, and you control the base color, spread and pin count, with a **randomize** button to spark new ideas instantly.",
      "Everything runs **fully in your browser**, so your color experiments never leave your device. The tool is **free** to try (repeated use may prompt for Pro) and copies **production-ready CSS** you can paste straight into your site, perfect for **hero sections**, **cards** and **app backgrounds**."
    ],
    faqs: [
      { q: "What is a mesh gradient?", a: "A mesh gradient blends several radial gradients that overlap on one surface, creating smooth, organic color transitions. It is the same look designers make in Figma or Illustrator, exported here as plain CSS." },
      { q: "How do I get the CSS into my site?", a: "Press the copy button and paste the .mesh-gradient class into your stylesheet. It uses background-color plus layered radial-gradient values, so it works in every modern browser with no images or extra assets." },
      { q: "How many color pins can I use?", a: "Between 4 and 6 pins. Four pins give a balanced blend, while six pins let you build richer, more complex color fields. Select a pin to change its color, drag it to move it, or remove it." },
      { q: "Is my work uploaded anywhere?", a: "No. The whole tool runs locally in your browser with JavaScript. Your colors and layouts never leave your device, so it is safe to use for client or unreleased projects." },
      { q: "Can I get random ideas quickly?", a: "Yes. The shuffle button repositions every pin and picks fresh colors from a curated palette, so you can generate dozens of starting points in seconds and fine tune the one you like." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "mesh gradient generator",
      "mesh gradient css",
      "css mesh gradient generator",
      "mesh gradient background",
      "gradient mesh generator online",
      "radial gradient mesh",
      "layered radial gradients css",
      "mesh gradient maker free",
      "create mesh gradient online",
      "css gradient background generator",
      "mesh background generator",
      "color mesh generator",
      "aurora gradient generator",
      "blob gradient generator",
      "fluid gradient background",
      "organic gradient background",
      "modern gradient background css",
      "hero section gradient css",
      "mesh gradient for websites",
      "css mesh gradient tool",
      "mesh gradient color picker",
      "multi color gradient generator",
      "blended color blobs css",
      "radial gradient overlapping css",
      "how to make mesh gradient css",
      "mesh gradient tutorial css",
      "mesh gradient without figma",
      "free mesh gradient tool",
      "online mesh gradient creator",
      "mesh gradient wallpaper maker",
      "abstract gradient background maker",
      "soft gradient background css",
      "vibrant gradient background",
      "pastel mesh gradient",
      "dark mesh gradient background",
      "neon mesh gradient css",
      "mesh gradient palette ideas",
      "best mesh gradient colors",
      "mesh gradient for landing page",
      "css background layered gradients",
      "multiple radial gradients css",
      "background image mesh gradient css",
      "smooth color blend background",
      "gradient mesh design trend",
      "mesh gradient inspiration",
      "copy paste mesh gradient css",
      "responsive gradient background",
      "lightweight css gradient background",
      "no image gradient background",
      "mesh gradient tailwind",
      "css gradient art generator",
      "colorful website background generator"
    ],
  };

export default seo;
