import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Metronome - Free Online Music Tempo Tool | IconVault",
    metaDescription: "Free online metronome with tap tempo, 2/4, 3/4, 4/4 and 6/8 time signatures and a visual beat pulse. Runs in your browser.",
    about: [
      "**IconVault**'s **Metronome** is a precise **Web Audio** metronome that plays an accented downbeat with a **visual pulse** so you can feel every bar. Set the **BPM** with the slider or use **tap tempo** to match the song in your head, and switch between **2/4, 3/4, 4/4 and 6/8** time signatures for practice, lessons or recording.",
      "Clicks are scheduled with **sample-accurate timing**, so the beat stays steady even while you adjust settings. It is **free** to try (repeated use may prompt for Pro) and runs **fully in your browser** with no download or signup, a handy metronome for **guitar**, **piano**, **drums** and vocal practice."
    ],
    faqs: [
      { q: "How accurate is this metronome?", a: "Very. It uses the Web Audio API with a lookahead scheduler, the same technique professional metronome apps use, so clicks stay on time even when the browser is busy." },
      { q: "What is tap tempo?", a: "Tap tempo lets you tap a button in rhythm with a song to measure its tempo. The tool averages your taps and sets the BPM automatically, which is faster than guessing a number." },
      { q: "Which time signatures are supported?", a: "Four of the most common: 2/4, 3/4, 4/4 and 6/8. The first beat of every bar is accented with a higher pitch, and the visual pulse shows which beat you are on." },
      { q: "Can I change the tempo while it plays?", a: "Yes. Move the BPM slider mid playback and the new tempo applies on the next scheduled beat without stopping the metronome." },
      { q: "Does it make sound on silent devices?", a: "On phones, make sure silent mode is off and media volume is up. The tool uses Web Audio, which follows your device's media volume, not the ringer." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "online metronome",
      "free metronome online",
      "metronome online free",
      "metronome app free",
      "metronome 120 bpm",
      "bpm metronome",
      "tap tempo online",
      "tap tempo metronome",
      "metronome with tap tempo",
      "metronome 4/4",
      "metronome 3/4",
      "metronome 6/8",
      "metronome 2/4",
      "time signature metronome",
      "metronome for guitar practice",
      "metronome for piano",
      "metronome for drums",
      "metronome for singing practice",
      "metronome 60 bpm",
      "metronome 80 bpm",
      "metronome 100 bpm",
      "metronome 140 bpm",
      "metronome 90 bpm",
      "metronome 70 bpm",
      "metronome 50 bpm",
      "metronome 180 bpm",
      "metronome 200 bpm",
      "metronome bpm counter",
      "beats per minute metronome",
      "visual metronome",
      "metronome with flashing light",
      "accurate online metronome",
      "best free online metronome",
      "metronome no download",
      "metronome no app needed",
      "practice metronome online",
      "music practice tempo tool",
      "tempo keeper online",
      "how to use a metronome",
      "what bpm should I practice at",
      "metronome for beginners",
      "metronome for violin",
      "metronome for bass guitar",
      "metronome for ukulele",
      "metronome for saxophone",
      "metronome for trumpet",
      "metronome for clarinet",
      "metronome for cello",
      "metronome for flute",
      "metronome for music lessons",
      "rhythm practice tool",
      "keep time while practicing music",
      "steady beat practice tool",
      "web audio metronome"
    ],
  };

export default seo;
