import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "MIME Types - Free Online MIME Type Lookup Tool | IconVault",
    metaDescription: "Look up MIME types by file extension and extensions by MIME type. 150+ entries with search and copy. Free, in your browser.",
    about: [
      "**IconVault**'s **MIME Types** lookup is a **two-way reference**: type a **file extension** like mp4 to get its MIME type, or paste a **MIME type** like image/webp to find the matching extensions. The table covers **150+ entries** across images, video, audio, documents, fonts, archives and web formats.",
      "Every search runs **fully in your browser** with nothing uploaded, and one click copies the result for your **Content-Type headers**, upload **accept attributes** or **server config**. It is **free** to try (repeated use may prompt for Pro), handy for **developers**, **sysadmins** and anyone configuring **nginx**, **Apache** or **S3**."
    ],
    faqs: [
      { q: "What is a MIME type?", a: "A MIME type, also called a media type, is a label like image/png or application/pdf that tells browsers and servers what kind of content a file holds. It is sent in the Content-Type HTTP header." },
      { q: "Can I search in both directions?", a: "Yes. Search for an extension to get its MIME type, or search for a MIME type to see every extension mapped to it. Click any result to copy it to your clipboard." },
      { q: "How many entries does the lookup include?", a: "Over 150 extension and MIME type pairs, covering images, video, audio, text, code, fonts, documents, archives, executables, 3D formats and common web data types." },
      { q: "Why does my server send the wrong MIME type?", a: "Usually the server is missing a mapping for that extension. Look up the correct type here and add it to your nginx mime.types, Apache .htaccess, or your framework's static file configuration." },
      { q: "Is my data uploaded anywhere?", a: "No. The whole lookup runs locally in your browser. Your searches never leave your device." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "mime type lookup",
      "mime type checker",
      "file extension to mime type",
      "mime type to file extension",
      "what is the mime type of pdf",
      "what is the mime type of png",
      "what is the mime type of jpg",
      "what is the mime type of mp4",
      "what is the mime type of mp3",
      "what is the mime type of svg",
      "what is the mime type of webp",
      "what is the mime type of json",
      "what is the mime type of csv",
      "what is the mime type of zip",
      "what is the mime type of html",
      "what is the mime type of css",
      "what is the mime type of js",
      "what is the mime type of docx",
      "what is the mime type of xlsx",
      "what is the mime type of woff2",
      "what is the mime type of ttf",
      "what is the mime type of ico",
      "what is the mime type of avif",
      "what is the mime type of gif",
      "what is the mime type of mov",
      "what is the mime type of wav",
      "what is the mime type of epub",
      "what is the mime type of heic",
      "image jpeg mime type",
      "application pdf mime type",
      "video mp4 mime type",
      "audio mpeg mime type",
      "text csv mime type",
      "application json mime type",
      "font woff2 mime type",
      "application zip mime type",
      "list of mime types",
      "common mime types list",
      "mime types reference",
      "content type list",
      "http content type reference",
      "nginx mime types list",
      "apache mime types",
      "file upload accept mime types",
      "mime type for file upload input",
      "set content type header",
      "mime type vs file extension",
      "why is my mime type wrong",
      "correct mime type for svg",
      "mime type octet stream meaning",
      "text plain mime type",
      "application octet stream",
      "multipart form data mime type",
      "mime type search online",
      "free mime type lookup"
    ],
  };

export default seo;
