import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Mock Data Generator - Free Fake Data Generator Tool | IconVault",
    metaDescription: "Generate realistic fake rows as JSON, CSV or SQL from a field schema, with a seed for repeatable output. Free, in your browser.",
    about: [
      "**IconVault**'s **Mock Data Generator** builds **realistic test rows** from a field schema you define: names, **emails**, phones, companies, **UUIDs**, integers, floats, booleans, dates, **IPv4 addresses**, URLs, colors, words and sentences. Export the result as **JSON**, **CSV** or **SQL** and drop it straight into your app, database or test suite.",
      "A **seed** keeps the output **repeatable**, so the same seed always produces the same rows, ideal for **demos**, **unit tests** and shared fixtures. Everything runs **fully in your browser** and it is **free** to try (repeated use may prompt for Pro), so your fake data never touches a server."
    ],
    faqs: [
      { q: "What formats can I export?", a: "JSON, CSV and SQL INSERT statements. JSON is handy for APIs and frontend mocks, CSV opens in any spreadsheet, and SQL drops straight into a database." },
      { q: "What does the seed do?", a: "The seed drives the random number generator, so the same seed and schema always produce identical rows. That makes tests deterministic and lets teammates reproduce the exact same dataset." },
      { q: "Which field types are supported?", a: "Full names, emails, phone numbers, company names, UUIDs, integers and floats with min/max ranges, booleans, dates and ISO dates, IPv4 addresses, URLs, hex colors, word lists and full sentences." },
      { q: "Is the generated data real?", a: "No, every value is fabricated from built-in word lists and random generators. Names, emails and companies are fictional, so nothing can be traced to a real person." },
      { q: "Can I use the generated data in commercial projects?", a: "Yes. It is placeholder data with no copyrighted content, so you can use it in prototypes, demos, tests and documentation freely." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "mock data generator",
      "fake data generator",
      "test data generator online",
      "dummy data generator free",
      "generate fake data online",
      "mock json data generator",
      "fake json generator",
      "json test data generator",
      "generate fake json",
      "random json data generator",
      "csv test data generator",
      "generate fake csv",
      "sql insert generator",
      "generate fake sql rows",
      "fake data for testing",
      "seeded random data generator",
      "repeatable fake data",
      "deterministic mock data",
      "fake data with seed",
      "random user generator",
      "fake name and email generator",
      "fake email generator",
      "fake phone number generator",
      "random uuid generator",
      "uuid v4 generator",
      "random ip address generator",
      "fake ipv4 generator",
      "random date generator",
      "fake company name generator",
      "random boolean generator",
      "random integer generator",
      "random float generator",
      "lorem ipsum sentence generator",
      "random color hex generator",
      "random url generator",
      "fake url generator",
      "mock api data generator",
      "api testing fake data",
      "frontend mock data tool",
      "database seed data generator",
      "seed database with fake data",
      "unit test fake data",
      "qa test data generator",
      "demo data generator",
      "sample data generator",
      "placeholder data generator",
      "generate rows of fake data",
      "bulk fake data generator",
      "no signup mock data generator",
      "free fake data tool",
      "faker js alternative online",
      "generate fake names list",
      "random names and emails csv",
      "json placeholder alternative"
    ],
  };

export default seo;
