import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Molar Mass Calculator - Free Chemistry Tool | IconVault",
    metaDescription: "Enter a chemical formula like H2SO4 to get its molar mass and each element's mass share. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Molar Mass Calculator** parses any **chemical formula**, including nested **parentheses** like Ca(OH)2, and returns the **molar mass** in g/mol plus a full breakdown of every element: its **symbol**, **atom count**, **mass contribution** and **percentage** of the total. It uses **standard atomic weights** for all elements.",
      "Everything runs **fully in your browser** with nothing uploaded. It is **free** to try (repeated use may prompt for Pro), making it a quick companion for **chemistry students**, **lab work** and **stoichiometry** practice."
    ],
    faqs: [
      { q: "How do I enter a formula?", a: "Type it as plain text with capital letters for element symbols, for example H2O, H2SO4, C6H12O6 or Ca(OH)2. The parser handles numbers after symbols and nested parentheses automatically." },
      { q: "Does it support parentheses?", a: "Yes, including nested ones. Ca(OH)2 is read as one calcium plus two OH groups, and multipliers apply to everything inside the brackets, just like in real chemistry notation." },
      { q: "Which atomic weights are used?", a: "Standard atomic weights in grams per mole, the same values published on the periodic table. Results are rounded to a sensible number of decimals for lab and homework use." },
      { q: "What is molar mass used for?", a: "Molar mass converts between grams and moles, the core step in stoichiometry. You need it to calculate reactant amounts, solution concentrations and percent composition." },
      { q: "What is the difference between molar mass and molecular weight?", a: "They are numerically the same value. Molar mass is expressed in g/mol, while molecular weight is dimensionless relative to carbon-12. This tool reports molar mass in g/mol." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "molar mass calculator",
      "molecular weight calculator",
      "molar mass of water",
      "molar mass of h2so4",
      "molar mass of nacl",
      "molar mass of co2",
      "molar mass of glucose",
      "molar mass of caco3",
      "molar mass of hcl",
      "molar mass of naoh",
      "molar mass of h2o2",
      "molar mass of ch4",
      "molar mass of c6h12o6",
      "molar mass of caoh2",
      "molar mass of hno3",
      "molar mass of nh3",
      "molar mass of o2",
      "molar mass of n2",
      "molar mass of ethanol",
      "molar mass of c2h5oh",
      "molar mass of sucrose",
      "molar mass of mgso4",
      "molar mass of kmno4",
      "molar mass of feso4",
      "molar mass of al2o3",
      "molar mass of agno3",
      "molar mass of cuo",
      "molar mass of zno",
      "molar mass of fe2o3",
      "calculate molar mass online",
      "chemical formula mass calculator",
      "how to calculate molar mass",
      "molar mass formula chemistry",
      "molar mass from chemical formula",
      "element mass percent calculator",
      "mass percent of elements in compound",
      "stoichiometry calculator",
      "chemistry calculator online",
      "free chemistry calculator",
      "atomic weight calculator",
      "periodic table molar mass",
      "grams per mole calculator",
      "g mol calculator",
      "mole calculator chemistry",
      "chemistry homework helper",
      "molar mass practice",
      "molecular mass vs molar mass",
      "is molar mass the same as molecular weight",
      "molar mass of air",
      "molar mass of helium",
      "molar mass of iron",
      "molar mass of gold",
      "molar mass of silver",
      "molar mass of copper"
    ],
  };

export default seo;
