import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Morse Code Translator - Free Online Encoder Tool | IconVault",
    metaDescription: "Encode text to Morse code and decode it back, with audible playback and an adjustable WPM speed slider. Free, in your browser.",
    about: [
      "**IconVault**'s **Morse Code** translator converts text into **standard ITU Morse code** and decodes Morse back into readable text, covering letters, **numbers** and common **punctuation**. A built-in **Web Audio player** sounds out the dots and dashes with an adjustable **WPM speed slider**, so you can learn the rhythm by ear.",
      "Everything runs **fully in your browser** and the tool is **free** to try (repeated use may prompt for Pro). Great for **amateur radio** fans, **scouts**, **puzzle lovers** and anyone learning Morse for fun or basic emergency signaling."
    ],
    faqs: [
      { q: "Which characters are supported?", a: "All 26 letters, digits 0-9, and common punctuation including period, comma, question mark, exclamation mark, slash, colon, at sign and quotes, following the ITU International Morse standard." },
      { q: "How do I decode Morse code?", a: "Paste the code with spaces between letters and slashes between words, for example .... . / ... .., then press decode. Unrecognized sequences are shown as question marks." },
      { q: "What does WPM mean?", a: "WPM is words per minute, the standard measure of Morse speed based on the word PARIS. Beginners start around 5 WPM, while experienced operators copy 20 WPM or faster. Move the slider to change the playback speed." },
      { q: "Can I actually hear the Morse code?", a: "Yes. The play button renders the dots and dashes as audio beeps through your browser with correct ITU timing, including the pauses between letters and words." },
      { q: "What standard does this follow?", a: "International Morse code as defined by the ITU, the same standard used in amateur radio and maritime signaling. SOS is dot-dot-dot dash-dash-dash dot-dot-dot." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "morse code translator",
      "morse code decoder",
      "morse code encoder",
      "text to morse code",
      "morse code to text",
      "morse code translator audio",
      "morse code player",
      "morse code sound",
      "morse code alphabet",
      "morse code chart",
      "international morse code",
      "itu morse code",
      "morse code letters",
      "morse code numbers",
      "morse code punctuation",
      "morse code sos",
      "morse code for hello",
      "morse code hello world",
      "translate english to morse code",
      "decode morse code online",
      "morse code beeper",
      "morse code audio generator",
      "play morse code online",
      "learn morse code",
      "morse code practice",
      "morse code trainer",
      "morse code wpm",
      "morse code speed",
      "what is morse code",
      "how does morse code work",
      "morse code history",
      "morse code for beginners",
      "easy morse code translator",
      "free morse code tool",
      "online morse code converter",
      "morse code dot dash",
      "morse code signals",
      "morse code emergency signal",
      "morse code tapping",
      "morse code flashlight",
      "morse code bracelet",
      "morse code tattoo ideas",
      "morse code necklace",
      "morse code puzzle",
      "escape room morse code",
      "scout morse code",
      "ham radio morse code",
      "amateur radio cw",
      "morse code key",
      "morse code app alternative",
      "morse code no download",
      "learn morse code by sound"
    ],
  };

export default seo;
