import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Mortgage Calculator - Free Home Loan Calculator | IconVault",
    metaDescription: "Calculate monthly mortgage payments, total interest and a yearly amortization table, with extra-payment modeling. Free, in your browser.",
    about: [
      "**IconVault**'s **Mortgage Calculator** computes your **monthly payment** from the loan amount, **interest rate** and term, then shows **total interest**, the **payoff timeline** and a year-by-year **amortization table**. Add an **extra monthly payment** to see exactly how much interest you save and how many years you shave off the loan.",
      "A built-in **principal vs interest chart** visualizes how your payments shift over time. Everything runs **fully in your browser** and it is **free** to try (repeated use may prompt for Pro), ideal for **home buyers**, **refinancing** comparisons and budgeting before you talk to a lender."
    ],
    faqs: [
      { q: "How is the monthly payment calculated?", a: "With the standard fixed-rate amortization formula: the loan amount times the monthly rate, divided by one minus the rate raised to the negative number of payments. That gives the payment that exactly pays off the loan over the term." },
      { q: "Does this include property taxes and insurance?", a: "No. This tool calculates principal and interest only. Taxes, homeowners insurance and PMI are location and policy dependent, so add them separately for a full monthly housing budget." },
      { q: "How do extra monthly payments help?", a: "Extra payments go straight to principal, which shrinks the balance that interest is charged on. Even a small extra amount can cut years off a 30-year loan and save tens of thousands in interest." },
      { q: "What is an amortization table?", a: "A schedule showing, for each year of the loan, how much of your payments went to principal versus interest and what the remaining balance is. Early years are interest-heavy; later years are principal-heavy." },
      { q: "Can I compare different interest rates?", a: "Yes. Enter the same loan amount and term with different rates to see how much each percentage point costs you per month and over the life of the loan. It is a quick way to sanity-check lender quotes." },
      { q: "Is this financial advice?", a: "No. It is a planning tool for estimates only. Actual loan terms depend on your lender, credit profile, taxes, insurance and fees, so confirm the numbers with a qualified professional before signing anything." }
    ],
    tags: [
      "mortgage calculator",
      "home loan calculator",
      "mortgage payment calculator",
      "monthly mortgage payment calculator",
      "mortgage calculator with extra payments",
      "mortgage amortization calculator",
      "amortization schedule calculator",
      "mortgage interest calculator",
      "how much house can I afford",
      "house affordability calculator",
      "home affordability calculator",
      "mortgage calculator extra principal payment",
      "extra mortgage payment calculator",
      "how much interest will I pay on mortgage",
      "mortgage payoff calculator",
      "how long to pay off mortgage",
      "30 year mortgage calculator",
      "15 year mortgage calculator",
      "20 year mortgage calculator",
      "fixed rate mortgage calculator",
      "mortgage rate comparison",
      "compare mortgage rates",
      "refinance calculator",
      "should I refinance my mortgage",
      "mortgage refinance break even",
      "loan amortization table",
      "yearly amortization schedule",
      "principal vs interest chart",
      "mortgage payment breakdown",
      "how is mortgage payment calculated",
      "mortgage formula",
      "mortgage calculator no signup",
      "free mortgage calculator",
      "online mortgage calculator",
      "best free mortgage calculator",
      "mortgage calculator for first time buyers",
      "first time home buyer calculator",
      "down payment calculator",
      "how much down payment for house",
      "20 percent down payment calculator",
      "adjustable rate mortgage calculator",
      "arm vs fixed calculator",
      "biweekly mortgage calculator",
      "biweekly vs monthly mortgage",
      "mortgage calculator excel alternative",
      "home loan emi calculator",
      "emi calculator home loan",
      "housing loan calculator",
      "property loan calculator",
      "mortgage affordability",
      "debt to income ratio calculator",
      "dti calculator mortgage",
      "closing costs calculator",
      "how much are closing costs",
      "mortgage pre approval calculator",
      "home buying budget planner",
      "home loan planning tool"
    ],
  };

export default seo;
