import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "NATO Phonetic Alphabet - Free Spelling Alphabet Tool | IconVault",
    metaDescription: "Convert text to the NATO phonetic alphabet (Alpha, Bravo, Charlie) and decode it back. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **NATO Phonetic** tool converts any text into the **NATO phonetic alphabet**, Alpha, Bravo, Charlie and the rest, so names, **confirmation codes** and serial numbers come through clearly on calls. It also **decodes** phonetic spelling back into plain text, accepting common variants like Nine for Niner.",
      "Everything runs **fully in your browser** with nothing uploaded, and it is **free** to try (repeated use may prompt for Pro). Useful for **customer support**, **call centers**, **pilots**, radio operators and anyone spelling tricky names over a bad connection."
    ],
    faqs: [
      { q: "What is the NATO phonetic alphabet?", a: "It is the international spelling alphabet where each letter is represented by a distinct word: Alpha for A, Bravo for B, Charlie for C, all the way to Zulu for Z. It was designed so letters stay intelligible over noisy radio." },
      { q: "Can I convert phonetic spelling back to text?", a: "Yes. Switch to decode mode and paste words like Alpha Bravo Charlie; the tool converts them back to ABC. It ignores commas, periods and dashes between words." },
      { q: "Does it handle numbers?", a: "Yes. Digits 0-9 map to Zero, One, Two, Three, Four, Five, Six, Seven, Eight and Niner. Niner is pronounced with an extra syllable so it cannot be confused with the German word nein." },
      { q: "What is the difference between Nine and Niner?", a: "The official NATO word is Niner, chosen to avoid confusion over radio. This tool accepts both on decode, so pasting either variant works." },
      { q: "Is my text uploaded anywhere?", a: "No. Conversion happens entirely in your browser with JavaScript. Your text never leaves your device." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "nato phonetic alphabet",
      "nato phonetic",
      "phonetic alphabet",
      "nato spelling alphabet",
      "alpha bravo charlie",
      "alpha bravo charlie alphabet",
      "nato alphabet list",
      "phonetic alphabet chart",
      "icao phonetic alphabet",
      "military phonetic alphabet",
      "aviation phonetic alphabet",
      "radio phonetic alphabet",
      "nato phonetic translator",
      "text to nato phonetic",
      "convert to nato phonetic",
      "nato phonetic converter",
      "phonetic spelling generator",
      "spell name in nato phonetic",
      "nato code for letters",
      "what is a in nato phonetic",
      "nato phonetic for numbers",
      "nato numbers zero niner",
      "nine vs niner nato",
      "nato phonetic decoder",
      "decode nato phonetic",
      "phonetic to text converter",
      "how to spell with nato alphabet",
      "nato alphabet for names",
      "phonetic alphabet for call center",
      "customer service spelling alphabet",
      "spelling alphabet for phone calls",
      "how to spell over the phone clearly",
      "pilot alphabet",
      "pilot phonetic alphabet",
      "airline alphabet",
      "maritime phonetic alphabet",
      "police phonetic alphabet",
      "emergency services phonetic alphabet",
      "learn nato phonetic alphabet",
      "memorize nato alphabet",
      "nato alphabet quiz",
      "nato alphabet practice",
      "full nato alphabet a to z",
      "nato alphabet with pronunciation",
      "why is it called nato alphabet",
      "nato alphabet history",
      "free phonetic alphabet tool",
      "online phonetic spelling tool",
      "nato alphabet for confirmation codes",
      "spell serial number phonetically",
      "nato phonetic for wifi password",
      "share wifi password phonetic",
      "nato alphabet for booking reference"
    ],
  };

export default seo;
