import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Navigation API Playground - Interactive Web API Lab | IconVault",
    metaDescription: "Explore the modern Navigation API: live history entries, programmatic navigation, intercept rules and a navigate event log. Free, in your browser.",
    about: [ "**IconVault**'s **Navigation API Playground** uses the real **`window.navigation`** API: browse the live list of **history entries** with keys and indexes, trigger **programmatic navigation** with `navigate()`, `back()`, `forward()` and `traverseTo()`, set **intercept** rules, and watch every **`navigate` event** land in a detailed log. It is free and runs fully in your browser.", "The Navigation API is the planned successor to the old **History API**, built for single-page apps: one `navigate` event replaces the patchwork of `popstate`, `hashchange` and monkey-patched `pushState`. You will learn how **intercept()** turns a full page load into a same-document transition, how **scroll restoration** and **transition promises** work, and the current reality that this is Chromium-only, so the lab feature-detects and explains the fallback." ],
    faqs: [ { q: "What is the Navigation API?", a: "The modern replacement for the History API: window.navigation exposes history entries and a navigate event, designed for single-page app routing. This lab exercises it live." }, { q: "How is it different from history.pushState?", a: "pushState changes the URL silently; navigation.navigate() fires a navigate event you can intercept, await transitions on, and inspect entries for, all in one API." }, { q: "What does intercept() do?", a: "Inside a navigate event handler, intercept() converts the navigation into a same-document transition, letting your SPA update content without a full reload." }, { q: "Which browsers support it?", a: "Chromium browsers (Chrome, Edge, Opera). Firefox and Safari still use the History API, so the lab detects support and teaches both paths." }, { q: "What are navigation entries?", a: "Objects with key, id, url, index and sameDocument flags representing each history item; the lab lists them live as you navigate." }, { q: "Can I cancel a navigation?", a: "Yes, with preventDefault() on the navigate event or by rejecting the transition promise. The lab logs cancellations so you can see the flow." } ],
    tags: [ "navigation api", "window.navigation", "navigation api javascript", "navigate event", "navigation.navigate", "history entries api", "navigation entries", "intercept navigation", "navigation intercept", "spa routing api", "single page app navigation", "history api vs navigation api", "pushstate replacement", "popstate alternative", "navigation api tutorial", "navigation api example", "navigation api demo", "navigation playground", "javascript navigation", "programmatic navigation", "traverseTo", "navigation.back", "navigation.forward", "navigation.reload", "NavigateEvent", "navigateevent intercept", "transition promise", "scroll restoration navigation api", "sameDocument navigation", "navigation api chrome", "navigation api firefox", "mdn navigation api", "caniuse navigation api", "is navigation api supported", "navigation api typescript", "spa router javascript", "client side routing", "hashchange vs navigate", "preventdefault navigation", "cancel navigation javascript", "navigation currententry", "navigation.entries()", "navigation key index", "web routing api", "modern web navigation", "app router web api", "navigation api playground online", "window navigation demo", "spa navigation demo", "navigate event example" ],
  };

export default seo;
