import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Network Information Playground - Interactive Web API Lab | IconVault",
    metaDescription: "Inspect the real Network Information API: effectiveType, downlink, RTT and saveData with a live change log. Free, runs in your browser.",
    about: [ "**IconVault**'s **Network Information Playground** reads the live **`navigator.connection`** object: **effectiveType** (slow-2g through 4g), estimated **downlink** speed, **round-trip time (RTT)**, and the user's **saveData** preference, all updating in a dashboard with a **change log** that records every fluctuation. It is free and runs fully in your browser.", "You will learn the honest limits first: these are **estimates**, not measurements, and the API is Chromium and Android-only, so the lab explains the gaps instead of inventing values. Then the practical patterns: serving lighter images on `save-data` or `2g`, deferring video preloads, and why you should treat the data as a hint for **adaptive loading** rather than a gate that blocks features." ],
    faqs: [ { q: "What does navigator.connection tell me?", a: "effectiveType (slow-2g, 2g, 3g, 4g), downlink in Mbps, rtt in ms, and the saveData boolean. The lab renders all four live." }, { q: "How accurate are the network estimates?", a: "They are coarse estimates from the browser's network stack, not live speed tests. Use them as hints for adaptive loading, never as precise measurements." }, { q: "What is the saveData flag?", a: "A user preference for reduced data usage, exposed as navigator.connection.saveData. Respect it by serving lighter assets; the lab shows when it is on." }, { q: "Which browsers support the Network Information API?", a: "Chrome, Edge and Android browsers. Firefox, Safari and iOS do not expose it, so the lab reports unknown there instead of guessing." }, { q: "How should apps adapt to slow connections?", a: "Load smaller images, defer non-critical scripts, disable autoplay video and offer a lite mode on 2g or when saveData is set. Adapt, do not block." }, { q: "Can I listen for connection changes?", a: "Yes, the connection object fires a change event. The lab logs every change with a timestamp so you can watch it react as your network shifts." } ],
    tags: [ "network information api", "navigator.connection", "network api javascript", "effectiveType", "downlink javascript", "rtt network api", "saveData", "save-data header", "detect connection speed javascript", "javascript network speed", "connection type web", "slow-2g 2g 3g 4g", "adaptive loading", "network aware web app", "data saver web", "reduce data usage javascript", "connection change event", "navigator.connection.change", "network information example", "network information tutorial", "network info playground", "mdn network information", "NetworkInformation api", "online offline detection", "navigator.onLine", "network status javascript", "detect slow network", "slow connection warning", "lite mode web app", "responsive loading", "connection.effectiveType", "how to check internet speed in javascript", "browser connection api", "mobile data detection", "wifi vs cellular web", "network throttling test", "chrome devtools network", "network api chrome", "network api android", "caniuse network information", "is network information supported", "network information typescript", "network information firefox", "adaptive images javascript", "preload strategy connection", "pwa offline network", "network info api demo", "check connection type online", "detect 4g 5g javascript", "networkinformation demo" ],
  };

export default seo;
