import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Neumorphism Generator - Free Soft UI CSS Tool | IconVault",
    metaDescription: "Design neumorphic soft-UI shadows with flat, concave, convex and pressed shapes, then copy the CSS. Free, in your browser.",
    about: [
      "**IconVault**'s **Neumorphism Generator** creates **soft-UI** shadows from any base color, blending a **dark shadow** and a **light shadow** to make elements look extruded from the surface. Choose **flat**, **concave**, **convex** or **pressed** shapes, tune **distance**, **blur** and **intensity**, rotate the **light angle** and preview in **dark mode**.",
      "Everything runs **fully in your browser** and the generated **box-shadow CSS** is copy-ready for your project. It is **free** to try (repeated use may prompt for Pro), perfect for **cards**, **buttons**, **toggles** and **dashboards** with that soft, tactile look."
    ],
    faqs: [
      { q: "What is neumorphism?", a: "Neumorphism, or soft UI, is a design style where elements appear extruded from the background using two shadows, one dark and one light, cast from the same base color. The result looks like soft molded plastic." },
      { q: "Which shapes are supported?", a: "Four: flat for a raised surface, concave for a scooped look, convex for a pillowed look, and pressed for an inset, button-down state. Each uses the right combination of outer and inset shadows." },
      { q: "How do I use the generated CSS?", a: "Copy the output and paste it into your stylesheet. It sets the background color and the box-shadow values, and optionally a gradient background for concave and convex shapes." },
      { q: "Does it support dark mode?", a: "Yes. Toggle dark preview to see how the same settings render on a dark base, then adjust distance and intensity until the shadows read well on dark surfaces." },
      { q: "Which colors work best?", a: "Muted mid-tone bases like light gray or slate work best, because the shadows are derived by shading the base color. Very saturated or very dark colors can make the shadows look muddy, and always check text contrast, since neumorphism is naturally low contrast." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro, which unlocks unlimited use." }
    ],
    tags: [
      "neumorphism generator",
      "neumorphism css generator",
      "neomorphism generator",
      "soft ui generator",
      "neumorphic design generator",
      "neumorphism shadow generator",
      "neumorphic css",
      "neumorphism box shadow",
      "css neumorphism",
      "soft ui css generator",
      "soft ui design tool",
      "neumorphic button css",
      "neumorphic card css",
      "neumorphism ui kit",
      "neumorphism examples",
      "what is neumorphism",
      "neumorphism vs glassmorphism",
      "neumorphism design trend",
      "how to create neumorphism css",
      "neumorphism tutorial",
      "neumorphism dark mode",
      "dark neumorphism css",
      "neumorphic toggle switch css",
      "neumorphic dashboard",
      "neumorphic input css",
      "neumorphism color palette",
      "best colors for neumorphism",
      "neumorphism accessibility",
      "neumorphism contrast issues",
      "flat concave convex pressed css",
      "inset box shadow generator",
      "soft shadow css generator",
      "double box shadow css",
      "light and dark shadow css",
      "extruded plastic effect css",
      "claymorphism vs neumorphism",
      "neumorphism figma alternative",
      "online neumorphism tool",
      "free neumorphism generator",
      "copy paste neumorphism css",
      "neumorphism css code",
      "soft ui shadows css",
      "neumorphic design inspiration",
      "neumorphism landing page",
      "neumorphism app design",
      "neumorphism buttons design",
      "neumorphic icons",
      "neumorphism tailwind",
      "tailwind neumorphism",
      "neumorphism border radius",
      "neumorphism light angle",
      "neumorphic login form",
      "soft ui card design"
    ],
  };

export default seo;
