import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Nginx Config Generator - Free Server Block Builder | IconVault",
    metaDescription: "Build a production-ready nginx server block with SSL, gzip, reverse-proxy and PHP-FPM modes. Live preview, copy or download. Free.",
    about: [
      "**IconVault**'s **Nginx Config Generator** builds a **production-ready server block** from a simple form: **domain**, **root**, **port**, **SSL** with force-HTTPS, **gzip**, **www redirects**, plus **static**, **reverse-proxy** and **PHP-FPM** modes. The **nginx.conf preview** updates live as you change options, and you can **copy** or **download** the finished config.",
      "Everything runs **fully in your browser**, so no server details ever leave your device. It is **free** to try (repeated use may prompt for Pro), and the generated config includes the **deploy steps**: place it in sites-available, symlink it to sites-enabled, then test and reload."
    ],
    faqs: [
      { q: "What does the generated config include?", a: "A complete server block with listen directives, server_name, root or proxy settings, SSL certificate lines, force-HTTPS redirect, www canonicalization, gzip compression, static asset caching and client max body size, depending on the options you choose." },
      { q: "How do I install the config on my server?", a: "Save the output to /etc/nginx/sites-available/your-domain, symlink it into sites-enabled, then run sudo nginx -t to test the syntax and sudo systemctl reload nginx to apply it. These steps are included as comments in the file." },
      { q: "Does it support HTTPS?", a: "Yes. Enable SSL, set your certificate and key paths, and optionally force all HTTP traffic to HTTPS with a 301 redirect. Use certificates from Lets Encrypt or your own CA." },
      { q: "Can it proxy to a Node.js app?", a: "Yes. Choose reverse-proxy mode and set the target, for example http://localhost:3000, and the generator writes a location block with proxy_pass plus the standard forwarding headers." },
      { q: "Does it handle PHP?", a: "Yes. PHP-FPM mode adds a location block for .php files that passes requests to your PHP socket with the standard fastcgi parameters." },
      { q: "Should I review the config before using it in production?", a: "Yes. The generator produces a solid starting point, but every server is different. Review the output, adjust paths, limits and security settings for your environment, and always run nginx -t before reloading." }
    ],
    tags: [
      "nginx config generator",
      "nginx server block generator",
      "nginx conf generator",
      "generate nginx config",
      "nginx virtual host generator",
      "nginx reverse proxy config",
      "nginx reverse proxy generator",
      "nginx proxy pass example",
      "nginx ssl config generator",
      "nginx https redirect config",
      "nginx letsencrypt config",
      "nginx force https",
      "nginx gzip config",
      "nginx static site config",
      "nginx php fpm config",
      "nginx nodejs reverse proxy",
      "nginx proxy to localhost 3000",
      "nginx config for react app",
      "nginx spa config",
      "nginx try files spa",
      "nginx www to non www",
      "nginx redirect www to non-www",
      "nginx server name example",
      "nginx listen 443 ssl",
      "nginx config file location",
      "nginx sites available example",
      "nginx test config",
      "nginx reload config",
      "nginx config syntax checker",
      "how to write nginx config",
      "nginx config tutorial",
      "nginx beginner guide",
      "nginx config best practices",
      "nginx security headers config",
      "nginx rate limiting config",
      "nginx caching static assets",
      "nginx client max body size",
      "nginx config online tool",
      "free nginx generator",
      "nginx config builder",
      "visual nginx config",
      "nginx gui generator",
      "docker nginx config",
      "nginx docker reverse proxy",
      "nginx load balancer config",
      "nginx upstream example",
      "nginx multiple domains",
      "nginx subdomain config",
      "nginx config explained",
      "nginx vs apache config",
      "nginx config for api",
      "nginx cors config",
      "nginx websocket proxy",
      "nginx config template"
    ],
  };

export default seo;
