import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Notification Builder - Interactive Web API Lab | IconVault",
    metaDescription: "Build real browser notifications: permission flow, title, body and options builder, action buttons and a fired-notification log. Free, in your browser.",
    about: [ "**IconVault**'s **Notification Builder** uses the real **`Notification`** API: walk the **permission** flow (default, granted, denied), compose **title**, **body** and every option (icon, badge, image, tag, actions, vibration, silent), then **fire real notifications** that appear in your OS notification center, with action clicks logged back in the page. It is free and runs fully in your browser.", "You will learn the rules that keep notifications trustworthy: they require **permission** and a **secure context**, most browsers only allow them from a user gesture or an installed context, and **tags** replace duplicates instead of stacking. The lab covers service-worker notifications for background delivery, why **actions** need careful labels, and the etiquette of never asking for permission on page load." ],
    faqs: [ { q: "How do I ask for notification permission?", a: "Call Notification.requestPermission(), which returns granted, denied or default. The builder runs the real flow and shows your current state." }, { q: "Why did my notification not appear?", a: "Common causes: permission denied, a non-secure HTTP origin, the page closed (needs a service worker for background delivery), or OS-level notification settings blocking the browser." }, { q: "What are notification actions?", a: "Buttons on the notification, defined in the actions array with action IDs and titles. Click one and the builder logs which action fired." }, { q: "What does the tag option do?", a: "Notifications with the same tag replace each other instead of stacking, which is ideal for updating progress or chat message counts." }, { q: "Can notifications work when the page is closed?", a: "Yes, via a service worker's showNotification(), typically triggered by push. This lab fires foreground notifications and documents the service-worker path." }, { q: "When should I request permission?", a: "After the user takes a meaningful action, like enabling alerts in settings, never on page load. The builder follows this pattern in its own flow." } ],
    tags: [ "notification api", "web notifications api", "browser notifications javascript", "notification builder", "javascript notifications", "desktop notifications web", "notification.requestpermission", "new Notification", "notification options", "notification actions", "notification tag", "notification icon badge", "web notification example", "web notification tutorial", "notification api demo", "notification playground", "push notifications web", "service worker notifications", "showNotification", "notificationclick", "notification permission denied", "notification not working", "notifications https required", "notification secure context", "request permission best practices", "notification etiquette", "notification vibration", "silent notification", "renotify option", "notification image", "notification badge android", "notification requireInteraction", "mdn notification api", "notifications chrome", "notifications safari", "notifications firefox", "caniuse notifications", "is notification api supported", "notification typescript", "how to send browser notification", "website notifications", "alert user javascript", "toast vs notification", "os notification center web", "notification event log", "test notifications online", "browser notification demo", "test web notifications", "notification api playground online", "send notification javascript" ],
  };

export default seo;
