import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "NPM Health - Free Online npm Package Health Checker | IconVault",
    metaDescription: "Check any npm package's health with 9 real registry metrics and an A-F grade: maintenance, downloads, license, deps. Free, in your browser.",
    about: [
      "**IconVault**'s **NPM Health** grades any npm package with **9 real metrics** pulled live from the **npm registry**: maintenance activity, weekly download volume, deprecation status, license declaration, repository link, readme presence, maintainer count, version count and dependency count. The results roll up into a simple **A-F health grade** so you can judge a package at a glance before adding it to your project.",
      "Everything runs **fully in your browser**: the registry is queried directly from this page, nothing is installed and nothing is uploaded. It is **free** to use with no signup. The honest caveat: the grade is a **heuristic**, not a security audit. Download counts can be inflated by CI systems and mirrors, and a healthy-looking package can still contain vulnerabilities, so pair this check with a proper security scan before shipping."
    ],
    faqs: [
      { q: "What metrics does NPM Health check?", a: "Nine metrics: actively maintained (days since last publish), weekly download volume, deprecation status, license declared, repository URL present, readme present, number of maintainers, number of published versions and number of runtime dependencies. Each gets a pass, warn or fail verdict that feeds the A-F grade." },
      { q: "Where does the data come from?", a: "Directly from the public npm registry (registry.npmjs.org) and the npm downloads API, queried from your browser when you run a check. No caching server or middleman is involved." },
      { q: "Is it really free?", a: "Yes. Unlimited checks, no account, no signup. The npm registry APIs used are public and free." },
      { q: "Can I check scoped packages like @scope/name?", a: "Yes. Type the full scoped name including the @ and the slash, for example @tanstack/react-query, and the tool queries the registry for that exact package." },
      { q: "Why did a popular package get a low grade?", a: "Usually because it has not been published in a long time (stale maintenance metric) or has a huge dependency count. A low grade means review carefully, not that the package is broken. Stable, finished packages often score lower on the maintenance metric by design." },
      { q: "Does this replace npm audit?", a: "No. This tool checks package health signals like maintenance and popularity. Run npm audit or a dedicated scanner for known vulnerability data." }
    ],
    tags: [
      "npm health",
      "npm package health checker",
      "check npm package health",
      "npm package score",
      "npm package quality checker",
      "is this npm package safe",
      "npm package checker",
      "npm package analyzer",
      "npm package grade",
      "npm package audit online",
      "check if npm package is maintained",
      "npm package last updated checker",
      "npm package download stats",
      "npm package popularity checker",
      "npm package deprecation checker",
      "npm package license checker",
      "npm package dependencies checker",
      "npm registry lookup",
      "npm package metadata viewer",
      "npm package health score online",
      "check npm package before installing",
      "npm package risk checker",
      "npm package trust checker",
      "npm package maintenance checker",
      "npm package abandoned checker",
      "npm package vetting tool",
      "npm package review tool",
      "npm package inspector",
      "npm package info lookup",
      "npm package details online",
      "npm package version checker",
      "npm package repository checker",
      "npm package readme viewer",
      "npm package maintainers checker",
      "is npm package deprecated",
      "npm package deprecated check",
      "npm package weekly downloads",
      "npm download count checker",
      "npm package popularity score",
      "best way to check npm package quality",
      "should i install this npm package",
      "npm package security check free",
      "npm package health grade",
      "npm health check tool online",
      "npm package due diligence",
      "npm package evaluation tool",
      "evaluate npm package online",
      "npm package reliability checker",
      "npm package health report",
      "npm package freshness checker"
    ],
  };

export default seo;
