import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Base Converter - Free Online Number Base Converter Tool | IconVault",
    metaDescription: "Convert between binary, octal, decimal and hexadecimal with a clickable bit visualizer and two's complement mode. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Base Converter** converts numbers between **binary**, **octal**, **decimal** and **hexadecimal** instantly, using **BigInt** so even very large values convert exactly. Type in any base and see all four representations at once, explore the value with a **clickable bit visualizer** at any **bit width**, and switch on **two's complement mode** to see how signed integers are stored.",
      "Everything runs **fully in your browser** with no signup, and it is **free** to use. It is a learning and debugging aid for programmers, students and electronics hobbyists, not a calculator for financial or cryptographic work, so always double check results that feed into real systems."
    ],
    faqs: [
      { q: "Which number bases are supported?", a: "Binary (base 2), octal (base 8), decimal (base 10) and hexadecimal (base 16). Type a value in any one base and the other three update instantly." },
      { q: "What is the bit visualizer?", a: "It shows the value as individual bits you can click to toggle, grouped in fours for readability. Change the bit width to 8, 16, 32 or more and watch how the same value is represented at different widths." },
      { q: "What does two's complement mode do?", a: "It interprets the bits as a signed integer using two's complement, the standard way computers store negative numbers. Toggle it to see the signed and unsigned readings side by side." },
      { q: "Can it handle very large numbers?", a: "Yes. The converter uses BigInt internally, so huge values convert exactly instead of losing precision the way normal floating point math would." },
      { q: "Is my input sent anywhere?", a: "No. Conversion happens entirely in your browser with JavaScript. Nothing is uploaded or logged." },
      { q: "Is it free?", a: "Yes, completely free with no signup and no limits." }
    ],
    tags: [
      "number base converter",
      "base converter online",
      "binary to decimal converter",
      "decimal to binary converter",
      "hex to decimal converter",
      "decimal to hex converter",
      "binary to hex converter",
      "hex to binary converter",
      "octal to decimal converter",
      "decimal to octal converter",
      "binary to octal converter",
      "octal to binary converter",
      "hex to octal converter",
      "octal to hex converter",
      "convert binary to decimal online free",
      "convert hex to decimal",
      "convert decimal to hexadecimal",
      "number system converter",
      "numeral system converter",
      "binary octal decimal hexadecimal converter",
      "bit visualizer",
      "binary bit visualizer",
      "clickable bits binary",
      "binary bits calculator",
      "twos complement calculator",
      "twos complement converter",
      "twos complement to decimal",
      "decimal to twos complement",
      "signed binary converter",
      "binary to signed decimal",
      "big number base converter",
      "large binary to decimal",
      "bigint base conversion",
      "binary calculator online",
      "hex calculator online",
      "programmers calculator online",
      "number base converter free",
      "convert 255 to binary",
      "what is 255 in binary",
      "what is ff in decimal",
      "binary to decimal table",
      "hex to decimal table",
      "how to convert binary to decimal",
      "how to convert decimal to binary",
      "how to convert hex to decimal",
      "binary number converter",
      "hexadecimal converter online",
      "octal converter online",
      "bit width converter",
      "8 bit binary converter",
      "16 bit hex converter",
      "32 bit binary to decimal",
      "binary to ascii converter",
      "ascii to binary converter",
      "base 2 to base 16"
    ],
  };

export default seo;
