import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "OCR Extractor - Free Online Image to Text Tool | IconVault",
    metaDescription: "Extract text from images with on-device OCR. English, live progress, copy or download as .txt. Free and private, runs fully in your browser.",
    about: [
      "**IconVault**'s **OCR Extractor** pulls text out of images using **on-device OCR** powered by **Tesseract.js**, so your image is never uploaded to a server. Drop in a screenshot, photo or scan, watch the **live progress bar**, then copy the recognized text or download it as a **.txt file**. Recognition happens right in your browser tab.",
      "It is **free** with no signup and fully private. Two honest notes: the first run downloads the **English language model** once (it is cached after that), and accuracy depends on image quality, so sharp, high-contrast images give the best results. Stylized fonts, heavy blur or busy backgrounds will reduce accuracy."
    ],
    faqs: [
      { q: "How does the OCR extractor work?", a: "It runs Tesseract.js, a well-known open-source OCR engine, directly in your browser. Your image is processed locally and the recognized text appears with a progress bar while the engine works." },
      { q: "Is my image uploaded anywhere?", a: "No. Recognition happens on your device. The only download is the OCR language model on first use, which is then cached by your browser." },
      { q: "Which languages are supported?", a: "English. The tool loads the English trained data, so it works best on English text in printed or screen fonts." },
      { q: "What image types can I use?", a: "Any common image format your browser can open: PNG, JPG, WebP and similar. Screenshots, document photos, scans and pictures of signs all work." },
      { q: "Why is some text recognized incorrectly?", a: "OCR accuracy depends on image quality. Low resolution, blur, rotation, shadows and decorative fonts all hurt recognition. For best results use a sharp, straight, high-contrast image." },
      { q: "Can I download the extracted text?", a: "Yes. You can copy it to your clipboard or download it as a .txt file named after your image." }
    ],
    tags: [
      "ocr online free",
      "image to text converter",
      "extract text from image",
      "picture to text converter",
      "photo to text converter",
      "screenshot to text converter",
      "ocr extractor",
      "free ocr tool",
      "online ocr no signup",
      "ocr in browser",
      "on device ocr",
      "private ocr tool",
      "ocr without uploading",
      "extract text from screenshot",
      "extract text from photo",
      "image to text free",
      "jpg to text converter",
      "png to text converter",
      "convert image to editable text",
      "scan image to text",
      "document scanner text extraction",
      "photo of document to text",
      "receipt to text converter",
      "business card to text",
      "book page to text converter",
      "whiteboard to text converter",
      "meme text extractor",
      "extract text from meme",
      "tesseract ocr online",
      "tesseract.js demo",
      "ocr progress bar",
      "ocr download as txt",
      "copy text from image",
      "how to copy text from an image",
      "how to extract text from a screenshot",
      "image text recognition",
      "optical character recognition online",
      "ocr english",
      "best free ocr online",
      "ocr tool no watermark",
      "unlimited ocr free",
      "png image to text",
      "jpeg to text",
      "webp to text",
      "screenshot text copy tool",
      "grab text from image",
      "convert photo to text free",
      "picture to text free no signup",
      "ocr for students",
      "ocr for developers",
      "extract code from screenshot",
      "screenshot code to text",
      "image to text converter online free",
      "english ocr online",
      "text scanner online",
      "free text scanner"
    ],
  };

export default seo;
