import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "OG Checker - Free Online Open Graph Validator Tool | IconVault",
    metaDescription: "Validate Open Graph and Twitter card meta tags: paste page HTML to check og:title, og:image, twitter:card and more. Free, 100% in your browser.",
    about: [
      "**IconVault**'s **OG Checker** validates your **Open Graph** and **Twitter card** meta tags so your links look right when shared. Paste a page's **HTML** and it checks the required tags (**og:title**, **og:type**, **og:image**, **og:url**) plus recommended ones (**og:description**, **og:site_name**, **twitter:card**, image dimensions), reporting **pass, warn or fail** for each with a plain-English hint on how to fix it.",
      "It is **free**, needs no signup, and runs **100% in your browser**. One honest note: fetching a URL directly is usually blocked by **CORS**, so for a full check you paste your page's HTML (View Source, copy, paste). The checker validates tags, it does not render the final preview exactly as each social network would."
    ],
    faqs: [
      { q: "How do I check my page's Open Graph tags?", a: "Open your page, use View Source, copy the HTML, and paste it into the checker. It parses all meta tags and validates the Open Graph and Twitter card set with pass, warn or fail statuses." },
      { q: "Why can't I just paste a URL?", a: "Browsers block cross-site fetching through CORS, so most sites cannot be fetched directly from a web page. Pasting the HTML gives the same validation result without the restriction." },
      { q: "Which tags are required?", a: "og:title, og:type, og:image and og:url are treated as required. og:description, og:site_name, twitter:card and og:image:width/height are recommended for the best-looking previews." },
      { q: "What image size should og:image be?", a: "1200 x 630 pixels is the widely recommended size for link previews, using an absolute https URL. Declaring og:image:width and og:image:height explicitly helps scrapers render faster." },
      { q: "Will this fix my broken link preview?", a: "It will show you exactly which tags are missing or misconfigured, which is the cause of most broken previews. After fixing, remember that social networks cache previews, so you may need to re-scrape the URL in their debugger." },
      { q: "Is my HTML sent to a server?", a: "No. Parsing and validation happen entirely in your browser. Nothing is uploaded or stored." }
    ],
    tags: [
      "open graph checker",
      "og tag checker",
      "open graph validator",
      "twitter card validator",
      "check og tags",
      "open graph debugger",
      "facebook open graph checker",
      "linkedin preview checker",
      "social media preview checker",
      "link preview checker",
      "website link preview test",
      "og image checker",
      "check og:image tag",
      "twitter card checker",
      "twitter card preview tool",
      "meta tag checker",
      "seo meta tags checker",
      "open graph tags list",
      "required open graph tags",
      "og:title og:description checker",
      "validate open graph html",
      "paste html check meta tags",
      "open graph checker online free",
      "why is my link preview not showing",
      "link preview image not showing",
      "facebook link preview not working",
      "twitter card image not showing",
      "discord link embed not working",
      "slack link preview not showing",
      "whatsapp link preview image",
      "telegram link preview",
      "og:image size requirements",
      "open graph image dimensions",
      "1200x630 og image",
      "twitter summary_large_image",
      "twitter card types",
      "og:type website vs article",
      "og:url canonical",
      "og:site_name",
      "og:description length",
      "how to add open graph tags",
      "open graph tags example",
      "open graph protocol",
      "meta property og tags",
      "check meta tags of a website",
      "html meta tag validator",
      "social share preview tester",
      "debug social media preview",
      "open graph checker no signup",
      "free og tag validator",
      "twitter meta tags checker",
      "check twitter:card tag",
      "open graph image width height tags",
      "facebook sharing debugger alternative",
      "og checker",
      "og tag validator",
      "facebook debugger alternative",
      "opengraph validator online",
      "validate og tags",
      "og meta tag checker",
      "validate twitter card",
      "og image validator",
      "check og image",
      "og title checker",
      "social preview checker",
      "facebook link preview check",
      "how to check open graph tags",
      "og debugger online",
      "meta tag validator open graph",
      "check meta tags for social sharing",
      "facebook sharing debugger",
      "linkedin post inspector",
      "whatsapp link preview checker",
      "discord embed checker",
      "slack unfurl checker",
      "telegram link preview check",
      "og tags missing",
      "og image not showing",
      "facebook not showing og image",
      "og image size",
      "og image dimensions",
      "og image 1200x630",
      "twitter summary large image",
      "twitter card image size",
      "og type website",
      "og url tag",
      "og site name",
      "og description",
      "og locale",
      "og video tags",
      "article og tags",
      "product og tags",
      "open graph for nextjs",
      "open graph react",
      "nextjs metadata og",
      "generate og tags",
      "og tag generator",
      "open graph tags explained",
      "og tags seo",
      "social media meta tags",
      "validate html meta tags",
      "view page source meta tags"],
  };

export default seo;
