import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "OpenAPI Viewer - Free Online Swagger Spec Viewer Tool | IconVault",
    metaDescription: "Paste or upload an OpenAPI/Swagger spec and browse endpoints grouped by tag, with methods, parameters and responses. Free, no requests executed.",
    about: [
      "**IconVault**'s **OpenAPI Viewer** turns a raw **OpenAPI** or **Swagger** spec into a readable API reference. Paste or upload your spec in **JSON or YAML** and browse every **endpoint grouped by tag**, with **HTTP methods**, summaries, **parameters**, request bodies and **responses** laid out clearly, plus search to jump to the operation you need. A built-in sample spec lets you explore before loading your own.",
      "It is **free** with no signup, and your spec is only **visualized**: no requests are executed and nothing is uploaded. The honest limitation: this is a viewer, not a try-it-out client, so you cannot send live requests from here, use a dedicated API client for that."
    ],
    faqs: [
      { q: "What file formats can I load?", a: "OpenAPI and Swagger specs in JSON or YAML format. You can paste the text directly or upload a .json, .yaml or .yml file." },
      { q: "Are any API requests executed?", a: "No. The tool only parses and displays your spec. It never calls your API, so it is safe to load internal or production specs." },
      { q: "Is my spec uploaded to a server?", a: "No. Parsing and rendering happen entirely in your browser. Your spec never leaves your device." },
      { q: "Does it support OpenAPI 3 and Swagger 2?", a: "Yes. Both OpenAPI 3.x and Swagger 2.0 style specs are parsed, and endpoints are grouped by their tags with method badges for GET, POST, PUT, PATCH, DELETE and the rest." },
      { q: "Can I see request and response schemas?", a: "Yes. Parameters, request bodies and responses from each operation are shown with their descriptions and schemas where the spec defines them." },
      { q: "Is there a sample I can try first?", a: "Yes. A built-in demo store API spec loads with one click so you can see how the viewer organizes endpoints before pasting your own." }
    ],
    tags: [
      "openapi viewer",
      "swagger viewer",
      "openapi spec viewer online",
      "swagger ui alternative",
      "view openapi json online",
      "openapi yaml viewer",
      "swagger editor online free",
      "openapi documentation viewer",
      "browse api endpoints",
      "api spec viewer",
      "openapi 3 viewer",
      "swagger 2 viewer",
      "paste openapi spec",
      "upload swagger file",
      "openapi json visualizer",
      "api documentation browser",
      "rest api viewer",
      "endpoints by tag viewer",
      "openapi tags browser",
      "view api methods and parameters",
      "openapi parameters viewer",
      "api request response viewer",
      "swagger json viewer online",
      "openapi online tool free",
      "no signup openapi viewer",
      "openapi viewer no server",
      "private swagger viewer",
      "openapi spec validator viewer",
      "what is openapi",
      "what is swagger",
      "openapi vs swagger",
      "openapi example spec",
      "sample openapi json",
      "openapi 3.0 example",
      "how to read an openapi spec",
      "openapi paths explained",
      "rest api documentation tool",
      "api reference viewer",
      "generate api docs from openapi",
      "openapi to documentation",
      "swagger file reader",
      "openapi file reader online",
      "view yaml api spec",
      "convert swagger to readable docs",
      "openapi explorer",
      "api endpoint list generator",
      "list all api endpoints from spec",
      "openapi methods get post put delete",
      "swagger operations viewer",
      "openapi schema viewer",
      "api spec pretty viewer",
      "free api documentation viewer"
    ],
  };

export default seo;
