import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "package.json Generator - Free Online package.json Maker Tool | IconVault",
    metaDescription: "Build a valid package.json visually: project type presets, name, version, scripts, dependencies, engines. Live preview, copy or download. Free.",
    about: [
      "**IconVault**'s **package.json Generator** builds a valid **package.json** visually, no memorized field names required. Pick a **project type** (app, library or CLI) for sensible presets, then fill in name, version, description, author and license, add or remove **scripts**, **dependencies** and **devDependencies** with versions, set **engines**, and watch the **live JSON preview** update as you type. Copy it or download the finished file when you are done.",
      "It is **free**, needs no signup, and runs **100% client-side**. The honest note: the tool produces clean, valid JSON with correct structure, but it cannot know your exact dependency versions, so double check version ranges against the registry before you publish or commit."
    ],
    faqs: [
      { q: "What project types are supported?", a: "App, library and CLI presets. Each sets sensible defaults: apps get dev/build/preview scripts, libraries get build/test/prepublishOnly with dist output, and CLIs get a bin entry wired up." },
      { q: "Can I add my own scripts and dependencies?", a: "Yes. Scripts, dependencies, devDependencies and engines are all editable lists: add rows, set names and values, and remove anything you do not need." },
      { q: "Is the generated JSON valid?", a: "Yes. The preview is built from a real object and serialized with JSON.stringify, so it is always syntactically valid. Field names follow the npm package.json specification." },
      { q: "How do I get the file out?", a: "Copy the JSON to your clipboard with one click, or download it as package.json and drop it into your project folder." },
      { q: "Does it look up the latest dependency versions?", a: "No. You type the versions yourself, which keeps the tool fully offline and private. Check the npm registry for the latest versions of the packages you add." },
      { q: "Is anything uploaded?", a: "No. The whole builder runs in your browser. Nothing you type leaves your device." }
    ],
    tags: [
      "package.json generator",
      "package json generator online",
      "create package.json online",
      "package.json maker",
      "package.json builder",
      "generate package.json free",
      "package.json template",
      "package.json example",
      "sample package.json",
      "package.json fields explained",
      "package.json scripts",
      "package.json dependencies",
      "package.json devdependencies",
      "package.json engines",
      "package.json bin",
      "package.json main field",
      "package.json module field",
      "package.json types field",
      "package.json private true",
      "package.json license",
      "package.json author",
      "package.json version",
      "package.json name",
      "package.json description",
      "npm init alternative",
      "npm init online",
      "how to create a package.json",
      "package.json for cli tool",
      "package.json for library",
      "package.json for node app",
      "node project setup tool",
      "javascript project scaffolder",
      "package.json validator",
      "valid package.json generator",
      "package.json copy paste",
      "download package.json",
      "package.json scripts examples",
      "common npm scripts",
      "package.json scripts dev build test",
      "add dependency to package.json",
      "package.json dependencies vs devdependencies",
      "package.json engines node version",
      "what is package.json",
      "package.json explained",
      "package.json keywords",
      "package.json files field",
      "package.json sideeffects",
      "package.json exports field",
      "package.json workspaces",
      "monorepo package.json",
      "typescript package.json template",
      "vite package.json template",
      "react package.json example",
      "node cli package.json example"
    ],
  };

export default seo;
