import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Page Lifecycle Playground - Interactive Web API Lab | IconVault",
    metaDescription: "Master the page lifecycle: live state machine, freeze and resume, visibility changes, bfcache eligibility and an event log. Free, in your browser.",
    about: [ "**IconVault**'s **Page Lifecycle Playground** visualizes the real **page lifecycle** state machine: **active**, **passive**, **hidden**, **frozen**, **terminated** and **discarded**, with live **visibility** tracking, **freeze and resume** simulation, **bfcache eligibility** checks that flag what blocks back-forward cache, and a full **event log** of every transition. It is free and runs fully in your browser.", "You will learn why the old `unload` event is unreliable on mobile and what to use instead: `pagehide`, `visibilitychange` and `freeze` for saving state. The lab shows how to make pages **bfcache-friendly** (no unload listeners, careful with open connections), how frozen pages stop timers and network, and the resume pattern that restores state when the user navigates back." ],
    faqs: [ { q: "What are the page lifecycle states?", a: "Active, passive, hidden, frozen, terminated and discarded. The lab renders the state machine live and highlights your page's current state." }, { q: "Why should I stop using the unload event?", a: "Mobile browsers often skip unload entirely, and pages with unload listeners are blocked from the back-forward cache. Use pagehide or visibilitychange instead." }, { q: "What is bfcache?", a: "The back-forward cache keeps a frozen snapshot of the page so back/forward navigation is instant. The lab checks common blockers like unload listeners and open IndexedDB transactions." }, { q: "What happens when a page is frozen?", a: "Timers stop, network requests pause and the page cannot run JavaScript, which saves battery and memory. The lab simulates freezing and logs the freeze and resume events." }, { q: "How do I save state before the page goes away?", a: "Listen for pagehide or visibilitychange with visibilityState hidden, and persist to IndexedDB or sessionStorage. The lab demonstrates the pattern." }, { q: "What is the difference between pagehide and visibilitychange?", a: "visibilitychange fires when the tab becomes hidden or visible; pagehide fires when navigating away, with a persisted flag telling you if bfcache took the page." } ],
    tags: [ "page lifecycle api", "page lifecycle javascript", "page lifecycle states", "bfcache", "back forward cache", "pageshow pagehide", "visibilitychange", "document.visibilitystate", "freeze resume page", "page freeze event", "unload vs pagehide", "beforeunload", "discarded page", "passive state page", "page lifecycle tutorial", "page lifecycle example", "page lifecycle demo", "page lifecycle playground", "mdn page lifecycle", "web page states", "mobile page lifecycle", "save state before unload", "persist state javascript", "sessionstorage pagehide", "indexeddb pagehide", "bfcache eligibility", "bfcache blockers", "unload listener bfcache", "make page bfcache friendly", "back button instant", "navigation instant back", "frozen page timers", "chrome page lifecycle", "page lifecycle chrome", "caniuse pagefreeze", "is pagehide supported", "page lifecycle typescript", "web performance bfcache", "core web vitals bfcache", "why unload is bad", "pagehide persisted", "pageshow persisted", "restore state back navigation", "lifecycle event log", "test bfcache online", "devtools bfcache tester", "web page lifecycle guide", "bfcache test online", "page states diagram", "web lifecycle events" ],
  };

export default seo;
