import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Passport Photo Maker - Free Online Tool | IconVault",
    metaDescription: "Crop and size photos to passport and visa dimensions at 300 DPI. Drag to position, zoom, export JPG. Free and private.",
    about: [
      "**IconVault**'s **Passport Photo Maker** crops and sizes your photo to official document dimensions at **300 DPI**: US passport/visa 2x2in, UK 35x45mm, India 35x45mm, India visa/OCI 51x51mm, Schengen 35x45mm, Canada 50x70mm, China 33x48mm and Australia 35x45mm, with millimeter-to-pixel conversion done for you and DPI embedded in the file.",
      "Drag to position your face, use the **zoom slider**, pick a **fill color** for empty areas, and export a print-ready **JPG**. Honest note: this tool **crops and sizes only**, it does not change the background, so shoot against a plain light wall. Everything runs **in your browser**: your photo never leaves your device. **Free** with a daily trial, unlimited with Pro.",
    ],
    faqs: [
      { q: "Which document sizes are supported?", a: "US passport/visa 2x2in (600x600px), UK, India, Schengen and Australia 35x45mm, India visa/OCI 51x51mm, Canada 50x70mm and China 33x48mm, all rendered at 300 DPI with the density embedded in the JPG." },
      { q: "How do I frame my face correctly?", a: "Drag the photo inside the preview frame to position yourself, then use the zoom slider (100 to 300%) to size your head correctly for the document's requirements." },
      { q: "Does it remove or change the background?", a: "No. It crops and sizes only and does not alter the background. Shoot against a plain light wall or door for a compliant photo, and use the fill color for any empty edges." },
      { q: "What is the 300 DPI for?", a: "Printers and photo labs read DPI to size the print correctly. 300 DPI is the standard for photo-quality printing, and this tool writes it into the JPG metadata." },
      { q: "Is my photo uploaded to a server?", a: "No. Cropping and encoding happen locally in your browser. Nothing leaves your device." },
      { q: "Is it free?", a: "Yes, with a daily free trial limit. IconVault Pro unlocks unlimited exports across all tools." },
    ],
    tags: [ "passport photo maker", "passport photo online", "visa photo maker", "2x2 passport photo", "35x45mm photo maker", "indian passport photo size", "us visa photo tool", "schengen visa photo", "canada passport photo size", "china visa photo size", "300 dpi passport photo", "crop photo for passport", "id photo maker online", "passport photo jpg", "oci photo size", "uk passport photo", "australia passport photo", "visa photo dimensions", "free passport photo tool", "print passport photo at home" ,
      "make passport photo online free",
      "passport photo maker free",
      "best passport photo maker",
      "online passport photo maker",
      "passport size photo maker",
      "create passport photo free",
      "passport photo from selfie",
      "selfie to passport photo",
      "passport photo background remover",
      "white background passport photo",
      "passport photo white background online",
      "id photo maker free",
      "visa photo maker online free",
      "us passport photo online",
      "indian passport photo online",
      "uk passport photo online",
      "biometric passport photo",
      "passport photo requirements",
      "passport photo size in pixels",
      "passport photo 600x600",
      "2x2 inch photo maker",
      "35x45 mm photo online",
      "51x51 mm photo maker",
      "passport photo digital copy",
      "digital passport photo",
      "passport photo for online application",
      "oci photo maker online",
      "pan card photo resizer",
      "aadhaar photo maker",
      "driving licence photo maker",
      "passport photo editor free",
      "crop image to passport size",
      "resize photo to passport size",
      "passport photo background changer",
      "change passport photo background",
      "passport photo with formal dress",
      "baby passport photo maker",
      "infant passport photo",
      "passport photo checker",
      "passport photo size guide"],
  };

export default seo;
