import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Password Strength - Free Online Password Security Tool | IconVault",
    metaDescription: "Test password strength with entropy analysis, a 5-bar meter and crack-time estimates for online, bcrypt and fast-hash attacks. Free, fully in your browser.",
    about: [
      "**IconVault**'s **Password Strength** checker measures how hard your password really is to crack using **entropy math**, not guesswork. Type any password and get its **entropy in bits**, a **5-bar strength meter** from Very weak to Very strong, and a breakdown of your **character-class pool** (lowercase, uppercase, digits, symbols) so you can see exactly what adds strength.",
      "It also shows **estimated crack times** for three realistic attackers: an **online attack** with rate limits, a stolen **bcrypt** hash database, and a stolen **fast-hash** database attacked with a GPU rig, plus personalized tips on how to make your password stronger. It is **free** and runs **fully in your browser**, so your password is analyzed in this tab only and is **never sent, stored or logged**. The honest caveat: estimates assume random guessing against the full pool, while real attackers try **dictionaries, leaks and common patterns** first, so a common word falls far faster than the math suggests."
    ],
    faqs: [
      { q: "How is password strength calculated?", a: "The tool measures entropy in bits: password length multiplied by log2 of the character pool size. The pool is built from the character classes your password uses (lowercase 26, uppercase 26, digits 10, symbols 32). More bits means exponentially more guesses needed to crack it." },
      { q: "Is my password sent to a server?", a: "No. The analysis runs entirely in your browser tab. Your password is never sent anywhere, never stored, never logged, and never leaves your device." },
      { q: "What do the crack-time estimates mean?", a: "They divide the expected number of guesses (half of 2^bits) by three attacker speeds: 10 guesses per second for an online login form with rate limits, 10,000 per second for a stolen bcrypt hash database, and 10 billion per second for a stolen fast hash like SHA-1 attacked with a GPU rig." },
      { q: "Why does it say length beats complexity?", a: "Each extra character multiplies the search space by the whole pool size. A 20-character passphrase of plain words has far more entropy than an 8-character mix of symbols, and it is easier to remember and type." },
      { q: "My password uses common words. Is it really that weak?", a: "Yes, in practice. The entropy math assumes random guessing, but real attackers try dictionaries, password leaks and predictable patterns first. A common word or a year at the end falls much faster than the raw bit count suggests." },
      { q: "What makes a strong password?", a: "At least 12 to 16 characters, ideally a passphrase of four or more random words, mixed character classes, and no repeats or predictable patterns. The tool's tip list tells you exactly which of these your password is missing." }
    ],
    tags: [
      "password strength checker",
      "password strength test",
      "check password strength online",
      "test my password strength",
      "how strong is my password",
      "password entropy calculator",
      "password crack time estimator",
      "password meter online",
      "strong password checker",
      "password security check",
      "password tester",
      "test password strength free",
      "online password strength checker",
      "password entropy test",
      "how long to crack my password",
      "password bits of entropy calculator",
      "password strength meter tool",
      "check if password is strong",
      "password score checker",
      "weak password checker",
      "is my password strong enough",
      "password complexity checker",
      "password brute force time calculator",
      "how much entropy does my password have",
      "password strength analyzer",
      "password security tester online",
      "free password strength checker",
      "test password security online",
      "passphrase strength checker",
      "password length vs complexity",
      "how to make my password stronger",
      "strong password requirements checker",
      "password vulnerability checker",
      "check password entropy online",
      "online password analyzer",
      "password strength estimate tool",
      "how secure is my password",
      "password guessing time calculator",
      "dictionary attack password crack time",
      "password pool size calculator",
      "minimum password length check",
      "passphrase entropy calculator",
      "password safety tips checker",
      "password rating tool",
      "online password security tool",
      "password cracker time estimate",
      "entropy bits password test",
      "password analysis tool free",
      "secure password checker online",
      "how to create strong password",
      "password hack time calculator"
    ],
  };

export default seo;
