import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Passport Photo Sheet - Free Online Tool | IconVault",
    metaDescription: "Print multiple passport photos on one 4x6in or A4 sheet with cut guides at 300 DPI. Free and browser-private.",
    about: [
      "**IconVault**'s **Passport Photo Sheet** lays out multiple copies of your photo on a single printable sheet, so one print gives you several passport photos. Choose **35 x 45 mm (India, UK, EU), 2 x 2 in (US), or 51 x 51 mm (OCI, visa)**, pick a **4 x 6 in or A4 sheet**, and the tool arranges your photos at **300 DPI** with optional **cut guides** and a thin border. It is **free**, runs **100% in your browser**, and your photo never leaves your device.",
      "Set the **gap** between photos, pick **Auto** orientation to fit the most copies, and print at **100% / actual size** so the measurements stay exact. **Pro** members get unlimited sheets; free users get a trial quota.",
    ],
    faqs: [
      { q: "How many passport photos fit on a 4x6 sheet?", a: "With 35 x 45 mm photos and a 2 mm gap, up to 8 fit in landscape orientation (4 x 2). The tool shows the exact capacity for your settings before you create the sheet." },
      { q: "What DPI is the sheet?", a: "300 DPI, the standard for photo printing. The DPI is embedded in the PNG so print software reads it correctly." },
      { q: "Which photo sizes are supported?", a: "35 x 45 mm (India, UK, EU), 2 x 2 in (US), and 51 x 51 mm (OCI, visa applications)." },
      { q: "What are cut guides?", a: "Dashed lines around each photo that show where to trim after printing. Turn them on for neat cutting with scissors or a paper trimmer." },
      { q: "How should I print the sheet?", a: "Print at 100% / actual size, not fit to page. Scaling the page changes the photo dimensions and they will no longer be the right size." },
      { q: "Is my photo uploaded anywhere?", a: "No. The sheet is composed entirely in your browser, so your photo never leaves your device." },
    ],
    tags: ["passport photo sheet", "passport photo print sheet", "4x6 passport photo sheet", "a4 passport photo sheet", "multiple passport photos one page", "35x45mm photo sheet", "2x2 inch photo sheet", "51x51mm photo sheet", "oci photo sheet", "visa photo sheet", "passport photo cut guides", "300 dpi photo sheet", "print passport photos at home", "free passport photo sheet", "online passport photo printer", "indian passport photo 35x45", "us visa photo 2x2", "photo sheet generator", "passport photo collage print", "id photo sheet maker",
      "passport photo sheet maker",
      "passport photo sheet online free",
      "make passport photo sheet",
      "create passport photo sheet",
      "passport photo sheet generator free",
      "best passport photo sheet maker",
      "passport photo print layout",
      "passport photo layout maker",
      "arrange passport photos on a4",
      "multiple passport photos on 4x6",
      "6 passport photos on 4x6",
      "8 passport photos on a4",
      "passport photo grid print",
      "passport photo sheet pdf",
      "download passport photo sheet",
      "passport photo sheet jpg",
      "visa photo print sheet",
      "id photo print sheet",
      "2x2 photo sheet maker",
      "35x45 photo sheet maker",
      "custom size photo sheet",
      "passport photo sheet with cut lines",
      "photo sheet with cutting guides",
      "print multiple id photos",
      "print id photos at home free",
      "diy passport photo printing",
      "passport photo sheet app alternative",
      "online photo sheet maker",
      "free photo sheet generator",
      "photo sheet maker online free",
      "wallet size photo sheet",
      "stamp size photo sheet",
      "4 passport photos one page",
      "12 passport photos one page",
      "passport photo sheet 300 dpi",
      "high resolution photo sheet",
      "photo sheet for studio printing",
      "passport photo sheet template",
      "a4 photo sheet template",
      "4x6 photo sheet template"],
  };

export default seo;
