import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Paste Image to File - Free Online Tool | IconVault",
    metaDescription: "Paste an image with Ctrl+V and save it as PNG, JPG or WebP, free in your browser. No uploads, fully private.",
    about: [
      "**IconVault**'s **Paste Image to File** saves whatever is on your **clipboard** as a real image file, right in your browser. Copy a screenshot, photo or meme, press **Ctrl+V** anywhere on the page, and download it as **PNG, JPG or WebP**. The tool is completely **free**, and your images **never leave your device**.",
      "The **file name** is prefilled with the date and time so saves never clash, and you can rename it freely. Drag-drop and file browsing work too, not just pasting. **IconVault Pro** removes trial limits for unlimited pastes.",
    ],
    faqs: [
      { q: "Is Paste Image to File free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited pastes." },
      { q: "Is my pasted image uploaded?", a: "No. Everything stays in your browser, so your clipboard images stay private." },
      { q: "How do I paste?", a: "Copy any image, then press Ctrl+V (or Cmd+V on Mac) anywhere on this page." },
      { q: "Which formats can I save as?", a: "PNG for lossless quality, JPG for small photos, WebP for the best of both." },
      { q: "What is the default file name?", a: "It is prefilled as pasted-image-YYYY-MM-DD-HHMM, and you can rename it before downloading." },
      { q: "Can I use drag-drop instead?", a: "Yes. Drop an image onto the page or click to browse your files." },
    ],
    tags: ["paste image", "paste image to file", "clipboard to image", "save clipboard image", "paste screenshot", "ctrl v image", "clipboard image saver", "paste image online", "screenshot to png", "paste image free", "save pasted image", "clipboard to png", "paste to jpg", "image paste tool", "paste image download", "screenshot saver", "paste image no signup", "clipboard image download", "paste photo", "paste image private",
      "paste image online free",
      "paste image from clipboard",
      "paste and save image",
      "ctrl v to save image",
      "paste screenshot online",
      "paste screenshot to file",
      "save screenshot from clipboard",
      "clipboard image to file",
      "clipboard to png online",
      "clipboard to jpg",
      "clipboard image converter",
      "convert clipboard to image",
      "paste image and download",
      "download pasted image",
      "paste image as png",
      "paste image as jpg",
      "paste image as webp",
      "screenshot clipboard saver",
      "save clipboard screenshot",
      "snipping tool image saver",
      "paste print screen image",
      "paste image from snip",
      "online clipboard viewer",
      "view clipboard image online",
      "paste image no download app",
      "paste image in browser",
      "how to save pasted image",
      "how to paste a screenshot",
      "paste image to png free",
      "paste image to jpg free",
      "paste multiple images",
      "paste image history",
      "clipboard image download free",
      "paste photo from clipboard",
      "paste image and share link",
      "quick image paste tool",
      "instant screenshot to file",
      "paste image file converter",
      "paste image rename download",
      "paste image without app"],
  };

export default seo;
