import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "PDF Signature - Free Online PDF Signing Tool | IconVault",
    metaDescription: "Draw your signature and place it on any PDF page, or add a typed name. Electronic signature for informal use, free and fully in your browser.",
    about: [
      "**IconVault**'s **PDF Signature** tool lets you sign a PDF without printing, scanning or installing anything. **Draw your signature** with mouse or touch on the signature pad, or **type your name** to place it as styled text, then pick the **page, position and size** with a live placement preview before downloading the signed file.",
      "It is **free** and runs **fully in your browser**, so your document is processed locally and **never uploaded** to any server. The honest note: this adds an **electronic signature for informal use** (a drawn image or typed name on the page). It is **not a certified digital signature** and carries no cryptographic proof of identity, so it suits everyday agreements, forms and internal approvals rather than documents that legally require certified signing."
    ],
    faqs: [
      { q: "Is this a legally certified digital signature?", a: "No. This tool places a drawn image or typed name onto the PDF page, which is an electronic signature for informal use. It is not a certificate-based digital signature and carries no cryptographic proof of identity. For documents that require certified signatures, use a dedicated e-signature service." },
      { q: "Is my PDF uploaded anywhere?", a: "No. The PDF is loaded and edited entirely in your browser using pdf-lib. Your document never leaves your device." },
      { q: "Can I sign a specific page of a long PDF?", a: "Yes. Select any page from 1 to the total page count, and the placement preview shows a proportional outline of where your signature will land on that page." },
      { q: "How do I position the signature precisely?", a: "Use the X and Y sliders, measured in PDF points from the bottom-left corner of the page, plus a size slider from 30% to 200%. The dashed preview box updates live as you adjust." },
      { q: "Why does my PDF fail to load?", a: "The most common cause is an encrypted or password-protected PDF, which the tool cannot open. Try removing the password protection in another app first, then load it here." },
      { q: "Can I use a drawn and a typed signature together?", a: "Yes. If both are set, the typed name is placed as text just under your drawn signature. You can also use either one on its own." }
    ],
    tags: [
      "sign pdf online free",
      "pdf signature online",
      "add signature to pdf",
      "draw signature on pdf",
      "electronic signature pdf online",
      "sign pdf document online",
      "digital signature for pdf free",
      "put signature on pdf",
      "sign pdf without printing",
      "how to sign a pdf",
      "add signature to pdf online free",
      "sign pdf in browser",
      "draw my signature online",
      "electronic sign pdf free",
      "pdf sign online free no signup",
      "add digital signature to pdf",
      "sign pdf document free",
      "type signature on pdf",
      "signature on pdf document",
      "online pdf signer",
      "free pdf signature tool",
      "add handwritten signature to pdf",
      "sign pdf with mouse",
      "esign pdf online free",
      "electronic signature maker for pdf",
      "pdf document signer online",
      "sign pdf online no account",
      "how to add signature to pdf",
      "insert signature into pdf",
      "pdf signature pad online",
      "sign pdf on phone",
      "add signature block to pdf",
      "free electronic signature for pdf",
      "online signature for documents",
      "sign pdf without adobe",
      "pdf signature app online",
      "draw signature and add to pdf",
      "sign a pdf electronically",
      "pdf signature creator free",
      "add name signature to pdf",
      "signature stamp for pdf",
      "how do i sign a pdf document",
      "pdf signing tool online",
      "sign pdf free no email",
      "online pdf signature maker",
      "place signature on pdf page",
      "add signature to pdf file",
      "sign pdf documents online free",
      "electronic signature pdf maker",
      "sign pdf online tool",
      "free online pdf signer",
      "pdf signature without software"
    ],
  };

export default seo;
