import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "PDF Toolkit - Free Online PDF Merger, Splitter and Watermark Tool | IconVault",
    metaDescription: "Merge, split, rotate, watermark and reorder PDF pages for free. Everything runs in your browser, nothing is uploaded.",
    about: [
      "**IconVault**'s **PDF Toolkit** is a five-in-one PDF editor that works without uploads or installs. **Merge** multiple PDFs into one in any order, **split** pages out by ranges like 1-3, 5, **rotate** selected pages by 90, 180 or 270 degrees, add a **text watermark** (diagonal, centered or corner, with adjustable opacity and size), and **reorder** pages with simple up and down controls.",
      "Every operation runs **fully in your browser** with pdf-lib, so your documents are **never uploaded** to a server and the tool stays **free** to use. The honest caveat: **encrypted or password-protected PDFs** cannot be opened here, so remove the password protection first in another app before loading them."
    ],
    faqs: [
      { q: "Are my PDFs uploaded to a server?", a: "No. All merging, splitting, rotating, watermarking and reordering happens in your browser with pdf-lib. Your files never leave your device." },
      { q: "How do I merge multiple PDFs?", a: "Drop two or more PDFs onto the tool, arrange them with the up and down arrows to set the page order, then click Merge and download. The output is a single PDF named merged.pdf." },
      { q: "How does the split tool work?", a: "Select a PDF and type page ranges like 1-3, 5. Each consecutive range becomes its own downloaded file, so 1-3 becomes one file and 5 becomes another." },
      { q: "Can I rotate only some pages?", a: "Yes. Type all to rotate every page, or a selection like 2, 4-6 to rotate just those pages, then choose 90, 180 or 270 degrees." },
      { q: "What watermark options are available?", a: "Any text you type, font size in points, six positions (diagonal across the page, center, or any corner), and opacity from 5% to 100%. Common uses are DRAFT, CONFIDENTIAL or SAMPLE stamps." },
      { q: "Why does my PDF fail to load?", a: "Encrypted or password-protected PDFs are not supported by the in-browser engine. Remove the password in another PDF app first, then load the file here." }
    ],
    tags: [
      "merge pdf online free",
      "split pdf online",
      "combine pdf files",
      "join pdf online",
      "rotate pdf pages",
      "add watermark to pdf",
      "reorder pdf pages",
      "pdf merger online free",
      "pdf splitter online free",
      "merge pdf files free",
      "combine pdfs into one",
      "split pdf pages",
      "pdf page rotator",
      "pdf watermark online",
      "rearrange pdf pages",
      "merge multiple pdf into one",
      "pdf joiner online",
      "free pdf tools online",
      "split pdf into separate pages",
      "rotate pdf 90 degrees",
      "add text watermark to pdf",
      "merge pdf without software",
      "online pdf toolkit",
      "pdf merge split online",
      "extract pages from pdf",
      "combine pdf documents free",
      "pdf combiner online",
      "split pdf by pages",
      "rotate all pdf pages",
      "add draft watermark to pdf",
      "merge pdf free no signup",
      "pdf page organizer",
      "reorder pages in pdf",
      "merge pdf in browser",
      "split pdf free online",
      "join multiple pdf files",
      "pdf rotation tool",
      "watermark pdf online free",
      "pdf page reorder tool",
      "combine two pdfs",
      "pdf merge tool free",
      "extract selected pages from pdf",
      "add confidential watermark pdf",
      "pdf toolkit online free",
      "merge pdf documents online",
      "split pdf document",
      "rotate pdf page online",
      "change pdf page order",
      "combine pdf online no upload",
      "pdf editing tools online",
      "free pdf merger splitter",
      "merge split rotate pdf",
      "pdf watermark maker online"
    ],
  };

export default seo;
