import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "PDF to Image Converter - Free Online Tool | IconVault",
    metaDescription: "Turn PDF pages into JPG or PNG images free in your browser. Pick pages, 72 to 300 DPI, ZIP download, no uploads.",
    about: [
      "**IconVault**'s **PDF to Image Converter** renders **PDF pages** as **JPG or PNG images** right in your browser. Choose exactly which pages to convert, pick a resolution from **72 to 300 DPI**, and download one image or a whole **ZIP** of pages. The tool is completely **free**, and your documents **never leave your device**.",
      "300 DPI gives print-quality images, 150 DPI is crisp for screens, and 72 DPI keeps files tiny. Select pages like **1-3, 5** or leave the field empty for every page. **IconVault Pro** removes trial limits for large documents.",
    ],
    faqs: [
      { q: "Is PDF to Image conversion free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited conversions." },
      { q: "Is my PDF uploaded anywhere?", a: "No. Pages render locally in your browser, so your document stays private." },
      { q: "What DPI should I choose?", a: "300 DPI for printing, 150 DPI for sharp screen use, 72 DPI for the smallest files." },
      { q: "Can I convert only some pages?", a: "Yes. Type ranges like 1-3, 5, or leave the field empty to convert every page." },
      { q: "JPG or PNG: which format is better?", a: "JPG is smaller for document pages. PNG is lossless and better for graphics-heavy pages." },
      { q: "How do I download many pages?", a: "When you convert more than one page, everything is bundled into a single ZIP download." },
    ],
    tags: ["pdf to image", "pdf to jpg", "pdf to png", "convert pdf to image", "pdf to jpg online", "pdf page to image", "pdf to image free", "pdf to jpg free", "extract images from pdf", "pdf to png online", "pdf to image dpi", "pdf to jpg 300 dpi", "pdf pages to jpg", "pdf to image batch", "pdf to image no signup", "pdf to image private", "pdf screenshot", "pdf to jpg zip", "convert pdf pages", "pdf to image tool",
      "convert pdf to image free",
      "pdf to jpg online free",
      "pdf to png online free",
      "pdf to image online free",
      "pdf to jpeg",
      "pdf to webp",
      "pdf page to jpg",
      "pdf page to png",
      "convert pdf pages to images",
      "turn pdf into images",
      "pdf to images converter",
      "best pdf to image converter",
      "pdf to image high quality",
      "pdf to image 300 dpi free",
      "pdf to jpg high resolution",
      "pdf to image no watermark",
      "free pdf to jpg converter",
      "pdf to jpg in browser",
      "how to convert pdf to jpg",
      "how to turn pdf into image",
      "each pdf page as image",
      "save pdf pages as pictures",
      "pdf to png transparent",
      "pdf to image with transparency",
      "pdf to image bulk",
      "batch pdf to image",
      "multiple pdfs to images",
      "pdf to jpg zip download",
      "pdf to png zip",
      "pdf to image for presentation",
      "pdf slides to images",
      "pdf to image for social media",
      "convert scanned pdf to image",
      "pdf to image mobile",
      "pdf to image android",
      "pdf to image iphone",
      "pdf to image without acrobat",
      "pdf to image no signup free",
      "pdf to image fast converter",
      "pdf to image converter app"],
  };

export default seo;
