import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Percentage Calculator - Free Online Percentage Tool | IconVault",
    metaDescription: "Calculate X percent of Y, what percent X is of Y, and percent increase or decrease with live results. Free and fully in your browser.",
    about: [
      "**IconVault**'s **Percentage Calculator** handles the three percentage questions people actually ask, with **live results** as you type. **X% of Y** finds a share of a value, **X is what % of Y** turns a part and whole into a percent, and **Percent change** shows increase or decrease between an old and a new value with the direction labeled.",
      "It is **free** and runs **fully in your browser**, and you can **copy the result** to your clipboard in one click. Built-in examples cover the everyday cases: **discounts** (what is 25% off 80), **tips and tax** (adding 18% to a bill), and **growth** (from 200 to 260 is a +30% change). The honest note: results are rounded to four decimal places and formatted for readability, so for high-precision engineering math verify in your own tooling."
    ],
    faqs: [
      { q: "What can this percentage calculator do?", a: "Three things: find X% of Y (for example 20% of 150 is 30), find what percent X is of Y (30 is 20% of 150), and find the percent change from an old value to a new value (from 200 to 260 is a +30% increase). Results update live as you type." },
      { q: "How do I calculate a discount?", a: "Use X% of Y mode: type 25 as X and 80 as Y to get 20, the discount amount, then subtract it from 80 to get the sale price of 60." },
      { q: "How do I calculate percent increase?", a: "Use Percent change mode: put the new value in the first box and the old value in the second. The tool shows the change amount, the direction (increase, decrease or no change), and the percentage." },
      { q: "Is my data sent anywhere?", a: "No. All calculations run in your browser. Nothing is uploaded, stored or logged." },
      { q: "Why does the result sometimes show a dash?", a: "A dash means the input is not a valid calculation, for example empty boxes, non-numbers, or dividing by zero in what-percent or percent-change mode." },
      { q: "How accurate are the results?", a: "Results are computed with standard floating-point math and shown with up to four decimal places. That is plenty for shopping, finance homework and business estimates, but verify in dedicated tooling for high-precision engineering work." }
    ],
    tags: [
      "percentage calculator",
      "percent calculator",
      "calculate percentage online",
      "what percent of",
      "x percent of y",
      "percent change calculator",
      "percentage increase calculator",
      "percentage decrease calculator",
      "how to calculate percentage",
      "percentage formula calculator",
      "find percentage of number",
      "what is x percent of y",
      "percentage of total calculator",
      "discount percentage calculator",
      "tip percentage calculator",
      "percent difference calculator",
      "percentage growth calculator",
      "markup percentage calculator",
      "percent of calculator online",
      "free percentage calculator",
      "percentage math solver",
      "calculate percent increase",
      "calculate percent decrease",
      "percentage converter calculator",
      "what percentage is x of y",
      "reverse percentage calculator",
      "original price after discount calculator",
      "percentage points calculator",
      "calculate gst percentage",
      "percentage of marks calculator",
      "percent off calculator",
      "sale price percentage calculator",
      "how to find percentage",
      "percentage increase formula",
      "percentage decrease formula",
      "percent change formula",
      "calculate percentage change online",
      "percentage calculator with steps",
      "online percent calculator",
      "math percentage calculator",
      "easy percentage calculator",
      "percent to number calculator",
      "number to percent calculator",
      "percentage difference between two numbers",
      "calculate tip percent",
      "tax percentage calculator",
      "exam percentage calculator",
      "score percentage calculator",
      "percentage profit calculator",
      "loss percentage calculator",
      "percentage share calculator",
      "fraction to percentage calculator",
      "decimal to percent calculator"
    ],
  };

export default seo;
