import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Performance Budget - Free Online Website Speed Budget Tool | IconVault",
    metaDescription: "Scan a page's real assets or enter a manual list, set per-type size budgets and see pass or fail with rough load-time estimates. Free, in your browser.",
    about: [
      "**IconVault**'s **Performance Budget** tool helps you keep websites fast by setting a **weight budget per asset type** and checking what passes. Click **Scan this page** to read the real network assets of this page through the browser's **Resource Timing API**, or build a **manual asset list** when planning a page you have not built yet, then set budgets for **JavaScript, CSS, images, fonts and other** assets and get an instant **pass or fail** verdict per type.",
      "You also get **rough load-time estimates** for Slow 3G, 4G and WiFi, a sortable **asset table** with sizes, and a **CSV export** of your asset inventory. It is **free** and runs **fully in your browser**. The honest caveat: load times are simple weight-divided-by-throughput estimates that ignore **latency, render blocking and caching**, and cached assets may report 0 bytes, so treat them as a planning signal rather than a lab measurement."
    ],
    faqs: [
      { q: "What is a performance budget?", a: "A performance budget is a size limit you set for parts of a web page, usually per asset type like JavaScript or images. If a build exceeds the budget, you investigate before shipping. This tool lets you define those limits and checks your assets against them." },
      { q: "How does the page scan work?", a: "It reads the browser's Resource Timing API, which lists every network resource the current page loaded: scripts, stylesheets, images, fonts and more. Each asset is classified by type and size, sorted biggest first, and checked against your budgets." },
      { q: "Why do some assets show 0 bytes?", a: "Assets served from the browser cache may report a transfer size of zero. The tool filters out anything under 0.5 KB, but cached resources can still skew the totals. For a true measurement, scan in a fresh profile or incognito window." },
      { q: "How accurate are the load-time estimates?", a: "They are rough. The tool divides total weight by the throughput of Slow 3G, 4G or WiFi. Real loads add DNS, TLS handshakes, latency, render blocking and compression on top, so actual times are usually higher." },
      { q: "What are sensible default budgets?", a: "The tool ships with defaults of 300 KB JavaScript, 150 KB CSS, 1000 KB images, 200 KB fonts and 500 KB other. Those are starting points, not rules: adjust them to your audience and connection profile." },
      { q: "Can I export my asset list?", a: "Yes. The CSV export downloads name, type and size in KB for every asset, which you can open in a spreadsheet or attach to a performance review." }
    ],
    tags: [
      "performance budget tool",
      "website performance budget",
      "web performance budget calculator",
      "page weight budget tool",
      "asset size budget checker",
      "javascript budget calculator",
      "core web vitals budget",
      "website speed budget planner",
      "page size checker online",
      "web page weight analyzer",
      "how big should my website be",
      "js bundle size budget",
      "image weight budget website",
      "font loading budget",
      "website load time estimator",
      "page load time calculator",
      "website speed test budget",
      "performance budget template",
      "web performance metrics tool",
      "check website asset sizes",
      "analyze page resources",
      "resource timing api tool",
      "scan webpage assets",
      "list page network assets",
      "website asset inventory tool",
      "page weight breakdown",
      "total page size calculator",
      "javascript size limit",
      "css size budget",
      "image size budget per page",
      "web performance checklist",
      "lighthouse performance budget",
      "performance budget dashboard",
      "website optimization budget",
      "front end performance budget",
      "page speed budget tool",
      "web asset size analyzer",
      "estimate load time from page weight",
      "slow 3g load time calculator",
      "4g page load estimator",
      "website bandwidth calculator",
      "page weight vs load time",
      "reduce page weight tool",
      "web performance planning tool",
      "asset budget tracker",
      "website speed optimization planner",
      "performance budget report",
      "web page size limit",
      "how fast will my page load",
      "check total page weight"
    ],
  };

export default seo;
