import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Periodic Table - Free Interactive Element Reference Tool | IconVault",
    metaDescription: "Interactive periodic table with data for all 118 elements: atomic mass, group, period, electronegativity and category. Free, fully in your browser.",
    about: [
      "**IconVault**'s **Periodic Table** is an interactive chemistry reference with built-in data for **all 118 elements**. Click any element tile to see its **atomic number, symbol, name, atomic mass, group, period, electronegativity (Pauling)** and category, or use the **search box** to find elements by name, symbol or number. A color-coded legend covers **alkali metals, alkaline earth, transition metals, metalloids, halogens, noble gases, lanthanides and actinides**.",
      "You can **copy any element's data** as plain text for homework or notes. It is **free** and works **fully in your browser** with no network calls after the page loads. The honest note: atomic masses are standard values, with **bracketed masses** showing the most stable known isotope, and electronegativity values are Pauling-scale estimates that are unknown for most synthetic elements."
    ],
    faqs: [
      { q: "How many elements are included?", a: "All 118 confirmed elements, from hydrogen (1) to oganesson (118), laid out in the standard 18-group table with the lanthanide and actinide rows." },
      { q: "What data is shown for each element?", a: "Atomic number, symbol, name, atomic mass, group, period, category (for example alkali metal or noble gas) and Pauling electronegativity where known." },
      { q: "Why are some atomic masses in brackets?", a: "Brackets mark synthetic elements with no stable isotopes: the value shown is the mass number of the most stable known isotope, not a standard atomic weight." },
      { q: "How do I search for an element?", a: "Type a name like gold, a symbol like Au, or a number like 79 into the search box. Matching elements appear in a dropdown, and clicking one jumps to its detail card." },
      { q: "Can I copy element data?", a: "Yes. The Copy element data button puts the selected element's name, symbol, atomic number, mass, group, period, category and electronegativity onto your clipboard as plain text." },
      { q: "Does this work offline?", a: "All element data is bundled into the page itself, so once the page has loaded, searching and browsing the table needs no network connection." }
    ],
    tags: [
      "periodic table",
      "periodic table of elements",
      "interactive periodic table",
      "periodic table online",
      "all 118 elements",
      "element symbols chart",
      "periodic table with atomic mass",
      "periodic table groups and periods",
      "chemistry periodic table",
      "periodic table for students",
      "element electronegativity chart",
      "atomic number lookup",
      "element properties table",
      "periodic table categories",
      "alkali metals list",
      "noble gases list",
      "halogens list",
      "transition metals list",
      "lanthanides and actinides",
      "periodic table search",
      "find element by symbol",
      "element symbol meanings",
      "periodic table printable",
      "periodic table study tool",
      "chemistry element reference",
      "periodic table quiz practice",
      "element atomic mass table",
      "metals nonmetals metalloids chart",
      "periodic trends chart",
      "group 1 elements",
      "group 17 elements",
      "group 18 elements",
      "what is the symbol for gold",
      "atomic number of carbon",
      "heaviest element",
      "lightest element",
      "most reactive metal",
      "periodic table memorization tool",
      "element data lookup",
      "chemistry homework helper",
      "periodic table app online",
      "learn periodic table online",
      "element names and symbols",
      "periodic table explained",
      "periodic table element chart",
      "element facts lookup",
      "atomic mass of oxygen",
      "symbol for iron",
      "symbol for silver",
      "interactive element table",
      "chemistry reference table",
      "periodic table element search",
      "element category chart",
      "atomic number of hydrogen",
      "symbol for copper"
    ],
  };

export default seo;
