import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Permissions Dashboard - Free Online Tool | IconVault",
    metaDescription: "Query the real Permissions API live: camera, mic, geolocation, notifications and more, with granted/denied states and working request buttons.",
    about: [
      "**IconVault**'s **Permissions Dashboard** queries your browser's real Permissions API for fourteen permission names, from camera and microphone to MIDI, wake lock, and ambient light sensors. Each row shows the live state (granted, denied, prompt, or unsupported), a summary bar counts the totals, and working Request buttons trigger the genuine browser permission prompts. It is free and runs fully in your browser.",
      "Browser permissions are confusing because every API answers differently: some support **navigator.permissions.query()**, some need a real request call to reveal their state, and a deny can only be reset in **browser settings**. This lab shows all of that in one place, explains the common gotchas (like why geolocation needs a **user gesture**, which the buttons provide), and ships a copyable code snippet for the query and **onchange listener** pattern you will reuse in every project."
    ],
    faqs: [
      { q: "What is the Permissions API?", a: "A standardized way to query the state of a permission (camera, microphone, notifications, etc.) as granted, denied, or prompt. You call navigator.permissions.query({name}) and get a PermissionStatus object you can also observe for changes." },
      { q: "What does the prompt state mean?", a: "The user has not decided yet. The next time your code triggers the real request flow, the browser will show its permission dialog. Pressing Request here fires that real prompt." },
      { q: "Why does a permission show as denied?", a: "Usually because it was blocked in the browser's site settings, either by the user or by policy. A web page cannot override a denial; the user must reset it in the browser UI." },
      { q: "Which permissions can this API query?", a: "Support varies by browser. Chrome covers camera, microphone, geolocation, notifications, clipboard, MIDI, background-sync, sensors, wake lock, storage, and a few more. Missing names report as unsupported rather than failing." },
      { q: "Why do some Request buttons do more than query?", a: "For camera, mic, and geolocation, the only honest way to change the state is the real request call (getUserMedia, getCurrentPosition). Those buttons make the genuine call, so the dashboard reflects reality." },
      { q: "Is my data sent anywhere?", a: "No. Every query and request runs locally in your browser tab. The dashboard never contacts a server and records nothing." }
    ],
    tags: [
      "permissions api",
      "permissions api javascript",
      "navigator.permissions.query",
      "browser permissions dashboard",
      "check permission status js",
      "permissionstatus",
      "permissions api tutorial",
      "permissions api example",
      "permissions query camera",
      "permissions query microphone",
      "permissions query geolocation",
      "permissions query notifications",
      "how to check camera permission js",
      "how to check microphone permission javascript",
      "notification permission check",
      "geolocation permission status",
      "request camera permission web",
      "request microphone permission browser",
      "permission granted denied prompt",
      "permissionstate granted denied prompt",
      "permissions api browser support",
      "permissions api chrome",
      "permissions api firefox",
      "permissions api safari",
      "clipboard read permission",
      "clipboard write permission",
      "persistent storage permission",
      "midi permission web",
      "background sync permission",
      "screen wake lock permission",
      "accelerometer permission",
      "gyroscope permission",
      "magnetometer permission",
      "ambient light sensor permission",
      "permission onchange listener",
      "permissions api mdn",
      "javascript permission manager",
      "web permissions list",
      "browser permission states",
      "reset site permissions chrome",
      "permission denied how to fix",
      "notification.requestpermission example",
      "getusermedia permission",
      "permissions policy vs permissions api",
      "permissions api typescript",
      "query permission name list",
      "permissions api playground",
      "test browser permissions",
      "permissions dashboard web",
      "learn permissions api",
      "permissions api code sample",
      "check all permissions website",
      "permission request button",
      "web api permission states",
      "frontend permissions handling"
    ],
  };

export default seo;
