import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Phone Parser - Free Online Phone Number Parser Tool | IconVault",
    metaDescription: "Parse phone numbers with a built-in dial-code table: detect country and get E.164, international and national formats. Free, fully in your browser.",
    about: [
      "**IconVault**'s **Phone Parser** normalizes messy phone numbers into clean, standard formats. Paste numbers one per line and it detects the **country from the dial code**, then outputs **E.164** (like +919876543210), **international** and **national** formats for each number in a simple results table, with trunk prefixes restored where the local format needs them.",
      "It is **free** and runs **fully in your browser** with a built-in table of **70+ country dial codes**, so nothing is uploaded. The honest caveat: this is **best-effort parsing**, not a full libphonenumber port, so it cannot validate area codes or number lengths per country. Always **verify critical numbers** before using them in production systems."
    ],
    faqs: [
      { q: "What formats does the parser output?", a: "Three formats per number: E.164 (+ followed by country code and digits, no spaces), international (+ country code with grouped digits), and national (local format with the trunk prefix restored, for example 0 for India and the UK)." },
      { q: "How does it detect the country?", a: "It uses longest-prefix matching against a built-in table of 70+ dial codes. If you include a + or 00 country prefix, matching is reliable. Without a prefix it falls back to matching local trunk prefixes, which is a best-effort guess." },
      { q: "What if my country code is not in the table?", a: "You will see a note saying the country code is not in the built-in table. The table covers the most-used codes worldwide, but it is not exhaustive, which is why critical numbers should be verified." },
      { q: "Can I parse many numbers at once?", a: "Yes. Paste one number per line and each is parsed into its own row in the results table, with failed parses clearly marked with an explanation." },
      { q: "Is this as accurate as libphonenumber?", a: "No, and it does not claim to be. Google's libphonenumber validates per-country rules, area codes and lengths. This tool is a lightweight in-browser normalizer for formatting and country detection, ideal for quick cleanup rather than production validation." },
      { q: "Is my phone number list uploaded anywhere?", a: "No. Parsing happens entirely in your browser. Your numbers never leave your device." }
    ],
    tags: [
      "phone number parser",
      "parse phone number online",
      "phone number format checker",
      "e164 formatter",
      "convert phone number to e164",
      "phone number normalizer",
      "international phone number format",
      "national phone number format",
      "country code lookup",
      "dial code lookup",
      "phone number country detector",
      "format phone number online",
      "validate phone number format",
      "phone number formatter tool",
      "bulk phone number parser",
      "normalize phone numbers",
      "e164 phone number format",
      "what is e164 format",
      "phone number with country code",
      "add country code to phone number",
      "international dialing code list",
      "country dialing codes table",
      "phone number country code finder",
      "parse phone numbers in bulk",
      "phone number validation tool",
      "format indian phone number",
      "format us phone number",
      "format uk phone number",
      "indian mobile number e164 format",
      "uk phone number international format",
      "us phone number international format",
      "phone number international format example",
      "national vs international phone number",
      "phone number trunk prefix",
      "nanp phone number format",
      "phone number parsing alternative",
      "libphonenumber online alternative",
      "phone number format converter",
      "clean phone number list",
      "standardize phone numbers",
      "phone number data cleaning",
      "extract country from phone number",
      "detect country code phone",
      "phone number structure analyzer",
      "mobile number format checker",
      "landline format checker",
      "phone number digits validator",
      "format phone numbers for sms",
      "e164 format for twilio",
      "phone number formatting tool free",
      "international phone format tool"
    ],
  };

export default seo;
