import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Photo GPS Extractor - Free Online Tool | IconVault",
    metaDescription: "Extract GPS coordinates from photo EXIF data online. Free, private, CSV export, runs in your browser.",
    about: [
      "**IconVault**'s **Photo GPS Extractor** scans your photos for the **GPS coordinates** your camera embedded in the EXIF data and lists each photo with its **latitude and longitude**, plus a one-click **Open in maps** link to see the exact spot. It reads everything **in your browser**, so your photos and their locations are never uploaded anywhere.",
      "It is **free**, works on **batches of photos** at once, and photos without GPS are clearly marked instead of silently skipped. Once coordinates are found you can **export a CSV** of filenames and coordinates for spreadsheets, travel logs or asset catalogs. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "How do I find where a photo was taken?", a: "Upload the photo and the tool reads its EXIF GPS tags. If the camera recorded a location, you get latitude and longitude plus a link to open it in a map." },
      { q: "Are my photos or locations uploaded?", a: "No. GPS extraction runs entirely in your browser. Nothing leaves your device." },
      { q: "What if a photo has no GPS data?", a: "The photo is listed as having no GPS data. Screenshots, web downloads and photos with location services off usually carry none." },
      { q: "Can I export the coordinates?", a: "Yes. Once at least one photo has coordinates, the Export CSV button downloads a spreadsheet with filename, latitude and longitude for every photo." },
      { q: "Can I process many photos at once?", a: "Yes. Drop a whole batch and every photo gets its own row in the results table." },
      { q: "Is it free?", a: "Yes, with 5 free scans. Pro members get unlimited runs plus HD exports and every template across all IconVault tools." },
    ],
    tags: [ "photo gps extractor", "extract gps from photo", "image gps coordinates", "photo location extractor", "exif gps extractor", "get coordinates from photo", "photo geotag viewer", "find photo location", "gps data from image", "photo latitude longitude", "image location finder", "exif location extractor", "photo coordinates online", "geotagged photo viewer", "extract location from jpg", "photo gps to csv", "image gps reader free", "where was this photo taken", "photo metadata gps", "gps tag reader" ,
      "gps extractor",
      "photo gps data",
      "find where photo was taken",
      "photo map viewer",
      "show photo location on map",
      "gps coordinates from image",
      "exif gps reader",
      "read geotag photo",
      "photo location reader",
      "check gps of photo",
      "image geolocation finder",
      "photo taken location map",
      "gps metadata extractor",
      "iphone photo location finder",
      "android photo gps info",
      "camera gps data reader",
      "view photo coordinates",
      "jpg gps coordinates",
      "png gps data",
      "raw photo gps",
      "drone photo gps extractor",
      "gps track from photos",
      "photos to map route",
      "map my photos online",
      "batch gps extractor photos",
      "export photo locations kml",
      "photo location list csv",
      "see all my photos on map",
      "geotag checker online",
      "photo geo location tool",
      "image gps metadata viewer",
      "locate photo online",
      "photo location privacy check",
      "does my photo have gps",
      "photo timestamp and location viewer",
      "altitude data from photo",
      "photo compass direction exif",
      "find lost camera by photo gps",
      "verify photo location",
      "reverse geocode photo location"],
  };

export default seo;
