import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Photo and Signature Joiner - Free Online Tool | IconVault",
    metaDescription: "Join your photo and signature into one JPG sized for Indian exam portals. Free, runs in your browser, files never leave your device.",
    about: [
      "**IconVault**'s **Photo and Signature Joiner** combines your **passport photo** and **signature** into a single JPG image, exactly what several government and exam form portals ask for. Choose the photo shape (3.5 x 4.5 passport, 200 x 230 for IBPS/SBI, or square), pick the signature strip style, add an optional label, and set a **Min/Max KB file size** so the result passes the portal's upload check. It is **free** to use, works **100% in your browser**, and your files never leave your device.",
      "The tool can **clean the signature background** (whitens paper so the ink stands out), trims the photo with center-crop, and compresses the joined image to your size limit. A **Pro** upgrade unlocks unlimited joins; free users get a daily trial quota.",
    ],
    faqs: [
      { q: "How do I join my photo and signature into one image?", a: "Upload your photo and your signature, choose the photo shape and signature strip style, set the file size limit, and click Join images. The tool stacks the photo on top with the signature strip below and downloads a single JPG." },
      { q: "Which portals need a combined photo and signature image?", a: "Some state and university admission portals ask for one combined image instead of two separate uploads. Always check your notification for the exact dimensions and file size before submitting." },
      { q: "Can I clean up a scanned signature?", a: "Yes. Turn on Clean signature background and the tool whitens the paper so your ink looks crisp on a pure white strip." },
      { q: "What file sizes can I set?", a: "Set any Min and Max KB you like (for example 20 to 50 KB). The tool compresses the joined image to fit inside your maximum and warns you honestly if the minimum cannot be reached." },
      { q: "Are my photo and signature uploaded anywhere?", a: "No. Everything runs in your browser on your own device. No upload, no server, no storage." },
      { q: "What format is the download?", a: "A single JPG file named photo-signature.jpg, ready to upload to your form portal." },
    ],
    tags: ["photo signature joiner", "join photo and signature", "combine photo signature one image", "exam form photo signature joiner", "ibps photo signature joiner", "sbi photo signature joiner", "photo signature joiner jpg", "photo and signature maker online", "government form photo signature", "signature strip joiner", "passport photo signature join", "free photo signature joiner", "online photo signature combiner", "ssc photo signature join", "upsc photo signature image", "neet photo signature joiner", "one image photo signature", "portal photo signature combine", "photo signature kb resizer", "exam portal image joiner",
      "signature joiner",
      "photo and signature joiner",
      "merge photo and signature",
      "attach signature below photo",
      "photo signature combo maker",
      "photo signature merger",
      "ssc cgl photo signature joiner",
      "railway exam photo signature",
      "upsc photo signature joiner",
      "gate photo signature joiner",
      "cat exam photo signature",
      "bank exam photo signature",
      "po exam photo signature joiner",
      "clerk exam photo signature",
      "police exam photo signature",
      "army form photo signature",
      "teacher exam photo signature",
      "admission form photo signature",
      "scholarship form photo signature",
      "job application photo signature",
      "signature under photo maker",
      "thumb impression photo joiner",
      "photo signature thumb joiner",
      "ibps clerk photo signature",
      "ibps rrb photo signature joiner",
      "sbi clerk photo signature",
      "rbi photo signature joiner",
      "lic photo signature joiner",
      "photo signature in one file",
      "vertical photo signature stack",
      "photo signature 20kb joiner",
      "photo signature 50kb joiner",
      "resize joined photo signature",
      "photo signature white background joiner",
      "exam portal upload photo signature",
      "photo signature combiner free",
      "make photo signature image",
      "photo with signature online tool",
      "attach signature to passport photo",
      "join photo signature no signup"],
  };

export default seo;
