import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Photo Collage Maker - Free Online Tool | IconVault",
    metaDescription: "Combine 2 to 9 photos into a beautiful collage online. Free, private, in-browser collage maker with live preview.",
    about: [
      "**IconVault**'s **Photo Collage** maker combines 2 to 9 photos into one polished image. Pick from **6 layouts** including 2x2, 3x3 and 1 big + 2, choose a **shape** like 1:1, 4:5 or 16:9, then tune **spacing**, **rounded corners** and the **background color** while a live preview updates. Everything runs **free** and **browser-private**, your photos never leave your device.",
      "The collage exports at a crisp **1200px wide** in JPG or PNG. **Pro** members get unlimited use with no trial limits.",
    ],
    faqs: [
      { q: "How do I make a photo collage online?", a: "Drop 2 to 9 photos into the collage maker, pick a layout and shape, adjust spacing and corners in the live preview, then download at 1200px wide." },
      { q: "How many photos can I add to a collage?", a: "Between 2 and 9. Each layout fits a fixed number of photos, and the tool tells you if you need to add more for the layout you picked." },
      { q: "Can I make a collage for Instagram?", a: "Yes. Choose the 1:1 shape for feed posts, 4:5 for portrait posts, or 9:16 for stories, then download the collage." },
      { q: "What size is the downloaded collage?", a: "The export is 1200px wide, with the height set by the shape you chose. The on-screen preview is smaller but the layout is identical." },
      { q: "Are my photos uploaded anywhere?", a: "No. The collage is built entirely in your browser, so your photos stay private on your own device." },
      { q: "Is the collage maker free?", a: "Yes, free users get a generous number of uses. Pro members get unlimited use of every tool." },
    ],
    tags: [ "photo collage maker", "make collage online free", "picture collage generator", "combine photos into one", "collage maker online", "photo grid maker", "make photo collage free", "instagram collage maker", "combine multiple photos", "picture mosaic maker", "photo layout maker", "2x2 photo collage", "3x3 photo grid", "free collage creator", "collage maker no watermark", "merge photos online", "photo montage maker", "collage photo editor", "make a collage of pictures", "online photo combiner" ,
      "collage maker",
      "photo collage app online",
      "make a photo collage",
      "free photo collage",
      "collage photo maker",
      "picture collage maker free",
      "online collage editor",
      "wedding photo collage maker",
      "family photo collage maker",
      "birthday collage maker",
      "photo collage templates free",
      "customizable photo collage",
      "create photo collage online",
      "polaroid collage maker",
      "photo collage with borders",
      "heart shape photo collage",
      "letter shape collage maker",
      "anniversary photo collage",
      "best friends photo collage",
      "dog photo collage maker",
      "baby photo collage maker",
      "travel photo collage",
      "mood board maker online",
      "vision board maker",
      "photo grid collage maker",
      "side by side collage maker",
      "diptych photo maker",
      "triptych photo maker",
      "photo strip maker",
      "storyboard photo layout",
      "facebook cover collage",
      "pinterest collage maker",
      "collage for whatsapp status",
      "printable photo collage",
      "photo collage without app",
      "collage maker no signup",
      "drag and drop collage maker",
      "square photo collage maker",
      "download collage free",
      "photo collage browser tool"],
  };

export default seo;
