import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Photo Filters - Free Online Tool | IconVault",
    metaDescription: "Apply Instagram-style filters to one photo or a whole batch. Presets plus fine-tune sliders, ZIP for batches. Free.",
    about: [
      "**IconVault**'s **Photo Filters** brings Instagram-style editing to your browser: nine **presets** including Original, Grayscale, Sepia, Vintage fade, Warm, Cool, High contrast, Noir and Film grain, each built from canvas filters and subtle color overlays. The grain preset adds real random **film noise** for an analog feel.",
      "Fine-tune with **Brightness, Contrast, Saturation and Grain sliders** on top of any preset, hit Reset to start over, and watch the **live preview** update. Upload **one photo or a whole batch**: the same settings apply to all, and batches download as a single **ZIP**. Everything runs **locally**, your photos never leave your device. **Free** with a daily trial, unlimited with Pro.",
    ],
    faqs: [
      { q: "Which filters are included?", a: "Nine presets: Original, Grayscale, Sepia, Vintage fade, Warm, Cool, High contrast, Noir and Film grain. Vintage fade adds a warm wash, Warm and Cool shift color temperature, and Film grain layers random noise over a sepia-contrast base." },
      { q: "Can I adjust a filter after choosing it?", a: "Yes. Brightness, Contrast, Saturation and Grain sliders stack on top of any preset, so you can soften or push an effect to taste. Reset restores the defaults." },
      { q: "How do batch filters work?", a: "Drop multiple photos and the exact same preset plus slider settings apply to every one. Single photos download as JPG; batches download as a ZIP of filtered JPGs." },
      { q: "What export quality do I get?", a: "Filtered photos export as JPG at 92% quality at full resolution, a good balance of sharpness and file size for web and print sharing." },
      { q: "Are my photos uploaded anywhere?", a: "No. Filtering happens on canvas in your browser with no network transfer. Nothing leaves your device." },
      { q: "Is the tool free?", a: "Yes, with a daily free trial limit. IconVault Pro unlocks unlimited exports across all tools." },
    ],
    tags: [ "photo filters online", "instagram filters online", "apply filter to photo", "vintage photo filter", "sepia filter online", "grayscale photo filter", "film grain effect", "noir photo filter", "warm cool photo filter", "batch photo filter", "filter multiple photos", "photo editor filters free", "retro photo effect", "high contrast filter", "photo filter app web", "edit photos online free", "analog photo filter", "photo effects generator", "filter zip download", "free photo filter tool" ,
      "photo filter",
      "online photo filter",
      "photo effect",
      "add filter to picture",
      "photo filter editor",
      "polaroid filter",
      "kodak filter online",
      "film look photo filter",
      "cinematic photo filter",
      "aesthetic photo filter",
      "vsco style filters online",
      "lightroom preset alternative free",
      "moody photo filter",
      "bright airy photo filter",
      "soft pink photo filter",
      "autumn photo filter",
      "summer photo filter",
      "winter photo filter",
      "beach photo filter",
      "golden hour filter",
      "portrait photo filter",
      "selfie filter online",
      "black and white photo filter",
      "duotone photo effect",
      "pop color filter",
      "hdr photo effect",
      "sharpen photo filter",
      "blur photo effect",
      "vignette effect online",
      "lens flare photo effect",
      "bokeh effect photo",
      "watercolor photo effect",
      "oil painting photo effect",
      "sketch photo effect",
      "cartoon photo effect",
      "lomo photo effect",
      "cross process filter",
      "fade filter photo",
      "photo luts online",
      "batch apply filter photos"],
  };

export default seo;
