import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Piano Keyboard - Free Online Virtual Piano | IconVault",
    metaDescription: "Play a virtual piano in your browser with mouse, touch or your computer keyboard. Octave shift, sustain toggle and note-sequence copy. Free.",
    about: [
      "**IconVault**'s **Piano Keyboard** is a playable virtual piano that needs no install or download. Play with **mouse or touch** on the on-screen keys, or use your **computer keyboard** as the instrument: the Z row plays the lower octave and the Q row plays the upper octave, chromatically from C to B. Sound is **synthesized live** with the **Web Audio API**, so every key press rings out instantly.",
      "You get an **octave shift** control (octaves 1 to 6), a **sustain toggle** that lengthens note release, and a **note sequence recorder** that logs every note you play as names like C4 and E4, which you can **copy to your clipboard**. It is **free** and runs **fully in your browser**. The honest note: notes use a simple triangle-wave synth voice, so it sounds like a clean electronic tone rather than a sampled grand piano."
    ],
    faqs: [
      { q: "How do I play notes with my computer keyboard?", a: "The Z row (Z S X D C V G B H N J M) plays the lower octave chromatically and the Q row (Q 2 W 3 E R 5 T 6 Y 7 U) plays the upper octave. Each key is labeled on the piano so you can see the mapping." },
      { q: "How do I change octaves?", a: "Use the minus and plus buttons around the Octave label to shift between octave 1 and octave 6. The on-screen keys and the keyboard mapping both follow the selected octave." },
      { q: "What does the sustain toggle do?", a: "Sustain switches the note release from a short 0.12 second fade to a long 1.6 second fade, letting notes ring out like a piano's sustain pedal. Press keys again to stack ringing notes into chords." },
      { q: "Can I see what I played?", a: "Yes. Every note is appended to the note sequence panel as note names with octaves (for example C4 E4 G4). You can copy the whole sequence to your clipboard or clear it to start over." },
      { q: "Do I need to install anything or download sound files?", a: "No. All sound is synthesized live in your browser with the Web Audio API. Nothing downloads and nothing is uploaded." },
      { q: "Does it work on mobile?", a: "Yes. The piano supports touch input, and the key area scrolls horizontally on small screens so every key stays reachable." }
    ],
    tags: [
      "virtual piano",
      "online piano",
      "piano keyboard online",
      "play piano online free",
      "virtual piano keyboard",
      "web piano",
      "piano simulator online",
      "online piano keyboard free",
      "playable piano in browser",
      "piano with computer keyboard",
      "qwerty piano",
      "keyboard piano online",
      "learn piano notes online",
      "piano note player",
      "web audio piano",
      "online piano with sound",
      "free virtual piano",
      "piano practice online",
      "piano keys online",
      "interactive piano",
      "digital piano online free",
      "browser piano",
      "piano app online",
      "play piano with keyboard keys",
      "piano octave changer",
      "piano sustain pedal online",
      "piano note names",
      "learn piano keys",
      "piano for beginners online",
      "two octave piano online",
      "chromatic piano keyboard",
      "piano chord player",
      "play melodies online",
      "virtual instrument piano",
      "online music keyboard",
      "piano sound simulator",
      "midi note player",
      "piano frequency chart",
      "middle c piano online",
      "piano key labels",
      "computer keyboard as piano",
      "type to play piano",
      "online piano no download",
      "piano toy online",
      "kids piano online",
      "music theory piano tool",
      "piano ear training tool",
      "piano scale player",
      "online piano with sustain",
      "free online piano keyboard",
      "play piano notes online",
      "virtual piano with sustain",
      "browser based piano",
      "piano note sequence recorder"
    ],
  };

export default seo;
