import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Pinyin Converter - Free Online Chinese to Pinyin Tool | IconVault",
    metaDescription: "Convert Chinese text to Pinyin with tone marks, tone numbers or no tones. Character-by-character output, free and fully in your browser.",
    about: [
      "**IconVault**'s **Pinyin Converter** turns Chinese text into **Pinyin romanization** so you can read pronunciation at a glance. Paste any Chinese text and get **character-by-character output** with each character shown alongside its Pinyin in brackets, for example 你(nǐ)好(hǎo). Choose from three **tone styles**: **tone marks** (hàn yǔ), **tone numbers** (han4 yu3), or **no tones** (han yu).",
      "It is **free** and runs **fully in your browser**; the Pinyin dictionary loads on demand the first time you convert (a few hundred KB) and is then cached. The honest caveat: Pinyin reflects the **most common reading** of each character, and characters with **multiple readings** use the default one, so learners should double-check tones for polyphonic characters in study contexts."
    ],
    faqs: [
      { q: "What is Pinyin?", a: "Pinyin, or Hanyu Pinyin, is the official romanization system for Mandarin Chinese. It writes Chinese pronunciation with the Latin alphabet plus tone marks, so learners can read characters they have not memorized yet." },
      { q: "What are the three tone styles?", a: "Tone marks use diacritics like nǐ, tone numbers append the tone digit like ni3, and no tones strips all tone information like ni. Marks are best for learning, numbers are handy for typing and databases." },
      { q: "How is the output formatted?", a: "Each Chinese character is shown with its Pinyin in brackets right after it, for example 你(nǐ)好(hǎo), while punctuation and non-Chinese text pass through unchanged." },
      { q: "Does it handle characters with multiple readings?", a: "Each character gets its most common reading by default. Polyphonic characters may need a different reading in context, so verify tones when studying or publishing text." },
      { q: "Why does the first conversion take a moment?", a: "The Pinyin dictionary (a few hundred KB) is loaded on demand the first time you convert, then cached for instant conversions afterwards." },
      { q: "Can I convert traditional Chinese too?", a: "Yes. The converter recognizes both simplified and traditional characters, since most share the same readings." }
    ],
    tags: [
      "pinyin converter",
      "chinese to pinyin",
      "convert chinese to pinyin online",
      "pinyin translator",
      "hanzi to pinyin",
      "chinese characters to pinyin",
      "pinyin with tone marks",
      "pinyin tone numbers",
      "pinyin without tones",
      "chinese pronunciation tool",
      "learn pinyin online",
      "pinyin converter free",
      "mandarin pinyin converter",
      "convert hanzi to pinyin",
      "chinese to pinyin with tones",
      "pinyin generator",
      "pinyin reading tool",
      "chinese text pronunciation",
      "how to read chinese characters",
      "pinyin tone marks converter",
      "nihao in pinyin",
      "chinese name to pinyin",
      "pinyin input tool",
      "pinyin chart online",
      "pinyin pronunciation guide",
      "chinese to english pronunciation",
      "mandarin pronunciation helper",
      "pinyin converter with tone marks",
      "tone mark pinyin online",
      "pinyin number to mark",
      "chinese character reader",
      "read chinese text pinyin",
      "pinyin study tool",
      "hsk pinyin practice",
      "chinese learning tool pinyin",
      "pinyin segmentation tool",
      "character by character pinyin",
      "pinyin for beginners",
      "mandarin chinese pinyin",
      "simplified chinese to pinyin",
      "traditional chinese to pinyin",
      "pinyin dictionary online",
      "chinese phonetic transcription",
      "pinyin romanization tool",
      "hanyu pinyin converter",
      "pinyin text converter free",
      "convert paragraph to pinyin",
      "bulk chinese to pinyin",
      "pinyin copy paste tool",
      "chinese pronunciation practice",
      "learn chinese pronunciation online",
      "pinyin tone mark keyboard"
    ],
  };

export default seo;
