import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Picture-in-Picture Playground - Free Online Tool | IconVault",
    metaDescription: "Learn PiP hands-on: a live canvas feeds a real requestPictureInPicture() window with custom controls and a live event log. Free, in your browser.",
    about: [
      "**IconVault**'s **Picture-in-Picture Playground** feeds an animated canvas (live clock, audio-style bars, or a bouncing ball) into a video element through captureStream(), then opens a genuine picture-in-picture window with requestPictureInPicture(). Your page keeps full control: the custom transport buttons on the page drive the floating window, and every enterpictureinpicture and leavepictureinpicture event lands in a live log with the window size. It is free and runs fully in your browser.",
      "PiP is the browser primitive behind **floating video** on every video site. This lab makes the whole contract visible: autoplay needs **muted playback**, entering PiP requires a **user gesture**, and the floating window is driven by the same video element your page controls, so play, pause, and exit all work from your own UI. Switch canvas sources to see a live stream versus generated content, and take the copyable control pattern back to your own video features."
    ],
    faqs: [
      { q: "What is Picture-in-Picture?", a: "A browser feature that pops a video out into a small floating window that stays on top while you use other apps. It is triggered with video.requestPictureInPicture() and closed with document.exitPictureInPicture()." },
      { q: "How does the canvas become a video?", a: "HTMLCanvasElement.captureStream() turns the live canvas into a MediaStream, which is assigned to a video element's srcObject. Anything drawn on the canvas appears in the video and therefore in the PiP window in real time." },
      { q: "Why does the video need to be muted?", a: "Autoplay policies require muted playback for a video to start without a user gesture. The lab defaults to muted and explains this, with a toggle so you can test the policy yourself." },
      { q: "Why did PiP fail with a gesture error?", a: "requestPictureInPicture() requires transient user activation, meaning it must be called from a click handler. Calling it from a timer or on page load will be rejected, which the lab shows honestly." },
      { q: "What is the difference from Document PiP?", a: "Video PiP (this lab) floats a video element. Document PiP (a separate lab) floats arbitrary HTML in a second window. Video PiP is supported in Chrome, Edge, and Safari; Document PiP is Chromium-only." },
      { q: "Can I control the PiP window from my page?", a: "Yes. The floating window mirrors the video element, so video.play(), pause(), and muted on your page drive it, and document.exitPictureInPicture() closes it programmatically." }
    ],
    tags: [
      "picture in picture",
      "picture in picture api",
      "pip javascript",
      "requestpictureinpicture",
      "picture in picture tutorial",
      "pip html video",
      "requestpictureinpicture example",
      "exitpictureinpicture",
      "enterpictureinpicture event",
      "leavepictureinpicture event",
      "document.pictureinpictureenabled",
      "pip custom controls",
      "canvas capturestream",
      "capturestream pip",
      "picture in picture demo",
      "pip playground",
      "how to do picture in picture web",
      "pip video javascript",
      "floating video window",
      "picture in picture chrome",
      "picture in picture safari",
      "picture in picture firefox",
      "pip browser support",
      "pip autoplay policy",
      "pictureinpicturewindow",
      "pip window size",
      "video pip web development",
      "picture in picture mdn",
      "pip typescript",
      "htmlvideoelement requestpictureinpicture",
      "picture in picture react",
      "pip event listener",
      "picture in picture not working",
      "requestpictureinpicture user gesture",
      "pip muted required",
      "canvas stream to video",
      "live canvas video stream",
      "picture in picture code sample",
      "learn picture in picture api",
      "pip controls custom",
      "picture in picture overlay",
      "web pip api",
      "document picture in picture vs video pip",
      "pip javascript tutorial",
      "picture in picture web app",
      "interactive pip demo",
      "pip lab",
      "video floating window js",
      "pip api example code",
      "browser pip feature"
    ],
  };

export default seo;
