import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Pixel Art Maker - Free Online Pixel Art Drawing Tool | IconVault",
    metaDescription: "Draw pixel art on an 8x8 to 64x64 grid with brush, eraser and fill tools. Export scaled PNG or copy a data URL. Free, fully in your browser.",
    about: [
      "**IconVault**'s **Pixel Art Maker** is a free in-browser studio for drawing **pixel art** on grids from **8x8 to 64x64**. Pick a color from the 16-color **palette** or any **custom color**, then paint with the **brush**, clean up with the **eraser**, or fill whole areas with the **flood-fill** tool. Full **undo and redo** history means every stroke is reversible.",
      "When your art is done, **export a scaled-up PNG** that keeps every pixel crisp with no smoothing, or **copy a PNG data URL** straight to your clipboard for embedding in code and game assets. Everything runs **fully in your browser**, free with no signup. The honest note: changing the grid size starts a fresh blank canvas, so export your work before switching sizes."
    ],
    faqs: [
      { q: "What grid sizes are available?", a: "8x8, 16x16, 24x24, 32x32, 48x48 and 64x64. Smaller grids suit icons and sprites, larger ones suit detailed scenes. Changing size clears the canvas, so export first." },
      { q: "What drawing tools are included?", a: "A brush for painting pixels, an eraser for clearing them, and a flood-fill tool for filling connected areas of the same color. Undo and redo support up to 30 steps each." },
      { q: "How do I export my pixel art?", a: "Click PNG to download a scaled-up image (16x per pixel, so a 16x16 grid becomes 256x256) with crisp edges and no smoothing. Or copy a PNG data URL to embed the art directly in HTML or game code." },
      { q: "Can I pick custom colors?", a: "Yes. A 16-color starter palette is built in, and a custom color picker lets you use any color you like, with the active color previewed next to it." },
      { q: "Is the exported PNG blurry?", a: "No. Exporting disables image smoothing, so each source pixel becomes a sharp 16x16 block. The art stays perfectly crisp at any display size." },
      { q: "Is my art uploaded anywhere?", a: "No. Drawing and exporting happen entirely in your browser. Nothing is sent to a server or stored online." }
    ],
    tags: [
      "pixel art maker",
      "pixel art editor online",
      "draw pixel art online",
      "pixel art creator free",
      "online pixel art tool",
      "pixel drawing app",
      "16x16 pixel art maker",
      "8x8 pixel art grid",
      "32x32 pixel art editor",
      "pixel art canvas online",
      "make pixel art free",
      "pixel art generator online",
      "sprite maker online",
      "pixel sprite editor",
      "retro pixel art tool",
      "pixel art paint online",
      "pixel art fill tool",
      "pixel art undo redo",
      "export pixel art png",
      "pixel art to png",
      "pixel art data url",
      "pixel art for games",
      "game sprite maker",
      "indie game pixel art",
      "pixel art character maker",
      "draw sprites online",
      "pixel art tutorial tool",
      "easy pixel art maker",
      "pixel art for beginners",
      "minecraft pixel art maker",
      "pixel art grid paper online",
      "pixel art color palette",
      "custom pixel art",
      "pixel art logo maker",
      "favicon pixel art maker",
      "pixel art icon maker",
      "64x64 pixel art",
      "pixel art brush tool",
      "pixel art eraser",
      "flood fill pixel art",
      "pixel art download png",
      "free sprite editor online",
      "2d game art maker",
      "pixel art portrait maker",
      "pixel art animal maker",
      "cute pixel art maker",
      "pixel art practice tool",
      "draw pixel art with mouse",
      "online drawing pixel grid",
      "pixel art maker no signup",
      "retro game art tool",
      "pixel art studio online",
      "pixel art maker free online",
      "sprite sheet art tool",
      "8 bit art maker"
    ],
  };

export default seo;
