import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Package.json Linter - Free Online package.json Checker | IconVault",
    metaDescription: "Paste your package.json and get 25+ quality checks with an A-F grade: name, license, scripts, deps. Free, parsed locally in your browser.",
    about: [
      "**IconVault**'s **Package.json Linter** runs **25+ quality checks** on your package.json and rolls them into an **A-F grade**. It validates the **name** against npm rules, checks the **license** is a valid **SPDX identifier**, inspects **scripts**, **keywords**, **engines**, **repository**, **files**, **exports** and **dependency** hygiene, and flags the mistakes that break installs or publishes.",
      "Your package.json is **parsed and checked locally in your browser**: it is never uploaded, never sent anywhere and never stored. It is **free** with no signup, and a **sample package.json** is included so you can try it instantly. The honest caveat: this is a **static checklist**, not a build test. A passing grade means the manifest looks right, not that the package actually builds or runs."
    ],
    faqs: [
      { q: "What does the linter check?", a: "Over 25 checks across name validity, version format, license SPDX validity, description, keywords, author, repository, homepage, main/exports entry points, bin, files, scripts, engines and dependency ranges. Each check reports pass, warn or fail with an explanation." },
      { q: "Is my package.json uploaded anywhere?", a: "No. Parsing and all checks run locally in your browser with JavaScript. Your file never leaves your device." },
      { q: "What is an SPDX license identifier?", a: "A standard short code for open source licenses, like MIT, ISC or Apache-2.0. npm warns when the license field is not a valid SPDX identifier, and this tool checks yours against the known list." },
      { q: "How is the A-F grade calculated?", a: "Fails weigh heaviest, warnings lighter, passes contribute positively. An A means publish-ready manifest hygiene; lower grades point at specific checks to fix first." },
      { q: "Can it fix my package.json automatically?", a: "No. It reports issues with explanations so you learn the fix, but it does not rewrite your file. Copy the flagged fields back into your editor after correcting them." },
      { q: "Is it really free?", a: "Yes. Unlimited lint runs, no account, no signup." }
    ],
    tags: [
      "package.json linter",
      "package.json checker",
      "package.json validator",
      "lint package.json online",
      "package.json analyzer",
      "package.json quality checker",
      "package.json best practices",
      "package.json validator online",
      "package.json syntax checker",
      "package.json schema validator",
      "check package.json errors",
      "package.json audit",
      "package.json review tool",
      "package.json grade",
      "package.json score",
      "package.json health check",
      "package.json name validator",
      "package.json license checker",
      "package.json scripts checker",
      "package.json dependencies checker",
      "package.json engines field",
      "package.json keywords checker",
      "package.json description missing",
      "package.json repository field",
      "package.json files field",
      "package.json main vs exports",
      "package.json type module",
      "npm package.json guide",
      "package.json fields explained",
      "package.json required fields",
      "package.json optional fields",
      "fix package.json online",
      "package.json formatter",
      "package.json prettier",
      "validate package.json free",
      "package.json linter free",
      "package.json check before publish",
      "npm publish checklist",
      "package.json publish readiness",
      "package.json mistakes",
      "common package.json errors",
      "package.json warnings",
      "package.json deprecation",
      "package.json bin field",
      "package.json peer dependencies check",
      "package.json version format",
      "semver checker package.json",
      "package.json spdx license",
      "package.json author field",
      "package.json homepage field"
    ],
  };

export default seo;
