import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Placeholder Image - Free Online Image Generator Tool | IconVault",
    metaDescription: "Create custom placeholder images with any size, colors and text. Live preview, PNG or JPG download. Free, runs entirely in your browser.",
    about: [
      "**IconVault**'s **Placeholder Image** generator creates **custom placeholder images** for mockups, wireframes and layout drafts. Set any **width and height** up to 2000 pixels, pick **background and text colors**, add your own **label text** and tune the **font size** with a slider. The canvas shows a **live preview** of exactly what will download.",
      "It is **free** and runs **fully in your browser**, so nothing you type leaves your device. The honest limit: placeholders are simple **solid-color images with centered text**, there are no gradients, patterns or multi-line text layouts. They are meant to hold a space in your design until real assets arrive, not to replace them."
    ],
    faqs: [
      { q: "How do I make a placeholder image?", a: "Enter a width and height, pick background and text colors, optionally type custom text and adjust the font size. The live preview shows the result, then download it as PNG or JPG." },
      { q: "What download formats are supported?", a: "PNG and JPG. PNG is the default and best for mockups with flat colors; JPG downloads at 92% quality if you need a smaller file." },
      { q: "What is the maximum placeholder size?", a: "2000 by 2000 pixels in each dimension. That is plenty for hero mockups and high-resolution wireframes." },
      { q: "What text shows if I leave the text box blank?", a: "The tool falls back to showing the dimensions, for example 800 x 600, which is the classic placeholder convention." },
      { q: "Can I pick exact brand colors?", a: "Yes. Use the color picker or type a hex code directly, for example #0F766E, into the background or text color field." },
      { q: "Is my data uploaded anywhere?", a: "No. The image is drawn on a canvas in your browser and the download is generated locally. Nothing is sent to a server." }
    ],
    tags: [
      "placeholder image generator",
      "placeholder image",
      "placeholder image maker",
      "create placeholder image",
      "custom placeholder image",
      "free placeholder image",
      "placeholder image online",
      "placeholder image with text",
      "placeholder image with dimensions",
      "placeholder image custom size",
      "placeholder image custom color",
      "placeholder image png",
      "placeholder image jpg",
      "placeholder image download",
      "generate placeholder image free",
      "placeholder image tool",
      "dummy image generator",
      "dummy image placeholder",
      "lorem ipsum image generator",
      "fake image generator",
      "mockup image placeholder",
      "wireframe placeholder image",
      "placeholder for website mockup",
      "placeholder image for web design",
      "placeholder image for layout",
      "placeholder image html",
      "placeholder image generator with text",
      "placeholder image generator online free",
      "placeholder image generator custom dimensions",
      "placeholder image generator custom text",
      "placeholder image 800x600",
      "placeholder image 1920x1080",
      "placeholder image 1200x630",
      "placeholder image 300x250",
      "placeholder image size generator",
      "any size placeholder image",
      "placeholder image brand color",
      "placeholder image hex color",
      "placeholder image font size",
      "placeholder image with label",
      "image placeholder maker",
      "design placeholder generator",
      "figma placeholder image",
      "ui mockup placeholder",
      "grey placeholder image",
      "solid color placeholder image",
      "temporary image generator",
      "stand in image generator",
      "hold space image generator",
      "placeholder image no signup",
      "placeholder image no watermark",
      "browser placeholder image generator",
      "free dummy image tool"
    ],
  };

export default seo;
