import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "PNG to JPG Converter - Free Online Tool | IconVault",
    metaDescription: "Convert PNG images to JPG free in your browser. Bulk support, quality slider, background fill, no uploads.",
    about: [
      "**IconVault**'s **PNG to JPG Converter** turns heavy **PNG images** into small, shareable **JPG files** right in your browser. JPG is the format every website, app and printer accepts, and files shrink dramatically for photos. The tool is completely **free**, handles **bulk uploads**, and your images **never leave your device**.",
      "Pick **JPEG quality** (90% keeps things crisp) and a **background color** for transparent areas, since JPG has no alpha channel. Batch conversions download as a **ZIP**. **IconVault Pro** removes trial limits for unlimited use.",
    ],
    faqs: [
      { q: "Is PNG to JPG conversion free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited conversions." },
      { q: "Do my images get uploaded?", a: "No. Conversion runs entirely in your browser, so your images stay on your device." },
      { q: "What happens to transparency?", a: "JPG cannot store transparency, so transparent areas become the background color you pick, white by default." },
      { q: "How much smaller is JPG than PNG?", a: "For photos, often 70 to 90 percent smaller at high quality. For flat graphics the savings are smaller." },
      { q: "What quality should I choose?", a: "90% is a solid default. Use 75 to 80% for web images and 95% plus for archiving." },
      { q: "Can I convert many PNGs at once?", a: "Yes. Drop in a batch and download everything as a ZIP file." },
    ],
    tags: ["png to jpg", "convert png to jpg", "png to jpeg", "png to jpg online", "png converter", "png to jpg free", "bulk png to jpg", "png to jpg quality", "png transparent to jpg", "png to jpg batch", "png to jpg no signup", "png to jpg background", "png image converter", "save png as jpg", "png to jpg private", "png to jpg download", "free png converter", "png to jpeg converter", "png to jpg zip", "compress png to jpg",
      "jpg converter",
      "png jpg converter",
      "png to jpeg online",
      "convert png files to jpg",
      "png to jpg small size",
      "png to jpg white background",
      "png to jpg black background",
      "change png to jpg",
      "turn png into jpg",
      "convert transparent png to jpg",
      "png to jpg high quality",
      "png to jpg low size",
      "multiple png to jpg",
      "all png to jpg at once",
      "png to jpg for email",
      "png to jpg for upload",
      "png to jpg for website",
      "reduce png size jpg",
      "png to jpg ios",
      "png to jpg android",
      "png to jpg windows",
      "png to jpg mac",
      "png to jpg chromebook",
      "screenshot png to jpg",
      "logo png to jpg",
      "convert png screenshot",
      "png to jpg 300kb",
      "png to jpg under 1mb",
      "png to jpg fast",
      "png to jpg browser",
      "png to jpg without losing quality",
      "png to jpg keep quality",
      "png to jpeg batch free",
      "png to jpg drag and drop",
      "png to jpg tool online",
      "free png to jpg converter online",
      "png to jpg no watermark",
      "png to jpg offline in browser",
      "png to jpg instantly",
      "best png to jpg converter"],
  };

export default seo;
