import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Pomodoro Timer - Free Online Focus Timer Tool | IconVault",
    metaDescription: "Free Pomodoro timer with custom focus and break durations, browser notifications on phase changes and session history. Runs fully in your browser.",
    about: [
      "**IconVault**'s **Pomodoro Timer** runs the classic **focus technique** in your browser: **25-minute focus sessions** broken up by **short breaks** and **long breaks**, with all durations **editable** to fit your rhythm. When a phase ends you get an **audible beep** and an optional **browser notification**, the timer advances automatically, and every finished session is saved to a **session history** you can review or export.",
      "It is **free** and runs **fully in your browser**, with history stored on your device so no account is needed. The honest limit: the timer only keeps time while the page stays open, so closing the tab pauses your session. It tracks time in a box for you; it cannot make the work happen, but it gives focus a clear start and end."
    ],
    faqs: [
      { q: "What is the Pomodoro technique?", a: "It is a focus method where you work in timed intervals, classically 25 minutes of focused work followed by a 5 minute break, with a longer break after four sessions. The timer automates the cycle so you do not watch the clock." },
      { q: "Can I change the focus and break lengths?", a: "Yes. The focus, short break and long break durations are all editable in minutes, up to 180 each. Changing them while paused updates the current phase immediately." },
      { q: "How do I get alerts when a phase ends?", a: "Click Enable phase-change alerts to grant notification permission. You will then get a browser notification and a short beep when a focus session or break finishes." },
      { q: "Is my session history saved?", a: "Yes, on this device only. Finished sessions are stored in your browser's local storage and shown in the history list, with the option to export to CSV or clear them." },
      { q: "Does the timer keep running if I close the tab?", a: "No. It is an in-page timer, so closing or navigating away stops the countdown. Keep the tab open during a session for accurate timing." },
      { q: "Is my data sent anywhere?", a: "No. Everything runs in your browser and the history never leaves your device." }
    ],
    tags: [
      "pomodoro timer",
      "pomodoro timer online",
      "free pomodoro timer",
      "online pomodoro timer",
      "pomodoro timer free online",
      "pomodoro technique timer",
      "focus timer",
      "focus timer online",
      "free focus timer",
      "study timer",
      "online study timer",
      "25 minute timer",
      "25 5 pomodoro timer",
      "pomodoro 25 minutes",
      "custom pomodoro timer",
      "pomodoro timer with breaks",
      "pomodoro timer short break long break",
      "pomodoro timer with notification",
      "pomodoro timer with alarm",
      "pomodoro timer with sound",
      "pomodoro session tracker",
      "pomodoro history",
      "pomodoro timer export",
      "productivity timer",
      "work timer",
      "online work timer",
      "deep work timer",
      "timeboxing timer",
      "interval work timer",
      "focus session timer",
      "study with me timer",
      "exam study timer",
      "student focus timer",
      "adhd focus timer",
      "adhd pomodoro timer",
      "time management timer",
      "task timer online",
      "break reminder timer",
      "work break timer",
      "browser pomodoro timer",
      "pomodoro timer no signup",
      "pomodoro timer no app",
      "pomodoro timer web",
      "pomodoro timer csv export",
      "pomodoro timer for developers",
      "coding focus timer",
      "writing focus timer",
      "pomodoro technique online tool",
      "best free pomodoro timer",
      "simple pomodoro timer",
      "minimal pomodoro timer",
      "pomodoro timer dark mode",
      "tomato timer"
    ],
  };

export default seo;
