import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Port Reference - Free Online Network Reference Tool | IconVault",
    metaDescription: "Search 130 common network ports by number, service or protocol. Port, protocol, service and security note with click to copy. Free and client-side.",
    about: [
      "**IconVault**'s **Port Reference** is a searchable table of **130 well-known and registered ports**, covering the classics like **22 (SSH)**, **80 (HTTP)** and **443 (HTTPS)** through databases, messaging systems, game servers and DevOps infrastructure. Every row lists the **port number**, **protocol**, **service name** and a practical **security note**, and clicking any row copies the port number to your clipboard.",
      "It is **free** and runs **fully in your browser**, with instant filtering as you type. The honest limit: this is a **reference**, not a scanner. It cannot tell you which ports are open on your machine or anyone else's, and a handful of rows cover the most common services, not the full IANA registry."
    ],
    faqs: [
      { q: "What is a network port?", a: "A port is a numbered endpoint that network services listen on, from 0 to 65535. For example web traffic uses port 443 for HTTPS, and SSH uses port 22. Knowing which port a service uses is the first step in configuring firewalls." },
      { q: "How do I search the port list?", a: "Type into the search box: a port number like 443, a service like mysql, or a protocol like UDP. The table filters instantly across the port number, service, protocol and security notes." },
      { q: "How do I copy a port number?", a: "Click any row in the table and the port number is copied to your clipboard with a confirmation toast." },
      { q: "What do the security notes cover?", a: "Each row carries a short hardening tip, for example never expose port 3389 (RDP) to the internet, bind Redis on 6379 to localhost, or enforce 2FA on hosting panels. Treat them as starting reminders, not full security guidance." },
      { q: "Can this tool scan my open ports?", a: "No. It is a static reference of common ports. Use a dedicated port scanner or firewall tool to check which ports are actually open on a device." },
      { q: "Does it need an internet connection or account?", a: "The full 130 port table is bundled with the page, so once it loads it works without any further requests and without an account." }
    ],
    tags: [
      "port reference",
      "tcp port list",
      "common ports list",
      "well known ports",
      "well known port numbers",
      "registered ports list",
      "port number lookup",
      "port lookup",
      "what port does ssh use",
      "what port does https use",
      "port 443 service",
      "port 80 service",
      "port 22 service",
      "port 3306",
      "port 5432",
      "port 3389",
      "port 8080",
      "port 25",
      "port 53",
      "port 587",
      "port 27017",
      "port 6379",
      "port 25565",
      "port 9092",
      "mysql default port",
      "postgres default port",
      "mongodb default port",
      "redis default port",
      "elasticsearch default port",
      "kafka default port",
      "minecraft server port",
      "rdp port number",
      "ssh port number",
      "https port number",
      "http port number",
      "dns port number",
      "smtp port numbers",
      "ftp port numbers",
      "network ports cheat sheet",
      "ports cheat sheet",
      "common network ports cheat sheet",
      "tcp udp ports list",
      "port protocol reference",
      "port security guide",
      "which ports to block firewall",
      "dangerous open ports",
      "common ports and services",
      "port number chart",
      "networking ports table",
      "devops port reference",
      "sysadmin port list",
      "firewall port reference",
      "free port reference tool",
      "port list with descriptions",
      "port 1024 to 49151 registered ports"
    ],
  };

export default seo;
