import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Prettier Config Generator - Free Online Code Tool | IconVault",
    metaDescription: "Build a .prettierrc visually with toggles and sliders, watch a live sample reformat itself, then copy or download the JSON. Free, in your browser.",
    about: [
      "**IconVault**'s **Prettier Config Generator** builds a **.prettierrc** file without touching JSON by hand. **Toggle** options like **semi**, **singleQuote**, **useTabs** and **bracketSpacing**, drag **sliders** for **printWidth** and **tabWidth**, and pick **trailingComma**, **arrowParens** and **endOfLine** from dropdowns. A **live JSON preview** updates as you click, and a **sample code snippet** re-formats itself so you can see exactly what each setting does before you commit.",
      "It is **free** and runs **fully in your browser**, so your preferences never leave the page. The honest limit: the sample snippet is a **demonstration**, not a real Prettier run, so edge cases may format slightly differently in the actual formatter. When you are happy, **copy** the JSON or **download** it as `.prettierrc` and drop it into your project root."
    ],
    faqs: [
      { q: "What is a .prettierrc file?", a: "It is the JSON configuration file for Prettier, the opinionated code formatter. Placed in your project root, it controls how Prettier formats your code: quote style, semicolons, line width, indentation and more." },
      { q: "Which Prettier options can I configure?", a: "printWidth, tabWidth, useTabs, semi, singleQuote, trailingComma (all, es5, none), bracketSpacing, arrowParens (always, avoid) and endOfLine (lf, crlf, auto)." },
      { q: "How does the live sample work?", a: "A built-in snippet applies your current settings to real-looking code, including a long function call that wraps or stays on one line depending on your printWidth. It demonstrates the effect of each option as you change it." },
      { q: "How do I get the config into my project?", a: "Click Copy to put the JSON on your clipboard, or Download to save it as a file named .prettierrc, then place it in your project root next to package.json." },
      { q: "Is this a real Prettier formatting run?", a: "No. The live sample is a simulation of your settings applied to one snippet, which makes the effect of each option visible instantly. The downloaded JSON itself is real and works with actual Prettier." },
      { q: "Is anything uploaded?", a: "No. Every control and the JSON output run entirely in your browser. Nothing leaves your device." }
    ],
    tags: [
      "prettier config generator",
      "prettierrc generator",
      "prettier config",
      "generate prettierrc",
      "prettierrc file",
      "prettierrc example",
      "prettier configuration",
      "prettier settings",
      "prettier options",
      "prettier printwidth",
      "prettier tabwidth",
      "prettier singlequote",
      "prettier semi",
      "prettier trailing comma",
      "prettier bracket spacing",
      "prettier arrow parens",
      "prettier endofline",
      "prettier use tabs",
      "prettierrc json",
      "create prettierrc",
      "prettierrc template",
      "prettierrc best practices",
      "prettierrc recommended settings",
      "prettier config online",
      "prettier config visual",
      "prettier config builder",
      "prettier playground config",
      "format code prettier config",
      "javascript formatter config",
      "typescript formatter config",
      "code formatter settings",
      "vscode prettier config",
      "prettier setup guide",
      "how to configure prettier",
      "prettierrc explained",
      "prettier options explained",
      "printwidth 80 vs 100",
      "prettier single quote vs double",
      "prettier semicolons yes or no",
      "prettier config for react",
      "prettier config for node",
      "prettier config for nextjs",
      "eslint prettier config",
      "prettier editorconfig",
      "prettierrc vs prettier config js",
      "download prettierrc",
      "copy prettier config",
      "free prettier tool",
      "online prettier config tool",
      "prettier visual editor",
      "prettier settings ui"
    ],
  };

export default seo;
