import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Privacy Policy Generator - Free Online Document Generator Tool | IconVault",
    metaDescription: "Generate a tailored privacy policy draft from your company details and data practices. Download as Markdown. Free, in your browser. Not legal advice.",
    about: [
      "**IconVault**'s **Privacy Policy Generator** turns your **company name**, **website URL** and **contact email** plus the **data categories** you collect, like **analytics**, **cookies**, **user accounts**, **payments** or **newsletter**, into a readable **privacy policy draft** with sections on **data collection**, **use of information**, **cookies**, **third-party services**, **user rights**, **security** and **policy changes**. A **live preview** updates as you type, and you can **download the result as Markdown**.",
      "It is **free** and runs **fully in your browser**, so your company details never leave your device. The honest and important limit: this is a **starting template, not legal advice**. Privacy law varies by jurisdiction and by what you actually do with data. Have the draft reviewed by a qualified professional before you publish it."
    ],
    faqs: [
      { q: "How do I generate a privacy policy?", a: "Enter your company name, website URL and contact email, tick the data categories you collect, then review the live preview and download the Markdown file. The policy text adapts to your selections." },
      { q: "What sections does the policy include?", a: "Information we collect, how we use information, cookies, third-party services, your rights, security, changes to the policy and contact us, with a last updated date at the top." },
      { q: "Can I customize which data types are covered?", a: "Yes. Checkboxes for analytics, cookies, user accounts, payments and newsletter control which data categories appear in the Information We Collect section and whether the cookies section describes active tracking." },
      { q: "Is this legal advice?", a: "No. It is a generic starting template. Privacy requirements differ across regions like the EU, UK, California and India, and a template cannot capture your actual data practices. Have it reviewed by a lawyer before publishing." },
      { q: "What format is the download?", a: "Markdown (.md), which you can paste into a static site, convert to HTML, or open in any document editor." },
      { q: "Is my company information uploaded?", a: "No. The policy is generated in your browser from what you type. Nothing is sent to a server or stored." }
    ],
    tags: [
      "privacy policy generator",
      "free privacy policy generator",
      "privacy policy generator online",
      "generate privacy policy",
      "create privacy policy",
      "privacy policy template",
      "free privacy policy template",
      "privacy policy template for website",
      "website privacy policy generator",
      "privacy policy maker",
      "privacy policy builder",
      "privacy policy sample",
      "simple privacy policy template",
      "startup privacy policy template",
      "small business privacy policy",
      "blog privacy policy template",
      "ecommerce privacy policy template",
      "app privacy policy generator",
      "mobile app privacy policy template",
      "saas privacy policy template",
      "gdpr privacy policy template",
      "gdpr privacy policy generator",
      "ccpa privacy policy template",
      "privacy policy for shopify",
      "privacy policy for wordpress",
      "privacy policy markdown",
      "download privacy policy",
      "privacy policy draft",
      "write a privacy policy",
      "how to write a privacy policy",
      "what to include in privacy policy",
      "privacy policy requirements",
      "privacy policy checklist",
      "do i need a privacy policy",
      "privacy policy for new website",
      "privacy policy disclaimer",
      "privacy policy not legal advice",
      "cookies privacy policy section",
      "data collection policy template",
      "user rights privacy policy",
      "third party services privacy policy",
      "privacy policy contact section",
      "privacy policy last updated",
      "free legal document generator",
      "website legal pages generator",
      "privacy policy no signup",
      "privacy policy no lawyer",
      "online privacy policy tool",
      "privacy policy generator free download",
      "custom privacy policy",
      "tailored privacy policy template"
    ],
  };

export default seo;
