import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Probability Lab - Free Online Statistics Lab Tool | IconVault",
    metaDescription: "Run Monte Carlo probability experiments: coin flips, dice rolls and the Monty Hall problem, with a live convergence chart. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Probability Lab** makes the **law of large numbers** visible. Pick an experiment, **coin flip**, **dice roll (six)** or the **Monty Hall problem** with both **switch** and **stay** strategies, set **100 to 100,000 trials** and run a **Monte Carlo simulation**. A **convergence chart** plots the **observed win rate** against the **theoretical probability** as trials grow, with the gap between them reported in percentage points.",
      "It is **free** and runs **fully in your browser**, and you can **copy the results** as plain text for homework or notes. The honest limit: the simulation uses **pseudo-random numbers** from your browser, which are fine for learning but not for cryptography or real gambling analysis. With few trials the observed rate can sit far from theory; that noise shrinking as trials grow is exactly the lesson."
    ],
    faqs: [
      { q: "What experiments are included?", a: "Coin flip (theoretical 50%), dice roll tracking sixes (16.67%), Monty Hall where you switch doors (66.67%) and Monty Hall where you stay (33.33%). Each shows its theoretical probability as a dashed green line on the chart." },
      { q: "Why does the observed rate differ from the theoretical one?", a: "Randomness. With few trials, luck dominates and the observed rate can be far off. As trials grow into the thousands, the observed rate converges toward the theoretical probability. That convergence is the law of large numbers." },
      { q: "What is the Monty Hall problem?", a: "You pick one of three doors, the host opens a different door revealing a goat, and you choose to switch or stay. Switching wins about two thirds of the time because your first pick was probably wrong. Run both strategies here and watch the difference." },
      { q: "How many trials can I run?", a: "From 100 up to 100,000 in steps of 100. Higher trial counts give smoother convergence curves and cost nothing but a moment of computation." },
      { q: "Can I copy the results?", a: "Yes. The copy button puts the experiment name, trial count, theoretical probability, observed win rate and the gap into plain text you can paste into notes or assignments." },
      { q: "Are the random numbers truly random?", a: "They come from your browser's Math.random, which is pseudo-random. That is plenty for exploring probability concepts, but not suitable for cryptography, lotteries or anything needing real unpredictability." }
    ],
    tags: [
      "probability lab",
      "probability simulator",
      "probability simulation online",
      "monte carlo simulator",
      "monte carlo simulation online",
      "law of large numbers simulator",
      "law of large numbers demo",
      "coin flip simulator",
      "coin flip probability",
      "coin toss simulator",
      "dice roll simulator",
      "dice probability simulator",
      "roll a dice probability",
      "monty hall simulator",
      "monty hall problem",
      "monty hall switch vs stay",
      "monty hall problem explained",
      "monty hall simulation",
      "probability experiments",
      "probability experiments online",
      "statistics simulator",
      "statistics lab online",
      "probability learning tool",
      "teach probability",
      "probability for students",
      "probability homework help",
      "convergence chart",
      "observed vs theoretical probability",
      "random trial simulator",
      "simulate coin flips",
      "simulate dice rolls",
      "how many coin flips to get 50 percent",
      "probability of rolling a six",
      "expected value simulator",
      "binomial probability simulator",
      "randomness demo",
      "probability visualizer",
      "probability chart maker",
      "statistics classroom tool",
      "math lab probability",
      "interactive probability",
      "free probability tool",
      "online statistics tool",
      "probability calculator simulation",
      "gambler's fallacy demo",
      "streak probability",
      "coin flip streak odds",
      "browser probability simulator",
      "no signup probability lab",
      "probability demo tool"
    ],
  };

export default seo;
