import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Projectile Lab - Free Online Physics Lab Tool | IconVault",
    metaDescription: "Interactive projectile motion simulator with launch angle, velocity, gravity presets and optional air drag. Trajectory chart and stats. Free, in-browser.",
    about: [
      "**IconVault**'s **Projectile Lab** simulates **projectile motion** with a live **trajectory chart**. Set the **launch velocity** and **launch angle** with sliders, choose **gravity** presets for **Earth, Moon, Mars or Jupiter**, and toggle **quadratic air resistance** with an adjustable **drag coefficient**. The chart marks the **launch point**, **apex** and **landing**, while stat cards report **range**, **maximum height** and **flight time** to one decimal place.",
      "It is **free** and runs **fully in your browser** using numeric integration, and you can **copy the stats** as text. The honest limit: it models a **1 kg ball, 10 cm in diameter** launched from ground level onto flat ground, with no wind, lift or spin. Real projectiles with different shapes, air conditions and elevations will land differently, so treat it as a learning model, not an engineering tool."
    ],
    faqs: [
      { q: "How do I simulate a projectile?", a: "Set the launch velocity (1 to 100 m/s) and launch angle (5 to 85 degrees) with the sliders. The trajectory chart and range, max height and flight time update instantly." },
      { q: "What gravity options are available?", a: "Earth at 9.81, Moon at 1.62, Mars at 3.71 and Jupiter at 24.79 meters per second squared. Try the same launch on the Moon to see how much farther it flies." },
      { q: "How does air resistance work in the simulation?", a: "Toggle it on to apply quadratic drag, F = 0.5 x rho x Cd x A x v squared, with an adjustable drag coefficient. A smooth sphere is 0.47 and a flat plate is about 1.2. Watch the trajectory flatten and the range shrink." },
      { q: "What launch angle gives maximum range?", a: "Without air resistance, 45 degrees. With drag enabled, the best angle drops below 45 because the projectile loses speed along the longer path. Try it and compare the range stat." },
      { q: "What are the model assumptions?", a: "A 1 kg ball of 10 cm diameter, launched from ground level onto flat ground, constant gravity, no wind, no lift and no spin. Integration runs at 5 ms time steps." },
      { q: "Can I copy the results?", a: "Yes. The copy button exports the launch settings, drag setting, range, max height and flight time as plain text for notes or lab reports." }
    ],
    tags: [
      "projectile motion simulator",
      "projectile motion calculator",
      "projectile lab",
      "projectile motion lab online",
      "trajectory simulator",
      "trajectory calculator",
      "ballistic trajectory simulator",
      "launch angle calculator",
      "projectile range calculator",
      "projectile motion formula",
      "range of projectile formula",
      "maximum height projectile formula",
      "time of flight projectile",
      "projectile motion physics",
      "projectile motion explained",
      "projectile motion simulation",
      "physics projectile lab",
      "physics simulator online",
      "kinematics simulator",
      "kinematics lab online",
      "gravity simulator",
      "moon gravity projectile",
      "mars gravity projectile",
      "air resistance simulator",
      "drag coefficient simulator",
      "quadratic drag simulation",
      "projectile motion with air resistance",
      "optimal launch angle",
      "best angle for maximum range",
      "45 degree launch range",
      "projectile motion graph",
      "trajectory graph maker",
      "physics homework help",
      "projectile motion problems",
      "projectile motion examples",
      "learn projectile motion",
      "teach projectile motion",
      "interactive physics lab",
      "virtual physics lab",
      "free physics simulator",
      "online physics lab",
      "projectile motion applet",
      "cannonball trajectory calculator",
      "sports projectile physics",
      "javelin throw physics",
      "basketball shot physics",
      "golf ball trajectory",
      "browser physics simulator",
      "no signup physics lab",
      "projectile motion worksheet",
      "physics classroom tool"
    ],
  };

export default seo;
