import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Punnett Square - Free Online Genetics Lab Tool | IconVault",
    metaDescription: "Build interactive Punnett squares: pick parent genotypes, see genotype and phenotype ratios with step-by-step explanations. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Punnett Square** lab builds a **2x2 Punnett square** from the **genotypes** you pick for each parent. Choose **AA**, **Aa** or **aa** for **Parent 1** and **Parent 2**, and the square fills in live with **gametes** along the edges, color-coded offspring boxes, **genotypic ratios** (AA, Aa, aa as fractions and percents) and **phenotypic ratios** (dominant vs recessive). A **step-by-step walkthrough** explains how the gametes, counts and ratios were derived.",
      "It is **free** and runs **fully in your browser**, and you can **copy the full result** including the steps. The honest limit: it models **one gene with two alleles under complete dominance**. Real traits often involve **incomplete dominance**, **codominance**, **multiple genes** or **environmental effects**, which this lab does not cover."
    ],
    faqs: [
      { q: "How do I use the Punnett square tool?", a: "Pick a genotype for Parent 1 and Parent 2 from AA, Aa or aa. The square, gametes, genotype counts and phenotype ratios update instantly, with a numbered explanation of each step." },
      { q: "What does A and a stand for?", a: "A is the dominant allele and a is the recessive allele. Any genotype containing A shows the dominant trait; only aa shows the recessive trait under the complete dominance model." },
      { q: "What is the difference between genotype and phenotype ratio?", a: "The genotypic ratio counts the allele combinations, for example 1:2:1 for AA:Aa:aa from two Aa parents. The phenotypic ratio counts the observable traits, which is 3:1 dominant to recessive in that same cross." },
      { q: "What are the possible parent crosses?", a: "AA x AA, AA x Aa, AA x aa, Aa x Aa, Aa x aa and aa x aa. Try Aa x Aa for the classic 1:2:1 genotypic and 3:1 phenotypic ratios." },
      { q: "Does this cover incomplete dominance or codominance?", a: "No. The lab assumes complete dominance of one gene with two alleles. Traits with blending, both traits visible, or multiple genes need a more advanced model." },
      { q: "Can I copy the results for homework?", a: "Yes. The copy button exports the cross, genotype fractions, phenotype fractions and the full step-by-step explanation as plain text." }
    ],
    tags: [
      "punnett square",
      "punnett square calculator",
      "punnett square maker",
      "punnett square generator",
      "punnett square online",
      "free punnett square",
      "interactive punnett square",
      "punnett square solver",
      "punnett square practice",
      "punnett square worksheet",
      "how to do a punnett square",
      "punnett square steps",
      "punnett square explained",
      "punnett square examples",
      "genotype ratio calculator",
      "phenotype ratio calculator",
      "genotypic ratio",
      "phenotypic ratio",
      "genotype vs phenotype",
      "dominant vs recessive alleles",
      "complete dominance",
      "monohybrid cross",
      "monohybrid cross calculator",
      "aa x aa punnett square",
      "heterozygous cross",
      "homozygous dominant",
      "homozygous recessive",
      "mendelian genetics calculator",
      "genetics calculator",
      "genetics lab online",
      "biology punnett square",
      "biology homework help",
      "genetics homework help",
      "heredity calculator",
      "allele combination calculator",
      "gamete calculator",
      "probability offspring traits",
      "dominant trait probability",
      "recessive trait probability",
      "1:2:1 genotypic ratio",
      "3:1 phenotypic ratio",
      "learn genetics",
      "teach genetics",
      "biology classroom tool",
      "genetics study tool",
      "ap biology punnett square",
      "high school genetics",
      "browser genetics lab",
      "no signup punnett square",
      "free genetics tool"
    ],
  };

export default seo;
