import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "QR Code Scanner - Free Online Tool | IconVault",
    metaDescription: "Scan QR codes from an image or your camera right in the browser. Copy text or open links instantly. Free, private.",
    about: [
      "**IconVault**'s **QR Code Scanner** reads QR codes without installing an app: **drop, click or paste** an image or screenshot, or hit **Scan with camera** to point your webcam at a code. It tries the native **BarcodeDetector** first and falls back to the jsQR library, so detection is fast and reliable on modern browsers.",
      "Once decoded, you get the raw text with a **Copy** button, and if it looks like a URL you get an **Open link** button too. Everything is processed **on your device**: the image never leaves your browser. Tip: crop closer to the code if a scan fails. **Free** with a daily trial, unlimited with Pro.",
    ],
    faqs: [
      { q: "How do I scan a QR code with this tool?", a: "Three ways: drop or click to upload an image, paste a screenshot from your clipboard, or press Scan with camera to use your device camera. Detection runs automatically and the decoded text appears below." },
      { q: "Why does it ask for camera permission?", a: "Camera scanning uses your browser's getUserMedia API, which requires permission. If you deny it, you can still upload or paste an image instead." },
      { q: "What happens when the code contains a link?", a: "The scanner detects URL-shaped text and shows an Open link button that opens it in a new tab. Always check the decoded text before opening unfamiliar links." },
      { q: "The scan failed. What can I try?", a: "Crop closer to the code so it fills most of the image, make sure it is in focus and well lit, and avoid extreme angles. High contrast codes scan most reliably." },
      { q: "Is the scanned content sent to a server?", a: "No. Decoding happens entirely in your browser via the native BarcodeDetector or the jsQR library. Your images and codes never leave your device." },
      { q: "Is the QR scanner free?", a: "Yes, with a daily free trial limit. IconVault Pro removes the limit for unlimited scans." },
    ],
    tags: [ "qr code scanner online", "scan qr code from image", "qr reader web", "decode qr code", "qr code scanner camera", "online qr scanner", "read qr from screenshot", "qr code decoder", "scan qr online free", "barcode detector", "jsqr online", "qr text extractor", "qr link scanner", "paste qr image scan", "webcam qr scanner", "qr code reader no app", "scan qr code browser", "qr code to text", "free qr scanner", "qr scanner privacy" ,
      "qr scanner",
      "qr reader",
      "scan qr code",
      "qr code reader online",
      "scan qr code online",
      "qr scanner online free",
      "scan qr from photo",
      "qr code scan from gallery",
      "read qr code online",
      "qr decoder online",
      "upload qr code to scan",
      "qr image reader",
      "scan qr code on pc",
      "qr code scanner for laptop",
      "qr scanner for computer",
      "qr reader for desktop",
      "scan qr code without phone",
      "qr code checker online",
      "verify qr code",
      "qr code content viewer",
      "extract url from qr",
      "qr to link converter",
      "scan wifi qr code",
      "qr scanner for pc windows",
      "qr reader chrome",
      "online qr code test",
      "qr code scanner no download",
      "free qr code scanner",
      "fast qr scanner online",
      "qr code scanner tool",
      "scan damaged qr code",
      "qr code image decoder",
      "read qr code from pdf",
      "scan qr code screenshot",
      "qr scanner drag and drop",
      "qr code analyzer online",
      "check qr code safety",
      "is this qr code safe",
      "qr phishing checker",
      "qr code scanner secure"],
  };

export default seo;
