import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Query String Builder - Free Online Developer Tool | IconVault",
    metaDescription: "Build URL query strings from key value rows with automatic encoding, or paste a query string to parse it back. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Query String Builder** constructs **URL query strings** from simple **key and value rows**, with **automatic percent-encoding** of keys and values so spaces and special characters are handled correctly. **Duplicate keys** are allowed, a **base URL** field shows a **full URL preview**, and the reverse direction works too: **paste any query string** or full URL and parse it back into editable rows.",
      "It is **free** and runs **fully in your browser**, so URLs you are building never leave your device. The honest limit: encoding follows **encodeURIComponent** rules, which is what most web frameworks expect, but it does not handle **array bracket conventions** like `tag[]=a` specially; you can type those keys literally and they will be encoded as-is."
    ],
    faqs: [
      { q: "How do I build a query string?", a: "Add rows and type a key and value in each. The query string and a full URL preview build live below, with keys and values percent-encoded automatically. Copy either with one click." },
      { q: "Can a key appear more than once?", a: "Yes. Duplicate keys are allowed, so tag=outline&tag=duotone works. Rows are joined with & in the order you enter them." },
      { q: "How do I parse an existing query string?", a: "Paste the query string, or a full URL containing one, into the reverse box and click Parse into rows. Percent-encoded characters are decoded back into readable keys and values." },
      { q: "How are special characters encoded?", a: "Keys and values go through encodeURIComponent, so a space becomes %20, & becomes %26 and = becomes %3D. Rows with an empty key are skipped." },
      { q: "What is the base URL field for?", a: "Type your endpoint, for example https://example.com/search, and the tool shows the complete URL with your query string appended, ready to copy and test." },
      { q: "Is my data uploaded anywhere?", a: "No. Building and parsing happen entirely in your browser. Nothing you type is sent to a server." }
    ],
    tags: [
      "query string builder",
      "url query string builder",
      "build query string",
      "query string generator",
      "url parameter builder",
      "url parameters builder",
      "query params builder",
      "free query string builder",
      "online query string builder",
      "query string maker",
      "create query string",
      "url query builder",
      "query string encoder",
      "url encode query string",
      "percent encode url",
      "encodeuricomponent online",
      "url encoding tool",
      "query string decoder",
      "url decode query string",
      "parse query string",
      "query string parser",
      "parse url parameters",
      "url to query params",
      "query string to json",
      "duplicate query params",
      "multiple query parameters",
      "url builder",
      "free url builder",
      "online url builder",
      "api query string builder",
      "rest api query params",
      "build api url",
      "test api url builder",
      "utm builder",
      "utm parameter builder",
      "utm url builder",
      "campaign url builder",
      "google analytics utm builder",
      "query string cheat sheet",
      "url query string syntax",
      "what is a query string",
      "query string format",
      "ampersand query string",
      "question mark url parameters",
      "url parameters explained",
      "javascript query string",
      "urlsearchparams",
      "how to add parameters to url",
      "browser url builder",
      "no signup url tool",
      "developer url tool",
      "free developer tools"
    ],
  };

export default seo;
