import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Random Port - Free Online Network Tool | IconVault",
    metaDescription: "Generate random TCP/UDP port numbers with secure randomness, optionally excluding well-known ports 0-1023. No duplicates. Free, client-side.",
    about: [
      "**IconVault**'s **Random Port** generator picks **random usable port numbers** for dev servers, containers and test setups. Choose **1, 5, 10, 20 or 50 ports**, toggle whether to **exclude well-known ports 0 to 1023**, and every batch is drawn with your browser's **cryptographically secure random generator** with **no duplicates** in one batch. Click any port, or the whole list, to **copy** it.",
      "It is **free** and runs **fully in your browser**, so nothing about your setup is shared. The honest limit: the tool picks **random numbers**, it does not check whether a port is actually **free on your machine**. Before binding, verify the port is not already in use, and remember that well-known ports are excluded by default because they usually need elevated privileges."
    ],
    faqs: [
      { q: "How do I get a random port number?", a: "Pick how many ports you want and click Generate. Each batch is unique within itself, sorted numerically, and clickable to copy individual ports or the whole list." },
      { q: "Should I exclude well-known ports?", a: "Usually yes, and it is the default. Ports 0 to 1023 are reserved for system services like HTTP and SSH and often need administrator rights to bind. Keeping the toggle on draws from 1024 to 65535." },
      { q: "Are the ports really random?", a: "Yes. Generation uses crypto.getRandomValues, your browser's cryptographically secure random source, not the weaker Math.random." },
      { q: "Can two ports in one batch be the same?", a: "No. Picks are collected in a set, so duplicates are impossible within a single generated batch." },
      { q: "Does this check if a port is free on my computer?", a: "No. It generates random port numbers only. A port could still be in use by another program, so check availability on your machine before binding to it." },
      { q: "Is anything sent to a server?", a: "No. Generation and copying happen entirely in your browser." }
    ],
    tags: [
      "random port generator",
      "random port",
      "generate random port",
      "free random port",
      "online random port generator",
      "random tcp port",
      "random udp port",
      "random port number",
      "random port picker",
      "port number generator",
      "free port generator",
      "usable port generator",
      "random open port",
      "find free port",
      "dev server port",
      "random port for development",
      "docker random port",
      "random port for container",
      "test server port",
      "random port for testing",
      "localhost port generator",
      "random localhost port",
      "ephemeral port",
      "dynamic port range",
      "private port range",
      "registered port range",
      "well known ports list",
      "exclude well known ports",
      "port 1024 to 65535",
      "valid port numbers",
      "port number range",
      "what is a valid port",
      "how to pick a port number",
      "choose unused port",
      "check if port is free",
      "port already in use",
      "cryptographically secure random port",
      "random port no duplicates",
      "generate 10 random ports",
      "multiple random ports",
      "copy port list",
      "nodejs random port",
      "vite dev port",
      "react dev server port",
      "port for web server",
      "port for api server",
      "network tools free",
      "sysadmin tools online",
      "devops random port",
      "browser port generator",
      "no signup port tool"
    ],
  };

export default seo;
