import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "README Score - Free Online README Grader Tool | IconVault",
    metaDescription: "Paste your README.md and get it graded against 16 proven practices: badges, screenshots, install docs, usage, API, license. Free, runs 100% in your browser.",
    about: [
      "**IconVault**'s **README Score** grades your README against **16 proven practices** that separate good project docs from great ones: a clear H1 title, a one-paragraph description, **status badges**, screenshots or a demo, **install** and **usage** sections, API reference, **contributing** guide, changelog, table of contents and a **license**, among others.",
      "Paste your markdown and every check gets a **pass or fail** with a short, actionable tip explaining what to add or fix. It runs **100% in your browser**, so your content is never uploaded, and it is **free** with no signup."
    ],
    faqs: [
      { q: "How is my README scored?", a: "The tool runs 16 checks against proven README practices: title, description, badges, screenshots or demo, install section, usage section, API docs, contributing guide, changelog, table of contents, license, and more. Each check passes or fails with a tip." },
      { q: "What should I do with failing checks?", a: "Each failed check includes a short tip, for example adding a shields.io badge block near the top or a one-paragraph description under the title. Fix the flagged sections and re-paste to watch your score improve." },
      { q: "What is a good README score?", a: "There is no universal passing grade, but READMEs that pass most of the 16 checks tend to get more stars and fewer setup questions from users. Aim for all 16 if you can." },
      { q: "Does it work with any markdown flavor?", a: "Yes. It analyzes plain markdown text, so README.md files from GitHub, GitLab, Bitbucket or npm packages all work the same way." },
      { q: "Is my README sent to a server?", a: "No. The analysis happens entirely in your browser. Nothing you paste is uploaded, logged or stored." },
      { q: "Can it check a README from a URL?", a: "Not directly. Open the README in your browser or editor, copy its raw markdown, and paste it into the tool. That takes a few seconds and keeps everything private." }
    ],
    tags: [
      "readme score",
      "readme grader",
      "readme checker",
      "readme quality checker",
      "grade my readme",
      "readme audit tool",
      "readme review tool",
      "readme analyzer",
      "readme evaluation tool",
      "github readme checker",
      "readme best practices checker",
      "readme lint",
      "markdown readme linter",
      "check readme quality",
      "readme completeness check",
      "readme score calculator",
      "improve github readme",
      "readme improvement tool",
      "readme feedback tool",
      "how to improve readme",
      "readme checklist grader",
      "readme standards check",
      "open source readme review",
      "repo documentation checker",
      "project documentation audit",
      "documentation quality checker",
      "docs quality score",
      "readme badges check",
      "readme missing badges",
      "readme screenshots check",
      "readme install section check",
      "readme usage section check",
      "readme api docs check",
      "readme contributing guide check",
      "readme changelog check",
      "readme license check",
      "readme table of contents check",
      "readme title check",
      "readme description check",
      "readme demo link check",
      "documentation completeness tool",
      "free readme audit online",
      "github repo health check",
      "repository documentation grader",
      "npm readme quality check",
      "developer documentation review tool",
      "readme writing checklist",
      "what makes a good readme",
      "readme do and dont",
      "readme template checklist",
      "github profile readme review",
      "private readme analysis tool",
      "browser based readme grader"
    ],
  };

export default seo;
