import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Redact Image - Free Online Tool | IconVault",
    metaDescription: "Permanently black out text and regions in images online. Free, private, runs in your browser.",
    about: [
      "**IconVault**'s **Redact Image** tool permanently covers **names, numbers, faces** and any sensitive region with a solid color bar you draw yourself. Unlike blur, the covered pixels are **destroyed, not hidden**, and because the image is **re-encoded**, the redaction cannot be undone and the file's **metadata is removed** too.",
      "It is **free** and runs **100% in your browser**, so sensitive documents never leave your device. Pick any **fill color** (black by default, via color well or hex), draw multiple resizable boxes, then export as **JPG, PNG, WebP** or the original format. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "Is redaction really permanent?", a: "Yes. Covered pixels are painted over with a solid color and the image is re-encoded from those pixels, so the original content is gone for good, not just hidden under a layer." },
      { q: "Redact vs blur: which is safer?", a: "Redaction. Blur and pixelation can sometimes be partially reversed with enhancement techniques. A solid color fill cannot." },
      { q: "Is my image uploaded?", a: "No. Redaction happens entirely in your browser. Sensitive images never leave your device." },
      { q: "Can I change the redaction color?", a: "Yes. Use the color well or type any 6-digit hex code. Black is the default." },
      { q: "Does it remove metadata too?", a: "Yes. Because the image is re-encoded, EXIF and GPS metadata are removed in the same step." },
      { q: "Is it free?", a: "Yes, with 5 free exports. Pro members get unlimited exports plus HD quality and every template across all IconVault tools." },
    ],
    tags: [ "redact image online", "black out text in image", "image redaction tool", "censor image online", "redact photo", "cover text in image", "permanent image redaction", "black bar image", "redact screenshot", "hide text in photo", "document redaction image", "redact personal info photo", "image blackout tool", "redact image free", "secure image redaction", "paint over image text", "redaction bar generator", "hide sensitive info image", "redact png online", "irreversible image redaction" ,
      "redact image",
      "image redactor",
      "redaction tool",
      "censor photo",
      "hide information in image",
      "black out image",
      "cover up text image",
      "block out text photo",
      "mask sensitive data image",
      "blur sensitive text image",
      "redacted photo maker",
      "redact id card photo",
      "redact aadhaar photo",
      "redact passport photo",
      "redact bank statement image",
      "hide account number screenshot",
      "censor name in screenshot",
      "hide address in photo",
      "redact license plate",
      "redaction box tool",
      "white box redaction image",
      "pixel redaction tool",
      "redact image for court",
      "legal document redaction",
      "redact medical record image",
      "hide patient info photo",
      "redact exam paper image",
      "redact pdf page image",
      "redacted screenshot maker",
      "before after redaction",
      "redact multiple areas image",
      "bulk redact images",
      "redact image online free no signup",
      "redact image without watermark",
      "drag to redact image",
      "draw black box on image",
      "cover face with black box",
      "censor bar maker",
      "mosaic redaction image",
      "secure redact online"],
  };

export default seo;
