import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Regex Cheatsheet - Free Online Regex Reference Tool | IconVault",
    metaDescription: "65 regex patterns grouped and searchable: anchors, character classes, quantifiers, groups, lookarounds. Click to copy. Free, JavaScript flavor, no signup.",
    about: [
      "**IconVault**'s **Regex Cheatsheet** packs **65 essential regex patterns** into one fast, searchable page. Every pattern is grouped by topic: **anchors**, **character classes**, **quantifiers**, **groups and capturing**, **lookarounds**, **backreferences**, **flags**, **escaping** and more, each with a plain-language explanation of what it matches.",
      "Type to **search** the whole sheet instantly and **click any pattern to copy it** to your clipboard. The patterns follow the **JavaScript regex flavor**, and the page is **free** with no signup, running entirely in your browser."
    ],
    faqs: [
      { q: "How many patterns does the cheatsheet include?", a: "65 patterns grouped into topic sections: anchors, character classes, quantifiers, groups, lookarounds, backreferences, flags and escaping." },
      { q: "Which regex flavor does it use?", a: "The JavaScript flavor, so the patterns work as-is in new RegExp() and regex literals in your JS and TypeScript code. Most patterns also work in other flavors like PCRE." },
      { q: "How do I copy a pattern?", a: "Click any pattern card and it is copied to your clipboard immediately. You can then paste it straight into your code." },
      { q: "Can I search the cheatsheet?", a: "Yes. Start typing in the search box and the list filters instantly across pattern text and descriptions, so you can find what you need without scrolling." },
      { q: "Does it cover lookahead and lookbehind?", a: "Yes. Positive and negative lookahead and lookbehind are included with examples, along with named groups and backreferences." },
      { q: "Is it really free?", a: "Yes. The full cheatsheet, search and click-to-copy all work with no account and no cost." }
    ],
    tags: [
      "regex cheatsheet",
      "regex cheat sheet",
      "regular expression cheatsheet",
      "regex reference",
      "regex quick reference",
      "regex syntax reference",
      "regex patterns list",
      "common regex patterns",
      "regex examples",
      "regex symbols explained",
      "regex metacharacters list",
      "regex anchors explained",
      "regex character classes",
      "regex quantifiers explained",
      "regex groups explained",
      "regex lookahead cheat sheet",
      "regex lookbehind examples",
      "regex backreference examples",
      "regex named groups syntax",
      "javascript regex cheatsheet",
      "js regex reference",
      "regex flags explained",
      "regex i flag g flag m flag",
      "regex dot all flag",
      "regex word boundary explained",
      "regex escape characters",
      "regex email pattern",
      "regex phone number pattern",
      "regex url pattern",
      "regex date pattern",
      "regex ip address pattern",
      "regex password validation pattern",
      "regex username validation",
      "regex hex color pattern",
      "regex number pattern",
      "regex whitespace pattern",
      "regex start end string",
      "regex or operator",
      "regex optional group",
      "regex greedy vs lazy",
      "regex non capturing group",
      "regex alternation examples",
      "regex shorthand classes",
      "regex unicode property escapes",
      "learn regex quickly",
      "regex for beginners reference",
      "regex pdf cheat sheet alternative",
      "printable regex reference",
      "regex pattern copy paste",
      "copy regex patterns",
      "regex one liners",
      "regex cookbook patterns",
      "regex validation patterns list"
    ],
  };

export default seo;
