import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Regex Visualizer - Free Online Regex Railroad Diagram Tool | IconVault",
    metaDescription: "Understand any regex: railroad diagram, plain-English explanation and live match tester. Paste a pattern and see what it really matches. Free, in your browser.",
    about: [
      "**IconVault**'s **Regex Visualizer** turns cryptic patterns into something you can actually read. Paste any **JavaScript regex** and get a **railroad diagram** that lays the pattern out as a flowchart, a **plain-English explanation** of each token, and a **live tester** that highlights matches in your sample text.",
      "It is perfect for **decoding** inherited patterns, **learning** regex by example, and **debugging** why a pattern matches too much or too little. Everything renders **instantly in your browser**, and the tool is **free** with no signup."
    ],
    faqs: [
      { q: "What is a railroad diagram?", a: "A railroad diagram, also called a syntax diagram, draws your regex as connected tracks. Loops represent quantifiers, branches represent alternation, and you can trace a valid match by following the lines, which makes structure obvious at a glance." },
      { q: "How does the plain-English explanation work?", a: "The tool parses your pattern and describes each part in words, for example that \\d{3} means exactly three digits. It is much easier than mentally compiling symbols." },
      { q: "Can I test my regex against sample text?", a: "Yes. The built-in live tester highlights every match in text you paste, so you can immediately see whether the pattern behaves the way the diagram suggests." },
      { q: "Which regex syntax is supported?", a: "JavaScript regex syntax: literals, character classes, shorthands like \\d and \\w, quantifiers, greedy and lazy matching, groups, non-capturing groups, alternation and anchors." },
      { q: "Can it explain someone else's regex?", a: "That is one of its best uses. Paste a cryptic pattern from Stack Overflow or a legacy codebase and get the diagram plus explanation instead of decoding it by hand." },
      { q: "Is it free?", a: "Yes. Diagram, explanation and tester are all free with no account required." }
    ],
    tags: [
      "regex visualizer",
      "regex visualizer online",
      "regex railroad diagram",
      "regex diagram generator",
      "regex syntax diagram",
      "visualize regex pattern",
      "regex explained visually",
      "regex in plain english",
      "regex explainer",
      "explain regex pattern",
      "regex decoder",
      "understand regex pattern",
      "regex parser visual",
      "regex flowchart",
      "regex graph",
      "regex structure diagram",
      "regex live tester",
      "regex match highlighter",
      "test regex online visual",
      "regex playground visual",
      "regex debugger visual",
      "debug regex online",
      "why does my regex match",
      "regex too greedy fix",
      "learn regex visually",
      "regex teaching tool visual",
      "regex for beginners visual",
      "interactive regex diagram",
      "regex token explanation",
      "regex breakdown tool",
      "regex pattern analyzer",
      "analyze regex pattern",
      "regex inspector",
      "regex explorer online",
      "free regex diagram tool",
      "javascript regex visualizer",
      "js regex diagram",
      "regex101 alternative",
      "regexr alternative",
      "online regex explainer",
      "regex to english",
      "regex to words",
      "readable regex",
      "regex documentation generator",
      "comment my regex",
      "regex readability tool",
      "legacy regex decoder",
      "stack overflow regex explained",
      "copy paste regex explain",
      "no signup regex visualizer",
      "browser regex diagram"
    ],
  };

export default seo;
