import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Regex Replace - Free Online Regex Find and Replace Tool | IconVault",
    metaDescription: "Find and replace with regex and $1 backreferences. Live highlighted diff, match count and copyable output. Free, runs 100% in your browser.",
    about: [
      "**IconVault**'s **Regex Replace** is a live **find and replace** workbench for text. Enter a **regex pattern** with any JS flags, write a **replacement string** using **$1 backreferences**, **$&**, **$$** and friends, and see a **highlighted diff** of every change update instantly as you type.",
      "It shows the **match count**, flags pattern errors clearly, and gives you a **copyable output** in one click. Everything runs **100% in your browser**, so large or private text never leaves your device, and it is **free** with no signup."
    ],
    faqs: [
      { q: "How do backreferences work here?", a: "Use $1 through $9 to insert capture groups into the replacement. $& inserts the whole match, $$ inserts a literal dollar sign, $` inserts the text before the match and $' inserts the text after it, following JavaScript replacement string rules." },
      { q: "Which flags are supported?", a: "The flags g, i, m, s, u and y are supported. The global flag is applied automatically so every match is replaced, not just the first." },
      { q: "What does the highlighted diff show?", a: "Your input text is rendered with every replaced segment highlighted, so you can verify each change before copying the result. The match count tells you how many replacements were made." },
      { q: "Can I use it for renaming patterns in code?", a: "Yes. Paste a code snippet, match a naming pattern like get(\\w+) and replace with fetch$1 to bulk-rename, then copy the output back into your editor." },
      { q: "Is there a limit on input size?", a: "The tool runs in your browser, so practical limits depend on your device. It comfortably handles multi-thousand-line pastes like log files and data dumps." },
      { q: "Is my text uploaded anywhere?", a: "No. Matching, replacement and diff rendering all happen locally in your browser. Nothing is sent to a server." }
    ],
    tags: [
      "regex replace",
      "regex find and replace",
      "regex replace online",
      "regex substitution tool",
      "regex replace tester",
      "regex search replace online",
      "find replace with regex",
      "regex replace text",
      "regex backreference replace",
      "regex $1 replacement",
      "regex replace with capture group",
      "regex replacement string",
      "javascript regex replace tool",
      "js regex replace online",
      "regex global replace",
      "bulk text replace regex",
      "regex replace in text file",
      "regex replace multiple occurrences",
      "regex replace all matches",
      "regex replace with dollar sign",
      "regex $& whole match replace",
      "regex replace before after match",
      "highlighted diff regex",
      "regex replace preview",
      "live regex replace",
      "regex replace match count",
      "regex replace copy output",
      "online sed tool",
      "sed alternative online",
      "regex text transformer",
      "regex reformat text",
      "regex rename tool",
      "bulk rename with regex",
      "regex replace log files",
      "regex clean up text",
      "regex replace whitespace",
      "regex replace newlines",
      "regex replace commas",
      "regex replace quotes",
      "regex replace html tags",
      "regex replace dates format",
      "regex replace phone numbers",
      "regex replace email addresses",
      "regex replace special characters",
      "regex replace case insensitive",
      "regex replace multiline",
      "regex replace tutorial",
      "regex substitution examples",
      "regex replace cheat sheet",
      "free regex replace tool",
      "no signup regex tool",
      "browser regex replace",
      "private text replace tool"
    ],
  };

export default seo;
