import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Remove Duplicate Lines - Free Dedupe Tool | IconVault",
    metaDescription:
      "Remove duplicate lines free: dedupe lists instantly with counts, case-insensitive mode and sorting. Runs in your browser.",
    about: [
      "**IconVault**'s **Remove Duplicate Lines** cleans messy lists in one click: paste **lines**, drop the **duplicates**, and get back a unique list - with a count of removed **lines**, optional **case-insensitive** matching, whitespace trimming and alphabetical **sorting**.",
      "Keeps first occurrence order by default, so ranked lists stay ranked. Everything runs locally in your browser - free, no account.",
    ],
    faqs: [
      {
        q: "Which duplicate is kept?",
        a: "The first occurrence. Order is preserved unless you enable sorting.",
      },
      {
        q: "Does it handle case differences?",
        a: "Optionally - enable case-insensitive mode to treat 'Apple' and 'apple' as the same line.",
      },
      {
        q: "What about blank lines?",
        a: "You can strip empty lines and trim whitespace per line before deduping, so ' item ' and 'item' match.",
      },
      {
        q: "How many lines can it process?",
        a: "Hundreds of thousands - deduping is O(n) and local, so even huge lists finish instantly.",
      },
    ],
    tags: [
      "remove duplicate lines", "dedupe lines online", "remove duplicates from list",
      "delete duplicate lines", "unique lines", "line deduper free",
      "remove duplicate rows", "deduplicate text", "excel remove duplicates online",
      "list cleaner", "remove repeated lines",
    
      "remove duplicates online",
      "duplicate line remover",
      "delete duplicates online",
      "dedupe text",
      "find duplicate lines",
      "unique line filter",
      "remove duplicate entries",
      "clean duplicate lines",
      "deduplicate list online",
      "remove repeated text",
      "unique values extractor",
      "delete duplicate rows online",
      "remove duplicate emails",
      "dedupe email list",
      "remove duplicate urls",
      "duplicate url remover",
      "clean list online",
      "list deduplicator",
      "remove duplicates free",
      "dedupe lines free",
      "sort and dedupe",
      "alphabetical dedupe",
      "remove duplicates keep order",
      "unique lines online",
      "extract unique lines",
      "get unique values from list",
      "remove duplicate words",
      "dedupe words",
      "remove duplicate sentences",
      "duplicate sentence remover",
      "text deduplication tool",
      "list cleaner online",
      "remove redundant lines",
      "data cleaner online",
      "csv dedupe online",
      "remove duplicate rows csv",
      "dedupe csv",
      "excel dedupe online",
      "remove duplicates no signup",
      "free duplicate remover",
      "duplicate finder online",
      "highlight duplicate lines",
      "count duplicate lines",
      "remove duplicate paragraphs",
      "dedupe names list",
      "remove duplicate keywords",
      "keyword list cleaner",
      "unique keyword extractor",
      "backlink list cleaner"],
  };

export default seo;
