import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Remove Extra Spaces - Free Whitespace Cleaner | IconVault",
    metaDescription:
      "Remove extra spaces free: collapse multiple spaces, trim lines and clean pasted text. One-click whitespace cleanup.",
    about: [
      "**IconVault**'s **Remove Extra Spaces** fixes sloppy **whitespace** in one click: collapse **multiple spaces** to one, **trim** leading/trailing spaces per line, strip blank lines, and normalize tabs - the cleanup every pasted **text** needs.",
      "See before/after stats (characters saved) and copy the cleaned result. Runs in your browser, free, no account needed.",
    ],
    faqs: [
      {
        q: "What does it clean?",
        a: "Multiple consecutive spaces become one, lines are trimmed, tabs can be converted to spaces, and empty lines removed - each toggleable.",
      },
      {
        q: "Will it break my code indentation?",
        a: "It has a code-safe mode that only collapses horizontal whitespace runs longer than one space and never touches line-leading indentation.",
      },
      {
        q: "Does it handle non-breaking spaces?",
        a: "Yes - NBSP and other unicode spaces are normalized to regular spaces.",
      },
      {
        q: "Is my text uploaded?",
        a: "No. All cleaning happens locally in your browser.",
      },
    ],
    tags: [
      "remove extra spaces", "remove double spaces", "whitespace remover",
      "trim spaces online", "clean up spaces in text", "collapse whitespace",
      "remove blank lines", "text cleaner", "fix spacing in text",
      "extra space remover", "free text cleaner",
    
      "remove spaces online",
      "remove spaces from text",
      "extra whitespace remover",
      "delete extra spaces",
      "trim whitespace online",
      "clean whitespace online",
      "normalize spaces",
      "fix double spaces",
      "remove trailing spaces",
      "remove leading spaces",
      "trim text online",
      "whitespace cleaner",
      "space remover tool",
      "delete blank lines",
      "remove empty lines online",
      "blank line remover",
      "delete empty lines",
      "text whitespace fixer",
      "clean text formatting",
      "remove tabs from text",
      "remove line breaks",
      "remove newlines online",
      "join lines tool",
      "single line text maker",
      "collapse lines online",
      "remove paragraph breaks",
      "fix text spacing",
      "text cleanup tool",
      "tidy text online",
      "clean pasted text",
      "remove formatting from text",
      "plain text cleaner",
      "normalize whitespace",
      "text formatter online free",
      "remove spaces free",
      "whitespace remover online",
      "space cleaner online",
      "extra line remover",
      "double space fixer",
      "remove multiple spaces",
      "single space converter",
      "trim all spaces",
      "clean copied text",
      "excel space remover",
      "remove spaces in excel cell",
      "sql space cleaner",
      "remove spaces no signup",
      "free whitespace tool",
      "text tidier"],
  };

export default seo;
