import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Remove Metadata from Photos - Free Online Tool | IconVault",
    metaDescription: "Strip EXIF and GPS metadata from photos online. Re-saves pixels in your browser, free and private.",
    about: [
      "**IconVault**'s **Remove Metadata** tool wipes every trace of **EXIF data** from your photos: camera model, capture time, **GPS location**, software tags and thumbnails. It works by **re-saving the pixels** through your browser's canvas, and canvas output carries no metadata at all, so the cleaned photo is genuinely clean, not just relabeled.",
      "It is **free**, handles **multiple photos at once**, and keeps your images upright (optional EXIF rotation) and color-accurate (converted to web-standard sRGB). Nothing is ever uploaded: your photos never leave your device. Download each cleaned photo individually or grab them all as a **ZIP**. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "What metadata is removed?", a: "Everything EXIF carries: camera make and model, date taken, GPS coordinates, exposure settings, software used and embedded thumbnails. The output file has no metadata at all." },
      { q: "Does it change how my photo looks?", a: "No visible change. Pixels are re-saved at high quality, with optional EXIF rotation applied and colors converted to sRGB so they look the same everywhere." },
      { q: "Is my photo uploaded anywhere?", a: "Never. Stripping happens entirely in your browser. Your photos never leave your device." },
      { q: "Can I clean multiple photos at once?", a: "Yes. Add as many photos as you like, strip them all in one run, then download each one or all of them as a ZIP." },
      { q: "Will the GPS location really be gone?", a: "Yes. Because the image is re-encoded from raw pixels, the GPS tags cannot survive. You can verify with the EXIF Viewer afterwards." },
      { q: "Is it free?", a: "Yes, with 5 free runs. Pro members get unlimited runs plus HD exports and every template across all IconVault tools." },
    ],
    tags: [ "remove exif data", "remove metadata from photo", "strip exif online", "photo metadata remover", "remove gps from photo", "exif remover free", "clean photo metadata", "remove image metadata online", "strip photo metadata", "exif cleaner", "remove location from photo", "photo privacy tool", "delete exif data", "image metadata stripper", "remove camera info from photo", "anonymize photo", "scrub exif online free", "photo exif eraser", "remove jpg metadata", "batch exif remover" ,
      "remove metadata",
      "metadata remover",
      "exif removal tool",
      "photo metadata cleaner",
      "clear image metadata",
      "wipe exif data",
      "erase photo metadata",
      "strip metadata from image",
      "metadata cleaner online",
      "exif data eraser",
      "remove metadata from jpg",
      "remove metadata from png",
      "remove metadata from webp",
      "remove metadata from heic",
      "remove metadata from tiff",
      "remove metadata from raw photo",
      "bulk metadata remover",
      "remove metadata multiple photos",
      "photo anonymizer online",
      "clean image before upload",
      "privacy photo cleaner",
      "remove exif before posting",
      "strip exif before upload",
      "remove personal data from photo",
      "delete photo properties",
      "clear photo details",
      "photo info remover",
      "image info cleaner",
      "exif stripper",
      "exif scrubber",
      "iptc remover",
      "xmp metadata remover",
      "remove thumbnail from exif",
      "clean scanned document metadata",
      "photo metadata removal free",
      "exif remover no signup",
      "remove metadata browser tool",
      "offline metadata remover",
      "keep image quality remove exif",
      "exif remover for photographers"],
  };

export default seo;
