import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Resize GIF - Free Online Tool | IconVault",
    metaDescription: "Resize animated GIFs by pixels or percent online. Every frame scaled, loop preserved. Free, private.",
    about: [
      "**IconVault**'s **Resize GIF** tool scales an **animated GIF** to any size: type exact **pixels** or pick a **percentage**, with an optional **keep aspect ratio** lock. Every single frame is resized, and the **animation loop is preserved** exactly as the original, so a forever-looping GIF keeps looping.",
      "It is **free** and runs **100% in your browser**, with an **animated preview** of the resized result before you download. Your GIF never leaves your device. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "How do I resize an animated GIF?", a: "Drop the GIF, choose Pixels or Percent, set the size and hit Resize GIF. Every frame is scaled and you get an animated preview before downloading." },
      { q: "Does resizing keep the animation?", a: "Yes. All frames are resized individually and the original loop setting is preserved in the output." },
      { q: "Can I resize by percentage?", a: "Yes. Switch to Percent mode and drag the scale slider, or type exact pixels in Pixels mode." },
      { q: "Will it keep the aspect ratio?", a: "Yes, when the keep aspect ratio box is checked. Uncheck it to set width and height independently." },
      { q: "Is my GIF uploaded?", a: "No. Resizing happens entirely in your browser. Your GIF never leaves your device." },
      { q: "Is it free?", a: "Yes, with 5 free resizes. Pro members get unlimited runs plus HD exports and every template across all IconVault tools." },
    ],
    tags: [ "resize gif", "gif resizer", "change gif size", "scale gif online", "gif dimensions", "resize animated gif", "make gif bigger", "make gif smaller dimensions", "gif width height", "online gif resizer", "gif scaler", "resize gif free", "gif pixel size", "shrink gif dimensions", "enlarge gif", "gif size changer", "resize gif no watermark", "browser gif resizer", "gif aspect ratio", "animated gif dimensions" ,
      "gif resize",
      "resize gif online",
      "gif size reducer dimensions",
      "change gif dimensions",
      "gif width changer",
      "gif height changer",
      "resize gif to 500px",
      "resize gif to 300px",
      "resize gif for discord",
      "resize gif for discord emoji",
      "resize gif for telegram",
      "resize gif for whatsapp",
      "resize gif for twitter",
      "resize gif for avatar",
      "resize gif profile picture",
      "resize gif for website",
      "resize gif for email",
      "scale down gif",
      "scale up gif",
      "shrink animated gif",
      "enlarge animated gif",
      "resize gif without losing animation",
      "keep gif animation resize",
      "resize gif frames",
      "gif dimension converter",
      "make gif square",
      "make gif 1:1",
      "gif to 512x512",
      "gif to 256x256",
      "gif to 1080p",
      "custom gif size",
      "set gif width",
      "gif percentage resize",
      "resize gif 50 percent",
      "batch resize gifs",
      "resize multiple gifs",
      "free gif resize tool",
      "gif resizer no signup",
      "fast gif resizer",
      "resize gif online free tool"],
  };

export default seo;
