import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Resize to CM / MM - Free Online Tool | IconVault",
    metaDescription: "Resize photos to an exact size in cm, mm or inches at your DPI, free in your browser. Perfect for ID and passport photos.",
    about: [
      "**IconVault**'s **Resize to CM / MM** resizes a photo to an exact **physical size** in centimeters, millimeters or inches at your chosen **DPI** (72, 150, 300, 600 or custom), and **embeds the DPI in the file** so printers and form portals read it correctly. The default 3.5 x 4.5 cm at 300 DPI is the classic **passport and ID photo** size. Output is exact on both sides: extra edges are **center-cropped**, and a live readout shows the resulting pixel dimensions.",
      "It is **free** to use and **private by design**: everything runs in your browser, so ID photos and documents never leave your device. **Pro** members get unlimited resizes with print-ready output.",
    ],
    faqs: [
      { q: "How do I make a 3.5 x 4.5 cm passport photo?", a: "Upload your photo, keep CM selected with 3.5 width and 4.5 height, choose 300 DPI, and download. The tool outputs exactly 413 x 531 px with 300 DPI embedded." },
      { q: "Is the DPI really embedded in the file?", a: "Yes. For JPG it is written into the JFIF header and for PNG into a pHYs chunk, so printers and portals detect the correct physical size." },
      { q: "What happens if my photo's shape doesn't match?", a: "The image is scaled to cover your target frame exactly, and extra edges are center-cropped. Nothing is stretched or squashed." },
      { q: "Can I keep my photo's proportions?", a: "Yes. Tick Keep proportions and changing one side updates the other automatically based on your photo's aspect ratio." },
      { q: "What is Same as input format?", a: "It exports in your upload's format (JPG, PNG or WebP). DPI embedding applies to JPG and PNG; WebP has no standard DPI header, so it is skipped there." },
      { q: "Are my ID photos uploaded anywhere?", a: "No. All processing happens locally in your browser. Your files never leave your device." },
    ],
    tags: ["resize image to cm", "photo size in cm", "resize photo to 3.5x4.5 cm", "passport photo resizer", "id photo size maker", "resize image to mm", "cm to pixels converter image", "300 dpi photo resizer", "resize photo for print", "image size in inches", "passport photo maker online", "3.5x4.5 cm photo", "resize jpg to cm", "photo dpi changer", "set dpi of image", "print size photo resizer", "id card photo resizer", "visa photo size maker", "free cm resizer", "physical size image resizer",
      "cm photo resizer",
      "mm photo resizer",
      "resize photo in cm online",
      "convert cm to pixels",
      "pixels to cm converter",
      "inches to pixels photo",
      "photo size converter cm",
      "2x2 inch photo maker",
      "35x45 mm photo maker",
      "4x6 inch photo resizer",
      "5x7 inch photo maker",
      "a4 photo size maker",
      "passport size photo 3.5x4.5",
      "indian passport photo 3.5x4.5 cm",
      "visa photo 5x5 cm",
      "id card photo size cm",
      "driving licence photo size india",
      "pan card photo size",
      "photo print size calculator",
      "print photo at exact size",
      "resize image for printing",
      "change photo dpi online",
      "300 dpi image maker",
      "600 dpi photo resizer",
      "dpi converter image",
      "set image resolution dpi",
      "photo cm to pixel calculator",
      "mm to pixel converter photo",
      "physical dimension photo resizer",
      "real size photo printer",
      "resize photo to 10x15 cm",
      "resize photo to 13x18 cm",
      "resize image to a4 size",
      "poster size photo maker",
      "banner size photo resizer",
      "frame size photo maker",
      "photo enlargement size tool",
      "exact cm photo tool",
      "photo measurement resizer",
      "dimension converter for photos"],
  };

export default seo;
