import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Responsive Tester - Free Online Responsive Design Tester Tool | IconVault",
    metaDescription: "Preview any URL at popular breakpoints and device sizes in a sandboxed iframe. iPhone, Pixel, iPad, laptop, desktop presets, plus rotate. Free.",
    about: [
      "**IconVault**'s **Responsive Tester** loads any URL into a **sandboxed iframe** at the **breakpoints and device sizes** that matter. Jump between **375px, 768px, 1024px and 1440px** widths, use **device presets** for iPhone, Pixel, iPad, laptop and desktop, and **rotate** the viewport to check landscape layouts.",
      "It runs **entirely in your browser**, so there is nothing to install and no screenshots uploaded anywhere. One honest caveat: some sites block embedding with **X-Frame-Options**, so a blank frame usually means the site refused to be embedded, not a bug in the tool."
    ],
    faqs: [
      { q: "How do I test my site?", a: "Paste the URL, hit load, then pick a breakpoint or device preset. The page renders in a sandboxed iframe at that exact viewport size, with the width and height shown so you can verify your media queries." },
      { q: "Which breakpoints are included?", a: "Common widths of 375, 768, 1024 and 1440 pixels, plus full width, and device presets for iPhone (390x844), Pixel (412x915), iPad (820x1180), laptop (1440x900) and desktop (1920x1080)." },
      { q: "Why is the preview blank for some sites?", a: "Many sites send X-Frame-Options or Content-Security-Policy headers that forbid embedding in iframes. That is the site protecting itself, and no iframe-based tester can bypass it. Your own sites work if you allow framing." },
      { q: "Can I rotate the viewport?", a: "Yes. A rotate button swaps width and height so you can check landscape layouts on phones and tablets instantly." },
      { q: "Does it emulate touch or device pixels?", a: "It resizes the viewport only. It does not emulate device pixel ratio, touch events or user agents. For deep device emulation, use your browser's built-in dev tools alongside this quick checker." },
      { q: "Is it free?", a: "Yes. Unlimited previews with no account and no signup." }
    ],
    tags: [
      "responsive tester",
      "responsive design tester",
      "responsive website tester",
      "responsive test online",
      "test website responsiveness",
      "check responsive design",
      "mobile responsive checker",
      "responsive preview tool",
      "website breakpoint tester",
      "viewport tester",
      "screen size tester",
      "device size preview",
      "mobile viewport preview",
      "test site on mobile sizes",
      "preview website on iphone",
      "preview website on ipad",
      "website mobile view checker",
      "desktop to mobile preview",
      "responsive layout checker",
      "media query tester",
      "css breakpoint tester",
      "test breakpoints online",
      "375px 768px 1024px tester",
      "common breakpoints tester",
      "iphone viewport tester",
      "pixel phone viewport tester",
      "ipad viewport tester",
      "laptop viewport tester",
      "desktop viewport tester",
      "rotate viewport tester",
      "landscape mode tester",
      "iframe website preview",
      "sandboxed iframe preview",
      "embed website preview tool",
      "url preview different sizes",
      "website screenshot sizes",
      "responsive design check free",
      "free responsive checker online",
      "web design qa tool",
      "frontend qa responsive",
      "check my site on mobile",
      "is my website mobile friendly",
      "mobile friendly test alternative",
      "google mobile friendly test",
      "responsive design examples tester",
      "webflow responsive preview",
      "wordpress responsive check",
      "shopify mobile preview",
      "landing page responsive test",
      "portfolio responsive check",
      "no install responsive tester",
      "browser based viewport tool"
    ],
  };

export default seo;
