import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Resume Builder - Free Online Resume Builder Tool | IconVault",
    metaDescription: "Build an ATS-friendly resume with live preview. Add experience, education and skills, then export to PDF, Word or Markdown. Free, runs 100% in your browser.",
    about: [
      "**IconVault**'s **Resume Builder** helps you write a clean, **ATS-friendly resume** without fighting a word processor. Add your contact details, a **summary**, **work experience** with bullet points, **education** and **skills**, and a **live preview** shows exactly how the finished resume looks as you type.",
      "When it is ready, **export to PDF, Word or Markdown** in one click. Everything is built **100% in your browser**, so your personal details are never uploaded or stored, and the tool is **free** with no signup."
    ],
    faqs: [
      { q: "What makes a resume ATS-friendly?", a: "Applicant tracking systems parse simple, single-column layouts best. This builder uses a clean structure with standard section headings, no text boxes or graphics, and plain text that parsers can read reliably." },
      { q: "Which export formats are supported?", a: "You can export your resume as PDF, Word (.doc) or Markdown, so you can submit the PDF to employers and keep an editable copy for yourself." },
      { q: "Can I add multiple jobs and schools?", a: "Yes. Add as many experience and education entries as you need, reorder them, and remove any that no longer belong." },
      { q: "Is my personal information private?", a: "Completely. Everything you type stays in your browser. Nothing is uploaded, stored or shared, which matters when your resume contains phone numbers and addresses." },
      { q: "Do I need an account?", a: "No. The full builder and all exports work with no signup." },
      { q: "Can I use it for a CV or a one-page resume?", a: "Yes. The format works for resumes and academic CVs alike. Keep it to one or two pages for most roles by trimming older or less relevant entries." }
    ],
    tags: [
      "resume builder",
      "free resume builder",
      "online resume builder",
      "resume maker",
      "free resume maker",
      "cv builder",
      "free cv builder",
      "online cv maker",
      "resume creator",
      "build my resume online",
      "create resume free",
      "make a resume online free",
      "resume template builder",
      "ats friendly resume builder",
      "ats resume builder",
      "resume builder pdf",
      "resume to pdf online",
      "resume word export",
      "download resume pdf free",
      "professional resume builder",
      "simple resume builder",
      "clean resume builder",
      "modern resume builder",
      "one page resume builder",
      "resume builder no signup",
      "resume maker no account",
      "private resume builder",
      "resume builder no watermark",
      "job resume creator",
      "work experience resume builder",
      "resume summary builder",
      "resume skills section builder",
      "education section resume",
      "resume bullet points builder",
      "resume format tool",
      "best resume format 2026",
      "resume layout maker",
      "resume live preview",
      "resume markdown export",
      "resume writing tool",
      "how to write a resume",
      "resume tips builder",
      "resume examples generator",
      "entry level resume builder",
      "student resume builder",
      "fresher resume maker",
      "experienced resume builder",
      "tech resume builder",
      "developer resume builder",
      "designer resume builder",
      "internship resume builder",
      "cover letter resume combo",
      "linkedin resume builder",
      "resume checker friendly",
      "browser based resume maker"
    ],
  };

export default seo;
