import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "ROT13 Cipher - Free Online Cipher and Caesar Shift Tool | IconVault",
    metaDescription: "Encode and decode ROT13 plus any Caesar shift from 1 to 25, with live output as you type. Free and fully in your browser.",
    about: [
      "**IconVault**'s **ROT13 Cipher** tool encodes and decodes **ROT13** text instantly, and also works as a full **Caesar cipher** tool with an adjustable shift from 1 to 25. Type or paste your text and the output updates **live as you type**; flip between **Encode** and **Decode** with one tap. Non-letters pass through untouched, and letter case is preserved.",
      "Everything runs **100% in your browser**, so nothing you encode ever leaves your device, and copying the result is all it takes to use it. It is **free** with no signup. The honest note: ROT13 and Caesar shifts are **puzzles and obfuscation, not real encryption**. They are great for spoilers, geocaching hints and classroom demos, but anything that must stay secret needs real encryption like AES."
    ],
    faqs: [
      { q: "What is ROT13?", a: "ROT13 is a simple letter substitution where each letter is replaced by the one 13 places later in the alphabet. Applying it twice restores the original text, which is why it is popular for hiding spoilers." },
      { q: "What is the Caesar cipher?", a: "The Caesar cipher shifts every letter by a fixed number of positions, famously used by Julius Caesar with a shift of 3. This tool supports any shift from 1 to 25, with 13 giving classic ROT13." },
      { q: "Does it preserve capital letters and punctuation?", a: "Yes. Uppercase stays uppercase, lowercase stays lowercase, and numbers, spaces and punctuation are left unchanged." },
      { q: "Is ROT13 secure?", a: "No. It is trivially reversible and provides zero real security. Use it for fun, puzzles and spoiler hiding, never for anything confidential." },
      { q: "Is my text sent to a server?", a: "No. The transformation runs entirely in your browser with plain JavaScript. Your text never leaves the page." },
      { q: "Can I decode text without knowing the shift?", a: "For ROT13 you can, since encoding and decoding are the same operation. For other shifts, try each shift from 1 to 25 with the Decode mode until the text reads correctly." }
    ],
    tags: [
      "rot13 cipher",
      "rot13 decoder",
      "rot13 encoder",
      "rot13 translator",
      "caesar cipher",
      "caesar cipher decoder",
      "caesar cipher encoder",
      "caesar shift cipher",
      "caesar cipher calculator",
      "decode rot13 online",
      "encode rot13 online",
      "rot13 to text",
      "text to rot13",
      "rot13 converter free",
      "caesar cipher converter",
      "caesar cipher solver",
      "caesar cipher with shift",
      "rot13 cipher tool",
      "what is rot13",
      "how does rot13 work",
      "rot13 example",
      "rot13 explained",
      "caesar cipher explained",
      "shift cipher decoder",
      "letter shift cipher",
      "monoalphabetic substitution cipher",
      "substitution cipher decoder",
      "simple cipher encoder online",
      "encode secret message cipher",
      "secret message encoder",
      "decode hidden message online",
      "puzzle cipher decoder",
      "escape room cipher solver",
      "rot13 geocaching",
      "caesar cipher puzzle",
      "rot13 spoiler decoder",
      "unscramble rot13 text",
      "rot13 shift 13",
      "caesar cipher shift 3",
      "rot13 online free no signup",
      "caesar cipher free tool",
      "encode text with cipher online",
      "decode caesar cipher without shift",
      "brute force caesar cipher",
      "all caesar shifts decoder",
      "rot13 in browser",
      "caesar cipher history",
      "who invented caesar cipher",
      "rot13 email obfuscation",
      "rot13 for spoilers",
      "cipher text generator",
      "fun cipher generator online",
      "rot13 decode tool",
      "caesar cipher online free"
    ],
  };

export default seo;
