import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Rotate & Flip Image - Free Online Tool | IconVault",
    metaDescription: "Rotate or flip any photo online in seconds. Free batch image rotator that works privately in your browser.",
    about: [
      "**IconVault**'s **Rotate & Flip** tool fixes sideways photos and mirrors images in one click. Rotate left, rotate right, flip horizontal or flip vertical, and when you have a whole batch, apply the same edit to every image at once. Everything runs **free** and **browser-private**, your photos never leave your device.",
      "Pixels are moved exactly, never cropped or re-sampled, so quality stays intact. **Transparent images export as PNG** automatically, everything else as high-quality JPG. **Pro** members get unlimited use with no trial limits.",
    ],
    faqs: [
      { q: "How do I rotate a photo 90 degrees online?", a: "Drop your image into the Rotate & Flip tool, click Rotate right or Rotate left, then download. The rotation is exact and lossless, no cropping happens." },
      { q: "Can I rotate multiple images at once?", a: "Yes. Upload several photos, set the rotation or flip on one of them, then click Apply to all. You can download everything together as a ZIP." },
      { q: "Does rotating reduce image quality?", a: "No. The tool moves pixels exactly without re-sampling, so 90, 180 and 270 degree rotations are completely lossless." },
      { q: "What format do rotated images download as?", a: "Images with transparency export as PNG. Everything else exports as JPG at a quality you control with the slider, default 95." },
      { q: "Is my photo uploaded to a server?", a: "Never. All processing happens in your browser on your own device, so your photos stay completely private." },
      { q: "Is the rotate tool really free?", a: "Yes, free users get a generous number of uses per tool. Pro members get unlimited use of every tool with no limits." },
    ],
    tags: [ "rotate image online", "flip image online", "rotate photo 90 degrees", "rotate picture online free", "flip photo horizontally", "mirror image online", "rotate jpg online", "rotate png online", "batch rotate images", "rotate multiple photos at once", "flip image vertically", "rotate image without losing quality", "free image rotator", "rotate image 180 degrees", "flip picture online", "rotate image in browser", "photo flipper online", "rotate image left", "rotate image right", "image rotation tool" ,
      "rotate image",
      "flip image",
      "image rotator",
      "image flipper",
      "rotate photo online",
      "flip photo online",
      "rotate picture 90 degrees",
      "rotate image 90 degrees clockwise",
      "rotate image 270 degrees",
      "rotate photo upside down",
      "flip image left right",
      "flip image up down",
      "mirror photo online",
      "mirror selfie online",
      "unmirror selfie",
      "flip selfie camera photo",
      "rotate image 45 degrees",
      "custom angle image rotate",
      "straighten photo online",
      "fix tilted photo",
      "rotate scanned document",
      "rotate pdf page image",
      "rotate webp image",
      "rotate gif image",
      "rotate heic photo",
      "rotate image without cropping",
      "lossless image rotate",
      "rotate image and save",
      "rotate photo for upload",
      "rotate image for instagram",
      "rotate video thumbnail",
      "batch flip images",
      "flip multiple photos",
      "mirror batch photos",
      "rotate all images at once",
      "rotate image no signup",
      "rotate image free tool",
      "online image flipper",
      "photo rotation editor",
      "image orientation fixer"],
  };

export default seo;
