import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "RSA Key Generator - Free Online RSA Key Pair Generator Tool | IconVault",
    metaDescription: "Generate RSA-2048 or RSA-4096 key pairs with WebCrypto and export PKCS#8 and SPKI PEM files. Keys never leave your device. Free.",
    about: [
      "**IconVault**'s **RSA Key Generator** creates **RSA-2048** or **RSA-4096** key pairs using the browser's **WebCrypto API**, the same cryptography built into modern browsers. The private key is exported as **PKCS#8 PEM** and the public key as **SPKI PEM**, ready to paste into SSH configs, JWT signing setups, TLS workflows and API authentication.",
      "Because generation happens **entirely on your device**, your private keys are **never transmitted, stored or logged** anywhere. It is **free** with no signup. The honest note: this produces fresh random keys for development and personal use. For production systems, follow your organization's key management policy, protect private keys with file permissions and consider RSA-4096 for long-lived credentials."
    ],
    faqs: [
      { q: "What key sizes are supported?", a: "RSA-2048 and RSA-4096. 2048 is the common default and still considered secure; 4096 is slower but stronger and preferred for long-lived keys." },
      { q: "What format are the exported keys?", a: "The private key is exported as PKCS#8 PEM and the public key as SPKI PEM. These are standard formats accepted by OpenSSL, SSH tools, JWT libraries and most servers." },
      { q: "Are my private keys sent to a server?", a: "No. Keys are generated inside your browser using the WebCrypto API and never leave your device. There is nothing to leak on our side because we never see the keys." },
      { q: "Is RSA-2048 still secure?", a: "Yes, RSA-2048 remains widely considered secure against classical attacks. Some organizations now prefer RSA-4096 for keys that must stay valid for many years." },
      { q: "Can I use these keys for SSH?", a: "The tool produces PEM keys; most SSH workflows want OpenSSH format. You can convert with ssh-keygen or OpenSSL, or generate OpenSSH keys directly for SSH and use these PEM keys for JWT, TLS and API signing." },
      { q: "What is the difference between PKCS#8 and PKCS#1?", a: "PKCS#8 is the modern container that wraps the private key and names its algorithm, while PKCS#1 holds only the raw RSA key material. This tool exports PKCS#8, which is accepted by virtually all modern software." }
    ],
    tags: [
      "rsa key generator",
      "generate rsa key pair",
      "rsa key generator online",
      "rsa 2048 key generator",
      "rsa 4096 key generator",
      "rsa private public key generator",
      "generate rsa keys in browser",
      "rsa key pair generator free",
      "pem key generator",
      "rsa pem generator",
      "pkcs8 private key generator",
      "spki public key generator",
      "rsa keygen online",
      "ssh key generator",
      "rsa key generator no server",
      "client side rsa generation",
      "webcrypto rsa keygen",
      "rsa public key from private key",
      "rsa key formats explained",
      "pem vs der",
      "pkcs8 vs pkcs1",
      "rsa key size 2048 vs 4096",
      "how to generate rsa key pair",
      "create rsa keys for ssh",
      "rsa key for jwt signing",
      "rsa encryption explained",
      "what is rsa key pair",
      "rsa key generator javascript",
      "generate ssh key online",
      "ssh-rsa key generator",
      "rsa key length calculator",
      "is rsa 2048 still secure",
      "how long is an rsa 2048 key",
      "rsa key fingerprint",
      "rsa private key example",
      "rsa public key example",
      "free rsa key generator no signup",
      "secure rsa key generator",
      "rsa keys for tls certificates",
      "rsa key generator for developers",
      "test rsa keys generator",
      "rsa key pair for api authentication",
      "generate keys without openssl",
      "rsa keygen browser tool",
      "private key generator online",
      "public key generator online",
      "rsa cryptography tool",
      "asymmetric key generator",
      "public key cryptography generator",
      "rsa key generator 2026",
      "best rsa key generator online"
    ],
  };

export default seo;
