import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SafeLink Decoder - Free Online URL Decoder Tool | IconVault",
    metaDescription: "Paste Outlook SafeLinks and get the real destination URL back. Batch-friendly and 100% in-browser, so nothing is uploaded. Free.",
    about: [
      "**IconVault**'s **SafeLink Decoder** unwraps **Microsoft Outlook SafeLinks** (those long `safelinks.protection.outlook.com` URLs) and reveals the **real destination URL** underneath. Paste one link or a whole batch, and the tool decodes the wrapped address instantly so you can see where a link actually goes before deciding what to do with it.",
      "Decoding runs **100% in your browser**: nothing is uploaded, nothing is clicked and no request is sent to the destination, so this is a **safe way to inspect suspicious links**. It is **free** with no signup. The honest note: decoding a link is not the same as verifying it is safe. A decoded URL can still point to a malicious site, so treat unknown links with care even after unwrapping them."
    ],
    faqs: [
      { q: "What is an Outlook SafeLink?", a: "SafeLinks is a Microsoft Defender feature that rewrites URLs in emails into long safelinks.protection.outlook.com addresses. The real destination is embedded inside, encoded in the URL parameters." },
      { q: "Is it safe to decode a suspicious link here?", a: "Yes, safer than clicking it. The tool only decodes the URL text locally in your browser and never sends a request to the destination, so no tracking pixel or malware is triggered." },
      { q: "Can I decode multiple links at once?", a: "Yes. Paste a batch of SafeLinks and the tool decodes each one, showing the real destination next to the original link." },
      { q: "What if the decoded value is not a valid URL?", a: "The tool tells you the decoded value is not a valid URL instead of guessing. That usually means the link was not a SafeLink or the wrapper was corrupted when pasted." },
      { q: "Does this remove the SafeLink protection?", a: "No, it only reveals the destination. Microsoft's click-time scanning still applies when you open the original SafeLink; decoding just lets you preview where it points." },
      { q: "Is anything I paste sent to a server?", a: "No. Decoding happens entirely in your browser. Your links are never uploaded, logged or shared." }
    ],
    tags: [
      "safelink decoder",
      "outlook safelink decoder",
      "decode safelink url",
      "safelinks protection outlook decoder",
      "unwrap safelink",
      "remove safelink wrapper",
      "get real url from safelink",
      "safelink url decoder online",
      "outlook link decoder",
      "microsoft safelinks decoder",
      "safelink checker",
      "what is a safelink",
      "why do outlook links look weird",
      "decode protected url",
      "unwrap outlook redirect",
      "safe links decoder free",
      "batch safelink decoder",
      "decode multiple safelinks",
      "safelink expander",
      "url unwrapper online",
      "outlook safe links remove",
      "safelink to original url",
      "extract destination url",
      "redirect url decoder",
      "tracking link decoder",
      "decode redirect chain",
      "email link decoder",
      "phishing link checker",
      "check where a link really goes",
      "see real destination of shortened url",
      "url redirect checker",
      "link expander online",
      "unwrap email links",
      "decode url online free",
      "percent encoded url decoder",
      "url decode tool",
      "decode url parameters",
      "safelink decoder no signup",
      "safelink decoder in browser",
      "private link decoder",
      "email security link decoder",
      "office 365 safelinks decode",
      "microsoft defender safelinks",
      "safelink url format explained",
      "how to copy real url from outlook",
      "outlook rewritten url decoder",
      "decode safelink without clicking",
      "safe way to check suspicious link",
      "outlook safe link preview",
      "url safety checker online",
      "free safelink decoder",
      "safelink decode tool"
    ],
  };

export default seo;
