import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Salary Calculator - Free Online Salary Calculator Tool | IconVault",
    metaDescription: "Turn an hourly wage into annual, monthly and weekly pay with overtime and an editable after-tax estimate. Planning estimates, free in-browser.",
    about: [
      "**IconVault**'s **Salary Calculator** converts an **hourly wage** into **annual, monthly and weekly pay**, and works in reverse too. Add **overtime hours** at your overtime rate and the calculator folds them into the totals. An **editable tax rate** produces a rough **after-tax estimate** so you can see take-home pay next to gross pay.",
      "Everything runs **100% in your browser**, so your pay details never leave the page. It is **free** with no signup. The honest note: this is a **planning estimate, not tax advice**. Real take-home pay depends on your tax bracket, filing status, deductions and benefits, so always confirm with official payroll or tax guidance before making decisions."
    ],
    faqs: [
      { q: "How do I convert hourly pay to annual salary?", a: "Enter your hourly rate and weekly hours. The tool multiplies them out to annual, monthly and weekly totals instantly. A common shortcut is hourly rate times 2,080 hours for a full-time year." },
      { q: "Can I include overtime?", a: "Yes. Enter your overtime hours and overtime rate (often 1.5 times your normal rate) and they are added to your gross pay totals." },
      { q: "How is the after-tax estimate calculated?", a: "The tool applies your editable tax rate to gross pay to estimate take-home. It is intentionally simple and adjustable, not a real tax computation." },
      { q: "Is this tax advice?", a: "No. It is a rough planning estimate only. Actual taxes depend on federal and state brackets, deductions, credits and benefits, so use official tools or a tax professional for anything binding." },
      { q: "Can it convert salary back to hourly?", a: "Yes. Enter an annual salary and the tool breaks it down into hourly, weekly and monthly equivalents based on the hours you enter." },
      { q: "Is my salary data sent anywhere?", a: "No. All calculations happen in your browser. Nothing is uploaded, stored or tracked." }
    ],
    tags: [
      "salary calculator",
      "hourly to salary calculator",
      "annual salary calculator",
      "paycheck calculator",
      "take home pay calculator",
      "net pay calculator",
      "gross to net salary calculator",
      "salary to hourly calculator",
      "monthly salary calculator",
      "weekly pay calculator",
      "overtime pay calculator",
      "salary calculator free online",
      "20 dollars an hour salary",
      "hourly wage calculator",
      "calculate annual income from hourly",
      "after tax salary calculator",
      "income tax calculator estimate",
      "salary breakdown calculator",
      "monthly to annual salary",
      "weekly to monthly pay calculator",
      "biweekly paycheck calculator",
      "salary per hour calculator",
      "what is my hourly rate",
      "salary raise calculator",
      "pay raise calculator",
      "new salary calculator",
      "salary comparison calculator",
      "job offer salary calculator",
      "negotiate salary calculator",
      "salary calculator with overtime",
      "overtime rate calculator",
      "time and a half calculator",
      "double time calculator",
      "freelance rate calculator",
      "hourly rate for freelancers",
      "contractor rate calculator",
      "salary to monthly conversion",
      "annual to monthly pay",
      "how much do i make a year",
      "how much do i make a month",
      "full time salary calculator",
      "part time pay calculator",
      "salary calculator 2026",
      "tax free salary calculator",
      "salary deductions calculator",
      "paycheck breakdown",
      "pay stub calculator",
      "salary estimator",
      "expected salary calculator",
      "salary calculator no signup",
      "salary calculator in browser"
    ],
  };

export default seo;
