import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Scientific Calculator - Free Online Scientific Calculator Tool | IconVault",
    metaDescription: "Trig, logs, powers, roots, factorials, constants, DEG/RAD mode and a history tape, all in your browser with keyboard support. Free.",
    about: [
      "**IconVault**'s **Scientific Calculator** is a full-featured calculator with **trigonometric functions** (sin, cos, tan and inverses), **logarithms** (log and natural log), **powers and roots**, **factorials**, **permutations and combinations**, and constants like **pi and e**. A **DEG/RAD toggle**, a scrollable **history tape** and full **keyboard support** make it genuinely usable for real work.",
      "Everything runs **100% in your browser**, so it works offline after loading and your calculations never leave the page. It is **free** with no signup. The honest note: it is a browser tool, not a certified exam calculator, so check your exam's rules before relying on it for a test. For homework, physics, chemistry and engineering, it is ready."
    ],
    faqs: [
      { q: "What functions does the scientific calculator have?", a: "Trigonometric and inverse trigonometric functions, logarithms (base 10 and natural), powers, square and nth roots, factorials, permutations, combinations, modulus, percentages and constants pi and e." },
      { q: "How do I switch between degrees and radians?", a: "Use the DEG/RAD toggle on the calculator. Trigonometric functions follow whichever mode is active, which is the most common source of wrong trig answers." },
      { q: "Can I use my keyboard?", a: "Yes. Digits, operators, parentheses and Enter all work from the keyboard, so you can type expressions naturally." },
      { q: "What is the history tape for?", a: "Every calculation is saved to a scrollable tape so you can review past results, spot mistakes and reuse values without retyping." },
      { q: "Can I use this for exams?", a: "Probably not. Most standardized exams restrict which calculators are allowed. This is ideal for homework, study and professional work, not proctored tests." },
      { q: "Is anything I calculate sent to a server?", a: "No. All math runs locally in your browser. Nothing is uploaded or tracked." }
    ],
    tags: [
      "scientific calculator",
      "scientific calculator online",
      "free scientific calculator",
      "online scientific calculator",
      "trig calculator",
      "trigonometry calculator online",
      "log calculator",
      "natural log calculator",
      "square root calculator",
      "power calculator",
      "exponent calculator",
      "factorial calculator",
      "sin cos tan calculator",
      "degrees to radians calculator",
      "deg rad calculator",
      "scientific calculator with history",
      "calculator with tape history",
      "keyboard scientific calculator",
      "pi calculator",
      "e constant calculator",
      "scientific notation calculator",
      "inverse trig calculator",
      "arcsin arccos arctan calculator",
      "hyperbolic functions calculator",
      "permutation calculator",
      "combination calculator",
      "modulus calculator",
      "percentage calculator scientific",
      "root calculator",
      "nth root calculator",
      "cube root calculator",
      "10x calculator",
      "antilog calculator",
      "scientific calculator for students",
      "calculator for physics",
      "calculator for chemistry",
      "engineering calculator online",
      "graphing calculator alternative",
      "ti 84 online alternative",
      "casio calculator online",
      "scientific calculator no download",
      "scientific calculator in browser",
      "mobile scientific calculator",
      "phone scientific calculator",
      "scientific calculator app free",
      "advanced calculator online",
      "math calculator online",
      "calculator with parentheses",
      "order of operations calculator",
      "scientific calculator 2026",
      "best free scientific calculator online",
      "solve scientific notation"
    ],
  };

export default seo;
