import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Screenshot Beautifier - Free Online Tool | IconVault",
    metaDescription: "Frame screenshots on beautiful gradients with padding, rounded corners, shadows and macOS chrome. Free PNG export.",
    about: [
      "**IconVault**'s **Screenshot Beautifier** turns plain screenshots into share-ready visuals: pick from ten **gradient backgrounds** (Sunset, Ocean, Dusk, Peach, Midnight, Mint, Candy, Lavender, Slate, Aurora), a solid color, or transparency, then tune **padding, corner radius and shadow**, and optionally add a **macOS window frame** with the classic traffic-light dots.",
      "Lock the canvas to **Auto, 16:9, 1:1 or 4:3**, preview everything live, and export a crisp **PNG at 1x or 2x**. Perfect for product launches, docs and social posts. Everything renders **in your browser**: your screenshots never leave your device. **Free** with a daily trial, unlimited with Pro.",
    ],
    faqs: [
      { q: "What backgrounds can I use?", a: "Ten curated gradients (Sunset, Ocean, Dusk, Peach, Midnight, Mint, Candy, Lavender, Slate, Aurora), any solid color from the color well, or a fully transparent background." },
      { q: "How does the macOS window frame work?", a: "It adds a title bar above your screenshot with the red, yellow and green traffic-light dots in light or dark chrome, giving that classic macOS window look seen in product screenshots." },
      { q: "What export sizes are available?", a: "Export PNG at 1x (the live preview resolution) or 2x for retina-sharp images on high-density displays." },
      { q: "Can I force a square or widescreen canvas?", a: "Yes. The aspect control offers Auto (follows your screenshot), 16:9, 1:1 and 4:3. Non-auto aspects center-crop the image to fill the frame." },
      { q: "Are my screenshots uploaded?", a: "No. The entire composition is drawn on canvas locally in your browser. Nothing leaves your device." },
      { q: "Is the screenshot beautifier free?", a: "Yes, with a daily free trial limit. IconVault Pro removes the limit for unlimited exports." },
    ],
    tags: [ "screenshot beautifier", "beautify screenshot online", "screenshot mockup generator", "gradient screenshot background", "screenshot frame generator", "macos screenshot frame", "pretty screenshot maker", "screenshot shadow effect", "product screenshot tool", "social media screenshot", "screenshot with background", "browser frame screenshot", "screenshot design tool", "shareable screenshot maker", "screenshot padding corners", "2x screenshot export", "app screenshot mockup", "docs screenshot styling", "free screenshot tool", "screenshot aesthetic" ,
      "screenshot maker",
      "beautiful screenshots",
      "screenshot styler",
      "fancy screenshot maker",
      "screenshot editor online",
      "code screenshot beautifier",
      "code snippet screenshot",
      "carbon alternative screenshot",
      "tweet screenshot maker",
      "chat screenshot maker",
      "whatsapp chat screenshot mockup",
      "iphone frame screenshot",
      "android frame screenshot",
      "phone mockup screenshot",
      "laptop frame screenshot",
      "desktop mockup screenshot",
      "website screenshot mockup",
      "saas screenshot tool",
      "app store screenshot maker",
      "landing page screenshot frame",
      "product hunt screenshot",
      "twitter card screenshot",
      "linkedin post screenshot",
      "blog screenshot styling",
      "tutorial screenshot maker",
      "documentation screenshot tool",
      "screenshot with rounded corners",
      "screenshot drop shadow",
      "gradient background screenshot",
      "pastel screenshot background",
      "dark mode screenshot frame",
      "clean screenshot maker",
      "annotate screenshot online",
      "screenshot arrow annotation",
      "blur part of screenshot",
      "screenshot to png hd",
      "4k screenshot export",
      "screenshot template maker",
      "mockup generator online",
      "device frame generator"],
  };

export default seo;
