import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Screen Orientation Playground - Free Online Tool | IconVault",
    metaDescription: "Learn the Screen Orientation API: live type and angle, a device mirror, lock() and unlock() demos with honest errors. Free, in your browser.",
    about: [
      "**IconVault**'s **Screen Orientation Playground** reads your real screen.orientation and mirrors it: the type (portrait-primary, landscape-secondary, and friends) and angle update live as you rotate your device, and an animated phone mock follows along. Buttons demo lock() for all eight orientation values and unlock(), with the genuine success or rejection shown, and a fullscreen toggle is included because most browsers only allow locking from fullscreen. It is free and runs fully in your browser.",
      "Screen orientation matters for games, video, and kiosk apps, but the API contract has teeth: **lock()** returns a promise that **rejects on desktop**, on non-fullscreen pages, and where the platform forbids it. This lab reports those real outcomes instead of faking a lock, so you learn the exact conditions under which orientation locking works, and ships a copyable pattern with the **try/catch** you will need in production."
    ],
    faqs: [
      { q: "What is the Screen Orientation API?", a: "A browser API exposing screen.orientation with a type (like landscape-primary) and an angle (0, 90, 180, 270), change events, and lock()/unlock() methods to request a fixed orientation." },
      { q: "What do portrait-primary and landscape-secondary mean?", a: "The four combos of portrait/landscape with primary/secondary. Primary is the device's natural rotation direction; secondary is the 180-degree flip of it." },
      { q: "Why does lock() fail on desktop?", a: "Chrome and most browsers only honor orientation lock from fullscreen or on mobile devices. On a normal desktop tab the promise rejects, which the lab demonstrates and explains honestly." },
      { q: "How do I listen for orientation changes?", a: "screen.orientation.addEventListener('change', ...) fires whenever the type or angle changes. The lab's live readouts and phone mock are driven by exactly this listener." },
      { q: "Is screen.orientation.angle the same as deviceorientation?", a: "No. screen.orientation describes the screen's rotation (0/90/180/270). DeviceOrientationEvent describes the physical device tilt in 3D space. Different APIs for different questions." },
      { q: "Can I lock orientation in a PWA?", a: "Installed PWAs can also declare orientation in the web app manifest (\"orientation\": \"landscape\"), which is the more reliable route than lock() on mobile." }
    ],
    tags: [
      "screen orientation api",
      "screen orientation tutorial",
      "screen orientation javascript",
      "screen.orientation",
      "screen orientation lock",
      "screen.orientation.lock",
      "screen orientation unlock",
      "screen.orientation.unlock",
      "orientation type angle",
      "landscape-primary",
      "portrait-primary",
      "landscape-secondary",
      "portrait-secondary",
      "orientation lock web",
      "lock screen orientation website",
      "screen orientation change event",
      "orientationchange",
      "how to lock orientation js",
      "screen orientation demo",
      "screen orientation playground",
      "screen orientation mdn",
      "screen orientation browser support",
      "screen orientation chrome",
      "screen orientation safari",
      "screen orientation ios",
      "screen orientation android",
      "orientation lock fullscreen",
      "lock orientation fullscreen required",
      "pwa orientation manifest",
      "web app manifest orientation",
      "detect screen rotation javascript",
      "get screen orientation js",
      "portrait vs landscape detection",
      "responsive orientation web",
      "game orientation lock",
      "video fullscreen orientation",
      "screen orientation typescript",
      "screen orientation react",
      "learn screen orientation api",
      "interactive orientation demo",
      "device rotation web",
      "screen angle 90 270",
      "orientation lock not working",
      "screen.orientation not supported",
      "mobile web orientation",
      "tablet orientation api",
      "kiosk orientation lock",
      "screen orientation code sample",
      "web orientation api",
      "screen rotation javascript",
      "orientation media query vs api"
    ],
  };

export default seo;
