import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Screen Capture Playground - Free Online Tool | IconVault",
    metaDescription: "Learn getDisplayMedia: share your screen with surface selection, inspect real track settings, and download PNG snapshots. Free, in your browser.",
    about: [
      "**IconVault**'s **Screen Capture Playground** teaches getDisplayMedia with the real thing. Press Share screen and your browser's native picker appears; you can hint the surface preference (monitor, window, or tab) and toggle system audio. The live preview streams your chosen surface, a settings panel shows the actual track values (displaySurface, logicalSurface, resolution, frame rate, cursor mode), and one click captures a full-resolution PNG snapshot you can download. It is free and runs fully in your browser.",
      "Screen capture powers everything from meeting apps to bug-report recorders, but the API surface has real subtleties: the **surface hint** is only a hint, **track settings** reveal what the user actually shared, and the **ended event** fires when they stop from the browser chrome. This lab surfaces all of it, handles the cancel case gracefully, and keeps everything local so your screen never leaves the device."
    ],
    faqs: [
      { q: "What is getDisplayMedia?", a: "The browser API for capturing the screen, a window, or a tab as a live MediaStream. It opens the OS-level share picker; the user always chooses what to share, and the page receives video (and optionally audio) tracks." },
      { q: "Why does it need HTTPS?", a: "getDisplayMedia is restricted to secure contexts. On plain HTTP the API is unavailable; localhost counts as secure for local development." },
      { q: "What does the surface preference do?", a: "The displaySurface constraint hints which tab of the picker to pre-select (monitor, window, or browser tab), but the user always makes the final choice. It is a hint, not a command." },
      { q: "What is displaySurface vs logicalSurface?", a: "displaySurface is what the user picked (monitor, window, or browser). logicalSurface is what the browser actually captured, which can differ, for example when a window is minimized or occluded." },
      { q: "How do I detect when the user stops sharing?", a: "Listen for the ended event on the video track. The lab wires this up and shows a toast when you press the browser's Stop sharing control." },
      { q: "Is my screen uploaded anywhere?", a: "No. Capture and snapshots happen entirely in your tab. Snapshots are encoded to PNG locally and downloaded to your device; nothing is transmitted." }
    ],
    tags: [
      "getdisplaymedia",
      "getdisplaymedia tutorial",
      "getdisplaymedia example",
      "screen capture api",
      "screen capture javascript",
      "screen sharing web",
      "navigator.mediadevices.getdisplaymedia",
      "screen capture demo",
      "screen capture playground",
      "how to capture screen javascript",
      "getdisplaymedia constraints",
      "displaysurface",
      "logicalsurface",
      "getdisplaymedia monitor window tab",
      "screen capture track settings",
      "getsettings displaysurface",
      "screen share web app",
      "browser screen recorder",
      "screen capture snapshot",
      "capture screenshot of screen js",
      "getdisplaymedia audio",
      "share system audio browser",
      "getdisplaymedia cursor",
      "screen capture cursor mode",
      "getdisplaymedia frame rate",
      "track ended event",
      "stop screen sharing",
      "getdisplaymedia not working",
      "getdisplaymedia permission",
      "getdisplaymedia https",
      "getdisplaymedia browser support",
      "getdisplaymedia safari",
      "getdisplaymedia firefox",
      "getdisplaymedia chrome",
      "getdisplaymedia mdn",
      "getdisplaymedia typescript",
      "getdisplaymedia react",
      "screen capture web development",
      "learn getdisplaymedia",
      "interactive screen capture",
      "screen share picker",
      "mediastream screen",
      "video track settings",
      "getvideotracks",
      "screen recording web api",
      "webrtc screen share",
      "getdisplaymedia vs getusermedia",
      "tab capture api",
      "window capture web",
      "screen capture png download",
      "local screen capture"
    ],
  };

export default seo;
