import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Scroll Animations - Free Online Scroll Animation CSS Generator Tool | IconVault",
    metaDescription: "Build scroll-triggered CSS animations (fade, slide, zoom, parallax) with copy-paste keyframes and IntersectionObserver code. Free.",
    about: [
      "**IconVault**'s **Scroll Animations** tool generates **scroll-triggered CSS animations** you can drop into any website. Pick a preset like **fade in**, **slide up**, **slide from left**, **scale up** or **parallax drift**, preview it live, then copy the **CSS keyframes** and the small **IntersectionObserver** snippet that fires the animation when the element scrolls into view.",
      "The generated code is **framework-free vanilla CSS and JavaScript**, so it works in plain HTML, React, or any site builder, and it is **free** with no signup. The honest note: animation presets are starting points, not finished design. Tune duration, easing and distance to match your site, and keep `prefers-reduced-motion` in mind so motion-sensitive visitors get a calm experience."
    ],
    faqs: [
      { q: "How do scroll-triggered animations work?", a: "An IntersectionObserver watches your element and adds a CSS class when it enters the viewport. That class starts a keyframe animation such as fade-in or slide-up." },
      { q: "Do I need a library like AOS?", a: "No. The tool generates plain CSS plus a tiny vanilla JavaScript snippet, so you get the effect with zero dependencies." },
      { q: "What animation presets are included?", a: "Fade in, slide up, slide from left, scale up and parallax drift, each with adjustable timing you can tune before copying." },
      { q: "Will this slow down my website?", a: "Not meaningfully if used sensibly. The animations use transform and opacity, which browsers render on the GPU, and IntersectionObserver is cheap. Animating hundreds of elements at once is the thing to avoid." },
      { q: "Are the animations accessible?", a: "They are a starting point. Pair them with a prefers-reduced-motion media query that disables motion for users who ask for it, which is the standard accessibility practice." },
      { q: "Can I use the code in React or a site builder?", a: "Yes. The CSS is universal, and the IntersectionObserver snippet can go in a useEffect or any script tag. Paste the keyframes into your stylesheet or style block." }
    ],
    tags: [
      "scroll animations",
      "scroll animation css",
      "css scroll animations",
      "scroll reveal animation",
      "on scroll animation css",
      "scroll triggered animations",
      "fade in on scroll css",
      "slide up on scroll",
      "scroll animation generator",
      "css animation generator",
      "scroll reveal generator",
      "intersection observer animation",
      "intersectionobserver example",
      "animate on scroll javascript",
      "aos alternative",
      "scroll animation library",
      "vanilla js scroll animation",
      "no library scroll animations",
      "scroll fade in effect",
      "parallax scroll effect",
      "parallax css generator",
      "scroll zoom effect",
      "reveal on scroll tutorial",
      "how to animate elements on scroll",
      "scroll animations for website",
      "landing page scroll animations",
      "scroll animation presets",
      "copy paste scroll animations",
      "css keyframes scroll",
      "scroll based animations web",
      "web design scroll effects",
      "modern website scroll animations",
      "smooth scroll reveal",
      "scroll animation snippets",
      "css scroll animations examples",
      "scroll animation code generator free",
      "frontend scroll effects",
      "website animation on scroll",
      "scroll slide in animation css",
      "scroll scale up animation",
      "scroll rotate animation",
      "staggered scroll animation",
      "scroll animation timing",
      "prefers reduced motion scroll",
      "accessible scroll animations",
      "performant scroll animations",
      "gpu friendly scroll animations",
      "scroll animations without jquery",
      "scroll animation css only",
      "scroll driven animations css",
      "css scroll timeline",
      "view transitions scroll"
    ],
  };

export default seo;
