import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Security Headers - Free Online HTTP Security Header Generator Tool | IconVault",
    metaDescription: "Generate copy-paste HTTP security headers for nginx, Apache and more: CSP, HSTS, X-Frame-Options and friends. Free, in your browser.",
    about: [
      "**IconVault**'s **Security Headers** tool generates ready-to-paste **HTTP security header** configurations for your server. It covers **Content-Security-Policy**, **Strict-Transport-Security (HSTS)**, **X-Frame-Options**, **X-Content-Type-Options**, **Referrer-Policy**, **Permissions-Policy** and **Cross-Origin** policies, with output formatted for **nginx** and **Apache** (plus plain header text you can adapt anywhere).",
      "Generation runs **100% in your browser** and it is **free** with no signup. The honest note: this tool writes the config, it does not scan your site. A strict Content-Security-Policy can break scripts, styles or embeds, so test on staging first and confirm with a real header scanner before calling it done."
    ],
    faqs: [
      { q: "What are HTTP security headers?", a: "They are response headers that tell browsers how to behave: enforcing HTTPS, blocking clickjacking, restricting scripts and controlling referrers. They are a free, high-value layer of web security." },
      { q: "Which headers should every site have?", a: "At minimum: Strict-Transport-Security, X-Content-Type-Options, Referrer-Policy and a frame-ancestors rule or X-Frame-Options. Content-Security-Policy is the most powerful and the one most worth configuring carefully." },
      { q: "Does the tool support nginx and Apache?", a: "Yes. It outputs nginx add_header blocks and Apache Header directives, plus plain header text you can adapt to Caddy, Cloudflare, Vercel, Netlify or application middleware." },
      { q: "Will a Content-Security-Policy break my site?", a: "It can, if your site loads scripts, styles, fonts or embeds from sources the policy does not allow. Start in report-only mode or test on staging, then tighten." },
      { q: "What is HSTS?", a: "HTTP Strict Transport Security tells browsers to only ever use HTTPS for your domain, defeating SSL-stripping attacks. Enable it only when HTTPS works everywhere on the domain." },
      { q: "Is generating headers enough to secure my site?", a: "No, it is one layer. Keep software patched, use HTTPS, validate input and scan your live site with a header checker to confirm the headers are actually served." }
    ],
    tags: [
      "security headers",
      "http security headers",
      "security headers generator",
      "generate security headers",
      "content security policy generator",
      "csp generator",
      "strict transport security header",
      "hsts header generator",
      "x frame options header",
      "clickjacking protection header",
      "x content type options",
      "referrer policy header",
      "permissions policy header",
      "cross origin opener policy",
      "cross origin embedder policy",
      "nginx security headers",
      "apache security headers",
      "security headers for nginx",
      "security headers for apache",
      "htaccess security headers",
      "cloudflare security headers",
      "security headers checker",
      "test website security headers",
      "securityheaders.com alternative",
      "website security headers test",
      "http headers best practices",
      "secure http headers list",
      "owasp secure headers",
      "owasp http headers cheat sheet",
      "web security headers explained",
      "what are security headers",
      "which security headers should i use",
      "security headers for next.js",
      "nextjs security headers config",
      "security headers for wordpress",
      "wordpress security headers plugin alternative",
      "security headers vercel",
      "netlify security headers",
      "express security headers",
      "helmet js alternative",
      "node js security headers",
      "security headers copy paste config",
      "free security headers tool",
      "security headers in browser",
      "generate csp header online",
      "csp nonce vs hash",
      "frame ancestors directive",
      "xss protection headers",
      "prevent mime sniffing header",
      "ssl hsts preload",
      "security headers 2026",
      "modern security headers guide"
    ],
  };

export default seo;
