import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Semver Calculator - Free Online Semantic Versioning Calculator Tool | IconVault",
    metaDescription: "Parse versions, bump major/minor/patch/prerelease, test semver ranges and compare versions. A hand-written engine, 100% client-side.",
    about: [
      "**IconVault**'s **Semver Calculator** is built on a **hand-written semver engine** (no npm semver package) that runs **100% client-side**. It **parses versions**, **bumps major, minor, patch and prerelease** numbers, **tests version ranges** (`^`, `~`, `>=`, `<=`, `>`, `<`, `=`) and **compares two versions**, so you can answer questions like whether `1.2.3` satisfies `^1.0.0` before you publish.",
      "It is **free** with no signup, and everything happens in your browser. The honest note: this implements the widely used npm-style semver conventions. If your ecosystem versions differently (some do), treat the results as a guide and check your package manager's own rules."
    ],
    faqs: [
      { q: "What is semantic versioning?", a: "A versioning scheme of MAJOR.MINOR.PATCH where major means breaking changes, minor means new backwards-compatible features and patch means backwards-compatible fixes. Prerelease tags like 1.0.0-beta.1 mark early releases." },
      { q: "What is the difference between ^ and ~ in ranges?", a: "Caret (^1.2.3) allows changes that do not modify the leftmost non-zero digit, so ^1.2.3 covers 1.x.x. Tilde (~1.2.3) is stricter, allowing only patch-level changes within 1.2.x." },
      { q: "Does 1.2.3 satisfy ^1.0.0?", a: "Yes. Test it directly in the tool's range checker: enter the version and the range and it tells you whether it satisfies, with the rule explained." },
      { q: "How do prerelease versions work?", a: "A version with a prerelease tag (1.0.0-alpha) is considered older than the same version without one. Prereleases only satisfy ranges that explicitly include prerelease versions." },
      { q: "When should I bump major vs minor vs patch?", a: "Bump major for breaking API changes, minor for new backwards-compatible features and patch for bug fixes. Tools like release-please and changesets automate this from your commits." },
      { q: "Is this the same as npm's semver package?", a: "It is an independent hand-written implementation of the same conventions, so results match npm behavior for standard cases. Nothing is sent to npm or any registry." }
    ],
    tags: [
      "semver calculator",
      "semantic versioning calculator",
      "semver version bump",
      "npm version bump calculator",
      "major minor patch calculator",
      "semver range tester",
      "npm semver range checker",
      "caret vs tilde npm",
      "semver compare versions",
      "version comparison tool",
      "semver parser online",
      "parse semantic version",
      "bump major minor patch",
      "npm version major minor patch",
      "prerelease version calculator",
      "semver prerelease explained",
      "alpha beta rc versioning",
      "what is semantic versioning",
      "semver explained",
      "semver cheat sheet",
      "semver rules",
      "semver 2.0.0 spec",
      "npm versioning guide",
      "package version calculator",
      "does 1.2.3 satisfy caret range 1.0.0",
      "semver satisfies calculator",
      "test npm version range",
      "version range syntax npm",
      "greater than equal semver range",
      "semver wildcard x range",
      "hyphen ranges semver",
      "semver comparator tool",
      "compare two versions online",
      "which version is newer",
      "sort versions semver",
      "release version calculator",
      "next release version",
      "conventional commits version bump",
      "release please versioning",
      "changesets version bump",
      "github release versioning",
      "docker tag versioning",
      "api versioning semver",
      "semver for developers",
      "free semver tool online",
      "semver calculator no signup",
      "semver in browser",
      "semver version validator",
      "is this a valid semver",
      "semver regex",
      "build metadata semver",
      "0.x versioning rules"
    ],
  };

export default seo;
