import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SERP Preview Tool - Free Google Preview | IconVault",
    metaDescription:
      "Preview your Google search result free: title, URL and meta description with pixel-width truncation checks for desktop and mobile.",
    about: [
      "**IconVault**'s **SERP Preview** shows exactly how your page will look in **Google search results**: type your **title**, URL and **meta description** and see a pixel-accurate **desktop and mobile preview** with live **truncation warnings** when your title exceeds ~580px or description ~990px.",
      "It also previews rich-result eligibility hints and favicon display. Tune until nothing gets cut off, then copy your tags. Free, no account, all in your browser.",
    ],
    faqs: [
      {
        q: "How long can a Google title be?",
        a: "Google truncates by pixel width, not characters - roughly 580px on desktop (about 50-60 characters). The preview measures your actual title width and warns before it gets cut.",
      },
      {
        q: "How long should the meta description be?",
        a: "Around 150-160 characters / ~990px on desktop, shorter on mobile. Longer descriptions get truncated with an ellipsis.",
      },
      {
        q: "Why does mobile preview matter?",
        a: "Most searches happen on mobile, where titles and descriptions truncate earlier. The tool shows both so you optimize for the smaller screen.",
      },
      {
        q: "Does Google always use my meta description?",
        a: "No - Google rewrites descriptions ~60% of the time to match the query. A good description still improves click-through when it is shown.",
      },
    ],
    tags: [
      "serp preview", "google serp preview tool", "search result preview",
      "meta title preview", "serp simulator", "google preview tool free",
      "title tag checker", "meta description preview", "serp snippet optimizer",
      "google result simulator", "seo preview tool", "search snippet preview",
    
      "google search preview",
      "serp snippet preview",
      "search preview tool",
      "google result preview",
      "preview google listing",
      "serp preview tool free",
      "google title preview",
      "meta title length checker",
      "meta description length checker",
      "google snippet checker",
      "serp checker",
      "google search result simulator",
      "preview search result",
      "seo title checker",
      "seo description checker",
      "google listing preview",
      "serp pixel width checker",
      "title tag length checker",
      "description tag length",
      "google preview generator",
      "search engine preview",
      "serp emulator",
      "rich snippet preview",
      "google rich result preview",
      "mobile serp preview",
      "desktop serp preview",
      "google search simulator",
      "see how page looks on google",
      "google title tag preview",
      "meta title description preview",
      "free serp preview",
      "serp preview online",
      "google snippet preview tool",
      "optimize google snippet",
      "click through rate optimizer",
      "ctr optimizer",
      "google result checker",
      "serp title checker",
      "search snippet tester",
      "preview meta tags google",
      "google search page preview",
      "how my page looks on google",
      "test google search result",
      "serp snippet generator",
      "google preview checker",
      "seo snippet preview tool",
      "search result tester",
      "free google preview tool"],
  };

export default seo;
