import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Signature Resizer - Free Online Tool | IconVault",
    metaDescription: "Resize your signature to exact exam portal dimensions (IBPS, SSC, NEET, UPSC) with a 10 or 20 KB file limit. Free and browser-private.",
    about: [
      "**IconVault**'s **Signature Resizer** prepares your signature for Indian exam and government form portals in one click. Pick a preset (**140 x 60 for IBPS/SBI, 315 x 157 for SSC, 350 x 150 for NEET/JEE, 700 x 350 for UPSC**) or enter custom dimensions, set a **10 KB, 20 KB, or custom file size cap**, and download a crisp JPG. It is **free**, runs entirely in your **browser**, and your files never leave your device.",
      "The built-in **background cleaner** turns scanned paper pure white while keeping dark ink, the **ink darkness slider** fine-tunes what counts as ink, and the tool trims the edges and centers your signature on the canvas. **Pro** members get unlimited resizes; free users get a trial quota.",
    ],
    faqs: [
      { q: "What signature size does IBPS need?", a: "IBPS and SBI typically ask for a 140 x 60 px signature between 10 and 20 KB. This tool has that exact preset built in." },
      { q: "What signature size does SSC need?", a: "SSC forms usually ask for a 4 x 2 cm signature, which is 315 x 157 px at 200 DPI, typically 10 to 20 KB. Use the SSC preset." },
      { q: "How do I clean a scanned signature background?", a: "Keep Clean background turned on. The tool whitens the paper to pure white and keeps only the ink. Adjust the Ink darkness slider if your pen was light." },
      { q: "Can I set a custom file size limit?", a: "Yes. Choose 10 KB, 20 KB, or Custom and enter any KB value. The tool compresses the signature to fit inside your cap." },
      { q: "Is my signature uploaded to a server?", a: "No. The whole resize happens in your browser. Nothing is uploaded, stored, or shared." },
      { q: "What is the ink darkness slider?", a: "It controls how light a pixel can be before it is treated as paper and whitened. Lower values keep only dark ink; higher values also keep light pencil strokes." },
    ],
    tags: ["signature resizer", "resize signature online", "signature size reducer kb", "ibps signature size 140x60", "sbi signature 140 x 60", "ssc signature size 4x2cm", "neet signature 350 x 150", "upsc signature 700x350", "signature 20 kb", "signature 10 kb", "signature photo compressor kb", "clean signature background white", "scanned signature cleaner", "exam signature maker", "free signature resizer", "signature jpg resizer", "neet signature size", "jee signature size", "online signature size reducer", "government form signature",
      "signature maker",
      "resize signature image",
      "signature compressor",
      "compress signature to 10kb",
      "compress signature to 30kb",
      "signature kb reducer",
      "signature size converter",
      "ibps clerk signature size",
      "ibps rrb signature size",
      "sbi clerk signature 140x60",
      "sbi po signature size",
      "ssc cgl signature size",
      "ssc chsl signature size",
      "ssc gd signature size",
      "upsc cse signature size",
      "neet ug signature size",
      "jee main signature size",
      "gate signature size",
      "railway signature size rrb",
      "ctet signature size",
      "signature dimensions for exam",
      "signature 140x60 maker",
      "signature 350x150 maker",
      "signature 4x2 cm maker",
      "white background signature maker",
      "transparent signature maker",
      "clean scanned signature",
      "remove lines from signature scan",
      "darken signature scan",
      "signature to jpg converter",
      "handwritten signature resizer",
      "digital signature image resizer",
      "signature photo size tool",
      "signature file size reducer",
      "signature under 20kb",
      "signature under 50kb",
      "exam signature photo tool",
      "online signature editor",
      "signature cropper online",
      "signature resizer no signup"],
  };

export default seo;
