import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Slug Generator - Free URL Slug Maker | IconVault",
    metaDescription:
      "Convert headlines to clean URL slugs free. Lowercase, hyphenated, stop-word removal and bulk mode. Copy-paste ready.",
    about: [
      "**IconVault**'s **Slug Generator** turns messy **headlines** into clean **URL slugs**: lowercases everything, strips accents and special characters, joins words with hyphens, and can drop **stop words** for shorter URLs. Paste a whole list for **bulk** slug generation.",
      "Slugs are generated live as you type with duplicate detection for lists. Everything runs in your browser - free, no account needed.",
    ],
    faqs: [
      {
        q: "What is a URL slug?",
        a: "The readable part of a URL after the domain - e.g. /blog/best-fonts-2026. Good slugs are short, lowercase, hyphenated and describe the page.",
      },
      {
        q: "Should I remove stop words from slugs?",
        a: "Shorter slugs are generally better, but keep words that carry meaning. The generator offers optional stop-word removal - use it for long headlines, skip it when every word matters.",
      },
      {
        q: "How does bulk mode work?",
        a: "Paste one headline per line and get one slug per line back, with automatic -2, -3 suffixes for duplicates so every slug stays unique.",
      },
      {
        q: "Are accents and unicode handled?",
        a: "Yes - characters are transliterated (e.g. cafe from café) so slugs stay ASCII-safe and work everywhere.",
      },
    ],
    tags: [
      "slug generator", "url slug generator", "slug maker", "url slug creator free",
      "headline to slug", "permalink generator", "clean url generator",
      "slugify online", "bulk slug generator", "wordpress slug generator",
      "seo friendly url generator", "url slugify", "free slug tool",
    
      "url slug maker",
      "create url slug",
      "title to slug converter",
      "blog post slug generator",
      "seo slug generator",
      "slug creator",
      "online slug generator",
      "slugify text",
      "convert title to url",
      "post title to slug",
      "slug maker online",
      "generate permalink",
      "url friendly title",
      "create clean url",
      "headline to url converter",
      "page title to slug",
      "slug generator free online",
      "bulk url slug maker",
      "multiple slugs generator",
      "wordpress permalink generator",
      "blogger slug generator",
      "slugify string",
      "text to slug online",
      "url slug formatter",
      "seo url maker",
      "pretty url generator",
      "clean permalink maker",
      "slug builder",
      "generate seo slug",
      "blog slug creator",
      "article slug generator",
      "title to permalink",
      "url slug tool free",
      "convert text to slug",
      "dash separated url",
      "lowercase url generator",
      "remove special characters url",
      "slugify title",
      "free url slug tool",
      "slug checker",
      "duplicate slug finder",
      "shopify slug generator",
      "next.js slug generator",
      "youtube video slug",
      "slug generator no signup",
      "online permalink maker",
      "url slug generator free"],
  };

export default seo;
