import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Smart Paste - Free Online Paste Format Detector Tool | IconVault",
    metaDescription: "Paste JWT, JSON, SQL, URLs, Base64, CSV or Markdown. Smart Paste auto-detects the format, shows a preview and opens the right tool. Free, in-browser.",
    about: [
      "**IconVault**'s **Smart Paste** figures out what you just pasted. Drop in a **JWT**, some **JSON**, a **SQL** query, a **URL**, a chunk of **Base64**, **CSV** rows or **Markdown** and it instantly **detects the format**, shows a smart preview (decoded claims, formatted JSON, URL parts, decoded text, row preview) and points you at the **right IconVault tool** with one click.",
      "Everything happens **100% in your browser**: your paste is never uploaded, logged or stored, so it is safe for tokens and private data. It is **free** to use. Detection is heuristic, so unusual edge cases may fall back to plain text, and IconVault does not have a dedicated XML formatter yet, in which case the raw text is shown."
    ],
    faqs: [
      { q: "What formats does Smart Paste detect?", a: "JWT tokens, JSON, XML/HTML markup, SQL statements, URLs, Base64 blobs, CSV rows and Markdown. Anything else is shown as plain text. A live hint above the paste box guesses the type as you type, without using a trial." },
      { q: "What does it show for a JWT?", a: "It decodes the base64url header and payload and displays the claims as formatted JSON. It does not verify the signature and never sends the token anywhere, so it is safe to paste private tokens." },
      { q: "Can I jump to the right tool from here?", a: "Yes. When the detected format has a dedicated IconVault tool, such as the JSON Formatter, JWT Decoder, URL Encoder, Base64 tool or Markdown Preview, a button opens it directly so you can keep working." },
      { q: "Is my pasted data sent to a server?", a: "No. Detection, decoding and previews all run locally in your browser. Nothing you paste leaves your device, which is why the tool can safely handle secrets like JWTs." },
      { q: "What happens with CSV or Base64 data?", a: "CSV shows the first rows as a numbered row preview, and Base64 is decoded and shown as text when it is printable, or labeled binary data when it is not. The character count is shown as a hint." },
      { q: "Why did it detect plain text instead of my format?", a: "Detection uses patterns, not magic. Very short strings, malformed JSON, or markup without a standard doctype can fall through to plain text. Paste more of the document or open the matching formatter manually." }
    ],
    tags: [
      "paste detector",
      "smart paste",
      "detect paste format",
      "what did i paste",
      "identify pasted text",
      "paste format identifier online",
      "jwt json detector",
      "detect if text is json",
      "is this base64",
      "detect base64 string online",
      "jwt paste decoder",
      "paste jwt token decode",
      "decode jwt online free",
      "jwt decoder paste",
      "paste json formatter",
      "detect json format online",
      "json or xml detector",
      "paste sql highlighter",
      "detect sql query from text",
      "url detector online",
      "paste url analyzer",
      "csv detector online",
      "detect csv format",
      "paste markdown preview",
      "markdown detector",
      "paste anything analyzer",
      "clipboard content detector",
      "what format is this text",
      "identify text format online",
      "text type detector",
      "paste and detect",
      "online paste inspector",
      "free paste analyzer",
      "paste decoder tool",
      "jwt vs json detector",
      "base64 or plain text check",
      "check if string is base64",
      "validate base64 online",
      "decode base64 paste",
      "json validator paste",
      "check if json is valid online",
      "sql keyword highlighter online",
      "detect xml markup online",
      "paste url parts",
      "split url into parts online",
      "markdown to preview paste",
      "csv row preview online",
      "paste token inspector",
      "developer paste tool",
      "programmer clipboard helper",
      "free online paste tool",
      "no signup paste detector"
    ],
  };

export default seo;
