import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Smoothie Macros - Free Online Smoothie Nutrition Calculator | IconVault",
    metaDescription: "Build a smoothie from real ingredients and get calories, protein, carbs and fat instantly. Free nutrition calculator that runs fully in your browser.",
    about: [
      "**IconVault**'s **Smoothie Macros** turns your blender ideas into numbers. Pick from **27 real ingredients** across fruits, liquids, protein foods and extras, set the **grams** for each, and get instant totals for **calories**, **protein**, **carbs** and **fat**, with a calorie-share bar for each macro and a per-ingredient breakdown.",
      "Everything runs **100% in your browser** and it is **free**, with a one-click recipe copy you can save or share. Values are approximate per-100g averages, so treat them as guidance: real brands vary, especially **protein powders**, and this is not medical nutrition advice."
    ],
    faqs: [
      { q: "How do I build my smoothie?", a: "Choose ingredients from the dropdowns, set the amount in grams for each row, add more rows with the Add button, and the totals update instantly on the right. Copy recipe copies the full recipe and totals to your clipboard." },
      { q: "Where do the nutrition numbers come from?", a: "Each ingredient carries approximate per-100 gram values for calories, protein, carbs and fat based on standard USDA-style averages. Your totals scale linearly with the grams you enter." },
      { q: "How accurate is the calorie count?", a: "Good as a ballpark, not lab-grade. Fresh produce varies by ripeness and brand, and protein powders differ a lot between products. For strict dieting, cross-check with the nutrition label on your exact product." },
      { q: "Can I save or share my recipe?", a: "Yes. Copy recipe writes a clean text recipe with every ingredient and amount plus the total macros to your clipboard, ready to paste into notes, a message or a fitness app." },
      { q: "Is my data sent anywhere?", a: "No. The calculator runs entirely in your browser. Your recipes are never uploaded or stored." },
      { q: "Is this medical or diet advice?", a: "No. This is a convenience calculator for smoothie building. If you have health conditions, allergies or strict dietary requirements, talk to a qualified dietitian." }
    ],
    tags: [
      "smoothie macro calculator",
      "smoothie calories calculator",
      "smoothie nutrition calculator",
      "calculate smoothie calories",
      "how many calories in my smoothie",
      "smoothie protein calculator",
      "smoothie carbs and fat calculator",
      "build a smoothie online",
      "smoothie builder app",
      "smoothie recipe calculator",
      "smoothie ingredient calculator",
      "banana smoothie calories",
      "peanut butter smoothie calories",
      "protein smoothie macro calculator",
      "whey protein smoothie calories",
      "greek yogurt smoothie calories",
      "oats smoothie nutrition",
      "chia seed smoothie calories",
      "avocado smoothie calories",
      "mango smoothie calories",
      "berry smoothie calories",
      "green smoothie calories",
      "spinach smoothie nutrition",
      "kale smoothie calories",
      "almond milk smoothie calories",
      "coconut water smoothie calories",
      "honey smoothie calories",
      "cocoa smoothie calories",
      "flaxseed smoothie nutrition",
      "macro calculator for smoothies",
      "smoothie macro tracker",
      "smoothie nutrition facts calculator",
      "calculate macros per smoothie",
      "smoothie serving calories",
      "how much protein in a smoothie",
      "low calorie smoothie calculator",
      "high protein smoothie calculator",
      "weight loss smoothie calories",
      "meal replacement smoothie macros",
      "pre workout smoothie calories",
      "post workout smoothie macros",
      "free smoothie calculator online",
      "smoothie nutrition calculator free",
      "smoothie recipe nutrition calculator",
      "healthy smoothie builder",
      "custom smoothie nutrition",
      "smoothie calorie counter",
      "count calories in homemade smoothie",
      "smoothie diet calculator",
      "fitness smoothie calculator"
    ],
  };

export default seo;
