import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Social Media Resizer - Free Online Tool | IconVault",
    metaDescription: "Resize one photo for every platform free in your browser: Instagram, YouTube, X, LinkedIn, Facebook, Pinterest.",
    about: [
      "**IconVault**'s **Social Media Resizer** turns one photo into every platform size in a single click: **Instagram** post, portrait and story/Reel, **YouTube** thumbnail, **X** post and header, **LinkedIn** post and banner, **Facebook** cover and **Pinterest** pin. Tick the sizes you need (or Select all), choose **Crop to fill** or **Fit whole image** with a letterbox background color, and download each size separately or as one ZIP.",
      "It is **free** to use and **private by design**: all resizing happens in your browser, so your photos never leave your device. **Pro** members get unlimited resizes for full content calendars.",
    ],
    faqs: [
      { q: "Which platform sizes are included?", a: "Instagram post (1080x1080), Instagram portrait (1080x1350), Instagram story/Reel (1080x1920), YouTube thumbnail (1280x720), X post (1600x900), X header (1500x500), LinkedIn post (1200x627), LinkedIn banner (1584x396), Facebook cover (820x312) and Pinterest pin (1000x1500)." },
      { q: "What is the difference between Crop to fill and Fit whole image?", a: "Crop to fill scales the photo to fill the frame and trims the edges. Fit whole image shows the entire photo with a letterbox background in your chosen color, so nothing is cropped." },
      { q: "Can I pick only some sizes?", a: "Yes. Tick individual presets, use Select all, or Clear and choose just the ones you post to." },
      { q: "What formats can I export?", a: "JPG (with a quality slider) or PNG, applied to every selected size at once." },
      { q: "Are my photos uploaded anywhere?", a: "No. All resizing happens locally in your browser. Your files never leave your device." },
      { q: "Do I get each size as a separate file?", a: "Yes, every size gets its own download button, and you can also download everything together as a ZIP." },
    ],
    tags: ["social media image resizer", "instagram photo resizer", "resize image for instagram", "youtube thumbnail resizer", "resize photo for social media", "linkedin banner resizer", "facebook cover resizer", "pinterest pin resizer", "x header resizer", "free social media resizer", "resize image for all platforms", "instagram post size maker", "social media photo sizes", "bulk social media resize", "online image resizer social", "resize picture for instagram post", "youtube thumbnail size maker", "linkedin post image size", "instagram story resizer", "social media image sizes tool",
      "social media resizer",
      "image resizer for social media",
      "instagram size maker",
      "instagram post resizer 1080x1080",
      "instagram reel cover resizer",
      "instagram profile resizer",
      "facebook post image size",
      "facebook profile picture resizer",
      "facebook event cover size",
      "youtube banner resizer",
      "youtube profile picture size",
      "youtube community post size",
      "twitter post image size",
      "twitter header size maker",
      "linkedin profile banner size",
      "linkedin company logo size",
      "tiktok video cover size",
      "snapchat geofilter size",
      "pinterest profile cover size",
      "whatsapp dp resizer",
      "telegram profile photo resizer",
      "discord banner size",
      "twitch banner size",
      "twitch profile picture size",
      "all social media sizes",
      "social media image dimensions 2026",
      "social media size guide",
      "post size for every platform",
      "one image all social sizes",
      "bulk resize social images",
      "resize banner online",
      "cover photo resizer",
      "header image resizer",
      "profile picture size maker",
      "story size maker 1080x1920",
      "square post maker",
      "portrait post resizer 1080x1350",
      "landscape post resizer 1080x566",
      "social media crop tool",
      "platform preset image resizer"],
  };

export default seo;
