import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Solar System - Free Online Interactive Planet Simulator | IconVault",
    metaDescription: "Animated solar system with real planet data, speed control and click-for-facts. Free interactive orbit simulator that runs fully in your browser.",
    about: [
      "**IconVault**'s **Solar System** is an **interactive orbit simulator** built on **real planet data**: distance in AU, true orbital periods, diameters, moon counts, day lengths and a fun fact for all **8 planets**. Watch them orbit in real time, drag the **speed slider** from 0.5 to 60 days per second, and click any planet to inspect it.",
      "The animation runs **100% in your browser** on canvas and it is **free**, with a one-click facts copy for school projects or presentations. Orbits use true relative periods, but distances are log-compressed so the outer planets stay visible, which is not to scale the way textbook diagrams imply."
    ],
    faqs: [
      { q: "How do I use the Solar System simulator?", a: "Press play and watch the planets orbit the sun. Drag the speed slider to change the simulated days per second, or click any planet (or its name in the planet list) to see its distance, orbital period, diameter, moons, day length and a fun fact." },
      { q: "Is the simulation accurate?", a: "Orbital periods and the displayed planet data are real. Planet sizes scale with the log of their diameter and distances are log-compressed so Neptune stays on screen, so do not treat the geometry as to-scale." },
      { q: "Can I copy planet facts for homework?", a: "Yes. Select a planet and press Copy facts to get a formatted summary of its distance, orbital period, diameter, moons, day length and fun fact, ready to paste into notes or slides." },
      { q: "Does it work on phones?", a: "Yes. The canvas animation and planet buttons are fully clickable on touch devices, and the layout stacks the facts panel below the animation on small screens." },
      { q: "Does it need the internet after loading?", a: "No. Once the page loads, the animation and all planet data run locally in your browser. It is free with no signup." },
      { q: "Why is Pluto missing?", a: "Pluto is classified as a dwarf planet. The simulator shows the eight official planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune." }
    ],
    tags: [
      "solar system simulator",
      "interactive solar system",
      "planet orbit simulator",
      "solar system animation",
      "planets orbit animation",
      "solar system model online",
      "3d solar system simulator free",
      "planet simulator online",
      "orbit simulation tool",
      "solar system for kids",
      "learn planets online",
      "planet facts for kids",
      "solar system educational tool",
      "planet data explorer",
      "planet distance from sun",
      "orbital period of planets",
      "how long is a year on mars",
      "how many moons does saturn have",
      "jupiter facts for kids",
      "saturn facts for kids",
      "mars facts for kids",
      "venus facts for kids",
      "mercury facts for kids",
      "neptune facts for kids",
      "uranus facts for kids",
      "earth facts for kids",
      "planet day length",
      "planet diameter comparison",
      "solar system school project",
      "planet facts copy",
      "free astronomy tool",
      "astronomy simulator online",
      "space learning tool",
      "solar system quiz helper",
      "planet orbit speed",
      "how fast do planets orbit",
      "solar system diagram interactive",
      "interactive planet map",
      "planets in order from sun",
      "eight planets list",
      "solar system presentation helper",
      "planet comparison tool",
      "which planet has most moons",
      "hottest planet facts",
      "coldest planet facts",
      "biggest planet in solar system",
      "smallest planet in solar system",
      "free online planet simulator",
      "no signup astronomy tool",
      "classroom astronomy tool",
      "solar system homework help"
    ],
  };

export default seo;
