import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Source Map Explorer - Free Online Bundle Analyzer Tool | IconVault",
    metaDescription: "Upload a .js.map file and see which sources it contains with approximate byte weights. Free, 100% client-side, nothing is uploaded.",
    about: [
      "**IconVault**'s **Source Map Explorer** shows what is really inside your JavaScript bundle. Drop in a **.js.map** file and it decodes the **VLQ mappings**, lists every contained **source** with its mapping count, and estimates **approximate byte weights** so you can see which files and libraries are eating your bundle.",
      "Analysis runs **100% in your browser**: your source map is never uploaded, so proprietary code stays private. It is **free** with a searchable, sortable-by-weight source list. Weights are honest estimates from mapping share, not exact byte ranges, and only source map version 3 is supported."
    ],
    faqs: [
      { q: "How do I analyze a source map?", a: "Drag a .js.map file onto the drop zone or click to browse. The tool parses it locally, then shows the map size, source count, total mappings and a bar chart list of sources ordered by weight, with a filter box to search source names." },
      { q: "How are the byte weights calculated?", a: "The tool counts VLQ mappings per source and distributes the map file size across sources by mapping share. This is an approximation, good for finding the biggest contributors, not a precise per-file byte measurement." },
      { q: "Is my source map uploaded anywhere?", a: "No. Parsing and all math happen locally in your browser. This makes it safe to analyze proprietary or unreleased bundles." },
      { q: "Which source map versions are supported?", a: "Version 3, the standard format emitted by webpack, Vite, esbuild, Rollup and most modern bundlers. Invalid JSON or non-v3 maps show a clear error message." },
      { q: "Can I find which library bloats my bundle?", a: "Yes. Sort by weight and look for node_modules paths: large mapping counts on a single library file usually mean it dominates your bundle. Use the filter box to isolate vendor or app sources." },
      { q: "Why is this different from webpack-bundle-analyzer?", a: "Webpack-bundle-analyzer works from the stats file at build time and gives exact sizes. This tool works from the .map file alone in your browser, with no build integration needed, trading exactness for convenience." }
    ],
    tags: [
      "source map explorer",
      "source map analyzer",
      "js.map analyzer online",
      "analyze source map online",
      "source map viewer",
      "javascript bundle analyzer",
      "bundle size analyzer",
      "webpack bundle analyzer online",
      "vite bundle analyzer",
      "see inside js bundle",
      "what is in my bundle",
      "bundle bloat finder",
      "find large files in bundle",
      "js.map file viewer",
      "source map sources list",
      "vlq mappings decoder",
      "decode source map mappings",
      "source map weight estimator",
      "bundle composition tool",
      "javascript bundle breakdown",
      "webpack bundle breakdown online",
      "reduce javascript bundle size",
      "find heavy dependencies",
      "which library makes bundle big",
      "node_modules bundle size",
      "tree shaking check tool",
      "bundle audit tool",
      "frontend performance tool",
      "web performance analyzer",
      "page weight analyzer js",
      "source map version 3 viewer",
      "parse .map file online",
      "read js.map file",
      "source map to file list",
      "mapping count per source",
      "esbuild source map analyzer",
      "rollup bundle analyzer",
      "parcel bundle analyzer",
      "next.js bundle analyzer online",
      "nuxt bundle size check",
      "angular bundle analyzer",
      "private bundle analyzer",
      "source map analyzer no upload",
      "client side source map tool",
      "free bundle analyzer online",
      "no install bundle analyzer",
      "developer performance tool",
      "frontend dev tools online",
      "free online source map explorer",
      "no signup bundle tool"
    ],
  };

export default seo;
