import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Spacing Scale - Free Online CSS Spacing Generator Tool | IconVault",
    metaDescription: "Build a spacing scale from a base unit and ratio with visual bars. Export CSS variables and a Tailwind theme snippet. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Spacing Scale** builds a consistent **spacing system** from a base pixel unit and a growth **ratio**. Start from presets like a **Tailwind-like scale**, the classic **8pt grid**, the **golden ratio**, **major third** or **perfect fourth**, or dial in a fully custom geometric scale with your own step count.",
      "Every step is drawn as a **visual bar** with its px and rem values, and you can copy ready-to-use **CSS variables** or a **Tailwind theme** snippet in one click. It is **free** and runs **fully in your browser**. It generates the scale values, not the full design system, so token naming and responsive behavior are up to your own conventions."
    ],
    faqs: [
      { q: "How do I build a spacing scale?", a: "Pick a preset or set a base in pixels, a ratio and a step count. The visual scale, px/rem values, CSS variables and a Tailwind theme snippet all generate instantly, and both code blocks can be copied with one click." },
      { q: "What presets are included?", a: "Tailwind-like, 8pt grid, golden ratio (1.618), major third (1.25), perfect fourth (1.333) and linear 8px. Choosing a preset fills in the base and ratio; you can switch back to a custom geometric scale at any time." },
      { q: "What does the ratio do?", a: "Each step multiplies the previous step by the ratio, giving a geometric progression. A ratio of 1.5 with a base of 8 gives 8, 12, 18, 27 and so on. Ratios near 1.25 feel calm, larger ratios create more dramatic jumps." },
      { q: "How do I use the output in my project?", a: "Copy the CSS variables block into your stylesheet's :root and use var(--space-3) anywhere, or paste the Tailwind theme snippet into the spacing section of tailwind.config.js to get utilities like p-3 and m-6." },
      { q: "Are values shown in px and rem?", a: "Yes. Each step shows pixels and its rem equivalent at the standard 16px root size, so the scale stays consistent if users change their base font size." },
      { q: "Is anything sent to a server?", a: "No. The scale math and code generation run entirely in your browser, and the tool is free to use with no signup." }
    ],
    tags: [
      "spacing scale generator",
      "css spacing scale",
      "spacing system generator",
      "design spacing scale",
      "8pt grid generator",
      "8 point grid spacing",
      "spacing scale calculator",
      "css variables spacing",
      "generate spacing tokens",
      "design token spacing",
      "spacing tokens generator",
      "tailwind spacing scale",
      "tailwind theme spacing generator",
      "custom tailwind spacing",
      "spacing scale css",
      "consistent spacing web design",
      "spacing scale ratio",
      "golden ratio spacing",
      "modular scale spacing",
      "major third spacing scale",
      "perfect fourth spacing",
      "geometric spacing scale",
      "spacing scale px rem",
      "px to rem spacing scale",
      "margin padding scale",
      "css margin scale",
      "css padding scale",
      "spacing scale for designers",
      "ui spacing system",
      "design system spacing",
      "spacing scale figma",
      "spacing scale webflow",
      "bootstrap spacing scale",
      "material design spacing",
      "4px grid spacing",
      "base unit spacing",
      "spacing scale tool",
      "visual spacing scale",
      "spacing scale chart",
      "spacing scale preview",
      "export spacing css variables",
      "copy css spacing variables",
      "tailwind config spacing",
      "spacing scale react",
      "spacing scale vue",
      "web design spacing calculator",
      "free spacing scale generator",
      "online spacing scale tool",
      "no signup design tool",
      "frontend spacing helper",
      "css helper tool online"
    ],
  };

export default seo;
