import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Speech Playground - Interactive Tool | IconVault",
    metaDescription: "Speech studio in your browser: live mic transcription with SpeechRecognition and text-to-speech with real voices, rate and pitch. Free.",
    about: [ "**IconVault**'s **Speech Playground** is a two-in-one speech studio that runs entirely in your browser. The transcription panel uses the real **SpeechRecognition API** with live interim results and accumulating final text in ten languages, while the text-to-speech panel speaks through **speechSynthesis** with your device's actual voices, adjustable rate, and pitch. It is free and nothing is uploaded.", "If your browser lacks **speech recognition**, the mic panel says so honestly and stays disabled instead of faking it. The TTS voice list is read live from your **operating system**, so what you hear is exactly what your users would hear. Dictate notes, test voice UX copy, or explore how the **Web Speech API** behaves before you ship it." ],
    faqs: [
      { q: "How does the transcription work?", a: "It uses the browser's SpeechRecognition (or webkitSpeechRecognition) API with interim results on and continuous mode, so you see words appear live and final sentences accumulate. Your audio is processed by the browser's speech service, not by this page." },
      { q: "Why is the mic button disabled?", a: "Speech recognition only exists in Chrome and Edge on desktop and Android. The page detects the API honestly and disables the button where it is missing, instead of pretending to transcribe." },
      { q: "Where do the TTS voices come from?", a: "From your operating system and browser via speechSynthesis.getVoices(). The list is read live, which is why it differs between devices. Local voices are marked so you can pick ones that work offline." },
      { q: "Can I change the speaking speed?", a: "Yes. Rate runs from 0.5x to 2x and pitch from 0 to 2, applied to a real SpeechSynthesisUtterance with your chosen voice." },
      { q: "Is my voice recording uploaded?", a: "No. This page only calls browser APIs. Audio goes to the browser's own speech pipeline, and nothing is stored or sent to IconVault." },
      { q: "Which languages are supported?", a: "The language dropdown offers ten common locales, but the actual recognition languages depend on the browser's speech service. Pick the locale matching the speaker for best accuracy." },
    ],
    tags: [ "speech recognition browser", "speech to text online", "web speech api", "speechrecognition javascript", "browser transcription", "mic to text online", "text to speech online", "speechsynthesis", "tts voices browser", "speech playground", "voice to text free", "online dictation tool", "speech recognition demo", "webkitSpeechRecognition", "speechSynthesis.getVoices", "javascript text to speech", "browser tts", "speak text online", "voice typing online", "transcribe audio browser", "speech api tutorial", "learn web speech api", "speech to text javascript example", "interim results speech recognition", "continuous speech recognition", "speech recognition languages", "microphone transcription web", "free speech to text", "no signup speech to text", "tts rate pitch", "speech synthesis utterance", "choose tts voice", "local tts voices", "voiceover testing tool", "accessibility speech test", "dictate notes online", "voice input demo", "web api playground", "learn browser apis", "chrome speech recognition", "edge speech to text", "speech recognition not supported", "html5 speech input", "voice user interface test", "pronunciation tester", "read aloud tool", "narrator voice online", "robot voice generator", "speech studio online", "speech synthesis voices demo "],
  };

export default seo;
