import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Sprite Sheet Generator - Free Online Tool | IconVault",
    metaDescription: "Combine images into one PNG sprite sheet with auto-generated CSS classes. Grid or packed layouts, retina 2x. Free.",
    about: [
      "**IconVault**'s **Sprite Sheet Generator** merges your individual images into a single **PNG sprite sheet** and writes the matching **CSS classes** for you, one class per sprite with correct width, height and background-position. Each uploaded file becomes one sprite, named after the file, so your classes come out readable like `.sprite-logo`.",
      "Choose a **grid** layout (auto or fixed columns) or **packed rows** for mixed sizes, add padding between sprites, and enable **Retina 2x** to get both 1x and 2x sheets in a ZIP with CSS sized for standard displays. Everything runs **locally in your browser**: files never leave your device. **Free** with a daily trial, unlimited with Pro.",
    ],
    faqs: [
      { q: "What is a sprite sheet and why use one?", a: "A sprite sheet packs many small images into one file so a page loads one image instead of dozens of HTTP requests. The generated CSS positions a shared background image to show each sprite, which speeds up sites with lots of icons." },
      { q: "How do Grid and Packed rows differ?", a: "Grid places every sprite in uniform cells with a fixed column count (or an auto square-ish count). Packed rows shelves sprites row by row and fits mixed image sizes more tightly, wasting less space." },
      { q: "How does the Retina 2x option work?", a: "It renders the sheet at 2x resolution alongside the 1x version and adds media-query rules that set background-size so high-density screens show crisp sprites while CSS sizes stay at the 1x dimensions." },
      { q: "How are the CSS class names chosen?", a: "Each class is built from your prefix plus the file name, sanitized to lowercase CSS-safe slugs. The base class sets the shared background image; each sprite class sets width, height and background-position." },
      { q: "Are my images uploaded anywhere?", a: "No. The sheet is composited on canvas in your browser and the CSS is generated locally. Nothing leaves your device." },
      { q: "Is there a free limit?", a: "Yes, a daily trial covers free builds. IconVault Pro unlocks unlimited sprite sheet builds and every other tool." },
    ],
    tags: [ "sprite sheet generator", "css sprite generator", "make sprite sheet online", "png sprite sheet", "sprite css generator", "combine images into sprite", "retina sprite sheet", "game sprite sheet maker", "icon sprite generator", "sprite sheet from png", "css sprites tool", "2x sprite sheet", "sprite packer online", "web sprite generator", "sprite atlas generator", "merge images one png", "sprite sheet css classes", "free sprite generator", "packed sprite layout", "sprite background position css" ,
      "sprite generator",
      "sprite sheet maker",
      "spritesheet creator",
      "css sprites generator",
      "image sprite maker",
      "sprite sheet online free",
      "game spritesheet tool",
      "pixel art sprite sheet",
      "character sprite sheet maker",
      "animation sprite sheet",
      "sprite sheet for unity",
      "sprite sheet for godot",
      "sprite sheet for phaser",
      "sprite sheet for gamemaker",
      "texture atlas maker",
      "sprite atlas online",
      "tilemap sprite packer",
      "spritesheet packer online",
      "bin packing sprite tool",
      "sprite sheet json generator",
      "sprite sheet xml output",
      "cocos sprite sheet",
      "sprite sheet padding",
      "sprite sheet spacing",
      "trim sprites sheet",
      "sprite sheet background transparent",
      "emoji sprite sheet",
      "flag sprite sheet",
      "website icon sprite",
      "ui icon sprite generator",
      "button sprite generator",
      "hover sprite maker",
      "sprite animation preview",
      "spritesheet to gif preview",
      "split sprite sheet",
      "sprite sheet cutter",
      "extract sprites from sheet",
      "sprite sheet resizer",
      "svg sprite generator",
      "svg symbol sprite maker"],
  };

export default seo;
