import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SQL to MongoDB - Free Online SQL to Mongo Query Converter Tool | IconVault",
    metaDescription: "Convert SQL SELECT queries to MongoDB find() or an aggregate pipeline. WHERE, ORDER BY, LIMIT supported. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **SQL to MongoDB** translates **SELECT queries** into MongoDB you can paste straight into mongosh. It converts columns, WHERE with **AND/OR** and parentheses, comparison operators, **LIKE**, **IN**, **BETWEEN**, **IS NULL**, **ORDER BY**, **LIMIT** and **OFFSET** into either a chained **find()** call or an **aggregate() pipeline** with $match, $project, $sort, $skip and $limit stages.",
      "Conversion runs **100% in your browser** and is **free**. It is honest about the supported subset: **JOINs**, subqueries and **GROUP BY** aggregations are rejected with a clear error instead of silently producing wrong queries, and LIKE patterns become proper anchored regular expressions."
    ],
    faqs: [
      { q: "What SQL is supported?", a: "SELECT column lists, FROM, WHERE with AND/OR/NOT and parentheses, =, !=, <>, >, <, >=, <=, LIKE, NOT LIKE, IN, NOT IN, BETWEEN, IS NULL and IS NOT NULL, ORDER BY with ASC/DESC, LIMIT and OFFSET. Column aliases are accepted." },
      { q: "Should I use find() or aggregate() output?", a: "find() is the natural fit for simple filtering, sorting and pagination. Choose aggregate() when you want an explicit pipeline of $match, $project, $sort, $skip and $limit stages, which is easier to extend later." },
      { q: "How is LIKE converted?", a: "LIKE patterns become anchored $regex expressions: % becomes .* and _ becomes a single character, with regex metacharacters escaped. NOT LIKE becomes $not with the same pattern." },
      { q: "What is not supported?", a: "JOINs, subqueries, GROUP BY aggregations, DISTINCT in output, expressions and function calls in the SELECT list, and UNION. These raise a clear error message rather than guessing." },
      { q: "Is my query sent to a server?", a: "No. The SQL parser and MongoDB code generation run entirely in your browser. Your schema and query text never leave your device." },
      { q: "Can I trust the output in production?", a: "Review it first. The converter is accurate within its documented subset, but field types, indexes and collation differ between SQL and MongoDB, so test the generated query against your actual data." }
    ],
    tags: [
      "sql to mongodb",
      "sql to mongo converter",
      "convert sql to mongodb online",
      "sql select to mongodb find",
      "sql to mongo query",
      "sql to mongodb query converter",
      "translate sql to mongodb",
      "sql to nosql converter",
      "sql to mongodb find",
      "sql to aggregate pipeline",
      "sql to mongo aggregate",
      "mongodb query builder from sql",
      "convert where clause to mongodb",
      "sql like to mongodb regex",
      "sql in to mongodb $in",
      "sql between to mongodb",
      "sql order by to mongodb sort",
      "sql limit to mongodb limit",
      "sql offset to mongodb skip",
      "sql is null mongodb",
      "mongodb $match generator",
      "mongodb $project generator",
      "mongodb find syntax generator",
      "mongosh query converter",
      "learn mongodb from sql",
      "sql to mongodb tutorial",
      "mongodb for sql developers",
      "migrate sql to mongodb",
      "sql migration mongodb",
      "convert mysql to mongodb",
      "convert postgres to mongodb",
      "relational to document query",
      "sql to document db converter",
      "mongodb query translator",
      "sql syntax to mongo syntax",
      "mongodb cheat sheet sql",
      "sql vs mongodb queries",
      "free sql to mongodb converter",
      "online sql to mongo",
      "sql to mongodb no signup",
      "mongodb playground sql",
      "test mongodb queries online",
      "mongodb query generator",
      "nosql query builder",
      "database migration tool",
      "sql developer mongodb tool",
      "backend developer tools",
      "free online converter sql mongo",
      "sql to mongo in browser",
      "private sql converter"
    ],
  };

export default seo;
