import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SQL to JSON - Free Online SQL INSERT to JSON Converter Tool | IconVault",
    metaDescription: "Convert SQL INSERT statements into a JSON array with correct types. Handles NULL, numbers, booleans and quoted strings. Free, in-browser.",
    about: [
      "**IconVault**'s **SQL to JSON** turns database **INSERT statements** into clean **JSON**. Paste one or many INSERT INTO ... VALUES statements and get a formatted **JSON array** where NULL stays null, numbers stay numbers, TRUE and FALSE become real booleans, and quoted strings are unescaped correctly, including '' and \\' escapes.",
      "It is **free** and runs **100% in your browser**, with one-click copy and a **.json download** named after your table. It honestly handles INSERT statements only: other statement types are rejected with a clear error, and statements without a column list get generic col1, col2 names."
    ],
    faqs: [
      { q: "What SQL does it convert?", a: "Standard INSERT INTO table (columns) VALUES (...), (...) statements, including multiple statements in one paste. Backtick, double-quote and bracket-quoted identifiers are all understood." },
      { q: "How are values typed in the JSON?", a: "NULL becomes null, TRUE/FALSE become booleans, numeric literals become numbers, and quoted strings become strings with escapes resolved. Unquoted non-numeric values pass through as strings." },
      { q: "What if my INSERT has no column list?", a: "The converter still works and names the fields col1, col2, col3 in order. For cleaner output, add the column list to your INSERT." },
      { q: "Can I download the result?", a: "Yes. The .json button downloads the formatted JSON, named after the table for a single statement or inserts.json for multiple tables." },
      { q: "Is my SQL data sent to a server?", a: "No. Parsing and JSON generation happen entirely in your browser. Row data never leaves your device, so database dumps stay private." },
      { q: "Why did it reject my statement?", a: "Only INSERT INTO ... VALUES (...) is supported. SELECT, UPDATE, DELETE, CREATE TABLE and exotic syntax like ON CONFLICT or multi-row constructors with functions will raise an error rather than guess wrong." }
    ],
    tags: [
      "sql to json",
      "sql to json converter",
      "convert sql to json online",
      "insert to json",
      "sql insert to json",
      "convert insert statements to json",
      "mysql to json converter",
      "postgres insert to json",
      "sql dump to json",
      "convert sql dump to json",
      "sql values to json",
      "sql rows to json array",
      "database to json converter",
      "export sql as json",
      "sql result to json",
      "sql data to json online",
      "json from sql insert",
      "parse sql insert online",
      "sql insert parser",
      "sql to json api",
      "sql to json free",
      "sql to json no signup",
      "online sql converter",
      "sql to json array",
      "sql to json object",
      "convert database rows to json",
      "mysql dump to json online",
      "seed data to json",
      "sql seed to json",
      "fixtures from sql",
      "sql to json for api",
      "rest api seed json",
      "mock data from sql",
      "sql to json download",
      "json file from sql",
      "sql null to json null",
      "sql boolean to json",
      "quoted string sql json",
      "escape quotes sql json",
      "multi row insert to json",
      "bulk insert to json",
      "sql to json formatter",
      "pretty json from sql",
      "sql to json privacy",
      "convert sql in browser",
      "sql migration to json",
      "etl sql to json",
      "sql to nosql json",
      "database export json",
      "table to json converter",
      "sql table to json online"
    ],
  };

export default seo;
