import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SQL Parameterizer - Free Online SQL Placeholder Converter Tool | IconVault",
    metaDescription: "Replace inline SQL literals with ?, $1, :p1 or @p1 placeholders and get an ordered parameter list. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **SQL Parameterizer** converts risky inline values into **safe placeholders**. Paste SQL with hard-coded strings and numbers and it rewrites them as **?**, **$1**, **:p1** or **@p1** style parameters, depending on your database, and hands you an **ordered parameter list** with the original values, ready to bind in your code.",
      "It runs **100% in your browser** and is **free**, leaving NULLs, TRUE/FALSE, identifiers, comments and existing placeholders untouched. It is a text rewriting helper, not a security auditor: always review the output and keep using your driver's **parameter binding** rather than string concatenation."
    ],
    faqs: [
      { q: "What does the SQL Parameterizer do?", a: "It scans your SQL for single-quoted string literals and standalone number literals, replaces each with a placeholder in your chosen style, and lists every parameter in order with its original value and type so you can bind them in code." },
      { q: "Which placeholder styles are supported?", a: "? for MySQL, SQLite and JDBC, $1, $2 for PostgreSQL, :p1, :p2 Oracle-style named parameters, and @p1, @p2 for SQL Server." },
      { q: "What is left unchanged?", a: "NULL, TRUE and FALSE keywords, quoted identifiers, comments, numbers that are part of identifiers, and placeholders that already exist in the query are all preserved exactly as written." },
      { q: "Does this prevent SQL injection?", a: "It helps you write parameterized queries, which is the right defense, but only if you bind the listed values through your database driver's parameter API. Pasting the values back into the query string yourself would defeat the purpose." },
      { q: "Is my SQL sent to a server?", a: "No. The rewriting runs entirely in your browser. Queries, table names and literal values never leave your device." },
      { q: "Can I copy just the parameter list?", a: "Yes. There are separate copy buttons for the parameterized SQL and for the ordered parameter list, which is formatted as placeholder = value lines." }
    ],
    tags: [
      "sql parameterizer",
      "parameterize sql query",
      "sql placeholder converter",
      "sql literals to parameters",
      "convert sql to parameterized query",
      "sql question mark placeholders",
      "sql dollar placeholders",
      "postgres $1 placeholder generator",
      "sql server @p1 parameters",
      "oracle named parameters sql",
      "replace inline values sql",
      "sql injection prevention tool",
      "parameterized query builder",
      "sql prepared statement helper",
      "bind variables sql",
      "sql bind parameters online",
      "extract parameters from sql",
      "sql query parameters list",
      "get sql parameters online",
      "sql string to parameters",
      "hardcoded values to placeholders",
      "sql query sanitizer",
      "safe sql query tool",
      "mysql prepared statement",
      "sqlite parameterized query",
      "jdbc placeholder converter",
      "psycopg2 placeholder sql",
      "node pg parameterized query",
      "sequelize raw query parameters",
      "typeorm query parameters",
      "prisma raw sql parameters",
      "dapper sql parameters",
      "ado.net parameterized query",
      "php pdo placeholders",
      "python sql parameters",
      "java jdbc sql parameters",
      "convert dynamic sql to static",
      "sql template parameters",
      "stored procedure parameters from sql",
      "refactor sql to prepared statement",
      "sql code review helper",
      "secure sql generator",
      "database developer tool",
      "free sql parameterizer",
      "online sql parameterizer",
      "sql tools online free",
      "no signup sql tool",
      "sql formatter parameters",
      "sql query cleaner",
      "sql placeholder list generator"
    ],
  };

export default seo;
