import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SQL Formatter - Free Online SQL Beautifier Tool | IconVault",
    metaDescription: "Format and beautify SQL with clause newlines, indentation and keyword casing. MySQL, PostgreSQL, SQL Server, SQLite dialects. Free, in-browser.",
    about: [
      "**IconVault**'s **SQL Formatter** turns one-line query soup into readable **SQL**. Its lightweight tokenizer adds **clause newlines**, smart **indentation**, one-column-per-line SELECT lists, inline short parentheses and your choice of **UPPERCASE**, **lowercase** or preserved **keyword casing**, with per-dialect keyword vocabulary for **MySQL**, **PostgreSQL**, **SQL Server**, **SQLite** and generic SQL.",
      "Formatting runs **100% in your browser**, so your queries and data are never uploaded, and it is **free** to use. It is honest about being a lightweight formatter: very exotic dialect syntax may not format perfectly, and it does not validate your SQL against a live database."
    ],
    faqs: [
      { q: "How do I format my SQL?", a: "Paste your query, pick a dialect and a keyword casing, then press Format. The formatted output appears below with a one-click copy button, and you can load a sample query to see the style instantly." },
      { q: "Which SQL dialects are supported?", a: "Generic, MySQL, PostgreSQL, SQL Server and SQLite. The dialect extends the formatter's keyword vocabulary with dialect-specific words; the formatting rules themselves stay the same." },
      { q: "Can I change keyword casing?", a: "Yes. Choose UPPERCASE for the classic look, lowercase for a modern style, or Preserve to keep your original casing while still fixing layout." },
      { q: "Is my SQL sent to a server?", a: "No. The tokenizer and formatter run entirely in your browser. Nothing is uploaded, logged or stored, so proprietary queries stay private." },
      { q: "Does it validate my SQL?", a: "No, it only reformats text. It will not catch syntax errors, wrong table names or logic bugs. Always test formatted queries against your database before running them in production." },
      { q: "What is not supported?", a: "Very exotic dialect-specific syntax may format imperfectly because this is a lightweight tokenizer, not a full parser. Comments are stripped during formatting in this version." }
    ],
    tags: [
      "sql formatter",
      "sql beautifier",
      "format sql online",
      "beautify sql query",
      "sql pretty print",
      "sql formatter online free",
      "sql query formatter",
      "format sql query online",
      "sql code formatter",
      "tidy sql",
      "sql indenter",
      "sql indent online",
      "mysql formatter",
      "format mysql query",
      "mysql query beautifier",
      "postgresql formatter",
      "format postgres query",
      "postgres sql beautifier",
      "sql server formatter",
      "format tsql online",
      "tsql beautifier",
      "sqlite formatter",
      "format sqlite query",
      "sql keyword uppercase",
      "uppercase sql keywords online",
      "sql casing converter",
      "sql select formatter",
      "format select statement",
      "format join query",
      "readable sql",
      "pretty sql query",
      "sql style formatter",
      "sql linter online",
      "sql minifier reverse",
      "unminify sql",
      "sql one line to multiline",
      "format sql in browser",
      "sql formatter no signup",
      "free sql formatter",
      "sql formatter privacy",
      "format sql without upload",
      "database query formatter",
      "plsql formatter online",
      "oracle sql formatter",
      "format stored procedure sql",
      "sql view formatter",
      "format create table statement",
      "online sql tools",
      "developer sql tool",
      "dba formatter tool",
      "sql formatter chrome"
    ],
  };

export default seo;
