import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SQL Query Builder - Free Online Visual SQL Builder Tool | IconVault",
    metaDescription: "Build SELECT, INSERT, UPDATE and DELETE queries visually with live SQL output and per-dialect identifier quoting. Free, runs in your browser.",
    about: [
      "**IconVault**'s **SQL Query Builder** writes **SQL** for you, visually. Pick a statement type, name your **table** and **columns**, add **WHERE conditions** with operators like =, LIKE, IN and BETWEEN, toggle **ORDER BY** and **LIMIT**, and watch valid SQL generate **live** as you type.",
      "Identifier quoting adapts to your **dialect**: backticks for **MySQL**, square brackets for **SQL Server**, double quotes for **PostgreSQL**, **SQLite** and generic SQL. It is **free** and runs **fully in your browser**, and it warns you loudly before a WHERE-less DELETE. It is honest about scope: no JOINs, subqueries or aggregations, just clean single-table statements."
    ],
    faqs: [
      { q: "Which statements can I build?", a: "SELECT with columns, WHERE, ORDER BY and LIMIT; INSERT with columns and values; UPDATE with SET assignments and WHERE; and DELETE with WHERE. JOINs, subqueries, GROUP BY and aggregations are not part of this builder." },
      { q: "How does dialect quoting work?", a: "Pick generic, MySQL, PostgreSQL, SQL Server or SQLite and identifiers are quoted the way that database expects: `col` for MySQL, [col] for SQL Server, and \"col\" for the rest. Plain expressions pass through untouched." },
      { q: "How are values handled?", a: "Numbers and true/false stay unquoted, empty values become NULL, and everything else is wrapped in quotes with single quotes escaped, so the generated SQL is valid as written for simple cases." },
      { q: "Is a DELETE without WHERE dangerous?", a: "Very. The builder inserts a bold warning comment when no WHERE clause is present so you notice before copying, but always double-check the generated SQL before running it anywhere." },
      { q: "Is my schema sent to a server?", a: "No. The builder runs entirely in your browser. Table names, columns and values never leave your device, and the tool is free with no signup." },
      { q: "Can I use this to learn SQL?", a: "Yes, it is a nice learning aid: change a condition or toggle ORDER BY and watch how the SQL changes. For real work, review the output and test it against your database." }
    ],
    tags: [
      "sql query builder",
      "visual sql builder",
      "build sql query online",
      "sql builder online free",
      "generate sql query",
      "sql query generator",
      "create select query online",
      "select query builder",
      "sql where clause builder",
      "sql insert builder",
      "insert query generator",
      "sql update builder",
      "update query generator",
      "sql delete builder",
      "delete query generator",
      "sql statement generator",
      "visual query builder free",
      "no code sql builder",
      "sql builder for beginners",
      "learn sql query builder",
      "sql practice tool",
      "mysql query builder",
      "postgres query builder",
      "sql server query builder",
      "sqlite query builder",
      "sql identifier quoting",
      "mysql backtick quoting",
      "sql server bracket quoting",
      "postgres double quote identifiers",
      "sql order by builder",
      "sql limit clause generator",
      "sql like condition builder",
      "sql in clause builder",
      "sql between builder",
      "sql where and or builder",
      "generate where clause",
      "sql syntax generator",
      "write sql without coding",
      "sql helper tool",
      "database query helper",
      "sql learning tool",
      "sql tutorial helper",
      "free online sql builder",
      "sql builder no signup",
      "sql tools for developers",
      "dba query builder",
      "sql playground online",
      "test sql queries online",
      "sql query maker",
      "sql statement maker"
    ],
  };

export default seo;
