import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SQLite Browser - Free Online SQLite Database Viewer Tool | IconVault",
    metaDescription: "Open .sqlite files in your browser, browse tables, run SQL queries and export results to CSV or JSON. Free, no upload needed.",
    about: [
      "**IconVault**'s **SQLite Browser** opens any **SQLite database file** right in your web browser. Just **drop a .sqlite, .db or .sqlite3 file** onto the page to browse its **tables**, row counts and **schema** (columns, types, primary keys) instantly. A real SQLite engine (**sql.js**, compiled to **WebAssembly**) powers everything, so there is no server and **your database never leaves your device**.",
      "A built-in **SQL editor** lets you run any **SELECT query** and other statements against the open database, with results shown in a clean table. **Export query results to CSV or JSON** with one click, or copy your SQL for reuse. Everything runs **fully in your browser**, and it is **free** to try (repeated use may ask for Pro)."
    ],
    faqs: [
      { q: "What does the SQLite Browser do?", a: "It opens SQLite database files in your browser so you can browse tables, inspect the schema and run SQL queries without installing desktop software like DB Browser for SQLite." },
      { q: "Do I need to install anything?", a: "No. The sql.js engine loads from a CDN on first use (it needs network access once and is cached by your browser afterward). Your database file itself is read locally and never uploaded." },
      { q: "Is my database uploaded to a server?", a: "No. Every query runs locally in your browser through WebAssembly. Your file never leaves your device, so it is safe to inspect databases with real or sensitive data." },
      { q: "Can I export query results?", a: "Yes. Any result set can be downloaded as CSV or JSON with one click, and you can copy your SQL statements to the clipboard." },
      { q: "Which file types are supported?", a: "Files with .sqlite, .db, .sqlite3 and .db3 extensions. If the engine cannot parse the file, you will get a clear error instead of a silent failure." },
      { q: "Is the tool really free?", a: "Yes, it is free to try with no signup. Opening many databases in a short period may prompt an upgrade to Pro for unlimited use." }
    ],
    tags: [
      "sqlite browser",
      "sqlite viewer online",
      "open sqlite file online",
      "sqlite database viewer",
      "view sqlite db online",
      "sqlite online viewer",
      "browse sqlite database",
      ".db file viewer online",
      "open .db file online",
      "sqlite3 file viewer",
      "view sqlite file without install",
      "sqlite database browser online",
      "sqlite editor online free",
      "run sql on sqlite file online",
      "sqlite query tool online",
      "sqlite sql editor browser",
      "query sqlite in browser",
      "sqlite online sql query",
      "sqlite file reader",
      "read sqlite database online",
      "sqlite table viewer",
      "sqlite schema viewer",
      "sqlite database explorer",
      "sqlite db explorer online",
      "open sqlite database in browser",
      "sqlite file opener online",
      "sqlite database opener",
      "view .sqlite file online",
      "sqlite browser free",
      "best sqlite browser online",
      "sqlite viewer no install",
      "sqlite db browser free",
      "sqlite database client online",
      "online sqlite database manager",
      "sqlite manager online free",
      "sqlite database tool online",
      "inspect sqlite file online",
      "sqlite data viewer",
      "export sqlite to csv online",
      "sqlite to csv converter online",
      "sqlite query to json",
      "export sqlite results json",
      "sqlite file viewer windows alternative online",
      "db browser for sqlite online alternative",
      "open sqlite3 file in browser",
      "sqlite wasm viewer",
      "sql.js online",
      "sqlite in browser",
      "how to open a sqlite file",
      "what is a sqlite browser",
      "sqlite database viewer free"
    ],
  };

export default seo;
