import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SRI Generator - Free Online Subresource Integrity Hash Tool | IconVault",
    metaDescription: "Generate SHA-256, SHA-384 and SHA-512 integrity hashes for scripts and stylesheets with a paste-ready tag. Free, in your browser.",
    about: [
      "**IconVault**'s **SRI Generator** creates **Subresource Integrity (SRI) hashes** for your **JavaScript** and **CSS** files. Paste the file content or upload it, pick **SHA-256**, **SHA-384** or **SHA-512**, and get the exact **integrity=\"sha384-...\"** attribute value. Hashing uses your browser's **WebCrypto API**, so it is fast and accurate, and your files are **never uploaded** anywhere.",
      "Optionally add the file's **CDN URL** and the tool builds a **paste-ready <script> or <link> tag** with the integrity attribute and **crossorigin=\"anonymous\"** included. **SHA-384** is preselected as the recommended balance of security and hash length. It is **free** to try, and everything runs **fully in your browser**."
    ],
    faqs: [
      { q: "What is Subresource Integrity (SRI)?", a: "SRI is a browser security feature that lets a page verify a file loaded from a CDN has not been tampered with. The browser hashes the downloaded file and compares it to the integrity attribute; if they differ, the file is blocked." },
      { q: "Which hash algorithm should I choose?", a: "SHA-384 is the recommended default and is preselected in the tool. SHA-256 gives a shorter hash and SHA-512 gives the strongest digest; all three are supported by browsers for SRI." },
      { q: "Do I have to regenerate the hash when my file changes?", a: "Yes. Even a single changed byte produces a completely different hash, and the browser will refuse to load the resource until the integrity attribute is updated. Regenerate the hash on every deploy that touches the file." },
      { q: "Why does the generated tag include crossorigin?", a: "Browsers require crossorigin=\"anonymous\" on the tag for the integrity check to run on cross-origin resources. The paste-ready tag includes it automatically." },
      { q: "Is my file uploaded anywhere?", a: "No. The hash is computed locally with the WebCrypto API in your browser. Your script or stylesheet content never leaves your device." },
      { q: "Is the SRI Generator free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "sri generator",
      "subresource integrity generator",
      "integrity hash generator",
      "generate sri hash",
      "sha384 integrity hash",
      "sha256 integrity generator",
      "sha512 integrity generator",
      "sri hash online",
      "script integrity attribute generator",
      "generate integrity attribute",
      "cdn integrity hash",
      "subresource integrity sha384",
      "integrity sha256 generator",
      "integrity sha512 generator",
      "html integrity hash tool",
      "create sri hash online",
      "sri hash calculator",
      "file to sri hash",
      "js file integrity hash",
      "css file integrity hash",
      "generate integrity for cdn script",
      "script tag integrity generator",
      "link tag integrity generator",
      "sri generator free",
      "online sri hash generator",
      "what is subresource integrity",
      "how to generate sri hash",
      "sri hash from file",
      "paste text generate integrity hash",
      "webcrypto sha384 base64",
      "sha384 base64 hash online",
      "integrity attribute value generator",
      "crossorigin anonymous integrity",
      "cdnjs integrity hash",
      "jsdelivr sri hash generator",
      "unpkg integrity hash",
      "generate sri for jquery",
      "sri hash for bootstrap css",
      "subresource integrity best practices",
      "why use sri hashes",
      "sri hash mismatch fix",
      "regenerate sri hash after file change",
      "sha384 sri example",
      "integrity hash javascript",
      "secure cdn script with integrity",
      "html script integrity hash",
      "stylesheet integrity hash generator",
      "sri hash tool online free",
      "generate sri hash from url content",
      "sha256 sri hash example"
    ],
  };

export default seo;
