import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SSH Config Generator - Free Online SSH Config Builder Tool | IconVault",
    metaDescription: "Build your ~/.ssh/config visually with hosts, ports, identity files and ProxyJump. Live preview, copy or download. Free, in your browser.",
    about: [
      "**IconVault**'s **SSH Config Generator** builds your **~/.ssh/config** file **visually**, so you never have to memorize OpenSSH syntax. Add **host entries** with short aliases, **HostName**, **User**, **Port**, **IdentityFile**, **ProxyJump** and keep-alive settings, then flip toggles for **ForwardAgent**, **AddKeysToAgent** and **Compression**. A **live preview** shows the exact config file updating as you type.",
      "**Copy** the finished config to your clipboard or **download** it, then save it as **~/.ssh/config** and connect with short commands like `ssh web` instead of full hostnames and flags. Everything runs **fully in your browser** with nothing uploaded, and it is **free** to try."
    ],
    faqs: [
      { q: "What is an SSH config file?", a: "The ~/.ssh/config file stores per-host connection settings for OpenSSH, so instead of typing long commands with usernames, ports and key paths, you connect with a short alias like ssh web." },
      { q: "Where do I save the generated config?", a: "Save the downloaded or copied text as ~/.ssh/config on macOS or Linux (create the ~/.ssh folder if needed and set permissions with chmod 600 ~/.ssh/config). Windows users with OpenSSH can use the same path in their user profile." },
      { q: "What is ProxyJump and when do I need it?", a: "ProxyJump connects you through an intermediate bastion or jump host to reach servers on a private network. Enter the jump host's alias in the ProxyJump field and SSH handles the hop automatically." },
      { q: "Should I enable ForwardAgent?", a: "Agent forwarding is convenient when you hop between servers and need your local key on the remote side, but a compromised intermediate server could use your agent. Only enable it for hosts you trust." },
      { q: "Can I manage multiple hosts in one config?", a: "Yes. Add as many host entries as you need, for example one per VPS, staging server or Git host, and the preview combines them into a single valid config file." },
      { q: "Is my host data uploaded anywhere?", a: "No. The whole builder runs locally in your browser, so real hostnames, IPs and usernames never leave your device." }
    ],
    tags: [
      "ssh config generator",
      "ssh config builder",
      "ssh config file generator",
      "generate ssh config",
      "ssh config online",
      "ssh host alias generator",
      "ssh config maker",
      "ssh client config generator",
      "visual ssh config editor",
      "ssh config file creator",
      "ssh config generator free",
      "ssh config template",
      "ssh config file example",
      "ssh config host entry generator",
      "ssh config proxyjump",
      "ssh proxyjump config generator",
      "ssh config identityfile",
      "ssh config port",
      "ssh config forwardagent",
      "ssh config addkeystoagent",
      "ssh config compression",
      "ssh config serveraliveinterval",
      "multiple ssh hosts config",
      "ssh config for github",
      "ssh config for gitlab",
      "ssh config bastion host",
      "ssh jump host config example",
      "ssh config for vps",
      "ssh config digitalocean",
      "ssh config aws ec2",
      "how to create ssh config file",
      "ssh config file location",
      "ssh config file format",
      "ssh config syntax",
      "ssh config generator windows",
      "ssh config generator mac",
      "ssh config download",
      "ssh config copy paste",
      "ssh alias generator",
      "ssh shortcut config",
      "ssh config user port",
      "openssh config generator",
      "openssh config file builder",
      "ssh config best practices",
      "ssh config tips",
      "ssh config cheat sheet",
      "ssh config generator online free",
      "create ssh config online",
      "ssh host entry template",
      "ssh config keepalive setting"
    ],
  };

export default seo;
