import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Statistics Calculator - Free Online Descriptive Statistics Tool | IconVault",
    metaDescription: "Compute mean, median, mode, standard deviation, quartiles and a box plot for any number list. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Statistics Calculator** turns any **number list** into a full set of **descriptive statistics** instantly. Paste **comma, space or newline separated** numbers and get **count, sum, mean, median, mode and range**, both **sample and population standard deviation** and **variance**, plus **quartiles (Q1, Q3)** and the **interquartile range (IQR)**. A rendered **box plot** visualizes the spread, with whiskers for min and max and the median line through the box.",
      "Percentiles use **linear interpolation**, the same method as NumPy's default, and any entries that are not numbers are skipped with the count shown. **Copy all statistics** as plain text for reports or spreadsheets. Everything runs **fully in your browser**, your data is never uploaded, and it is **free** to try."
    ],
    faqs: [
      { q: "What statistics does the calculator compute?", a: "Count, sum, mean, median, mode, sample and population standard deviation and variance, min, max, range, Q1, Q3 and the interquartile range, plus a box plot of the data." },
      { q: "How should I enter my numbers?", a: "Paste them separated by commas, spaces, semicolons or newlines, for example: 12, 18, 21, 25, 30. Anything that is not a number is skipped and reported." },
      { q: "What is the difference between sample and population standard deviation?", a: "Population standard deviation divides by n and describes the full data set; sample standard deviation divides by n-1 and estimates the spread of a larger population your data was drawn from. The tool shows both so you can pick the right one." },
      { q: "What does the box plot show?", a: "The box spans Q1 to Q3 with a line at the median, and the whiskers extend to the minimum and maximum values, giving a quick visual of the data's spread and center." },
      { q: "Is my data uploaded anywhere?", a: "No. All calculations happen locally in your browser with JavaScript, so your numbers never leave your device." },
      { q: "Is the Statistics Calculator free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "statistics calculator",
      "descriptive statistics calculator",
      "mean median mode calculator",
      "standard deviation calculator",
      "mean calculator online",
      "median calculator",
      "mode calculator online",
      "variance calculator",
      "standard deviation online",
      "sample standard deviation calculator",
      "population standard deviation calculator",
      "quartiles calculator",
      "q1 q3 calculator",
      "interquartile range calculator",
      "iqr calculator",
      "box plot maker online",
      "box plot generator",
      "box and whisker plot online",
      "range calculator statistics",
      "sum calculator online",
      "count mean median calculator",
      "descriptive stats online free",
      "statistics calculator free",
      "calculate statistics online",
      "number list statistics",
      "data set statistics calculator",
      "std dev calculator free",
      "variance and standard deviation calculator",
      "calculate mean of numbers",
      "how to calculate standard deviation",
      "standard deviation formula calculator",
      "median of a data set calculator",
      "mode of numbers calculator",
      "quartiles of data calculator",
      "iqr formula calculator",
      "box plot maker free",
      "create box plot online",
      "box plot from data",
      "statistics for students",
      "stats homework calculator",
      "descriptive statistics tool",
      "statistics summary calculator",
      "five number summary calculator",
      "min max range calculator",
      "outlier calculator iqr",
      "numpy percentile calculator",
      "linear interpolation percentile",
      "copy statistics as text",
      "statistics calculator no signup",
      "online stats calculator",
      "basic statistics calculator"
    ],
  };

export default seo;
