import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "String Escaper - Free Online String Escape Tool | IconVault",
    metaDescription: "Escape strings for Java, Python, C#, SQL or CSV: quotes, backslashes and newlines handled per language rules. Free, in your browser.",
    about: [
      "**IconVault**'s **String Escaper** escapes any string for the language you are pasting it into. Pick **Java**, **Python**, **C#**, **SQL** or **CSV** and the tool applies the correct rules live as you type: **backslash escapes** for quotes, newlines, tabs and carriage returns in Java, Python and C#; **doubled single quotes** for **SQL string literals** (works for MySQL, PostgreSQL and SQL Server); and **RFC 4180 quoting** for CSV fields.",
      "The **escaped output** appears side by side with your raw input and copies with one click, so embedding multiline or quote-heavy text in code stops being error-prone. Everything runs **fully in your browser** with nothing uploaded, and it is **free** to try."
    ],
    faqs: [
      { q: "What does it mean to escape a string?", a: "Escaping adds escape sequences (like backslashes) in front of special characters so they are treated as literal text instead of breaking the string's syntax, for example turning a quote into \\\" inside a Java string." },
      { q: "Which languages are supported?", a: "Java, Python, C#, SQL and CSV. Java, Python and C# share the same backslash escaping; SQL doubles single quotes; CSV wraps the field in quotes and doubles inner quotes per RFC 4180." },
      { q: "How are newlines and tabs escaped?", a: "Newlines become \\n, carriage returns become \\r and tabs become \\t for the Java, Python and C# modes, so multiline text collapses into a valid single-line string literal." },
      { q: "Does SQL escaping protect against SQL injection?", a: "Doubling quotes is the correct way to write a string literal, but it is not a substitute for parameterized queries. Always use prepared statements or parameters for untrusted user input; escaping alone is not a complete security fix." },
      { q: "What is RFC 4180 CSV quoting?", a: "The CSV standard says a field containing quotes, commas or newlines must be wrapped in double quotes, with any inner double quote written twice. The CSV mode applies exactly this rule." },
      { q: "Is my text uploaded anywhere?", a: "No. Escaping happens instantly in your browser with JavaScript, so your text never leaves your device." }
    ],
    tags: [
      "string escaper",
      "escape string online",
      "string escape tool",
      "escape quotes online",
      "escape double quotes",
      "escape newline characters",
      "escape backslash string",
      "java string escaper",
      "escape string java",
      "java escape quotes",
      "python string escaper",
      "escape string python",
      "python escape quotes online",
      "c# string escaper",
      "escape string csharp",
      "c# escape quotes",
      "sql string escaper",
      "escape single quotes sql",
      "sql escape quote online",
      "double single quotes sql",
      "csv escaper",
      "escape csv field",
      "csv quote escaping",
      "rfc 4180 escape",
      "escape special characters string",
      "multiline string to escaped",
      "convert newline to \\n",
      "escape tab character",
      "escape carriage return",
      "string literal escaper",
      "paste text escape for code",
      "escape string for programming",
      "online string escaper free",
      "escape text online free",
      "escape string for code",
      "how to escape quotes in java",
      "how to escape quotes in python",
      "how to escape quotes in c#",
      "java string escape rules",
      "python string escape sequences",
      "c# verbatim vs escaped string",
      "sql string literal escaping",
      "mysql escape single quote",
      "postgres escape single quote",
      "sql server escape quote",
      "csv field with quotes",
      "csv escape double quotes",
      "wrap csv field in quotes",
      "escape commas in csv",
      "text to csv safe string",
      "escape string copy paste",
      "string escaper no signup",
      "free string escaper tool"
    ],
  };

export default seo;
