import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "String Masker - Free Online Text Obfuscator Tool | IconVault",
    metaDescription: "Mask emails, phone numbers and sensitive text before sharing: keep first or last characters, pick a mask symbol. Free, in your browser.",
    about: [
      "**IconVault**'s **String Masker** hides **sensitive text** before you share it in screenshots, tickets, docs or demos. Paste a list of items, one per line, and **mask the middle characters** while keeping the **first N and last N characters** visible, turning an API key like `Secret12345` into `S*********2345`. Choose a mask character such as *, #, the bullet, x or _.",
      "Dedicated **presets** handle the two most common cases: **emails** are masked to `j***@gmail.com`, keeping the domain readable, and **phone numbers** keep only the last 4 digits. Everything runs **fully in your browser**, so the original unmasked values are never uploaded, and it is **free** to try."
    ],
    faqs: [
      { q: "What is string masking?", a: "Masking replaces the sensitive middle of a string with a mask character while keeping a few leading or trailing characters visible, so the value stays recognizable in context without exposing the secret." },
      { q: "Can I mask a whole list at once?", a: "Yes. Paste one item per line and every line is masked with the same settings, which is handy for lists of emails, phone numbers or keys." },
      { q: "How does the email preset work?", a: "It keeps the first character of the local part and the full domain, masking the rest, so john.doe@gmail.com becomes j***@gmail.com." },
      { q: "How does the phone preset work?", a: "It masks every character except the last 4 digits, so +1-555-0123 becomes ********0123." },
      { q: "Can the original value be recovered from the masked output?", a: "No. Masking is one-way: the hidden characters are replaced, not encrypted. And since everything runs in your browser, the originals never leave your device in the first place." },
      { q: "Is the String Masker free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "string masker",
      "string obfuscator",
      "mask text online",
      "obfuscate string online",
      "mask sensitive data",
      "data masking tool",
      "mask email address online",
      "email masker",
      "mask email for privacy",
      "hide email address",
      "mask phone number online",
      "phone number masker",
      "hide phone number digits",
      "mask credit card number",
      "mask api key",
      "hide api key",
      "obfuscate api key",
      "mask password text",
      "redact text online",
      "text redaction tool",
      "mask pii online",
      "pii masking tool",
      "hide personal data",
      "anonymize text online",
      "data anonymization tool",
      "mask list of emails",
      "bulk email masking",
      "mask multiple strings",
      "keep first and last characters",
      "show first last 4 characters",
      "mask middle of string",
      "replace characters with asterisks",
      "asterisk mask generator",
      "text obfuscation free",
      "online text masker free",
      "mask string online free",
      "pii redaction tool",
      "gdpr data masking",
      "mask data before sharing",
      "hide sensitive info screenshot",
      "mask data for demo",
      "mask customer data",
      "mask user emails",
      "partial mask email",
      "email obfuscation tool",
      "phone obfuscation",
      "mask phone digits online",
      "keep last 4 digits",
      "show only last 4 digits",
      "mask all but last 4",
      "custom mask character",
      "mask with hash symbol",
      "string masker no signup",
      "free string obfuscator",
      "obfuscate text online free",
      "mask confidential text"
    ],
  };

export default seo;
