import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Subnet Calculator - Free Online CIDR Subnet Calculator Tool | IconVault",
    metaDescription: "Get network, broadcast, first and last usable host, masks, wildcard and binary view for any IPv4 CIDR block. Free, in your browser.",
    about: [
      "**IconVault**'s **Subnet Calculator** breaks down any **IPv4 CIDR block** (like 192.168.1.0/24) into everything a network plan needs: the **network address**, **broadcast address**, **first and last usable host**, **subnet mask**, **wildcard mask**, **total addresses** and **usable host count**. A **binary view** shows the network, mask and broadcast in dotted-binary so you can see exactly which bits are network and which are host.",
      "Every value has a **one-click copy button**, and /31 and /32 edge cases are handled correctly. It is **free** and runs **100% in your browser** with nothing uploaded."
    ],
    faqs: [
      { q: "What does a subnet calculator do?", a: "You enter an IPv4 address in CIDR notation and it computes the network address, broadcast address, usable host range, subnet and wildcard masks, and address counts for that subnet." },
      { q: "What is CIDR notation?", a: "CIDR writes an IP address followed by a prefix length, like 192.168.1.0/24. The number after the slash says how many leading bits are the network portion; /24 means the first 24 bits, leaving 8 bits (256 addresses) for hosts." },
      { q: "How many usable hosts are in a /24?", a: "254. A /24 has 256 total addresses, but the network address and the broadcast address are reserved, leaving 254 usable for hosts." },
      { q: "What is a wildcard mask?", a: "The wildcard mask is the inverse of the subnet mask (every 0 becomes 1 and vice versa). It is used in router access lists and some firewall rules to specify which address bits to match." },
      { q: "Does it support IPv6?", a: "No. This calculator handles IPv4 CIDR blocks from /0 to /32 only; IPv6 subnets are not supported." },
      { q: "Is the Subnet Calculator free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "subnet calculator",
      "cidr calculator",
      "ip subnet calculator",
      "subnet calculator online",
      "cidr subnet calculator",
      "ipv4 subnet calculator",
      "subnet mask calculator",
      "calculate subnet mask",
      "network calculator",
      "ip network calculator",
      "broadcast address calculator",
      "find broadcast address",
      "network address calculator",
      "usable hosts calculator",
      "number of hosts in subnet",
      "how many hosts in /24",
      "/24 subnet hosts",
      "/16 subnet calculator",
      "/30 subnet usable hosts",
      "/27 subnet calculator",
      "/28 subnet calculator",
      "/29 subnet calculator",
      "/25 subnet calculator",
      "/23 subnet calculator",
      "subnet calculator /24",
      "cidr to subnet mask",
      "cidr notation explained",
      "what is cidr",
      "subnet mask cheat sheet",
      "subnetting calculator",
      "ip subnetting practice",
      "subnet calculator free",
      "online subnet calculator free",
      "wildcard mask calculator",
      "inverse subnet mask",
      "binary subnet calculator",
      "ip to binary converter",
      "subnet mask in binary",
      "first usable ip calculator",
      "last usable ip calculator",
      "ip range calculator",
      "cidr range calculator",
      "subnet ip range",
      "private ip subnet calculator",
      "192.168.1.0/24 explained",
      "10.0.0.0/8 subnets",
      "subnet calculator no signup",
      "network engineer tools",
      "ccna subnet calculator",
      "subnetting for beginners"
    ],
  };

export default seo;
