import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SVG Previewer - Free Online SVG Viewer Tool | IconVault",
    metaDescription: "Paste SVG markup or load a .svg file for instant validated preview with zoom and background options. Free, runs in your browser.",
    about: [
      "**IconVault**'s **SVG Previewer** renders any **SVG markup** instantly. **Paste your SVG code** or **load a .svg file**, and the tool **validates the XML** and shows a **live preview** the moment you type. Validation errors are reported with the parser's message, so broken markup is easy to spot and fix.",
      "**Zoom** from 10% to 400% to inspect fine details, and switch the preview **background** between a **transparency checker**, **white** and **dark** to check how the graphic looks in different contexts. **Download** the validated file as **.svg** or copy the code back out. It is **free** and runs **100% in your browser**."
    ],
    faqs: [
      { q: "How do I preview an SVG?", a: "Paste your SVG markup into the editor or click Load .svg file to read one from your computer. The preview renders live as you type." },
      { q: "What happens if my SVG has an error?", a: "The tool parses the markup as XML and shows the parser's error message with the offending detail, so you can find and fix the problem instead of staring at a blank box." },
      { q: "Why is my SVG not showing anything?", a: "Common causes: the root element is not <svg>, unclosed tags, or an unescaped & or < in the markup. The validator message usually points at the exact issue." },
      { q: "What is the checker background for?", a: "The checkerboard pattern marks transparent areas, so you can tell whether empty-looking regions are actually transparent or rendered white." },
      { q: "Can I download the SVG?", a: "Yes. Once the markup validates, the Download .svg button saves it as a file, and you can also copy the code to the clipboard." },
      { q: "Is the SVG Previewer free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "svg previewer",
      "svg viewer online",
      "preview svg online",
      "svg preview online free",
      "view svg file online",
      "open svg file online",
      "svg file viewer",
      "svg code preview",
      "paste svg preview",
      "svg markup preview",
      "svg validator online",
      "validate svg online",
      "check svg code",
      "svg xml validator",
      "svg error checker",
      "test svg code online",
      "svg tester",
      "svg playground",
      "svg editor with preview",
      "live svg preview",
      "svg zoom viewer",
      "svg transparency checker",
      "view svg on checker background",
      "svg dark background preview",
      "svg file opener",
      "open .svg in browser",
      "svg viewer free",
      "online svg viewer free",
      "svg preview no signup",
      "render svg online",
      "svg renderer online",
      "display svg code",
      "svg to preview",
      "preview svg markup",
      "svg code tester online",
      "debug svg online",
      "fix svg not showing",
      "svg not rendering",
      "svg parser error",
      "svg root element check",
      "download svg file",
      "save svg online",
      "copy svg code",
      "svg preview tool",
      "best svg viewer online",
      "svg viewer for windows alternative online",
      "view vector file online",
      "svg image viewer",
      "online vector preview",
      "svg previewer free"
    ],
  };

export default seo;
