import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "SVG Path Editor - Free Online Bezier Path Tool | IconVault",
    metaDescription: "Draw SVG paths visually: click to add points, drag handles to shape Bezier curves, copy the path data or full SVG. Free, in your browser.",
    about: [
      "**IconVault**'s **SVG Path Editor** lets you draw **vector paths** on a **grid canvas** without hand-writing path data. **Click to add points**, then **drag points** to move them and drag the orange **Bezier handles** to shape curves. Choose the next point type from **line (L)**, **cubic Bezier (C)** or **quadratic (Q)**, and toggle **close path (Z)** to fill shapes.",
      "The **path data (d attribute)** updates live as you draw and can be copied with one click, along with a complete **copy-paste SVG snippet** ready for your page. Points can be selected, deleted or cleared entirely. It is **free** and runs **100% in your browser**."
    ],
    faqs: [
      { q: "What is an SVG path?", a: "An SVG path is a shape defined by the d attribute of a <path> element, using commands like M (move), L (line), C and Q (Bezier curves) and Z (close). It is how icons and illustrations are drawn in vector form." },
      { q: "Do I need to know path syntax to use the editor?", a: "No. You draw visually by clicking and dragging, and the editor generates the d attribute for you, which makes it a good way to learn what each command does." },
      { q: "What are the orange Bezier handles?", a: "They are the curve control points. Dragging a handle changes the tangent and pull of the curve at that point, which is how you shape smooth cubic and quadratic Bezier segments." },
      { q: "Can I import an existing path to edit it?", a: "Not currently. The editor starts from a blank canvas, so it is best for creating new paths; copy the generated d attribute into your own file afterward." },
      { q: "How do I use the output in my project?", a: "Copy the path data and paste it as the d attribute of a <path> element, or use the Copy SVG button to get a complete standalone <svg> snippet you can drop into HTML or save as a file." },
      { q: "Is the SVG Path Editor free?", a: "Yes, it is free to try with no signup. Heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "svg path editor",
      "svg path editor online",
      "bezier path editor",
      "svg bezier curve editor",
      "draw svg path online",
      "svg path maker",
      "svg path generator",
      "create svg path",
      "svg d attribute generator",
      "generate svg path data",
      "svg path data editor",
      "edit svg path online",
      "visual svg editor",
      "svg curve editor",
      "bezier curve maker online",
      "cubic bezier editor",
      "quadratic bezier editor",
      "svg line path tool",
      "svg path drawer",
      "draw vector path online",
      "svg path tool free",
      "free svg path editor",
      "svg path editor no signup",
      "svg path commands",
      "svg m l c q z",
      "svg path d explained",
      "what is svg path data",
      "svg path syntax",
      "svg path tutorial",
      "learn svg paths",
      "svg path cheat sheet",
      "copy svg path data",
      "svg path to code",
      "svg path snippet generator",
      "vector path editor online",
      "online vector drawing tool",
      "simple svg editor",
      "svg shape maker",
      "svg icon path editor",
      "make svg icons online",
      "draw svg icon",
      "svg path for icons",
      "svg path grid editor",
      "snap to grid svg",
      "svg path coordinates",
      "get coordinates from svg path",
      "svg path point editor",
      "drag bezier handles",
      "bezier handle editor online",
      "svg path builder"
    ],
  };

export default seo;
