import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "systemd Generator - Free Online Linux Service File Tool | IconVault",
    metaDescription: "Build production-ready systemd unit files visually: ExecStart, restart policy, env vars and security hardening. Copy or download free.",
    about: [
      "**IconVault**'s **systemd Generator** builds a complete **.service unit file** from a simple form, so you never hand-write **systemd syntax** again. Fill in the **service name**, **Description**, **Type**, **ExecStart** (plus optional ExecStop and ExecReload), **User**, **Group** and **WorkingDirectory**, choose a **Restart policy** like on-failure, and watch a live preview of the exact unit file update as you type.",
      "The tool also covers the parts most tutorials skip: an **environment variables** editor and one-click **security hardening** toggles (**NoNewPrivileges**, **PrivateTmp**, **ProtectSystem**, **ProtectHome** and more). Everything runs **fully in your browser**, is **free** to try (repeat use may ask for Pro), and outputs a ready-to-save file with the **daemon-reload and enable commands** you need to install it. Always review paths and the ExecStart command before enabling a unit on a real server."
    ],
    faqs: [
      { q: "What is a systemd unit file?", a: "A systemd unit file is a plain-text config (usually ending in .service) that tells Linux's systemd how to start, stop and supervise a program. It lives in /etc/systemd/system/ and defines things like the command to run, which user runs it, and what to do if it crashes." },
      { q: "Where do I save the generated file?", a: "Save it as /etc/systemd/system/<name>.service, then run systemctl daemon-reload followed by systemctl enable --now <name>. Installing units requires root or sudo, and the tool shows these commands in the preview." },
      { q: "Which restart policy should I pick?", a: "on-failure is the safe default: it restarts your app only when it crashes, not on a clean exit. Use always for processes that must stay up constantly, and no for one-shot tasks like backups." },
      { q: "What do the security hardening toggles do?", a: "They add sandbox directives such as NoNewPrivileges (blocks privilege escalation), PrivateTmp (gives the service its own /tmp) and ProtectSystem (makes system directories read-only). They shrink what a compromised service can touch. Test them first, since over-strict settings can break apps that need those paths." },
      { q: "Can I use this for a Node, Python or Go app?", a: "Yes. Put your runtime in ExecStart (for example /usr/bin/node /opt/myapp/server.js), set the working directory and user, add PORT or NODE_ENV in the environment section, and pick on-failure as the restart policy." },
      { q: "Is anything uploaded to a server?", a: "No. The generator runs entirely in your browser. Your commands, users and environment values never leave your device." }
    ],
    tags: [
      "systemd generator",
      "systemd service generator",
      "systemd unit file generator",
      "create systemd service",
      "generate systemd service file",
      "systemd service file creator",
      "systemd unit creator online",
      "make a systemd service",
      "systemd service builder",
      "linux service generator",
      "systemd service file example",
      "systemd unit file example",
      "how to create a systemd service",
      "systemd service tutorial",
      "write a systemd service file",
      "systemd ExecStart generator",
      "systemd restart policy",
      "systemd restart on failure",
      "systemd RestartSec example",
      "systemd WorkingDirectory",
      "systemd environment variables",
      "systemd NoNewPrivileges",
      "systemd PrivateTmp",
      "systemd ProtectSystem",
      "systemd ProtectHome",
      "systemd security hardening",
      "harden systemd service",
      "systemd sandbox service",
      "run app as systemd service",
      "systemd service for node app",
      "systemd service for python script",
      "systemd service for go binary",
      "systemd service for java jar",
      "start program on linux boot",
      "auto start app on ubuntu boot",
      "systemctl enable service",
      "systemd service on ubuntu",
      "systemd service on debian",
      "systemd service on centos",
      "systemd service raspberry pi",
      "simple systemd service example",
      "oneshot systemd service",
      "systemd timer vs service",
      "systemd service type simple",
      "systemd service WantedBy multi-user.target",
      "systemd After network.target",
      "systemd service as non root user",
      "copy systemd unit file online",
      "download systemd service file",
      "systemd unit file syntax checker",
      "free systemd generator online",
      "systemd service generator free"
    ],
  };

export default seo;
