import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Table Generator - Free Online Table Maker Tool | IconVault",
    metaDescription: "Design a table in an editable grid and export it as HTML, Markdown, CSV, JSON, LaTeX or ASCII. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Table Generator** lets you build a table by clicking cells in an **editable grid**, then export it instantly in the format you need. Add or remove **rows and columns**, toggle a **header row**, and flip between **HTML**, **Markdown**, **CSV**, **JSON**, **LaTeX** and **ASCII art** with one click, with special characters properly escaped for each format.",
      "Writing tables by hand is slow and error-prone, especially **Markdown pipes** and **LaTeX tabulars**, so this tool does the tedious formatting for you. It is **free** to try and runs **fully in your browser** (editing and copying are unlimited, downloads use a free trial), so your data never leaves your device. Perfect for docs, README files, spreadsheets, papers and forum posts."
    ],
    faqs: [
      { q: "What formats can I export my table to?", a: "HTML, Markdown, CSV, JSON, LaTeX and ASCII art. Each output is generated with correct escaping: HTML entities, CSV quoting, LaTeX special characters and ASCII borders." },
      { q: "How big can my table be?", a: "Tables support up to 30 rows and 12 columns, which covers most documentation and data-exchange use cases without the page slowing down." },
      { q: "Is there a Markdown table generator here?", a: "Yes. Select the Markdown tab and the tool outputs a pipe-delimited table with a header separator row, ready to paste into GitHub, Notion, Obsidian or any Markdown renderer." },
      { q: "Can I generate an HTML table?", a: "Yes. The HTML export produces a clean table with thead and tbody, th header cells and escaped content, ready to drop into a webpage." },
      { q: "How do I make a LaTeX table?", a: "Build your table in the grid, switch to LaTeX, and copy the generated tabular environment with hlines. Ampersands, percent signs, underscores and other special characters are escaped automatically." },
      { q: "Is my data uploaded anywhere?", a: "No. The table is built and exported entirely in your browser. Nothing is sent to a server." }
    ],
    tags: [
      "table generator",
      "online table generator",
      "free table generator",
      "table maker online",
      "create table online",
      "html table generator",
      "generate html table",
      "html table creator",
      "make html table online",
      "markdown table generator",
      "markdown table maker",
      "create markdown table",
      "markdown table generator online",
      "github markdown table generator",
      "csv table generator",
      "table to csv converter",
      "make csv table online",
      "json table generator",
      "table to json converter",
      "convert table to json",
      "latex table generator",
      "latex table maker online",
      "generate latex tabular",
      "create latex table",
      "ascii table generator",
      "text table generator",
      "ascii art table maker",
      "plain text table generator",
      "table to markdown converter",
      "table to html converter",
      "table to latex converter",
      "table to ascii converter",
      "convert csv to markdown table",
      "convert csv to html table",
      "spreadsheet to markdown table",
      "excel to markdown table",
      "table generator for readme",
      "readme table generator",
      "notion table to markdown",
      "forum table generator",
      "bbcode table generator alternative",
      "table generator with header row",
      "editable table online",
      "table editor online free",
      "draw a table online",
      "data table maker",
      "comparison table generator",
      "pricing table generator",
      "table generator no signup",
      "table generator without login",
      "copy table as html",
      "download table as csv",
      "table export tool free"
    ],
  };

export default seo;
