import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Tailwind Color Finder - Free Online Tailwind Palette Tool | IconVault",
    metaDescription: "Paste any hex color and find the closest Tailwind shade (like sky-500) with weighted RGB matching. Free, in your browser.",
    about: [
      "**IconVault**'s **Tailwind Color Finder** takes any **hex color** and finds the **closest Tailwind CSS shade** using **weighted RGB distance**, so a brand color like #0ea5e9 resolves instantly to **sky-500** with its exact hex value. You get the best match plus **7 runner-up shades**, a side-by-side visual comparison, and one-click **copy of the class name** or hex.",
      "It searches the full **Tailwind default palette**: black, white and all 11 shades of the 22 color ramps (slate, red, emerald, sky and more). Everything runs **fully in your browser** and is **free** to try, which makes it ideal for converting design mockups, Figma colors or legacy CSS values into clean Tailwind utility classes."
    ],
    faqs: [
      { q: "How do I convert a hex color to a Tailwind class?", a: "Paste the hex code into the tool and click Find closest shade. It returns the nearest Tailwind class (for example sky-500) with a copy button, using weighted RGB distance across the whole default palette." },
      { q: "How accurate is the closest shade matching?", a: "The tool uses a redmean-style weighted Euclidean distance on RGB values, which approximates human color perception better than a naive distance. It finds the mathematically nearest palette entry, though a designer may still prefer a nearby shade for brand consistency." },
      { q: "Does it work with Tailwind v4?", a: "The default palette (shade names and hex values) is the same in Tailwind v3 and v4, so the matches apply to both versions." },
      { q: "What colors are in the palette?", a: "Black, white, and the full 50 to 950 ramps for slate, gray, zinc, neutral, stone, red, orange, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink and rose." },
      { q: "Can I copy the class name directly?", a: "Yes. Each result has a copy button for the class name and the hex value, so you can paste them straight into your markup." },
      { q: "Is it really free?", a: "Yes, lookups are free to try with no signup. Heavier repeated use may prompt an upgrade to Pro for unlimited lookups." }
    ],
    tags: [
      "tailwind color finder",
      "find closest tailwind color",
      "hex to tailwind color",
      "tailwind shade finder",
      "tailwind color matcher",
      "convert hex to tailwind class",
      "hex to tailwind class converter",
      "color to tailwind class",
      "closest tailwind class",
      "tailwind palette search",
      "search tailwind colors",
      "tailwind color palette finder",
      "tailwind color lookup",
      "tailwind hex lookup",
      "what tailwind color is this",
      "identify tailwind color from hex",
      "tailwind color name finder",
      "tailwind color picker tool",
      "tailwind v3 color palette",
      "tailwind v4 color palette",
      "tailwind default colors list",
      "tailwind color shades",
      "tailwind sky-500 hex",
      "tailwind blue-600 hex",
      "tailwind red-500 hex",
      "tailwind emerald-500 hex",
      "tailwind slate colors",
      "tailwind neutral palette",
      "tailwind zinc vs gray",
      "rgb to tailwind class",
      "convert rgb to tailwind",
      "figma color to tailwind",
      "convert figma colors to tailwind",
      "brand color to tailwind",
      "design to tailwind colors",
      "css color to tailwind utility",
      "tailwind class from color picker",
      "pick color get tailwind class",
      "tailwind color distance",
      "nearest tailwind color online",
      "free tailwind color finder",
      "tailwind color tool free",
      "tailwind color converter online",
      "tailwind palette hex codes",
      "all tailwind colors with hex",
      "tailwind 950 shade colors",
      "tailwind color ramps",
      "tailwind gray scale shades",
      "matching brand colors in tailwind",
      "tailwind ui color matching"
    ],
  };

export default seo;
