import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Tailwind Converter - Free Online Tailwind to CSS Tool | IconVault",
    metaDescription: "Convert Tailwind utilities to plain CSS and back. Spacing, typography, display and layout tables. Free, in your browser.",
    about: [
      "**IconVault**'s **Tailwind Converter** translates **Tailwind utility classes** into **plain CSS declarations** and converts CSS back into Tailwind classes, using a static utility table covering **spacing**, **text sizes**, **font weights**, **display**, **layout** and other common utilities. Paste a class string or a CSS rule and get the equivalent output instantly.",
      "It is a quick reference and migration helper for moving between **Tailwind** and hand-written CSS: learn what p-4 or text-2xl actually compute to, or turn legacy **CSS declarations** into compact utilities. The tool is **free**, runs **fully in your browser**, and clearly notes it is best-effort over common utilities rather than a full Tailwind compiler."
    ],
    faqs: [
      { q: "Can I convert Tailwind classes to CSS?", a: "Yes. Paste Tailwind utilities and the tool maps each one to its CSS declaration using its built-in utility table, for example p-4 becomes padding: 1rem." },
      { q: "Can I convert CSS back to Tailwind?", a: "Yes, the reverse direction works for covered utilities: a CSS declaration like font-weight: 700 becomes font-bold. Values outside the table are left as-is." },
      { q: "Which utilities are supported?", a: "The converter covers common utilities: spacing scale, text sizes, font weights, display modes and layout helpers. It is a static table, not the full Tailwind engine, so arbitrary values and variants may not translate." },
      { q: "Is this a replacement for the Tailwind compiler?", a: "No. It is a lightweight reference and migration helper. It does not handle variants (hover:, md:), custom theme values, plugins or the full Tailwind utility set." },
      { q: "What is p-4 in CSS?", a: "p-4 maps to padding: 1rem in Tailwind's spacing scale, where each step is 0.25rem. The tool shows these conversions instantly." },
      { q: "Does it cost anything or need signup?", a: "No. The converter is free to try and runs entirely in your browser with no account needed." }
    ],
    tags: [
      "tailwind converter",
      "tailwind to css converter",
      "convert tailwind to css",
      "tailwind classes to css",
      "tailwind utility to css",
      "css to tailwind converter",
      "convert css to tailwind",
      "css declarations to tailwind",
      "tailwind to vanilla css",
      "tailwind to plain css",
      "tailwind class translator",
      "tailwind utility translator",
      "what does tailwind class mean",
      "tailwind class to css rule",
      "tailwind spacing to css",
      "tailwind p-4 in css",
      "tailwind m-2 css equivalent",
      "tailwind text sizes css",
      "tailwind font weights css",
      "tailwind display utilities css",
      "tailwind flex css equivalent",
      "tailwind grid css equivalent",
      "tailwind to css online free",
      "free tailwind to css",
      "tailwind css decoder",
      "decode tailwind classes",
      "tailwind class reference",
      "tailwind utility reference",
      "tailwind cheat sheet converter",
      "learn tailwind utilities",
      "tailwind for beginners css mapping",
      "migrate from tailwind to css",
      "remove tailwind convert to css",
      "migrate css to tailwind",
      "convert legacy css to tailwind",
      "tailwind migration helper",
      "tailwind class lookup tool",
      "tailwind utility lookup",
      "tailwind to inline styles",
      "tailwind to style attribute",
      "css to utility classes",
      "atomic css converter",
      "utility first css converter",
      "tailwind arbitrary values converter",
      "tailwind rem values",
      "tailwind spacing scale chart",
      "tailwind to css table",
      "online tailwind converter",
      "tailwind converter no signup",
      "tailwind reverse converter"
    ],
  };

export default seo;
