import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Team Randomizer - Free Online Random Team Generator | IconVault",
    metaDescription: "Split any name list into fair random teams. Choose team count or size, avoid repeat pairings, replay from a seed. Free, in your browser.",
    about: [
      "**IconVault**'s **Team Randomizer** splits a pasted **name list** into fair, **random teams** in one click. Choose split by **number of teams** or by **team size**, and the tool shuffles names evenly so every team comes out balanced. An **avoid-repeat** mode remembers past splits in your browser and reshuffles if it detects a pairing you have already used.",
      "Every split gets a **seeded random draw**, so you can reproduce or share the exact same teams later, and results are easy to **copy** for chat or email. It is **free**, runs **fully in your browser**, and is perfect for sports captains, teachers, hackathons, office games and tournament brackets."
    ],
    faqs: [
      { q: "How do I split names into random teams?", a: "Paste one name per line, choose split by team count or team size, and click shuffle. The tool distributes names evenly across teams at random." },
      { q: "Can I make teams of equal size?", a: "Yes. Pick the team size mode and enter how many people per team. If the names do not divide evenly, the tool spreads the remainder fairly instead of leaving one tiny team." },
      { q: "What does avoid repeat pairings do?", a: "It stores signatures of past splits in your browser's local storage and automatically reshuffles if a new draw would repeat a previous team combination, so weekly games stay fresh." },
      { q: "Can I reproduce the same teams later?", a: "Yes. Each draw uses a seeded random shuffle, and the seed is shown with the results. Re-entering the same seed with the same name list reproduces the identical split." },
      { q: "Is the shuffle really random?", a: "It uses a seeded PRNG (mulberry32) driving a Fisher-Yates shuffle, which is fair and unbiased. Because it is seeded, it is reproducible rather than cryptographically random, which is exactly what you want for team draws." },
      { q: "Is it free and private?", a: "Yes. It is free to use, runs entirely in your browser, and your name lists are never uploaded." }
    ],
    tags: [
      "team randomizer",
      "random team generator",
      "team generator",
      "random team picker",
      "team picker",
      "split into random teams",
      "divide into teams randomly",
      "random group generator",
      "random team maker",
      "make random teams",
      "generate random teams",
      "team shuffler",
      "shuffle teams",
      "random team divider",
      "split names into teams",
      "name list to teams",
      "fair team generator",
      "balanced team generator",
      "random teams of 2",
      "random teams of 3",
      "random teams of 4",
      "random teams of 5",
      "split into 2 teams",
      "split into 3 teams",
      "split into 4 teams",
      "split class into groups",
      "classroom group generator",
      "student group randomizer",
      "random student groups",
      "sports team randomizer",
      "football team picker",
      "cricket team randomizer",
      "basketball team generator",
      "hackathon team generator",
      "office team randomizer",
      "team building randomizer",
      "secret santa team splitter",
      "tournament team generator",
      "bracket team randomizer",
      "gaming team randomizer",
      "esports team picker",
      "pub quiz team generator",
      "workshop group randomizer",
      "seeded team generator",
      "reproducible random teams",
      "random teams no repeat",
      "avoid same teams twice",
      "free team randomizer",
      "online team randomizer free",
      "team randomizer no signup"
    ],
  };

export default seo;
