import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Terraform Generator - Free Online Terraform Config Tool | IconVault",
    metaDescription: "Build Terraform HCL visually for AWS, GCP and Azure: resources, variables and live preview. Copy or download free.",
    about: [
      "**IconVault**'s **Terraform Generator** builds **Terraform HCL** from a visual form instead of hand-written config. Pick a **provider** (**AWS**, **GCP** or **Azure**), add **resources** like EC2 instances, S3 buckets and RDS databases through guided pickers, define **custom variables**, and watch the **live HCL output** update as you configure.",
      "It is built as an honest **starter scaffold**: a fast way to get valid config structure, provider blocks and resource skeletons that you then review and extend. Everything runs **fully in your browser** and is **free** to try, with **copy and download** of the generated .tf content. Always run terraform plan and review before applying to real infrastructure."
    ],
    faqs: [
      { q: "What does this Terraform generator create?", a: "It generates starter Terraform HCL: a provider block for AWS, GCP or Azure, resource blocks for the resources you pick (for example EC2, S3, RDS), and any custom variables you define. It is scaffolding to build on, not a complete production module." },
      { q: "Which cloud providers are supported?", a: "AWS (hashicorp/aws), Google Cloud (hashicorp/google) and Azure (hashicorp/azurerm). You pick one provider per generated config." },
      { q: "Can I generate an EC2 instance config?", a: "Yes. Choose AWS, add the EC2 instance resource, and fill in the name tag, AMI and instance type. The HCL preview updates live and can be copied or downloaded." },
      { q: "Is the generated code production-ready?", a: "Treat it as a starting point. It gives you valid structure, but production use needs your own review: correct AMIs, regions, networking, IAM, state backend and secrets handling, plus a terraform plan before apply." },
      { q: "How do I use the output?", a: "Copy or download the HCL into a main.tf file, run terraform init and terraform plan, review the plan carefully, then terraform apply." },
      { q: "Is my infrastructure data uploaded?", a: "No. The builder runs entirely in your browser. Your resource names and values never leave your device." }
    ],
    tags: [
      "terraform generator",
      "terraform config generator",
      "generate terraform code",
      "terraform hcl generator",
      "terraform builder online",
      "terraform file generator",
      "create terraform config",
      "terraform template generator",
      "terraform ec2 generator",
      "terraform s3 bucket generator",
      "terraform rds generator",
      "aws terraform generator",
      "terraform aws ec2 example",
      "terraform aws s3 example",
      "gcp terraform generator",
      "terraform gcp example",
      "azure terraform generator",
      "terraform azure example",
      "terraform provider block generator",
      "terraform variables generator",
      "terraform resource generator",
      "terraform module generator",
      "terraform starter template",
      "terraform boilerplate",
      "terraform scaffold",
      "terraform skeleton generator",
      "iac generator online",
      "infrastructure as code generator",
      "terraform for beginners",
      "learn terraform online",
      "terraform tutorial generator",
      "terraform main.tf generator",
      "terraform init example",
      "terraform plan explained",
      "hcl generator",
      "hcl config generator",
      "hashicorp configuration language tool",
      "terraform visual builder",
      "visual terraform editor",
      "terraform gui tool",
      "terraform online editor",
      "free terraform generator",
      "terraform generator free online",
      "terraform config no signup",
      "terraform aws beginner template",
      "terraform multi cloud",
      "terraform resource picker",
      "generate terraform from form",
      "terraform code builder",
      "terraform config builder free",
    ],
  };

export default seo;
