import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Text Shadow Generator - Free Online CSS Text Effect Tool | IconVault",
    metaDescription: "Design layered CSS text shadows visually: offsets, blur, color and opacity. Live preview, copy the CSS. Free, in your browser.",
    about: [
      "**IconVault**'s **Text Shadow Generator** lets you build **layered CSS text shadows** with sliders instead of guessing numbers. Stack multiple **shadow layers**, tune each layer's **X and Y offset**, **blur radius**, **color** and **opacity**, reorder or remove layers, and watch the **live preview** update on your own text, font size, text color and background.",
      "Layered shadows are how designers create **3D depth**, **neon glow**, **retro** and **long-shadow** effects, and this tool outputs clean, copy-ready **text-shadow CSS** for all of it. It is **free** to try, runs **fully in your browser**, and the trial is only counted when you copy the CSS."
    ],
    faqs: [
      { q: "How do I create a CSS text shadow?", a: "Add a layer, set its X and Y offsets, blur and color, and preview it live. The tool generates the text-shadow declaration for you to copy, for example text-shadow: 2px 2px 4px rgba(0,0,0,0.5)." },
      { q: "Can I stack multiple text shadows?", a: "Yes. Add as many layers as you like and reorder them with the up and down controls. Multiple comma-separated shadows are how glow, outline and 3D effects are built." },
      { q: "How do I make a neon glow text effect?", a: "Stack several layers with zero offsets, increasing blur radii and a bright color like cyan or magenta. The layered blurs blend into a glow." },
      { q: "How do I make a 3D text effect?", a: "Add many 1px-stepped layers with no blur in a dark color. Each offset layer builds a solid extruded edge behind the text." },
      { q: "What do the text-shadow values mean?", a: "The syntax is text-shadow: offset-x offset-y blur-radius color. Offsets move the shadow, blur softens it, and color sets its tint. Opacity is handled through rgba colors." },
      { q: "Is it free?", a: "Yes. Designing and previewing is free and unlimited; copying the CSS uses the free trial, and Pro unlocks unlimited use." }
    ],
    tags: [
      "text shadow generator",
      "css text shadow generator",
      "text shadow css",
      "text shadow maker",
      "css text shadow maker",
      "text shadow creator",
      "generate text shadow css",
      "text shadow css generator online",
      "layered text shadow",
      "multiple text shadows css",
      "stacked text shadow",
      "text shadow blur",
      "text shadow offset",
      "text shadow color",
      "text shadow opacity",
      "3d text shadow generator",
      "3d text effect css",
      "extruded text css",
      "neon text generator",
      "neon glow text css",
      "glow text effect",
      "retro text shadow",
      "vintage text effect css",
      "long shadow text generator",
      "long shadow css",
      "drop shadow text",
      "text drop shadow css",
      "css text effects generator",
      "text effect generator css",
      "fancy text css generator",
      "cool text shadows",
      "text shadow examples",
      "text shadow copy paste",
      "copy paste text shadow css",
      "text shadow code generator",
      "css text shadow tool",
      "online text shadow editor",
      "visual text shadow editor",
      "text shadow preview",
      "live text shadow preview",
      "text shadow with custom text",
      "font shadow generator",
      "heading shadow generator",
      "title text shadow",
      "button text shadow css",
      "free text shadow generator",
      "text shadow generator no signup",
      "css generator text shadow",
      "text-shadow property generator",
      "css text shadow playground",
    ],
  };

export default seo;
