import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Text on Image - Free Online Tool | IconVault",
    metaDescription: "Add styled, draggable text layers to any photo. Custom fonts, colors, shadows. Export JPG, PNG or WebP. Free.",
    about: [
      "**IconVault**'s **Text on Image** tool lets you overlay professional-looking text on any photo: **add text** layers, drag each one anywhere on the canvas, and style them individually with **font, size, color, bold and shadow** controls. Multi-line text is supported, and everything renders in a live preview.",
      "When you are happy, export in the **original format, JPG, PNG or WebP** at full resolution. Great for quotes, thumbnails, announcements and watermark-style captions. All editing happens **in your browser**: your images never leave your device. **Free** with a daily trial, unlimited with Pro.",
    ],
    faqs: [
      { q: "How many text layers can I add?", a: "Up to eight text layers. Click a layer in the list to select it, then edit its text, font, size, color, bold and shadow settings independently." },
      { q: "How do I position the text?", a: "Drag any text layer directly on the preview canvas. It follows your cursor and re-renders live so you can place captions exactly where you want them." },
      { q: "Which fonts are available?", a: "Inter, Arial, Georgia, Times New Roman, Courier New, Impact and Comic Sans MS, covering clean sans-serif, classic serif, monospace and display styles." },
      { q: "What export formats are supported?", a: "Same as original, JPG, PNG or WebP, all at the source image's full resolution. JPG exports get a white background fill so transparent areas stay clean." },
      { q: "Is my photo uploaded to a server?", a: "No. All text rendering happens on canvas in your browser. Nothing leaves your device." },
      { q: "Is it free to use?", a: "Yes, with a daily free trial limit. IconVault Pro unlocks unlimited exports across all tools." },
    ],
    tags: [ "text on image", "add text to photo online", "image text editor", "caption photo online", "photo text overlay", "add captions to pictures", "text watermark image", "quote maker image", "thumbnail text tool", "drag text on photo", "photo typography tool", "add words to picture", "image caption generator", "text layers photo", "free photo text editor", "announcement image maker", "picture quote maker", "overlay text jpg", "png text overlay", "webp text on image" ,
      "add text to image",
      "text on photo",
      "photo text maker",
      "image text overlay",
      "write on photo online",
      "add text to picture",
      "photo caption maker",
      "image caption maker",
      "quote on image maker",
      "motivational quote image maker",
      "birthday wish photo maker",
      "greeting card text photo",
      "festival wish image maker",
      "diwali greeting image maker",
      "text on photo for whatsapp",
      "good morning image maker",
      "announcement photo maker",
      "sale banner text maker",
      "poster text editor",
      "flyer text maker",
      "thumbnail text maker",
      "youtube thumbnail text",
      "cover photo text maker",
      "add heading to image",
      "curved text on image",
      "stylish fonts on photo",
      "3d text on photo",
      "neon text photo effect",
      "text with background box",
      "text shadow on image",
      "outline text photo",
      "multi line text image",
      "text alignment photo tool",
      "drag drop text photo",
      "photo text font changer",
      "add text to image free no signup",
      "text on image without watermark",
      "text on png online",
      "text on jpg online",
      "online photo text app"],
  };

export default seo;
