import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Text to Binary - Free Online Binary Converter Tool | IconVault",
    metaDescription: "Convert text to binary and binary back to text with UTF-8 support and custom delimiters. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Text to Binary** converter translates **text into binary** and decodes **binary back to text** in both directions. It is **UTF-8 aware**, so emoji and non-English characters encode correctly, and you can choose the **delimiter** between bytes (spaces, commas, none and more) to match whatever format you need.",
      "Binary input is validated with clear errors: the tool tells you if characters are not 0 or 1, if the length is not a multiple of 8, or if the bytes are not valid **UTF-8**. It is **free** and runs **fully in your browser**, which makes it handy for CS homework, encoding puzzles and learning how text is stored as bits."
    ],
    faqs: [
      { q: "How do I convert text to binary?", a: "Type or paste your text and the tool converts each UTF-8 byte to 8 bits, joined by your chosen delimiter. For example, A becomes 01000001." },
      { q: "How do I convert binary to text?", a: "Paste the binary (0s and 1s, whitespace allowed), and the tool groups it into bytes and decodes the UTF-8 text. Invalid input gets a specific error message instead of silent garbage." },
      { q: "Does it support emoji and non-English text?", a: "Yes. The converter works on UTF-8 bytes, not just ASCII, so emoji, accented characters and scripts like Hindi or Chinese encode and decode correctly." },
      { q: "What delimiters can I use?", a: "You can separate bytes with spaces, commas, newlines or no separator at all, depending on the format your assignment or tool expects." },
      { q: "Why does it say the length must be a multiple of 8?", a: "Each byte is 8 bits, so valid binary text must come in groups of 8. If your length is off, a digit is missing or extra somewhere." },
      { q: "Is it free?", a: "Yes. The converter is free to use and runs entirely in your browser with no signup." }
    ],
    tags: [
      "text to binary",
      "text to binary converter",
      "convert text to binary",
      "binary translator",
      "text to binary code",
      "binary code translator",
      "binary to text",
      "binary to text converter",
      "convert binary to text",
      "decode binary to text",
      "binary decoder",
      "binary to english",
      "translate binary to english",
      "english to binary translator",
      "binary encoder",
      "binary decoder online",
      "binary converter online",
      "free binary translator",
      "binary translator no signup",
      "utf-8 to binary",
      "binary to utf-8",
      "emoji to binary",
      "binary to emoji",
      "ascii to binary converter",
      "binary to ascii converter",
      "string to binary",
      "binary to string",
      "8 bit binary converter",
      "binary byte converter",
      "binary translator with spaces",
      "binary code generator",
      "binary code decoder",
      "learn binary code",
      "binary for beginners",
      "how to read binary",
      "how to write in binary",
      "binary alphabet translator",
      "binary alphabet chart",
      "binary numbers translator",
      "binary translator for students",
      "cs homework binary converter",
      "binary puzzle solver",
      "decode binary message",
      "secret binary message",
      "binary message translator",
      "binary text converter free",
      "online binary tool",
      "binary conversion tool",
      "text binary converter",
      "binary text tool online",
    ],
  };

export default seo;
