import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Text to Speech - Free Online Voice Reader Tool | IconVault",
    metaDescription: "Read any text aloud with your device's built-in voices. Voice picker, rate and pitch controls. Free, nothing uploaded.",
    about: [
      "**IconVault**'s **Text to Speech** reads your text aloud using your **device's built-in voices** through the **Web Speech API**. Pick from the **voices** installed on your phone or computer, adjust the **speaking rate** and **pitch**, and use **play, pause and stop** controls while it reads.",
      "It is handy for **proofreading** (hearing your writing catches errors your eyes miss), **accessibility**, language practice and listening to articles hands-free. It is **free**, runs **fully in your browser**, and **nothing is uploaded**: speech is synthesized locally by your device, so the available voices depend on your system."
    ],
    faqs: [
      { q: "How do I make text read aloud?", a: "Paste your text into the box, pick a voice, and press play. Your device's speech synthesis reads it back with the rate and pitch you set." },
      { q: "Which voices are available?", a: "The tool lists every voice your device provides through the Web Speech API. Chrome on desktop usually has many, including Google voices; phones expose their system voices. Availability varies by device and browser." },
      { q: "Can I change the speed and pitch?", a: "Yes. Sliders control the speaking rate (slower or faster) and pitch (lower or higher), so you can tune the voice to your preference." },
      { q: "Does it work offline?", a: "It depends on the voice: some system voices are local and work offline, while others (like some Chrome voices) need a network connection to Google's servers." },
      { q: "Is my text uploaded to a server?", a: "No. Synthesis happens on your device through the browser's Web Speech API. Your text never leaves your computer or phone." },
      { q: "Can I use it for proofreading?", a: "Yes, that is one of its best uses. Listening to your draft read aloud surfaces awkward phrasing, missing words and run-on sentences that silent reading misses." }
    ],
    tags: [
      "text to speech",
      "text to speech online",
      "free text to speech",
      "text to speech free",
      "tts online",
      "free tts online",
      "text to voice",
      "text to voice generator",
      "read text aloud",
      "read aloud online",
      "read my text aloud",
      "text reader online",
      "online text reader",
      "voice reader online",
      "text to speech reader",
      "text to speech converter",
      "convert text to speech",
      "text to audio",
      "text to audio online",
      "speak text online",
      "text speaker online",
      "voice over text",
      "narration generator free",
      "ai voice reader",
      "robot voice text to speech",
      "natural voice text to speech",
      "male voice text to speech",
      "female voice text to speech",
      "english text to speech",
      "hindi text to speech",
      "spanish text to speech",
      "text to speech with voice selection",
      "text to speech speed control",
      "text to speech pitch control",
      "proofreading text to speech",
      "listen to text",
      "listen to article online",
      "read article aloud",
      "accessibility text reader",
      "dyslexia reading tool",
      "text to speech for students",
      "text to speech for essays",
      "speech synthesis online",
      "web speech api demo",
      "browser text to speech",
      "text to speech no signup",
      "text to speech without download",
      "paste text listen",
      "online voice generator free",
      "text to speech tool online",
    ],
  };

export default seo;
