import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Timezone Converter - Free Online Time Tool | IconVault",
    metaDescription: "Convert any time between world timezones and plan meetings across 4 zones at once. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Timezone Converter** converts any date and time between **world timezones** instantly, showing the result in each zone with **daylight saving** handled by the browser's own timezone data. The built-in **meeting planner** lines up four zones side by side so you can pick a slot that works for everyone on the call.",
      "All conversion happens **in your browser**, nothing is uploaded, and the tool is **free** with no signup. The honest note: results rely on your browser's timezone database, which is usually current, but double-check against an official source before booking flights or legal deadlines."
    ],
    faqs: [
      { q: "How do I convert a time to another timezone?", a: "Pick the source timezone, enter the date and time, and the tool shows the equivalent time in your chosen zones, with DST applied automatically." },
      { q: "What is the meeting planner for?", a: "It shows the same moment across up to 4 timezones side by side, so a distributed team can scan for overlapping working hours when scheduling." },
      { q: "Does it handle daylight saving time?", a: "Yes. Conversions use the IANA timezone database built into your browser, which includes DST rules for each zone." },
      { q: "Is my input sent to a server?", a: "No. Everything is computed locally in your browser. No account, no tracking, no uploads." },
      { q: "Can I convert past or future dates?", a: "Yes. Any date works, and historical and future DST rules come from the same timezone database." },
      { q: "Is it free?", a: "Yes, completely free with no signup." }
    ],
    tags: [
      "timezone converter",
      "time zone converter",
      "convert time zones",
      "world time converter",
      "time converter online",
      "est to ist converter",
      "pst to ist time converter",
      "est to pst converter",
      "gmt to ist converter",
      "cet to est converter",
      "ist to est time",
      "utc to local time converter",
      "meeting time zone planner",
      "world clock meeting planner",
      "schedule meeting across time zones",
      "best time for global meeting",
      "time zone overlap calculator",
      "4 time zone converter",
      "compare time zones",
      "what time is it in",
      "current time in time zones",
      "daylight saving time converter",
      "dst aware time converter",
      "convert pst to gmt",
      "convert est to gmt",
      "cst to ist converter",
      "aest to pst converter",
      "jst to est converter",
      "uk time to india time",
      "usa time to india time",
      "time difference calculator zones",
      "hours difference between time zones",
      "international time converter",
      "remote team meeting scheduler",
      "free timezone converter no signup",
      "time zone calculator online",
      "convert 3pm est to ist",
      "9am pst in ist",
      "5pm gmt in est",
      "time zone map converter",
      "world time buddy alternative",
      "multi zone time converter",
      "business hours overlap tool",
      "convert time for zoom meeting",
      "timezone friendly scheduling",
      "what time is 12pm utc in ist",
      "convert epoch to timezone",
      "time converter with date",
      "global call time planner",
      "timezone converter app free",
      "find common meeting time zones",
      "convert local time to utc",
      "utc time converter online"
    ],
  };

export default seo;
