import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Time Duration Calculator - Free Online Date Tool | IconVault",
    metaDescription: "Calculate the exact duration between two dates or add and subtract time from any date. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Time Duration Calculator** gives you the exact time between any two **dates and times**, broken into days, hours, minutes and seconds plus total hours, minutes and seconds. A second mode **adds or subtracts** a duration (days, hours, minutes) from any date, so you can answer questions like what date is 90 days from now or what time was 36 hours ago.",
      "Everything computes **instantly in your browser** with no signup and nothing sent anywhere, and it is completely **free**. The honest note: calculations use your device's local calendar math, so results across **daylight saving changes** reflect your local timezone rules, double-check if you need legal or payroll precision."
    ],
    faqs: [
      { q: "How do I calculate the time between two dates?", a: "Enter a start and end date with times, then press calculate. You get the difference in days, hours, minutes and seconds, plus the total in hours, minutes and seconds." },
      { q: "Can I add or subtract days from a date?", a: "Yes. Switch to the add/subtract tab, enter a base date, set how many days, hours and minutes to add or remove, and the tool shows the resulting date and time." },
      { q: "Does it count negative durations?", a: "Yes. If the end date is before the start date, the tool flags the result as negative and still shows the exact magnitude." },
      { q: "Is the calculation done on a server?", a: "No. Everything runs in your browser using JavaScript date math. No data leaves your device." },
      { q: "Is it accurate across timezones and DST?", a: "It uses your browser's local timezone calendar. Around daylight saving transitions the raw hour count can shift by an hour, so verify against a calendar for contracts or payroll." },
      { q: "Is it free?", a: "Yes, completely free with no signup." }
    ],
    tags: [
      "time duration calculator",
      "date duration calculator",
      "time between two dates",
      "calculate time difference",
      "how many days between two dates",
      "hours between two dates",
      "date difference calculator",
      "time elapsed calculator",
      "add days to date calculator",
      "subtract days from date",
      "add hours to time",
      "date plus days calculator",
      "what date is 90 days from now",
      "what date was 30 days ago",
      "add time to date online",
      "subtract time from date",
      "duration in hours calculator",
      "convert days to hours minutes seconds",
      "time span calculator",
      "date math calculator",
      "add 24 hours to date",
      "calculate working hours between dates",
      "time calculator online free",
      "date time calculator",
      "minutes between two times",
      "seconds between two dates",
      "days hours minutes seconds calculator",
      "how long ago was date",
      "how long until date",
      "countdown duration calculator",
      "project duration calculator",
      "add weeks to date",
      "subtract hours from time",
      "date shift calculator",
      "time addition calculator",
      "time subtraction calculator",
      "exact age calculator days hours",
      "calculate duration online",
      "free date calculator no signup",
      "date arithmetic tool",
      "add months days to date",
      "time between timestamps",
      "elapsed time calculator",
      "interval calculator date",
      "date difference in days online",
      "how many hours between dates",
      "how many minutes between times",
      "duration calculator app free",
      "add subtract time calculator",
      "date calculator with time",
      "two date calculator",
      "time gap calculator",
      "what time will it be in x hours",
      "deadline calculator days"
    ],
  };

export default seo;
