import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Title Analyzer - Free Online SEO Headline Tool | IconVault",
    metaDescription: "Score your blog title across 16 headline elements with actionable fixes. Free, 100% in your browser, nothing uploaded.",
    about: [
      "**IconVault**'s **Title Analyzer** scores your headline across **16 headline elements**, including length, word balance, sentiment words, power words, numbers, question hooks and more, then gives you **actionable fixes** for each weak spot. You see exactly why a title scores the way it does instead of getting a mystery number.",
      "The analysis runs **100% in your browser**, so your drafts are **never uploaded**, and the tool is **free** with no signup. The honest note: scoring rules are heuristics distilled from headline best practices, not a Google ranking formula, so treat the score as a writing aid, not a traffic guarantee."
    ],
    faqs: [
      { q: "What does the title analyzer check?", a: "16 headline elements: character and word length, common/uncommon/emotional/power word balance, sentiment, numbers, question or how-to hooks, reading grade hints, keyword placement and more." },
      { q: "Is this a Google ranking predictor?", a: "No. The score reflects headline best practices from copywriting research. It can raise your click-through rate, but rankings depend on content quality, relevance and authority." },
      { q: "What is the ideal headline length?", a: "Roughly 50 to 60 characters so it displays fully in search results, and 6 to 12 words for readability. The tool flags titles that fall outside these bands." },
      { q: "Is my title sent to a server?", a: "No. Scoring runs entirely in your browser. Your drafts never leave your device." },
      { q: "How do I raise my score?", a: "Follow the listed fixes: add a power or emotional word, front-load your keyword, try a number or a question hook, and trim filler words. Small edits usually move the score quickly." },
      { q: "Is it free?", a: "Yes, completely free with no signup." }
    ],
    tags: [
      "title analyzer",
      "headline analyzer",
      "blog title checker",
      "headline score checker",
      "seo title checker",
      "title score tool",
      "headline generator score",
      "check my headline",
      "blog post title analyzer",
      "article title scorer",
      "headline optimizer free",
      "seo headline checker",
      "title length checker seo",
      "best headline analyzer",
      "co schedule headline analyzer alternative",
      "free headline analyzer no signup",
      "emotional headline analyzer",
      "power words checker",
      "headline word balance",
      "click through rate title tips",
      "how to write clickable headlines",
      "headline best practices 2026",
      "ideal blog title length",
      "seo title length checker",
      "meta title analyzer",
      "youtube title analyzer",
      "email subject line analyzer",
      "subject line score checker",
      "headline sentiment analyzer",
      "title case checker",
      "improve blog titles",
      "headline writing tool",
      "title tester online",
      "score my blog title",
      "headline grader",
      "blog headline generator and scorer",
      "catchy title checker",
      "title capitalization checker seo",
      "keyword in title checker",
      "headline readability checker",
      "analyze title for seo",
      "free seo copywriting tool",
      "content headline optimizer",
      "viral headline formula",
      "headline hook checker",
      "question headline score",
      "number in headline seo",
      "title tag analyzer",
      "serp title preview checker",
      "how long should a blog title be",
      "what makes a good headline",
      "headline emotional words list",
      "title analyzer for bloggers"
    ],
  };

export default seo;
