import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "TOML to JSON Converter - Free Online Dev Tool | IconVault",
    metaDescription: "Convert TOML to JSON and JSON to TOML instantly with validation. Free, runs entirely in your browser, nothing uploaded.",
    about: [
      "**IconVault**'s **TOML to JSON** converter translates configs both ways, **TOML to JSON** and **JSON to TOML**, with syntax validation and clear error messages when the input is malformed. The result can be **copied or downloaded**, and the TOML parser loads on demand so the page stays fast.",
      "All conversion runs **entirely in your browser**, so your config files are **never uploaded**, and the tool is **free** with no signup. The honest note: exotic TOML edge cases like unusual datetime forms may round-trip differently, so spot-check generated configs before shipping them to production."
    ],
    faqs: [
      { q: "Can I convert TOML to JSON?", a: "Yes. Paste TOML, get formatted JSON instantly. The reverse direction, JSON to TOML, is supported in the same tool." },
      { q: "Does it validate my input?", a: "Yes. Malformed TOML or JSON produces a clear error message pointing at the problem instead of silently guessing." },
      { q: "Is my config data sent to a server?", a: "No. Parsing and conversion run entirely in your browser. Your files never leave your device." },
      { q: "Can I download the converted file?", a: "Yes. Both directions support copy to clipboard and download as a file." },
      { q: "Why convert TOML to JSON?", a: "TOML is common for config files like Cargo.toml and pyproject.toml, while JSON is easier to process programmatically. Converting lets you script, diff or validate configs with JSON tooling." },
      { q: "Is it free?", a: "Yes, completely free with no signup." }
    ],
    tags: [
      "toml to json",
      "json to toml",
      "toml json converter",
      "convert toml to json online",
      "convert json to toml online",
      "toml converter",
      "toml parser online",
      "toml validator",
      "validate toml online",
      "toml formatter",
      "pretty print toml",
      "toml to json python",
      "toml config to json",
      "cargo toml to json",
      "pyproject toml to json",
      "json to toml converter free",
      "toml to yaml alternative",
      "toml syntax checker",
      "online toml editor",
      "toml beautifier",
      "minify toml",
      "toml to json javascript",
      "parse toml in browser",
      "free toml tools",
      "toml file converter",
      "convert config files online",
      "toml vs json",
      "when to use toml",
      "toml example",
      "toml datetime format",
      "toml array of tables",
      "toml inline table",
      "json to toml rust",
      "toml to json command line alternative",
      "toml linter online",
      "check toml syntax",
      "toml error checker",
      "fix toml syntax",
      "toml to json api alternative",
      "convert toml online free",
      "no signup toml converter",
      "toml to json no upload",
      "private toml converter",
      "toml to json pretty",
      "nested toml to json",
      "toml table to json object",
      "json object to toml table",
      "toml string escaping",
      "multiline toml string",
      "toml comments json",
      "convert env to toml",
      "toml to json for github actions"
    ],
  };

export default seo;
