import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Tone Generator - Free Online Audio Test Tool | IconVault",
    metaDescription: "Play test tones from 20 Hz to 20 kHz with sine, square, sawtooth and triangle waves. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Tone Generator** plays pure test tones using the **Web Audio API**, with **sine, square, sawtooth and triangle waveforms** on a logarithmic **20 Hz to 20 kHz** slider, adjustable **volume**, and a **frequency sweep mode** where you set the start frequency, end frequency and sweep duration.",
      "Everything is generated **live in your browser**, so there are **no audio files to download** and nothing to upload, and the tool is **free** with no signup. The honest note: exact pitch perception depends on your speakers or headphones, so cheap laptop speakers will not reproduce very low bass tones accurately."
    ],
    faqs: [
      { q: "How do I play a tone at a specific frequency?", a: "Pick a waveform, drag the frequency slider or type a value between 20 Hz and 20 kHz, then press play. The tone is generated live in your browser." },
      { q: "What waveforms are available?", a: "Sine, square, sawtooth and triangle. Sine is the purest tone, square and sawtooth are brighter and harsher, triangle sits in between." },
      { q: "What is frequency sweep mode?", a: "Instead of a fixed pitch, the tone glides from a start frequency to an end frequency over the duration you set. It is useful for finding rattles, resonances or the limits of your hearing." },
      { q: "Can I test my hearing range with this?", a: "Roughly. Sweeping from 20 Hz to 20 kHz tells you where you start and stop hearing tones, but it is a casual check, not a medical hearing test. Keep the volume low at first." },
      { q: "Can I use it to test speakers or headphones?", a: "Yes. Fixed tones reveal buzzing or distortion at specific frequencies, and sweeps expose rattles, dropouts and weak bass response in speakers, headphones and rooms." },
      { q: "Is it free?", a: "Yes, completely free with no signup, and all audio is synthesized locally in your browser." }
    ],
    tags: [
      "tone generator",
      "online tone generator",
      "free tone generator",
      "frequency generator",
      "audio tone generator",
      "test tone generator",
      "sine wave generator",
      "square wave generator",
      "sawtooth wave generator",
      "triangle wave generator",
      "play tone at frequency",
      "generate tone online",
      "frequency sweep generator",
      "audio sweep test",
      "speaker test tones",
      "headphone test tone",
      "hearing test tone",
      "hearing range test online",
      "test your hearing frequency",
      "20 hz to 20 khz test",
      "bass test tone",
      "subwoofer test tone",
      "treble test tone",
      "440 hz tone",
      "play 440 hz online",
      "1000 hz test tone",
      "1 khz reference tone",
      "pure tone generator",
      "online function generator",
      "web audio tone generator",
      "browser tone generator",
      "tone generator no download",
      "free audio test tool",
      "left right speaker test",
      "stereo test tone",
      "room resonance test tone",
      "find rattling speaker tone",
      "tinnitus frequency finder",
      "mosquito tone generator",
      "ultrasonic tone generator",
      "dog whistle frequency online",
      "metronome alternative tone",
      "calibration tone generator",
      "signal generator online free",
      "pitch generator online",
      "note frequency generator",
      "play musical note frequency",
      "a4 440 hz tone",
      "online oscillator",
      "waveform generator browser",
      "test microphone with tone",
      "audio equipment test tone"
    ],
  };

export default seo;
