import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "TOTP Generator - Free Online 2FA Code Tool | IconVault",
    metaDescription: "Generate TOTP secrets, scan-ready QR codes and live 2FA codes in your browser. SHA-1, SHA-256, SHA-512 supported. Free.",
    about: [
      "**IconVault**'s **TOTP Generator** creates **time-based one-time password** secrets for **two-factor authentication**, shows the **current 6-digit code** with a live countdown, and builds a **scan-ready QR code** (otpauth URI) with your issuer and account label so you can enroll it in **Google Authenticator, Authy or any TOTP app**.",
      "You can also switch to **validate mode** to check a code, and choose **SHA-1, SHA-256 or SHA-512**, with everything computed **entirely in your browser** so your secrets are **never uploaded or stored** anywhere. It is **free** with no signup. The honest note: this is a convenience tool for generating and testing codes, and you should store real 2FA secrets in your authenticator app or password manager, not in a browser tab."
    ],
    faqs: [
      { q: "How do I create a TOTP secret?", a: "Click generate to get a random Base32 secret. The tool then shows live 6-digit codes with a countdown and a QR code you can scan with any authenticator app." },
      { q: "Can I scan the QR code with Google Authenticator?", a: "Yes. The QR code uses the standard otpauth URI format, so Google Authenticator, Authy, Microsoft Authenticator and 1Password all accept it." },
      { q: "Which hash algorithms are supported?", a: "SHA-1, SHA-256 and SHA-512. SHA-1 is the default and the most widely compatible with authenticator apps." },
      { q: "Can I check whether a code is valid?", a: "Yes. Switch to validate mode, enter the secret and the code, and the tool tells you whether it matches the current time window." },
      { q: "Is my secret sent to a server?", a: "No. Secret generation, code calculation and QR rendering all happen locally in your browser. Nothing is uploaded or saved." },
      { q: "Is it free?", a: "Yes, completely free with no signup." }
    ],
    tags: [
      "totp generator",
      "online totp generator",
      "free totp generator",
      "2fa code generator",
      "two factor code generator",
      "authenticator code generator",
      "generate totp secret",
      "totp secret generator",
      "create totp secret online",
      "totp qr code generator",
      "otpauth qr generator",
      "qr code for authenticator app",
      "google authenticator qr generator",
      "authy qr code generator",
      "6 digit code generator",
      "time based otp generator",
      "one time password generator",
      "2fa test code generator",
      "validate totp code",
      "check totp code online",
      "totp code checker",
      "sha1 totp",
      "sha256 totp",
      "sha512 totp",
      "totp algorithm sha256",
      "base32 secret generator",
      "2fa secret key generator",
      "authenticator secret generator",
      "setup 2fa without phone",
      "test 2fa setup",
      "totp for developers",
      "totp implementation test",
      "rfc 6238 generator",
      "rfc 4226 hotp totp",
      "totp code valid 30 seconds",
      "why totp code not working",
      "totp time sync issue",
      "2fa backup codes alternative",
      "manual entry key 2fa",
      "enter 2fa key manually",
      "totp uri generator",
      "otpauth uri builder",
      "generate otp online free",
      "totp generator no signup",
      "private totp generator",
      "totp in browser",
      "2fa code generator online free",
      "authenticator app test",
      "totp enrollment qr",
      "add account to authenticator"
    ],
  };

export default seo;
