import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Trim Transparent Edges - Free Online Tool | IconVault",
    metaDescription: "Cut empty transparent margins off PNG and WebP images online. Free, private, in-browser trimmer with before and after view.",
    about: [
      "**IconVault**'s **Trim Transparent Edges** tool cuts the empty margins off PNG and WebP images so the file is tight and centered. The **threshold slider** trims only fully clear pixels at 0, or also faint shadows and soft edges when raised, and **padding** keeps breathing room around the result. Everything runs **free** and **browser-private**, your image never leaves your device.",
      "A **before and after view** shows the exact dimensions, so you always know what changed. **Pro** members get unlimited use with no trial limits.",
    ],
    faqs: [
      { q: "How do I remove transparent edges from a PNG?", a: "Drop your PNG into the trimmer, press Trim edges, and download the cropped result. The tool scans for transparent pixels and cuts the empty margins on all four sides." },
      { q: "What does the threshold slider do?", a: "At 0 only fully clear pixels are trimmed. Raising it also trims faint shadows and anti-aliased edges, useful for cutouts with soft borders." },
      { q: "Can I keep some space around the trimmed image?", a: "Yes. The padding control adds pixels of breathing room back around the trimmed result." },
      { q: "Which formats does this work with?", a: "PNG and WebP, the formats that can carry transparency. JPG has no transparency so there is nothing to trim." },
      { q: "Is my image uploaded to a server?", a: "Never. Trimming happens entirely in your browser on your own device." },
      { q: "Is the trim tool free?", a: "Yes, free users get a generous number of uses. Pro members get unlimited use of every tool." },
    ],
    tags: [ "trim transparent edges", "remove transparent border png", "crop transparent background", "trim png margins", "autocrop transparent pixels", "remove empty space png", "trim webp transparency", "png trimmer online", "crop transparent edges free", "tight crop png", "remove padding from png", "transparent edge cutter", "shrink png to content", "crop to visible pixels", "png whitespace remover", "trim image online free", "autotrim transparent image", "cut transparent margins", "png bounding box crop", "remove transparent area" ,
      "trim image",
      "image trimmer",
      "png trimmer",
      "autocrop image",
      "auto crop transparent",
      "trim png online",
      "transparent png cropper",
      "remove transparent padding",
      "crop to content png",
      "tight bounding box png",
      "trim webp online",
      "trim gif transparency",
      "remove empty transparent space",
      "sprite trimmer",
      "trim sprite transparent edges",
      "game asset trimmer",
      "icon trimmer png",
      "logo trim transparent",
      "trim scanned signature edges",
      "signature autocrop",
      "trim transparent gif",
      "trim apng edges",
      "batch trim png",
      "bulk autocrop images",
      "trim all images at once",
      "transparent border remover",
      "png margin remover",
      "crop invisible pixels",
      "remove invisible border",
      "minimal bounding box image",
      "content aware crop png",
      "autocrop scanned image",
      "trim png transparent online",
      "lossless png trim",
      "trim png free tool",
      "online image autocrop",
      "smart crop transparent",
      "alpha channel trimmer",
      "trim alpha edges",
      "png edge cleaner"],
  };

export default seo;
