import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Typography Scale - Free Online Type System Tool | IconVault",
    metaDescription: "Build a modular typography scale from a base size and ratio, preview every step live, and export ready-to-use CSS. Free and in-browser.",
    about: [
      "**IconVault**'s **Typography Scale** builds a **modular scale** for your project in seconds. Set a base font size, choose a ratio like the **golden ratio**, **perfect fourth** or **major third** (or dial in your own), and adjust how many steps go up and down. Every size renders live in a real preview so you can judge the hierarchy with your own eyes.",
      "When the scale feels right, export it as clean **CSS** with one click and drop it into your project. The tool is **free** and **runs fully in your browser**, no signup and nothing to install."
    ],
    faqs: [
      { q: "What is a modular typography scale?", a: "It is a set of font sizes generated by multiplying a base size by a fixed ratio. Because every size is mathematically related, headings and body text look harmonious instead of arbitrary." },
      { q: "Which ratio should I choose?", a: "The golden ratio (1.618) gives dramatic, editorial contrast. Perfect fourth (1.333) and major third (1.25) are safer for UI work. Pick the ratio whose jumps feel right at your base size." },
      { q: "How many steps do I need?", a: "Five steps up covers h1 through h6 plus display sizes, and three steps down handles small text and captions. Fewer steps keep the system easier to use." },
      { q: "How do I use the exported CSS?", a: "The export gives you CSS variables for each step. Paste them into your stylesheet and reference the variables wherever you set font sizes." },
      { q: "Can I use a custom ratio?", a: "Yes. Besides the preset ratios, you can enter any custom ratio and see the scale update live." },
      { q: "Is this typography tool free?", a: "Yes, it is completely free with no account needed. Build and export as many scales as you like." }
    ],
    tags: [
      "typography scale", "modular scale calculator", "type scale generator", "font scale calculator",
      "typography scale tool", "modular typography scale", "type scale css",
      "font size scale generator", "perfect fourth typography", "golden ratio typography",
      "major third type scale", "minor third font scale", "typography ratio calculator",
      "font size calculator design", "responsive type scale", "fluid type scale",
      "css type scale", "typography scale generator css", "font scale tool free",
      "online type scale calculator", "heading size calculator", "h1 h2 h3 size ratio",
      "font size hierarchy generator", "typographic scale tool", "web typography scale",
      "type system generator", "design system typography", "font size steps calculator",
      "base font size scale", "modular scale design", "typography for websites",
      "type scale ratio list", "choose typography ratio", "typography scale examples",
      "font scale for ui design", "type scale figma", "css clamp type scale",
      "typographic hierarchy tool", "font sizing system", "web font scale",
      "type scale 1.25", "major second typography", "augmented fourth type scale",
      "perfect fifth typography", "type scale export css", "free typography tool online",
      "font size proportion calculator", "harmonious font sizes", "type scale design system",
      "font size ratio tool", "typographic scale calculator online", "type scale preset ratios",
      "web design font scale", "typography scale for headings"
    ],
  };

export default seo;
