import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Video to GIF Converter - Free Online Tool | IconVault",
    metaDescription: "Convert video clips to animated GIFs online. Trim, frame rate and palette controls. Free, private, in-browser.",
    about: [
      "**IconVault**'s **Video to GIF** converter turns an **MP4, WebM or MOV** clip into a shareable **animated GIF**. Trim the exact **start and end seconds**, pick a **frame rate** (10 fps is the sweet spot), set the **width** and choose a 256, 128 or 64 **color palette**, then watch the animated preview before you download.",
      "Frames are captured one by one **in your browser**, so your video is never uploaded anywhere. It is **free** to use, and a built-in warning keeps you from accidentally building a 300-frame monster. Go **Pro** for unlimited runs across all 50+ IconVault tools.",
    ],
    faqs: [
      { q: "How do I convert a video to a GIF?", a: "Upload the video, trim the start and end seconds, choose a frame rate and width, then hit Make GIF. Frames are captured in your browser and encoded into a GIF." },
      { q: "Can I trim the video first?", a: "Yes. Once the video loads, start and end second inputs appear so you convert only the moment you want." },
      { q: "What frame rate should I use?", a: "10 fps gives smooth, small GIFs for most clips. Higher rates look smoother but make much heavier files." },
      { q: "Is my video uploaded?", a: "No. Capture and encoding happen entirely in your browser. Your video never leaves your device." },
      { q: "Why is there a frame limit?", a: "GIFs store every frame as an image, so long clips balloon in size. The tool caps at 300 frames and warns you on long clips to keep files shareable." },
      { q: "Is it free?", a: "Yes, with 5 free conversions. Pro members get unlimited runs plus HD exports and every template across all IconVault tools." },
    ],
    tags: [ "video to gif", "convert video to gif", "mp4 to gif", "video to gif online free", "mov to gif", "webm to gif", "clip to gif", "video gif converter", "make gif from video", "video to animated gif", "trim video to gif", "gif converter online", "video to gif no watermark", "free video gif maker", "video to gif converter online", "short clip gif", "video meme gif maker", "convert clip to gif", "browser video to gif", "video to gif fast" ,
      "gif from video",
      "video to gif converter free",
      "mp4 to gif online",
      "make gif from mp4",
      "convert mp4 to gif",
      "video clip to gif",
      "youtube video to gif",
      "screen recording to gif",
      "video to gif trimmer",
      "cut video make gif",
      "video to gif with text",
      "add caption video gif",
      "video to gif high quality",
      "video to gif small size",
      "video to gif 10 seconds",
      "video to gif loop",
      "boomerang gif maker",
      "video to gif for discord",
      "video to gif for whatsapp",
      "video to gif for twitter",
      "video to gif for reddit",
      "video to gif for slack",
      "video to gif for email",
      "video to gif avatar",
      "video to gif meme",
      "funny video gif maker",
      "reaction gif maker",
      "video to gif no signup",
      "video to gif private",
      "video to gif in browser",
      "video to gif without watermark free",
      "video to gif 15 fps",
      "video to gif 30 fps",
      "video to gif frame rate",
      "resize video to gif",
      "crop video to gif",
      "video to gif 480p",
      "video to gif 720p",
      "video to gif compressor",
      "online video gif studio"],
  };

export default seo;
