import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Wake Lock - Interactive Lab | IconVault",
    metaDescription: "Try the Screen Wake Lock API live: request a lock, watch visibility handling, and see release events in real time. Free, runs in your browser.",
    about: [ "**IconVault**'s **Wake Lock** playground lets you experiment with the real **Screen Wake Lock API**: request a lock, watch the **WakeLockSentinel** status flip to active, and see exactly what happens when you switch tabs. The browser releases the lock automatically on hide, and with auto re-acquire enabled the tool requests a fresh lock when you return, all logged to a live event feed. It is free and runs fully in your browser, with honest support detection for browsers that lack the API.", "This is the same API used by video players, presentation tools, recipe apps and dashboards that must keep the screen awake. The lab explains the **release event**, why locks do not survive page hides, and the HTTPS requirement, so you can ship reliable wake-lock behavior instead of guessing. No uploads, no accounts, no fake controls: every button calls the real `navigator.wakeLock.request()`." ],
    faqs: [ { q: "What does the Wake Lock API do?", a: "It prevents the device screen from dimming or turning off while your page holds a lock. Only the 'screen' lock type is exposed to web pages; the 'system' type is reserved for native apps." }, { q: "Why does the lock release when I switch tabs?", a: "That is specified browser behavior: wake locks are automatically released when the document becomes hidden, to save battery. Your code must listen for visibilitychange and re-request the lock, which this playground demonstrates." }, { q: "Which browsers support Wake Lock?", a: "Chrome and Edge 84+, Safari 16.4+, and Opera. Firefox does not support it yet. The page must be served over HTTPS or localhost, and the tool detects support before you click anything." }, { q: "Does holding a wake lock drain the battery?", a: "It keeps the screen on, which is the biggest battery consumer on mobile, so request the lock only while needed (video playing, navigation active) and release it immediately after." }, { q: "Can a page hold multiple wake locks?", a: "Requesting a new lock of the same type releases the previous one automatically; the release event fires on the old sentinel. This tool models that by releasing quietly before each new request." }, { q: "Is my usage tracked or sent anywhere?", a: "No. The playground runs entirely in your browser. The trial counter is a simple localStorage number so free users get 5 requests per tool." } ],
    tags: [ "wake lock api", "screen wake lock", "navigator.wakelock", "wake lock javascript", "wake lock demo", "wakelock api example", "screen wake lock api", "prevent screen sleep javascript", "keep screen on web app", "wakelock request example", "wake lock sentinel", "wakelock release event", "visibilitychange wake lock", "re acquire wake lock", "wake lock browser support", "wake lock safari", "wake lock chrome", "wake lock firefox", "wake lock https requirement", "screen lock web api", "prevent display sleep html", "keep display awake website", "wakelock notsupportederror", "wake lock typescript", "navigator wakelock request screen", "screen wake lock pwa", "wake lock video player", "wake lock presentation app", "mdn wake lock", "wake lock api tutorial", "how to keep screen on with javascript", "javascript prevent screen timeout", "wake lock api polyfill", "screen wake lock react", "wakelock auto release", "document hidden wake lock", "wake lock best practices", "wake lock battery", "screen wake lock mobile", "wake lock api demo page", "try wake lock api online", "wake lock playground", "wake lock tester", "wakelock sentinel released", "what is wake lock api", "web api keep screen awake", "screen orientation wake lock", "wake lock vs fullscreen", "does wake lock work on iphone", "wake lock screen timeout", "keep phone screen on website" ],
  };

export default seo;
