import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "WeakRef & GC - Interactive Lab | IconVault",
    metaDescription: "Watch JavaScript garbage collection reclaim WeakRefs live, with FinalizationRegistry callbacks and real GC-trigger guidance. Free, in-browser.",
    about: [ "**IconVault**'s **WeakRef & GC** visualizer lets you run real garbage-collection experiments: allocate objects of a chosen size, hold them only through **WeakRef**, and register them with a **FinalizationRegistry**. Drop the strong references, trigger a GC cycle, and watch liveness checks flip from alive to reclaimed while finalization callbacks stream into the log with timestamps. It is free and runs fully in your browser.", "Because JavaScript exposes no API to force collection, the lab teaches the honest workflow: the DevTools Memory tab's **collect-garbage button**, Chrome's **`--js-flags=--expose-gc`** flag, and a **memory-pressure button** that genuinely allocates and discards large temporaries to encourage a cycle. You will see why `deref()` returning `undefined` is the only safe liveness test and why **finalization callbacks** must never be used for critical cleanup." ],
    faqs: [ { q: "What is a WeakRef?", a: "A WeakRef holds a weak reference to an object: it does not prevent garbage collection. Calling deref() returns the object if it is still alive, or undefined if the GC has reclaimed it. It is the building block for caches that must not leak memory." }, { q: "What is FinalizationRegistry?", a: "It lets you register a cleanup callback that runs after the GC reclaims an object. Callbacks run on the GC's schedule, possibly much later, so they are for non-critical bookkeeping only, never for logic your program depends on." }, { q: "Can I force garbage collection from JavaScript?", a: "No. There is no standard API for it. In Chrome you can launch with --js-flags=--expose-gc and call gc(), or click the trash-can icon in the DevTools Memory tab. This playground documents both and adds a memory-pressure helper." }, { q: "Why did my object survive after dropping references?", a: "The GC had not run yet, or the engine kept the object alive for another reason (for example it was still reachable from a closure). Survival until a collection cycle is normal; weak references only mean the object is eligible, not that it is collected instantly." }, { q: "When should I actually use WeakRef?", a: "For caches and memoization tables keyed by objects you do not own, listener registries, and metadata maps (often paired with WeakMap). If you need deterministic cleanup, use explicit dispose() methods instead." }, { q: "Is any data sent to a server?", a: "No. Allocation, weak references, and finalization callbacks all happen in your browser's JS engine. The trial counter is a localStorage number." } ],
    tags: [ "weakref", "weakref javascript", "finalizationregistry", "javascript garbage collection", "js gc visualizer", "weakref deref", "weakref example", "finalizationregistry example", "how to trigger garbage collection javascript", "gc() chrome expose-gc", "javascript memory management", "weak reference vs strong reference", "weakmap vs weakref", "when to use weakref", "weakref cache", "javascript memory leak", "devtools collect garbage", "memory tab trash can chrome", "js-flags expose-gc", "garbage collection visualizer", "v8 garbage collector", "mark and sweep javascript", "generational gc v8", "weakref browser support", "finalizationregistry browser support", "weakref typescript", "deref undefined", "weakref polyfill", "do weakrefs prevent gc", "can you force gc in javascript", "javascript heap", "memory pressure javascript", "large array allocation gc", "finalization callback timing", "weakref cleanup", "registry register unregister", "javascript weak reference tutorial", "mdn weakref", "mdn finalizationregistry", "es2021 weakref", "target es2021 weakref", "weakref node js", "finalizationregistry node", "gc performance javascript", "memory leak detection javascript", "chrome memory profiler", "heap snapshot weakref", "does weakref work in safari", "weakref memory", "javascript weak reference example", "gc roots javascript" ],
  };

export default seo;
