import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Web Share - Interactive Tool | IconVault",
    metaDescription: "Learn the Web Share API: share real text, links and files, check file support, and build a share-target manifest. Free, in your browser.",
    about: [ "**IconVault**'s **Web Share** playground is a hands-on lab for the **Web Share API**. On a supported device it opens the real native share sheet for text, links, and files, with navigator.canShare checks that tell you honestly which files a browser will accept. If your browser does not support sharing, the page says so plainly and gives you a copy fallback instead of pretending. It is free and runs fully in your browser.", "The second half of the page is a **share-target manifest builder** for developers who want their PWA to receive shares from other apps. Enter your app name and action URL to generate a valid manifest.webmanifest with a share_target block, then download it or copy the JSON. Learn both directions of web sharing: sending with navigator.share and receiving with share_target." ],
    faqs: [
      { q: "What is the Web Share API?", a: "It is the navigator.share() browser API that opens the device's native share sheet, the same one apps use, so a website can share text, a URL, or files to any installed target without custom share buttons." },
      { q: "Why does the share button say not supported?", a: "navigator.share is only available on mobile browsers and on desktop browsers that expose share targets, like Edge and Safari, always in a secure context. The page detects this and disables the button honestly rather than faking a share." },
      { q: "How do I share files?", a: "Pick files in the playground, and it runs navigator.canShare({ files }) first. If the browser accepts them, the share button opens the native sheet with the files attached. Unsupported types are reported, not attempted." },
      { q: "What is a share target?", a: "A share target lets your installed PWA appear in other apps' share sheets. You declare it in your web app manifest with a share_target block containing an action URL and parameter names, and your action page reads the shared title, text, and URL." },
      { q: "Does sharing upload my files anywhere?", a: "No. navigator.share hands the data to the operating system's share sheet. This page never sees or stores what you share." },
      { q: "Can I share on desktop Chrome?", a: "Desktop Chrome does not implement navigator.share in most cases, which is why the playground shows the unsupported notice there. Try the page on your phone for the real share sheet." },
    ],
    tags: [ "web share api", "navigator.share", "web share tutorial", "share api demo", "navigator.share example", "web share files", "navigator.canshare", "web share not supported", "share text javascript", "share url web api", "native share sheet web", "web share target", "share_target manifest", "pwa share target example", "manifest share_target", "receive shares pwa", "web share api support", "how to use navigator.share", "javascript share button", "web share fallback", "copy link fallback share", "share files from browser", "web share api android", "web share ios safari", "mobile web share", "learn web share api", "web share playground", "web api playground", "share sheet javascript", "pwa manifest builder", "web app manifest generator", "share_target action url", "share_target params", "share title text url", "progressive web app sharing", "add to homescreen share", "web share vs share buttons", "social share without sdk", "browser share dialog", "navigator.share files example", "canShare check files", "web share secure context", "https share api", "frontend share feature", "javascript native sharing", "web platform share", "pwa capabilities", "installable web app share", "share sheet web app", "navigator.share tutorial" ],
  };

export default seo;
