import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Storage Quota - Interactive Tool | IconVault",
    metaDescription: "Test real browser storage limits: live quota estimate, localStorage and IndexedDB fill experiments, and persistence requests. Free.",
    about: [ "**IconVault**'s **Storage Quota** playground measures what browsers actually give you. The live panel reads the real **navigator.storage.estimate()** for usage and quota, and five hands-on experiments fill **localStorage**, **sessionStorage**, and **IndexedDB** with test data until the browser throws, so you see the true ceilings instead of guessing from documentation. It is free and runs fully in your browser.", "Every experiment writes clearly labeled test keys you can remove with one click, and the usage bar updates as you go. You will also learn when the browser may evict your data and how **navigator.storage.persist()** protects it. Perfect for planning offline-first apps, caches, and large client-side datasets." ],
    faqs: [
      { q: "What does the estimate panel show?", a: "The real result of navigator.storage.estimate() for this origin: bytes used and total quota granted. Quota is shared across IndexedDB, the Cache API, and other origin storage, and it varies by browser and free disk space." },
      { q: "How do the fill experiments work?", a: "They write 100KB chunks (or 1MB blobs for IndexedDB) in a loop until the browser throws QuotaExceededError or aborts the transaction, then report exactly how much was written. All test data is prefixed and removable with the Clear button." },
      { q: "How much can localStorage hold?", a: "Usually around 5 to 10MB per origin, but it varies. Run experiment 1 in your own browser to get the real number instead of trusting a blog post." },
      { q: "How much can IndexedDB hold?", a: "Much more, often a large share of free disk space, but browsers can evict it under storage pressure. Experiment 3 shows your browser's practical limit." },
      { q: "What does persistent storage do?", a: "navigator.storage.persist() asks the browser not to automatically evict your origin's data. The playground requests it for real and shows whether the browser granted or declined it." },
      { q: "Will the test data slow down my browser?", a: "The test keys live only in this origin's storage and are deleted with one click. Filling gigabytes on a nearly full disk is not recommended, but the experiments stop at the first quota error." },
    ],
    tags: [ "browser storage quota", "navigator.storage.estimate", "localstorage limit", "indexeddb limit", "sessionstorage limit", "storage quota test", "how much can localstorage hold", "browser storage limits", "test localstorage quota", "quotaexceedederror", "indexeddb size limit", "web storage limits", "navigator.storage.persist", "persistent storage web", "storage estimate api", "origin storage quota", "check browser storage", "localstorage 5mb limit", "indexeddb quota exceeded", "cache api storage limit", "browser eviction storage", "offline storage limits", "pwa storage quota", "learn web storage", "web storage playground", "storage api tutorial", "measure indexeddb usage", "how to check storage quota javascript", "storage buckets api", "best effort vs persistent storage", "prevent storage eviction", "web storage explained", "frontend storage guide", "client side storage limits", "large data browser storage", "fill localstorage test", "storage stress test browser", "javascript storage benchmark", "web api playground", "learn browser apis", "storage manager api", "estimate storage javascript", "quota management web", "browser data persistence", "opaque origin storage", "storage pressure browser", "clear site data test", "web storage vs indexeddb", "choose browser storage", "offline first storage planning" ],
  };

export default seo;
