import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Web OTP - Interactive Tool | IconVault",
    metaDescription: "Learn the WebOTP API: SMS one-time-code format builder, autocomplete guide, and credential retrieval snippet. Free, runs in your browser.",
    about: [ "**IconVault**'s **Web OTP** playground teaches the **WebOTP API**, the browser feature that reads SMS verification codes automatically so users never type them. Build a correctly formatted sample SMS with the required @domain #code binding line, check whether your browser and connection support WebOTP, and try the autocomplete=\"one-time-code\" input pattern that triggers autofill. It is free and runs fully in your browser.", "The page covers the three things most implementations get wrong: the **SMS format** (the binding line must be the last line and the domain must match your origin), the **HTTPS and browser requirements**, and the **navigator.credentials.get({ otp })** call with an AbortController timeout. Copy the production-ready snippet and the sample message, then wire them into your login flow with confidence." ],
    faqs: [
      { q: "What is the WebOTP API?", a: "It is a browser API that lets a website read a one-time code from an incoming SMS without the user typing or pasting it. The site calls navigator.credentials.get({ otp: { transport: ['sms'] } }) and the browser fills the code from a matching message." },
      { q: "What SMS format does WebOTP require?", a: "The message must end with a line exactly like @example.com #123456, where the domain matches the website's origin. The playground's format lab builds valid samples so you can see the rule in action." },
      { q: "Which browsers support WebOTP?", a: "Chrome and Edge on Android with Google Play Services. The playground detects OTPCredential support and whether you are on HTTPS, and says so honestly." },
      { q: "Do I still need autocomplete=\"one-time-code\"?", a: "Yes, for the broadest coverage. iOS Safari and many Android keyboards offer SMS code autofill for inputs with autocomplete=\"one-time-code\", even where the WebOTP API is unavailable. Use both." },
      { q: "Can I test receiving a real SMS here?", a: "No honest demo can. Receiving a code requires sending a real SMS from your backend to a real phone number. This playground builds the exact format your backend must send and the exact code your frontend must run." },
      { q: "Is anything uploaded or sent?", a: "No. The format lab, snippet, and autofill demo all run locally in your browser." },
    ],
    tags: [ "webotp api", "web otp tutorial", "sms otp autofill", "autocomplete one-time-code", "webotp sms format", "navigator.credentials.get otp", "otpcredential", "web otp example", "sms verification code format", "webotp api support", "how to implement webotp", "otp autofill web", "one time code html input", "sms code autofill android", "ios sms code autofill", "webotp javascript example", "otp transport sms", "webotp abortcontroller", "sms retriever vs webotp", "auto read otp web", "web otp demo", "webotp playground", "learn webotp", "otp input best practices", "login otp ux", "sms binding line format", "at domain hash code sms", "webotp origin matching", "https requirement webotp", "otp autocomplete attribute", "inputmode numeric otp", "verification code input html", "auto fill otp code", "webotp error handling", "webotp not working", "debug webotp sms", "otp ux design", "passwordless login otp", "2fa web implementation", "sms otp security", "webotp vs sms retriever api", "credential management api otp", "web platform otp", "frontend authentication otp", "web api playground", "learn browser apis", "mobile web otp", "chrome android otp api", "webotp code sample", "sms otp message template" ],
  };

export default seo;
