import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Web Font Analyzer - Free Online Font Face Checker | IconVault",
    metaDescription: "Paste @font-face CSS or a Google Fonts URL and get a breakdown of families, weights, styles, unicode ranges, plus a preload snippet. Free, in your browser.",
    about: [
      "**IconVault**'s **Web Font Analyzer** takes your **@font-face CSS** or a **Google Fonts CSS URL** and breaks it down into a clear audit: every **font family**, its **weights** and **styles**, **font-display** settings, **unicode ranges** with human-readable subset names like latin, latin-ext, cyrillic and devanagari, and every font **file URL** it loads. It also generates a ready-to-paste **preload snippet** for your critical fonts.",
      "Alongside the breakdown you get honest **performance tips** for cutting font weight, such as subsetting and avoiding unused variants. The analysis runs **fully in your browser**, so your CSS is never uploaded. It is **free** with no signup. Note that it analyzes the CSS you paste, it cannot auto-discover the fonts a live page loads, so paste the CSS from the page you want to audit."
    ],
    faqs: [
      { q: "What does the Web Font Analyzer check?", a: "Paste @font-face CSS or a Google Fonts CSS URL and it reports every font family, its weights, styles, font-display value, unicode ranges with readable subset names, and all font file URLs, plus a preload snippet and performance tips." },
      { q: "Can I analyze a live website's fonts?", a: "Not directly. Paste the page's @font-face CSS (from its stylesheet or the Google Fonts URL it uses) into the tool and it will analyze that. It does not fetch and scan arbitrary pages by itself." },
      { q: "Is my CSS uploaded anywhere?", a: "No. Parsing and analysis happen entirely in your browser. Your stylesheet never leaves your device." },
      { q: "What is a preload snippet and why do I need one?", a: "Preloading your most important font files with <link rel=preload> tells the browser to fetch them immediately instead of waiting, which reduces text flashes and improves loading scores. The tool generates the snippet for you." },
      { q: "How do I make my web fonts load faster?", a: "Serve only the weights and styles you use, subset unicode ranges to the languages you need, use font-display: swap, preload key fonts, and prefer WOFF2. The analyzer's tips walk you through this." },
      { q: "What does font-display: swap mean?", a: "It tells the browser to show fallback text immediately and swap in the web font when it arrives, so visitors are not staring at invisible text while fonts load." }
    ],
    tags: [
      "web font analyzer",
      "font face checker",
      "@font-face analyzer",
      "google fonts analyzer",
      "check website fonts",
      "font loading performance",
      "font preload generator",
      "unicode range checker",
      "font subset checker",
      "webfont performance audit",
      "analyze google fonts css",
      "font-display checker",
      "which fonts does a website use",
      "detect web fonts",
      "font weight checker",
      "list font families css",
      "parse @font-face css",
      "font css parser online",
      "preload fonts snippet generator",
      "link rel preload font generator",
      "reduce font loading time",
      "font performance optimization",
      "web font loading best practices",
      "font-display swap explained",
      "what is font subsetting",
      "unicode-range explained",
      "latin latin-ext cyrillic fonts",
      "devanagari web fonts",
      "woff2 vs woff",
      "how many font weights to load",
      "unused font weights remove",
      "font file urls extractor",
      "google fonts css2 url analyzer",
      "variable fonts explained",
      "webfont optimization tool",
      "font audit tool online",
      "check font display value",
      "text invisible flash fix",
      "fout vs foit",
      "improve lighthouse font score",
      "core web vitals fonts",
      "font preconnect google fonts",
      "self host google fonts",
      "self-hosting fonts performance",
      "font css validator",
      "extract font urls from css",
      "font family list generator",
      "typography audit tool",
      "web font loading strategy",
      "free font tools online",
      "developer font checker",
      "font weight 400 700 checker",
      "italic font variant checker",
      "font style normal italic audit",
      "how to preload web fonts",
      "preload woff2 example"
    ],
  };

export default seo;
