import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Web Locks - Interactive Tool | IconVault",
    metaDescription: "Learn the Web Locks API with live exclusive and shared lock demos, a cross-tab race test, and a real lock table. Free, runs in your browser.",
    about: [ "**IconVault**'s **Web Locks** playground is an interactive lab for the **Web Locks API**, the browser's built-in way to coordinate work across tabs, workers, and iframes. Request real exclusive and shared locks by name, watch them queue and release in the live lock table, and run a two-request race to see ordering in action. It is free and runs fully in your browser with nothing uploaded.", "Open the page in a second tab and request the same lock name to feel genuine cross-tab coordination. The playground covers **exclusive vs shared modes**, hold times, the pending queue, and navigator.locks.query(), with a timestamped event log so every acquire and release is visible. Whether you are guarding IndexedDB writes, serializing uploads, or just learning the API, this is the fastest way to build intuition for web locks." ],
    faqs: [
      { q: "What is the Web Locks API?", a: "It is a browser API (navigator.locks) that lets tabs, workers, and iframes coordinate access to a named resource, like a mutex for the web. An exclusive lock blocks everyone else; a shared lock lets other shared holders in but blocks exclusive ones." },
      { q: "Does this playground use real locks?", a: "Yes. Every demo calls the real navigator.locks.request() in your browser. The held and pending tables come from navigator.locks.query(), so what you see is what the browser actually does." },
      { q: "How do I see cross-tab locking?", a: "Open this page in two tabs, type the same lock name in both, and request an exclusive lock with a long hold time. The second tab's request will sit in the pending queue until the first tab releases." },
      { q: "Which browsers support Web Locks?", a: "Chromium browsers, Firefox 96 and newer, and Safari 15.2 and newer. The page detects support and tells you honestly if your browser cannot run the demos." },
      { q: "When should I use exclusive vs shared mode?", a: "Use exclusive when writing or mutating shared state, like an IndexedDB record or a file. Use shared when many readers can safely run at the same time and only writers need to be blocked." },
      { q: "Is my data sent anywhere?", a: "No. Everything runs in your browser tab. Locks exist only for the lifetime of the page and are never transmitted to any server." },
    ],
    tags: [ "web locks api", "navigator.locks", "web locks tutorial", "web locks demo", "javascript locks", "browser mutex", "cross tab locking", "shared lock vs exclusive lock", "navigator.locks.request example", "web locks query", "how to use web locks api", "javascript cross tab coordination", "indexeddb locking", "web locks held pending", "lock manager api", "web locks playground", "learn web locks", "web locks mdn", "javascript mutex browser", "prevent race condition javascript", "tab synchronization javascript", "web locks api support", "navigator.locks.query example", "exclusive lock javascript", "shared lock javascript", "web locks release", "locks api web dev", "coordinate tabs javascript", "web worker lock", "service worker locks", "web locks timeout", "abort signal locks", "javascript resource locking", "browser concurrency control", "web locks explained", "web locks use cases", "serialize indexeddb writes", "web locks demo page", "test web locks api", "web locks visualizer", "frontend locking mechanism", "javascript critical section", "cross tab mutex", "web locks api example code", "navigator.locks supported browsers", "web locks vs broadcast channel", "web locks best practices", "async lock javascript browser", "web platform locks api", "learn browser apis", "web api playground" ],
  };

export default seo;
