import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Web Crypto Lab - Free Online Cryptography Playground | IconVault",
    metaDescription: "Experiment with SHA-256 hashing, HMAC, AES-GCM encryption, RSA signing and secure random values in an interactive lab. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **Web Crypto Lab** is an interactive **cryptography explorer** that lets you try the Web Crypto API's core primitives hands-on: **SHA-256 hashing**, **HMAC** message authentication, **AES-GCM encryption** and decryption, **RSA signing and verification**, and **cryptographically secure random values**. Every section pairs a live working demo with a plain-English note explaining what the primitive is actually for, so you learn by doing instead of reading specs.",
      "Everything runs through your browser's **Web Crypto API**, so keys, plaintext and signatures **never leave your device** and nothing is uploaded. It is **free** with no signup. Honest note: this is a learning and experimentation lab, not a hardened security product. For production systems, use audited libraries and reviewed key-management practices rather than copy-pasting demo code."
    ],
    faqs: [
      { q: "What cryptography can I try in Web Crypto Lab?", a: "SHA-256 hashing, HMAC keyed hashing, AES-GCM encryption and decryption, RSA-PSS signing and verification, and secure random value generation. Each primitive has a live demo with sample inputs you can edit." },
      { q: "Is anything sent to a server?", a: "No. All operations run in your browser via the Web Crypto API. Your keys, plaintext and signatures never leave your device." },
      { q: "Can I use this to learn how WebCrypto works?", a: "Yes, that is exactly what it is for. Each section explains the primitive in plain English and shows the relevant WebCrypto calls, so developers can see how hashing, HMAC, AES-GCM and RSA signing fit together." },
      { q: "Is the code here safe to use in production?", a: "The primitives are standard WebCrypto, but the lab is a teaching tool, not an audited library. For production, use well-reviewed crypto libraries, proper key storage and a reviewed design rather than demo snippets." },
      { q: "Do I need to install anything?", a: "No. Any modern browser has the Web Crypto API built in, so the lab works instantly with no installation, signup or extensions." },
      { q: "Which browsers support the Web Crypto API?", a: "All current versions of Chrome, Edge, Firefox and Safari support it. Secure contexts (HTTPS or localhost) are required for the full API, including subtle.crypto operations." }
    ],
    tags: [
      "web crypto lab",
      "webcrypto api playground",
      "sha256 online",
      "sha 256 hash generator",
      "hmac online",
      "hmac sha256 generator",
      "aes gcm encrypt online",
      "rsa sign online",
      "rsa signature generator",
      "secure random generator",
      "cryptography playground",
      "webcrypto demo",
      "crypto.subtle example",
      "javascript crypto api",
      "sha256 hash online free",
      "sha512 hash generator",
      "hmac sha256 online free",
      "aes-gcm javascript example",
      "rsa-pss signing webcrypto",
      "generate random bytes browser",
      "crypto getrandomvalues online",
      "learn webcrypto api",
      "web cryptography tutorial",
      "interactive crypto lab",
      "hash string online sha256",
      "verify hmac online",
      "encrypt decrypt aes online",
      "rsa public private key demo",
      "digital signature demo online",
      "message authentication code tool",
      "what is hmac",
      "what is aes gcm",
      "sha256 vs sha512",
      "how to use crypto.subtle",
      "webcrypto digest example",
      "webcrypto generatekey example",
      "subtle crypto import key",
      "subtle crypto export key",
      "browser cryptography tools",
      "client side crypto demo",
      "free cryptography tools online",
      "crypto primitives explained",
      "hashing vs encryption explained",
      "learn cryptography online free",
      "cybersecurity learning tools",
      "developer crypto sandbox",
      "test sha256 implementation",
      "compare hash algorithms online",
      "digital signature verification tool",
      "secure random number generator",
      "cryptographic random values online",
      "nonce generator browser",
      "salt generator online",
      "iv generator aes",
      "uuid secure random browser",
      "password hashing demo",
      "checksum generator sha256"
    ],
  };

export default seo;
