import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "WebP to JPG Converter - Free Online Tool | IconVault",
    metaDescription: "Convert WebP images to JPG free in your browser. Bulk support, quality slider, custom background fill, no uploads.",
    about: [
      "**IconVault**'s **WebP to JPG Converter** changes modern **WebP images** into universally supported **JPG files** right in your browser. WebP looks great on the web, but many editors, printers and older apps still want JPG. The tool is completely **free**, handles **bulk uploads**, and your images **never leave your device**.",
      "A **quality slider** (90% default) balances sharpness against file size, and the **background color** picker fills transparent areas, since JPG cannot store alpha. Convert many files and get them back as a **ZIP**. **IconVault Pro** removes trial limits for unlimited batch work.",
    ],
    faqs: [
      { q: "Is WebP to JPG conversion free?", a: "Yes, with a daily free quota. IconVault Pro unlocks unlimited conversions." },
      { q: "Do my images get uploaded?", a: "No. Everything converts locally in your browser, so your images stay private." },
      { q: "Why convert WebP to JPG?", a: "JPG opens everywhere: old editors, email clients, printers and social apps that still reject WebP." },
      { q: "What happens to transparency?", a: "WebP can be transparent but JPG cannot, so transparent areas become the fill color you choose, white by default." },
      { q: "What quality should I use?", a: "90% is a good default for sharp results. Drop toward 75% for smaller web files." },
      { q: "Can I convert multiple WebP files at once?", a: "Yes. Add as many as you like and download them together as a ZIP file." },
    ],
    tags: ["webp to jpg", "convert webp to jpg", "webp converter", "webp to jpeg", "webp to jpg online", "bulk webp to jpg", "webp to jpg free", "convert webp files", "webp to jpg quality", "webp transparent to jpg", "webp to jpg batch", "webp to jpg no signup", "webp image converter", "webp to jpg private", "save webp as jpg", "webp to jpg chrome", "webp to jpg download", "webp to jpeg converter", "free webp converter", "webp to jpg zip",
      "jpg from webp",
      "webp to jpeg online",
      "convert webp to jpeg",
      "webp to jpg high quality",
      "webp to jpg small size",
      "webp to jpg white background",
      "change webp to jpg",
      "turn webp into jpg",
      "convert transparent webp to jpg",
      "multiple webp to jpg",
      "all webp to jpg at once",
      "webp to jpg for upload",
      "webp to jpg for email",
      "webp to jpg for printing",
      "webp to jpg ios",
      "webp to jpg android",
      "webp to jpg windows 11",
      "webp to jpg mac",
      "webp image to jpg",
      "downloaded webp to jpg",
      "google images webp to jpg",
      "whatsapp webp to jpg",
      "telegram webp to jpg",
      "webp sticker to jpg",
      "webp to jpg 1mb",
      "webp to jpg under 500kb",
      "webp to jpg fast converter",
      "webp to jpg drag drop",
      "webp to jpg browser tool",
      "webp to jpg no watermark",
      "webp to jpg keep quality",
      "webp to jpg offline in browser",
      "webp to jpg instantly",
      "best webp to jpg converter",
      "webp to jpg tool free",
      "webp to jpg converter online free",
      "webp to jpeg batch",
      "webp animated to jpg",
      "webp to jpg first frame",
      "webp to jpg for old software"],
  };

export default seo;
