import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "WebSocket Frame Inspector - Free RFC 6455 Frame Tool | IconVault",
    metaDescription: "Build raw WebSocket frames byte by byte and decode hex frames back into FIN, opcode, mask and payload. Free, fully in your browser.",
    about: [
      "**IconVault**'s **WebSocket Frames** inspector lets you **build raw WebSocket frames byte by byte** according to **RFC 6455** and decode hex dumps back into their fields. Choose the **opcode** (text, binary, close, ping, pong, continuation), set **FIN** and **mask** flags, supply a payload, and get the exact bytes a client would put on the wire, or paste hex and see it broken down into header fields and decoded payload.",
      "It is built for developers debugging **custom WebSocket implementations**, proxies and protocol stacks, where seeing the actual framing matters more than a high-level client. Everything is computed **in your browser** with nothing uploaded, and it is **free** with no signup. Honest note: this inspects protocol framing only; it does not open real connections, for that use a WebSocket client or sandbox tool."
    ],
    faqs: [
      { q: "What is a WebSocket frame?", a: "The binary unit of a WebSocket message defined by RFC 6455. Each frame has a header with a FIN bit, an opcode (text, binary, close, ping, pong), masking info and payload length, followed by the payload bytes." },
      { q: "Can I decode a hex dump of a WebSocket frame?", a: "Yes. Paste the hex bytes and the tool breaks the frame into its fields: FIN flag, opcode, masked bit, payload length and the decoded payload text." },
      { q: "Why are client-to-server frames masked?", a: "RFC 6455 requires clients to mask every frame with a random 32-bit key, a legacy defense against cache-poisoning attacks on misbehaving proxies. Server frames are never masked. The tool lets you build masked or unmasked frames." },
      { q: "What do the opcodes mean?", a: "0x0 continues a fragmented message, 0x1 is text, 0x2 is binary, 0x8 closes the connection, 0x9 is a ping and 0xA is a pong. The tool supports building and decoding all of them." },
      { q: "Does this connect to a WebSocket server?", a: "No. It is a framing inspector and builder for the bytes themselves, which is exactly what you need when writing or debugging a WebSocket implementation. To test live servers, use a WebSocket client tool." },
      { q: "Is my data uploaded?", a: "No. Frame building and decoding run entirely in your browser. Pasted hex and payloads never leave your device." }
    ],
    tags: [
      "websocket frame inspector",
      "websocket frame decoder",
      "websocket frame builder",
      "rfc 6455 frame",
      "websocket protocol frames",
      "websocket hex decoder",
      "decode websocket frame",
      "build websocket frame",
      "websocket opcode",
      "websocket fin bit",
      "websocket masking",
      "websocket frame format",
      "websocket frame header",
      "websocket binary protocol",
      "websocket ping pong frame",
      "websocket close frame",
      "websocket text frame bytes",
      "websocket frame parser",
      "parse websocket hex",
      "websocket wire protocol",
      "websocket framing explained",
      "how websocket frames work",
      "rfc6455 explained",
      "websocket handshake vs frames",
      "websocket mask key",
      "why websocket frames are masked",
      "websocket payload length",
      "websocket extended payload",
      "websocket fragmentation",
      "continuation frame websocket",
      "websocket control frames",
      "debug websocket implementation",
      "websocket server from scratch",
      "write websocket server",
      "websocket proxy debugging",
      "websocket protocol testing",
      "raw websocket bytes",
      "websocket packet inspector",
      "websocket analyzer tool",
      "network protocol tools",
      "binary protocol debugger",
      "hex to websocket frame",
      "websocket frame to hex",
      "generate websocket frame bytes",
      "websocket test vectors",
      "websocket compliance testing",
      "autobahn websocket test",
      "websocket library debugging",
      "nodejs websocket frames",
      "python websocket frame",
      "rust websocket implementation",
      "go websocket frames",
      "free websocket tools online",
      "developer protocol tools"
    ],
  };

export default seo;
