import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Word Counter - Free Online | IconVault",
    metaDescription:
      "Count words free: live word, character, sentence and paragraph counts plus reading time. No signup, runs in your browser.",
    about: [
      "**IconVault**'s **Word Counter** counts as you type: **words**, **characters**, **sentences**, **paragraphs**, reading time and speaking time - the live stats writers, students and SEOs check before hitting publish.",
      "Paste an essay, article or tweet draft and watch every metric update instantly. Your **text** never leaves your **browser**. Free forever, no account needed.",
    ],
    faqs: [
      {
        q: "How are words counted?",
        a: "Text is split on whitespace and punctuation boundaries, matching how most editors count. Hyphenated compounds count as one word.",
      },
      {
        q: "How is reading time calculated?",
        a: "At 200 words per minute for reading and 130 for speaking - standard averages you can sanity-check against your own pace.",
      },
      {
        q: "Is there a character limit?",
        a: "No - paste entire manuscripts. Everything is computed locally, so even very long texts stay instant.",
      },
      {
        q: "Is my text private?",
        a: "Completely. Counting runs in your browser; nothing is uploaded or stored.",
      },
    ],
    tags: [
      "word counter", "word count online", "free word counter", "count words",
      "word counter no signup", "character and word counter", "essay word counter",
      "reading time calculator", "sentence counter", "paragraph counter",
      "word count tool", "online wordcount",
    
      "count words online free",
      "words counter tool",
      "count words in text",
      "online word counter tool",
      "text word counter",
      "essay word count",
      "blog word counter",
      "article word counter",
      "word counter for writers",
      "words count checker",
      "count words characters",
      "free online word counter",
      "word count checker",
      "count my words",
      "words and characters counter",
      "essay length checker",
      "paragraph word counter",
      "word count for seo",
      "seo word count checker",
      "minimum word count checker",
      "article length checker",
      "blog post word count",
      "words counter online",
      "word tally",
      "count words in paragraph",
      "sentence and word counter",
      "word counter app",
      "writing word counter",
      "novel word counter",
      "book word count tool",
      "assignment word counter",
      "dissertation word counter",
      "word count for students",
      "free word count tool",
      "word counter no limit",
      "count words without signup",
      "instant word counter",
      "real time word counter",
      "live word counter",
      "word count statistics",
      "word frequency counter",
      "unique word counter",
      "most used words finder",
      "reading level calculator",
      "speaking time calculator",
      "words per minute calculator",
      "text statistics tool",
      "word count generator"],
  };

export default seo;
