import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Word Search - Free Online Word Search Puzzle Maker | IconVault",
    metaDescription: "Generate themed word search puzzles in animals, food, space, tech, sports and music, then find words by dragging. Free, unlimited, in your browser.",
    about: [
      "**IconVault**'s **Word Search** generates unlimited **word search puzzles** from built-in **themes** like Animals, Food, Space, Tech, Sports and Music. Every puzzle is freshly randomized: words hide in all eight directions and the remaining squares fill with random letters, so no two grids are the same. Find words by **clicking and dragging** across the grid, track your progress in the word list, and print puzzles for offline play.",
      "It runs **fully in your browser** with no signup, no downloads and no ads interrupting your game, and it is **free** with unlimited puzzles. Great for a quick brain break, vocabulary practice for kids, or printing a stack of puzzles for a classroom or road trip."
    ],
    faqs: [
      { q: "How do I play the word search?", a: "Pick a theme, then click and drag across letters to select words. Words can run horizontally, vertically or diagonally, forwards or backwards. Found words are marked off the list until the puzzle is complete." },
      { q: "What themes are available?", a: "Six built-in themes: Animals, Food, Space, Tech, Sports and Music, each with its own word list." },
      { q: "Can I print the puzzles?", a: "Yes. There is a print option so you can take puzzles offline for classrooms, waiting rooms or travel." },
      { q: "Are the puzzles different every time?", a: "Yes. Word placement and filler letters are randomized on every generation, so each puzzle is unique." },
      { q: "Is it free?", a: "Yes. Unlimited puzzle generation and play, free, with no account required." },
      { q: "Is it good for kids?", a: "Yes. It is a gentle vocabulary and pattern-recognition game with no ads, no chat and no in-app purchases, making it classroom and family friendly." }
    ],
    tags: [
      "word search",
      "word search game",
      "word search online",
      "word search puzzles",
      "free word search",
      "word search maker",
      "word search generator",
      "word search puzzle generator",
      "printable word search",
      "word search printable",
      "word search for kids",
      "word search for adults",
      "word search animals",
      "word search food",
      "word search space",
      "word search sports",
      "word search music",
      "themed word search",
      "daily word search",
      "unlimited word search",
      "word find game",
      "word find puzzles",
      "word seek game",
      "find hidden words game",
      "word puzzle games",
      "brain games word search",
      "vocabulary games online",
      "spelling practice games",
      "word games for kids",
      "word games for adults",
      "educational word games",
      "classroom word search",
      "teacher word search maker",
      "homeschool word puzzles",
      "esl word search",
      "english vocabulary puzzles",
      "word search no ads",
      "word search no download",
      "play word search free",
      "online puzzle games",
      "relaxing puzzle games",
      "brain training games",
      "cognitive games seniors",
      "word search for seniors",
      "large print word search",
      "road trip games",
      "waiting room games",
      "rainy day activities kids",
      "screen free activities",
      "puzzle generator for teachers",
      "custom word search",
      "make your own word search",
      "word search with timer",
      "8 direction word search",
      "diagonal word search"
    ],
  };

export default seo;
