import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "Word Filter - Free Online Profanity Filter | IconVault",
    metaDescription: "Scan text against a built-in word list plus your own custom words, highlight matches or clean them to ***. Free, runs in your browser.",
    about: [
      "**IconVault**'s **Word Filter** scans your text against a built-in **sensitive word list** plus any **custom words** you add, then either **highlights every match** in place or **cleans** them to ***. It is a quick way to check user comments, chat messages, form submissions or any copy before it goes live, and to produce a sanitized version you can copy out.",
      "Scanning runs **fully in your browser**, so your text is never uploaded and nothing is stored. It is **free** with no signup. Honest note: the built-in list is a moderate starter set in English, not a comprehensive moderation dictionary, so add your own words for real moderation use, and remember that simple word matching cannot catch creative misspellings or context."
    ],
    faqs: [
      { q: "What is a word filter?", a: "A tool that scans text for a list of blocked or sensitive words. This one highlights matches so you can review them, or replaces them with *** to produce a clean version." },
      { q: "Can I add my own blocked words?", a: "Yes. Add any custom words alongside the built-in list, which is handy for brand-specific terms, spoilers, or internal jargon you want kept out of public text." },
      { q: "What is the difference between highlight and clean mode?", a: "Highlight mode shows you where every match is so you can edit manually. Clean mode replaces matches with *** and gives you the sanitized text ready to copy." },
      { q: "Is my text uploaded to a server?", a: "No. The scan runs entirely in your browser. Your text never leaves your device." },
      { q: "Is this enough for real content moderation?", a: "It is a good first layer for drafts and small communities, but production moderation needs more: context awareness, misspelling tolerance, multilingual lists and human review. Treat this as a helper, not a complete solution." },
      { q: "Does it catch misspelled bad words?", a: "No. It matches whole words from your list, so deliberate misspellings and leetspeak will slip through. Add common variants to your custom list to cover the obvious ones." }
    ],
    tags: [
      "word filter",
      "profanity filter",
      "profanity filter online",
      "bad word filter",
      "swear word filter",
      "profanity checker",
      "check text for profanity",
      "censor bad words",
      "censor text online",
      "clean text profanity",
      "replace swear words",
      "profanity remover",
      "content filter tool",
      "text moderation tool",
      "comment moderation tool",
      "chat filter",
      "chat profanity filter",
      "custom word blacklist",
      "blocked words list",
      "banned words checker",
      "sensitive word filter",
      "filter inappropriate words",
      "keep text clean",
      "family friendly text checker",
      "safe text checker",
      "highlight bad words",
      "find swear words in text",
      "scan document profanity",
      "profanity filter for comments",
      "profanity filter for chat",
      "profanity filter for forum",
      "profanity filter for website",
      "profanity filter for games",
      "moderate user comments",
      "moderate chat messages",
      "user generated content filter",
      "content moderation basics",
      "simple content moderator",
      "free moderation tools",
      "profanity filter no signup",
      "online text cleaner",
      "sanitize text online",
      "clean copy before publishing",
      "check article for bad words",
      "brand safety text check",
      "kid safe text checker",
      "classroom safe text",
      "teacher text checker",
      "parental control text",
      "profanity filter javascript",
      "build profanity filter",
      "word blacklist regex",
      "profanity list english",
      "custom blacklist words",
      "asterisk censor text",
      "replace words with ***",
      "bulk text censor"
    ],
  };

export default seo;
