import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "World Clock - Free Online World Time Converter | IconVault",
    metaDescription: "See live ticking clocks for world cities, add or remove time zones and switch 12/24h format. Free, instant, no signup.",
    about: [
      "**IconVault**'s **World Clock** shows **live ticking clocks** for major world cities side by side, from New York and London to Dubai, Mumbai, Singapore, Tokyo and Sydney. Add or remove any **time zone**, toggle between **12-hour and 24-hour** format, and see at a glance who is awake, who is asleep, and whether your meeting time is sane for everyone invited.",
      "It uses your browser's built-in **time zone data**, so times stay correct through daylight saving changes with no manual updates. It is **free**, runs entirely in your browser with no signup, and is perfect for remote teams, freelancers with global clients, travelers, and anyone scheduling across time zones."
    ],
    faqs: [
      { q: "How do I add a city to the world clock?", a: "Use the add control to pick any time zone from the list. You can add as many as you like and remove any clock you no longer need." },
      { q: "Does it handle daylight saving time?", a: "Yes. Times come from your browser's built-in IANA time zone database, which applies daylight saving rules automatically." },
      { q: "Can I switch between 12 and 24 hour format?", a: "Yes. One toggle switches every clock between 12-hour (AM/PM) and 24-hour display." },
      { q: "Is the time accurate?", a: "Clocks tick from your device's system clock, so they are as accurate as your device. For scheduling purposes, that is the same time your calendar and alarms use." },
      { q: "Do I need an account?", a: "No. The world clock is free and works instantly with no signup." },
      { q: "Which cities are included?", a: "It starts with a spread of major cities across the Americas, Europe, Africa, Asia and Oceania, and you can add any other IANA time zone you need." }
    ],
    tags: [
      "world clock",
      "world clock online",
      "world time clock",
      "time zones clock",
      "live world clock",
      "current time world",
      "what time is it in",
      "time in tokyo",
      "time in london",
      "time in new york",
      "time in dubai",
      "time in mumbai",
      "time in singapore",
      "time in sydney",
      "world time zones",
      "time zone converter",
      "convert time zones",
      "meeting time zone planner",
      "schedule across time zones",
      "remote team time zones",
      "global team clock",
      "freelancer time zone tool",
      "client time zone checker",
      "travel time zones",
      "jet lag planner",
      "12 hour vs 24 hour clock",
      "military time converter",
      "world clock widget",
      "world clock free",
      "online clock",
      "digital world clock",
      "multiple time zone clock",
      "add time zone clock",
      "compare times cities",
      "is it daytime in",
      "business hours overlap",
      "find meeting time global team",
      "best time to call",
      "international call planner",
      "daylight saving time",
      "dst time zones",
      "iana time zones list",
      "utc time now",
      "gmt time now",
      "world clock no ads",
      "simple world clock",
      "minimal world clock",
      "world clock for mac",
      "world clock for windows",
      "world clock phone",
      "world clock desktop",
      "time zone map",
      "every time zone now",
      "world time buddy alternative",
      "free time zone tools"
    ],
  };

export default seo;
