import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "XML Formatter - Free Online XML Beautifier & Validator | IconVault",
    metaDescription: "Pretty-print, minify and validate XML in your browser, with an XPath query box. Free, instant, nothing uploaded.",
    about: [
      "**IconVault**'s **XML Formatter** takes messy or minified **XML** and **pretty-prints** it with clean indentation, or **minifies** it down for transport. It also **validates** your document and reports parse errors with line and column numbers, so you can fix malformed feeds, configs and API payloads fast. A built-in **XPath query box** powered by document.evaluate lets you extract exactly the nodes you need.",
      "Parsing and formatting happen **fully in your browser** using the native DOMParser, so your data is never uploaded to a server. It is **free** with no signup and no limits. Honest note: it validates well-formedness, not schema conformance, so it will not check your document against an XSD or DTD."
    ],
    faqs: [
      { q: "How do I format XML online?", a: "Paste your XML and the tool pretty-prints it with readable indentation instantly. One click also minifies it back down when you need a compact payload." },
      { q: "Does it validate XML?", a: "Yes. It checks that your document is well-formed and reports errors with line and column numbers. It does not validate against XSD schemas or DTDs." },
      { q: "What is the XPath box for?", a: "Type an XPath expression to query your document and see matching nodes, which is handy for pulling specific values out of large XML feeds or SOAP responses without manual digging." },
      { q: "Is my XML uploaded anywhere?", a: "No. Everything is parsed and formatted in your browser with the native DOMParser. Your data never leaves your device." },
      { q: "Can it handle large XML files?", a: "It handles typical API payloads, feeds and config files comfortably. Extremely large multi-megabyte documents may feel sluggish since everything runs in the browser tab." },
      { q: "What is the difference between well-formed and valid XML?", a: "Well-formed means the syntax is correct: tags closed, nesting proper, attributes quoted. Valid means it also conforms to a schema like XSD. This tool checks well-formedness." }
    ],
    tags: [
      "xml formatter",
      "xml formatter online",
      "xml beautifier",
      "beautify xml online",
      "pretty print xml",
      "xml pretty printer",
      "xml minifier",
      "minify xml online",
      "xml validator",
      "validate xml online",
      "xml checker",
      "xml syntax checker",
      "xml parser online",
      "xml viewer",
      "view xml formatted",
      "format xml file",
      "xml indent",
      "xml indentation tool",
      "xml tidy",
      "clean up xml",
      "xml escape tool",
      "xml unescape",
      "xpath tester",
      "xpath tester online",
      "xpath query tool",
      "evaluate xpath",
      "xml query language",
      "extract data from xml",
      "parse xml feed",
      "rss xml formatter",
      "soap xml formatter",
      "format soap response",
      "sitemap xml checker",
      "xml sitemap validator",
      "config xml formatter",
      "web.config formatter",
      "pom.xml formatter",
      "android manifest formatter",
      "plist formatter",
      "svg xml formatter",
      "xml vs json",
      "convert xml to json",
      "xml to json online",
      "xml tree viewer",
      "collapse xml nodes",
      "xml editor online",
      "edit xml online",
      "free xml tools",
      "xml tools for developers",
      "api xml formatter",
      "rest api xml response",
      "debug xml api",
      "xml namespace",
      "xml cdata",
      "xml comments formatter",
      "xml declaration",
      "xml encoding utf-8",
      "fix malformed xml"
    ],
  };

export default seo;
