import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "XPath Tester - Free Online XML Query Tool | IconVault",
    metaDescription: "Test XPath expressions against any XML in your browser. See matched node paths, string values and scalar results instantly. Free, nothing uploaded.",
    about: [
      "**IconVault**'s **XPath Tester** lets you evaluate **XPath expressions** against any **XML document** and see exactly what they match. Paste your XML, type an expression like `//book[@lang='en']/title`, and get back every **matched node** with its full **node path** and **string value**. It supports all **XPath result types** through the browser's native `document.evaluate`: **node sets**, **booleans**, **numbers** and **strings**.",
      "The tool ships with **sample XML** and ready-made expressions for `count()`, `sum()`, predicates and attribute selectors, so you can learn by experimenting. Everything runs **fully in your browser** with **nothing uploaded**, which makes it safe for testing **Selenium**, **Playwright** or scraping selectors against private XML. It is **free** to try, with a small number of evaluations before Pro is suggested. One honest limitation: **namespaces are not registered**, so namespace-qualified paths may not match."
    ],
    faqs: [
      { q: "What does the XPath Tester do?", a: "It evaluates an XPath expression against an XML document you paste in and shows every matched node with its full path and text value, or the scalar result for boolean, number and string expressions." },
      { q: "Is my XML uploaded to a server?", a: "No. The XML is parsed and evaluated entirely in your browser with the built-in document.evaluate API. Nothing is sent anywhere, so you can safely test selectors against private data." },
      { q: "Which XPath result types are supported?", a: "All of them: node sets (shown as path and value pairs), booleans, numbers and strings. Each result is labeled with its result kind, such as Node set (3) or Boolean." },
      { q: "Can I test XPath for Selenium or Playwright?", a: "Yes. XPath is the same query language used by Selenium, Playwright and browser DevTools, so selectors you verify here will behave the same way against the same XML or HTML structure." },
      { q: "Why does my namespace-qualified XPath return nothing?", a: "The tool does not register namespace prefixes, so paths like ns:book may not match even when the document uses them. Use local-name() workarounds or test against a namespace-free copy of the XML." },
      { q: "Is the tool free?", a: "Yes, it is free to try with no signup. A limited number of free evaluations are included; heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "xpath tester",
      "xpath tester online",
      "test xpath online",
      "xpath evaluator",
      "xpath evaluator online",
      "evaluate xpath expression",
      "xpath expression tester",
      "xpath query tester",
      "xpath online editor",
      "free xpath tester",
      "xml xpath tester",
      "xpath checker",
      "xpath syntax checker",
      "xpath validator online",
      "validate xpath expression",
      "xpath builder online",
      "xpath finder online",
      "xpath 1.0 tester",
      "xpath test tool",
      "run xpath on xml",
      "apply xpath to xml",
      "xpath expression validator",
      "xpath playground",
      "online xpath playground",
      "xpath expressions test",
      "test xpath query against xml",
      "xpath node finder",
      "xpath result viewer",
      "count xpath function online",
      "sum xpath function test",
      "xpath contains function tester",
      "xpath attribute selector test",
      "xpath tutorial tester",
      "learn xpath online tool",
      "xpath cheat sheet tool",
      "xpath predicate tester",
      "xpath boolean function online",
      "xpath string function test",
      "xpath number function online",
      "normalize space xpath tester",
      "xpath position function test",
      "xpath last function online",
      "xml path tester",
      "xml query tool online",
      "query xml online free",
      "extract data from xml online",
      "xml scraper xpath tool",
      "xpath for web scraping test",
      "selenium xpath tester",
      "selenium xpath checker online",
      "playwright xpath tester",
      "chrome xpath tester online",
      "firefox xpath evaluator online",
      "xpath helper tool online",
      "xpath namespace test",
      "xpath local-name tester",
      "xpath text function online",
      "xpath and operator tester",
      "xpath starts-with tester",
      "xpath not function online"
    ],
  };

export default seo;
