import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "XSD Validator - Free Online XML Validator Tool | IconVault",
    metaDescription: "Validate XML against an XSD schema in your browser. Checks element order, required attributes and data types with clear error paths. Free, nothing uploaded.",
    about: [
      "**IconVault**'s **XSD Validator** checks an **XML document** against an **XSD schema** and reports every **structural violation** with a precise **element path**, such as `/catalog/book[2]: missing required attribute \"id\"`. It verifies **element presence**, **xs:sequence order**, **minOccurs/maxOccurs**, **required attributes** and basic **simple types** (string, integer, decimal, boolean, date, dateTime), so you get actionable errors instead of a bare pass or fail.",
      "Be aware this is a **structural check, not a full XSD 1.1 validator**: it does not enforce **facets**, **xs:choice** subtleties, **namespaces**, keys/keyrefs or assertions. For quick schema conformance checks during development it is fast, private and dependable. Everything runs **fully in your browser** with **nothing uploaded**, and it is **free** to try, with a limited number of free validations before Pro is suggested."
    ],
    faqs: [
      { q: "What does the XSD Validator check?", a: "It checks that your XML's root element matches the schema, that required elements are present in xs:sequence order, that occurrence counts respect minOccurs and maxOccurs, that required attributes exist, and that text values match their declared simple types." },
      { q: "Is this a complete XSD 1.1 validator?", a: "No. It is a best-effort structural validator. It does not enforce facets like patterns or length limits, namespace rules, xs:choice subtleties, keys and keyrefs, or assertions. For mission-critical validation, use a dedicated XSD 1.1 processor." },
      { q: "How are errors reported?", a: "Each violation is listed with the full path of the offending element, for example a missing required element or an unexpected element not declared in the schema, so you can jump straight to the problem." },
      { q: "Is my XML or XSD uploaded?", a: "No. Both documents are parsed and compared entirely in your browser. Nothing is sent to any server, which makes it safe for proprietary schemas and payloads." },
      { q: "What happens if my XML is not well-formed?", a: "The tool reports that the XML itself is not well-formed before attempting any schema validation, since a broken document cannot be checked against a schema." },
      { q: "Is the tool free?", a: "Yes, it is free to try with no signup. A limited number of free validations are included; heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "xsd validator",
      "xsd validator online",
      "validate xml against xsd online",
      "xml xsd validation online",
      "xml schema validator",
      "xml validator xsd free",
      "check xml against xsd",
      "validate xml with xsd",
      "xsd validation tool",
      "online xml validator",
      "xml well formed validator",
      "xml schema validation online free",
      "xsd checker online",
      "xsd syntax checker",
      "validate xsd file online",
      "xsd schema validator free",
      "xml against schema tester",
      "xml xsd tester online",
      "xml validation online",
      "free xml validator",
      "xml validator online free",
      "validate xml file online",
      "xml schema check",
      "xsd conformance checker",
      "xsd compliance validator",
      "xml structure validator",
      "xml sequence order validator",
      "xsd minoccurs validator",
      "xsd required attribute checker",
      "xml attribute validation",
      "xsd type validation online",
      "xml data type validator",
      "validate xml decimal date boolean",
      "xsd simple type checker",
      "xml root element validator",
      "xsd 1.0 validator online",
      "best xml validator online",
      "xml validator no upload",
      "xml validator privacy safe",
      "browser xml validator",
      "client side xml validator",
      "soap xml validator online",
      "validate soap envelope xsd",
      "xml config validator",
      "sitemap xml validator",
      "rss xml validator online",
      "svg xml validator",
      "xsd error finder",
      "xml validation error messages",
      "fix xml schema errors",
      "xsd validation report",
      "xml schema violation checker",
      "xsd unexpected element checker",
      "xml missing element validator"
    ],
  };

export default seo;
