import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "XSD Generator - Free Online XML Schema Tool | IconVault",
    metaDescription: "Generate an XSD schema from sample XML in your browser. Infers elements, attributes, data types and min/max occurrences. Free, nothing uploaded.",
    about: [
      "**IconVault**'s **XSD Generator** creates a complete **XSD schema** from a representative **sample XML** document. It walks your XML and infers every **element**, **attribute** and **simple type** (xs:string, xs:integer, xs:decimal, xs:boolean, xs:date, xs:dateTime), detects **required attributes**, and computes **minOccurs** and **maxOccurs** from how often each child appears. The result is a clean, downloadable **schema.xsd** with proper **xs:sequence** and **xs:complexType** structure.",
      "The more representative your sample, the better the schema: include **repeated elements** and **optional fields** so occurrences are inferred correctly. Everything runs **fully in your browser** with **nothing uploaded**, and the generated XSD can be **copied or downloaded** instantly. It is **free** to try, with a limited number of free generations before Pro is suggested."
    ],
    faqs: [
      { q: "What does the XSD Generator do?", a: "You paste a sample XML document and it generates an XSD schema that describes the document's structure: elements, attributes, data types, and min/max occurrence rules, ready to download as schema.xsd." },
      { q: "How accurate is the inferred schema?", a: "Accuracy depends on your sample. Include repeated elements and optional fields so the tool can infer maxOccurs=\"unbounded\" and minOccurs=\"0\" correctly. Conflicting value types fall back to xs:string, so review the output before relying on it." },
      { q: "What data types does it infer?", a: "It infers xs:integer, xs:decimal, xs:boolean, xs:date and xs:dateTime from value patterns, defaulting to xs:string. Attributes present on every instance of an element are marked use=\"required\"." },
      { q: "Is my XML uploaded anywhere?", a: "No. The XML is parsed and analyzed entirely in your browser. Nothing leaves your device, so you can generate schemas from private or client XML safely." },
      { q: "Can I download the generated XSD?", a: "Yes. The output panel has a one-click .xsd download button as well as copy to clipboard, so you can drop the schema straight into your project or validator." },
      { q: "Is the tool free?", a: "Yes, it is free to try with no signup. A limited number of free generations are included; heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "xsd generator",
      "generate xsd from xml",
      "xml to xsd converter online",
      "xsd from xml online",
      "create xsd schema from xml",
      "xsd schema generator free",
      "infer xsd from xml",
      "xml schema generator online",
      "xsd file generator",
      "generate xsd online free",
      "xsd creator online",
      "xsd builder online",
      "xml to xsd online free",
      "convert xml to xsd",
      "xml xsd generator tool",
      "xsd generator from sample xml",
      "xsd schema from xml example",
      "generate xs schema from xml",
      "xsd generator tool",
      "free xsd generator",
      "xsd maker online",
      "xsd authoring tool",
      "create xsd file online",
      "xsd schema creator",
      "xml schema file generator",
      "generate schema for xml",
      "xsd minoccurs generator",
      "xsd type inference tool",
      "xsd complex type generator",
      "xsd sequence generator",
      "xsd attribute generator",
      "xsd simple type inference",
      "xsd from xml document",
      "xsd from xml string",
      "xsd generator for developers",
      "xsd schema design tool",
      "xml validation schema generator",
      "soap xsd generator",
      "wsdl xsd generator online",
      "xsd tutorial generator",
      "learn xsd from xml",
      "xsd example generator",
      "xsd schema template generator",
      "generate xsd for soap request",
      "xml to xsd mapping tool",
      "xsd namespace generator",
      "targetnamespace xsd generator",
      "xsd documentation generator online",
      "visual xsd generator free",
      "online xml schema designer",
      "xsd editor generator free",
      "generate xsd without software",
      "xsd generator no download",
      "xsd generator no signup",
      "xsd generator browser",
      "xsd generator privacy safe",
      "xsd maxoccurs unbounded generator",
      "xsd required attribute generator",
      "xsd complextype from xml",
      "generate xsd schema file",
      "xml instance to xsd"
    ],
  };

export default seo;
