import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "YAML Formatter - Free Online YAML Validation Tool | IconVault",
    metaDescription: "Validate and format YAML online with clear line-number errors. Beautify indentation and switch to a pretty JSON view. Free, runs in your browser.",
    about: [
      "**IconVault**'s **YAML Formatter** validates your **YAML** and rewrites it with clean, consistent **formatting**: normalized **indentation**, tidy **lists** and **maps**, and predictable quoting. If the YAML is invalid, you get a clear **error message** with the exact **line and column** where parsing failed, so fixing **indentation errors** or stray **tabs** takes seconds instead of guesswork.",
      "One click switches the output to a **pretty-printed JSON view**, and you can **copy** or **download** either version. The **YAML parser** loads on demand to keep the page fast, and everything runs **fully in your browser** with **nothing uploaded**. It is **free** to try, with a limited number of free format runs before Pro is suggested."
    ],
    faqs: [
      { q: "What does the YAML Formatter do?", a: "It validates your YAML syntax and outputs a cleanly formatted version with consistent indentation. If the YAML is broken, it shows exactly where, with line and column numbers." },
      { q: "Can I see the YAML as JSON?", a: "Yes. A toggle above the output switches instantly between formatted YAML and a pretty-printed JSON view of the same document, and you can copy or download either one." },
      { q: "What YAML errors does it catch?", a: "It catches the common ones: bad indentation, tabs instead of spaces, unclosed quotes and brackets, duplicate keys behavior, and malformed block scalars, reporting the line and column of each failure." },
      { q: "Is my YAML uploaded to a server?", a: "No. Parsing and formatting happen entirely in your browser using a lazily loaded YAML library. Your config files never leave your device." },
      { q: "Does it work for Kubernetes or Docker Compose files?", a: "Yes. It validates any YAML document, including Kubernetes manifests, docker-compose files, GitHub Actions workflows and Ansible playbooks, which are the most common use cases." },
      { q: "Is the tool free?", a: "Yes, it is free to try with no signup. A limited number of free format runs are included; heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "yaml formatter",
      "yaml formatter online",
      "format yaml online",
      "yaml beautifier",
      "yaml beautifier online",
      "yaml validator",
      "yaml validator online",
      "validate yaml online",
      "check yaml syntax online",
      "yaml lint online",
      "yaml syntax checker",
      "yaml syntax validator",
      "yaml pretty print",
      "pretty print yaml online",
      "yaml indentation fixer",
      "fix yaml indentation online",
      "yaml tidy online",
      "yaml formatter free",
      "best yaml formatter",
      "yaml formatter no signup",
      "yaml normalizer online",
      "yaml canonical formatter",
      "yaml parser online",
      "parse yaml online",
      "yaml viewer online",
      "yaml reader online",
      "yaml to json viewer",
      "yaml json viewer online",
      "yaml editor online free",
      "online yaml editor",
      "yaml playground",
      "yaml tester online",
      "test yaml syntax",
      "yaml error checker",
      "yaml line error finder",
      "yaml indentation error checker",
      "yaml tab error checker",
      "kubernetes yaml validator",
      "validate kubernetes yaml online",
      "docker compose yaml validator",
      "github actions yaml validator",
      "ansible yaml syntax checker",
      "gitlab ci yaml validator",
      "yaml config validator",
      "yaml front matter validator",
      "openapi yaml validator",
      "swagger yaml validator",
      "yaml anchors validator",
      "yaml multiline string formatter",
      "yaml list formatter",
      "yaml map formatter",
      "yaml null value checker",
      "yaml boolean checker",
      "yaml quoting checker",
      "yaml formatter browser",
      "yaml tool online free",
      "fix yaml online",
      "yaml prettifier"
    ],
  };

export default seo;
