import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "YAML to JSON Converter - Free Online Conversion Tool | IconVault",
    metaDescription: "Convert YAML to JSON and JSON to YAML online. Pretty-printed output, instant copy and download. Free, runs fully in your browser.",
    about: [
      "**IconVault**'s **YAML to JSON Converter** converts in **both directions**: **YAML to JSON** with clean **pretty-printed** output, and **JSON to YAML** with natural **indentation** and block style. Switch modes with one click, paste your document, and convert instantly. Invalid input gets a plain-language **error message** instead of a crash, so you know exactly what to fix.",
      "Converted output can be **copied** to the clipboard or **downloaded** as a `.json` or `.yaml` file. The **YAML parser** loads on demand to keep the page fast, and everything runs **fully in your browser** with **nothing uploaded**, which keeps private configs safe. It is **free** to try, with a limited number of free conversions before Pro is suggested."
    ],
    faqs: [
      { q: "Which conversions does this tool support?", a: "Both directions: YAML to JSON and JSON to YAML. Toggle between the two modes with one click; each mode has its own input pane, sample data and file download." },
      { q: "Is the JSON output pretty-printed?", a: "Yes. YAML to JSON conversion produces indented, readable JSON with 2-space indentation. JSON to YAML conversion produces clean block-style YAML." },
      { q: "What happens with invalid input?", a: "The tool shows a clear error message, such as Invalid YAML or Invalid JSON with the underlying parser detail, and leaves the output pane empty so you never get a half-converted result." },
      { q: "Is my data uploaded anywhere?", a: "No. Conversion happens entirely in your browser with a lazily loaded YAML library. Nothing is sent to any server." },
      { q: "Can I download the converted file?", a: "Yes. The download button saves the result as converted.json or converted.yaml depending on the direction you converted." },
      { q: "Is the tool free?", a: "Yes, it is free to try with no signup. A limited number of free conversions are included; heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "yaml to json",
      "yaml to json converter",
      "yaml to json online",
      "convert yaml to json",
      "convert yaml to json online",
      "yaml to json converter online free",
      "json to yaml",
      "json to yaml converter",
      "json to yaml online",
      "convert json to yaml",
      "convert json to yaml online",
      "json to yaml converter online free",
      "yaml json converter",
      "yaml json converter online",
      "yml to json",
      "yml to json converter online",
      "json to yml converter",
      "yaml to json formatter",
      "yaml to json pretty",
      "pretty json from yaml",
      "json to yaml pretty print",
      "yaml to json tool",
      "json to yaml tool",
      "free yaml json converter",
      "yaml json converter no signup",
      "yaml json converter no upload",
      "online yaml json converter",
      "yaml to json parser",
      "json to yaml parser online",
      "yaml to json api alternative",
      "yaml array to json",
      "yaml config to json",
      "kubernetes yaml to json",
      "docker compose to json",
      "openapi yaml to json",
      "swagger yaml to json converter",
      "yaml front matter to json",
      "json to yaml for ansible",
      "json to yaml kubernetes",
      "yaml to json command line alternative",
      "yaml to json javascript",
      "yaml to json formatter validator",
      "validate then convert yaml",
      "yaml anchors to json",
      "yaml multiline to json",
      "json to yaml multiline strings",
      "json to yaml quoting",
      "yaml to json download file",
      "json to yaml download",
      "yaml json converter browser",
      "client side yaml converter",
      "yaml to json without install",
      "json to yaml no signup",
      "yaml to json privacy safe"
    ],
  };

export default seo;
