import type { ToolSeo } from "../tool-seo";

const seo: ToolSeo = {
    title: "ZIP Explorer - Free Online Archive Viewer Tool | IconVault",
    metaDescription: "Browse ZIP files in your browser: file tree, text and image previews, extract single files or everything. Free, nothing uploaded.",
    about: [
      "**IconVault**'s **ZIP Explorer** lets you peek inside a **ZIP archive** without extracting it first. Drop a `.zip` file to see its full **file tree**, then click any entry to get an instant **preview**: **text files** (code, configs, markdown) render their contents, and **images** display inline. Each file has its own **extract button**, or you can **extract all** files at once.",
      "Everything runs **fully in your browser** with **nothing uploaded**, so archives stay on your device. One honest note: browsers cannot recreate the original **folder structure** on download, so Extract all saves each file individually. **Password-protected ZIPs** are not supported. It is **free** to try, with a limited number of free extractions before Pro is suggested."
    ],
    faqs: [
      { q: "What does the ZIP Explorer do?", a: "You drop a ZIP file onto the page and it shows a browsable file tree of the archive. You can preview text files and images in place, extract individual files, or extract everything at once, all without uploading the archive." },
      { q: "Is my ZIP file uploaded to a server?", a: "No. The archive is read and decompressed entirely in your browser. Nothing leaves your device, so it is safe for archives with private content." },
      { q: "Can I extract the original folder structure?", a: "Not exactly. Browsers cannot recreate folders when saving downloads, so Extract all downloads each file individually rather than as a folder tree. Filenames are preserved." },
      { q: "Does it support password-protected ZIPs?", a: "No. Encrypted ZIPs cannot be opened because decryption happens nowhere: everything runs locally in your browser, and the tool does not implement ZIP decryption." },
      { q: "Which file previews are supported?", a: "Text-based files such as code, configs, JSON, XML, CSV and markdown show their contents (long files are truncated in preview), and common image formats like PNG, JPG, GIF and WebP render inline." },
      { q: "Is the tool free?", a: "Yes, it is free to try with no signup. A limited number of free extractions are included; heavier repeated use may prompt an upgrade to Pro." }
    ],
    tags: [
      "zip explorer",
      "zip explorer online",
      "open zip online",
      "open zip file online",
      "view zip contents online",
      "zip file viewer",
      "zip viewer online",
      "browse zip online",
      "zip file opener online",
      "open zip without downloading",
      "extract zip online",
      "extract zip files online",
      "unzip online free",
      "unzip files online",
      "online unzip tool",
      "zip extractor online",
      "extract files from zip online",
      "zip opener",
      "zip file reader",
      "read zip file online",
      "peek inside zip",
      "preview zip contents",
      "zip content viewer",
      "zip archive viewer",
      "list files in zip online",
      "zip file list viewer",
      "zip tree viewer",
      "zip folder viewer online",
      "download file from zip online",
      "extract single file from zip",
      "extract one file from zip online",
      "zip image preview",
      "preview images in zip online",
      "zip text preview online",
      "zip file inspector",
      "zip archive inspector online",
      "check zip contents before download",
      "zip file checker online",
      "corrupt zip checker",
      "zip file analyzer",
      "zip metadata viewer",
      "zip file size viewer",
      "zip entry list",
      "online zip tool free",
      "zip tool no install",
      "zip viewer no download",
      "unzip in browser",
      "browser zip extractor",
      "client side unzip",
      "zip opener no signup",
      "free zip file opener",
      "zip viewer mac online",
      "zip viewer windows online",
      "open zip on phone online",
      "zip viewer android online",
      "zip file browser online"
    ],
  };

export default seo;
