// /tools/nginx-generator - Build a production-ready nginx server block:
// domain, root, port, SSL, gzip, static / reverse-proxy / PHP-FPM modes.
// Live nginx.conf preview, copy + download. 100% client-side.

import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Copy, Download } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { downloadBlob } from "@/lib/logo-builder";
import { usePlan } from "@/hooks/usePlan";
import { useToolTrial, TOOL_TRIAL_LIMIT } from "@/lib/tool-trial";
import toolSeo from "@/lib/tool-seo-data/nginx-generator";
import toolSeoMeta from "@/lib/tool-seo-meta-data/nginx-generator";
import ToolPageShell, { ActionButton, TrialUpsell } from "@/components/ToolPageShell";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

export const Route = createFileRoute("/tools_/nginx-generator")({
  head: () => {
    const seo = toolSeoMeta;
    const canonical = "https://iconvault.site/tools/nginx-generator";
    return {
      meta: [
        { title: seo.title },
        { name: "description", content: seo.metaDescription },
        { property: "og:title", content: seo.title },
        { property: "og:description", content: seo.metaDescription },
        { property: "og:type", content: "website" },
        { property: "og:url", content: canonical },
        { name: "twitter:card", content: "summary" },
        { name: "twitter:title", content: seo.title },
        { name: "twitter:description", content: seo.metaDescription },
      ],
      links: [{ rel: "canonical", href: canonical }],
    };
  },
  component: NginxGeneratorTool,
});

type Mode = "static" | "proxy" | "php";

function ToggleRow({ label, hint, checked, onChange }: { label: string; hint?: string; checked: boolean; onChange: (v: boolean) => void }) {
  return (
    <div className="flex items-center justify-between gap-3 py-1.5">
      <div>
        <p className="text-[13px] font-medium">{label}</p>
        {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
      </div>
      <Switch checked={checked} onCheckedChange={onChange} />
    </div>
  );
}

function buildConf(o: {
  domain: string; root: string; port: number; ssl: boolean; certPath: string; keyPath: string;
  forceHttps: boolean; www: "none" | "to-www" | "to-nonwww"; gzip: boolean; mode: Mode;
  proxyTarget: string; proxyHeaders: boolean; phpSocket: string; maxBody: string; cacheAssets: boolean;
}): string {
  const d = o.domain.trim() || "example.com";
  const root = o.root.trim() || "/var/www/html";
  const lines: string[] = [];
  lines.push("# Generated by IconVault Nginx Generator");
  lines.push("# Place in /etc/nginx/sites-available/ and symlink to sites-enabled,");
  lines.push("# then run: sudo nginx -t && sudo systemctl reload nginx");
  lines.push("");

  if (o.ssl && o.forceHttps) {
    lines.push("# Redirect all HTTP traffic to HTTPS");
    lines.push("server {");
    lines.push(`    listen 80;`);
    lines.push(`    listen [::]:80;`);
    lines.push(`    server_name ${d}${o.www !== "none" ? ` www.${d}` : ""};`);
    lines.push(`    return 301 https://$host$request_uri;`);
    lines.push("}");
    lines.push("");
  }

  lines.push("server {");
  const listenPort = o.ssl ? 443 : o.port;
  lines.push(o.ssl ? `    listen ${listenPort} ssl;` : `    listen ${listenPort};`);
  if (o.ssl) lines.push(`    listen [::]:${listenPort} ssl;`);
  else lines.push(`    listen [::]:${listenPort};`);
  lines.push("");

  let names = d;
  if (o.www === "to-www") names = `${d} www.${d}`;
  else if (o.www === "to-nonwww") names = `www.${d} ${d}`;
  lines.push(`    server_name ${names};`);
  lines.push("");

  if (o.www === "to-www") {
    lines.push("    # Canonical www redirect");
    lines.push(`    if ($host = ${d}) { return 301 $scheme://www.${d}$request_uri; }`);
    lines.push("");
  } else if (o.www === "to-nonwww") {
    lines.push("    # Canonical non-www redirect");
    lines.push(`    if ($host = www.${d}) { return 301 $scheme://${d}$request_uri; }`);
    lines.push("");
  }

  if (o.ssl) {
    lines.push("    # SSL certificates (from Lets Encrypt or your CA)");
    lines.push(`    ssl_certificate ${o.certPath.trim() || `/etc/letsencrypt/live/${d}/fullchain.pem`};`);
    lines.push(`    ssl_certificate_key ${o.keyPath.trim() || `/etc/letsencrypt/live/${d}/privkey.pem`};`);
    lines.push("    ssl_protocols TLSv1.2 TLSv1.3;");
    lines.push("    ssl_prefer_server_ciphers on;");
    lines.push('    add_header Strict-Transport-Security "max-age=63072000" always;');
    lines.push("");
  }

  lines.push(`    root ${root};`);
  lines.push("    index index.html index.htm;");
  if (o.maxBody.trim()) lines.push(`    client_max_body_size ${o.maxBody.trim()};`);
  lines.push("");

  if (o.gzip) {
    lines.push("    # Gzip compression");
    lines.push("    gzip on;");
    lines.push("    gzip_vary on;");
    lines.push("    gzip_min_length 1024;");
    lines.push("    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml image/svg+xml;");
    lines.push("");
  }

  if (o.mode === "static") {
    lines.push("    location / {");
    lines.push("        try_files $uri $uri/ =404;");
    lines.push("    }");
    if (o.cacheAssets) {
      lines.push("");
      lines.push("    # Long-lived cache for versioned static assets");
      lines.push("    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {");
      lines.push("        expires 30d;");
      lines.push("        add_header Cache-Control \"public, immutable\";");
      lines.push("    }");
    }
  } else if (o.mode === "proxy") {
    const target = o.proxyTarget.trim() || "http://127.0.0.1:3000";
    lines.push("    location / {");
    lines.push(`        proxy_pass ${target};`);
    if (o.proxyHeaders) {
      lines.push("        proxy_http_version 1.1;");
      lines.push("        proxy_set_header Upgrade $http_upgrade;");
      lines.push('        proxy_set_header Connection "upgrade";');
      lines.push("        proxy_set_header Host $host;");
      lines.push("        proxy_set_header X-Real-IP $remote_addr;");
      lines.push("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
      lines.push("        proxy_set_header X-Forwarded-Proto $scheme;");
    }
    lines.push("    }");
  } else {
    lines.push("    location / {");
    lines.push("        try_files $uri $uri/ /index.php?$query_string;");
    lines.push("    }");
    lines.push("");
    lines.push("    # PHP via PHP-FPM");
    lines.push("    location ~ \\.php$ {");
    lines.push("        include fastcgi_params;");
    lines.push(`        fastcgi_pass ${o.phpSocket.trim() || "unix:/run/php/php8.3-fpm.sock"};`);
    lines.push("        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;");
    lines.push("        fastcgi_index index.php;");
    lines.push("    }");
  }

  lines.push("");
  lines.push("    # Security: deny hidden files");
  lines.push("    location ~ /\\. {");
  lines.push("        deny all;");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

function NginxGeneratorTool() {
  const { isPro } = usePlan();
  const trial = useToolTrial("nginx-generator", isPro);
  const seo = toolSeo;

  const [domain, setDomain] = useState("example.com");
  const [root, setRoot] = useState("/var/www/html");
  const [port, setPort] = useState(80);
  const [mode, setMode] = useState<Mode>("static");
  const [ssl, setSsl] = useState(false);
  const [certPath, setCertPath] = useState("");
  const [keyPath, setKeyPath] = useState("");
  const [forceHttps, setForceHttps] = useState(true);
  const [www, setWww] = useState<"none" | "to-www" | "to-nonwww">("none");
  const [gzip, setGzip] = useState(true);
  const [cacheAssets, setCacheAssets] = useState(true);
  const [proxyTarget, setProxyTarget] = useState("http://127.0.0.1:3000");
  const [proxyHeaders, setProxyHeaders] = useState(true);
  const [phpSocket, setPhpSocket] = useState("unix:/run/php/php8.3-fpm.sock");
  const [maxBody, setMaxBody] = useState("10M");

  const conf = useMemo(
    () => buildConf({ domain, root, port, ssl, certPath, keyPath, forceHttps, www, gzip, mode, proxyTarget, proxyHeaders, phpSocket, maxBody, cacheAssets }),
    [domain, root, port, ssl, certPath, keyPath, forceHttps, www, gzip, mode, proxyTarget, proxyHeaders, phpSocket, maxBody, cacheAssets],
  );

  const fileName = `${(domain.trim() || "example.com").replace(/^www\./, "")}.conf`;

  const copy = async () => {
    if (!trial.canUse) return;
    const ok = await copyToClipboard(conf);
    if (ok) {
      trial.recordUse();
      toast.success("nginx.conf copied.");
    } else toast.error("Could not copy to clipboard.");
  };

  const download = () => {
    if (!trial.canUse) return;
    downloadBlob(new Blob([conf], { type: "text/plain" }), fileName);
    trial.recordUse();
    toast.success(`${fileName} downloaded.`);
  };

  return (
    <ToolPageShell toolId="nginx-generator" seo={seo} trial={trial} isPro={isPro}>
      <TrialUpsell toolName="Nginx Config Generator" left={trial.left} />

      <div className="grid gap-6 lg:grid-cols-[380px_1fr]">
        <div className="space-y-5 rounded-2xl border border-border bg-card p-5">
          <div className="grid grid-cols-2 gap-3">
            <div className="col-span-2">
              <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Domain</Label>
              <Input value={domain} onChange={(e) => setDomain(e.target.value)} className="font-mono" placeholder="example.com" />
            </div>
            <div>
              <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Port</Label>
              <Input type="number" min={1} max={65535} value={port} onChange={(e) => setPort(parseInt(e.target.value || "80", 10))} className="font-mono" />
            </div>
            <div>
              <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Mode</Label>
              <Select value={mode} onValueChange={(v) => setMode(v as Mode)}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="static">Static files</SelectItem>
                  <SelectItem value="proxy">Reverse proxy</SelectItem>
                  <SelectItem value="php">PHP-FPM</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="col-span-2">
              <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Document root</Label>
              <Input value={root} onChange={(e) => setRoot(e.target.value)} className="font-mono" placeholder="/var/www/html" />
            </div>
            {mode === "proxy" && (
              <div className="col-span-2">
                <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Proxy target</Label>
                <Input value={proxyTarget} onChange={(e) => setProxyTarget(e.target.value)} className="font-mono" placeholder="http://127.0.0.1:3000" />
              </div>
            )}
            {mode === "php" && (
              <div className="col-span-2">
                <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">PHP-FPM socket</Label>
                <Input value={phpSocket} onChange={(e) => setPhpSocket(e.target.value)} className="font-mono" placeholder="unix:/run/php/php8.3-fpm.sock" />
              </div>
            )}
            <div className="col-span-2">
              <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Max upload size</Label>
              <Input value={maxBody} onChange={(e) => setMaxBody(e.target.value)} className="font-mono" placeholder="10M" />
            </div>
          </div>

          <div className="divide-y divide-border/60 rounded-xl border border-border px-4">
            <ToggleRow label="Enable SSL" hint="Listens on 443 with TLS 1.2/1.3" checked={ssl} onChange={setSsl} />
            {ssl && (
              <>
                <div className="grid gap-2 py-2">
                  <Input value={certPath} onChange={(e) => setCertPath(e.target.value)} className="font-mono text-xs" placeholder="Cert path (default: Lets Encrypt)" />
                  <Input value={keyPath} onChange={(e) => setKeyPath(e.target.value)} className="font-mono text-xs" placeholder="Key path (default: Lets Encrypt)" />
                </div>
                <ToggleRow label="Force HTTPS" hint="301 redirect from port 80" checked={forceHttps} onChange={setForceHttps} />
              </>
            )}
            <ToggleRow label="Gzip compression" hint="Compress text, CSS, JS and SVG" checked={gzip} onChange={setGzip} />
            <ToggleRow label="Cache static assets" hint="30-day immutable cache headers" checked={cacheAssets} onChange={setCacheAssets} />
            <ToggleRow label="Proxy headers" hint="Forwarded-For, Host, WebSocket upgrade" checked={proxyHeaders} onChange={setProxyHeaders} />
          </div>

          <div>
            <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Canonical domain</Label>
            <Select value={www} onValueChange={(v) => setWww(v as typeof www)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="none">No redirect</SelectItem>
                <SelectItem value="to-www">Redirect to www</SelectItem>
                <SelectItem value="to-nonwww">Redirect to non-www</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <ActionButton busy={false} disabled={!trial.canUse} onClick={download}>
            <Download className="h-4 w-4" /> Download .conf
          </ActionButton>
          {!isPro && (
            <p className="text-xs text-muted-foreground">
              {trial.left} of {TOOL_TRIAL_LIMIT} free generations left - runs fully in your browser, nothing is uploaded.
            </p>
          )}
        </div>

        <div className="rounded-2xl border border-border bg-card p-5">
          <div className="mb-3 flex items-center justify-between">
            <p className="text-[13px] font-medium text-foreground/80">Live preview: {fileName}</p>
            <button
              type="button"
              onClick={copy}
              disabled={!trial.canUse}
              className={cn(
                "inline-flex items-center gap-1.5 rounded-xl border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition hover:border-primary/40 hover:text-foreground",
                !trial.canUse && "cursor-not-allowed opacity-50",
              )}
            >
              <Copy className="h-3.5 w-3.5" /> Copy
            </button>
          </div>
          <pre className="max-h-[640px] overflow-auto whitespace-pre rounded-xl bg-zinc-950 p-4 font-mono text-xs leading-relaxed text-zinc-100">
            {conf}
          </pre>
          <p className="mt-3 text-xs text-muted-foreground">
            After downloading, place the file in /etc/nginx/sites-available/, symlink it into sites-enabled, then run
            <span className="font-mono"> sudo nginx -t &amp;&amp; sudo systemctl reload nginx</span> to apply.
          </p>
        </div>
      </div>
    </ToolPageShell>
  );
}
