// /tools/docker-compose-generator - Compose a docker-compose.yml visually:
// add/remove services (name, image, ports, volumes, env, depends_on,
// restart), custom networks. Live YAML, copy + download. 100% client-side.

import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Copy, Download, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { downloadBlob } from "@/lib/logo-builder";
import { usePlan } from "@/hooks/usePlan";
import { useToolTrial, TOOL_TRIAL_LIMIT } from "@/lib/tool-trial";
import { getToolSeo } from "@/lib/tool-seo";
import { getToolSeoMeta } from "@/lib/tool-seo-meta";
import ToolPageShell, { ActionButton, TrialUpsell } from "@/components/ToolPageShell";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const Route = createFileRoute("/tools_/docker-compose-generator")({
  head: () => {
    const seo = getToolSeoMeta("docker-compose-generator");
    const canonical = "https://iconvault.site/tools/docker-compose-generator";
    return {
      meta: [
        { title: seo.title },
        { name: "description", content: seo.metaDescription },
        { property: "og:title", content: seo.title },
        { property: "og:description", content: seo.metaDescription },
        { property: "og:type", content: "website" },
        { property: "og:url", content: canonical },
        { name: "twitter:card", content: "summary" },
        { name: "twitter:title", content: seo.title },
        { name: "twitter:description", content: seo.metaDescription },
      ],
      links: [{ rel: "canonical", href: canonical }],
    };
  },
  component: ComposeGeneratorTool,
});

interface Service {
  id: number;
  name: string;
  image: string;
  ports: string;
  volumes: string;
  env: string;
  dependsOn: string;
  restart: string;
  networks: string;
}

const PRESETS: Record<string, Partial<Service>> = {
  web: { image: "nginx:alpine", ports: "8080:80", volumes: "./html:/usr/share/nginx/html:ro" },
  app: { image: "node:22-alpine", ports: "3000:3000", volumes: "./app:/app" },
  postgres: { image: "postgres:16-alpine", ports: "5432:5432", volumes: "pgdata:/var/lib/postgresql/data", env: "POSTGRES_PASSWORD=secret" },
  redis: { image: "redis:7-alpine", ports: "6379:6379", volumes: "redisdata:/data" },
  mongo: { image: "mongo:7", ports: "27017:27017", volumes: "mongodata:/data/db" },
  mysql: { image: "mysql:8", ports: "3306:3306", volumes: "mysqldata:/var/lib/mysql", env: "MYSQL_ROOT_PASSWORD=secret" },
};

let svcSeq = 1;

const blankService = (name = "", preset?: Partial<Service>): Service => ({
  id: svcSeq++,
  name,
  image: preset?.image ?? "",
  ports: preset?.ports ?? "",
  volumes: preset?.volumes ?? "",
  env: preset?.env ?? "",
  dependsOn: "",
  restart: "unless-stopped",
  networks: "",
});

const yamlList = (raw: string): string[] => raw.split(/[\n,]+/).map((s) => s.trim()).filter(Boolean);

const yamlValue = (v: string): string => (/^[a-zA-Z0-9_.\-/:]+$/.test(v) ? v : JSON.stringify(v));

function buildYaml(services: Service[], networks: string): string {
  const L: string[] = [];
  L.push("# Generated by IconVault Compose Generator");
  L.push("# Run with: docker compose up -d");
  L.push("");
  L.push('version: "3.9"');
  L.push("");
  L.push("services:");

  for (const s of services) {
    const name = s.name.trim().toLowerCase().replace(/[^a-z0-9_-]/g, "") || "service";
    L.push(`  ${name}:`);
    if (s.image.trim()) L.push(`    image: ${yamlValue(s.image.trim())}`);
    if (s.restart !== "no") L.push(`    restart: ${s.restart}`);
    const ports = yamlList(s.ports);
    if (ports.length) {
      L.push("    ports:");
      for (const p of ports) L.push(`      - "${p}"`);
    }
    const volumes = yamlList(s.volumes);
    if (volumes.length) {
      L.push("    volumes:");
      for (const v of volumes) L.push(`      - ${yamlValue(v)}`);
    }
    const envs = yamlList(s.env);
    if (envs.length) {
      L.push("    environment:");
      for (const e of envs) L.push(`      - ${yamlValue(e)}`);
    }
    const deps = yamlList(s.dependsOn);
    if (deps.length) {
      L.push("    depends_on:");
      for (const d of deps) L.push(`      - ${d.toLowerCase().replace(/[^a-z0-9_-]/g, "")}`);
    }
    const nets = yamlList(s.networks);
    if (nets.length) {
      L.push("    networks:");
      for (const n of nets) L.push(`      - ${n.toLowerCase().replace(/[^a-z0-9_-]/g, "")}`);
    }
  }

  const nets = yamlList(networks);
  const usedVols = new Set<string>();
  for (const s of services) {
    for (const v of yamlList(s.volumes)) {
      const host = v.split(":")[0] ?? "";
      if (host && !host.startsWith(".") && !host.startsWith("/") && !host.startsWith("~")) usedVols.add(host);
    }
  }
  if (nets.length || usedVols.size) L.push("");
  if (nets.length) {
    L.push("networks:");
    for (const n of nets) L.push(`  ${n.toLowerCase().replace(/[^a-z0-9_-]/g, "")}:`);
  }
  if (usedVols.size) {
    L.push("volumes:");
    for (const v of [...usedVols].sort()) L.push(`  ${v}:`);
  }
  L.push("");
  return L.join("\n");
}

async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string }) {
  return (
    <div>
      <Label className="mb-1 block text-xs font-medium text-foreground/70">{label}</Label>
      <Input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="font-mono text-xs" />
    </div>
  );
}

function ComposeGeneratorTool() {
  const { isPro } = usePlan();
  const trial = useToolTrial("docker-compose-generator", isPro);
  const seo = getToolSeo("docker-compose-generator");

  const [services, setServices] = useState<Service[]>([
    blankService("web", PRESETS["web"]),
    blankService("db", PRESETS["postgres"]),
  ]);
  const [networks, setNetworks] = useState("");
  const [presetKey, setPresetKey] = useState("web");

  const patch = (id: number, p: Partial<Service>) =>
    setServices((prev) => prev.map((s) => (s.id === id ? { ...s, ...p } : s)));

  const yml = useMemo(() => buildYaml(services, networks), [services, networks]);

  const copy = async () => {
    if (!trial.canUse) return;
    const ok = await copyToClipboard(yml);
    if (ok) {
      trial.recordUse();
      toast.success("docker-compose.yml copied.");
    } else toast.error("Could not copy to clipboard.");
  };

  const download = () => {
    if (!trial.canUse) return;
    downloadBlob(new Blob([yml], { type: "text/yaml" }), "docker-compose.yml");
    trial.recordUse();
    toast.success("docker-compose.yml downloaded.");
  };

  return (
    <ToolPageShell toolId="docker-compose-generator" seo={seo} trial={trial} isPro={isPro}>
      <TrialUpsell toolName="Compose Generator" left={trial.left} />

      <div className="grid gap-6 lg:grid-cols-[400px_1fr]">
        <div className="space-y-4">
          <div className="rounded-2xl border border-border bg-card p-5">
            <div className="mb-3 flex items-center justify-between gap-2">
              <Label className="text-[13px] font-medium text-foreground/80">Services ({services.length})</Label>
              <div className="flex items-center gap-2">
                <Select value={presetKey} onValueChange={setPresetKey}>
                  <SelectTrigger className="w-32"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {Object.keys(PRESETS).map((k) => (
                      <SelectItem key={k} value={k}>{k}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <button
                  type="button"
                  onClick={() => setServices((p) => [...p, blankService(presetKey, PRESETS[presetKey])])}
                  className="inline-flex items-center gap-1 rounded-lg border border-border px-2.5 py-1.5 text-xs font-semibold text-muted-foreground transition hover:border-primary/40 hover:text-foreground"
                >
                  <Plus className="h-3.5 w-3.5" /> Add
                </button>
              </div>
            </div>
            <div className="max-h-[520px] space-y-4 overflow-y-auto pr-1">
              {services.map((s) => (
                <div key={s.id} className="space-y-2 rounded-xl border border-border/70 p-3">
                  <div className="flex items-center gap-2">
                    <Input
                      value={s.name}
                      onChange={(e) => patch(s.id, { name: e.target.value })}
                      placeholder="service-name"
                      className="font-mono text-xs font-bold"
                    />
                    <button
                      type="button"
                      onClick={() => setServices((p) => p.filter((x) => x.id !== s.id))}
                      aria-label="Remove service"
                      className="shrink-0 rounded-lg p-1.5 text-muted-foreground transition hover:bg-red-500/10 hover:text-red-500"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                  <Field label="Image" value={s.image} onChange={(v) => patch(s.id, { image: v })} placeholder="nginx:alpine" />
                  <div className="grid grid-cols-2 gap-2">
                    <Field label="Ports (host:container)" value={s.ports} onChange={(v) => patch(s.id, { ports: v })} placeholder="8080:80" />
                    <Field label="Depends on" value={s.dependsOn} onChange={(v) => patch(s.id, { dependsOn: v })} placeholder="db, cache" />
                  </div>
                  <Field label="Volumes" value={s.volumes} onChange={(v) => patch(s.id, { volumes: v })} placeholder="./data:/data" />
                  <Field label="Environment (KEY=value)" value={s.env} onChange={(v) => patch(s.id, { env: v })} placeholder="KEY=value" />
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <Label className="mb-1 block text-xs font-medium text-foreground/70">Restart</Label>
                      <Select value={s.restart} onValueChange={(v) => patch(s.id, { restart: v })}>
                        <SelectTrigger className="text-xs"><SelectValue /></SelectTrigger>
                        <SelectContent>
                          <SelectItem value="no">no</SelectItem>
                          <SelectItem value="always">always</SelectItem>
                          <SelectItem value="unless-stopped">unless-stopped</SelectItem>
                          <SelectItem value="on-failure">on-failure</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <Field label="Networks" value={s.networks} onChange={(v) => patch(s.id, { networks: v })} placeholder="frontend" />
                  </div>
                </div>
              ))}
              {services.length === 0 && <p className="text-sm text-muted-foreground">Add at least one service.</p>}
            </div>
            <p className="mt-2 text-xs text-muted-foreground">Separate multiple values with commas or new lines.</p>
          </div>

          <div className="rounded-2xl border border-border bg-card p-5">
            <Field label="Custom networks (comma separated)" value={networks} onChange={setNetworks} placeholder="frontend, backend" />
          </div>

          <div className="rounded-2xl border border-border bg-card p-5">
            <ActionButton busy={false} disabled={!trial.canUse || services.length === 0} onClick={download}>
              <Download className="h-4 w-4" /> Download compose file
            </ActionButton>
            {!isPro && (
              <p className="mt-2 text-xs text-muted-foreground">
                {trial.left} of {TOOL_TRIAL_LIMIT} free generations left - runs fully in your browser, nothing is uploaded.
              </p>
            )}
          </div>
        </div>

        <div className="rounded-2xl border border-border bg-card p-5">
          <div className="mb-3 flex items-center justify-between">
            <p className="text-[13px] font-medium text-foreground/80">Live preview: docker-compose.yml</p>
            <button
              type="button"
              onClick={copy}
              disabled={!trial.canUse}
              className={cn(
                "inline-flex items-center gap-1.5 rounded-xl border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition hover:border-primary/40 hover:text-foreground",
                !trial.canUse && "cursor-not-allowed opacity-50",
              )}
            >
              <Copy className="h-3.5 w-3.5" /> Copy
            </button>
          </div>
          <pre className="max-h-[720px] overflow-auto whitespace-pre rounded-xl bg-zinc-950 p-4 font-mono text-xs leading-relaxed text-zinc-100">
            {yml}
          </pre>
          <p className="mt-3 text-xs text-muted-foreground">
            Named volumes are declared at the bottom automatically. Bring the stack up with
            <span className="font-mono"> docker compose up -d</span>.
          </p>
        </div>
      </div>
    </ToolPageShell>
  );
}
