// /tools/htaccess-generator - Build a production .htaccess visually:
// HTTPS redirect, www redirect, gzip, browser caching, security headers,
// custom error pages, directory listing, hotlink protection and rewrite
// rules. Live preview, copy + download. 100% client-side.

import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Copy, Download, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { downloadBlob } from "@/lib/logo-builder";
import { usePlan } from "@/hooks/usePlan";
import { useToolTrial, TOOL_TRIAL_LIMIT } from "@/lib/tool-trial";
import toolSeo from "@/lib/tool-seo-data/htaccess-generator";
import toolSeoMeta from "@/lib/tool-seo-meta-data/htaccess-generator";
import ToolPageShell, { ActionButton, TrialUpsell } from "@/components/ToolPageShell";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

export const Route = createFileRoute("/tools_/htaccess-generator")({
  head: () => {
    const seo = toolSeoMeta;
    const canonical = "https://iconvault.site/tools/htaccess-generator";
    return {
      meta: [
        { title: seo.title },
        { name: "description", content: seo.metaDescription },
        { property: "og:title", content: seo.title },
        { property: "og:description", content: seo.metaDescription },
        { property: "og:type", content: "website" },
        { property: "og:url", content: canonical },
        { name: "twitter:card", content: "summary" },
        { name: "twitter:title", content: seo.title },
        { name: "twitter:description", content: seo.metaDescription },
      ],
      links: [{ rel: "canonical", href: canonical }],
    };
  },
  component: HtaccessGeneratorTool,
});

interface RewriteRule {
  id: number;
  from: string;
  to: string;
  permanent: boolean;
}

let ruleSeq = 1;

function ToggleRow({ label, hint, checked, onChange }: { label: string; hint?: string; checked: boolean; onChange: (v: boolean) => void }) {
  return (
    <div className="flex items-center justify-between gap-3 py-1.5">
      <div>
        <p className="text-[13px] font-medium">{label}</p>
        {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
      </div>
      <Switch checked={checked} onCheckedChange={onChange} />
    </div>
  );
}

interface Opts {
  https: boolean; www: "none" | "to-www" | "to-nonwww"; gzip: boolean; caching: boolean;
  secHeaders: boolean; err404: string; err500: string; noListing: boolean; hotlink: boolean; hotlinkDomain: string;
  rules: RewriteRule[];
}

function buildHtaccess(o: Opts): string {
  const L: string[] = [];
  L.push("# Generated by IconVault htaccess Generator");
  L.push("");

  const needRewrite = o.https || o.www !== "none" || o.rules.length > 0;
  if (needRewrite) {
    L.push("<IfModule mod_rewrite.c>");
    L.push("  RewriteEngine On");
    L.push("");
    if (o.https) {
      L.push("  # Force HTTPS");
      L.push("  RewriteCond %{HTTPS} off");
      L.push("  RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      L.push("");
    }
    if (o.www === "to-www") {
      L.push("  # Redirect to www");
      L.push("  RewriteCond %{HTTP_HOST} !^www\\. [NC]");
      L.push("  RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [L,R=301]");
      L.push("");
    } else if (o.www === "to-nonwww") {
      L.push("  # Redirect to non-www");
      L.push("  RewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]");
      L.push("  RewriteRule ^(.*)$ https://%1/$1 [L,R=301]");
      L.push("");
    }
    for (const r of o.rules) {
      if (!r.from.trim() || !r.to.trim()) continue;
      L.push(`  RewriteRule ${r.from.trim()} ${r.to.trim()} [L${r.permanent ? ",R=301" : ""}]`);
    }
    if (o.rules.some((r) => r.from.trim() && r.to.trim())) L.push("");
    L.push("</IfModule>");
    L.push("");
  }

  if (o.gzip) {
    L.push("# Gzip compression");
    L.push("<IfModule mod_deflate.c>");
    L.push("  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json application/xml image/svg+xml");
    L.push("</IfModule>");
    L.push("");
  }

  if (o.caching) {
    L.push("# Browser caching");
    L.push("<IfModule mod_expires.c>");
    L.push("  ExpiresActive On");
    L.push('  ExpiresByType image/jpg "access plus 1 month"');
    L.push('  ExpiresByType image/jpeg "access plus 1 month"');
    L.push('  ExpiresByType image/png "access plus 1 month"');
    L.push('  ExpiresByType image/gif "access plus 1 month"');
    L.push('  ExpiresByType image/webp "access plus 1 month"');
    L.push('  ExpiresByType image/svg+xml "access plus 1 month"');
    L.push('  ExpiresByType text/css "access plus 1 month"');
    L.push('  ExpiresByType application/javascript "access plus 1 month"');
    L.push('  ExpiresByType font/woff2 "access plus 1 year"');
    L.push('  ExpiresDefault "access plus 1 week"');
    L.push("</IfModule>");
    L.push("");
  }

  if (o.secHeaders) {
    L.push("# Security headers");
    L.push("<IfModule mod_headers.c>");
    L.push('  Header always set X-Content-Type-Options "nosniff"');
    L.push('  Header always set X-Frame-Options "SAMEORIGIN"');
    L.push('  Header always set Referrer-Policy "strict-origin-when-cross-origin"');
    L.push('  Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"');
    L.push('  Header always set Content-Security-Policy "default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data: https:; font-src \'self\' data:"');
    L.push("</IfModule>");
    L.push("");
  }

  if (o.noListing) {
    L.push("# Disable directory listing");
    L.push("Options -Indexes");
    L.push("");
  }

  if (o.hotlink) {
    const d = (o.hotlinkDomain.trim() || "example.com").replace(/^https?:\/\//, "").replace(/\/.*$/, "");
    L.push("# Hotlink protection for images");
    L.push("<IfModule mod_rewrite.c>");
    L.push("  RewriteEngine On");
    L.push("  RewriteCond %{HTTP_REFERER} !^$");
    L.push(`  RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${d.replace(/\./g, "\\.")}/ [NC]`);
    L.push("  RewriteRule \\.(jpe?g|png|gif|webp|svg)$ - [F,NC]");
    L.push("</IfModule>");
    L.push("");
  }

  if (o.err404.trim() || o.err500.trim()) {
    L.push("# Custom error pages");
    if (o.err404.trim()) L.push(`ErrorDocument 404 ${o.err404.trim()}`);
    if (o.err500.trim()) L.push(`ErrorDocument 500 ${o.err500.trim()}`);
    L.push("");
  }

  return L.join("\n");
}

async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

function HtaccessGeneratorTool() {
  const { isPro } = usePlan();
  const trial = useToolTrial("htaccess-generator", isPro);
  const seo = toolSeo;

  const [https, setHttps] = useState(true);
  const [www, setWww] = useState<"none" | "to-www" | "to-nonwww">("none");
  const [gzip, setGzip] = useState(true);
  const [caching, setCaching] = useState(true);
  const [secHeaders, setSecHeaders] = useState(true);
  const [err404, setErr404] = useState("/404.html");
  const [err500, setErr500] = useState("/500.html");
  const [noListing, setNoListing] = useState(true);
  const [hotlink, setHotlink] = useState(false);
  const [hotlinkDomain, setHotlinkDomain] = useState("example.com");
  const [rules, setRules] = useState<RewriteRule[]>([
    { id: ruleSeq++, from: "^old-page/?$", to: "/new-page", permanent: true },
  ]);

  const out = useMemo(
    () => buildHtaccess({ https, www, gzip, caching, secHeaders, err404, err500, noListing, hotlink, hotlinkDomain, rules }),
    [https, www, gzip, caching, secHeaders, err404, err500, noListing, hotlink, hotlinkDomain, rules],
  );

  const copy = async () => {
    if (!trial.canUse) return;
    const ok = await copyToClipboard(out);
    if (ok) {
      trial.recordUse();
      toast.success(".htaccess copied.");
    } else toast.error("Could not copy to clipboard.");
  };

  const download = () => {
    if (!trial.canUse) return;
    downloadBlob(new Blob([out], { type: "text/plain" }), ".htaccess");
    trial.recordUse();
    toast.success(".htaccess downloaded.");
  };

  return (
    <ToolPageShell toolId="htaccess-generator" seo={seo} trial={trial} isPro={isPro}>
      <TrialUpsell toolName="htaccess Generator" left={trial.left} />

      <div className="grid gap-6 lg:grid-cols-[380px_1fr]">
        <div className="space-y-5 rounded-2xl border border-border bg-card p-5">
          <div>
            <p className="mb-1.5 text-[13px] font-medium text-foreground/80">Redirects</p>
            <div className="divide-y divide-border/60 rounded-xl border border-border px-4">
              <ToggleRow label="Force HTTPS" hint="301 redirect http to https" checked={https} onChange={setHttps} />
              <div className="py-2">
                <Label className="mb-1.5 block text-xs text-muted-foreground">Canonical domain</Label>
                <Select value={www} onValueChange={(v) => setWww(v as typeof www)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">No redirect</SelectItem>
                    <SelectItem value="to-www">Redirect to www</SelectItem>
                    <SelectItem value="to-nonwww">Redirect to non-www</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>

          <div>
            <p className="mb-1.5 text-[13px] font-medium text-foreground/80">Performance</p>
            <div className="divide-y divide-border/60 rounded-xl border border-border px-4">
              <ToggleRow label="Gzip compression" hint="mod_deflate for text, CSS, JS, SVG" checked={gzip} onChange={setGzip} />
              <ToggleRow label="Browser caching" hint="Expires headers for assets" checked={caching} onChange={setCaching} />
            </div>
          </div>

          <div>
            <p className="mb-1.5 text-[13px] font-medium text-foreground/80">Security</p>
            <div className="divide-y divide-border/60 rounded-xl border border-border px-4">
              <ToggleRow label="Security headers" hint="nosniff, SAMEORIGIN, CSP and more" checked={secHeaders} onChange={setSecHeaders} />
              <ToggleRow label="Disable directory listing" checked={noListing} onChange={setNoListing} />
              <ToggleRow label="Hotlink protection" hint="Block image embeds on other sites" checked={hotlink} onChange={setHotlink} />
              {hotlink && (
                <div className="py-2">
                  <Label className="mb-1 block text-xs text-muted-foreground">Your domain</Label>
                  <Input value={hotlinkDomain} onChange={(e) => setHotlinkDomain(e.target.value)} className="font-mono text-xs" placeholder="example.com" />
                </div>
              )}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">404 page</Label>
              <Input value={err404} onChange={(e) => setErr404(e.target.value)} className="font-mono text-xs" placeholder="/404.html" />
            </div>
            <div>
              <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">500 page</Label>
              <Input value={err500} onChange={(e) => setErr500(e.target.value)} className="font-mono text-xs" placeholder="/500.html" />
            </div>
          </div>

          <div>
            <div className="mb-2 flex items-center justify-between">
              <Label className="text-[13px] font-medium text-foreground/80">Custom rewrite rules</Label>
              <button
                type="button"
                onClick={() => setRules((p) => [...p, { id: ruleSeq++, from: "", to: "", permanent: true }])}
                className="inline-flex items-center gap-1 rounded-lg border border-border px-2.5 py-1 text-xs font-semibold text-muted-foreground transition hover:border-primary/40 hover:text-foreground"
              >
                <Plus className="h-3.5 w-3.5" /> Add
              </button>
            </div>
            <div className="space-y-2">
              {rules.map((r) => (
                <div key={r.id} className="flex items-center gap-2">
                  <Input value={r.from} onChange={(e) => setRules((p) => p.map((x) => (x.id === r.id ? { ...x, from: e.target.value } : x)))} placeholder="^old/?$" className="font-mono text-xs" />
                  <Input value={r.to} onChange={(e) => setRules((p) => p.map((x) => (x.id === r.id ? { ...x, to: e.target.value } : x)))} placeholder="/new" className="font-mono text-xs" />
                  <label className="flex shrink-0 items-center gap-1 text-xs text-muted-foreground">
                    <input type="checkbox" checked={r.permanent} onChange={(e) => setRules((p) => p.map((x) => (x.id === r.id ? { ...x, permanent: e.target.checked } : x)))} className="accent-current" />
                    301
                  </label>
                  <button
                    type="button"
                    onClick={() => setRules((p) => p.filter((x) => x.id !== r.id))}
                    aria-label="Remove rule"
                    className="shrink-0 rounded-lg p-1.5 text-muted-foreground transition hover:bg-red-500/10 hover:text-red-500"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              ))}
              {rules.length === 0 && <p className="text-xs text-muted-foreground">No custom rules.</p>}
            </div>
          </div>

          <ActionButton busy={false} disabled={!trial.canUse} onClick={download}>
            <Download className="h-4 w-4" /> Download .htaccess
          </ActionButton>
          {!isPro && (
            <p className="text-xs text-muted-foreground">
              {trial.left} of {TOOL_TRIAL_LIMIT} free generations left - runs fully in your browser, nothing is uploaded.
            </p>
          )}
        </div>

        <div className="rounded-2xl border border-border bg-card p-5">
          <div className="mb-3 flex items-center justify-between">
            <p className="text-[13px] font-medium text-foreground/80">Live preview: .htaccess</p>
            <button
              type="button"
              onClick={copy}
              disabled={!trial.canUse}
              className={cn(
                "inline-flex items-center gap-1.5 rounded-xl border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition hover:border-primary/40 hover:text-foreground",
                !trial.canUse && "cursor-not-allowed opacity-50",
              )}
            >
              <Copy className="h-3.5 w-3.5" /> Copy
            </button>
          </div>
          <pre className="max-h-[720px] overflow-auto whitespace-pre rounded-xl bg-zinc-950 p-4 font-mono text-xs leading-relaxed text-zinc-100">
            {out}
          </pre>
          <p className="mt-3 text-xs text-muted-foreground">
            Every block is wrapped in IfModule checks, so missing Apache modules will not break your site. Upload to your web root as <span className="font-mono">.htaccess</span>.
          </p>
        </div>
      </div>
    </ToolPageShell>
  );
}
