// /tools/github-actions-generator - Build a CI workflow YAML visually:
// triggers (push, PR, schedule), language matrix (Node/Python/Go/Docker),
// steps (checkout, setup, cache, test, build, docker push). Live preview,
// copy + download. 100% client-side.

import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Copy, Download } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { downloadBlob } from "@/lib/logo-builder";
import { usePlan } from "@/hooks/usePlan";
import { useToolTrial, TOOL_TRIAL_LIMIT } from "@/lib/tool-trial";
import { getToolSeo } from "@/lib/tool-seo";
import { getToolSeoMeta } from "@/lib/tool-seo-meta";
import ToolPageShell, { ActionButton, TrialUpsell } from "@/components/ToolPageShell";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

export const Route = createFileRoute("/tools_/github-actions-generator")({
  head: () => {
    const seo = getToolSeoMeta("github-actions-generator");
    return { meta: [{ title: seo.title }, { name: "description", content: seo.metaDescription }] };
  },
  component: GithubActionsGeneratorTool,
});

type Lang = "node" | "python" | "go" | "docker";

const LANG_DEFAULTS: Record<Lang, { version: string; install: string; test: string; build: string }> = {
  node: { version: "22", install: "npm ci", test: "npm test", build: "npm run build" },
  python: { version: "3.12", install: "pip install -r requirements.txt", test: "pytest", build: "python -m build" },
  go: { version: "1.23", install: "go mod download", test: "go test ./...", build: "go build ./..." },
  docker: { version: "", install: "", test: "", build: "docker build -t ${{ github.repository }} ." },
};

function ToggleRow({ label, hint, checked, onChange }: { label: string; hint?: string; checked: boolean; onChange: (v: boolean) => void }) {
  return (
    <div className="flex items-center justify-between gap-3 py-1.5">
      <div>
        <p className="text-[13px] font-medium">{label}</p>
        {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
      </div>
      <Switch checked={checked} onCheckedChange={onChange} />
    </div>
  );
}

interface Opts {
  name: string; lang: Lang; version: string; matrix: string; matrixOn: boolean;
  push: boolean; pushBranches: string; pr: boolean; schedule: boolean; cron: string; manual: boolean;
  checkout: boolean; cache: boolean; installCmd: string; testCmd: string; buildCmd: string;
  dockerPush: boolean; imageName: string;
}

function buildYaml(o: Opts): string {
  const L: string[] = [];
  L.push("# Generated by IconVault Actions Generator");
  L.push(`name: ${o.name.trim() || "CI"}`);
  L.push("");
  L.push("on:");
  if (o.push) {
    L.push("  push:");
    const branches = o.pushBranches.split(/[\n,]+/).map((s) => s.trim()).filter(Boolean);
    if (branches.length) {
      L.push("    branches:");
      for (const b of branches) L.push(`      - ${JSON.stringify(b)}`);
    }
  }
  if (o.pr) L.push("  pull_request:");
  if (o.schedule) {
    L.push("  schedule:");
    L.push(`    - cron: ${JSON.stringify(o.cron.trim() || "0 6 * * 1")}`);
  }
  if (o.manual) L.push("  workflow_dispatch:");
  L.push("");
  L.push("jobs:");
  L.push("  build:");
  L.push("    runs-on: ubuntu-latest");

  const versions = o.matrixOn
    ? o.matrix.split(/[\n,]+/).map((s) => s.trim()).filter(Boolean)
    : [o.version.trim()];
  if (o.matrixOn && versions.length > 0) {
    L.push("    strategy:");
    L.push("      matrix:");
    L.push(`        version: [${versions.map((v) => JSON.stringify(v)).join(", ")}]`);
    L.push("");
  }

  const versionRef = o.matrixOn ? "${{ matrix.version }}" : o.version.trim() || LANG_DEFAULTS[o.lang].version;
  L.push("    steps:");
  if (o.checkout) {
    L.push("      - name: Checkout");
    L.push("        uses: actions/checkout@v4");
  }

  if (o.lang === "node") {
    L.push("      - name: Setup Node.js");
    L.push("        uses: actions/setup-node@v4");
    L.push("        with:");
    L.push(`          node-version: ${versionRef}`);
    if (o.cache) L.push('          cache: "npm"');
  } else if (o.lang === "python") {
    L.push("      - name: Setup Python");
    L.push("        uses: actions/setup-python@v5");
    L.push("        with:");
    L.push(`          python-version: ${versionRef}`);
    if (o.cache) L.push('          cache: "pip"');
  } else if (o.lang === "go") {
    L.push("      - name: Setup Go");
    L.push("        uses: actions/setup-go@v5");
    L.push("        with:");
    L.push(`          go-version: ${versionRef}`);
    if (o.cache) L.push("          cache: true");
  } else {
    L.push("      - name: Set up Docker Buildx");
    L.push("        uses: docker/setup-buildx-action@v3");
  }

  const run = (name: string, cmd: string) => {
    L.push(`      - name: ${name}`);
    L.push(`        run: ${cmd}`);
  };
  if (o.installCmd.trim() && o.lang !== "docker") run("Install dependencies", o.installCmd.trim());
  if (o.testCmd.trim() && o.lang !== "docker") run("Run tests", o.testCmd.trim());
  if (o.buildCmd.trim() && o.lang !== "docker") run("Build", o.buildCmd.trim());

  if (o.lang === "docker" || o.dockerPush) {
    L.push("      - name: Log in to Docker Hub");
    L.push("        uses: docker/login-action@v3");
    L.push("        with:");
    L.push("          username: ${{ secrets.DOCKERHUB_USERNAME }}");
    L.push("          password: ${{ secrets.DOCKERHUB_TOKEN }}");
    L.push("      - name: Build and push image");
    L.push("        uses: docker/build-push-action@v6");
    L.push("        with:");
    L.push("          context: .");
    L.push("          push: true");
    L.push(`          tags: ${(o.imageName.trim() || "myuser/myapp")}:latest`);
  }

  L.push("");
  return L.join("\n");
}

async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

function GithubActionsGeneratorTool() {
  const { isPro } = usePlan();
  const trial = useToolTrial("github-actions-generator", isPro);
  const seo = getToolSeo("github-actions-generator");

  const [name, setName] = useState("CI");
  const [lang, setLang] = useState<Lang>("node");
  const [version, setVersion] = useState(LANG_DEFAULTS.node.version);
  const [matrixOn, setMatrixOn] = useState(false);
  const [matrix, setMatrix] = useState("20, 22");
  const [push, setPush] = useState(true);
  const [pushBranches, setPushBranches] = useState("main");
  const [pr, setPr] = useState(true);
  const [schedule, setSchedule] = useState(false);
  const [cron, setCron] = useState("0 6 * * 1");
  const [manual, setManual] = useState(true);
  const [checkout, setCheckout] = useState(true);
  const [cache, setCache] = useState(true);
  const [installCmd, setInstallCmd] = useState(LANG_DEFAULTS.node.install);
  const [testCmd, setTestCmd] = useState(LANG_DEFAULTS.node.test);
  const [buildCmd, setBuildCmd] = useState(LANG_DEFAULTS.node.build);
  const [dockerPush, setDockerPush] = useState(false);
  const [imageName, setImageName] = useState("myuser/myapp");

  const pickLang = (l: Lang) => {
    setLang(l);
    setVersion(LANG_DEFAULTS[l].version);
    setInstallCmd(LANG_DEFAULTS[l].install);
    setTestCmd(LANG_DEFAULTS[l].test);
    setBuildCmd(LANG_DEFAULTS[l].build);
    if (l === "docker") setDockerPush(true);
  };

  const yml = useMemo(
    () => buildYaml({ name, lang, version, matrix, matrixOn, push, pushBranches, pr, schedule, cron, manual, checkout, cache, installCmd, testCmd, buildCmd, dockerPush, imageName }),
    [name, lang, version, matrix, matrixOn, push, pushBranches, pr, schedule, cron, manual, checkout, cache, installCmd, testCmd, buildCmd, dockerPush, imageName],
  );

  const copy = async () => {
    if (!trial.canUse) return;
    const ok = await copyToClipboard(yml);
    if (ok) {
      trial.recordUse();
      toast.success("Workflow YAML copied.");
    } else toast.error("Could not copy to clipboard.");
  };

  const download = () => {
    if (!trial.canUse) return;
    downloadBlob(new Blob([yml], { type: "text/yaml" }), "ci.yml");
    trial.recordUse();
    toast.success("ci.yml downloaded.");
  };

  return (
    <ToolPageShell toolId="github-actions-generator" seo={seo} trial={trial} isPro={isPro}>
      <TrialUpsell toolName="Actions Generator" left={trial.left} />

      <div className="grid gap-6 lg:grid-cols-[380px_1fr]">
        <div className="space-y-5 rounded-2xl border border-border bg-card p-5">
          <div className="grid grid-cols-2 gap-3">
            <div className="col-span-2">
              <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Workflow name</Label>
              <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="CI" />
            </div>
            <div>
              <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Language</Label>
              <Select value={lang} onValueChange={(v) => pickLang(v as Lang)}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="node">Node.js</SelectItem>
                  <SelectItem value="python">Python</SelectItem>
                  <SelectItem value="go">Go</SelectItem>
                  <SelectItem value="docker">Docker</SelectItem>
                </SelectContent>
              </Select>
            </div>
            {lang !== "docker" && (
              <div>
                <Label className="mb-1.5 block text-[13px] font-medium text-foreground/80">Version</Label>
                <Input value={version} onChange={(e) => setVersion(e.target.value)} className="font-mono" />
              </div>
            )}
          </div>

          <div>
            <p className="mb-1.5 text-[13px] font-medium text-foreground/80">Triggers</p>
            <div className="divide-y divide-border/60 rounded-xl border border-border px-4">
              <ToggleRow label="On push" checked={push} onChange={setPush} />
              {push && (
                <div className="py-2">
                  <Label className="mb-1 block text-xs text-muted-foreground">Branches (comma separated)</Label>
                  <Input value={pushBranches} onChange={(e) => setPushBranches(e.target.value)} className="font-mono text-xs" placeholder="main" />
                </div>
              )}
              <ToggleRow label="On pull request" checked={pr} onChange={setPr} />
              <ToggleRow label="On schedule" hint="Cron expression, UTC" checked={schedule} onChange={setSchedule} />
              {schedule && (
                <div className="py-2">
                  <Input value={cron} onChange={(e) => setCron(e.target.value)} className="font-mono text-xs" placeholder="0 6 * * 1" />
                </div>
              )}
              <ToggleRow label="Manual run" hint="workflow_dispatch button" checked={manual} onChange={setManual} />
            </div>
          </div>

          <div>
            <p className="mb-1.5 text-[13px] font-medium text-foreground/80">Steps</p>
            <div className="divide-y divide-border/60 rounded-xl border border-border px-4">
              <ToggleRow label="Checkout code" checked={checkout} onChange={setCheckout} />
              {lang !== "docker" && <ToggleRow label="Dependency cache" checked={cache} onChange={setCache} />}
              <ToggleRow label="Version matrix" hint="Test across versions, comma separated" checked={matrixOn} onChange={setMatrixOn} />
              {matrixOn && (
                <div className="py-2">
                  <Input value={matrix} onChange={(e) => setMatrix(e.target.value)} className="font-mono text-xs" placeholder="20, 22" />
                </div>
              )}
              <ToggleRow label="Push Docker image" hint="Uses DOCKERHUB secrets" checked={dockerPush} onChange={setDockerPush} />
            </div>
          </div>

          {lang !== "docker" && (
            <div className="grid gap-2">
              <div>
                <Label className="mb-1 block text-xs text-muted-foreground">Install command</Label>
                <Input value={installCmd} onChange={(e) => setInstallCmd(e.target.value)} className="font-mono text-xs" />
              </div>
              <div>
                <Label className="mb-1 block text-xs text-muted-foreground">Test command</Label>
                <Input value={testCmd} onChange={(e) => setTestCmd(e.target.value)} className="font-mono text-xs" />
              </div>
              <div>
                <Label className="mb-1 block text-xs text-muted-foreground">Build command</Label>
                <Input value={buildCmd} onChange={(e) => setBuildCmd(e.target.value)} className="font-mono text-xs" />
              </div>
            </div>
          )}
          {dockerPush && (
            <div>
              <Label className="mb-1 block text-xs text-muted-foreground">Docker image name</Label>
              <Input value={imageName} onChange={(e) => setImageName(e.target.value)} className="font-mono text-xs" placeholder="myuser/myapp" />
            </div>
          )}

          <ActionButton busy={false} disabled={!trial.canUse} onClick={download}>
            <Download className="h-4 w-4" /> Download ci.yml
          </ActionButton>
          {!isPro && (
            <p className="text-xs text-muted-foreground">
              {trial.left} of {TOOL_TRIAL_LIMIT} free generations left - runs fully in your browser, nothing is uploaded.
            </p>
          )}
        </div>

        <div className="rounded-2xl border border-border bg-card p-5">
          <div className="mb-3 flex items-center justify-between">
            <p className="text-[13px] font-medium text-foreground/80">Live preview: .github/workflows/ci.yml</p>
            <button
              type="button"
              onClick={copy}
              disabled={!trial.canUse}
              className={cn(
                "inline-flex items-center gap-1.5 rounded-xl border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition hover:border-primary/40 hover:text-foreground",
                !trial.canUse && "cursor-not-allowed opacity-50",
              )}
            >
              <Copy className="h-3.5 w-3.5" /> Copy
            </button>
          </div>
          <pre className="max-h-[720px] overflow-auto whitespace-pre rounded-xl bg-zinc-950 p-4 font-mono text-xs leading-relaxed text-zinc-100">
            {yml}
          </pre>
          <p className="mt-3 text-xs text-muted-foreground">
            Save as <span className="font-mono">.github/workflows/ci.yml</span> in your repo. Docker push needs
            <span className="font-mono"> DOCKERHUB_USERNAME</span> and <span className="font-mono">DOCKERHUB_TOKEN</span> repo secrets.
          </p>
        </div>
      </div>
    </ToolPageShell>
  );
}
