// /tools/env-validator - Validate .env files: syntax, duplicates, secret
// detection, empty values. Generates a safe .env.example. 100% in-browser.

import { useCallback, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, CheckCircle2, Copy, Download, Eraser, FileKey } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { downloadBlob } from "@/lib/logo-builder";
import { usePlan } from "@/hooks/usePlan";
import { useToolTrial, TOOL_TRIAL_LIMIT } from "@/lib/tool-trial";
import { getToolSeo } from "@/lib/tool-seo";
import { getToolSeoMeta } from "@/lib/tool-seo-meta";
import ToolPageShell, { ActionButton, TrialUpsell } from "@/components/ToolPageShell";

export const Route = createFileRoute("/tools_/env-validator")({
  head: () => {
    const seo = getToolSeoMeta("env-validator");
    const canonical = "https://iconvault.site/tools/env-validator";
    return {
      meta: [
        { title: seo.title },
        { name: "description", content: seo.metaDescription },
        { property: "og:title", content: seo.title },
        { property: "og:description", content: seo.metaDescription },
        { property: "og:type", content: "website" },
        { property: "og:url", content: canonical },
        { name: "twitter:card", content: "summary" },
        { name: "twitter:title", content: seo.title },
        { name: "twitter:description", content: seo.metaDescription },
      ],
      links: [{ rel: "canonical", href: canonical }],
    };
  },
  component: EnvValidatorTool,
});

const SAMPLE = `# App config
APP_NAME=iconvault
APP_ENV=production
DATABASE_URL=postgres://user:pass@localhost:5432/app
API_SECRET_KEY=sk_live_9f8e7d6c5b4a
STRIPE_SECRET_KEY=sk_test_abc123
EMPTY_VALUE=
lowercase_key=oops
API_SECRET_KEY=duplicate_key
MALFORMED LINE
QUOTED="value with spaces"
SINGLE='another value'
# comment lines are ignored
PORT=3000`;

interface Issue {
  line: number;
  kind: "error" | "warning";
  message: string;
}

interface EnvVar {
  key: string;
  value: string;
  line: number;
  quoted: boolean;
}

const SECRET_HINTS = ["SECRET", "PASSWORD", "PASSWD", "TOKEN", "PRIVATE", "API_KEY", "ACCESS_KEY"];
const VALID_KEY = /^[A-Za-z_][A-Za-z0-9_]*$/;

function parseEnv(src: string): { vars: EnvVar[]; issues: Issue[] } {
  const vars: EnvVar[] = [];
  const issues: Issue[] = [];
  const seen = new Map<string, number>();
  const lines = src.split("\n");

  lines.forEach((raw, idx) => {
    const lineNo = idx + 1;
    const line = raw.trim();
    if (!line || line.startsWith("#")) return;

    const eq = raw.indexOf("=");
    if (eq === -1) {
      issues.push({ line: lineNo, kind: "error", message: "No '=' found - this line will be ignored by most parsers." });
      return;
    }
    const rawKey = raw.slice(0, eq).trim();
    let value = raw.slice(eq + 1).trim();
    let quoted = false;
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'")))
    ) {
      quoted = true;
      value = value.slice(1, -1);
    }

    if (!VALID_KEY.test(rawKey)) {
      issues.push({ line: lineNo, kind: "error", message: `Invalid key name "${rawKey}" - use letters, digits and underscores only.` });
      return;
    }
    const key = rawKey;

    if (seen.has(key)) {
      issues.push({ line: lineNo, kind: "error", message: `Duplicate key "${key}" - first defined on line ${seen.get(key)}.` });
    } else {
      seen.set(key, lineNo);
    }

    if (/[a-z]/.test(key)) {
      issues.push({ line: lineNo, kind: "warning", message: `Key "${key}" is not uppercase - convention is SCREAMING_SNAKE_CASE.` });
    }
    if (value === "") {
      issues.push({ line: lineNo, kind: "warning", message: `Key "${key}" has an empty value.` });
    }
    if (!quoted && /\s/.test(value) && value !== "") {
      issues.push({ line: lineNo, kind: "warning", message: `Value of "${key}" contains spaces - quote it to be safe.` });
    }
    if (SECRET_HINTS.some((h) => key.toUpperCase().includes(h)) && value !== "") {
      issues.push({
        line: lineNo,
        kind: "warning",
        message: `"${key}" looks like a secret - make sure this file is in .gitignore and never committed.`,
      });
    }

    vars.push({ key, value, line: lineNo, quoted });
  });

  return { vars, issues };
}

function buildExample(vars: EnvVar[]): string {
  const seen = new Set<string>();
  const out: string[] = ["# Generated by IconVault Env Validator", "# Fill in real values - never commit real secrets.", ""];
  for (const v of vars) {
    if (seen.has(v.key)) continue;
    seen.add(v.key);
    const looksSecret = SECRET_HINTS.some((h) => v.key.toUpperCase().includes(h));
    out.push(`${v.key}=${looksSecret ? "your_" + v.key.toLowerCase() + "_here" : ""}`);
  }
  return out.join("\n") + "\n";
}

function EnvValidatorTool() {
  const { isPro } = usePlan();
  const trial = useToolTrial("env-validator", isPro);
  const seo = getToolSeo("env-validator");

  const [input, setInput] = useState(SAMPLE);
  const [result, setResult] = useState<{ vars: EnvVar[]; issues: Issue[] } | null>(null);
  const [busy, setBusy] = useState(false);

  const run = useCallback(() => {
    if (!input.trim() || busy || !trial.canUse) return;
    setBusy(true);
    try {
      setResult(parseEnv(input));
      trial.recordUse();
      toast.success("Validation complete");
    } finally {
      setBusy(false);
    }
  }, [input, busy, trial]);

  const example = useMemo(() => (result ? buildExample(result.vars) : ""), [result]);

  const copyExample = useCallback(async () => {
    if (!example) return;
    try {
      await navigator.clipboard.writeText(example);
      toast.success(".env.example copied");
    } catch {
      toast.error("Copy failed in this browser.");
    }
  }, [example]);

  const downloadExample = useCallback(() => {
    if (!example) return;
    downloadBlob(new Blob([example], { type: "text/plain" }), ".env.example");
    toast.success(".env.example downloaded");
  }, [example]);

  const errors = result?.issues.filter((i) => i.kind === "error") ?? [];
  const warnings = result?.issues.filter((i) => i.kind === "warning") ?? [];

  return (
    <ToolPageShell toolId="env-validator" seo={seo} trial={trial} isPro={isPro}>
      <TrialUpsell toolName="Env Validator" left={trial.left} />

      <div className="grid gap-6 lg:grid-cols-[320px_1fr]">
        <div className="space-y-5 rounded-2xl border border-border bg-card p-5">
          <div className="flex items-start gap-3 rounded-xl border border-border bg-background p-3.5">
            <FileKey className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
            <p className="text-xs leading-relaxed text-muted-foreground">
              Paste your <span className="font-semibold text-foreground">.env</span> contents. The
              validator checks syntax, duplicate keys, empty values and flags anything that looks
              like a committed secret. Nothing is uploaded.
            </p>
          </div>

          <ActionButton busy={busy} disabled={!input.trim() || !trial.canUse} onClick={run}>
            {busy ? "Validating..." : "Validate .env"}
          </ActionButton>
          {!isPro && (
            <p className="text-xs text-muted-foreground">
              {trial.left} of {TOOL_TRIAL_LIMIT} free runs left.
            </p>
          )}
          <button
            type="button"
            onClick={() => {
              setInput("");
              setResult(null);
            }}
            className="flex w-full items-center justify-center gap-1.5 rounded-xl border border-border px-3.5 py-2 text-sm font-semibold text-muted-foreground transition hover:border-primary/40 hover:text-foreground"
          >
            <Eraser className="h-4 w-4" /> Clear
          </button>
        </div>

        <div className="space-y-4">
          <div className="rounded-2xl border border-border bg-card p-5">
            <p className="mb-2 text-[13px] font-medium text-foreground/80">.env contents</p>
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              spellCheck={false}
              placeholder="KEY=value&#10;# comments are ignored"
              className="h-52 w-full resize-y rounded-xl border border-border bg-background p-3 font-mono text-[13px] leading-relaxed outline-none focus:border-primary/60"
            />
          </div>

          {result && (
            <>
              <div className="grid gap-4 sm:grid-cols-3">
                <div className="rounded-2xl border border-border bg-card p-4">
                  <p className="text-xs text-muted-foreground">Variables found</p>
                  <p className="text-lg font-bold">{result.vars.length}</p>
                </div>
                <div className="rounded-2xl border border-border bg-card p-4">
                  <p className="text-xs text-muted-foreground">Errors</p>
                  <p className={cn("text-lg font-bold", errors.length > 0 ? "text-red-500" : "text-green-500")}>
                    {errors.length}
                  </p>
                </div>
                <div className="rounded-2xl border border-border bg-card p-4">
                  <p className="text-xs text-muted-foreground">Warnings</p>
                  <p className={cn("text-lg font-bold", warnings.length > 0 ? "text-amber-500" : "text-green-500")}>
                    {warnings.length}
                  </p>
                </div>
              </div>

              <div className="rounded-2xl border border-border bg-card p-5">
                <p className="mb-3 text-[13px] font-medium text-foreground/80">Issues</p>
                {result.issues.length === 0 ? (
                  <p className="flex items-center gap-2 text-sm font-medium text-green-600 dark:text-green-400">
                    <CheckCircle2 className="h-5 w-5" /> Clean - no errors or warnings found.
                  </p>
                ) : (
                  <ul className="space-y-2">
                    {result.issues.map((iss, i) => (
                      <li
                        key={i}
                        className={cn(
                          "flex items-start gap-2.5 rounded-xl border p-3 text-sm",
                          iss.kind === "error"
                            ? "border-red-500/30 bg-red-500/5"
                            : "border-amber-500/30 bg-amber-500/5",
                        )}
                      >
                        <AlertTriangle
                          className={cn(
                            "mt-0.5 h-4 w-4 shrink-0",
                            iss.kind === "error" ? "text-red-500" : "text-amber-500",
                          )}
                        />
                        <span>
                          <span className="font-mono text-xs text-muted-foreground">line {iss.line} - </span>
                          {iss.message}
                        </span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              <div className="rounded-2xl border border-border bg-card p-5">
                <div className="mb-2 flex items-center justify-between">
                  <p className="text-[13px] font-medium text-foreground/80">
                    Generated .env.example <span className="text-muted-foreground">(safe to commit)</span>
                  </p>
                  <div className="flex gap-2">
                    <button
                      type="button"
                      onClick={copyExample}
                      className="flex items-center gap-1.5 rounded-lg border border-border px-2.5 py-1.5 text-xs font-semibold transition hover:border-primary/40"
                    >
                      <Copy className="h-3.5 w-3.5" /> Copy
                    </button>
                    <button
                      type="button"
                      onClick={downloadExample}
                      className="flex items-center gap-1.5 rounded-lg border border-border px-2.5 py-1.5 text-xs font-semibold transition hover:border-primary/40"
                    >
                      <Download className="h-3.5 w-3.5" /> Download
                    </button>
                  </div>
                </div>
                <pre className="max-h-56 overflow-auto rounded-xl border border-border bg-background p-3 font-mono text-[13px] leading-relaxed">
                  {example}
                </pre>
              </div>
            </>
          )}
        </div>
      </div>
    </ToolPageShell>
  );
}
