import { useCallback, useEffect, useRef, useState } from "react";
import { loadIconData, type IconifyIconData } from "@/lib/iconify";
import { iconDataToSvg } from "@/lib/icon-svg";
import { cn } from "@/lib/utils";

/**
 * One shared IntersectionObserver for every ReliableIcon on the page,
 * instead of one observer per icon. Elements register a one-shot callback;
 * once visible the element is unobserved and its callback dropped.
 * Lazy-load behavior is identical to the old per-icon observer.
 */
const inViewCallbacks = new Map<Element, () => void>();
let sharedObserver: IntersectionObserver | null = null;

const getSharedObserver = (): IntersectionObserver => {
  if (!sharedObserver) {
    sharedObserver = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            const cb = inViewCallbacks.get(entry.target);
            if (cb) {
              inViewCallbacks.delete(entry.target);
              sharedObserver?.unobserve(entry.target);
              cb();
            }
          }
        }
      },
      { rootMargin: "600px 0px" },
    );
  }
  return sharedObserver;
};

const useInView = (
  ref: { current: Element | null },
  priority: boolean,
  onVisible: () => void,
): void => {
  useEffect(() => {
    if (priority) {
      onVisible();
      return;
    }
    const element = ref.current;
    if (!element || typeof IntersectionObserver === "undefined") {
      onVisible();
      return;
    }
    inViewCallbacks.set(element, onVisible);
    getSharedObserver().observe(element);
    return () => {
      inViewCallbacks.delete(element);
      sharedObserver?.unobserve(element);
    };
  }, [priority, ref, onVisible]);
};

interface ReliableIconProps {
  prefix: string;
  name: string;
  alt?: string;
  className?: string;
  width?: number;
  height?: number;
  color?: string;
  priority?: boolean;
}

type FallbackIconData = IconifyIconData & {
  left?: number;
  top?: number;
  rotate?: number;
  hFlip?: boolean;
  vFlip?: boolean;
};

/**
 * Reliable icon renderer.
 *
 * Primary path: request Iconify's already-generated SVG. This is important
 * because Iconify applies icon viewBox offsets, rotations and flips correctly.
 * A raw Iconify JSON body is only used as a second-level fallback.
 *
 * This avoids the two common failure modes we were seeing:
 * 1) broken <img> placeholders when an upstream/server route returns an error
 * 2) partially clipped icons when raw JSON is rendered without left/top or
 *    transformation metadata.
 */
export const ReliableIcon = ({
  prefix,
  name,
  alt = name,
  className,
  width = 24,
  height = 24,
  color,
  priority = false,
}: ReliableIconProps) => {
  const holderRef = useRef<HTMLSpanElement>(null);
  const [shouldLoad, setShouldLoad] = useState(priority);
  const [svg, setSvg] = useState<string | null>(null);
  const [data, setData] = useState<FallbackIconData | null>(null);
  const [failed, setFailed] = useState(false);

  const handleVisible = useCallback(() => setShouldLoad(true), []);
  useInView(holderRef, priority, handleVisible);

  useEffect(() => {
    if (!shouldLoad || !prefix || !name) return;

    let alive = true;
    setFailed(false);
    setSvg(null);
    setData(null);

    const load = async () => {
      try {
        // Single deduped fetch: the CDN race already tries every mirror, so a
        // failed load is retried by the caller, not duplicated here.
        const icon = (await loadIconData(prefix, name)) as FallbackIconData;
        if (!alive) return;
        try {
          // The generated SVG path is the most reliable representation because
          // Iconify applies all icon-set geometry and transformations for us.
          setSvg(iconDataToSvg(icon, { width, height, ...(color ? { color } : {}) }));
        } catch {
          // Raw JSON body as the second-level fallback (offsets/transforms
          // applied from the icon metadata).
          setData(icon);
        }
      } catch {
        if (alive) setFailed(true);
      }
    };

    void load();

    return () => {
      alive = false;
    };
  }, [name, prefix, shouldLoad, width, height, color]);

  const left = data?.left ?? 0;
  const top = data?.top ?? 0;
  const viewBoxWidth = data?.width || 24;
  const viewBoxHeight = data?.height || 24;

  let fallbackTransform = "";
  if (data?.hFlip) fallbackTransform += "scale(-1,1) ";
  if (data?.vFlip) fallbackTransform += "scale(1,-1) ";
  if (data?.rotate) {
    const turns = ((data.rotate % 4) + 4) % 4;
    fallbackTransform += `rotate(${turns * 90}deg) `;
  }

  return (
    <span
      ref={holderRef}
      className={cn(
        "inline-flex shrink-0 items-center justify-center",
        // Styles generated by Iconify's SVG endpoint.
        "[&>svg]:block [&>svg]:h-full [&>svg]:w-full",
        className,
      )}
      style={{ color, width, height }}
      role={alt ? "img" : undefined}
      aria-label={alt || undefined}
      aria-busy={shouldLoad && !svg && !data && !failed ? true : undefined}
    >
      {svg ? (
        <span
          className="block h-full w-full [&>svg]:block [&>svg]:h-full [&>svg]:w-full [&>svg]:max-h-full [&>svg]:max-w-full"
          dangerouslySetInnerHTML={{ __html: svg }}
          aria-hidden={!alt}
        />
      ) : data ? (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width={width}
          height={height}
          viewBox={`${left} ${top} ${viewBoxWidth} ${viewBoxHeight}`}
          focusable="false"
          aria-hidden={!alt}
          className="block h-full w-full"
          style={{
            transform: fallbackTransform || undefined,
            transformOrigin: "center",
            color,
          }}
          dangerouslySetInnerHTML={{ __html: data.body }}
        />
      ) : failed ? (
        <span className="grid h-5 w-5 place-items-center rounded-md border border-border/60 bg-muted/40" aria-hidden="true">
          <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground/50" />
        </span>
      ) : shouldLoad ? (
        <span className="block h-5 w-5 animate-pulse rounded-md bg-current/10" aria-hidden="true" />
      ) : null}
    </span>
  );
};

export default ReliableIcon;
