// ToolIcon: maps catalog icon keys to lucide components.
// Split out of ToolPageShell so the /tools hub can render icons without
// pulling the full ToolPageShell (and tool-catalog) into the client entry.

import type { ReactNode } from "react";
import {
  Atom,
  Barcode,
  Binary,
  Blocks,
  Blend,
  Bot,
  Braces,
  Camera,
  CaseUpper,
  Chrome,
  Circle,
  ClipboardPaste,
  Clock,
  Code,
  Columns2,
  Columns3,
  Contrast,
  Crop,
  Diff,
  Eraser,
  EyeOff,
  Figma,
  FileImage,
  FileText,
  Film,
  Fingerprint,
  Frame,
  GraduationCap,
  Grid2x2,
  Hash,
  IdCard,
  Key,
  Layers,
  LayoutGrid,
  ListX,
  Lock,
  MapPin,
  Minimize2,
  Network,
  Package,
  Palette,
  BarChart3,
  PenLine,
  Pilcrow,
  Pipette,
  QrCode,
  RefreshCcw,
  Regex,
  RotateCw,
  Scaling,
  ScanLine,
  Scissors,
  Search,
  Shapes,
  Share2,
  Smile,
  Space,
  Sparkles,
  Square,
  Stamp,
  Tags,
  Terminal,
  Text,
  Type,
  Users,
  Video,
  Wand2,
  Youtube,
  Zap,
  Activity,
  AppWindow,
  ArrowDownUp,
  ArrowRightLeft,
  ArrowUpFromLine,
  AudioLines,
  AudioWaveform,
  Battery,
  Bell,
  Bug,
  Calculator,
  Compass,
  Cookie,
  CreditCard,
  CupSoda,
  Database,
  Dices,
  Flag,
  FolderOpen,
  Gamepad2,
  GitCommitHorizontal,
  Globe,
  Grid3x3,
  HardDrive,
  Languages,
  LayoutDashboard,
  Mail,
  Maximize,
  MessageCircle,
  Mic,
  MousePointer,
  Move,
  Music,
  Paintbrush,
  Piano,
  PictureInPicture2,
  Play,
  Pointer,
  Radio,
  Rocket,
  Shuffle,
  Sprout,
  TriangleAlert,
  Volume2,
  Waves,
  Image as ImageIcon,
  Link as LinkIcon,
} from "lucide-react";

export function ToolIcon({ iconKey, className }: { iconKey: string; className?: string }) {
  const map: Record<string, ReactNode> = {
    palette: <Palette className={className} />,
    shapes: <Shapes className={className} />,
    image: <ImageIcon className={className} />,
    camera: <Camera className={className} />,
    minimize: <Minimize2 className={className} />,
    youtube: <Youtube className={className} />,
    package: <Package className={className} />,
    braces: <Braces className={className} />,
    "file-image": <FileImage className={className} />,
    zap: <Zap className={className} />,
    atom: <Atom className={className} />,
    scaling: <Scaling className={className} />,
    pipette: <Pipette className={className} />,
    contrast: <Contrast className={className} />,
    blend: <Blend className={className} />,
    layers: <Layers className={className} />,
    qr: <QrCode className={className} />,
    binary: <Binary className={className} />,
    key: <Key className={className} />,
    regex: <Regex className={className} />,
    clock: <Clock className={className} />,
    link: <LinkIcon className={className} />,
    fingerprint: <Fingerprint className={className} />,
    lock: <Lock className={className} />,
    diff: <Diff className={className} />,
    hash: <Hash className={className} />,
    markdown: <Text className={className} />,
    text: <Text className={className} />,
    terminal: <Terminal className={className} />,
    figma: <Figma className={className} />,
    blocks: <Blocks className={className} />,
    chrome: <Chrome className={className} />,
    bot: <Bot className={className} />,
    users: <Users className={className} />,
    type: <Type className={className} />,
    eraser: <Eraser className={className} />,
    tags: <Tags className={className} />,
    share: <Share2 className={className} />,
    network: <Network className={className} />,
    chart: <BarChart3 className={className} />,
    search: <Search className={className} />,
    code: <Code className={className} />,
    pilcrow: <Pilcrow className={className} />,
    case: <CaseUpper className={className} />,
    "list-x": <ListX className={className} />,
    space: <Space className={className} />,
    "file-text": <FileText className={className} />,
    barcode: <Barcode className={className} />,
    crop: <Crop className={className} />,
    "refresh-ccw": <RefreshCcw className={className} />,
    "clipboard-paste": <ClipboardPaste className={className} />,
    "rotate-cw": <RotateCw className={className} />,
    circle: <Circle className={className} />,
    frame: <Frame className={className} />,
    "layout-grid": <LayoutGrid className={className} />,
    "grid-2x2": <Grid2x2 className={className} />,
    "columns-3": <Columns3 className={className} />,
    "columns-2": <Columns2 className={className} />,
    scissors: <Scissors className={className} />,
    stamp: <Stamp className={className} />,
    "map-pin": <MapPin className={className} />,
    "eye-off": <EyeOff className={className} />,
    square: <Square className={className} />,
    film: <Film className={className} />,
    video: <Video className={className} />,
    sparkles: <Sparkles className={className} />,
    "scan-line": <ScanLine className={className} />,
    smile: <Smile className={className} />,
    "wand-2": <Wand2 className={className} />,
    "id-card": <IdCard className={className} />,
    "pen-line": <PenLine className={className} />,
    "graduation-cap": <GraduationCap className={className} />,
    "activity": <Activity className={className} />,
    "app-window": <AppWindow className={className} />,
    "arrow-down-up": <ArrowDownUp className={className} />,
    "arrow-right-left": <ArrowRightLeft className={className} />,
    "arrow-up-from-line": <ArrowUpFromLine className={className} />,
    "audio-lines": <AudioLines className={className} />,
    "audio-waveform": <AudioWaveform className={className} />,
    "battery": <Battery className={className} />,
    "bell": <Bell className={className} />,
    "bug": <Bug className={className} />,
    "calculator": <Calculator className={className} />,
    "compass": <Compass className={className} />,
    "cookie": <Cookie className={className} />,
    "credit-card": <CreditCard className={className} />,
    "cup-soda": <CupSoda className={className} />,
    "database": <Database className={className} />,
    "dices": <Dices className={className} />,
    "flag": <Flag className={className} />,
    "folder-open": <FolderOpen className={className} />,
    "gamepad-2": <Gamepad2 className={className} />,
    "git-commit-horizontal": <GitCommitHorizontal className={className} />,
    "globe": <Globe className={className} />,
    "grid-3x3": <Grid3x3 className={className} />,
    "hard-drive": <HardDrive className={className} />,
    "languages": <Languages className={className} />,
    "layout-dashboard": <LayoutDashboard className={className} />,
    "mail": <Mail className={className} />,
    "maximize": <Maximize className={className} />,
    "message-circle": <MessageCircle className={className} />,
    "mic": <Mic className={className} />,
    "mouse-pointer": <MousePointer className={className} />,
    "move": <Move className={className} />,
    "music": <Music className={className} />,
    "paintbrush": <Paintbrush className={className} />,
    "piano": <Piano className={className} />,
    "picture-in-picture-2": <PictureInPicture2 className={className} />,
    "play": <Play className={className} />,
    "pointer": <Pointer className={className} />,
    "radio": <Radio className={className} />,
    "rocket": <Rocket className={className} />,
    "shuffle": <Shuffle className={className} />,
    "sprout": <Sprout className={className} />,
    "triangle-alert": <TriangleAlert className={className} />,
    "volume-2": <Volume2 className={className} />,
    "waves": <Waves className={className} />,
  };
  return <>{map[iconKey] ?? <Sparkles className={className} />}</>;
}

