// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    // Verify the user's JWT against the Supabase Auth server using the
    // service-role client. This is the most reliable server-side check: it
    // works with any API key format (no JWKS/WebCrypto dependency) and uses
    // getServerEnv so it reads Cloudflare Worker bindings correctly.
    // NOTE: must use getServerEnv (not process.env) — on Cloudflare Workers,
    // dashboard variables are worker bindings, invisible to process.env.
    const { supabaseAdmin } = await import('@/integrations/supabase/client.server');
    const { data, error } = await supabaseAdmin.auth.getUser(token);
    if (error || !data?.user?.id) {
      console.error('[Supabase] getUser failed:', error?.message ?? 'no user');
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = supabaseAdmin;
    return next({
      context: {
        supabase,
        userId: data.user.id,
        claims: { sub: data.user.id, email: data.user.email },
      },
    });
  },
);
